export type ThemeId =
  | 'sun'
  | 'moon'
  | 'flood'
  | 'fire'
  | 'dragon'
  | 'love'
  | 'princess'
  | 'death'
  | 'war'
  | 'creation'
  | 'hero'
  | 'trickster'
  | 'underworld'
  | 'beast'
  | 'magic';

export type EraId = 'ancient' | 'classical' | 'medieval' | 'modern';

export interface ThemeDef {
  id: ThemeId;
  emoji: string;
  zh: string;
  en: string;
  /** Hex glow color used behind the emoji marker. */
  color: string;
}

export interface EraDef {
  id: EraId;
  zh: string;
  en: string;
  /** Approximate years (negative = BCE). */
  range: [number, number];
}

export interface CountryCentroid {
  /** ISO 3166-1 alpha-3 (e.g. "GRC"). */
  iso: string;
  /** Numeric country code matching the world-atlas topojson `id` field. */
  numeric: string;
  zh: string;
  en: string;
  /** Geographic centroid: [longitude, latitude]. */
  lnglat: [number, number];
  /** Country flag emoji. */
  flag: string;
}

export interface Story {
  id: string;
  title: { zh: string; en: string; native?: string };
  /** ISO 3166-1 alpha-3 country code. */
  country: string;
  /** Culture / pantheon name (free text). */
  culture: { zh: string; en: string };
  era: EraId;
  themes: ThemeId[];
  /** Approximate year (negative = BCE). */
  year?: number;
  emoji: string;
  /** Optional override for glow color (otherwise derived from first theme). */
  color?: string;
  /** Geographic location: [longitude, latitude]. */
  lnglat: [number, number];
  /** Public-domain illustration URL (e.g. Wikimedia Commons). */
  image?: string;
  description: { zh: string; en: string };
  /** Whether this story was generated by Gemini at runtime. */
  generated?: boolean;
}

export interface ProjectionStateFlat {
  mode: 'flat';
}
export interface ProjectionStateGlobe {
  mode: 'globe';
  /** Spherical rotation as d3-geo [lambda, phi, gamma]. */
  rotation: [number, number, number];
}
export type ProjectionState = ProjectionStateFlat | ProjectionStateGlobe;
