// 30 个业务对象的紧凑 DSL → data/objects.json（gen-samples.js 调用）。
// 字段串：key|label|type|flags…  flags：req · len=N · min=N · max=N · opt=a/b/c · ref=source · ex=例1;例2 · at=动作（该动作时填写）· auto（提交时自动带入当前用户）· after=字段（须晚于该字段）· due（超期判定日期）· rule=文案
// 员工只出 E-编号，联系人只出职务，含「元」的字段一律带「预计」。
const F = (s) => {
  const p = s.split('|');
  const f = { key: p[0].trim(), label: p[1].trim(), type: p[2].trim(), required: false, source: '对象库' };
  const toks = [];
  (p[3] || '').trim().split(/\s+/).filter(Boolean).forEach((t) => { if (/^(req|auto|due)$/.test(t) || /^\w+=/.test(t) || !toks.length) toks.push(t); else toks[toks.length - 1] += ' ' + t; });
  toks.forEach((t) => {
    const m = t.match(/^(\w+)=(.*)$/);
    if (!m) { if (t === 'req') f.required = true; else if (t === 'auto') f.auto = true; else if (t === 'due') f.due = true; return; }
    const k = m[1], v = m[2];
    if (k === 'len' || k === 'min' || k === 'max') f[k] = Number(v);
    else if (k === 'opt') f.options = v.split('/');
    else if (k === 'ref') f.ref = v;
    else if (k === 'ex') { const xs = v.split(';').map((x) => (f.type === 'number' || f.type === 'money' || f.type === 'photo' || f.type === 'rating' ? Number(x) : x)); f.example = xs[0]; if (xs.length > 1) f.examples = xs; }
    else if (k === 'at') f.at = v;
    else if (k === 'after') f.after = v;
    else if (k === 'rule') f.rule = v;
  });
  if (f.type === 'photo' && f.max == null) f.max = 3;
  if (f.type === 'rating') { if (f.min == null) f.min = 1; if (f.max == null) f.max = 5; }
  if ((f.type === 'text') && f.len == null) f.len = 60;
  if ((f.type === 'textarea') && f.len == null) f.len = 200;
  return f;
};
const O = (o) => Object.assign({ mode: null, optional: [], roles: null, stateLabels: null, actionLabels: null, tail: null, secondLevel: null, initialRule: null, sla: null }, o, { fields: o.fields.map(F), optional: (o.optional || []).map(F) });

module.exports = [
  // ---------- 通用 9 ----------
  O({ key: 'repair', name: '报修单', arche: 'common', prefix: 'BX', verb: '报修', short: '工单', flow: 'dispatch', mode: 'accept', sla: { accept: 2 },
    ruleText: '接单约定时效 2 小时，超过标记超时', roles: { make: { submitter: '班组长', handler: '设备员', lead: '生产主管' }, flow: { submitter: '仓储员', handler: '设备员', lead: '仓配主管' }, service: { submitter: '代账会计', handler: '设备员', lead: '作业主管' } },
    fields: ['device|设备编号|ref|ref=machines req ex=@machines', 'faultType|故障类型|select|opt=机械/电气/液压/其他 req ex=机械;电气;液压', 'desc|故障描述|textarea|len=200 req ex=主轴异响，转速上不去;机械手卡滞，报警 1012;液压站压力上不去;加热区温度波动大',
      'startedAt|故障发生时间|datetime|req ex=2026-09-17 08:20', 'photo|故障照片|photo|max=3 ex=1;2', 'urgency|紧急度|select|opt=一般/紧急/停机 req ex=紧急;停机;一般', 'expectAt|期望到场时间|datetime|req after=startedAt ex=2026-09-17 14:00',
      'reporter|报修人|member|auto ex=E-003', 'handler|处理人|member|auto at=accept ex=E-122', 'result|处理结果|textarea|len=200 req at=complete ex=更换主轴轴承;清理机械手并润滑;更换液压泵密封', 'cost|维修费用（预计）|money|min=0 max=100000 at=complete ex=1200;300;2600'],
    optional: ['downtime|停机影响|select|opt=是/否 req ex=是', 'parts|备件需求|text|len=60 ex=主轴轴承 6205 ×2', 'recur|复发标记|select|opt=首次/复发 ex=首次', 'hours|维修工时（预计）|number|min=0 max=200 at=complete ex=3'] }),
  O({ key: 'expense', name: '报销单', arche: 'common', prefix: 'BS', verb: '报销', short: '报销单', flow: 'approve', secondLevel: { field: 'amount', gte: 5000, text: '报销金额（预计）≥ 5,000 元二级审批' },
    ruleText: '报销金额（预计）≥ 5,000 元进入二级审批',
    fields: ['type|费用类型|select|opt=差旅/招待/办公/交通/其他 req ex=差旅;交通;办公', 'amount|报销金额（预计）|money|req min=1 max=1000000 ex=2360;680;5800', 'date|发生日期|date|req ex=2026-09-12', 'desc|事由|textarea|len=120 req ex=赴苏州客户现场技术支持;市内送样打车;打印耗材',
      'invoice|发票张数|number|req min=1 max=50 ex=3;1;2', 'photo|发票照片|photo|max=9 ex=3;1', 'applicant|申请人|member|auto ex=E-003', 'opinion|审批意见|textarea|len=100 at=approve ex=同意'],
    optional: ['project|所属项目|text|len=60 ex=新能源电池壳体打样', 'pay|支付方式|select|opt=转账/现金 ex=转账'] }),
  O({ key: 'leave', name: '请假单', arche: 'common', prefix: 'QJ', verb: '请假', short: '请假单', flow: 'approve', ruleText: '结束时间须晚于开始时间',
    fields: ['kind|请假类型|select|opt=事假/病假/年假/调休/婚假 req ex=年假;事假;调休', 'from|开始时间|datetime|req ex=2026-09-21 08:00', 'to|结束时间|datetime|req after=from ex=2026-09-22 17:30', 'days|天数|number|req min=0.5 max=30 ex=2;1;0.5',
      'reason|事由|textarea|len=120 req ex=家中事务;就医;调休', 'handover|工作交接人|member|ref=employees ex=@employees', 'applicant|申请人|member|auto ex=E-003', 'opinion|审批意见|textarea|len=100 at=approve ex=同意'],
    optional: ['attach|证明材料|photo|max=3 ex=1', 'contact|假期联系方式|phone|ex=138 0000 0000'] }),
  O({ key: 'vehicle', name: '用车申请', arche: 'common', prefix: 'YC', verb: '用车', short: '用车单', flow: 'approve', tail: { lent: '已领用', returned: '已归还' }, ruleText: '预计归还超过约定时间标记超期',
    fields: ['purpose|用车事由|textarea|len=120 req ex=送样到客户现场;接送来访客户;采购取料', 'dest|目的地|text|len=60 req ex=苏州工业园区;杭州萧山;宁波北仑', 'from|用车开始|datetime|req ex=2026-09-18 08:30', 'to|预计归还|datetime|req after=from due ex=2026-09-18 18:00',
      'passengers|乘车人数|number|req min=1 max=7 ex=2;1;3', 'driver|是否需要司机|select|opt=是/否 req ex=否;是', 'applicant|申请人|member|auto ex=E-003', 'opinion|审批意见|textarea|len=100 at=approve ex=同意', 'mileage|行驶里程（预计）|number|min=0 max=5000 at=return ex=120'],
    optional: ['plate|指定车牌|text|len=12 ex=不指定', 'toll|路桥费（预计）|money|min=0 max=5000 at=return ex=60'] }),
  O({ key: 'training', name: '培训报名', arche: 'common', prefix: 'PX', verb: '培训报名', short: '报名单', flow: 'approve', ruleText: '培训费用（预计）大于 0 时审批人可填意见',
    fields: ['course|课程名称|text|len=60 req ex=设备点检与保养基础;安全生产培训;质量意识培训', 'date|培训日期|date|req ex=2026-09-25', 'venue|培训地点|text|len=60 ex=培训室;二号会议室', 'applicant|报名人|member|auto ex=E-003',
      'reason|报名理由|textarea|len=100 ex=岗位需要;新员工必修', 'cost|培训费用（预计）|money|min=0 max=50000 ex=0;800', 'opinion|审批意见|textarea|len=100 at=approve ex=同意'],
    optional: ['cert|是否需要证书|select|opt=是/否 ex=否', 'seats|名额|number|min=1 max=100 ex=20'] }),
  O({ key: 'meeting', name: '会议室预约', arche: 'common', prefix: 'HY', verb: '会议室预约', short: '预约单', flow: 'approve', ruleText: '结束时间须晚于开始时间',
    fields: ['room|会议室|select|opt=一号会议室/二号会议室/培训室 req ex=一号会议室;二号会议室;培训室', 'topic|会议主题|text|len=60 req ex=周生产计划会;客户来访评审;质量月度会', 'from|开始时间|datetime|req ex=2026-09-18 14:00', 'to|结束时间|datetime|req after=from ex=2026-09-18 15:30',
      'people|参会人数|number|req min=1 max=60 ex=8;12;6', 'booker|预约人|member|auto ex=E-003', 'equip|需要设备|select|opt=投影/视频会议/白板/无 ex=投影;视频会议', 'opinion|确认意见|textarea|len=100 at=approve ex=已安排'],
    optional: ['tea|茶水|select|opt=需要/不需要 ex=不需要', 'note|备注|textarea|len=100 ex=无'] }),
  O({ key: 'complaint', name: '投诉工单', arche: 'common', prefix: 'TS', verb: '投诉登记', short: '工单', flow: 'dispatch', mode: 'accept', sla: { accept: 4 }, ruleText: '接单约定时效 4 小时',
    roles: { make: { submitter: '业务员', handler: '班组长', lead: '生产主管' }, flow: { submitter: '客服专员', handler: '仓储员', lead: '仓配主管' }, service: { submitter: '客户经理', handler: '代账会计', lead: '作业主管' } },
    fields: ['customer|客户|ref|ref=customers req ex=@customers', 'channel|投诉渠道|select|opt=电话/微信/现场/邮件 req ex=微信;电话', 'content|投诉内容|textarea|len=300 req ex=交付件表面划伤，要求补发;到货延迟一天;账务凭证录入有误', 'level|严重程度|select|opt=一般/严重/重大 req ex=严重;一般',
      'photo|附件|photo|max=5 ex=1;0', 'receiver|登记人|member|auto ex=@submitter', 'handler|处理人|member|auto at=accept ex=@handler', 'result|处理结果|textarea|len=200 req at=complete ex=已补发并致歉;已协调加急;已更正并复核', 'closeType|处理结论|select|opt=已解决/部分解决/无法解决 req at=complete ex=已解决'],
    optional: ['rating|客户评分|rating|at=rate ex=5', 'comp|补偿金额（预计）|money|min=0 max=100000 at=complete ex=0', 'cause|原因分类|select|opt=质量/交期/服务/其他 at=complete ex=质量'] }),
  O({ key: 'asset', name: '固定资产领用', arche: 'common', prefix: 'GD', verb: '资产领用', short: '领用单', flow: 'approve', tail: { lent: '已领用', returned: '已归还' }, ruleText: '预计归还日期到期未归还标记超期',
    fields: ['asset|资产名称|text|len=60 req ex=笔记本电脑 T14;测量投影仪;手持扫码枪', 'assetNo|资产编号|text|len=24 req ex=ZC-2025-031;ZC-2024-118;ZC-2026-007', 'qty|数量|number|req min=1 max=20 ex=1', 'purpose|用途|textarea|len=100 req ex=外出客户现场讲解;车间首件检测;仓库盘点',
      'from|领用日期|date|req ex=2026-09-17', 'to|预计归还日期|date|after=from due ex=2026-10-17', 'applicant|领用人|member|auto ex=@submitter', 'opinion|审批意见|textarea|len=100 at=approve ex=同意', 'condition|归还状态|select|opt=完好/损坏/丢失 req at=return ex=完好'],
    optional: ['photo|资产照片|photo|max=3 ex=1', 'note|备注|textarea|len=100 ex=无'] }),
  O({ key: 'visitor', name: '访客登记单', arche: 'common', prefix: 'FK', verb: '访客登记', short: '登记单', flow: 'approve', ruleText: '预计离开须晚于来访时间',
    fields: ['company|来访单位|text|len=60 req ex=汽配一级供应商;设备厂商;审核机构', 'count|来访人数|number|req min=1 max=30 ex=2;1;4', 'purpose|来访事由|select|opt=商务洽谈/技术交流/审核/参观/其他 req ex=技术交流;审核;商务洽谈', 'visitAt|来访时间|datetime|req ex=2026-09-18 10:00',
      'leaveAt|预计离开|datetime|req after=visitAt ex=2026-09-18 12:00', 'host|接待人|member|auto ex=@submitter', 'area|到访区域|select|opt=办公区/车间/仓库/全部 req ex=车间;办公区', 'opinion|审批意见|textarea|len=100 at=approve ex=同意'],
    optional: ['nda|是否签保密协议|select|opt=是/否 ex=是', 'photo|证件照片|photo|max=2 ex=1'] }),
  // ---------- 制造 8 ----------
  O({ key: 'inspection', name: '设备点检单', arche: 'make', prefix: 'DJ', verb: '点检', short: '点检单', flow: 'inspect', initialRule: { field: 'issues', gt: 0 }, sla: { fix: 72 }, ruleText: '异常项 > 0 自动转整改，整改约定 3 天',
    roles: { make: { submitter: '操作工', handler: '设备员', handler2: '班组长', lead: '生产主管' } },
    fields: ['device|设备编号|ref|ref=machines req ex=CNC-03;CNC-01;CNC-05;PA-02', 'shift|班次|select|opt=白班/夜班 req ex=白班;夜班', 'items|点检项数|number|req min=1 max=30 ex=12', 'issues|异常项数|number|req min=0 max=30 ex=1;0;2', 'issueDesc|异常描述|textarea|len=200 ex=主轴润滑油位偏低;冷却液浓度偏低;导轨防护罩破损',
      'photo|现场照片|photo|max=3 ex=1;0', 'inspector|点检人|member|auto ex=E-009', 'fixer|整改人|member|auto at=fix ex=E-122', 'fixResult|整改结果|textarea|len=200 req at=submitFix ex=已补充润滑油并复测;已更换冷却液;已更换防护罩', 'recheckNote|复检意见|textarea|len=100 at=pass ex=复检合格'],
    optional: ['dueDays|整改期限（天）|number|min=1 max=30 ex=3', 'downtime|停机影响|select|opt=是/否 ex=否'] }),
  O({ key: 'rectify', name: '整改单', arche: 'make', prefix: 'ZG', verb: '整改登记', short: '整改单', flow: 'inspect', sla: { fix: 72 }, ruleText: '整改约定 3 天，复核关闭',
    roles: { make: { submitter: '班组长', handler: '设备员', handler2: '生产主管', lead: '生产主管' } },
    fields: ['source|问题来源|select|opt=点检/巡检/审核/客户投诉 req ex=点检;审核;巡检', 'device|设备编号|ref|ref=machines ex=CNC-02;PL-01', 'problem|问题描述|textarea|len=200 req ex=机械手定位偏差;电镀槽液温度记录缺失;冲床光电保护失效', 'photo|问题照片|photo|max=3 ex=1',
      'due|整改期限|date|req due ex=2026-09-20', 'reporter|登记人|member|auto ex=E-003', 'owner|责任人|member|auto at=fix ex=E-122', 'fixResult|整改措施|textarea|len=200 req at=submitFix ex=重新校准机械手;补录并增设自动记录;更换光电传感器', 'verify|复核意见|textarea|len=100 at=pass ex=复核通过'],
    optional: ['cost|整改费用（预计）|money|min=0 max=100000 at=submitFix ex=800', 'level|问题等级|select|opt=一般/重要/紧急 ex=重要'] }),
  O({ key: 'mold', name: '模具领用单', arche: 'make', prefix: 'MJ', verb: '模具领用', short: '领用单', flow: 'approve', tail: { lent: '已领用', returned: '已归还' }, ruleText: '预计归还超过约定时间标记超期并提醒',
    roles: { make: { submitter: '班组长', handler: '模具管理员', lead: '生产主管' } },
    fields: ['mold|模具编号|text|len=24 req ex=F-12;F-07;F-03;F-09', 'workOrder|工单号|ref|ref=orders req ex=@orders', 'machine|使用设备|ref|ref=machines ex=CNC-02;PA-01;CNC-04', 'from|领用时间|datetime|req ex=2026-09-17 09:30', 'to|预计归还|datetime|req after=from due ex=2026-09-19 18:00',
      'applicant|领用人|member|auto ex=E-003', 'opinion|审批意见|textarea|len=100 at=approve ex=同意', 'condition|归还状态|select|opt=完好/需维修/报废 req at=return ex=完好;需维修'],
    optional: ['photo|模具照片|photo|max=3 ex=1', 'shots|本次模次|number|min=0 max=100000 at=return ex=3200'] }),
  O({ key: 'incoming', name: '来料异常单', arche: 'make', prefix: 'LY', verb: '来料异常登记', short: '异常单', flow: 'dispatch', mode: 'accept', sla: { accept: 4 }, ruleText: '接单约定时效 4 小时，处置方式四选一',
    roles: { make: { submitter: '操作工', handler: '班组长', lead: '生产主管' } },
    fields: ['material|物料|ref|ref=materials req ex=@materials', 'supplier|供应商|text|len=60 ex=不锈钢棒材供应商;冷轧钢带供应商', 'batch|批次号|text|len=24 req ex=PC-260915-02;PC-260916-05', 'qty|异常数量|number|req min=1 max=100000 ex=120;40;600', 'unit|单位|select|opt=件/kg/m/卷 req ex=件;kg;卷',
      'type|异常类型|select|opt=尺寸/外观/材质/数量/包装 req ex=尺寸;外观;数量', 'desc|异常描述|textarea|len=200 req ex=棒材直径超差 0.05;表面锈蚀;实收少 40 件', 'photo|照片|photo|max=5 ex=2;1', 'reporter|报告人|member|auto ex=E-009', 'handler|处理人|member|auto at=accept ex=E-003',
      'disposition|处置方式|select|opt=退货/挑选使用/让步接收/报废 req at=complete ex=挑选使用;退货'],
    optional: ['cost|损失金额（预计）|money|min=0 max=1000000 at=complete ex=0', 'recheck|复检结果|select|opt=合格/不合格 at=complete ex=合格'] }),
  O({ key: 'consumable', name: '耗材申领单', arche: 'make', prefix: 'HC', verb: '耗材申领', short: '申领单', flow: 'approve', ruleText: '按产线申领，审批后领取',
    roles: { make: { submitter: '班组长', handler: '生产主管', lead: '生产主管' } },
    fields: ['item|耗材名称|text|len=60 req ex=切削液 20L;砂轮片 Ø150;劳保手套', 'qty|数量|number|req min=1 max=1000 ex=2;10;50', 'unit|单位|select|opt=桶/盒/件/箱 req ex=桶;盒;箱', 'line|用于产线|ref|ref=lines req ex=@lines', 'reason|用途|textarea|len=100 ex=CNC 线周耗;冲压线换砂轮;月度劳保',
      'applicant|申领人|member|auto ex=E-003', 'opinion|审批意见|textarea|len=100 at=approve ex=同意'],
    optional: ['urgency|紧急程度|select|opt=一般/紧急 ex=一般', 'cost|金额（预计）|money|min=0 max=100000 ex=360'] }),
  O({ key: 'hazard', name: '安全隐患上报', arche: 'make', prefix: 'AQ', verb: '隐患上报', short: '隐患单', flow: 'inspect', sla: { fix: 72 }, ruleText: '隐患一律进整改，整改约定 3 天，复核后关闭',
    roles: { make: { submitter: '操作工', handler: '班组长', handler2: '生产主管', lead: '生产主管' } },
    fields: ['area|区域|select|opt=下料区/冲压区/CNC 区/热处理区/电镀区/装配区/仓库 req ex=CNC 区;冲压区;电镀区', 'type|隐患类型|select|opt=机械/电气/消防/化学品/操作行为/其他 req ex=机械;电气;化学品', 'desc|隐患描述|textarea|len=200 req ex=CNC-04 防护门联锁失效，开门仍可运行;配电柜门未关，线缆裸露;酸液桶未加盖',
      'photo|现场照片|photo|max=3 req ex=2;1', 'level|风险等级|select|opt=低/中/高 req ex=高;中;低', 'reporter|上报人|member|auto ex=E-009', 'owner|整改责任人|member|auto at=fix ex=E-003', 'measure|整改措施|textarea|len=200 req at=submitFix ex=更换联锁开关并测试;关闭柜门并整理线缆;加盖并贴标识', 'verify|复核意见|textarea|len=100 at=pass ex=复核合格，联锁恢复'],
    optional: ['due|整改期限|date|ex=2026-09-20', 'cost|整改费用（预计）|money|min=0 max=100000 at=submitFix ex=200'] }),
  O({ key: 'overtime', name: '加班申请', arche: 'make', prefix: 'JB', verb: '加班申请', short: '加班单', flow: 'approve', ruleText: '结束须晚于开始，按产线申请',
    roles: { make: { submitter: '班组长', handler: '生产主管', lead: '生产主管' } },
    fields: ['date|加班日期|date|req ex=2026-09-18', 'from|开始|datetime|req ex=2026-09-18 17:30', 'to|结束|datetime|req after=from ex=2026-09-18 19:30', 'hours|加班时长（小时）|number|req min=0.5 max=12 ex=2;3;1.5', 'reason|加班事由|textarea|len=120 req ex=紧急订单 SO-2609-0142 赶工;换型后补产;设备保养',
      'line|产线|ref|ref=lines req ex=@lines', 'people|加班人数|number|req min=1 max=50 ex=6;4;8', 'applicant|申请人|member|auto ex=E-003', 'opinion|审批意见|textarea|len=100 at=approve ex=同意'],
    optional: ['meal|是否安排餐食|select|opt=是/否 ex=是', 'order|关联订单|ref|ref=orders ex=@orders'] }),
  O({ key: 'supplier', name: '供应商准入', arche: 'make', prefix: 'GY', verb: '供应商准入', short: '准入单', flow: 'approve', secondLevel: { field: 'score', gte: 0, text: '一律二级审批' }, ruleText: '一律二级审批，样品合格才可通过',
    roles: { make: { submitter: '班组长', handler: '生产主管', handler2: '财务主管', lead: '生产主管' } },
    fields: ['name|供应商名称|text|len=60 req ex=不锈钢棒材供应商（宁波）;精密弹簧外协厂;液压件备件商', 'category|供应品类|select|opt=原材料/辅料/外协加工/设备备件 req ex=原材料;外协加工;设备备件', 'license|营业执照|photo|max=1 req ex=1', 'cert|质量体系证书|select|opt=ISO 9001/IATF 16949/无 req ex=ISO 9001;IATF 16949',
      'sample|样品检验结果|select|opt=合格/不合格/待检 req ex=合格;待检', 'contact|联系人职务|text|len=20 ex=销售经理;业务经理', 'score|评审得分|number|req min=0 max=100 ex=86;78;91', 'applicant|申请人|member|auto ex=E-003', 'opinion|审批意见|textarea|len=100 at=approve ex=同意准入'],
    optional: ['audit|现场审核日期|date|ex=2026-09-26', 'photo|现场照片|photo|max=5 ex=2'] }),
  // ---------- 贸易 6 ----------
  O({ key: 'return_order', name: '退换货工单', arche: 'flow', prefix: 'TH', verb: '退换货', short: '工单', flow: 'dispatch', mode: 'dual', sla: { accept: 24 },
    stateLabels: { open: '待审核', accepted: '已审核', doing: '收货中', done: '已入库' }, actionLabels: { accept: '审核', start: '收货', complete: '入库' }, ruleText: '客服审核 24 小时内，仓库收货后入库',
    roles: { flow: { submitter: '门店', handler: '客服专员', handler2: '仓储员', lead: '仓配主管' } },
    fields: ['customer|门店|ref|ref=customers req ex=@customers', 'product|商品|ref|ref=products req ex=@products', 'qty|数量（箱）|number|req min=1 max=999 ex=12;6;30', 'reason|退货原因|select|opt=破损/临期/发错货/多发/质量问题 ex=破损;临期;发错货', 'type|类型|select|opt=退货/换货 req ex=退货;换货',
      'photo|商品照片|photo|max=5 ex=2;1', 'desc|说明|textarea|len=200 ex=外箱受潮破损 12 箱;临期 15 天，门店要求退回;到货与订单不符', 'order|原订单号|ref|ref=orders ex=@orders', 'auditor|审核人|member|auto at=accept ex=客服专员', 'auditNote|审核意见|textarea|len=100 at=accept ex=同意退货;同意换货',
      'receiver|入库员|member|auto at=start ex=E-015', 'stock|入库数量（箱）|number|req min=0 max=999 at=complete ex=12;6;30'],
    optional: ['refund|退款金额（预计）|money|min=0 max=100000 at=complete ex=1032', 'express|快递单号|text|len=24 ex=SF-2609-118203', 'rejectReason|驳回原因|textarea|len=100 req at=reject ex=照片不清晰，请重拍后再提交'] }),
  O({ key: 'sample_req', name: '样品申请', arche: 'flow', prefix: 'YP', verb: '样品申请', short: '样品单', flow: 'approve', tail: { lent: '已寄出' }, ruleText: '审批通过后仓库寄样并登记快递单号',
    roles: { flow: { submitter: '业务员', handler: '仓配主管', lead: '仓配主管' } },
    fields: ['customer|客户|ref|ref=customers req ex=@customers', 'product|商品|ref|ref=products req ex=@products', 'qty|样品数量（箱）|number|req min=1 max=50 ex=2;1;3', 'purpose|用途|select|opt=新客试用/招标/展会/其他 req ex=新客试用;招标;展会', 'address|收件地址|text|len=80 req ex=客户仓库（杭州余杭）;客户门店（宁波鄞州）;展会现场（上海）',
      'needBy|需要日期|date|req ex=2026-09-20', 'applicant|申请人|member|auto ex=业务员', 'opinion|审批意见|textarea|len=100 at=approve ex=同意寄样', 'express|快递单号|text|len=24 req at=lend ex=SF-2609-118203;SF-2609-118377'],
    optional: ['cost|样品成本（预计）|money|min=0 max=10000 ex=172', 'feedback|客户反馈|textarea|len=200 ex=待反馈'] }),
  O({ key: 'display_check', name: '门店陈列检查', arche: 'flow', prefix: 'CL', verb: '陈列检查', short: '检查单', flow: 'inspect', initialRule: { field: 'issues', gt: 0 }, sla: { fix: 72 }, ruleText: '不合格项 > 0 转整改，整改约定 3 天，督导复核',
    roles: { flow: { submitter: '业务员', handler: '门店', handler2: '督导', lead: '仓配主管' } },
    fields: ['store|门店|ref|ref=customers req ex=@customers', 'date|检查日期|date|req ex=2026-09-17', 'photo|陈列照片|photo|max=6 req ex=3;4', 'items|检查项数|number|req min=1 max=20 ex=8', 'issues|不合格项|number|req min=0 max=20 ex=2;0;1', 'issueDesc|问题描述|textarea|len=200 ex=堆头缺货、价签过期;端架陈列与计划不符',
      'inspector|检查人|member|auto ex=业务员', 'fixer|整改人|member|auto at=fix ex=门店', 'fixResult|整改说明|textarea|len=200 req at=submitFix ex=已补货并更换价签;已按陈列图调整', 'verify|复核意见|textarea|len=100 at=pass ex=复核合格'],
    optional: ['score|陈列评分|number|min=0 max=100 ex=82', 'due|整改期限|date|ex=2026-09-20'] }),
  O({ key: 'price_req', name: '价格申请', arche: 'flow', prefix: 'JG', verb: '价格申请', short: '价格单', flow: 'approve', secondLevel: { field: 'discount', gte: 10, text: '折扣 ≥ 10% 二级审批' }, ruleText: '折扣 ≥ 10% 进入二级审批',
    roles: { flow: { submitter: '业务员', handler: '仓配主管', handler2: '财务主管', lead: '仓配主管' } },
    fields: ['customer|客户|ref|ref=customers req ex=@customers', 'product|商品|ref|ref=products req ex=@products', 'listPrice|标准价（元/箱，预计）|money|req min=1 max=100000 ex=86;72;118', 'askPrice|申请价（元/箱，预计）|money|req min=1 max=100000 ex=76;66;112', 'discount|折扣（%）|number|req min=0 max=50 ex=12;8;5',
      'qty|预计数量（箱）|number|req min=1 max=100000 ex=600;300;1200', 'reason|申请理由|textarea|len=150 req ex=竞品同规格低价，客户要求跟进;年度框架量大;新品铺货', 'validTo|有效期至|date|req ex=2026-10-31', 'applicant|申请人|member|auto ex=业务员', 'opinion|审批意见|textarea|len=100 at=approve ex=同意'],
    optional: ['competitor|竞品价格（元/箱，预计）|money|min=0 max=100000 ex=74', 'term|账期（天）|number|min=0 max=180 ex=30'] }),
  O({ key: 'promo_material', name: '促销物料申领单', arche: 'flow', prefix: 'WL', verb: '物料申领', short: '申领单', flow: 'approve', tail: { lent: '已发放' }, ruleText: '审核通过后仓库发放登记',
    roles: { flow: { submitter: '业务员', handler: '运营专员', lead: '仓配主管' } },
    fields: ['item|物料名称|select|opt=海报/堆头/价签/试吃台/礼品 req ex=堆头;海报;礼品', 'qty|数量|number|req min=1 max=500 ex=6;40;100', 'store|用于门店|ref|ref=customers req ex=@customers', 'campaign|活动名称|text|len=60 req ex=中秋礼盒专场;开学季饮品周;十一大促', 'needBy|需要日期|date|req ex=2026-09-19',
      'applicant|申领人|member|auto ex=业务员', 'opinion|审核意见|textarea|len=100 at=approve ex=同意发放', 'issuer|发放人|member|auto at=lend ex=E-016'],
    optional: ['photo|陈列效果照片|photo|max=3 ex=1', 'cost|物料成本（预计）|money|min=0 max=50000 ex=480'] }),
  O({ key: 'arrival', name: '到货预约单', arche: 'flow', prefix: 'DH', verb: '到货预约', short: '预约单', flow: 'approve', ruleText: '确认后按月台与时段卸货',
    roles: { flow: { submitter: '业务员', handler: '仓配主管', lead: '仓配主管' } },
    fields: ['supplier|供应商|text|len=60 req ex=常温饮料供应商;休闲食品供应商;乳品供应商', 'product|商品|ref|ref=products req ex=@products', 'qty|数量（箱）|number|req min=1 max=9999 ex=600;400;900', 'plate|车型|select|opt=厢式货车/平板车/冷藏车 req ex=厢式货车;冷藏车',
      'arriveAt|预约到货时间|datetime|req ex=2026-09-18 09:00', 'dock|卸货月台|select|opt=收货月台 A/收货月台 B/D1 发运月台 ex=收货月台 A;收货月台 B', 'booker|预约人|member|auto ex=业务员', 'opinion|确认意见|textarea|len=100 at=approve ex=已安排'],
    optional: ['temp|温区|select|opt=常温/冷藏/冷冻 ex=常温', 'pallets|托盘数|number|min=1 max=60 ex=12'] }),
  // ---------- 服务 7 ----------
  O({ key: 'client_onboard', name: '新客户资料', arche: 'service', prefix: 'XK', verb: '接入', short: '接入单', flow: 'dispatch', mode: 'assign', sla: { accept: 24 },
    stateLabels: { open: '待分配', accepted: '已分配', doing: '建账中', done: '已接入' }, actionLabels: { assign: '分配', start: '开始建账', complete: '完成接入' }, ruleText: '分配约定 24 小时，超过标记超时',
    roles: { service: { submitter: '客户经理', handler: '账务组长', handler2: '代账会计', lead: '作业主管' } },
    fields: ['customer|客户|ref|ref=customers req ex=@customers', 'taxType|纳税人类型|select|opt=小规模纳税人/一般纳税人 req ex=一般纳税人;小规模纳税人', 'service|服务项目|ref|ref=services req ex=@services', 'startMonth|起始账期|text|len=7 req ex=2026-10', 'docs|资料是否齐全|select|opt=齐全/待补 req ex=齐全;待补',
      'photo|营业执照|photo|max=1 req ex=1', 'manager|客户经理|member|auto ex=E-030', 'assignee|代账会计|member|ref=employees req at=assign ex=E-001;E-002', 'group|账务组|ref|ref=groups ex=@groups', 'note|备注|textarea|len=200 at=complete ex=账套已建，首月账期 2026-10'],
    optional: ['fee|服务费（预计）|money|min=0 max=100000 ex=4800', 'contact|客户联系人职务|text|len=20 ex=财务负责人'] }),
  O({ key: 'doc_handover', name: '票据交接单', arche: 'service', prefix: 'PJ', verb: '票据交接', short: '交接单', flow: 'dispatch', mode: 'accept', sla: { accept: 24 }, ruleText: '签收约定 24 小时，逾期未交提醒',
    roles: { service: { submitter: '客户', handler: '代账会计', lead: '作业主管' } },
    fields: ['customer|客户|ref|ref=customers req ex=@customers', 'period|所属账期|text|len=7 req ex=2026-08', 'count|票据张数|number|req min=1 max=999 ex=46;12;88', 'type|票据类型|select|opt=进项发票/销项发票/银行回单/费用票 req ex=进项发票;银行回单;费用票', 'photo|票据照片|photo|max=9 ex=2;1;4',
      'sender|交接人|member|auto ex=客户', 'signer|签收人|member|auto at=accept ex=E-001', 'signNote|签收备注|textarea|len=100 at=complete ex=已签收，46 张与清单一致;已签收'],
    optional: ['missing|缺失说明|textarea|len=100 ex=缺 8 月水电费票', 'due|应交日期|date|due ex=2026-09-10'] }),
  O({ key: 'consult', name: '咨询工单', arche: 'service', prefix: 'ZX', verb: '咨询', short: '工单', flow: 'dispatch', mode: 'assign', sla: { accept: 4 }, ruleText: '分配约定 4 小时，答复后完成',
    stateLabels: { open: '待分配', accepted: '已分配', doing: '答复中', done: '已答复' }, actionLabels: { assign: '分配', start: '开始答复', complete: '完成答复' },
    roles: { service: { submitter: '客户', handler: '账务组长', handler2: '代账会计', lead: '作业主管' } },
    fields: ['customer|客户|ref|ref=customers req ex=@customers', 'topic|咨询类别|select|opt=税务/账务/工商/社保/其他 req ex=税务;账务;工商', 'question|咨询内容|textarea|len=300 req ex=小规模转一般纳税人的时点与准备材料;8 月费用票能否跨月入账;股东变更需要哪些材料', 'urgency|紧急度|select|opt=一般/紧急 req ex=一般;紧急',
      'photo|附件|photo|max=3 ex=0;1', 'receiver|登记人|member|auto ex=客户', 'assignee|答复人|member|ref=employees req at=assign ex=E-001;E-002', 'answer|答复内容|textarea|len=500 req at=complete ex=连续 12 个月销售额超过 500 万元须登记为一般纳税人，需准备营业执照、财务负责人信息与银行开户资料;可以，按发票日期所属月入账;股东会决议、股权转让协议、新股东身份材料'],
    optional: ['rating|客户评分|rating|at=rate ex=5', 'fee|咨询费（预计）|money|min=0 max=10000 ex=0'] }),
  O({ key: 'renewal', name: '续费提醒', arche: 'service', prefix: 'XF', verb: '续费提醒', short: '提醒单', flow: 'dispatch', mode: 'assign', sla: { accept: 24 }, ruleText: '到期前 30 天生成，分配客户经理跟进',
    stateLabels: { open: '待分配', accepted: '已分配', doing: '跟进中', done: '已跟进' }, actionLabels: { assign: '分配', start: '开始跟进', complete: '完成跟进' },
    roles: { service: { submitter: '账务组长', handler: '作业主管', handler2: '客户经理', lead: '作业主管' } },
    fields: ['customer|客户|ref|ref=customers req ex=@customers', 'service|服务项目|ref|ref=services req ex=@services', 'expireAt|到期日|date|req ex=2026-10-15', 'fee|续费金额（预计）|money|req min=0 max=1000000 ex=4800;9600;2400', 'creator|发起人|member|auto ex=账务组长',
      'assignee|跟进人|member|ref=employees req at=assign ex=E-030;E-031', 'contactResult|跟进结果|select|opt=已续费/考虑中/流失 req at=complete ex=已续费;考虑中', 'note|跟进记录|textarea|len=200 at=complete ex=已续一年，合同已签;客户比价中，下周再联系'],
    optional: ['discount|续费折扣（%）|number|min=0 max=30 ex=5', 'nextAt|下次跟进|date|at=complete ex=2026-09-24'] }),
  O({ key: 'biz_change', name: '工商变更申请', arche: 'service', prefix: 'GS', verb: '工商变更', short: '变更单', flow: 'approve', tail: { lent: '办理中', returned: '已办结' }, ruleText: '受理后进入办理，办结登记结果',
    actionLabels: { approve: '受理', lend: '开始办理', return: '办结' },
    roles: { service: { submitter: '客户经理', handler: '办理人', lead: '作业主管' } },
    fields: ['customer|客户|ref|ref=customers req ex=@customers', 'changeType|变更事项|select|opt=法定代表人/注册地址/经营范围/注册资本/股权 req ex=注册地址;经营范围;股权', 'desc|变更说明|textarea|len=200 req ex=迁至新园区办公地址;新增食品经营范围;股东股权内部转让', 'docs|材料清单|textarea|len=200 req ex=股东会决议、章程修正案、新地址证明;股东会决议、章程修正案;股权转让协议、股东会决议',
      'photo|材料照片|photo|max=9 ex=3;2', 'applicant|申请人|member|auto ex=E-030', 'opinion|受理意见|textarea|len=100 at=approve ex=材料齐全，受理', 'handler|办理人|member|auto at=lend ex=办理人', 'doneAt|办结日期|date|at=return ex=2026-09-24', 'result|办结结果|textarea|len=100 at=return ex=已换发营业执照'],
    optional: ['fee|政府规费（预计）|money|min=0 max=10000 ex=0', 'agency|是否代办|select|opt=是/否 ex=是'] }),
  O({ key: 'visit_log', name: '客户回访登记', arche: 'service', prefix: 'HF', verb: '回访登记', short: '回访单', flow: 'dispatch', mode: 'accept', sla: { accept: 24 }, ruleText: '不满意的回访由跟进人接单处理',
    roles: { service: { submitter: '客户经理', handler: '账务组长', lead: '作业主管' } },
    fields: ['customer|客户|ref|ref=customers req ex=@customers', 'visitAt|回访时间|datetime|req ex=2026-09-16 15:00', 'way|回访方式|select|opt=电话/微信/上门 req ex=电话;微信;上门', 'content|回访内容|textarea|len=300 req ex=月度账务交付满意，希望提前 3 天出报表;申报提醒及时;票据签收慢',
      'satisfaction|满意度|select|opt=满意/一般/不满意 req ex=满意;一般;不满意', 'issues|待跟进事项|textarea|len=200 ex=报表提前 3 天;无;票据签收提速', 'visitor|回访人|member|auto ex=E-030', 'handler|跟进人|member|auto at=accept ex=账务组长', 'result|跟进结果|textarea|len=200 req at=complete ex=已调整报表节点;已反馈会计组;已安排专人签收'],
    optional: ['photo|现场照片|photo|max=3 ex=1', 'nextAt|下次回访|date|at=complete ex=2026-10-16'] }),
  O({ key: 'doc_supplement', name: '资料补交单', arche: 'service', prefix: 'BJ', verb: '资料补交', short: '补交单', flow: 'dispatch', mode: 'accept', sla: { accept: 24 }, ruleText: '补交期限到期未交提醒',
    roles: { service: { submitter: '代账会计', handler: '客户经理', lead: '作业主管' } },
    fields: ['customer|客户|ref|ref=customers req ex=@customers', 'item|需补资料|select|opt=银行回单/进项发票/工资表/社保明细/其他 req ex=银行回单;工资表;进项发票', 'period|所属账期|text|len=7 req ex=2026-08', 'deadline|补交期限|date|req due ex=2026-09-20', 'reason|说明|textarea|len=200 ex=8 月对公账户回单缺 3 笔;工资表未盖章;缺 2 张进项票',
      'requester|发起人|member|auto ex=E-001', 'receiver|接收人|member|auto at=accept ex=E-030', 'photo|补交资料|photo|max=9 at=complete ex=3;1', 'note|签收说明|textarea|len=100 at=complete ex=已补齐并核对;已补交'],
    optional: ['remind|提醒次数|number|min=0 max=10 ex=1', 'count|补交张数|number|min=0 max=999 at=complete ex=3'] })
];
