/* ===== 小图表（对话气泡与页面内嵌）：条 / 柱 / 环 / 线 / 雷达 / 时间轴 / 热力 / 甘特 / 漏斗 / 分组柱；同一套类别色 CPAL，顺序色 RAMP ===== */
const RAMP = ['#eef0fb', '#c9cbf5', '#9a9cf5', '#6f70f0', '#5a5bf0', '#3d3ec7'];
CH.mini = {
  W: 300,
  attrs(o) { return (o.act ? ' data-act="' + h(o.act) + '"' : '') + (o.who ? ' data-who="' + h(o.who) + '"' : '') + (o.id != null ? ' data-id="' + h(o.id) + '"' : '') + (o.k != null ? ' data-k="' + h(o.k) + '"' : '') + (o.i != null ? ' data-i="' + o.i + '"' : '') + (o.tip ? ' data-tip="' + h(o.tip) + '"' : ''); },
  bars(items, opt) { opt = opt || {}; const rh = opt.h || 14, x0 = opt.x0 || 50, W = 300 - x0 - 34; const max = opt.max || Math.max.apply(null, items.map(i => i.v)) * 1.12 || 1; const H = items.length * rh + 10;
    const body = items.map((it, i) => { const y = 8 + i * rh; const w = Math.max(3, it.v / max * W); const c = it.c || CPAL[0]; return '<g' + this.attrs(it) + '><rect x="0" y="' + (y - 6) + '" width="300" height="' + rh + '" fill="transparent"/><text x="' + (x0 - 6) + '" y="' + (y + 3.5) + '" text-anchor="end" class="lb">' + h(it.n) + '</text><rect x="' + x0 + '" y="' + (y - 4) + '" width="' + w.toFixed(1) + '" height="8" rx="3" fill="' + c + '"/><text x="' + (x0 + w + 5).toFixed(1) + '" y="' + (y + 3.5) + '" class="lb num">' + (it.txt != null ? h(it.txt) : it.v + (opt.unit || '')) + '</text></g>'; }).join('');
    const lim = opt.limit ? '<line x1="' + (x0 + opt.limit / max * W).toFixed(1) + '" y1="2" x2="' + (x0 + opt.limit / max * W).toFixed(1) + '" y2="' + (H - 2) + '" class="thr"/>' : '';
    return '<svg viewBox="0 0 300 ' + H + '" class="ch mini">' + body + lim + '</svg>'; },
  cols(items, opt) { opt = opt || {}; const L = 24, B = 22, T = 14, Hh = opt.h || 120; const n = items.length; const bw = Math.min(22, (300 - L - 8) / n * 0.62); const max = opt.max || Math.max.apply(null, items.map(i => i.v)) * 1.15 || 1; const x = i => L + (i + .5) * (300 - L - 8) / n; const y = v => T + (1 - v / max) * (Hh - T - B);
    const grid = [0, .5, 1].map(f => '<line x1="' + L + '" y1="' + y(max * f).toFixed(1) + '" x2="292" y2="' + y(max * f).toFixed(1) + '" class="grid"/><text x="' + (L - 3) + '" y="' + (y(max * f) + 3).toFixed(1) + '" text-anchor="end" class="lb mute">' + Math.round(max * f) + '</text>').join('');
    const body = items.map((it, i) => '<g' + this.attrs(it) + '><rect x="' + (x(i) - bw / 2).toFixed(1) + '" y="' + y(it.v).toFixed(1) + '" width="' + bw.toFixed(1) + '" height="' + (y(0) - y(it.v)).toFixed(1) + '" rx="3" fill="' + (it.c || CPAL[0]) + '"/><text x="' + x(i).toFixed(1) + '" y="' + (Hh - 8) + '" text-anchor="middle" class="lb mute">' + h(it.n) + '</text>' + (opt.labels ? '<text x="' + x(i).toFixed(1) + '" y="' + (y(it.v) - 3).toFixed(1) + '" text-anchor="middle" class="lb num">' + it.v + '</text>' : '') + '</g>').join('');
    return '<svg viewBox="0 0 300 ' + Hh + '" class="ch mini">' + grid + body + '</svg>'; },
  donut(items, opt) { opt = opt || {}; const tot = items.reduce((s, i) => s + i.v, 0) || 1; let a = -Math.PI / 2; const gap = .05, cx = 64, cy = 64, r = 44;
    const segs = items.map((it, i) => { const sw = it.v / tot * Math.PI * 2; const d = CH.arc(cx, cy, r, a + gap / 2, Math.max(a + gap / 2 + .01, a + sw - gap / 2)); a += sw; return '<path d="' + d + '" stroke="' + (it.c || CPAL[i % 6]) + '" stroke-width="13" fill="none"' + this.attrs(Object.assign({ tip: it.k + ' ' + it.v }, it)) + '/>'; }).join('');
    const leg = items.map((it, i) => '<g' + this.attrs(it) + '><rect x="132" y="' + (22 + i * 20) + '" width="9" height="9" rx="2" fill="' + (it.c || CPAL[i % 6]) + '"/><text x="146" y="' + (30 + i * 20) + '" class="lb">' + h(it.k) + '</text><text x="292" y="' + (30 + i * 20) + '" text-anchor="end" class="lb num">' + it.v + (opt.unit || '') + '</text></g>').join('');
    return '<svg viewBox="0 0 300 ' + Math.max(128, 30 + items.length * 20) + '" class="ch mini">' + segs + '<text x="' + cx + '" y="' + (cy + 1) + '" text-anchor="middle" class="hero" style="font-size:18px">' + h(opt.hero != null ? opt.hero : tot) + '</text><text x="' + cx + '" y="' + (cy + 14) + '" text-anchor="middle" class="lb mute">' + h(opt.sub || '') + '</text>' + leg + '</svg>'; },
  line(series, labels, opt) { opt = opt || {}; const L = 26, R = 12, T = 14, B = 22, Hh = opt.h || 130; const n = labels.length; const all = series.reduce((a, s) => a.concat(s.vals), []); const max = opt.max || (Math.max.apply(null, all) * 1.15 || 1); const x = i => L + i / Math.max(1, n - 1) * (300 - L - R); const y = v => T + (1 - v / max) * (Hh - T - B);
    const grid = [0, .5, 1].map(f => '<line x1="' + L + '" y1="' + y(max * f).toFixed(1) + '" x2="' + (300 - R) + '" y2="' + y(max * f).toFixed(1) + '" class="grid"/><text x="' + (L - 4) + '" y="' + (y(max * f) + 3).toFixed(1) + '" text-anchor="end" class="lb mute">' + (opt.pct ? Math.round(max * f) + '%' : Math.round(max * f)) + '</text>').join('');
    const step = Math.max(1, Math.ceil(n / 6)); const xl = labels.map((l, i) => i % step === 0 || i === n - 1 ? '<text x="' + x(i).toFixed(1) + '" y="' + (Hh - 7) + '" text-anchor="middle" class="lb mute">' + h(l) + '</text>' : '').join('');
    const paths = series.map((s, si) => { const c = s.c || CPAL[si % 6]; const d = s.vals.map((v, i) => (i ? 'L' : 'M') + x(i).toFixed(1) + ' ' + y(v).toFixed(1)).join(' '); return (s.area ? '<path d="' + d + ' L' + x(n - 1).toFixed(1) + ' ' + y(0).toFixed(1) + ' L' + x(0).toFixed(1) + ' ' + y(0).toFixed(1) + 'Z" fill="' + c + '" opacity=".1"/>' : '') + '<path d="' + d + '" fill="none" stroke="' + c + '" stroke-width="2" stroke-linejoin="round"/>' + s.vals.map((v, i) => '<circle cx="' + x(i).toFixed(1) + '" cy="' + y(v).toFixed(1) + '" r="3.5" fill="' + c + '" class="dot" data-tip="' + h(labels[i]) + ' · ' + h(s.n) + ' ' + v + (opt.unit || '') + '"' + (s.act ? ' data-act="' + s.act + '" data-i="' + i + '"' : '') + '/>').join('') + '<text x="' + (x(n - 1) - 5).toFixed(1) + '" y="' + (y(s.vals[n - 1]) - 6).toFixed(1) + '" text-anchor="end" class="lb" fill="' + c + '">' + h(s.n) + ' ' + s.vals[n - 1] + (opt.unit || '') + '</text>'; }).join('');
    return '<svg viewBox="0 0 300 ' + Hh + '" class="ch mini">' + grid + paths + xl + '</svg>'; },
  radar(dims, series, opt) { opt = opt || {}; const cx = 150, cy = 84, R = 56, n = dims.length, max = opt.max || 5; const pt = (i, v) => { const a = -Math.PI / 2 + i / n * Math.PI * 2; return [cx + R * v / max * Math.cos(a), cy + R * v / max * Math.sin(a)]; };
    const rings = [1, 2, 3, 4, 5].map(l => '<polygon points="' + dims.map((d, i) => pt(i, l * max / 5).map(v => v.toFixed(1)).join(',')).join(' ') + '" class="grid" fill="none"/>').join('');
    const labels = dims.map((d, i) => { const a = -Math.PI / 2 + i / n * Math.PI * 2; const x = cx + (R + 14) * Math.cos(a), y = cy + (R + 14) * Math.sin(a); return '<text x="' + x.toFixed(1) + '" y="' + (y + 3).toFixed(1) + '" text-anchor="' + (Math.abs(Math.cos(a)) < .2 ? 'middle' : Math.cos(a) > 0 ? 'start' : 'end') + '" class="lb">' + h(d) + '</text>'; }).join('');
    const polys = series.map((s, si) => { const c = s.c || CPAL[si % 6]; return '<polygon points="' + s.vals.map((v, i) => pt(i, v).map(q => q.toFixed(1)).join(',')).join(' ') + '" fill="' + c + '" fill-opacity="' + (si ? .08 : .18) + '" stroke="' + c + '" stroke-width="2"' + (s.dash ? ' stroke-dasharray="4 3"' : '') + '/>' + s.vals.map((v, i) => { const [x, y] = pt(i, v); return '<circle cx="' + x.toFixed(1) + '" cy="' + y.toFixed(1) + '" r="3.5" fill="' + c + '" class="dot" data-tip="' + h(dims[i]) + ' · ' + h(s.n) + ' ' + (opt.fmt ? opt.fmt(v) : v) + '"/>'; }).join(''); }).join('');
    return '<svg viewBox="0 0 300 168" class="ch mini">' + rings + polys + labels + '</svg>'; },
  timeline(items, opt) { opt = opt || {}; const L = 14, R = 14, span = opt.span || 365; const x = t => L + Math.min(1, Math.max(0, t / span)) * (300 - L - R); const lanes = []; const marks = (opt.marks || [0, 90, 180, 270, 365]).map(t => '<text x="' + x(t).toFixed(1) + '" y="70" text-anchor="middle" class="lb mute">' + (t === 0 ? '今天' : t + '天') + '</text>');
    const dots = items.slice().sort((a, b) => a.t - b.t).map(it => { const cx = x(it.t); let lane = 0; while (lanes[lane] != null && cx - lanes[lane] < 16) lane++; lanes[lane] = cx; const cy = 50 - lane * 14; return '<g' + this.attrs(it) + '><circle cx="' + cx.toFixed(1) + '" cy="' + cy + '" r="5" fill="' + (it.c || CPAL[0]) + '" class="dot"/>' + (it.lbl ? '<text x="' + cx.toFixed(1) + '" y="' + (cy - 8) + '" text-anchor="middle" class="lb" fill="' + (it.c || CPAL[0]) + '">' + h(it.lbl) + '</text>' : '') + '</g>'; }).join('');
    return '<svg viewBox="0 0 300 78" class="ch mini"><line x1="' + L + '" y1="58" x2="' + (300 - R) + '" y2="58" class="grid"/><line x1="' + L + '" y1="10" x2="' + L + '" y2="58" class="thr"/>' + marks.join('') + dots + '</svg>'; },
  heat(rows, cols, vals, opt) { opt = opt || {}; const max = opt.max || 5; const W = opt.w || 300, L = opt.L || 58, rh = opt.rh || 14; const cw = Math.min(opt.cwmax || 22, (W - L - 2) / cols.length); const H = 16 + rows.length * rh; const col = v => opt.colors ? opt.colors[v] || '#e6e8f4' : RAMP[Math.min(5, Math.round(v / max * 5))];
    const hd = cols.map((c, j) => (cols.length <= 12 || j % Math.ceil(cols.length / 10) === 0) ? '<text x="' + (L + (j + .5) * cw).toFixed(1) + '" y="10" text-anchor="middle" class="lb mute">' + h(c) + '</text>' : '').join('');
    const body = rows.map((r, i) => '<text x="' + (L - 4) + '" y="' + (14 + i * rh + 8) + '" text-anchor="end" class="lb">' + h(r) + '</text>' + cols.map((c, j) => '<rect x="' + (L + j * cw + 1).toFixed(1) + '" y="' + (14 + i * rh + 1) + '" width="' + (cw - 2).toFixed(1) + '" height="' + (rh - 2) + '" rx="2" fill="' + col(vals[i][j]) + '"' + this.attrs({ act: opt.act, who: r, i: j, tip: r + ' · ' + c + ' · ' + (opt.fmt ? opt.fmt(vals[i][j]) : vals[i][j]) }) + '/>').join('')).join('');
    return '<svg viewBox="0 0 ' + W + ' ' + H + '" class="ch mini">' + hd + body + '</svg>'; },
  gantt(items, days, opt) { opt = opt || {}; const W = opt.w || 300, L = opt.L || 100, rh = 16, n = days.length; const cw = (W - L - 6) / n; const H = 16 + items.length * rh;
    const hd = days.map((d, j) => '<text x="' + (L + (j + .5) * cw).toFixed(1) + '" y="10" text-anchor="middle" class="lb mute">' + h(d) + '</text><line x1="' + (L + j * cw).toFixed(1) + '" y1="14" x2="' + (L + j * cw).toFixed(1) + '" y2="' + H + '" class="grid"/>').join('');
    const body = items.map((it, i) => '<g' + this.attrs(it) + '><rect x="0" y="' + (14 + i * rh) + '" width="' + W + '" height="' + rh + '" fill="transparent"/><text x="' + (L - 6) + '" y="' + (14 + i * rh + 11) + '" text-anchor="end" class="lb">' + h(it.n.length > (opt.maxn || 11) ? it.n.slice(0, opt.maxn || 11) + '…' : it.n) + '</text><rect x="' + (L + it.d0 * cw + 1).toFixed(1) + '" y="' + (14 + i * rh + 3) + '" width="' + ((it.d1 - it.d0 + 1) * cw - 2).toFixed(1) + '" height="' + (rh - 6) + '" rx="4" fill="' + (it.c || CPAL[0]) + '"/></g>').join('');
    return '<svg viewBox="0 0 ' + W + ' ' + H + '" class="ch mini">' + hd + body + '</svg>'; },
  funnel(steps, opt) { opt = opt || {}; const max = Math.max.apply(null, steps.map(s => s.v)) || 1; const rh = 22; const H = steps.length * rh + 6;
    return '<svg viewBox="0 0 300 ' + H + '" class="ch mini">' + steps.map((s, i) => { const w = Math.max(20, s.v / max * 200); const x = 150 - w / 2; return '<g' + this.attrs(s) + '><rect x="' + x.toFixed(1) + '" y="' + (3 + i * rh) + '" width="' + w.toFixed(1) + '" height="' + (rh - 5) + '" rx="4" fill="' + (s.c || RAMP[5 - Math.min(4, i)]) + '"/><text x="150" y="' + (3 + i * rh + 12) + '" text-anchor="middle" class="lb" fill="#fff" font-weight="700">' + h(s.k) + ' ' + s.v + '</text></g>'; }).join('') + '</svg>'; },
  group(cats, series, opt) { opt = opt || {}; const L = 26, B = 22, T = 14, Hh = opt.h || 130; const n = cats.length, m = series.length; const all = series.reduce((a, s) => a.concat(s.vals), []); const max = opt.max || (Math.max.apply(null, all) * 1.15 || 1); const gw = (300 - L - 8) / n; const bw = Math.min(14, gw * .7 / m); const y = v => T + (1 - v / max) * (Hh - T - B);
    const grid = [0, .5, 1].map(f => '<line x1="' + L + '" y1="' + y(max * f).toFixed(1) + '" x2="292" y2="' + y(max * f).toFixed(1) + '" class="grid"/><text x="' + (L - 3) + '" y="' + (y(max * f) + 3).toFixed(1) + '" text-anchor="end" class="lb mute">' + Math.round(max * f) + (opt.unit || '') + '</text>').join('');
    const body = cats.map((c, i) => '<text x="' + (L + (i + .5) * gw).toFixed(1) + '" y="' + (Hh - 7) + '" text-anchor="middle" class="lb mute">' + h(c) + '</text>' + series.map((s, si) => { const x = L + (i + .5) * gw - (m * bw) / 2 + si * bw; return '<rect x="' + (x + 1).toFixed(1) + '" y="' + y(s.vals[i]).toFixed(1) + '" width="' + (bw - 2).toFixed(1) + '" height="' + (y(0) - y(s.vals[i])).toFixed(1) + '" rx="2.5" fill="' + (s.c || CPAL[si % 6]) + '"' + this.attrs({ act: s.act, k: c, who: s.n, tip: c + ' · ' + s.n + ' ' + s.vals[i] + (opt.unit || '') }) + '/>'; }).join('')).join('');
    return '<svg viewBox="0 0 300 ' + Hh + '" class="ch mini">' + grid + body + '</svg>'; },
  legend(series) { return '<div class="legend">' + series.map((s, i) => '<span><i style="background:' + (s.c || CPAL[i % 6]) + '"></i>' + h(s.n) + '</span>').join('') + '</div>'; }
};
