/* ===== 手绘 SVG 图表（零依赖）：环形 / 横向条 / 折线面积 / 雷达 / 到期时间轴 / 计量条；悬停提示 + 点击下钻 ===== */
const CPAL = ['#5a5bf0', '#e8791d', '#0f9bb0', '#d63384', '#2a9d4b', '#9a4dff']; // 类别色，固定顺序（已过色盲/对比校验）
const CH = {
  tip: null,
  initTip() { if (this.tip) return; const t = document.createElement('div'); t.id = 'tip'; t.className = 'tip'; document.body.appendChild(t); this.tip = t;
    document.addEventListener('mousemove', e => { const el = e.target.closest && e.target.closest('[data-tip]'); if (!el) { t.classList.remove('on'); return; } t.innerHTML = el.dataset.tip; t.classList.add('on'); const x = Math.min(window.innerWidth - t.offsetWidth - 12, e.clientX + 14), y = Math.max(8, e.clientY - t.offsetHeight - 12); t.style.left = x + 'px'; t.style.top = y + 'px'; }); },
  arc(cx, cy, r, a0, a1) { const p = a => [cx + r * Math.cos(a), cy + r * Math.sin(a)]; const [x0, y0] = p(a0), [x1, y1] = p(a1); return 'M' + x0.toFixed(1) + ' ' + y0.toFixed(1) + ' A' + r + ' ' + r + ' 0 ' + (a1 - a0 > Math.PI ? 1 : 0) + ' 1 ' + x1.toFixed(1) + ' ' + y1.toFixed(1); },
  /* 环形：本月任务按类型 */
  donut(items, hero, sub) { const tot = items.reduce((s, i) => s + i.v, 0); let a = -Math.PI / 2; const gap = 0.045; const cx = 78, cy = 88, r = 56;
    const segs = items.map((it, i) => { const sw = it.v / tot * Math.PI * 2; const d = this.arc(cx, cy, r, a + gap / 2, a + sw - gap / 2); a += sw; return '<path class="seg" d="' + d + '" stroke="' + CPAL[i] + '" stroke-width="16" fill="none" stroke-linecap="butt" data-act="ch-task" data-k="' + h(it.k) + '" data-tip="' + h(it.k) + ' ' + it.v + ' 项 · 完成 ' + it.done + ' · 点开看明细" style="transition-delay:' + (i * 90) + 'ms"/>'; }).join('');
    const leg = items.map((it, i) => '<g data-act="ch-task" data-k="' + h(it.k) + '" data-tip="' + h(it.k) + ' 完成 ' + it.done + '/' + it.v + '" class="lg"><rect x="160" y="' + (46 + i * 24) + '" width="10" height="10" rx="3" fill="' + CPAL[i] + '"/><text x="176" y="' + (55 + i * 24) + '" class="lb">' + h(it.k) + '</text><text x="292" y="' + (55 + i * 24) + '" class="lb num" text-anchor="end">' + it.done + '/' + it.v + '</text></g>').join('');
    return '<svg viewBox="0 0 300 180" class="ch">' + segs + '<text x="' + cx + '" y="' + (cy - 2) + '" text-anchor="middle" class="hero">' + hero + '</text><text x="' + cx + '" y="' + (cy + 16) + '" text-anchor="middle" class="lb mute">' + h(sub) + '</text>' + leg + '</svg>'; },
  /* 横向条：本周工时，24h 约定线 */
  bars(rows, limit) { const rh = 15, x0 = 46, W = 208, max = 28; const H = rows.length * rh + 22;
    const th = x0 + limit / max * W;
    const body = rows.map((r, i) => { const y = 16 + i * rh; const w = Math.max(6, r.v / max * W); const over = r.v >= limit; const col = over ? '#e5484d' : CPAL[0]; return '<g data-act="ch-hours" data-who="' + h(r.n) + '" data-tip="' + h(r.n) + ' 本周 ' + r.v + ' h' + (over ? ' · 超过约定' : '') + ' · 点开照亮台账"><rect x="0" y="' + (y - 7) + '" width="300" height="' + rh + '" fill="transparent"/><text x="' + (x0 - 6) + '" y="' + (y + 4) + '" text-anchor="end" class="lb">' + h(r.n) + '</text><path class="bar" d="M' + x0 + ' ' + (y - 4.5) + ' h' + (w - 4) + ' a4 4 0 0 1 4 4 v1 a4 4 0 0 1 -4 4 h-' + (w - 4) + ' z" fill="' + col + '" style="transform-origin:' + x0 + 'px ' + y + 'px;transition-delay:' + (i * 40) + 'ms"/>' + (over ? '<text x="' + (x0 + w + 5) + '" y="' + (y + 4) + '" class="lb num" fill="#e5484d">' + r.v + 'h</text>' : '') + '</g>'; }).join('');
    return '<svg viewBox="0 0 300 ' + H + '" class="ch">' + body + '<line x1="' + th + '" y1="6" x2="' + th + '" y2="' + (H - 6) + '" class="thr"/><text x="' + (th + 4) + '" y="' + (H - 2) + '" class="lb mute">' + limit + 'h 约定</text></svg>'; },
  /* 折线面积：近 30 天缺陷发现（累计）与闭环（累计） */
  area(days, s1, s2) { const L = 26, R = 12, T = 16, B = 26, W = 300, Hh = 180; const n = days.length; const max = Math.max.apply(null, s1.concat(s2)) + 1; const x = i => L + i / (n - 1) * (W - L - R); const y = v => T + (1 - v / max) * (Hh - T - B);
    const line = s => s.map((v, i) => (i ? 'L' : 'M') + x(i).toFixed(1) + ' ' + y(v).toFixed(1)).join(' ');
    const grid = [0, .5, 1].map(f => '<line x1="' + L + '" y1="' + y(max * f).toFixed(1) + '" x2="' + (W - R) + '" y2="' + y(max * f).toFixed(1) + '" class="grid"/><text x="' + (L - 4) + '" y="' + (y(max * f) + 3).toFixed(1) + '" text-anchor="end" class="lb mute">' + Math.round(max * f) + '</text>').join('');
    const xl = [0, Math.floor(n / 3), Math.floor(2 * n / 3), n - 1].map(i => '<text x="' + x(i).toFixed(1) + '" y="' + (Hh - 8) + '" text-anchor="middle" class="lb mute">' + h(days[i]) + '</text>').join('');
    const hit = days.map((d, i) => '<rect x="' + (x(i) - (W - L - R) / (n - 1) / 2).toFixed(1) + '" y="' + T + '" width="' + ((W - L - R) / (n - 1)).toFixed(1) + '" height="' + (Hh - T - B) + '" fill="transparent" data-act="ch-day" data-i="' + i + '" data-tip="' + h(d) + ' · 发现累计 ' + s1[i] + ' · 闭环累计 ' + s2[i] + ' · 点开看这天"/>').join('');
    const end = (s, c, t) => '<circle cx="' + x(n - 1).toFixed(1) + '" cy="' + y(s[n - 1]).toFixed(1) + '" r="4" fill="' + c + '" class="dot"/><text x="' + (x(n - 1) - 6).toFixed(1) + '" y="' + (y(s[n - 1]) - 7).toFixed(1) + '" text-anchor="end" class="lb" fill="' + c + '">' + t + ' ' + s[n - 1] + '</text>';
    return '<svg viewBox="0 0 300 ' + Hh + '" class="ch" id="charea">' + grid + '<path d="' + line(s1) + ' L' + x(n - 1).toFixed(1) + ' ' + y(0).toFixed(1) + ' L' + x(0).toFixed(1) + ' ' + y(0).toFixed(1) + ' Z" fill="' + CPAL[0] + '" opacity=".10"/><path d="' + line(s1) + '" class="ln" stroke="' + CPAL[0] + '" pathLength="1"/><path d="' + line(s2) + '" class="ln" stroke="' + CPAL[2] + '" pathLength="1"/>' + end(s1, CPAL[0], '发现') + end(s2, CPAL[2], '闭环') + xl + '<g class="xh" id="xh"><line y1="' + T + '" y2="' + (Hh - B) + '" class="xhl"/><circle r="4" class="dot" fill="' + CPAL[0] + '"/><circle r="4" class="dot" fill="' + CPAL[2] + '"/></g>' + hit + '</svg>'; },
  areaHover(svg, days, s1, s2) { const L = 26, R = 12, T = 16, B = 26, W = 300, Hh = 180; const n = days.length; const max = Math.max.apply(null, s1.concat(s2)) + 1; const x = i => L + i / (n - 1) * (W - L - R); const y = v => T + (1 - v / max) * (Hh - T - B); const xh = $('#xh', svg); const cs = $$('circle', xh);
    svg.addEventListener('mousemove', e => { const r = svg.getBoundingClientRect(); const px = (e.clientX - r.left) / r.width * W; let i = Math.round((px - L) / (W - L - R) * (n - 1)); i = Math.max(0, Math.min(n - 1, i)); xh.classList.add('on'); $('line', xh).setAttribute('x1', x(i)); $('line', xh).setAttribute('x2', x(i)); cs[0].setAttribute('cx', x(i)); cs[0].setAttribute('cy', y(s1[i])); cs[1].setAttribute('cx', x(i)); cs[1].setAttribute('cy', y(s2[i])); });
    svg.addEventListener('mouseleave', () => xh.classList.remove('on')); },
  /* 雷达：8 模块班组均值 vs 目标 L3 */
  radar(dims, vals, target) { const cx = 150, cy = 92, R = 66, n = dims.length; const pt = (i, v) => { const a = -Math.PI / 2 + i / n * Math.PI * 2; return [cx + R * v / 5 * Math.cos(a), cy + R * v / 5 * Math.sin(a)]; };
    const rings = [1, 2, 3, 4, 5].map(l => '<polygon points="' + dims.map((d, i) => pt(i, l).map(v => v.toFixed(1)).join(',')).join(' ') + '" class="grid" fill="none"/>').join('');
    const axes = dims.map((d, i) => { const [x, y] = pt(i, 5); return '<line x1="' + cx + '" y1="' + cy + '" x2="' + x.toFixed(1) + '" y2="' + y.toFixed(1) + '" class="grid"/>'; }).join('');
    const labels = dims.map((d, i) => { const a = -Math.PI / 2 + i / n * Math.PI * 2; const x = cx + (R + 16) * Math.cos(a), y = cy + (R + 16) * Math.sin(a); return '<text x="' + x.toFixed(1) + '" y="' + (y + 3).toFixed(1) + '" text-anchor="' + (Math.abs(Math.cos(a)) < .2 ? 'middle' : Math.cos(a) > 0 ? 'start' : 'end') + '" class="lb" data-act="ch-mod" data-i="' + i + '" data-tip="' + h(d) + ' · 班组均值 L' + vals[i].toFixed(1) + ' · 点开看短板">' + h(d.replace('能力', '')) + '</text>'; }).join('');
    const poly = '<polygon class="poly" points="' + vals.map((v, i) => pt(i, v).map(q => q.toFixed(1)).join(',')).join(' ') + '" fill="' + CPAL[0] + '" fill-opacity=".18" stroke="' + CPAL[0] + '" stroke-width="2"/>';
    const tgt = '<polygon points="' + dims.map((d, i) => pt(i, target).map(q => q.toFixed(1)).join(',')).join(' ') + '" fill="none" stroke="#7b849c" stroke-width="1" stroke-dasharray="4 3"/>';
    const dots = vals.map((v, i) => { const [x, y] = pt(i, v); return '<circle cx="' + x.toFixed(1) + '" cy="' + y.toFixed(1) + '" r="4.5" fill="' + (v < target ? '#e8791d' : CPAL[0]) + '" class="dot vt" data-act="ch-mod" data-i="' + i + '" data-tip="' + h(dims[i]) + ' · 班组均值 L' + v.toFixed(1) + (v < target ? ' · 低于目标 L3' : '') + '"/>'; }).join('');
    return '<svg viewBox="0 0 300 184" class="ch">' + rings + axes + tgt + poly + dots + labels + '</svg>'; },
  /* 到期时间轴：未来 12 个月的证书复审 */
  certline(certs) { const L = 14, R = 14, W = 300, Hh = 180; const t0 = new Date(TODAY).getTime(), span = 365 * 86400000; const x = d => L + Math.min(1, Math.max(0, (new Date(d).getTime() - t0) / span)) * (W - L - R);
    const months = []; for (let m = 0; m < 13; m += 3) { const d = new Date(TODAY); d.setMonth(d.getMonth() + m); months.push(d); }
    const ax = '<line x1="' + L + '" y1="120" x2="' + (W - R) + '" y2="120" class="grid"/>' + months.map(d => '<text x="' + x(d).toFixed(1) + '" y="136" text-anchor="middle" class="lb mute">' + (d.getFullYear() !== new Date(TODAY).getFullYear() ? (d.getMonth() + 1) + '月' : (d.getMonth() + 1) + '月') + '</text>').join('') + '<line x1="' + L + '" y1="24" x2="' + L + '" y2="120" class="thr"/><text x="' + (L + 3) + '" y="20" class="lb mute">今天</text>';
    const inYear = certs.filter(c => !c.renewed && daysTo(c.due) >= 0 && daysTo(c.due) <= 365).sort((a, b) => daysTo(a.due) - daysTo(b.due)); const lanes = [];
    const dots = inYear.map((c, i) => { const cx = x(c.due); let lane = 0; while (lanes[lane] != null && cx - lanes[lane] < 14) lane++; lanes[lane] = cx; const cy = 108 - lane * 18; const d = daysTo(c.due); const col = d <= 90 ? '#e5484d' : d <= 180 ? '#e8791d' : CPAL[0]; return '<g data-act="ch-cert" data-who="' + h(c.who) + '" data-tip="' + h(c.who) + ' · ' + h(c.name) + ' · ' + c.due + ' · 还有 ' + d + ' 天"><circle cx="' + cx.toFixed(1) + '" cy="' + cy + '" r="5" fill="' + col + '" class="dot"/>' + (d <= 90 ? '<text x="' + cx.toFixed(1) + '" y="' + (cy - 9) + '" text-anchor="middle" class="lb" fill="' + col + '">' + h(c.who) + '</text>' : '') + '</g>'; }).join('');
    const later = certs.filter(c => !c.renewed && daysTo(c.due) > 365).length;
    return '<svg viewBox="0 0 300 ' + Hh + '" class="ch">' + ax + dots + '<text x="' + (W - R) + '" y="160" text-anchor="end" class="lb mute">一年后到期 ' + later + ' 张</text><g><circle cx="20" cy="158" r="4" fill="#e5484d"/><text x="28" y="161" class="lb">90 天内</text><circle cx="78" cy="158" r="4" fill="#e8791d"/><text x="86" y="161" class="lb">半年内</text><circle cx="130" cy="158" r="4" fill="' + CPAL[0] + '"/><text x="138" y="161" class="lb">一年内</text></g></svg>'; },
  /* 计量条：单一比率对上限 */
  meters(items) { return '<div class="meters">' + items.map(it => '<div class="mt" data-act="ch-meter" data-k="' + h(it.k) + '" data-tip="' + h(it.tip) + '"><div class="ml"><span>' + h(it.n) + '</span><b class="num">' + h(it.txt) + '</b></div><div class="tr"><i style="width:0" data-w="' + Math.round(it.v * 100) + '" class="' + (it.v >= 1 ? 'full' : it.v < .7 ? 'low' : '') + '"></i></div></div>').join('') + '</div>'; },
  /* 挂载后触发生长动画 */
  mount(root) { this.initTip(); requestAnimationFrame(() => { $$('.chart', root).forEach(c => c.classList.add('in')); $$('.meters .tr i', root).forEach(i => i.style.width = i.dataset.w + '%'); }); }
};
