/* ===== 班组长 · 授权认证：照《作业授权认证表》汇总表与高 / 中 / 初级分表，逐人逐模块授权状态、★ 模块覆盖与断层、核心业务自主实施率，
   班组长逐格确认授权，生成认证表并导出（原九类核心技能已迁移到对应模块） ===== */
const AUTHPG = {
  tab() { return ['sum', '高', '中', '初', 'gap'].includes(S.sub) ? S.sub : 'sum'; },
  lvOf(tab) { return tab === 'sum' || tab === 'gap' ? '高' : tab; },
  people(tab) { return tab === 'sum' || tab === 'gap' ? PEOPLE : PEOPLE.filter(p => authLv(p) === tab); },
  mark(v) { return v === 'A' ? '<i class="au a">√</i>' : v === 'B' ? '<i class="au b">培</i>' : '<i class="au n"></i>'; },
  table(tab) {
    const L = this.people(tab), lv = this.lvOf(tab);
    const head = '<tr><th style="width:34px">序号</th><th style="width:58px">技能单元</th><th style="width:44px">模块序号</th><th class="au-m">作业授权认证模块</th><th style="width:34px">标星</th>' + L.map(p => '<th class="au-p" data-act="au-person" data-who="' + h(p.n) + '"><b>' + h(p.n) + '</b><span>' + h(authLvName(p).replace('作业员', '')) + '</span></th>').join('') + '</tr>';
    const body = AUTH_UNITS.map((u, ui) => { const mods = SKILL9.filter(s => s.unit === u); return mods.map((s, mi) => { const i = SKILL9.indexOf(s);
      return '<tr class="' + (s.star[lv] ? 'st' : '') + '">' + (mi === 0 ? '<td rowspan="' + mods.length + '" class="mono c">' + (ui + 1) + '</td><td rowspan="' + mods.length + '" class="c"><b>' + h(u) + '</b></td>' : '') +
        '<td class="mono c">' + h(s.k) + '</td><td>' + h(s.n) + '</td><td class="c star">' + (s.star[lv] ? '★' : '') + '</td>' +
        L.map(p => { const x = skill9Of(p); const own = s.star[authLv(p)]; return '<td class="c au-c' + (own ? ' own' : '') + '" data-act="au-cell" data-who="' + h(p.n) + '" data-k="' + s.k + '">' + this.mark(x.q[i]) + '</td>'; }).join('') + '</tr>'; }).join(''); }).join('');
    const foot = '<tr class="au-foot"><td colspan="5"><b>本岗级★模块已授权 · 核心业务自主实施率</b></td>' + L.map(p => { const x = skill9Of(p); return '<td class="c"><span class="mono">' + x.mustA + '/' + x.mustN + '</span><br><b class="mono ' + (x.rate >= 80 ? 'g' : x.rate < 50 ? 'b' : '') + '">' + x.rate + '%</b></td>'; }).join('') + '</tr>';
    const sign = LS.get('auth_sign', null);
    return '<div class="au-hd"><b>技能类岗位胜任能力评价作业授权认证表——配网运行维护' + (tab === 'sum' ? '汇总表' : ' · ' + { 高: '高级作业员', 中: '中级作业员', 初: '初级作业员' }[tab]) + '</b><span class="note">负责人签名：' + (sign ? h(sign.by) : '　　　') + '　单位：' + h(TEAM.full) + '</span></div>' +
      '<div class="tbl au-wrap"><table class="t aut">' + head + body + foot + '</table></div>' +
      '<div class="au-ft"><span>班组授权人：<b>' + (sign ? h(sign.by) : '　　　　') + '</b></span><span>授权时间：<b class="mono">' + (sign ? h(sign.d) : '　　　　') + '</b></span></div>';
  },
  gaps() { return skillCover().filter(c => c.must).map(c => { const ages = c.a.map(p => p.age); const avg = ages.length ? Math.round(ages.reduce((s, x) => s + x, 0) / ages.length) : 0; const young = ages.length ? Math.min.apply(null, ages) : 0;
    const risk = c.a.length <= 2 ? '高' : c.a.length <= 4 && young >= 35 ? '高' : c.a.length <= 4 ? '中' : '低';
    const cand = (c.b.length ? c.b : PEOPLE.filter(p => p.post !== '班长' && skill9Of(p).q[SKILL9.indexOf(c.s)] !== 'A' && (c.s.need || []).every(x => p.cert.includes(x)))).slice().sort((a, b) => a.age - b.age)[0];
    return Object.assign({}, c, { avg, young, risk, cand }); }); },
  gapHTML(list) { const G = (list || this.gaps()).slice().sort((a, b) => ({ 高: 0, 中: 1, 低: 2 }[a.risk] - { 高: 0, 中: 1, 低: 2 }[b.risk])); const plan = LS.get('plan', []);
    return '<div class="tbl"><table class="t"><tr><th>模块</th><th>技能单元</th><th>已授权</th><th>培训中</th><th>本年实操</th><th>已授权者年龄</th><th>断层风险</th><th>建议培养</th><th></th></tr>' +
      G.map(g => '<tr class="' + (g.risk === '高' ? 'hl' : '') + '"><td><b class="mono">' + h(g.s.k) + '</b> ' + h(g.s.n) + '</td><td class="note">' + h(g.s.unit) + '</td><td>' + (g.a.map(p => '<span class="tag ok">' + h(p.n) + '</span>').join('') || '<span class="note">无</span>') + '</td><td>' + (g.b.map(p => '<span class="tag w">' + h(p.n) + '</span>').join('') || '<span class="note">无</span>') + '</td><td class="mono">' + g.n + '</td><td class="note">' + (g.a.length ? '均 ' + g.avg + ' 岁 · 最小 ' + g.young + ' 岁' : '—') + '</td><td>' + MG.light(g.risk === '高' ? 'bad' : g.risk === '中' ? 'w' : 'ok', g.risk) + '</td><td>' + (g.cand ? '<b>' + h(g.cand.n) + '</b><span class="note">（' + g.cand.age + ' 岁）</span>' : '—') + '</td><td>' + (g.risk === '低' ? '' : plan.some(x => x.why === '授权断层 ' + g.risk && x.t.indexOf(g.s.k) === 0) ? '<span class="tag ok">已排</span>' : '<button class="s" data-act="au-teach" data-k="' + g.s.k + '">排带教取证</button>') + '</td></tr>').join('') + '</table></div>'; },
  unitHTML() { return '<div class="au-units">' + AUTH_UNITS.map(u => { const r = authUnitRate(PEOPLE, u); const all = SKILL9.filter(s => s.unit === u).length; const star = SKILL9.filter(s => s.unit === u && s.star['高']).length;
    return '<div class="au-u" data-act="au-unit" data-u="' + h(u) + '"><b>' + h(u) + '</b><span class="note">' + all + ' 个模块 · ★ ' + star + '</span>' + (r.pct == null ? '<em class="note">本单元无★模块</em>' : MG.bar(r.pct, r.pct >= 80 ? 'ok' : r.pct >= 60 ? 'w' : 'bad') + '<span class="mono">' + r.a + '/' + r.n + ' · ' + r.pct + '%</span>') + '</div>'; }).join('') + '</div>'; }
};
PAGES.auth = {
  render() { const tab = AUTHPG.tab(); const G = AUTHPG.gaps(); const hi = G.filter(g => g.risk === '高'); const rate = authRate(); const cov3 = G.filter(g => g.a.length >= 3).length; const trainN = PEOPLE.reduce((s, p) => s + skill9Of(p).mustB, 0); const sign = LS.get('auth_sign', null);
    return cmdHTML(['哪些★模块只有一两个人授权', '刘一鸣还差哪些模块', '把高风险模块都排带教', '生成本季度授权认证表']) +
      pageHead('授权认证', '作业授权认证表（配网运行维护） · 7 个技能单元 42 个模块 · ★ 按岗级标注必须取得授权的模块', '<button class="s g" data-act="au-export">导出认证表</button>' + (sign ? '<span class="tag ok">已确认 ' + h(sign.d) + '</span>' : '<button class="s" data-act="au-sign">确认本期授权</button>')) +
      '<div class="grid4"><div class="card kpi"><span>核心业务自主实施率</span><b class="' + (rate >= 80 ? 'g' : rate >= 60 ? 'w' : 'bad') + '">' + rate + '%</b><em>已授权★模块 ÷ 本岗级应授权★模块，全班 ' + PEOPLE.length + ' 人合计；星级五星线 ≥ 35%</em></div>' +
      '<div class="card kpi"><span>★模块 ≥ 3 人授权</span><b>' + cov3 + '/' + G.length + '</b><em>高级作业员口径 ' + G.length + ' 个★模块</em></div>' +
      '<div class="card kpi"><span>断层风险 高</span><b class="bad">' + hi.length + '</b><em>' + h(hi.map(g => g.s.k + ' ' + g.s.n).join('、') || '无') + '</em></div>' +
      '<div class="card kpi"><span>★模块培训中</span><b class="w">' + trainN + '</b><em>人次，取得授权后自主实施率随之上升</em></div></div>' +
      '<div class="card"><div class="h"><b>七个技能单元 · 自主实施率</b><span>点单元看模块明细</span></div>' + AUTHPG.unitHTML() +
        '<div class="legend-note">颜色说明：绿 = 单元内★模块授权率 ≥ 80%；黄 = 60%–79%；红 = 低于 60%；灰字 = 本单元没有★模块，不计入自主实施率。</div></div>' +
      '<div class="card"><div class="h"><b>作业授权认证表</b><span>点格看明细并确认授权 · 点姓名看此人缺口</span></div>' +
        tabsHTML([{ k: 'sum', n: '汇总表 · ' + PEOPLE.length + ' 人' }, { k: '高', n: '高级作业员 · ' + AUTHPG.people('高').length + ' 人' }, { k: '中', n: '中级作业员 · ' + AUTHPG.people('中').length + ' 人' }, { k: '初', n: '初级作业员 · ' + AUTHPG.people('初').length + ' 人' }, { k: 'gap', n: '★模块断层风险' }], tab) +
        (tab === 'gap' ? '<div class="h" style="margin-top:6px"><span>已授权 ≤ 2 人，或 ≤ 4 人且全部 35 岁以上为高；≤ 4 人为中</span><div class="r"><button class="s" data-act="au-teachall">高风险全部排带教取证</button></div></div>' + AUTHPG.gapHTML() +
          '<div class="legend-note">颜色说明：红灯 = 断层风险高；黄灯 = 断层风险中；绿灯 = 覆盖充足。绿标签为已授权人员，黄标签为培训中人员；整行底色标出高风险模块。</div>'
          : AUTHPG.table(tab) + '<div class="legend-note">说明：√ = 已取得授权；培 = 培训中，尚未授权；空白 = 未授权。★ 为' + (tab === 'sum' ? '高级作业员' : { 高: '高级作业员', 中: '中级作业员', 初: '初级作业员' }[tab]) + '必须取得授权的模块，整行浅色底标出；每人本岗级的★格有细框。底行百分比：绿 ≥ 80%，红 < 50%。</div>') + '</div>'; },
  after() { CH.mount($('#main')); }
};
Object.assign(ACT, {
  'au-cell'(el) { const p = P[el.dataset.who]; const s = SKILL9.find(x => x.k === el.dataset.k); if (!p || !s) return; const i = SKILL9.indexOf(s); const x = skill9Of(p); const v = x.q[i]; const lack = (s.need || []).filter(c => !p.cert.includes(c)); const own = s.star[authLv(p)];
    modal('<div class="t">' + h(p.n) + ' · ' + h(s.k) + ' ' + h(s.n) + '</div><div class="tbl"><table class="t"><tr><th style="width:120px">技能单元</th><td>' + h(s.unit) + '</td></tr><tr><th>本人岗级</th><td>' + h(authLvName(p)) + '　' + (own ? '<span class="tag bad">本岗级★ 必须授权</span>' : '<span class="note">本岗级非★模块</span>') + '</td></tr><tr><th>当前状态</th><td>' + (v === 'A' ? '<span class="tag ok">已授权</span>' : v === 'B' ? '<span class="tag w">培训中</span>' : '<span class="tag">未授权</span>') + '</td></tr><tr><th>本年实操</th><td class="mono">' + x.n[i] + ' 次</td></tr><tr><th>需持证</th><td>' + ((s.need || []).length ? s.need.map(c => p.cert.includes(c) ? '<span class="tag ok">' + h(c) + '</span>' : '<span class="tag bad">缺 ' + h(c) + '</span>').join('') : '<span class="note">不需要</span>') + '</td></tr></table></div>' +
      (lack.length ? '<div class="alert bad">' + MG.light('bad') + '缺 ' + h(lack.join('、')) + '，取证前不能确认授权</div>' : '') +
      '<div class="bt">' + (v !== 'A' && !lack.length ? '<button data-act="au-set" data-who="' + h(p.n) + '" data-k="' + s.k + '" data-v="A">确认授权</button>' : '') + (v !== 'B' ? '<button class="g" data-act="au-set" data-who="' + h(p.n) + '" data-k="' + s.k + '" data-v="B">标为培训中</button>' : '') + (v !== '-' ? '<button class="g" data-act="au-set" data-who="' + h(p.n) + '" data-k="' + s.k + '" data-v="-">撤销授权</button>' : '') + '<span class="cf">授权结论由班组长确认后生效</span></div>'); },
  'au-set'(el) { const n = el.dataset.who, k = el.dataset.k, v = el.dataset.v; DB.setSkillQ(n, k, v); if (LS.get('auth_sign', null)) LS.set('auth_sign', null); $('#modal').hidden = true; render(); const p = P[n]; const x = skill9Of(p); XW.fly(n + ' · ' + k + ' · ' + { A: '已授权', B: '培训中', '-': '未授权' }[v]); XW.answer(n + '的「' + k + ' ' + (SKILL9.find(s => s.k === k) || {}).n + '」改为' + { A: '已授权', B: '培训中', '-': '未授权' }[v] + '，本岗级★模块自主实施率现在 ' + x.rate + '%，班组 ' + authRate() + '%。本期认证表需要重新确认。', null, { confirm: false }); },
  'au-person'(el) { const p = P[el.dataset.who]; if (!p) return; const x = skill9Of(p); const lack = SKILL9.filter((s, i) => x.must[i] && x.q[i] !== 'A');
    XW.answer(p.n + '是' + authLvName(p) + '，本岗级★模块 ' + x.mustN + ' 个，已授权 ' + x.mustA + ' 个，自主实施率 ' + x.rate + '%。' + (lack.length ? '还差：' + lack.map(s => s.k + ' ' + s.n + (x.q[SKILL9.indexOf(s)] === 'B' ? '（培训中）' : '')).join('、') + '。' : '本岗级★模块已全部取得授权。'), null, { confirm: false, speak: false }); },
  'au-unit'(el) { const u = el.dataset.u; const mods = SKILL9.filter(s => s.unit === u); const cov = skillCover();
    modal('<div class="t">' + h(u) + ' · ' + mods.length + ' 个模块</div><div class="tbl"><table class="t"><tr><th>模块</th><th>★</th><th>已授权</th><th>培训中</th><th>本年实操</th></tr>' + mods.map(s => { const c = cov.find(y => y.s.k === s.k); return '<tr><td><b class="mono">' + s.k + '</b> ' + h(s.n) + '</td><td>' + (s.star['高'] ? '★' : '') + '</td><td class="mono">' + c.a.length + '</td><td class="mono">' + c.b.length + '</td><td class="mono">' + c.n + '</td></tr>'; }).join('') + '</table></div><div class="legend-note">★ 为高级作业员必须取得授权的模块；已授权与培训中为本班人数。</div>'); },
  'au-teach'(el) { const g = AUTHPG.gaps().find(x => x.s.k === el.dataset.k); if (!g || !g.cand) return; const m = g.a[0] ? g.a[0].n : '韩雪'; MG.planPush(g.cand.n, g.s.k + ' ' + g.s.n + ' 带教取证（师傅 ' + m + '）', '授权断层 ' + g.risk); DB.notify(g.cand.n, '带教取证 · ' + g.s.k + ' ' + g.s.n + '，师傅 ' + m + '，做满两次独立实操后申请授权', '已发'); render(); XW.answer('排好了：' + g.cand.n + '跟' + m + '做「' + g.s.k + ' ' + g.s.n + '」，做满两次独立实操后由你确认授权。', null, { confirm: false }); },
  'au-teachall'() { const G = AUTHPG.gaps().filter(g => g.risk === '高' && g.cand); let n = 0; G.forEach(g => { const m = g.a[0] ? g.a[0].n : '韩雪'; if (MG.planPush(g.cand.n, g.s.k + ' ' + g.s.n + ' 带教取证（师傅 ' + m + '）', '授权断层 高')) n++; }); render(); XW.fly('已排带教取证 ' + n + ' 项'); XW.answer(n ? '高风险的 ' + G.length + ' 个★模块都排了带教取证：' + G.map(g => g.s.k + ' ' + g.s.n + ' → ' + g.cand.n).join('、') + '。培养与梯队页能看到。' : '高风险模块已经都在计划里了。', null, { confirm: false }); },
  'au-sign'() { const d = DB.now(); LS.set('auth_sign', { by: ROLES.leader.who, d }); DB.log('作业授权', '本期作业授权认证表已确认 · 核心业务自主实施率 ' + authRate() + '%'); DB.notify('陈国安', '配电自动化班本期作业授权认证表已确认：核心业务自主实施率 ' + authRate() + '%，★模块断层风险高 ' + AUTHPG.gaps().filter(g => g.risk === '高').length + ' 个', '已发'); render(); XW.answer('本期认证表确认了，授权人和授权时间已填到表尾，同时报了陈国安。之后任何一格改动，都需要重新确认。', null, { confirm: false }); },
  'au-export'() { const tab = AUTHPG.tab() === 'gap' ? 'sum' : AUTHPG.tab(); const L = AUTHPG.people(tab), lv = AUTHPG.lvOf(tab); const sign = LS.get('auth_sign', null);
    const cell = v => v === 'A' ? '√' : v === 'B' ? '培' : '';
    const rows = SKILL9.map((s, i) => '<tr><td>' + (s === SKILL9.find(x => x.unit === s.unit) ? AUTH_UNITS.indexOf(s.unit) + 1 : '') + '</td><td>' + (s === SKILL9.find(x => x.unit === s.unit) ? s.unit : '') + '</td><td>' + s.k + '</td><td>' + s.n + '</td><td>' + (s.star[lv] ? '★' : '') + '</td>' + L.map(p => '<td style="text-align:center">' + cell(skill9Of(p).q[i]) + '</td>').join('') + '</tr>').join('');
    const title = '技能类岗位胜任能力评价作业授权认证表——配网运行维护' + (tab === 'sum' ? '汇总表' : { 高: '高级作业员', 中: '中级作业员', 初: '初级作业员' }[tab]);
    const html = '<html xmlns:x="urn:schemas-microsoft-com:office:excel"><head><meta charset="utf-8"><style>table{border-collapse:collapse;font-family:"Microsoft YaHei";font-size:10.5pt}td,th{border:.5pt solid #999;padding:4px 6px}th{background:#eef2ee}.t{font-size:14pt;font-weight:bold;border:none;text-align:center}.n{border:none}</style></head><body><table>' +
      '<tr><td class="t" colspan="' + (5 + L.length) + '">' + title + '</td></tr><tr><td class="n" colspan="' + (5 + L.length) + '">负责人签名：' + (sign ? sign.by : '') + '　　单位（盖章）：' + TEAM.full + '</td></tr>' +
      '<tr><th>序号</th><th>技能单元</th><th>模块序号</th><th>作业授权认证模块</th><th>标星</th>' + L.map(p => '<th>' + p.n + '</th>').join('') + '</tr>' + rows +
      '<tr><td colspan="5">本岗级★模块自主实施率</td>' + L.map(p => '<td>' + skill9Of(p).rate + '%</td>').join('') + '</tr>' +
      '<tr><td class="n" colspan="' + (5 + L.length) + '">班组授权人：' + (sign ? sign.by : '') + '　　授权时间：' + (sign ? sign.d : '') + '</td></tr></table></body></html>';
    const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob(['﻿' + html], { type: 'application/vnd.ms-excel;charset=utf-8' })); a.download = title + '.xls'; a.style.display = 'none'; document.body.appendChild(a); a.click(); setTimeout(() => { URL.revokeObjectURL(a.href); a.remove(); }, 800);
    DB.log('文稿', title + ' 已导出'); XW.fly('已导出 · ' + (tab === 'sum' ? '汇总表' : tab + '级')); XW.answer('认证表导出了：' + title + '，' + L.length + ' 人、42 个模块，版式照原表。负责人签名、班组授权人和授权时间' + (sign ? '已按 ' + sign.d + ' 的确认填好。' : '要在「确认本期授权」后才会填上。'), null, { confirm: false, speak: false }); }
});
