/* ===== 文稿中心：十类文稿逐段生成、取数停顿、局部重写、点段落看出处、口径记忆、版本对比、图表附页、待交清单、导出与分享 ===== */
const DOCS = {
  host: null, kind: null, ver: {},
  TYPES: [{ k: 'premeet', n: '班前会材料', due: '每日 07:40' }, { k: 'log', n: '工作日志', due: '每日 18:00' }, { k: 'weekly', n: '周报', due: '周五 17:00' }, { k: 'weekplan', n: '下周计划', due: '周五 17:00' }, { k: 'monthly', n: '月度总结', due: '月末' }, { k: 'monthplan', n: '下月计划', due: '月末' }, { k: 'report', n: '汇报材料', due: '按需' }, { k: 'notice', n: '通知', due: '按需' }, { k: 'plan', n: '培训计划', due: '月初' }, { k: 'minutes', n: '会议纪要', due: '会后' }],
  me() { return XW.mem.get('口径', '本班'); },
  paras(k) { const me = this.me(); const disp = LS.get('dispatch', {})['j5']; const crew = disp ? disp.lead + '、' + disp.crew.join('、') : '韩雪、郭子扬、赵敏'; const lag = PEOPLE.filter(p => p.hours.m < 3).map(p => p.n).join('、'); const due = certsDueWithin(90);
    const M = {
      premeet: ['一、今日安排：塘尾线巡视（吴倩、王安、刘一鸣，09:00）；光明变 10kV 出线柜检查（陈浩、周明，14:00）；志远站 F14 蓄电池消缺并入明日巡视。明日凤凰线更换 #12 杆刀闸，负责人 ' + (disp ? disp.lead : '韩雪') + '。', '二、风险提示：[取一下今日天气……] 台风蓝色预警，最高 34℃。台风影响期间停止登杆，风停后先巡后登；高温连续作业三小时轮换；田寮线 #7 杆拉线锈断已列紧急隐患，经过时保持距离。', '三、学习内容：拉线与杆根检查要点（上月两起拉线锈蚀）；停电作业安措顺序：停电、验电、装设接地线、悬挂标示牌。'],
      log: ['2026-09-03 工作日志。到岗 ' + PEOPLE.filter(p => p.status !== '休假').length + ' 人，林芷若休假。', '完成：塘尾线巡视 #1 至 #30 杆；志远站 F14 复查；光明变出线柜检查。发现隐患 2 处（田寮线 #7 杆拉线锈断，紧急，已登记；塘尾线 #31 杆鸟巢，一般）。', '派工：明日凤凰线更换 #12 杆刀闸，' + crew + '，刘一鸣随队。催办：志远站 F14 缺陷，吴倩明日处理。', '明日计划：凤凰线换刀闸；塘尾线剩余段巡视；周五安全日材料定稿。'],
      weekly: ['本周（9-1 至 9-3）' + me + '完成作业 [取一下本周任务……] 11 项，其中巡视 5、消缺 3、检查 2、拉线更换 1。工作票 3 张，全部合格。', '安全：无违章，发现隐患 3 处（凤凰线 #15 树障、田寮线 #7 拉线锈断、塘尾线 #31 鸟巢），均已登记；志远站 F14 缺陷超期 3 天，已催办。', '人员：黄伟强本周 26 小时、李文博 24 小时，均已提示；下周值班表已按约束排出。', '下周重点：凤凰线换刀闸；台风季拉线专项巡视；安全日活动（周五）。'],
      weekplan: ['下周（9-7 至 9-13）工作计划 · ' + me].concat(DAYS7.map((d, i) => { const js = JOBS_WEEK.filter(j => j.d0 <= i && i <= j.d1); return d + '：' + (js.length ? js.map(j => j.t + '（' + j.who.join('、') + '）').join('；') : '无外勤，室内资料整理') + '。'; })).concat(['风险提示：周一、周二台风影响，登杆作业看风停；周四振荡波试验为高风险作业，负责人韩雪。']),
      monthly: ['一、总体情况：8 月' + me + '共安排作业 [取一下本月任务……] ' + MONTH.jobs + ' 项，完成 ' + MONTH.jobsDone + ' 项，完成率 ' + Math.round(MONTH.jobsDone / MONTH.jobs * 100) + '%；工作票 ' + MONTH.tickets + ' 张，合格 ' + MONTH.ticketsOK + ' 张，合格率 [取一下两票合格率……] ' + Math.round(MONTH.ticketsOK / MONTH.tickets * 100) + '%。', '二、安全管理：开展安全日活动 ' + MONTH.safetyDays + ' 次、事故通报学习 ' + MONTH.incidentStudy + ' 次；发现缺陷 ' + MONTH.defectsFound + ' 处，闭环 ' + MONTH.defectsClosed + ' 处，1 处超期正在处理。', '三、人员与培训：全班 ' + PEOPLE.length + ' 人，年度学时平均完成 [取一下学时台账……] ' + Math.round(PEOPLE.reduce((s, p) => s + p.hours.done / p.hours.req, 0) / PEOPLE.length * 100) + '%；本月学时未完成 ' + PEOPLE.filter(p => p.hours.m < 3).length + ' 人（' + lag + '）；证书 90 天内到期 ' + due.length + ' 人（' + due.map(c => c.who).join('、') + '），已安排复审。', '四、荣誉：' + MONTH.honors.join('；') + '。', '五、存在问题：黄伟强连续三周工作量最高，任务分配需均衡；初级作业员理论测试通过率偏低。', '六、下月计划：台风季拉线专项巡视；继保专才课程排给陈浩、周明、刘一鸣；完成三张到期证书复审。'],
      monthplan: ['10 月工作计划（初稿）', '一、重点：台风季拉线与杆根专项巡视收尾（剩余凤凰线 #20 至 #40 杆）；配网自动化终端年度巡检第三批 [取一下终端台账……] 48 台；电缆振荡波试验 3 段。', '二、缺陷：志远站 F14 蓄电池更换验收；塘家公用柜锁具；凤凰线 #15 树障复查。', '三、培训：继保专才《配网保护整定实用化》全员；实操：开关柜局放检测考核（吴倩、郭子扬）。', '四、安全：安全日 2 次（10-9 汛后配电房检查、10-23 登杆作业专题）；两票合格率保持 100%。', '五、人员：黄伟强、赵敏证书复审；王安、陈浩、周明学时补课。'],
      report: ['凤凰供电所配电运维一班 9 月工作汇报要点：', '1. 任务：本月 ' + MONTH.jobs + ' 项作业完成 ' + MONTH.jobsDone + ' 项，两票合格率 100%。', '2. 安全：隐患 ' + MONTH.defectsFound + ' 处、闭环 ' + MONTH.defectsClosed + ' 处；台风季已启动拉线专项巡视。', '3. 人员：证书到期 ' + due.length + ' 人已安排复审；学时落后 ' + PEOPLE.filter(p => p.hours.m < 3).length + ' 人已排课。', '4. 需要所里支持：增加一名高级作业员，缓解黄伟强、李文博工时集中的问题。'],
      notice: ['通知：本周五（9-11）15:00 在所会议室开展安全日活动，主题"台风季线路巡视与登杆作业"，全班参加，外勤人员提前安排。', '请各位提前看一遍作业指导书"停电作业安措"一节，会上考问。—— 赵立群'],
      plan: ['9 月培训计划（' + me + '）：', '1. 继保专才《10kV 光纤电流差动保护》：刘一鸣（补考下周五）、陈浩、周明，9-15 前完成理论测试。', '2. 《配网 10kV 电力电缆试验》：王安、吴倩，配合 9 月电缆试验旁站。', '3. 实操：中压倒闸操作评分表考核，郭子扬、赵敏，9-20。', '4. 师带徒：刘一鸣跟黄伟强两次继保旁站。' + (LS.get('plan', []).length ? '\n5. 新增：' + LS.get('plan', []).map(p => p.who + '《' + p.t + '》' + p.when).join('；') : '')],
      minutes: ['班前会纪要 · 2026-09-03 07:50 · 主持 赵立群 · 到会 11 人，林芷若休假。', '1. 通报田寮线 #7 杆拉线锈断隐患，王安今日现场确认断口。', '2. 明日凤凰线换刀闸派工：' + crew + '，刘一鸣随队；台风期间停止登杆。', '3. 志远站 F14 缺陷超期，吴倩明日处理。', '4. 周五安全日，主题台风季登杆作业。']
    }; return M[k] || M.premeet; },
  chips(k) { const c = [{ k: 'short', n: '口气再简短些' }, { k: 'me', n: '"本班"改成"我班"' }]; if (['premeet', 'monthly', 'weekly', 'weekplan'].includes(k)) c.unshift({ k: 'typhoon', n: '安全那段加上台风应对' }); if (['monthly', 'report'].includes(k)) c.push({ k: 'data', n: '补上缺陷闭环明细' }); if (k === 'monthly') c.push({ k: 'formal', n: '口径改成所里例会版' }); c.push({ k: 'undo', n: '回退上一步' }); return c; },
  /* 每段的出处（点段落她照亮台账） */
  source(text) { if (/工作票|两票|合格率/.test(text)) return { title: '两票台账 · 本月', cols: ['票号', '类型', '任务', '负责人', '状态'], rows: TICKETS.map(t => [t.no, t.kind, t.task, t.lead, (LS.get('tickets', {})[t.no] || {}).st || '待审']).concat([['配一 2026-0901-02', '第一种工作票', '凤凰线 #9 杆拉线更换', '黄伟强', '合格'], ['配一 2026-0902-01', '第二种工作票', '志远站 F14 消缺', '黄伟强', '合格']]), me: [0, 1, 2, 3, 4], text: '这段的数字来自两票台账，本月 12 张全部合格。' };
    if (/学时|证书|复审/.test(text)) return { title: '学时与证书 · 2026', cols: ['姓名', '本月学时', '年度', '90 天内到期证书'], rows: PEOPLE.map(p => [p.n, p.hours.m + '/5', p.hours.done + '/' + p.hours.req, certsDueWithin(90).filter(c => c.who === p.n).map(c => c.name).join('、') || '—']), me: PEOPLE.map((p, i) => (p.hours.m < 3 || certsDueWithin(90).some(c => c.who === p.n)) ? i : -1).filter(i => i >= 0), text: '这段的数字来自学时台账和证书台账，我把学时没完成的和证书到期的行照亮了。' };
    if (/缺陷|隐患|闭环/.test(text)) return { title: '缺陷台账 · 本月', cols: ['缺陷', '等级', '登记', '状态'], rows: DEFECTS.concat(DEFECTS2).map(d => [d.t, d.lv, d.reg, SAFETYPG.stOf(d)]), me: [0, 1, 2, 3, 4, 5, 6, 7], text: '这段来自缺陷台账，八条都在这里。' };
    if (/工时|小时|工作量/.test(text)) return { title: '工时台账 · 本周', cols: ['日期', '人员', '作业', '小时'], rows: HOURS.map(r => [r.d, r.who, r.job, r.h]), me: HOURS.map((r, i) => /黄伟强|李文博/.test(r.who) ? i : -1).filter(i => i >= 0), sumCol: 3, unit: 'h', text: '这段来自工时台账，黄伟强和李文博的行照亮了。' };
    if (/任务|作业|完成/.test(text)) return { title: '任务台账 · 本月', cols: ['日期', '类型', '线路 / 站', '人员', '状态'], rows: TASKS_M.map(t => [t.d, t.t, t.line, t.who, t.st]), me: TASKS_M.map((t, i) => t.st !== '已完成' ? i : -1).filter(i => i >= 0), text: '这段来自任务台账，没完成的三项照亮了。' };
    if (/安全日|通报/.test(text)) return { title: '安全活动台账', cols: ['日期', '活动', '人数'], rows: SAFETY_ACT.map(a => [a.d, a.t, a.who]), me: [0, 1, 2], text: '这段来自安全活动台账。' };
    return null; },
  saveVersion(k, note) { const docs = LS.get('docs', {}); const d = docs[k]; if (!d) return; d.versions = d.versions || []; d.versions.push({ v: d.versions.length + 1, ts: Date.now(), body: DOCGEN.text(this.host), note: note || '' }); d.body = DOCGEN.text(this.host); d.ver = d.versions.length; LS.set('docs', docs); this.renderVers(k); },
  renderVers(k) { const d = LS.get('docs', {})[k]; const host = $('#vers'); if (!host) return; host.innerHTML = d && d.versions ? d.versions.slice().reverse().map(v => '<div data-act="doc-ver" data-k="' + k + '" data-v="' + v.v + '"><span style="font-size:11.5px;color:var(--ink)">v' + v.v + ' <span class="note">' + new Date(v.ts).toTimeString().slice(0, 5) + (v.note ? ' · ' + h(v.note) : '') + '</span></span><span class="tag">' + (v.v === d.versions.length ? '当前' : '回看') + '</span></div>').join('') : '<div class="note">还没有版本</div>'; },
  gen(k) { this.kind = k; const host = $('#dochost'); this.host = host; $$('.doclist a').forEach(a => a.classList.toggle('on', a.dataset.k === k)); const t = this.TYPES.find(x => x.k === k); $('#doctitle').textContent = t.n; const docs = LS.get('docs', {}); const ver = (docs[k] && docs[k].versions ? docs[k].versions.length : 0); const memo = XW.mem.get('口径') === '我班' && /本班|我班/.test(this.paras(k).join('')); if (memo) XW.answer('按你上次的习惯，这次直接写"我班"。', null, { confirm: false, speak: false });
    DOCGEN.stream(host, this.paras(k), { title: t.n + ' · ' + TODAY, chips: this.chips(k), ver, done: () => { const docs = LS.get('docs', {}); docs[k] = docs[k] || { t: t.n }; docs[k].t = t.n; docs[k].ts = Date.now(); LS.set('docs', docs); this.saveVersion(k, '生成'); $$('#dochost p').forEach(p => { p.dataset.act = 'doc-src'; p.title = '点一下她说这段的出处'; }); $('#docbt').innerHTML = '<button data-act="doc-export">导出 / 打印</button><button class="g" data-act="doc-share">发给所里</button><button class="g" data-act="doc-charts">图表附页</button><button class="g" data-act="doc-regen">重新生成</button>'; XW.answer(t.n + '写好了，哪段不合适点那段下面的芯片，我只改那一段；点任何一段，我说它的数从哪张台账来。', null, { speak: false, confirm: false }); } });
    XW.type($('#xwsub'), t.n + '我写一版，写到数字的地方我要取一下数。', 45); },
  chip(k) { const host = this.host || $('#dochost') || $('#sddoc'); if (!host) return; const ps = $$('p', host).filter(p => !p.classList.contains('old'));
    if (k === 'typhoon') { const idx = ps.findIndex(p => /安全|风险/.test(p.textContent)); const i = idx < 0 ? Math.min(2, ps.length - 1) : idx; const old = ps[i].textContent; const add = old.includes('台风') ? old.replace(/。$/, '') + '；台风影响期间停止登杆作业，风停后先巡后登。' : old.replace(/^(.*?[:：])/, '$1台风影响期间停止登杆作业，风停后先巡后登；'); DOCGEN.rewrite(host, +ps[i].dataset.i, add, '安全这段我加了台风期间的登杆管控，旧的那段划掉了，你看这样行不行。'); }
    else if (k === 'short') DOCGEN.shorten(host, '每段都缩短了，念下来大概两分钟。');
    else if (k === 'me') { XW.mem.set('口径', '我班'); ps.forEach(p => { if (/本班/.test(p.textContent)) DOCGEN.rewrite(host, +p.dataset.i, p.textContent.replace(/本班/g, '我班')); }); XW.answer('改成"我班"了。这个说法我记下了，以后周报、月度总结都这么写。', null, { confirm: false, speak: false }); }
    else if (k === 'data') { const i = ps.findIndex(p => /缺陷|人员/.test(p.textContent)); const p = ps[i < 0 ? ps.length - 1 : i]; DOCGEN.rewrite(host, +p.dataset.i, p.textContent.replace(/。$/, '') + (/缺陷/.test(p.textContent) ? '。闭环明细：凤凰线 #9 杆拉线锈蚀（9-1 消缺）、志远站电缆沟积水（9-1 关闭）、塘家公用柜锁具（处理中）、凤凰线 #15 树障（处理中）、凤凰线 #18 绝缘子（待验收）、田寮线 #7 拉线锈断（已登记）、志远站 F14 蓄电池（超期，已催办）。' : '。人员安排：韩雪牵头巡视，黄伟强、李文博轮流，陈浩、周明、刘一鸣随队学习。'), '明细补上了，都是从台账取的。'); }
    else if (k === 'formal') { ps.forEach(p => { if (/^一、|^二、/.test(p.textContent)) DOCGEN.rewrite(host, +p.dataset.i, p.textContent.replace(/共安排/, '按所月度计划安排').replace(/开展/, '按所安全生产例会要求开展')); }); XW.answer('口径改成所里例会版了，只动了前两段的说法，数字没变。', null, { confirm: false, speak: false }); }
    else if (k === 'undo') { const news = $$('p.new', host); if (!news.length) { XW.answer('没有可回退的改动。', null, { confirm: false, speak: false }); return; } const last = news[news.length - 1]; const oldp = last.previousElementSibling; if (oldp && oldp.classList.contains('old')) oldp.classList.remove('old'); last.remove(); XW.answer('回退了上一步，恢复成原来的那段。', null, { confirm: false, speak: false }); }
    if (this.kind && ['typhoon', 'short', 'me', 'data', 'formal'].includes(k) && $('#vers')) XW.at(2600, () => this.saveVersion(this.kind, { typhoon: '加台风应对', short: '缩短', me: '改口径', data: '补明细', formal: '例会版' }[k])); },
  dueList() { const docs = LS.get('docs', {}); return [{ k: 'log', n: '今日工作日志', when: '今天 18:00' }, { k: 'weekly', n: '本周周报', when: '周五 17:00' }, { k: 'weekplan', n: '下周计划', when: '周五 17:00' }, { k: 'monthly', n: '8 月月度总结', when: '9-5 前' }, { k: 'plan', n: '9 月培训计划', when: '已过期 2 天' }].map(d => ({ ...d, done: !!docs[d.k] })); }
};
PAGES.docs = {
  render() { const docs = LS.get('docs', {}); const mem = XW.mem.all(); return cmdHTML(['写今天的班前会材料', '生成本月的月度总结', '安全那段加上台风应对', '按上次口径写周报', '写下周计划']) + pageHead('文稿中心', '十类文稿 · 逐段生成 · 每个数字可追溯到台账 · 版本可回看') +
    '<div class="grid2" style="grid-template-columns:240px 1fr;flex:1;align-items:start"><div><div class="card"><div class="h"><b>文稿类型</b></div><div class="doclist">' + DOCS.TYPES.map(t => '<a data-act="doc-gen" data-k="' + t.k + '"><b>' + h(t.n) + '</b><span>' + (docs[t.k] ? 'v' + (docs[t.k].ver || 1) : h(t.due)) + '</span></a>').join('') + '</div></div>' +
    '<div class="card" style="margin-top:10px"><div class="h"><b>待交</b><span>按截止排</span></div><div class="jobs">' + DOCS.dueList().map(d => '<div data-act="doc-gen" data-k="' + d.k + '" style="cursor:pointer"><span style="font-size:11.5px;color:var(--ink)">' + h(d.n) + '<br><span class="note">' + h(d.when) + '</span></span><span class="tag ' + (d.done ? 'ok' : /过期/.test(d.when) ? 'bad' : 'w') + '">' + (d.done ? '已写' : '待写') + '</span></div>').join('') + '</div></div>' +
    '<div class="card" style="margin-top:10px"><div class="h"><b>她记住的口径</b></div>' + (Object.keys(mem).length ? Object.keys(mem).map(k => '<div class="note" style="color:var(--ink);margin:3px 0">' + h(k) + '：<b>' + h(mem[k]) + '</b></div>').join('') : '<div class="note">改一次措辞她就记住，下次沿用</div>') + '</div>' +
    '<div class="card" style="margin-top:10px"><div class="h"><b>已保存</b></div><div class="doclist">' + (Object.keys(docs).filter(k => !DOCS.TYPES.some(t => t.k === k)).map(k => '<a data-act="doc-open" data-k="' + h(k) + '"><b>' + h(docs[k].t) + '</b></a>').join('') || '<div class="note">暂无</div>') + '</div></div></div>' +
    '<div><div class="card"><div class="h"><b id="doctitle">文稿</b><span>由班组长确认后使用</span><div class="r" id="docbt"></div></div><div class="doc" id="dochost"><div class="empty">点左边的类型，她当着你的面写</div></div><div id="docapp" class="docapp" style="display:none"></div></div>' +
    '<div class="grid2" style="margin-top:10px"><div class="card"><div class="h"><b>版本</b><span>点一版回看</span></div><div class="jobs" id="vers"><div class="note">还没有版本</div></div></div><div class="card"><div class="h"><b>本月文稿</b><span>写了几份</span></div>' + CH.mini.cols([['班前会', 22], ['日志', 22], ['周报', 4], ['纪要', 8], ['通知', 6], ['总结', 1]].map(([n, v], i) => ({ n, v, c: CPAL[i % 6] })), { max: 26, h: 110, labels: true }) + '</div></div></div></div>'; },
  after() { CH.mount($('#main')); if (S.sub && DOCS.TYPES.some(t => t.k === S.sub)) XW.at(200, () => DOCS.gen(S.sub)); }
};
Object.assign(ACT, {
  'doc-gen'(el) { if (S.page !== 'docs') { ensure('docs', () => DOCS.gen(el.dataset.k)); return; } DOCS.gen(el.dataset.k); },
  'doc-open'(el) { const d = LS.get('docs', {})[el.dataset.k]; if (!d) return; $('#doctitle').textContent = d.t; $('#dochost').innerHTML = d.body.split('\n').map(p => '<p>' + h(p) + '</p>').join('') + '<div class="foot">以上内容为初稿与参考，由班组长确认后使用</div>'; $('#docbt').innerHTML = '<button data-act="doc-export">导出 / 打印</button>'; },
  'doc-chip'(el) { DOCS.chip(el.dataset.chip); },
  'doc-src'(el) { const src = DOCS.source(el.textContent); if (src) { XW.spot(src); } else XW.answer('这段是她按班组约定和当天安排写的，没有取数。', null, { confirm: false }); },
  'doc-ver'(el) { const d = LS.get('docs', {})[el.dataset.k]; const v = d.versions.find(x => x.v === +el.dataset.v); const cur = d.versions[d.versions.length - 1]; $('#dochost').innerHTML = '<h5>' + h(d.t) + ' · v' + v.v + (v.v !== cur.v ? '（对照当前 v' + cur.v + '）' : '') + '</h5>' + v.body.split('\n').map((p, i) => { const now = cur.body.split('\n')[i] || ''; return '<p class="' + (v.v !== cur.v && now !== p ? 'old' : '') + '">' + h(p) + '</p>' + (v.v !== cur.v && now !== p && now ? '<p class="new">' + h(now) + '</p>' : ''); }).join('') + '<div class="foot">v' + v.v + ' · ' + new Date(v.ts).toLocaleString() + '</div>'; XW.answer('这是 v' + v.v + (v.v !== cur.v ? '，和当前版本不同的段落我用划掉加新段标出来了。' : '，就是当前版本。'), null, { confirm: false, speak: false }); },
  'doc-export'() { window.print(); },
  'doc-share'() { XW.fly('已发送 所长 陈国安 · ' + ($('#doctitle').textContent || '文稿')); XW.answer('发给所里了，所长那边能看到你确认后的版本。', null, { confirm: false }); },
  'doc-charts'() { const app = $('#docapp'); if (!app) return; const on = app.style.display === 'none'; app.style.display = on ? '' : 'none'; if (on) { app.innerHTML = '<div class="note" style="margin:8px 0 4px">图表附页 · 与正文数字同源</div><div class="grid3"><div>' + CH.mini.donut([['巡视', 14], ['消缺', 9], ['检查', 9], ['检修', 6]].map(([k, v], i) => ({ k, v, c: CPAL[i] })), { hero: '35/38', sub: '本月任务' }) + '</div><div>' + CH.mini.line([{ n: '合格率', vals: TICKET_M.n.map((n, i) => Math.round(TICKET_M.ok[i] / n * 100)), c: CPAL[0], area: true }], TICKET_M.m, { max: 100, pct: true, h: 128 }) + '</div><div>' + CH.mini.bars(PEOPLE.slice(1).map(p => ({ n: p.n, v: p.hours.done, c: p.hours.done < 40 ? CPAL[1] : CPAL[4] })), { max: 60, unit: '', h: 11 }) + '</div></div>'; CH.mount(app); XW.answer('附了三张图：任务类型、两票合格率逐月、每人年度学时。打印时会跟在正文后面。', null, { confirm: false, speak: false }); } },
  'doc-regen'() { if (DOCS.kind) DOCS.gen(DOCS.kind); }
});
