/* ===== 今日工作台（班组长）：周报第 29 期驱动 —— 她先开口，三张决策卡随话浮出；主线：交接试验与验收派工（四条规则 → 推荐排除理由 → 确认 → 班前会材料） ===== */
const HOMEPG = {
  st() { return { disp: LS.get('dispatch', {})[MAINLINE], urged: LS.get('defects', {})['d5'], d5: (DB.defect('d5') || {}).st || '', focus: LS.get('nodefocus') }; },
  pending() { const s = this.st(); return DB.transfers().filter(t => t.st === '待确认' && (t.to === TEAM.name || t.from === TEAM.name)).length + (s.disp ? 0 : 1) + (s.urged || /已派|进行中|待验收|已关闭|催办|已登记/.test(s.d5) ? 0 : 1) + (s.focus ? 0 : 1); },
  /* 周报里光明局要盯的节点：按名次从差到好取前几项 */
  wkFocus() { return WK29.items.filter(i => typeof i.vals[0] === 'number' && i.node).map(i => ({ it: i, rank: WK29.rank(i.k), node: NODES.find(n => n.id === i.node) })).sort((a, b) => b.rank - a.rank).slice(0, 5); },
  chartsHTML() {
    const card = (t, sub, body) => '<div class="card chart"><div class="h"><b>' + h(t) + '</b><span>' + h(sub) + '</span></div>' + body + '</div>';
    const legend = items => '<div class="legend">' + items.map(([c, n]) => '<span><i style="background:' + c + '"></i>' + h(n) + '</span>').join('') + '</div>';
    const TL = DB.taskLedger(); const types = DB.typeCounts().map(([k, v]) => ({ k, v, done: TL.filter(t => t.t === k && /已完成|已关闭/.test(t.st)).length }));
    const bars = PEOPLE.filter(p => p.post !== '班长').map(p => ({ n: p.n, v: p.week })).sort((a, b) => b.v - a.v);
    const avg = MODS.map((m, i) => PEOPLE.reduce((s, p) => s + PEOPLEPG.lv(p)[i], 0) / PEOPLE.length);
    const meters = [{ k: 'online', n: '终端在线率', v: WK29.val('online') / 100, txt: WK29.val('online') + '%', tip: '周报第 29 期 · 光明 99.82%，全市第 ' + WK29.rank('online') + ' · 点开看周报指标台账' }, { k: 'remote', n: '遥控成功率', v: WK29.val('remote') / 100, txt: WK29.val('remote') + '%', tip: '周报第 29 期 · 光明 98.9%，全市第 ' + WK29.rank('remote') }, { k: 'close', n: '缺陷闭环率', v: WK29.val('close') / 100, txt: WK29.val('close') + '%', tip: '周报第 29 期 · 累计 543 单闭环 532 单' }, { k: 'morning', n: '晨操计划完成', v: WK29.val('morning') / 100, txt: WK29.val('morning') + '%', tip: '周报第 29 期 · 年度计划 210 条已执行 136 条' }];
    return '<div class="grid3 charts">' +
      card('本月任务 · 按类型', '点一段看明细', CH.donut(types, String(MONTH.jobsDone), '完成 / ' + MONTH.jobs)) +
      card('本周工时', '约定 ' + WEEK_LIMIT + 'h · 点一条照亮台账', CH.bars(bars, WEEK_LIMIT)) +
      card('近 30 天缺陷 · 应用失败与异常信号', '点一天看当天', CH.area(DEF30.days, DEF30.found, DEF30.closed) + legend([[CPAL[0], '发现累计'], [CPAL[2], '闭环累计']])) +
      card('班组能力 · 8 模块', '点一角看短板', CH.radar(MODS.map(m => m.n), avg, 3) + legend([[CPAL[0], '班组均值'], ['#7b849c', '目标 L3'], ['#e8791d', '低于目标']])) +
      card('证书复审 · 未来一年', '点一个看证书台账', CH.certline(CERTS)) +
      card('周报指标 · 第 ' + WK29.no + ' 期', '与台账中心同源 · 点一条看', CH.meters(meters)) + '</div>';
  },
  jobsHTML() { return '<div class="jobs">' + DB.todayJobs().map(j => { const who = DB.crewOf(j); const cls = /已派|票已审|已完成|已关闭/.test(j.st) ? 'ok' : /进行中/.test(j.st) ? 'c' : ''; return '<div data-act="job-open" data-id="' + j.id + '" style="cursor:pointer"><span style="color:var(--ink);font-size:11.5px">' + h(j.t) + (j.added ? ' <i class="tag v">新</i>' : '') + (who.length ? ' · ' + h(who.join(' ')) : '') + '</span>' + (cls ? '<span class="tag ' + cls + '">' + h(j.st) + '</span>' : j.lv ? '<em>' + h(j.lv) + ' · ' + h(j.st) + '</em>' : '<span>' + h(j.when) + ' · ' + h(j.st) + '</span>') + '</div>'; }).join('') + '</div>'; },
  wkHTML() { const f = this.wkFocus(); return '<div class="wkl">' + f.map(x => '<div data-act="wk-item-home" data-k="' + x.it.k + '"><b>' + h(x.it.n) + '</b><span class="' + (x.rank >= 9 ? 'b' : x.rank >= 6 ? 'w' : '') + '">' + (typeof x.it.vals[0] === 'number' ? x.it.vals[WK29.gm()] + x.it.unit : x.it.vals[WK29.gm()]) + ' · 全市第 ' + x.rank + '</span><i>' + h(x.node.t) + ' · A ' + h(x.node.a) + '</i></div>').join('') + '</div>'; }
};
PAGES.home = {
  render() {
    const s = HOMEPG.st(); const onsite = PEOPLE.filter(p => p.status === '在岗').length, out = PEOPLE.filter(p => p.status === '外勤').length; const j = DB.job(MAINLINE);
    const d = DISPATCH.defaults(j); const nr = DB.nodeRate(); const d5 = DB.defect('d5');
    return cmdHTML(['安排下周一田寮站 F02 的交接试验与验收', '黄伟强这周工时怎么算的', '三个月内证书到期的有谁', '周报里光明排名最靠后的是哪几项']) +
      '<div class="hero' + (XW_IMGS && XW_IMGS.main ? ' hasxw' : '') + '">' + (XW_IMGS && XW_IMGS.main ? '<img class="heroxw" src="' + XW_IMGS.main + '" alt="">' : '') + '<div><div class="g">' + TODAY_CN + ' · ' + WEATHER + ' · <span id="clock">' + new Date().toTimeString().slice(0, 5) + '</span></div><h4>早上好，' + h(TEAM.leader) + ' · <em>小瓦特</em></h4><p class="sub" id="sub"></p></div>' +
      '<div class="nums"><div data-act="nav" data-to="home"><b id="n1">' + HOMEPG.pending() + '</b><span>待拍板</span></div><div data-act="nav" data-to="sched"><b>' + DB.todayJobs().length + '</b><span>今日作业</span></div><div data-act="nav" data-to="sched" data-sub="nodes"><b>' + nr.done + '/' + nr.n + '</b><span>本周节点已清</span></div><div data-act="nav" data-to="people"><b>' + onsite + '/' + out + '</b><span>在岗/外勤</span></div></div></div>' +
      '<div class="sec"><i></i><b>今日待拍板</b><em id="badge2">' + HOMEPG.pending() + '</em><span>决定由班组长作出</span></div>' +
      (typeof SUPER !== 'undefined' ? SUPER.transferBlock() : '') +
      '<div class="grid3" id="dec">' +
      (s.disp ? '<div class="dc ok" id="d1"><span class="lv">已派 · 下周一 09:00</span><b class="t">派工 · ' + h(j.t) + '</b><p>工作负责人 ' + h(s.disp.lead) + '；班员 ' + h(s.disp.crew.join('、')) + (s.disp.follows && s.disp.follows.length ? '；随队 ' + h(s.disp.follows.join('、')) : '') + '。派工单已发，推荐与排除理由随单存了。</p><div class="bt"><button class="g" data-act="nav" data-to="sched">看派工单</button><button class="g" data-act="premeet-from" data-id="' + MAINLINE + '">生成班前会材料</button></div></div>'
        : '<div class="dc" id="d1"><span class="lv">重点 · 下周一上午</span><b class="t">派工 · ' + h(j.t) + '</b><p id="d1p">四条规则：' + h(j.need.map(c => c.replace('作业证', '证')).join('、')) + '、「' + h(SKILL9.find(x => x.k === j.skill).n) + '」可自主实施、本周工时、当天冲突。她的建议：工作负责人 <u class="num" data-act="whylead">' + h(d.lead ? d.lead.n : '待定') + '</u>；班员 ' + h(d.crew.map(p => p.n).join('、')) + '；' + h(d.follows.map(p => p.n).join('、')) + '随队。</p><div class="ppl" id="ppl"><div class="row"></div><div class="tk"><span class="lbl">小瓦特在想</span><span></span></div><div class="xpl" id="xpl"></div></div><div class="bt" id="d1bt"><button data-act="home-go">按她的安排</button><button class="g" data-act="home-swap">看理由 / 换人</button></div></div>') +
      (s.focus ? '<div class="dc ok" id="d2"><span class="lv">已排 · 本周节点</span><b class="t">周报第 ' + WK29.no + ' 期 · 本周要清的节点</b><p>' + h(s.focus.map(k => (NODES.find(n => n.id === k) || {}).t).join('、')) + ' 已提级，A/B 责任人已收到；周关键节点表里逐项打勾闭环。</p><div class="bt"><button class="g" data-act="nav" data-to="sched" data-sub="nodes">看周关键节点</button></div></div>'
        : '<div class="dc w" id="d2"><span class="lv">周报 · 今早 07:30</span><b class="t">周报第 ' + WK29.no + ' 期 · 光明局在 11 个区局里的位置</b><p id="d2p">新建终端投运率 ' + WK29.val('newrun') + '% 全市第 ' + WK29.rank('newrun') + '；十五类异常信号待消 ' + WK29.val('abn15') + ' 项、超期 10；晨操年度计划 ' + WK29.val('morning') + '%。她按关键节点表把这几项提成本周重点。</p><div class="bt" id="d2bt"><button data-act="nodes-plan">按周报排本周节点</button><button class="g" data-act="nav" data-to="ledger" data-sub="weekly">看周报指标</button></div></div>') +
      (/已关闭|已验证/.test(s.d5) ? '<div class="dc ok" id="d3"><span class="lv">已关闭</span><b class="t">应用失败 · 华发民公用柜 电容故障</b><p>消缺完工并验证，' + h(s.d5) + '，OMS 处理记录已生成同步单。</p><div class="bt"><button class="g" data-act="nav" data-to="ledger" data-sub="defect">看缺陷台账</button></div></div>'
        : /待验收/.test(s.d5) ? '<div class="dc w" id="d3"><span class="lv">待验收</span><b class="t">应用失败 · 华发民公用柜 电容故障</b><p>消缺已完工，等验证。验收人建议韩雪。</p><div class="bt" id="d3bt"><button data-act="hz-accept" data-id="d5">验收通过</button><button class="g" data-act="nav" data-to="sched" data-sub="pool">看任务</button></div></div>'
        : /已派|进行中|已排任务/.test(s.d5) ? '<div class="dc ok" id="d3"><span class="lv">' + h(s.d5) + '</span><b class="t">应用失败 · 华发民公用柜 电容故障</b><p>消缺任务已进任务池，在用工安排里跟进度；完工后转待验收。</p><div class="bt"><button class="g" data-act="nav" data-to="sched" data-sub="pool">看进度</button></div></div>'
        : s.urged ? '<div class="dc ok" id="d3"><span class="lv">已催办</span><b class="t">应用失败 · 华发民公用柜 电容故障</b><p>催办已发给韩雪（应用失败 A 责任），她回传处理照片后这条自动关闭。</p><div class="bt"><button class="g" data-act="urge-check">看催办状态</button><button data-act="hz-job" data-id="d5">生成消缺任务</button></div></div>'
        : '<div class="dc w" id="d3"><span class="lv">今日</span><b class="t">应用失败 · 华发民公用柜 电容故障 · 超期 2 天</b><p>8-2 登记的转电遥控失败，重大缺陷 72 小时内要消。周报里光明累计未消缺 17 单，这条是其中之一。</p><div class="bt" id="d3bt"><button data-act="urge">发出催办</button><button class="g" data-act="hz-job" data-id="d5">生成消缺任务</button></div></div>') +
      '</div>' +
      '<div class="grid2"><div class="card" id="k1"><div class="h"><b id="k1h">今日作业</b><span id="k1s">' + DB.todayJobs().length + ' 项 · 点一行她说进展</span></div><div id="k1b">' + HOMEPG.jobsHTML() + '</div></div>' +
      '<div class="card" id="k2"><div class="h"><b>周报第 ' + WK29.no + ' 期 · 光明局排名靠后的项</b><span>' + h(WK29.period) + ' · 点一行看对应节点</span></div>' + HOMEPG.wkHTML() + '<div class="bt" style="margin-top:8px"><button class="g" data-act="nav" data-to="ledger" data-sub="weekly">全部 ' + WK29.items.length + ' 项</button><button class="g" data-act="nav" data-to="know">周报两个案例</button></div></div></div>' +
      '<div class="sec"><i class="v"></i><b>班组一览</b><span>图表可点，点进去她照亮台账</span></div>' + HOMEPG.chartsHTML() +
      '<div class="card"><div class="h"><b>人员去向</b><span>' + onsite + ' 在岗 · ' + out + ' 外勤 · ' + PEOPLE.filter(p => p.status === '休假').length + ' 休假</span></div><div class="ppl on" style="margin:0;border:0;padding:0"><div class="row">' + PEOPLE.map(p => '<div class="chip" data-act="person" data-who="' + p.n + '" style="width:auto;flex-direction:row;align-items:center;gap:6px"><b>' + h(p.n) + '</b><span class="tag ' + (p.status === '在岗' ? 'ok' : p.status === '外勤' ? 'w' : '') + '" style="margin:0">' + h(p.status) + '</span></div>').join('') + '</div></div></div>';
  },
  after() {
    const s = HOMEPG.st(); CH.mount($('#main')); const ar = $('#charea'); if (ar) CH.areaHover(ar, DEF30.days, DEF30.found, DEF30.closed);
    if (S.briefed) { $$('#dec .dc').forEach(d => d.classList.add('in')); return; }
    S.briefed = true; XW.clearChat();
    const sub = $('#sub'); const mirror = (t, ms, done) => { XW.state('talk'); XW.type($('#xwsub'), t, ms); XW.type(sub, t, ms, () => { XW.state(''); done && done(); }); };
    XW.at(300, () => mirror('早上好，赵班长。周报第 ' + WK29.no + ' 期今早七点半到了，我对了光明局的每一行：新建终端投运率 ' + WK29.val('newrun') + '%，11 个区局里第 ' + WK29.rank('newrun') + '；十五类异常信号待消 ' + WK29.val('abn15') + ' 项；晨操年度计划 ' + WK29.val('morning') + '%。', 50));
    XW.at(7400, () => mirror('有' + HOMEPG.pending() + '件事要你拍板：' + (s.disp ? '' : '下周一田寮站 F02 的交接试验与验收还没派人，我按证书、核心技能、工时、冲突四条规则排了人选；') + (s.focus ? '' : '周报里排名靠后的几项要提成本周节点；') + (s.urged || /已派|进行中|待验收|已关闭|催办|已登记/.test(s.d5) ? '' : '华发民公用柜的电容故障超期两天了。'), 50));
    XW.at(9000, () => $('#d1').classList.add('in')); XW.at(11200, () => $('#d2').classList.add('in')); XW.at(13000, () => $('#d3').classList.add('in'));
    XW.at(14800, () => mirror('你先看哪件？', 60));
    XW.at(16000, () => XW.card('早上说的事都在上面，点哪张卡我就办哪件。'));
  }
};
Object.assign(ACT, {
  'home-swap'() { const host = $('#ppl'); if (!host || host.classList.contains('on')) return; $('#d1').classList.add('wide'); DISPATCH.open(host, DB.job(MAINLINE)); },
  'dispatch-pick'(el) { DISPATCH.pick(el.dataset.who); },
  'disp-save'() { XW.answer('这张派工单她正在填，填完会自动发出去并通知到人。要改内容的话等她填完，在任务池里点那一行的「改」。', null, { confirm: false }); },
  'dispatch-keep'() { const d = DISPATCH.defaults(); XW.answer('好，保留' + (d.crew[d.crew.length - 1] || d.lead).n + '。要办的话点「按她的安排」。', null, { confirm: false }); },
  'home-go'() { ACT['dispatch-go']({ dataset: {} }); },
  'dispatch-go'(el) { if (LS.get('dispatch', {})[MAINLINE] && S.page === 'home' && (!DISPATCH.job || DISPATCH.job.id === MAINLINE)) { XW.answer('田寮站 F02 的派工单已经发过了，要改的话去用工安排。', null, { confirm: false }); return; } $$('#d1bt button, .msg .bt button').forEach(b => b.disabled = true);
    const host = S.page === 'home' ? $('#k1b') : $('#dform'); if (!DISPATCH.job) DISPATCH.job = DB.job(MAINLINE);
    DISPATCH.go(el.dataset.who, host, rec => { if (S.page === 'home') { const d1 = $('#d1'); d1.className = 'dc ok in'; $('.lv', d1).textContent = '已派 · 下周一 09:00'; $('#d1p').innerHTML = '工作负责人 ' + h(rec.lead) + '；班员 ' + h(rec.crew.join('、')) + (rec.follows && rec.follows.length ? '；随队 ' + h(rec.follows.join('、')) : '') + '。派工单已发，' + (rec.crew.length + 1 + (rec.follows || []).length) + ' 人已收到，理由随单存了。'; $('#ppl').classList.remove('on'); $('#d1bt').innerHTML = '<button class="g" data-act="nav" data-to="sched">看派工单</button><button class="g" data-act="premeet-from" data-id="' + MAINLINE + '">生成班前会材料</button>'; $('#n1').textContent = HOMEPG.pending(); $('#badge2').textContent = HOMEPG.pending(); } else if (S.page === 'sched') { XW.at(200, () => render()); } badgeSync(); }); },
  whylead() { const e = DISPATCH.explain(DB.job(MAINLINE)); if (!e.lead) return; XW.answer(e.lead.p.n + '是这次的工作负责人：' + e.lead.why.join('，') + '。' + (e.overs.length ? '有资格但没排的是' + e.overs.map(x => x.p.n + '（' + x.why.find(w => /超约定/.test(w)) + '）').join('、') + '。' : '') + (e.outs.filter(x => x.p.cert.includes('工作负责人资格')).length ? '另外' + e.outs.filter(x => x.p.cert.includes('工作负责人资格')).map(x => x.p.n + '有负责人资格但' + x.why.find(w => /无|不具备|已派|休假/.test(w))).join('、') + '。' : ''), null, { confirm: false, done() { XW.card(DISPATCH.tableHTML(DB.job(MAINLINE))); } }); },
  /* 周报 → 本周节点 */
  'nodes-plan'() { const f = HOMEPG.wkFocus(); XW.state('think'); XW.think('周报里光明排名最靠后的是' + f.map(x => x.it.n + '第 ' + x.rank).join('、') + '……对到关键节点表：' + f.map(x => x.node.t + '（A ' + x.node.a + '，' + x.node.cyc + '）').join('、') + '。这几项本周提级，A 不在 B 顶上。', () => { const ids = []; f.forEach(x => { if (!ids.includes(x.node.id)) ids.push(x.node.id); }); LS.set('nodefocus', ids); const who = []; f.forEach(x => { [x.node.a, x.node.b].forEach(n => { if (P[n] && !who.includes(n)) who.push(n); }); }); DB.notify(who.join(' · '), '周报第 ' + WK29.no + ' 期 本周重点节点：' + ids.map(id => NODES.find(n => n.id === id).t).join('、'), who.length + ' 人已收到', true); DB.log('关键节点', '按周报第 ' + WK29.no + ' 期提级 ' + ids.length + ' 项'); XW.fly('本周重点节点已发 · ' + who.join(' · ')); const d2 = $('#d2'); if (d2) { d2.className = 'dc ok in'; $('.lv', d2).textContent = '已排 · 本周节点'; $('#d2p').textContent = ids.map(id => NODES.find(n => n.id === id).t).join('、') + ' 已提级，A/B 责任人已收到；周关键节点表里逐项打勾闭环。'; $('#d2bt').innerHTML = '<button class="g" data-act="nav" data-to="sched" data-sub="nodes">看周关键节点</button>'; $('#n1').textContent = HOMEPG.pending(); $('#badge2').textContent = HOMEPG.pending(); } badgeSync(); XW.answer('排好了：' + ids.map(id => { const n = NODES.find(x => x.id === id); return n.t + '由' + n.a + '牵头'; }).join('，') + '。A 责任人当天不在的由 B 顶上，周五我按管控周期核一遍谁清了谁没清。', null, { confirm: false, chart: CH.mini.bars(f.map(x => ({ n: x.it.n.slice(0, 8), v: 12 - x.rank, c: x.rank >= 9 ? '#e5484d' : CPAL[1], txt: '第 ' + x.rank, tip: x.it.n + ' 全市第 ' + x.rank })), { max: 11, h: 13, x0: 80 }) }); }); },
  'wk-item-home'(el) { const it = WK29.item(el.dataset.k); const n = NODES.find(x => x.id === it.node); const r = WK29.rank(it.k); XW.answer(it.n + '：光明 ' + (typeof it.vals[0] === 'number' ? it.vals[WK29.gm()] + it.unit : it.vals[WK29.gm()]) + '，全市 ' + it.total + it.unit + '，11 个区局里第 ' + r + '。' + it.detail + '。对应关键节点「' + n.t + '」，A ' + n.a + '、B ' + n.b + '，' + n.cyc + '。', null, { confirm: false, chart: CH.mini.bars(WK29.bureaus.map((b, i) => ({ n: b, v: typeof it.vals[i] === 'number' ? it.vals[i] : 0, c: b === '光明' ? '#e5484d' : CPAL[0], tip: b + ' ' + it.vals[i] + it.unit })), { max: typeof it.vals[0] === 'number' ? Math.max.apply(null, it.vals) * 1.05 : 10, h: 11, x0: 40, unit: it.unit }), done() { XW.card('<div class="bt" style="margin-top:0"><button data-act="nav" data-to="sched" data-sub="nodes">去周关键节点</button><button class="g" data-act="nav" data-to="ledger" data-sub="weekly">看周报指标台账</button></div>'); } }); },
  /* 应用失败催办 */
  urge() { XW.state('write'); const d = XW.msg('a', '催办消息我写好了，你看一下：<div class="draft"><span></span></div>'); const txt = '韩雪：华发民公用柜转电遥控失败（电容故障），8-2 登记，重大缺陷 72 小时内要消，已超期 2 天。周报第 29 期光明累计未消缺 17 单，这条在其中。请今天安排消缺，处理后拍照回传并在 OMS 填闭环。—— 赵立群';
    XW.type(d.querySelector('.draft span'), txt, 34, () => { d.insertAdjacentHTML('beforeend', '<div class="bt"><button data-act="urge-send">发送</button><button class="g" data-act="urge-edit">改一下</button></div>'); XW.state(''); XW.scrollChat(); }); XW.type($('#xwsub'), '催办消息我写好了，你看一下。', 45); },
  'urge-send'() { DB.setDefect('d5', '已催办', { who: '韩雪' }); DB.notify('韩雪', '华发民公用柜 应用失败催办', '已读', true); XW.fly('催办已送达 · 韩雪'); const d3 = $('#d3'); if (d3) { d3.className = 'dc ok in'; $('.lv', d3).textContent = '已催办'; $('p', d3).textContent = '催办已发给韩雪（应用失败 A 责任）。她回传处理照片后这条自动关闭。'; $('#d3bt').innerHTML = '<button class="g" data-act="urge-check">看催办状态</button><button data-act="hz-job" data-id="d5">生成消缺任务</button>'; $('#n1').textContent = HOMEPG.pending(); $('#badge2').textContent = HOMEPG.pending(); } XW.answer('发出去了，韩雪已收到。她回传处理照片后我把这条关掉，并生成 OMS 的处理记录同步单。', null, { confirm: false }); badgeSync(); },
  'urge-check'() { const d = DB.defect('d5'); const j = DB.jobs().find(x => x.defectId === 'd5' && x.st !== '已关闭'); XW.answer('华发民公用柜那条现在是「' + d.st + '」。' + (j ? '消缺任务「' + j.t + '」已经在任务池里，' + j.st + '。' : '催办 ' + (LS.get('defects', {})['d5'] || {}).who + ' 已读，还没回传处理照片。要我直接生成一条消缺任务派下去吗？'), null, { confirm: false, done() { if (!j) XW.card('<div class="bt" style="margin-top:0"><button data-act="hz-job" data-id="d5">生成消缺任务</button><button class="g" data-act="no" data-t="再等等">再等等</button></div>'); } }); },
  'urge-edit'() { XW.answer('你直接在上面那段里改，改完点发送。', null, { confirm: false }); },
  later() { XW.answer('改到哪天？在用工安排里点那一天，我把催办改成那天并重新算时限。', null, { confirm: false }); },
  person(el) { ensure('people', () => PEOPLEPG.show(el.dataset.who)); },
  /* 班前会材料：按派工单写 */
  'premeet-from'(el) { const j = DB.job(el.dataset.id || MAINLINE); const rec = LS.get('dispatch', {})[j.id]; if (!rec) { XW.answer('这项还没派工，派完我按派工单写班前会材料。', null, { confirm: false }); return; } XW.state('write'); const d = XW.msg('a', '班前会材料我按派工单写一版：<div class="draft"><span></span></div>'); const sk = SKILL9.find(s => s.k === j.skill); const txt = '一、任务：' + j.t + '，' + DB.whenOf(j) + '。工作负责人 ' + rec.lead + '，班员 ' + rec.crew.join('、') + (rec.follows && rec.follows.length ? '，随队 ' + rec.follows.join('、') : '') + '。\n二、为什么是这几个人：' + (rec.reasons || []).filter(r => r.role === 'lead' || r.role === 'crew').map(r => r.n + '——' + r.why.slice(0, 2).join('，')).join('；') + '。\n三、安全交底：' + (j.desc || '') + ' 试验前验电、放电、接地；试验区设围栏，人员站在安全距离外；试验完毕充分放电后拆线。工作票 ' + (j.ticketNo || '待起草') + '。\n四、技术交底：' + (sk ? '本次计入「' + sk.n + '」实操，完工后每人实操量 +1；' : '') + '出厂资料审查、外观检查、安装前试验、调试结果审核、安装后功能测试逐项签字。\n五、以上由班组长确认后使用。'; XW.type(d.querySelector('.draft span'), txt, 24, () => { XW.state(''); d.insertAdjacentHTML('beforeend', '<div class="bt"><button data-act="premeet-save" data-id="' + j.id + '">存为班前会材料并通知</button><button class="g" data-act="no" data-t="再改改">再改改</button></div>'); XW.scrollChat(); }); },
  'premeet-save'(el) { const j = DB.job(el.dataset.id); const docs = LS.get('docs', {}); docs['premeet-' + j.id] = { t: '班前会材料 · ' + j.t.slice(0, 16), ts: Date.now(), body: $$('.msg .draft').pop().textContent, adopted: true }; LS.set('docs', docs); DB.notify(DB.crewOf(j).join(' · ') || '工作班', '班前会材料 · ' + j.t.slice(0, 16), '已发', true); DB.log('班前会', j.t.slice(0, 16) + ' 材料已发'); XW.fly('班前会材料已发 · ' + DB.crewOf(j).join(' · ')); XW.answer('存好了，也发给了工作班成员。班前会点名复述安措时可以直接念第三段。', null, { confirm: false }); },
  /* 图表下钻 */
  'ch-task'(el) { const k = el.dataset.k; const TL = DB.taskLedger(); const rows = TL.map(t => [t.d, t.t, t.line, t.who, t.st]); const me = []; TL.forEach((t, i) => { if (t.t === k) me.push(i); }); const n = me.length, done = TL.filter(t => t.t === k && /已完成|已关闭/.test(t.st)).length; const cnt = {}; TL.filter(t => t.t === k).forEach(t => t.who.split('、').forEach(w => { if (P[w]) cnt[w] = (cnt[w] || 0) + 1; })); const top = Object.keys(cnt).sort((a, b) => cnt[b] - cnt[a])[0];
    XW.spot({ title: '任务台账 · 本月 · ' + k, cols: ['日期', '类型', '线路 / 站', '人员', '状态'], rows, me, text: '本月' + k + ' ' + n + ' 项，完成 ' + done + ' 项' + (n - done ? '，没完成的是' + TL.filter(t => t.t === k && !/已完成|已关闭/.test(t.st)).map(t => t.line + '（' + t.st + '）').join('、') : '') + '。' + (top ? k + '做得最多的是' + top + '，' + cnt[top] + ' 次。' : '') }); },
  'ch-hours'(el) { DISPATCH.hours(el.dataset.who); },
  'ch-day'(el) { const i = +el.dataset.i; const d = DEF30.days[i]; const df = DEF30.found[i] - (i ? DEF30.found[i - 1] : 0), dc = DEF30.closed[i] - (i ? DEF30.closed[i - 1] : 0); const last = i === DEF30.days.length - 1;
    XW.answer(d + ' 这天' + (df ? '发现 ' + df + ' 处' : '没有新发现') + (dc ? '，闭环 ' + dc + ' 处' : '') + '，到这天累计发现 ' + DEF30.found[i] + '、闭环 ' + DEF30.closed[i] + '。' + (last ? '还有 ' + (DEF30.found[i] - DEF30.closed[i]) + ' 处没闭环，华发民公用柜那条已经超期。' : ''), null, { confirm: false, done() { XW.card('<div class="bt" style="margin-top:0"><button data-act="nav" data-to="ledger" data-sub="defect">去缺陷台账</button></div>'); } }); },
  'ch-mod'(el) { const i = +el.dataset.i; const m = MODS[i]; const avg = PEOPLE.reduce((s, p) => s + PEOPLEPG.lv(p)[i], 0) / PEOPLE.length; const weak = PEOPLE.map(p => ({ p, v: PEOPLEPG.lv(p)[i] })).sort((a, b) => a.v - b.v).slice(0, 3); const c = COURSES.find(c => c.mod === m.k);
    XW.answer('"' + m.n + '"班组均值 L' + avg.toFixed(1) + (avg < 3 ? '，低于目标 L3' : '，达到目标') + '。最弱的三个是' + weak.map(w => w.p.n + ' ' + LV[w.v].slice(0, 2)).join('、') + '。' + (c ? '对应的课是《' + c.n + '》，要我排给这三个人吗？' : '这一块没有现成课件，可以安排一次班内带教。'), null, { confirm: false, done() { XW.card('<div class="bt" style="margin-top:0">' + (c ? '<button data-act="ch-mod-plan" data-i="' + i + '">排进培养计划</button>' : '') + '<button class="g" data-act="nav" data-to="people">去班组画像</button></div>'); } }); },
  'ch-mod-plan'(el) { const i = +el.dataset.i; const m = MODS[i]; const c = COURSES.find(c => c.mod === m.k); const weak = PEOPLE.map(p => ({ p, v: PEOPLEPG.lv(p)[i] })).sort((a, b) => a.v - b.v).slice(0, 3); const plan = LS.get('plan', []); weak.forEach(w => plan.push({ who: w.p.n, t: c.n, when: '下周', ts: Date.now() })); LS.set('plan', plan); XW.fly('已加入下周培养计划 · ' + weak.map(w => w.p.n).join(' · ')); XW.answer('排进去了：下周' + weak.map(w => w.p.n).join('、') + '学《' + c.n + '》，学完考一次，成绩回到图谱。', null, { confirm: false }); },
  'ch-cert'() { PEOPLEPG.sixAsk('cert'); },
  'ch-meter'(el) { const k = el.dataset.k; const it = WK29.item(k); if (!it) return; ACT['wk-item-home']({ dataset: { k } }); }
});
