/* ===== 班组知识库：分类与检索、规程问答带出处、关联条目、周报案例库、老师傅经验闭环（采集 → 沉淀 → 派工 / 培养时引用 → 用后评价）、她最近引用 ===== */
const KNOWPG = {
  q: '', cat: '全部', open: null,
  CATS: ['全部', '整定', '继保', '二次', '运维', '两票', '安规', '设备', '班组约定'],
  catOf(k) { if (k.cat) return k.cat; const t = k.tags.join(' '); if (/班组约定/.test(t)) return '班组约定'; if (/整定/.test(t)) return '整定'; if (/光差|继保/.test(t)) return '继保'; if (/二次|终端/.test(t)) return '二次'; if (/缺陷|巡视|在线率|交换机/.test(t)) return '运维'; if (/两票|安措/.test(t)) return '两票'; if (/登杆|安规|高温/.test(t)) return '安规'; return '设备'; },
  all() { return KB.concat(KB2); },
  QS: [{ q: '站内馈线保护定值是多少', k: 'k1' }, { q: '重合闸有哪几种方式', k: 'k2' }, { q: '遥控失败先查什么', k: 'k5' }, { q: '缺陷限时闭环是几天', k: 'k6' }, { q: '交换机取电怎么复核', k: 'k7' }, { q: '差动保护的差电流怎么算', k: 'k4' }, { q: '每周外勤上限是多少', k: 'k8' }, { q: '在线率管控每天做什么', k: 'k21' }, { q: '自主实施怎么认定', k: 'k23' }, { q: '人均实操量怎么算', k: 'k24' }, { q: '第一种和第二种工作票怎么分', k: 'k19' }, { q: '高温作业怎么轮换', k: 'k22' }],
  find(text) { const hit = this.QS.find(x => text.includes(x.q.slice(0, 4))); if (hit) return this.all().find(k => k.id === hit.k); const words = ['整定', '定值', '馈线', '重合闸', '零序', '接地变', '差动', '光差', '遥控', '终端', '二次', '安措', '接地线', '验电', '交换机', '取电', '在线率', '缺陷', '限时', '外勤', '工时', '约定', '高温', '工作票', '两票', '环网柜', '光纤', '识图', '采样', '自主实施', '实操', '三交三查', '振荡波']; const w = words.filter(x => text.includes(x)); return this.all().find(k => w.some(x => k.tags.includes(x) || k.body.includes(x) || k.t.includes(x))); },
  related(k) { const cat = this.catOf(k); return this.all().filter(x => x.id !== k.id && (this.catOf(x) === cat || x.tags.some(t => k.tags.includes(t)))).slice(0, 4); },
  use(k) { const u = LS.get('kbuse', []); u.unshift({ id: k.id, t: k.t, ts: Date.now() }); LS.set('kbuse', u.slice(0, 8)); },
  follow(k) { return k.id === 'k1' ? '要不要我顺便看看田寮站 F02 改造后的定值单和这个是否一致？' : k.id === 'k6' ? '华发民公用柜那条重大缺陷已经超期两天，催办在今日工作台。' : k.id === 'k7' ? '下午交换机取电排查的工作票安措里已经写了万用表复核。' : k.id === 'k21' ? '光明局本期在线率 99.63%，全市第 4，离线过夜的终端今天有 2 台。' : k.id === 'k23' || k.id === 'k24' ? '班组画像里每个人九类核心技能的资格和实操量都按这个口径记。' : ''; },
  ask(text) { const k = this.find(text); const host = $('#kba'); if (!k) { XW.answer('这条我在班组知识库里没找到，你可以把规程原文拖进来，我下次就会答。', null, { confirm: false }); return; } this.use(k); this.open = k.id;
    if (host) { host.innerHTML = '<div class="note" style="margin-bottom:4px">' + h(k.t) + ' · ' + h(this.catOf(k)) + '</div><div id="kbtext"></div><div class="src" data-act="kb-src">出处：' + h(k.src) + '（点开原文）</div><div class="orig">' + h(k.body) + '</div><div class="rel"><span class="note">相关：</span>' + this.related(k).map(r => '<b data-act="kb-open" data-id="' + r.id + '">' + h(r.t) + '</b>').join('') + '</div>'; XW.state('talk'); XW.type($('#kbtext'), k.body, 30, () => { XW.state(''); XW.answer('答案在左边，出处是' + k.src + '，点一下能看原文。' + this.follow(k), null, { confirm: false, speak: false }); const ul = $('#kbuse'); if (ul) ul.innerHTML = this.useHTML(); }); XW.type($('#xwsub'), k.body.slice(0, 60) + '…', 45); }
    else XW.answer(k.body + '（出处：' + k.src + '）', null, { confirm: false }); },
  useHTML() { const u = LS.get('kbuse', []); return u.length ? u.map(x => '<div class="note" style="color:var(--ink);margin:3px 0;cursor:pointer" data-act="kb-open" data-id="' + x.id + '">· ' + h(x.t) + ' <span class="note">' + new Date(x.ts).toTimeString().slice(0, 5) + '</span></div>').join('') : '<div class="note">她答过的问题会列在这里</div>'; },
  list() { const q = this.q.trim(); return this.all().filter(k => (this.cat === '全部' || this.catOf(k) === this.cat) && (!q || (k.t + k.body + k.tags.join('')).includes(q))); },
  listHTML() { const l = this.list(); return l.length ? l.map(k => '<div class="kbitem' + (k.id === this.open ? ' on' : '') + '" data-act="kb-open" data-id="' + k.id + '"><b>' + h(k.t) + '</b><span>' + h(k.body.length > 60 ? k.body.slice(0, 60) + '…' : k.body) + '</span><i>' + h(this.catOf(k)) + ' · ' + h(k.src.split(' · ')[0]) + '</i></div>').join('') : '<div class="empty">没有匹配的条目</div>'; },
  allCases() { return CASES.concat(CASES2, LS.get('cases', [])); },
  cases() { return this.allCases().map(c => '<div class="casec"><b>' + h(c.t) + ' <span class="note">' + h(c.d) + ' · ' + h(c.who) + '</span></b><div><i>现象</i><span>' + h(c.sym) + '</span></div><div><i>原因</i><span>' + h(c.cause) + '</span></div><div><i>处理</i><span>' + h(c.fix) + '</span></div><div><i>教训</i><span>' + h(c.lesson) + '</span></div>' + (c.kb ? '<div><i>规程</i><span data-act="kb-open" data-id="' + c.kb + '" style="color:var(--info);cursor:pointer">' + h((this.all().find(k => k.id === c.kb) || {}).t || '') + '</span></div>' : '') + '</div>').join(''); },
  /* 老师傅经验闭环：每条经验记引用次数与用后评价 */
  expAll() { const use = LS.get('expuse', {}); return EXPERIENCE.concat(EXPERIENCE2, LS.get('exp', [])).map(e => { const u = use[e.id] || {}; return Object.assign({}, e, { used: (e.used || 0) + (u.used || 0), rate: [(e.rate ? e.rate[0] : 0) + (u.up || 0), (e.rate ? e.rate[1] : 0) + (u.down || 0)] }); }); },
  expHTML() { return this.expAll().map(e => '<div class="casec exp"><b>' + h(e.t) + ' <span class="note">' + h(e.who) + (e.tags ? ' · ' + h(e.tags.join(' / ')) : '') + '</span></b><div><i>要点</i><span>' + h(e.body) + '</span></div><div><i>闭环</i><span>派工 / 培养时引用 ' + e.used + ' 次 · 用后评价 有用 ' + e.rate[0] + ' / 没用 ' + e.rate[1] + '</span></div><div class="bt" style="margin-top:4px"><button class="s g" data-act="exp-use" data-id="' + e.id + '">派工时引用</button><button class="s g" data-act="exp-rate" data-id="' + e.id + '" data-v="1">有用</button><button class="s g" data-act="exp-rate" data-id="' + e.id + '" data-v="0">没用</button></div></div>').join(''); }
};
PAGES.know = {
  render() { const cats = {}; KNOWPG.all().forEach(k => { const c = KNOWPG.catOf(k); cats[c] = (cats[c] || 0) + 1; }); const exp = KNOWPG.expAll(); return cmdHTML(['站内馈线保护定值是多少', '缺陷限时闭环是几天', '把光侨路 3# 公用柜的处理存为案例', '记一条我的经验', '交换机取电怎么复核']) + pageHead('班组知识库', '规程问答有出处 · ' + KNOWPG.all().length + ' 条规程与约定 · 周报案例沉淀 · 班长与骨干经验闭环') +
    '<div class="grid2" style="grid-template-columns:1.2fr 1fr"><div><div class="card"><div class="h"><b>规程问答</b><span>答案逐字出，条款可点开原文</span></div><div class="kbq">' + FAQ.map(q => '<b data-act="kb-ask" data-q="' + h(q) + '">' + h(q) + '</b>').join('') + '</div><div class="kba" id="kba" style="margin-top:8px"><div class="empty">点一个问题，或在上面输入</div></div></div>' +
    '<div class="card" style="margin-top:10px"><div class="h"><b>规程与约定条目</b><span id="kbcount">' + KNOWPG.list().length + ' 条</span></div><div class="search"><input id="kbsearch" placeholder="搜条目、关键词，如 交换机、重合闸、在线率" value="' + h(KNOWPG.q) + '"></div><div class="kbq" style="margin:6px 0">' + KNOWPG.CATS.map(c => '<b data-act="kb-cat" data-k="' + c + '" style="' + (c === KNOWPG.cat ? 'background:var(--tint);color:var(--pri);border-color:#c9cbf5' : '') + '">' + c + (cats[c] ? ' ' + cats[c] : '') + '</b>').join('') + '</div><div id="kblist">' + KNOWPG.listHTML() + '</div></div></div>' +
    '<div><div class="card"><div class="h"><b>知识分布</b><span>按类别</span></div>' + CH.mini.donut(Object.keys(cats).map((c, i) => ({ k: c, v: cats[c], c: CPAL[i % 6], act: 'kb-cat' })), { sub: '条' }) + '<div class="note" style="margin-top:4px">她最近引用</div><div id="kbuse">' + KNOWPG.useHTML() + '</div></div>' +
    '<div class="card" style="margin-top:10px"><div class="h"><b>典型案例</b><span>' + KNOWPG.allCases().length + ' 例 · 周报案例与本班处理记录 · 一键沉淀</span><div class="r"><button class="s" data-act="case-new">把光侨路 3# 存为案例</button></div></div><div id="cases">' + KNOWPG.cases() + '</div></div>' +
    '<div class="card" style="margin-top:10px"><div class="h"><b>班长与骨干经验</b><span>' + exp.length + ' 条 · 引用 ' + exp.reduce((s, e) => s + e.used, 0) + ' 次 · 她问，你说，她整理</span><div class="r"><button class="s g" data-act="exp-start">经验访谈</button></div></div><div id="explist">' + KNOWPG.expHTML() + '</div></div></div></div>'; },
  after() { CH.mount($('#main')); const inp = $('#kbsearch'); if (inp) inp.addEventListener('input', () => { KNOWPG.q = inp.value; $('#kblist').innerHTML = KNOWPG.listHTML(); $('#kbcount').textContent = KNOWPG.list().length + ' 条'; }); if (KNOWPG.open) { const k = KNOWPG.all().find(x => x.id === KNOWPG.open); if (k) ACT['kb-open']({ dataset: { id: k.id } }); } }
};
Object.assign(ACT, {
  'kb-ask'(el) { XW.user(el.dataset.q, false); XW.at(400, () => KNOWPG.ask(el.dataset.q)); },
  'kb-src'(el) { el.nextElementSibling.classList.toggle('on'); },
  'kb-cat'(el) { KNOWPG.cat = el.dataset.k; if (S.page !== 'know') { ensure('know', () => {}); return; } $('#kblist').innerHTML = KNOWPG.listHTML(); $('#kbcount').textContent = KNOWPG.list().length + ' 条'; $$('.kbq [data-act="kb-cat"]').forEach(b => { b.style.cssText = b.dataset.k === KNOWPG.cat ? 'background:var(--tint);color:var(--pri);border-color:#c9cbf5' : ''; }); },
  'kb-open'(el) { const k = KNOWPG.all().find(x => x.id === el.dataset.id); if (!k) return; if (S.page !== 'know') { KNOWPG.open = k.id; ensure('know', () => {}); return; } KNOWPG.open = k.id; KNOWPG.use(k); $$('.kbitem').forEach(x => x.classList.toggle('on', x.dataset.id === k.id)); const host = $('#kba'); host.innerHTML = '<div class="note" style="margin-bottom:4px">' + h(k.t) + ' · ' + h(KNOWPG.catOf(k)) + '</div><div id="kbtext">' + h(k.body) + '</div><div class="src" data-act="kb-src">出处：' + h(k.src) + '（点开原文）</div><div class="orig">' + h(k.body) + '</div><div class="rel"><span class="note">相关：</span>' + KNOWPG.related(k).map(r => '<b data-act="kb-open" data-id="' + r.id + '">' + h(r.t) + '</b>').join('') + '</div>'; host.scrollIntoView({ block: 'nearest' }); const ul = $('#kbuse'); if (ul) ul.innerHTML = KNOWPG.useHTML(); XW.answer('"' + k.t + '"：' + k.body.slice(0, 40) + (k.body.length > 40 ? '……' : '') + ' 出处' + k.src.split(' · ')[0] + '。相关的还有' + KNOWPG.related(k).slice(0, 2).map(r => '"' + r.t + '"').join('、') + '。', null, { confirm: false, speak: false }); },
  'case-new'() { const d = DB.defect('d8'); XW.state('write'); const m = XW.msg('a', '我把光侨路 3# 公用柜频繁投退的处理整理成案例：<div class="draft"><span></span></div>'); const txt = '案例：光侨路 3# 公用柜 频繁投退（十五类异常信号）\n现象：主站站端巡检发现开关位置遥信一日内频繁变位 28 次，终端在线，一次设备未动作\n原因：辅助接点接触不良，遥信抖动\n处理：更换辅助接点，主站核对 24 小时无变位后关闭；' + (d && /已关闭/.test(d.st) ? '缺陷已关闭' : '缺陷现在' + (d ? d.st : '处理中')) + '\n教训：十五类异常信号周周清；频繁投退先看遥信回路再看一次机构，不要一上来就换终端\n规程：在线率管控要求（周报 · 十五类异常信号）'; XW.type(m.querySelector('.draft span'), txt, 28, () => { XW.state(''); m.insertAdjacentHTML('beforeend', '<div class="bt"><button data-act="case-save">存入案例库</button><button class="g" data-act="no" data-t="改一下">改一下</button></div>'); XW.scrollChat(); }); },
  'case-save'() { const cs = LS.get('cases', []); if (!cs.some(c => c.t.includes('光侨路 3#'))) cs.push({ id: 'ax' + Date.now().toString(36), t: '光侨路 3# 公用柜 频繁投退', d: TODAY, who: '吴倩', sym: '遥信一日内频繁变位 28 次，终端在线，一次设备未动作', cause: '辅助接点接触不良，遥信抖动', fix: '更换辅助接点，主站核对 24 小时无变位后关闭', lesson: '十五类异常信号周周清；频繁投退先看遥信回路再看一次机构', kb: 'k21' }); LS.set('cases', cs); DB.log('案例', '光侨路 3# 公用柜 频繁投退 存入案例库'); if ($('#cases')) $('#cases').innerHTML = KNOWPG.cases(); XW.answer('存进案例库了。下次再有频繁投退的信号，派工和班前会材料里我会提这条。', null, { confirm: false }); },
  'exp-start'() { XW.answer('那我问你三个问题，你打字答就行。第一个：晨操遥控失败的单子，你一般先让人查什么、不让人先做什么？', null, { confirm: false }); XW._expWait = 1; },
  'exp-save'(el) { const ex = LS.get('exp', []); ex.push({ id: 'ex' + Date.now().toString(36), who: '赵立群', t: el.dataset.t || '遥控失败与新人验收', body: el.dataset.body, tags: ['遥控', '验收', '台风'], used: 0, rate: [0, 0] }); LS.set('exp', ex); DB.log('经验', '赵立群 沉淀经验一条：' + (el.dataset.t || '遥控失败与新人验收')); XW.answer('记成一条经验了，放在"班长与骨干经验"里，署名赵立群。派工和培养的时候我会引用，用完记得点有用没用。', null, { confirm: false }); if (S.page === 'know') render(); },
  'exp-use'(el) { const e = KNOWPG.expAll().find(x => x.id === el.dataset.id); if (!e) return; const use = LS.get('expuse', {}); use[e.id] = use[e.id] || {}; use[e.id].used = (use[e.id].used || 0) + 1; LS.set('expuse', use); XW.mem.set('派工引用经验', e.t); DB.log('经验引用', e.who + '「' + e.t + '」 派工时引用'); XW.fly('已引用 · ' + e.t); if ($('#explist')) $('#explist').innerHTML = KNOWPG.expHTML(); XW.answer('记下了，下次派' + (e.tags ? e.tags[0] : '这类') + '相关的活，派工单安措要点里我带上「' + e.t + '」：' + e.body.slice(0, 30) + '……用完你点有用或没用，我按评价决定以后还提不提。', null, { confirm: false }); },
  'exp-rate'(el) { const e = KNOWPG.expAll().find(x => x.id === el.dataset.id); if (!e) return; const use = LS.get('expuse', {}); use[e.id] = use[e.id] || {}; const good = el.dataset.v === '1'; use[e.id][good ? 'up' : 'down'] = (use[e.id][good ? 'up' : 'down'] || 0) + 1; LS.set('expuse', use); DB.log('经验评价', '「' + e.t + '」 ' + (good ? '有用' : '没用')); if ($('#explist')) $('#explist').innerHTML = KNOWPG.expHTML(); XW.answer(good ? '记为有用，这条以后遇到' + (e.tags ? e.tags.join('、') : '同类') + '的活我会先提。' : '记为没用。同一条被评没用超过两次，我就不再主动提，改由你点名引用。', null, { confirm: false, speak: false }); }
});
