/* ===== 班组知识库：分类与检索、规程问答带出处、关联条目、案例库、班长经验访谈、她最近引用 ===== */
const KNOWPG = {
  q: '', cat: '全部', open: null,
  CATS: ['全部', '整定', '继保', '二次', '运维', '两票', '安规', '设备', '班组约定'],
  catOf(k) { if (k.cat) return k.cat; const t = k.tags.join(' '); if (/班组约定/.test(t)) return '班组约定'; if (/整定/.test(t)) return '整定'; if (/光差|继保/.test(t)) return '继保'; if (/二次|终端/.test(t)) return '二次'; if (/电缆|试验/.test(t)) return '运维'; if (/两票|安措/.test(t)) return '两票'; if (/登杆|安规/.test(t)) return '安规'; return '设备'; },
  all() { return KB.concat(KB2); },
  QS: [{ q: '站内馈线保护定值是多少', k: 'k1' }, { q: '重合闸有哪几种方式', k: 'k2' }, { q: '遥控失败先查什么', k: 'k5' }, { q: '停电作业安措顺序', k: 'k6' }, { q: '差动保护的差电流怎么算', k: 'k4' }, { q: '每周外勤上限是多少', k: 'k8' }, { q: '电缆试验前要做什么', k: 'k7' }, { q: '登杆前要检查什么', k: 'k21' }, { q: '第一种和第二种工作票怎么分', k: 'k19' }],
  find(text) { const hit = this.QS.find(x => text.includes(x.q.slice(0, 4))); if (hit) return this.all().find(k => k.id === hit.k); const words = ['整定', '定值', '馈线', '重合闸', '零序', '接地变', '差动', '光差', '遥控', '终端', '二次', '安措', '接地线', '验电', '登杆', '电缆', '试验', '外勤', '工时', '约定', '高温', '树障', '工作票', '两票', '环网柜', '光纤', '识图', '采样']; const w = words.filter(x => text.includes(x)); return this.all().find(k => w.some(x => k.tags.includes(x) || k.body.includes(x) || k.t.includes(x))); },
  related(k) { const cat = this.catOf(k); return this.all().filter(x => x.id !== k.id && (this.catOf(x) === cat || x.tags.some(t => k.tags.includes(t)))).slice(0, 4); },
  use(k) { const u = LS.get('kbuse', []); u.unshift({ id: k.id, t: k.t, ts: Date.now() }); LS.set('kbuse', u.slice(0, 8)); },
  ask(text) { const k = this.find(text); const host = $('#kba'); if (!k) { XW.answer('这条我在班组知识库里没找到，你可以把规程原文拖进来，我下次就会答。', null, { confirm: false }); return; } this.use(k); this.open = k.id;
    if (host) { host.innerHTML = '<div class="note" style="margin-bottom:4px">' + h(k.t) + ' · ' + h(this.catOf(k)) + '</div><div id="kbtext"></div><div class="src" data-act="kb-src">出处：' + h(k.src) + '（点开原文）</div><div class="orig">' + h(k.body) + '</div><div class="rel"><span class="note">相关：</span>' + this.related(k).map(r => '<b data-act="kb-open" data-id="' + r.id + '">' + h(r.t) + '</b>').join('') + '</div>'; XW.state('talk'); XW.type($('#kbtext'), k.body, 30, () => { XW.state(''); XW.answer('答案在左边，出处是' + k.src + '，点一下能看原文。' + (k.id === 'k1' ? '要不要我顺便看看凤凰线现在的定值单和这个是否一致？' : k.id === 'k6' ? '明天凤凰线那张票我审过，验电和接地线档位补齐了。' : k.id === 'k21' ? '明天换刀闸的派工单安措要点里已经写了杆根检查。' : ''), null, { confirm: false, speak: false }); const ul = $('#kbuse'); if (ul) ul.innerHTML = this.useHTML(); }); XW.type($('#xwsub'), k.body.slice(0, 60) + '…', 45); }
    else XW.answer(k.body + '（出处：' + k.src + '）', null, { confirm: false }); },
  useHTML() { const u = LS.get('kbuse', []); return u.length ? u.map(x => '<div class="note" style="color:var(--ink);margin:3px 0;cursor:pointer" data-act="kb-open" data-id="' + x.id + '">· ' + h(x.t) + ' <span class="note">' + new Date(x.ts).toTimeString().slice(0, 5) + '</span></div>').join('') : '<div class="note">她答过的问题会列在这里</div>'; },
  list() { const q = this.q.trim(); return this.all().filter(k => (this.cat === '全部' || this.catOf(k) === this.cat) && (!q || (k.t + k.body + k.tags.join('')).includes(q))); },
  listHTML() { const l = this.list(); return l.length ? l.map(k => '<div class="kbitem' + (k.id === this.open ? ' on' : '') + '" data-act="kb-open" data-id="' + k.id + '"><b>' + h(k.t) + '</b><span>' + h(k.body.length > 60 ? k.body.slice(0, 60) + '…' : k.body) + '</span><i>' + h(this.catOf(k)) + ' · ' + h(k.src.split(' · ')[0]) + '</i></div>').join('') : '<div class="empty">没有匹配的条目</div>'; },
  cases() { const cs = CASES.concat(CASES2, LS.get('cases', [])); return cs.map(c => '<div class="casec"><b>' + h(c.t) + ' <span class="note">' + h(c.d) + ' · ' + h(c.who) + '</span></b><div><i>现象</i><span>' + h(c.sym) + '</span></div><div><i>原因</i><span>' + h(c.cause) + '</span></div><div><i>处理</i><span>' + h(c.fix) + '</span></div><div><i>教训</i><span>' + h(c.lesson) + '</span></div>' + (c.kb ? '<div><i>规程</i><span data-act="kb-open" data-id="' + c.kb + '" style="color:var(--info);cursor:pointer">' + h((this.all().find(k => k.id === c.kb) || {}).t || '') + '</span></div>' : '') + '</div>').join(''); }
};
PAGES.know = {
  render() { const exp = EXPERIENCE.concat(EXPERIENCE2, LS.get('exp', [])); const cats = {}; KNOWPG.all().forEach(k => { const c = KNOWPG.catOf(k); cats[c] = (cats[c] || 0) + 1; }); return cmdHTML(['站内馈线保护定值是多少', '停电作业安措顺序', '把今天田寮线的处理存为案例', '记一条我的经验', '登杆前要检查什么']) + pageHead('班组知识库', '规程问答有出处 · ' + KNOWPG.all().length + ' 条规程与约定 · 案例沉淀 · 班长经验') +
    '<div class="grid2" style="grid-template-columns:1.2fr 1fr"><div><div class="card"><div class="h"><b>规程问答</b><span>答案逐字出，条款可点开原文</span></div><div class="kbq">' + FAQ.map(q => '<b data-act="kb-ask" data-q="' + h(q) + '">' + h(q) + '</b>').join('') + '</div><div class="kba" id="kba" style="margin-top:8px"><div class="empty">点一个问题，或在上面输入</div></div></div>' +
    '<div class="card" style="margin-top:10px"><div class="h"><b>规程与约定条目</b><span id="kbcount">' + KNOWPG.list().length + ' 条</span></div><div class="search"><input id="kbsearch" placeholder="搜条目、关键词，如 接地线、重合闸" value="' + h(KNOWPG.q) + '"></div><div class="kbq" style="margin:6px 0">' + KNOWPG.CATS.map(c => '<b data-act="kb-cat" data-k="' + c + '" style="' + (c === KNOWPG.cat ? 'background:var(--tint);color:var(--pri);border-color:#c9cbf5' : '') + '">' + c + (cats[c] ? ' ' + cats[c] : '') + '</b>').join('') + '</div><div id="kblist">' + KNOWPG.listHTML() + '</div></div></div>' +
    '<div><div class="card"><div class="h"><b>知识分布</b><span>按类别</span></div>' + CH.mini.donut(Object.keys(cats).map((c, i) => ({ k: c, v: cats[c], c: CPAL[i % 6], act: 'kb-cat', k: c })), { sub: '条' }) + '<div class="note" style="margin-top:4px">她最近引用</div><div id="kbuse">' + KNOWPG.useHTML() + '</div></div>' +
    '<div class="card" style="margin-top:10px"><div class="h"><b>典型案例</b><span>' + (CASES.length + CASES2.length + LS.get('cases', []).length) + ' 例 · 处理记录一键沉淀</span><div class="r"><button class="s" data-act="case-new">把田寮线 #7 存为案例</button></div></div><div id="cases">' + KNOWPG.cases() + '</div></div>' +
    '<div class="card" style="margin-top:10px"><div class="h"><b>班长与骨干经验</b><span>她问，你说，她整理</span><div class="r"><button class="s g" data-act="exp-start">经验访谈</button></div></div>' + exp.map(e => '<div class="casec"><b>' + h(e.t) + ' <span class="note">' + h(e.who) + '</span></b><div><i>要点</i><span>' + h(e.body) + '</span></div></div>').join('') + '</div></div></div>'; },
  after() { CH.mount($('#main')); const inp = $('#kbsearch'); if (inp) inp.addEventListener('input', () => { KNOWPG.q = inp.value; $('#kblist').innerHTML = KNOWPG.listHTML(); $('#kbcount').textContent = KNOWPG.list().length + ' 条'; }); if (KNOWPG.open) { const k = KNOWPG.all().find(x => x.id === KNOWPG.open); if (k) ACT['kb-open']({ dataset: { id: k.id } }); } }
};
Object.assign(ACT, {
  'kb-ask'(el) { XW.user(el.dataset.q, false); XW.at(400, () => KNOWPG.ask(el.dataset.q)); },
  'kb-src'(el) { el.nextElementSibling.classList.toggle('on'); },
  'kb-cat'(el) { KNOWPG.cat = el.dataset.k; if (S.page !== 'know') { ensure('know', () => {}); return; } $('#kblist').innerHTML = KNOWPG.listHTML(); $('#kbcount').textContent = KNOWPG.list().length + ' 条'; $$('.kbq [data-act="kb-cat"]').forEach(b => { b.style.cssText = b.dataset.k === KNOWPG.cat ? 'background:var(--tint);color:var(--pri);border-color:#c9cbf5' : ''; }); },
  'kb-open'(el) { const k = KNOWPG.all().find(x => x.id === el.dataset.id); if (!k) return; if (S.page !== 'know') { KNOWPG.open = k.id; ensure('know', () => {}); return; } KNOWPG.open = k.id; KNOWPG.use(k); $$('.kbitem').forEach(x => x.classList.toggle('on', x.dataset.id === k.id)); const host = $('#kba'); host.innerHTML = '<div class="note" style="margin-bottom:4px">' + h(k.t) + ' · ' + h(KNOWPG.catOf(k)) + '</div><div id="kbtext">' + h(k.body) + '</div><div class="src" data-act="kb-src">出处：' + h(k.src) + '（点开原文）</div><div class="orig">' + h(k.body) + '</div><div class="rel"><span class="note">相关：</span>' + KNOWPG.related(k).map(r => '<b data-act="kb-open" data-id="' + r.id + '">' + h(r.t) + '</b>').join('') + '</div>'; host.scrollIntoView({ block: 'nearest' }); const ul = $('#kbuse'); if (ul) ul.innerHTML = KNOWPG.useHTML(); XW.answer('"' + k.t + '"：' + k.body.slice(0, 40) + (k.body.length > 40 ? '……' : '') + ' 出处' + k.src.split(' · ')[0] + '。相关的还有' + KNOWPG.related(k).slice(0, 2).map(r => '"' + r.t + '"').join('、') + '。', null, { confirm: false, speak: false }); },
  'case-new'() { XW.state('write'); const d = XW.msg('a', '我把今天田寮线 #7 的处理整理成案例：<div class="draft"><span></span></div>'); const txt = '案例：田寮线 #7 杆拉线锈断\n现象：班组群照片发现拉线离地约 1.2 m 处锈断，杆身未倾斜\n原因：沿海高湿，拉线镀锌层脱落；该段线路 #9 杆一周前同类缺陷\n处理：列紧急隐患，王安现场确认断口未触地，纳入明日凤凰线作业顺路更换\n教训：台风季前对沿海段拉线专项巡视；群里照片当天登记不过夜\n规程：登杆作业（作业指导书 · 登杆）'; XW.type(d.querySelector('.draft span'), txt, 28, () => { XW.state(''); d.insertAdjacentHTML('beforeend', '<div class="bt"><button data-act="case-save">存入案例库</button><button class="g" data-act="no" data-t="改一下">改一下</button></div>'); XW.scrollChat(); }); },
  'case-save'() { const cs = LS.get('cases', []); if (!cs.some(c => c.t.includes('田寮线 #7'))) cs.push({ t: '田寮线 #7 杆拉线锈断', d: TODAY, who: '王安', sym: '群照片发现拉线离地约 1.2 m 处锈断', cause: '沿海高湿，镀锌层脱落', fix: '列紧急隐患，现场确认后纳入凤凰线作业顺路更换', lesson: '台风季前沿海段拉线专项巡视；群里照片当天登记', kb: 'k21' }); LS.set('cases', cs); if ($('#cases')) $('#cases').innerHTML = KNOWPG.cases(); XW.answer('存进案例库了。下次再有拉线的活，派工和审票的时候我会提这条。', null, { confirm: false }); },
  'exp-start'() { XW.answer('那我问你三个问题，你打字答就行。第一个：新人第一次上杆，你一般让他先做什么、不让他做什么？', null, { confirm: false }); XW._expWait = 1; },
  'exp-save'(el) { const ex = LS.get('exp', []); ex.push({ who: '赵立群', t: '新人上杆', body: el.dataset.body }); LS.set('exp', ex); XW.answer('记成一条经验了，放在"班长与骨干经验"里，署名赵立群。', null, { confirm: false }); if (S.page === 'know') render(); }
});
