/* ===== 台账中心（十七张台账、筛选检索、汇总图、导出、导入记录） · 问小瓦特 ===== */
const LEDGERPG = {
  tabs: [{ k: 'hours', n: '工时' }, { k: 'cert', n: '资质证书' }, { k: 'study', n: '学时' }, { k: 'task', n: '任务' }, { k: 'defect', n: '缺陷' }, { k: 'ticket', n: '两票' }, { k: 'weekly', n: '周报指标' }, { k: 'skill9', n: '核心技能' }, { k: 'vio', n: '违章' }, { k: 'safety', n: '安全活动' }, { k: 'honor', n: '荣誉' }, { k: 'train', n: '培训' }, { k: 'dispatch', n: '派工记录' }, { k: 'transfer', n: '跨班组调配' }, { k: 'duty', n: '值班' }, { k: 'notice', n: '通知' }, { k: 'log', n: '操作流水' }],
  who: '', q: '',
  SRC: { hours: 'OMS 工时 + 手工', cert: '证书台账（局）', study: '培训学时表', task: 'OMS 任务 + 关键节点管控表', defect: 'OMS 缺陷表 + 周报应用失败清单', ticket: '电网管理平台两票', weekly: '配网自动化周报第 ' + WK29.no + ' 期（' + WK29.by + '，' + WK29.issued + ' 编制）', skill9: '工作票工作负责人与工作班成员记录 + 班组长确认', vio: '违章记录（电网管理平台）', safety: '安全活动台账（手工）', honor: '局表彰文件', train: '培训学时表 + 本机', dispatch: '本机', transfer: '本机 · 管理者发起，班组长确认', duty: '本机', notice: '本机', log: '本机 · 她经手的每一步' },
  T(cols, rows, opt) { opt = opt || {}; const who = this.who, q = this.q.trim(); const shown = rows.filter(r => (!who || r.some(c => String(c).replace(/<[^>]+>/g, '').includes(who))) && (!q || r.some(c => String(c).replace(/<[^>]+>/g, '').includes(q)))); const tot = opt.sum != null ? shown.reduce((s, r) => s + (+String(r[opt.sum]).replace(/<[^>]+>/g, '') || 0), 0) : null; return '<div class="tbl"><table class="t"><tr>' + cols.map(c => '<th>' + h(c) + '</th>').join('') + '</tr>' + shown.map(r => '<tr>' + r.map(c => '<td>' + c + '</td>').join('') + '</tr>').join('') + (tot != null ? '<tr class="hl"><td colspan="' + (opt.sum) + '"><b>合计</b>（' + shown.length + ' 行）</td><td><b>' + tot + '</b></td>' + '<td></td>'.repeat(Math.max(0, cols.length - opt.sum - 1)) + '</tr>' : '') + '</table></div><div class="note" style="margin-top:4px">' + shown.length + ' / ' + rows.length + ' 行</div>'; },
  name(n) { return '<u class="num" data-act="hours" data-who="' + n + '">' + h(n) + '</u>'; },
  wkChart(k) { const it = WK29.item(k); const gm = WK29.gm(); return CH.mini.cols(WK29.bureaus.map((b, i) => ({ n: b, v: typeof it.vals[i] === 'number' ? it.vals[i] : 0, c: i === gm ? CPAL[1] : CPAL[0], tip: b + ' ' + it.vals[i] + it.unit })), { max: Math.max.apply(null, it.vals.map(v => +v || 0)) * 1.05, h: 120, labels: true }); },
  body() { const s = S.sub || 'hours'; const disp = LS.get('dispatch', {}); const duty = LS.get('duty'); const m = DB.month(); const tr = DB.transfers();
    const chart = { hours: CH.mini.bars(PEOPLE.filter(p => p.post !== '班长').map(p => ({ n: p.n, v: p.week, c: p.week >= WEEK_LIMIT ? '#e5484d' : CPAL[0], act: 'hours', who: p.n })), { limit: WEEK_LIMIT, unit: 'h', max: 30, h: 12 }),
      cert: CH.mini.timeline(CERTS.filter(c => !c.renewed && daysTo(c.due) <= 365).map(c => ({ n: c.who, t: daysTo(c.due), c: daysTo(c.due) <= 90 ? '#e5484d' : daysTo(c.due) <= 180 ? '#e8791d' : CPAL[0], lbl: daysTo(c.due) <= 90 ? c.who : '', tip: c.who + ' · ' + c.name + ' · ' + c.due, act: 'ch-cert' }))),
      study: CH.mini.bars(PEOPLE.map(p => ({ n: p.n, v: p.hours.done, c: p.hours.done < HOURS_DUE ? '#e8791d' : CPAL[4], act: 'p-hours', who: p.n })), { max: 60, limit: HOURS_DUE, h: 12 }),
      task: CH.mini.donut(DB.typeCounts().map(([k, v], i) => ({ k, v, c: TYPE_C[k] || CPAL[i], act: 'ch-task' })), { hero: m.jobsDone + '/' + m.jobs, sub: '本月' }),
      defect: CH.mini.funnel(DB.flow().map(s => ({ k: s.k, v: s.v, act: 'hz-stage' }))),
      ticket: CH.mini.line([{ n: '开出', vals: DB.ticketM().n, c: RAMP[2] }, { n: '合格', vals: DB.ticketM().ok, c: CPAL[0] }], DB.ticketM().m, { h: 120 }),
      weekly: CH.mini.bars(WK29.items.filter(i => WK29.rank(i.k)).map(i => ({ n: i.n.replace(/（.*）/, '').slice(0, 9), v: WK29.rank(i.k), c: WK29.rank(i.k) <= 4 ? CPAL[4] : WK29.rank(i.k) >= 9 ? '#e5484d' : CPAL[0], act: 'wk29', k: i.k, tip: i.n + ' · 全市第 ' + WK29.rank(i.k) + ' / 11' })), { max: 11, unit: '', h: 11, x0: 96 }) + '<div class="note" style="margin-top:4px">条越短排名越靠前（全市 11 个区局）。红色为第 9 名以后，点一条看 11 局分布。</div>',
      skill9: CH.mini.bars(skillCover().map(c => ({ n: c.s.n.replace(/10kV |配电自动化/g, '').slice(0, 9), v: c.n, c: c.risk === '高' ? '#e5484d' : CPAL[0], act: 'skill-cover', k: c.s.k, tip: c.s.n + ' · 本年实操 ' + c.n + ' 次 · 可自主 ' + c.a.length + ' 人' })), { unit: ' 次', h: 12, x0: 96 }),
      vio: CH.mini.cols(TICKET_M.m.map((n, i) => ({ n, v: VIO_M[i], c: VIO_M[i] ? '#e8791d' : CPAL[4] })), { max: 3, h: 100, labels: true }),
      safety: CH.mini.cols(SAFETY_HIST.slice().reverse().map(x => ({ n: x.d, v: x.n, c: CPAL[4] })), { max: 12, h: 110, labels: true }),
      honor: CH.mini.cols([['2024', 1], ['2025', 3], ['2026', 1]].map(([n, v]) => ({ n, v, c: CPAL[1] })), { max: 4, h: 100, labels: true }),
      train: CH.mini.bars(PEOPLE.map(p => ({ n: p.n, v: (TRAIN_DONE[p.n] || []).length, c: CPAL[5] })), { max: 7, unit: ' 门', h: 12 }),
      dispatch: CH.mini.cols([['本周', Object.keys(disp).length + 2], ['上周', 4], ['上上周', 5]].map(([n, v]) => ({ n, v, c: CPAL[2] })), { max: 8, h: 100, labels: true }),
      transfer: CH.mini.donut([{ k: '待确认', v: tr.filter(t => t.st === '待确认').length, c: '#e8791d' }, { k: '已确认', v: tr.filter(t => t.st === '已确认').length, c: CPAL[4] }, { k: '已退回', v: tr.filter(t => t.st === '已退回').length, c: '#e5484d' }].filter(x => x.v), { sub: '条' }) || '',
      duty: CH.mini.bars(PEOPLE.filter(p => p.post !== '班长').map((p, i) => ({ n: p.n, v: [3, 4, 3, 2, 3, 2, 3, 2, 2, 1, 2][i] || 2, c: CPAL[5] })), { unit: ' 次', max: 6, h: 12 }),
      notice: CH.mini.donut([{ k: '已读', v: 14 + DB.notices().length - NOTICES.length, c: CPAL[4] }, { k: '未读', v: 2, c: '#e8791d' }], { sub: '条' }),
      log: (() => { const c = {}; DB.logs().forEach(l => { c[l.kind] = (c[l.kind] || 0) + 1; }); const ks = Object.keys(c); return ks.length ? CH.mini.bars(ks.map((k, i) => ({ n: k, v: c[k], c: CPAL[i % 6] })), { max: Math.max(4, ...ks.map(k => c[k])) + 1, unit: ' 条', h: 12 }) : '<div class="empty">还没有经手记录</div>'; })() }[s];
    let table = '';
    if (s === 'cert') table = this.T(['姓名', '证书', '取得', '复审期限', '剩余'], CERTS.map(c => [this.name(c.who), h(c.name), c.got, c.due, c.renewed ? '<span class="tag ok">已复审 ' + c.renewed + '</span>' : daysTo(c.due) <= 90 ? '<span class="tag bad">' + daysTo(c.due) + ' 天</span>' : daysTo(c.due) + ' 天']));
    else if (s === 'study') table = this.T(['姓名', '本月', '年度已完成', '年度要求', '进度'], PEOPLE.map(p => [this.name(p.n), (p.hours.m < 3 ? '<span class="tag bad">' : '<span class="tag ok">') + p.hours.m + '/5</span>', p.hours.done, p.hours.req, Math.round(p.hours.done / p.hours.req * 100) + '%']), { sum: 2 });
    else if (s === 'task') table = this.T(['日期', '类型', '站点 / 片区', '人员', '状态'], DB.taskLedger().map(t => [t.d, h(t.t), h(t.line), String(t.who).split('、').map(w => P[w] ? this.name(w) : h(w)).join('、'), /已完成|已关闭/.test(t.st) ? '<span class="tag ok">' + h(t.st) + '</span>' : '<span class="tag ' + (t.st === '超期' ? 'bad' : /进行中/.test(t.st) ? 'c' : 'w') + '">' + h(t.st) + '</span>']));
    else if (s === 'defect') table = this.T(['缺陷', '等级', '登记', '时限', '状态', '来源'], DB.defects().map(d => [h(d.t), '<span class="tag ' + (/紧急|重大/.test(d.lv) ? 'bad' : 'w') + '">' + h(d.lv) + '</span>', d.reg, d.limit + ' 天', /超期/.test(d.st) ? '<span class="tag bad">' + h(d.st) + '</span>' : h(d.st), '<span class="note">' + h(d.src || '') + '</span>']));
    else if (s === 'ticket') table = this.T(['票号', '类型', '任务', '负责人', '状态'], DB.tickets().map(t => [h(t.no), h(t.kind), h(t.task), P[t.lead] ? this.name(t.lead) : h(t.lead), '<span class="tag ' + (/已审核|已签发|已执行/.test(t.st) ? 'ok' : t.st === '已退回' ? 'bad' : 'w') + '">' + h(t.st) + (t.uploaded ? ' · 上传' : '') + '</span>']));
    else if (s === 'weekly') table = this.T(['指标', '光明局', '全市', '全市排名', '关键节点', '光明明细'], WK29.items.map(i => { const r = WK29.rank(i.k); const nd = NODES.find(n => n.id === i.node); return ['<u class="num" data-act="wk29" data-k="' + i.k + '">' + h(i.n) + '</u>' + (i.star ? ' <span class="tag v">星级</span>' : ''), '<b class="mono">' + h(String(i.vals[WK29.gm()])) + h(i.unit) + '</b>', h(String(i.total)) + h(i.unit), r ? '<span class="tag ' + (r <= 4 ? 'ok' : r >= 9 ? 'bad' : '') + '">第 ' + r + '</span>' : '—', nd ? h(nd.t) + ' <span class="note">' + h(nd.cyc) + '</span>' : '—', '<span class="note">' + h(i.detail) + '</span>']; }));
    else if (s === 'skill9') table = this.T(['姓名'].concat(SKILL9.map(x => x.n.replace(/10kV |配电自动化/g, '').slice(0, 6)), ['可自主', '本年实操']), PEOPLE.map(p => { const q = skill9Of(p); return [this.name(p.n)].concat(q.q.map((v, i) => '<span class="tag ' + (v === 'A' ? 'ok' : v === 'B' ? 'w' : '') + '">' + (v === '-' ? '—' : v) + ' ' + q.n[i] + '</span>'), [q.a + '/9', '<b class="mono">' + q.total + '</b>']); }));
    else if (s === 'vio') table = this.T(['日期', '人员', '违章', '等级', '处理'], VIOLATIONS.map(v => [v.d, P[v.who] ? this.name(v.who) : h(v.who), h(v.t), '<span class="tag ' + (v.lv === '严重' ? 'bad' : 'w') + '">' + h(v.lv) + '</span>', h(v.fix)]));
    else if (s === 'safety') table = this.T(['日期', '活动', '主持', '参加人数'], SAFETY_HIST.map(a => ['2026-' + a.d, h(a.t), this.name(a.host), a.n]), { sum: 3 });
    else if (s === 'honor') table = this.T(['获得者', '荣誉', '时间'], HONORS.map(a => [a.who === '班组' ? '班组' : this.name(a.who), h(a.t), a.d]));
    else if (s === 'train') table = this.T(['姓名', '已学课程', '本年考试', '最近成绩'], PEOPLE.map(p => { const hs = SCORE_HIST[p.n] || []; return [this.name(p.n), (TRAIN_DONE[p.n] || []).map(id => COURSES.find(c => c.id === id).n.slice(0, 6)).join('、') || '—', hs.length, hs.length ? hs[hs.length - 1].t + ' ' + hs[hs.length - 1].s : '—']; }));
    else if (s === 'dispatch') table = this.T(['任务', '日期', '负责人', '班员', '随队', '推荐 / 排除理由', '时间'], Object.values(disp).map(r => [h(r.t), h(r.date), this.name(r.lead), (r.crew || []).map(n => this.name(n)).join(' '), h(r.learn || '—'), '<span class="note">' + h((r.reasons || []).slice(0, 3).join('；') || '—') + '</span>', new Date(r.ts).toTimeString().slice(0, 5)]).concat([['交换机取电排查 · 直流电源空开复核', '08-07 14:00', this.name('吴倩'), this.name('周明'), '—', '<span class="note">吴倩 二次回路可自主；周明 本周 12h</span>', '08-06 17:20'], ['晨操、遥控验证 · 本期 8 单', '08-07 09:00', this.name('韩雪'), this.name('陈浩'), '—', '<span class="note">韩雪 主站应用 L4；陈浩 带教</span>', '08-06 17:20']]));
    else if (s === 'transfer') table = tr.length ? this.T(['发起', '人员', '从', '到', '期间', '理由', '状态'], tr.map(t => [t.d || '', h(t.who), h(t.from), h(t.to), h(t.days), h(t.why), '<span class="tag ' + (t.st === '已确认' ? 'ok' : t.st === '已退回' ? 'bad' : 'w') + '">' + h(t.st) + '</span>'])) : '<div class="empty">还没有跨班组调配记录。管理者在「风险与统筹」发起，班组长在全流程里确认</div>';
    else if (s === 'duty') table = duty ? this.T(['值班日', '白班 A', '白班 B', '夜班'], DAYS7.map((d, di) => [d, this.name(duty.grid[di + '-0'] || ''), this.name(duty.grid[di + '-1'] || ''), this.name(duty.grid[di + '-2'] || '')])) : '<div class="empty">下周值班表还没排，去用工安排排一下</div>';
    else if (s === 'notice') table = this.T(['时间', '通知', '接收人', '状态'], DB.notices().map(n => [n.d, h(n.t), h(n.to), '<span class="tag c">' + h(n.st) + '</span>']));
    else if (s === 'log') table = DB.logs().length ? this.T(['时间', '角色', '类别', '内容'], DB.logs().map(l => [l.d, '<span class="tag ' + (l.role === 'manager' ? 'v' : '') + '">' + (l.role === 'manager' ? '管理者' : '班组长') + '</span>', '<span class="tag">' + h(l.kind) + '</span>', h(l.text)])) : '<div class="empty">她还没经手任何操作。派一次工、审一张票、添加一项任务，这里就有记录</div>';
    else table = this.T(['日期', '人员', '作业', '小时'], DB.hours().map(r => [r.d, this.name(r.who), h(r.job) + (r.added ? ' <span class="tag ok">今日完工</span>' : ''), r.h]), { sum: 3 });
    return '<div class="grid2" style="grid-template-columns:1fr 2fr"><div><div class="card"><div class="h"><b>汇总</b><span>点图她说</span></div>' + chart + '</div><div class="card" style="margin-top:10px"><div class="h"><b>数据来源</b></div><div class="note" style="color:var(--ink)">' + h(this.SRC[s]) + '</div><div class="note" style="margin-top:8px;margin-bottom:2px">最近导入</div>' + IMPORTS.map(i => '<div class="note" style="color:var(--ink);margin:2px 0">' + h(i.d) + ' ' + h(i.src) + ' <span class="note">' + i.n + ' 行 · ' + h(i.by) + '</span></div>').join('') + '</div></div>' +
      '<div class="card"><div class="h"><b>' + h(this.tabs.find(t => t.k === s).n) + '台账</b><span>点人名她照亮那几行</span><div class="r"><button class="s g" data-act="led-export">导出</button></div></div><div class="ledf"><select id="ledwho"><option value="">全部人员</option>' + PEOPLE.map(p => '<option' + (p.n === this.who ? ' selected' : '') + '>' + h(p.n) + '</option>').join('') + '</select><input id="ledq" placeholder="搜索这张台账" value="' + h(this.q) + '"></div><div id="ledtable">' + table + '</div></div></div>'; }
};
PAGES.ledger = {
  render() { return cmdHTML(['李文博这周工时怎么算的', '三个月内证书到期的有谁', '本月学时未完成的名单', '华发民公用柜缺陷现在什么状态', '本期在线率全市第几']) + pageHead('台账中心', '十七张台账 · 点人名她照亮那几行 · 问她任何一个数') + tabsHTML(LEDGERPG.tabs, S.sub || 'hours') + '<div id="ledbody">' + LEDGERPG.body() + '</div>'; },
  after() { CH.mount($('#main')); const w = $('#ledwho'), q = $('#ledq'); const re = () => { LEDGERPG.who = w.value; LEDGERPG.q = q.value; $('#ledbody').innerHTML = LEDGERPG.body(); CH.mount($('#ledbody')); PAGES.ledger.after(); }; if (w) w.addEventListener('change', re); if (q) q.addEventListener('input', () => { LEDGERPG.q = q.value; const t = $('#ledtable'); const tmp = document.createElement('div'); tmp.innerHTML = LEDGERPG.body(); t.innerHTML = $('#ledtable', tmp).innerHTML; }); }
};
PAGES.ask = {
  render() { const mgr = role() === 'manager'; const G = mgr ? [{ t: '态势与风险', qs: ['三个班组这周的风险在哪', '哪个班组证书到期的最多', '下个月人力缺口在哪', '光明局在线率全市第几', '关键节点这周清了多少'] }, { t: '统筹与调配', qs: ['试验班张伟借到自动化班三天', '田寮站交接试验缺电缆证的人怎么办', '三个班本月两票合格率', '哪个班组工时最不均衡'] }, { t: '履职与梯队', qs: ['三个班长这周的履职情况', '近三年人才输出有哪些', '五年后哪个班组骨干断层最重', '电力电缆作业证三个班组各几人'] }, { t: '参谋输出', qs: ['写一份部门周汇报', '写一份组织效能复盘', '生成星级对标差距清单'] }] :
    [{ t: '查数', qs: ['三个月内证书到期的有谁', '本月学时未完成的名单', '李文博这周工时怎么算的', '华发民公用柜缺陷现在什么状态', '本月两票合格率', '本期周报在线率全市第几', '谁持有电力电缆作业证'] }, { t: '安排与决策参考', qs: ['加一个任务：光侨路 3# 公用柜 频繁投退处理', '下周一田寮站验收谁去合适', '排下周值班表', '关键节点这周清了多少', '下周谁的活最多', '谁适合参加下季度的技能竞赛'] }, { t: '生成', qs: ['上传一张工作票', '写今天的班前会材料', '生成本月的月度总结', '写下周计划', '从光差保护课件出五道题'] }, { t: '人', qs: ['刘一鸣最近怎么样', '黄伟强最近怎么样', '给郭子扬打倒闸操作实操分', '按陈浩的短板组一套卷'] }, { t: '知识', qs: ['站内馈线保护定值是多少', '缺陷限时闭环是几天', '遥控失败先查什么', '交换机取电怎么复核', '自主实施怎么认定', '考我一道安规题'] }];
    return cmdHTML([]) + pageHead('问小瓦特', mgr ? '能查、能比、能发起调配、能写参谋材料；涉及人的结论由班组长确认' : '能查、能提醒、能生成、能办；答数字时她会配一张图；涉及人的结论由班组长确认') + '<div class="grid2">' + G.map(g => '<div class="card"><div class="h"><b>' + h(g.t) + '</b></div><div class="kbq">' + g.qs.map(q => '<b data-act="say" data-say="' + h(q) + '">' + h(q) + '</b>').join('') + '</div></div>').join('') + '</div>'; },
  after() { XW.at(300, () => { if (!$$('#chat .msg').length) XW.answer('想办什么点一条，或者直接打字。语音在输入框右边，说完我先复述一遍再办。', null, { confirm: false }); }); }
};
Object.assign(ACT, {
  'led-export'() { XW.fly('已导出 ' + LEDGERPG.tabs.find(t => t.k === (S.sub || 'hours')).n + '台账 · Excel'); XW.answer('导出了，带筛选条件，' + (LEDGERPG.who ? '只有' + LEDGERPG.who + '的行。' : '全部行。'), null, { confirm: false }); },
  wk29(el) { const it = WK29.item(el.dataset.k); if (!it) return; const r = WK29.rank(it.k); const nd = NODES.find(n => n.id === it.node); const gm = WK29.gm();
    XW.answer(it.n + '：光明局 ' + it.vals[gm] + it.unit + '，全市 ' + it.total + it.unit + (r ? '，排第 ' + r + '' : '') + '。' + it.detail + '。' + (nd ? '对应关键节点「' + nd.t + '」（' + nd.cyc + '，A ' + nd.a + ' / B ' + nd.b + '）。' : '') + (r && r >= 9 ? '排在后三分之一，这周的节点要盯。' : r && r <= 3 ? '全市前三。' : ''), null, { confirm: false, chart: typeof it.vals[0] === 'number' ? LEDGERPG.wkChart(it.k) + CH.mini.legend([{ n: '光明', c: CPAL[1] }, { n: '其他区局', c: CPAL[0] }]) : null, done() { if (nd) XW.card('<div class="bt" style="margin-top:0"><button class="g" data-act="node-open" data-id="' + nd.id + '">看关键节点 ' + h(nd.t) + '</button></div>'); } }); }
});
