/* ===== 台账中心（十二张台账、筛选检索、汇总图、导出、导入记录） · 所级视图（三班组对比、人力缺口、借调、所级月报） · 问小瓦特 ===== */
const LEDGERPG = {
  tabs: [{ k: 'hours', n: '工时' }, { k: 'cert', n: '资质证书' }, { k: 'study', n: '学时' }, { k: 'task', n: '任务' }, { k: 'defect', n: '缺陷' }, { k: 'ticket', n: '两票' }, { k: 'safety', n: '安全活动' }, { k: 'honor', n: '荣誉' }, { k: 'train', n: '培训' }, { k: 'dispatch', n: '派工记录' }, { k: 'duty', n: '值班' }, { k: 'notice', n: '通知' }, { k: 'log', n: '操作流水' }],
  who: '', q: '',
  SRC: { hours: 'OMS 工时 + 手工', cert: '人资证书系统', study: '培训学时表（人资）', task: 'OMS 任务', defect: 'OMS 缺陷表', ticket: '两票台账（手工）', safety: '安全活动台账（手工）', honor: '人资', train: '培训学时表 + 本机', dispatch: '本机', duty: '本机', notice: '本机', log: '本机 · 她经手的每一步' },
  T(cols, rows, opt) { opt = opt || {}; const who = this.who, q = this.q.trim(); const shown = rows.filter(r => (!who || r.some(c => String(c).replace(/<[^>]+>/g, '').includes(who))) && (!q || r.some(c => String(c).replace(/<[^>]+>/g, '').includes(q)))); const tot = opt.sum != null ? shown.reduce((s, r) => s + (+String(r[opt.sum]).replace(/<[^>]+>/g, '') || 0), 0) : null; return '<div class="tbl"><table class="t"><tr>' + cols.map(c => '<th>' + h(c) + '</th>').join('') + '</tr>' + shown.map(r => '<tr>' + r.map(c => '<td>' + c + '</td>').join('') + '</tr>').join('') + (tot != null ? '<tr class="hl"><td colspan="' + (opt.sum) + '"><b>合计</b>（' + shown.length + ' 行）</td><td><b>' + tot + '</b></td>' + '<td></td>'.repeat(Math.max(0, cols.length - opt.sum - 1)) + '</tr>' : '') + '</table></div><div class="note" style="margin-top:4px">' + shown.length + ' / ' + rows.length + ' 行</div>'; },
  name(n) { return '<u class="num" data-act="hours" data-who="' + n + '">' + h(n) + '</u>'; },
  body() { const s = S.sub || 'hours'; const disp = LS.get('dispatch', {}); const duty = LS.get('duty');
    const chart = { hours: CH.mini.bars(PEOPLE.filter(p => p.post !== '班长').map(p => ({ n: p.n, v: p.week, c: p.week >= WEEK_LIMIT ? '#e5484d' : CPAL[0], act: 'hours', who: p.n })), { limit: WEEK_LIMIT, unit: 'h', max: 30, h: 12 }),
      cert: CH.mini.timeline(CERTS.filter(c => !c.renewed && daysTo(c.due) <= 365).map(c => ({ n: c.who, t: daysTo(c.due), c: daysTo(c.due) <= 90 ? '#e5484d' : daysTo(c.due) <= 180 ? '#e8791d' : CPAL[0], lbl: daysTo(c.due) <= 90 ? c.who : '', tip: c.who + ' · ' + c.name + ' · ' + c.due, act: 'ch-cert' }))),
      study: CH.mini.bars(PEOPLE.map(p => ({ n: p.n, v: p.hours.done, c: p.hours.done < 40 ? '#e8791d' : CPAL[4], act: 'p-hours', who: p.n })), { max: 60, limit: 40, h: 12 }),
      task: CH.mini.donut(DB.typeCounts().map(([k, v], i) => ({ k, v, c: TYPE_C[k] || CPAL[i], act: 'ch-task' })), { hero: MONTH.jobsDone + '/' + MONTH.jobs, sub: '本月' }),
      defect: CH.mini.funnel(DB.flow().map(s => ({ k: s.k, v: s.v, act: 'hz-stage' }))),
      ticket: CH.mini.line([{ n: '开出', vals: DB.ticketM().n, c: RAMP[2] }, { n: '合格', vals: DB.ticketM().ok, c: CPAL[0] }], DB.ticketM().m, { h: 120 }),
      safety: CH.mini.cols(SAFETY_HIST.slice().reverse().map(x => ({ n: x.d, v: x.n, c: CPAL[4] })), { max: 12, h: 110, labels: true }),
      honor: CH.mini.cols([['2024', 1], ['2025', 3], ['2026', 1]].map(([n, v]) => ({ n, v, c: CPAL[1] })), { max: 4, h: 100, labels: true }),
      train: CH.mini.bars(PEOPLE.map(p => ({ n: p.n, v: (TRAIN_DONE[p.n] || []).length, c: CPAL[5] })), { max: 7, unit: ' 门', h: 12 }),
      dispatch: CH.mini.cols([['本周', Object.keys(disp).length + 2], ['上周', 4], ['上上周', 5]].map(([n, v]) => ({ n, v, c: CPAL[2] })), { max: 8, h: 100, labels: true }),
      duty: CH.mini.bars(PEOPLE.filter(p => p.post !== '班长').map((p, i) => ({ n: p.n, v: [3, 4, 3, 2, 3, 2, 3, 2, 2, 1, 2][i] || 2, c: CPAL[5] })), { unit: ' 次', max: 6, h: 12 }),
      notice: CH.mini.donut([{ k: '已读', v: 14 + DB.notices().length - NOTICES.length, c: CPAL[4] }, { k: '未读', v: 2, c: '#e8791d' }], { sub: '条' }),
      log: (() => { const c = {}; DB.logs().forEach(l => { c[l.kind] = (c[l.kind] || 0) + 1; }); const ks = Object.keys(c); return ks.length ? CH.mini.bars(ks.map((k, i) => ({ n: k, v: c[k], c: CPAL[i % 6] })), { max: Math.max(4, ...ks.map(k => c[k])) + 1, unit: ' 条', h: 12 }) : '<div class="empty">还没有经手记录</div>'; })() }[s];
    let table = '';
    if (s === 'cert') table = this.T(['姓名', '证书', '取得', '复审期限', '剩余'], CERTS.map(c => [this.name(c.who), h(c.name), c.got, c.due, c.renewed ? '<span class="tag ok">已复审 ' + c.renewed + '</span>' : daysTo(c.due) <= 90 ? '<span class="tag bad">' + daysTo(c.due) + ' 天</span>' : daysTo(c.due) + ' 天']));
    else if (s === 'study') table = this.T(['姓名', '本月', '年度已完成', '年度要求', '进度'], PEOPLE.map(p => [this.name(p.n), (p.hours.m < 3 ? '<span class="tag bad">' : '<span class="tag ok">') + p.hours.m + '/5</span>', p.hours.done, p.hours.req, Math.round(p.hours.done / p.hours.req * 100) + '%']), { sum: 2 });
    else if (s === 'task') table = this.T(['日期', '类型', '线路 / 站', '人员', '状态'], DB.taskLedger().map(t => [t.d, h(t.t), h(t.line), t.who.split('、').map(w => P[w] ? this.name(w) : h(w)).join('、'), /已完成|已关闭/.test(t.st) ? '<span class="tag ok">' + h(t.st) + '</span>' : '<span class="tag ' + (t.st === '超期' ? 'bad' : /进行中/.test(t.st) ? 'c' : 'w') + '">' + h(t.st) + '</span>']));
    else if (s === 'defect') table = this.T(['缺陷', '等级', '登记', '时限', '状态', '来源'], DB.defects().map(d => [h(d.t), '<span class="tag ' + (d.lv === '紧急' ? 'bad' : 'w') + '">' + h(d.lv) + '</span>', d.reg, d.limit + ' 天', h(d.st), '<span class="note">' + h(d.src) + '</span>']));
    else if (s === 'ticket') table = this.T(['票号', '类型', '任务', '负责人', '状态'], DB.tickets().map(t => [h(t.no), h(t.kind), h(t.task), P[t.lead] ? this.name(t.lead) : h(t.lead), '<span class="tag ' + (/已审核|已签发|已执行/.test(t.st) ? 'ok' : t.st === '已退回' ? 'bad' : 'w') + '">' + h(t.st) + (t.uploaded ? ' · 上传' : '') + '</span>']).concat([['配一 2026-0901-02', '第一种工作票', '凤凰线 #9 杆拉线更换', this.name('黄伟强'), '<span class="tag ok">已完成 · 合格</span>'], ['配一 2026-0902-01', '第二种工作票', '志远站 F14 消缺', this.name('黄伟强'), '<span class="tag ok">已完成 · 合格</span>'], ['配一 2026-0902-03', '第二种工作票', '光明变出线柜检查', this.name('韩雪'), '<span class="tag ok">已完成 · 合格</span>'], ['配一 2026-0828-01', '第一种工作票', '塘尾线 #22 杆拉线更换', this.name('李文博'), '<span class="tag ok">已完成 · 合格</span>']]));
    else if (s === 'safety') table = this.T(['日期', '活动', '主持', '参加人数'], SAFETY_HIST.map(a => ['2026-' + a.d, h(a.t), this.name(a.host), a.n]), { sum: 3 });
    else if (s === 'honor') table = this.T(['获得者', '荣誉', '时间'], HONORS.map(a => [a.who === '班组' ? '班组' : this.name(a.who), h(a.t), a.d]));
    else if (s === 'train') table = this.T(['姓名', '已学课程', '本年考试', '最近成绩'], PEOPLE.map(p => { const hs = SCORE_HIST[p.n] || []; return [this.name(p.n), (TRAIN_DONE[p.n] || []).map(id => COURSES.find(c => c.id === id).n.slice(0, 6)).join('、') || '—', hs.length, hs.length ? hs[hs.length - 1].t + ' ' + hs[hs.length - 1].s : '—']; }));
    else if (s === 'dispatch') table = this.T(['任务', '日期', '负责人', '班员', '随队', '时间'], Object.values(disp).map(r => [h(r.t), h(r.date), this.name(r.lead), r.crew.map(n => this.name(n)).join(' '), h(r.learn), new Date(r.ts).toTimeString().slice(0, 5)]).concat([['凤凰线 #9 杆拉线更换', '09-01 09:00', this.name('黄伟强'), this.name('李文博') + ' ' + this.name('郭子扬'), '—', '08-31 17:20'], ['志远站 F14 消缺', '09-02 09:00', this.name('黄伟强'), this.name('李文博'), '—', '09-01 17:40']]));
    else if (s === 'duty') table = duty ? this.T(['值班日', '白班 A', '白班 B', '夜班'], DAYS7.map((d, di) => [d, this.name(duty.grid[di + '-0'] || ''), this.name(duty.grid[di + '-1'] || ''), this.name(duty.grid[di + '-2'] || '')])) : '<div class="empty">下周值班表还没排，去班务日程排一下</div>';
    else if (s === 'notice') table = this.T(['时间', '通知', '接收人', '状态'], DB.notices().map(n => [n.d, h(n.t), h(n.to), '<span class="tag c">' + h(n.st) + '</span>']));
    else if (s === 'log') table = DB.logs().length ? this.T(['时间', '类别', '内容'], DB.logs().map(l => [l.d, '<span class="tag">' + h(l.kind) + '</span>', h(l.text)])) : '<div class="empty">她还没经手任何操作。派一次工、审一张票、添加一项任务，这里就有记录</div>';
    else table = this.T(['日期', '人员', '作业', '小时'], DB.hours().map(r => [r.d, this.name(r.who), h(r.job) + (r.added ? ' <span class="tag ok">今日完工</span>' : ''), r.h]), { sum: 3 });
    return '<div class="grid2" style="grid-template-columns:1fr 2fr"><div><div class="card"><div class="h"><b>汇总</b><span>点图她说</span></div>' + chart + '</div><div class="card" style="margin-top:10px"><div class="h"><b>数据来源</b></div><div class="note" style="color:var(--ink)">' + h(this.SRC[s]) + '</div><div class="note" style="margin-top:8px;margin-bottom:2px">最近导入</div>' + IMPORTS.map(i => '<div class="note" style="color:var(--ink);margin:2px 0">' + h(i.d) + ' ' + h(i.src) + ' <span class="note">' + i.n + ' 行 · ' + h(i.by) + '</span></div>').join('') + '</div></div>' +
      '<div class="card"><div class="h"><b>' + h(this.tabs.find(t => t.k === s).n) + '台账</b><span>点人名她照亮那几行</span><div class="r"><button class="s g" data-act="led-export">导出</button></div></div><div class="ledf"><select id="ledwho"><option value="">全部人员</option>' + PEOPLE.map(p => '<option' + (p.n === this.who ? ' selected' : '') + '>' + h(p.n) + '</option>').join('') + '</select><input id="ledq" placeholder="搜索这张台账" value="' + h(this.q) + '"></div><div id="ledtable">' + table + '</div></div></div>'; }
};
PAGES.ledger = {
  render() { return cmdHTML(['李文博这周工时怎么算的', '三个月内证书到期的有谁', '本月学时未完成的名单', '志远站 F14 缺陷现在什么状态', '本月两票合格率']) + pageHead('台账中心', '十二张台账 · 点人名她照亮那几行 · 问她任何一个数') + tabsHTML(LEDGERPG.tabs, S.sub || 'hours') + '<div id="ledbody">' + LEDGERPG.body() + '</div>'; },
  after() { CH.mount($('#main')); const w = $('#ledwho'), q = $('#ledq'); const re = () => { LEDGERPG.who = w.value; LEDGERPG.q = q.value; $('#ledbody').innerHTML = LEDGERPG.body(); CH.mount($('#ledbody')); PAGES.ledger.after(); }; if (w) w.addEventListener('change', re); if (q) q.addEventListener('input', () => { LEDGERPG.q = q.value; const t = $('#ledtable'); const tmp = document.createElement('div'); tmp.innerHTML = LEDGERPG.body(); t.innerHTML = $('#ledtable', tmp).innerHTML; }); }
};
/* ---------- 所级视图 ---------- */
const OFFICEPG = {
  month: 5, team: null,
  render() { const names = Object.keys(TEAMS2); const m = this.month; return cmdHTML(['三个班本月培训完成情况', '哪个班证书到期的最多', '所里下个月人力缺口在哪', '本月三个班两票合格率', '生成所级月报']) + pageHead('所级视图', '三个班组的同一套数据汇总 · 不排名 · 点进任一班组', '<div class="kbq">' + MONTHS6.map((x, i) => '<b data-act="of-month" data-i="' + i + '" style="' + (i === m ? 'background:var(--tint);color:var(--pri);border-color:#c9cbf5' : '') + '">' + x + '</b>').join('') + '</div>') +
    '<div class="teams">' + TEAMS.map((t, i) => { const d = TEAMS2[t.n]; return '<div class="tc' + (this.team === t.n ? ' on' : '') + '" data-act="team" data-n="' + h(t.n) + '"><h5>' + h(t.n) + ' <span class="note">班长 ' + h(t.leader) + ' · ' + t.size + ' 人</span></h5><div><span>年度学时完成</span><b>' + d.hoursM[m] + '%</b></div><div><span>证书 90 天内到期</span><b>' + TEAM_CERTS[t.n] + '</b></div><div><span>本月两票</span><b>' + d.ticketsM[m] + ' 张</b></div><div><span>本月任务</span><b>' + d.jobsM[m] + ' 项</b></div>' + CH.mini.line([{ n: '学时', vals: d.hoursM, c: CPAL[i] }], MONTHS6, { max: 100, h: 70, pct: true }) + '</div>'; }).join('') + '</div>' +
    '<div class="grid3 charts"><div class="card chart"><div class="h"><b>年度学时完成 · 三班对比</b><span>%</span></div>' + CH.mini.group(MONTHS6, names.map((n, i) => ({ n: n.replace('配电', ''), vals: TEAMS2[n].hoursM, c: CPAL[i], act: 'of-cell' })), { max: 100, unit: '%', h: 140 }) + CH.mini.legend(names.map((n, i) => ({ n: n.replace('配电', ''), c: CPAL[i] }))) + '</div><div class="card chart"><div class="h"><b>两票开出 · 三班</b><span>张</span></div>' + CH.mini.group(MONTHS6, names.map((n, i) => ({ n: n.replace('配电', ''), vals: TEAMS2[n].ticketsM, c: CPAL[i], act: 'of-cell' })), { h: 140 }) + '</div><div class="card chart"><div class="h"><b>任务完成 · 三班</b><span>项</span></div>' + CH.mini.group(MONTHS6, names.map((n, i) => ({ n: n.replace('配电', ''), vals: TEAMS2[n].jobsM, c: CPAL[i], act: 'of-cell' })), { h: 140 }) + '</div></div>' +
    '<div class="grid2"><div class="card"><div class="h"><b>人力缺口 · 未来 8 周</b><span>需求超过可用的人数 · 点一格她提借调</span></div>' + CH.mini.heat(names.map(n => n.replace('配电', '')), WEEKS8.map(w => w.replace('第', '').replace('周', '')), names.map(n => TEAMS2[n].cap), { max: 5, act: 'of-cap', fmt: v => v ? '缺 ' + v + ' 人' : '够' }) + '<div class="note" style="margin-top:4px">深色 = 缺人多。一班 39 周台风季专项巡视加证书复审最紧。</div></div>' +
    '<div class="card"><div class="h"><b>线路隐患 · 按班组</b><span>本月</span></div>' + CH.mini.bars(names.reduce((a, n, i) => a.concat(TEAMS2[n].lines.map(l => ({ n: l[0], v: l[1], c: CPAL[i], tip: n + ' · ' + l[0] + ' ' + l[1] + ' 处' }))), []), { max: 5, unit: ' 处', h: 12 }) + CH.mini.legend(names.map((n, i) => ({ n: n.replace('配电', ''), c: CPAL[i] }))) + '</div></div>' +
    '<div class="grid2"><div class="card"><div class="h"><b>证书到期 · 三班 · 未来一年</b><span>点一个看</span></div>' + CH.mini.timeline(CERTS.filter(c => !c.renewed && daysTo(c.due) <= 365).map(c => ({ n: c.who, t: daysTo(c.due), c: CPAL[0], lbl: daysTo(c.due) <= 90 ? c.who : '', tip: '一班 · ' + c.who + ' · ' + c.name + ' · ' + c.due, act: 'ch-cert' })).concat([{ n: '周建国', t: 60, c: CPAL[1], lbl: '周建国', tip: '二班 · 周建国 · 高压电工证 · 60 天' }, { n: '刘畅', t: 45, c: CPAL[2], lbl: '刘畅', tip: '抢修班 · 刘畅 · 登高作业证 · 45 天' }, { n: '张伟', t: 80, c: CPAL[2], lbl: '张伟', tip: '抢修班 · 张伟 · 带电作业资格 · 80 天' }, { n: '吴磊', t: 200, c: CPAL[1], tip: '二班 · 吴磊 · 登高作业证 · 200 天' }])) + CH.mini.legend(names.map((n, i) => ({ n: n.replace('配电', ''), c: CPAL[i] }))) + '</div>' +
    '<div class="card"><div class="h"><b>所长问答</b><span>事实回答，不做评价</span><div class="r"><button class="s g" data-act="of-report">生成所级月报</button></div></div><div class="kbq">' + ['三个班本月培训完成情况', '哪个班证书到期的最多', '所里下个月人力缺口在哪', '本月三个班两票合格率', '哪条线路隐患最多'].map(q => '<b data-act="say" data-say="' + h(q) + '">' + h(q) + '</b>').join('') + '</div><div class="doc" id="ofrep" style="margin-top:8px"></div></div></div><div id="ofdrill"></div>'; },
  drill(n) { const d = TEAMS2[n]; const t = TEAMS.find(x => x.n === n); const host = $('#ofdrill'); if (!host) return; const avg = n === TEAMS[0].n ? MODS.map((m, i) => +(PEOPLE.reduce((s, p) => s + PEOPLEPG.lv(p)[i], 0) / PEOPLE.length).toFixed(1)) : n === TEAMS[1].n ? [3.2, 2.6, 2.9, 2.4, 3.0, 2.7, 3.1, 2.8] : [3.4, 2.2, 2.5, 2.1, 3.5, 2.3, 3.3, 2.6];
    host.innerHTML = '<div class="card"><div class="h"><b>' + h(n) + '</b><span>班长 ' + h(t.leader) + ' · ' + t.size + ' 人 · ' + Object.keys(d.posts).map(k => k + ' ' + d.posts[k]).join(' / ') + '</span><div class="r">' + (n === TEAMS[0].n ? '<button class="s" data-act="nav" data-to="people">进班组画像</button>' : '<button class="s g" data-act="of-auth" data-n="' + h(n) + '">申请查看明细</button>') + '</div></div><div class="grid3"><div>' + CH.mini.radar(MODS.map(m => m.n.replace('能力', '')), [{ n: '班组均值', vals: avg, c: CPAL[TEAMS.indexOf(t)] }, { n: '目标 L3', vals: [3, 3, 3, 3, 3, 3, 3, 3], c: '#7b849c', dash: true }]) + '</div><div>' + CH.mini.donut(Object.keys(d.posts).map((k, i) => ({ k, v: d.posts[k], c: CPAL[i] })), { sub: '人' }) + '</div><div>' + CH.mini.line([{ n: '任务', vals: d.jobsM, c: CPAL[0] }, { n: '两票', vals: d.ticketsM, c: CPAL[2] }], MONTHS6, { h: 128 }) + '</div></div></div>'; CH.mount(host); host.scrollIntoView({ block: 'nearest' });
    XW.answer(n + '：' + t.size + ' 人，年度学时 ' + d.hoursM[5] + '%，本月两票 ' + d.ticketsM[5] + ' 张全部合格，任务 ' + d.jobsM[5] + ' 项。图谱上最弱的是' + MODS[avg.indexOf(Math.min.apply(null, avg))].n + '（L' + Math.min.apply(null, avg) + '）。' + (n === TEAMS[0].n ? '明细在班组画像里。' : '明细要班长' + t.leader + '授权才能看。'), null, { confirm: false }); }
};
PAGES.office = { render() { return OFFICEPG.render(); }, after() { CH.mount($('#main')); if (OFFICEPG.team) OFFICEPG.drill(OFFICEPG.team); } };
PAGES.ask = {
  render() { const G = [{ t: '查数', qs: ['三个月内证书到期的有谁', '本月学时未完成的名单', '李文博这周工时怎么算的', '志远站 F14 缺陷现在什么状态', '本月两票合格率', '谁持有带电作业资格'] }, { t: '安排与决策参考', qs: ['加一个任务：塘尾线 #31 杆鸟巢拆除', '安排明天凤凰线换刀闸', '下周检修任务谁去合适', '排下周值班表', '明天凤凰线换刀闸是什么风险等级', '谁适合参加下季度的技能竞赛', '下周谁的活最多'] }, { t: '生成', qs: ['上传一张操作票', '写今天的班前会材料', '生成本月的月度总结', '写本周安全日讲稿', '从光差保护课件出五道题', '写下周计划', '生成所级月报'] }, { t: '人', qs: ['刘一鸣最近怎么样', '黄伟强最近怎么样', '给郭子扬打倒闸操作实操分', '按陈浩的短板组一套卷'] }, { t: '知识', qs: ['站内馈线保护定值是多少', '停电作业安措顺序', '遥控失败先查什么', '登杆前要检查什么', '考我一道安规题'] }];
    return cmdHTML([]) + pageHead('问小瓦特', '能查、能提醒、能生成、能办；答数字时她会配一张图；涉及人的结论由班组长确认') + '<div class="grid2">' + G.map(g => '<div class="card"><div class="h"><b>' + h(g.t) + '</b></div><div class="kbq">' + g.qs.map(q => '<b data-act="say" data-say="' + h(q) + '">' + h(q) + '</b>').join('') + '</div></div>').join('') + '</div>'; },
  after() { XW.at(300, () => { if (!$$('#chat .msg').length) XW.answer('想办什么点一条，或者直接打字。语音在输入框右边，说完我先复述一遍再办。', null, { confirm: false }); }); }
};
Object.assign(ACT, {
  'led-export'() { XW.fly('已导出 ' + LEDGERPG.tabs.find(t => t.k === (S.sub || 'hours')).n + '台账 · Excel'); XW.answer('导出了，带筛选条件，' + (LEDGERPG.who ? '只有' + LEDGERPG.who + '的行。' : '全部行。'), null, { confirm: false }); },
  team(el) { OFFICEPG.team = el.dataset.n; $$('.teams .tc').forEach(c => c.classList.toggle('on', c.dataset.n === el.dataset.n)); OFFICEPG.drill(el.dataset.n); },
  'of-month'(el) { OFFICEPG.month = +el.dataset.i; render(); XW.answer(MONTHS6[OFFICEPG.month] + '的三个班：学时 ' + Object.keys(TEAMS2).map(n => n.replace('配电', '') + ' ' + TEAMS2[n].hoursM[OFFICEPG.month] + '%').join('、') + '。', null, { confirm: false, speak: false }); },
  'of-cell'(el) { const n = Object.keys(TEAMS2).find(x => x.replace('配电', '') === el.dataset.who); const i = MONTHS6.indexOf(el.dataset.k); const d = TEAMS2[n]; XW.answer(n + ' ' + el.dataset.k + '：学时 ' + d.hoursM[i] + '%，两票 ' + d.ticketsM[i] + ' 张，任务 ' + d.jobsM[i] + ' 项。', null, { confirm: false, chart: CH.mini.line([{ n: '学时 %', vals: d.hoursM, c: CPAL[0] }], MONTHS6, { max: 100, h: 90 }) }); },
  'of-cap'(el) { const n = Object.keys(TEAMS2).find(x => x.replace('配电', '') === el.dataset.who); const i = +el.dataset.i; const v = TEAMS2[n].cap[i]; if (!v) { XW.answer(n + WEEKS8[i] + '人手够。', null, { confirm: false }); return; } const others = Object.keys(TEAMS2).filter(x => x !== n && TEAMS2[x].cap[i] === 0); XW.think(n + WEEKS8[i] + '缺 ' + v + ' 人……那周' + (others.length ? others.map(x => x.replace('配电', '')).join('、') + '不缺' : '三个班都紧') + '。' + (others.length ? '从' + others[0].replace('配电', '') + '借 ' + Math.min(v, 2) + ' 名高级作业员两周，两边都在约定内。' : '只能压缩非紧急任务。'), () => { XW.answer(n + WEEKS8[i] + '缺 ' + v + ' 人。' + (others.length ? '建议从' + others[0] + '借 ' + Math.min(v, 2) + ' 名高级作业员，' + WEEKS8[i] + '到' + (WEEKS8[i + 1] || WEEKS8[i]) + '。由所长定。' : '三个班那周都紧，建议把非紧急的检查任务往后挪。'), others.length ? '<div class="bt"><button data-act="of-borrow" data-from="' + others[0] + '" data-to="' + n + '" data-w="' + i + '">发起借调</button><button class="g">先不用</button></div>' : null, { confirm: false, chart: CH.mini.group([WEEKS8[i]], Object.keys(TEAMS2).map((x, xi) => ({ n: x.replace('配电', ''), vals: [TEAMS2[x].cap[i]], c: CPAL[xi] })), { max: 5, h: 90, unit: ' 人' }) }); }); },
  'of-borrow'(el) { XW.fly('借调申请已发 · ' + el.dataset.from + ' → ' + el.dataset.to + ' · ' + WEEKS8[+el.dataset.w]); XW.answer('借调申请发给两个班长了，' + el.dataset.from.replace('配电', '') + '班长确认后我把人加进' + el.dataset.to.replace('配电', '') + '的值班表。', null, { confirm: false }); },
  'of-auth'(el) { XW.fly('查看申请已发 · ' + el.dataset.n + ' 班长', 'w'); XW.answer('申请发给' + TEAMS.find(t => t.n === el.dataset.n).leader + '了，他同意后你能看到这个班的成员画像。', null, { confirm: false }); },
  'of-report'() { const host = $('#ofrep'); const names = Object.keys(TEAMS2); DOCGEN.stream(host, ['凤凰供电所 8 月班组工作汇总（初稿）', '一、任务与两票：三个班共完成作业 [取一下三班任务……] ' + names.reduce((s, n) => s + TEAMS2[n].jobsM[4], 0) + ' 项；工作票 ' + names.reduce((s, n) => s + TEAMS2[n].ticketsM[4], 0) + ' 张，全部合格。', '二、安全：隐患 ' + names.reduce((s, n) => s + TEAMS2[n].lines.reduce((a, l) => a + l[1], 0), 0) + ' 处，一班凤凰线 3 处最多，已列台风季专项；本年违章 3 起，均已处理。', '三、人员：年度学时一班 76%、二班 81%、抢修班 69%；证书 90 天内到期 6 人（一班 3、二班 1、抢修班 2），均已安排复审。', '四、人力：39 周一班缺 5 人，建议从二班借调 2 名高级作业员两周。', '五、下月重点：台风季拉线专项巡视、继保专才课程、证书复审。'], { chips: [{ k: 'short', n: '口气再简短些' }], done() { XW.answer('所级汇总写好了，三个班的数字都是台账汇的，不排名。', null, { speak: false, confirm: false }); } }); DOCS.host = host; DOCS.kind = 'ofreport'; }
});
