/* ===== 管理者 · 八页（9/21 客户口径：业务功能减、管理功能加）：考核指标（分管副总 / 主管 / 班长）/ 班组横向对比 / 团队画像总览（星级 · 荣誉 · 特色 · 班长队伍与梯队）/ 人员总览仪表盘（下钻人员清单 · 员工画像）/ 班组结构对比 / 团队风险画像 / 员工关怀（面谈提纲 · 重点关注 · 文化活动）/ 分析参谋（分析报告 · 近五年趋势）===== */
SUPER.OM_PEOPLE = TEAM3_PEOPLE.map(p => p.n);
SUPER.personOf = function (team, n) { if (team === TEAM.name) return P[n]; if (team === LAB.name) return LAB.people.find(p => p.n === n); return TEAM3_PEOPLE.find(p => p.n === n) || { n, post: '中级作业员', age: 34, cert: ['高压电工作业证', '岗位胜任能力证'] }; };
const MGR = {
  teamOrder: TEAMS.map(t => t.n),
  leaderOf(team) { return (TEAMS.find(t => t.n === team) || {}).leader || '赵立群'; },
};

/* ---------- 考核指标：分管副总 / 主管 / 班长三个维度（2026 年度业绩责任书）---------- */
const KPIPG = {
  tab() { return ['vp', 'mgr', 'lead'].includes(S.sub) ? S.sub : 'mgr'; },
  tgt(d, x) { return x == null ? '—' : d.fmt(x) + d.unit; },
  urgeKey(dk, k, team) { return dk + ':' + k + (team ? ':' + team : ''); },
  urged(dk, k, team) { return LS.get('goal_urge', {})[this.urgeKey(dk, k, team)]; },
  sBar(r) { return r.s == null ? '—' : r.risk ? '<b class="mono ' + (r.s < 0 ? 'b' : 'g') + '">' + (r.s < 0 ? r.s : '不扣分') + '</b>' : MG.bar(Math.min(100, r.s / 120 * 100), r.light) + '<span class="mono">' + r.s + '</span>'; },
  table(dk) { const D = KPI_LV.find(x => x.k === dk); const R = kpiRows(dk);
    if (dk !== 'lead') return '<div class="tbl"><table class="t goals"><tr><th></th><th>指标</th><th>权重</th><th>基础值</th><th>满分值</th><th>挑战值</th><th>当前值</th><th style="min-width:120px">预计得分</th><th>取数</th><th></th></tr>' +
      R.map(r => '<tr data-act="kpi-open" data-dim="' + dk + '" data-k="' + r.k + '" style="cursor:pointer" class="' + (r.light === 'bad' ? 'hl' : '') + '"><td>' + MG.light(r.light) + '</td><td><b>' + h(r.n) + (r.star ? ' <span class="kstar">*</span>' : '') + '</b></td><td class="mono">' + r.w + '%</td><td class="mono">' + this.tgt(r, r.base) + '</td><td class="mono">' + this.tgt(r, r.full) + '</td><td class="mono">' + this.tgt(r, r.chal) + '</td><td><b class="mono">' + h(r.vTxt) + '</b></td><td>' + this.sBar(r) + '</td><td class="note">' + h(r.src) + '</td><td>' + (this.urged(dk, r.k) ? '<span class="tag ok">已督办 ' + h(this.urged(dk, r.k)) + '</span>' : r.light === 'ok' ? '' : '<button class="s g" data-act="goal-urge" data-dim="' + dk + '" data-k="' + r.k + '">督办</button>') + '</td></tr>').join('') + '</table></div>';
    return '<div class="tbl"><table class="t goals"><tr><th></th><th>指标</th><th>权重</th><th>基础值</th><th>满分值</th>' + TEAMS.map(t => '<th>' + h(MGR.leaderOf(t.n)) + '<br><span class="note">' + h(t.n) + '</span></th>').join('') + '</tr>' +
      R.map(r => '<tr class="' + (r.light === 'bad' ? 'hl' : '') + '"><td>' + MG.light(r.light) + '</td><td><b data-act="kpi-open" data-dim="lead" data-k="' + r.k + '" style="cursor:pointer">' + h(r.n) + '</b>' + (r.risk ? '<br><span class="note">风险指标</span>' : '') + '</td><td class="mono">' + (r.risk ? '扣分' : r.w + '%') + '</td><td class="mono">' + this.tgt(r, r.base) + '</td><td class="mono">' + this.tgt(r, r.full) + '</td>' +
        TEAMS.map(t => { const c = r.teams[t.n]; return '<td data-act="kpi-open" data-dim="lead" data-k="' + r.k + '" data-team="' + h(t.n) + '" style="cursor:pointer">' + MG.light(c.light) + '<b class="mono">' + h(c.vTxt.replace(/^累计 [^·]+· 推算全年 /, '全年 ')) + '</b><br><span class="note">' + (c.risk ? (c.s < 0 ? '扣 ' + (-c.s) + ' 分' : '不扣分') : '得分 ' + c.s) + (this.urged('lead', r.k, t.n) ? ' · 已督办' : '') + '</span></td>'; }).join('') + '</tr>').join('') + '</table></div>'; },
  legend() { return '<div class="legend-note">颜色说明：绿灯 = 达到满分值（风险指标：不低于 50 分，不扣分）；黄灯 = 达到基础值、未到满分值（没有基础值的指标：得分在 108 分及以上）；红灯 = 未达基础值（风险指标：低于 50 分，按差值扣分），整行浅色底标出。带 * 的为年度重点考核指标。累计类指标（跳闸次数、平均停电时间）按时间进度 ' + YEAR_PCT + '% 推算全年后评判。预计得分按责任书评分标准计算，单项最高 120 分。</div>'; },
  rules(dk) { const D = KPI_LV.find(x => x.k === dk); const R = kpiRows(dk); return '<div class="tbl"><table class="t"><tr><th style="width:150px">指标</th><th>评分标准（责任书原文）</th></tr>' + R.map(r => '<tr><td><b>' + h(r.n) + (r.star ? ' *' : '') + '</b><br><span class="note">' + (r.risk ? '风险指标' : '权重 ' + r.w + '%') + '</span></td><td class="note">' + h(r.rule) + '</td></tr>').join('') + '</table></div><div class="note" style="margin-top:6px">来源：' + h(D.doc) + '（' + h(D.who) + '），考核指标占总权重的 ' + D.share + '%。</div>'; }
};
PAGES.goals = {
  render() { const dk = KPIPG.tab(); const D = KPI_LV.find(x => x.k === dk); const R = kpiRows(dk); const cells = dk === 'lead' ? R.reduce((a, r) => a.concat(Object.values(r.teams)), []) : R; const cnt = { ok: 0, w: 0, bad: 0 }; cells.forEach(c => cnt[c.light]++); const urged = Object.keys(LS.get('goal_urge', {})).length;
    return cmdHTML(['哪几项亮红灯', '快速复电成功率为什么扣分', '督办第三方客户满意度', '生成本月指标分析']) + pageHead('考核指标', '按 2026 年度业绩责任书分三个维度：分管副总 / 主管 / 班长 · 带 * 的为年度重点考核指标 · 时间进度 ' + YEAR_PCT + '%', '<button class="s g" data-act="nav" data-to="lperf">班长绩效</button><button class="s g" data-act="nav" data-to="compare">班组横向对比</button>') +
      tabsHTML(KPI_LV.map(x => ({ k: x.k, n: x.n + ' · ' + x.items.length + ' 项' })), dk) +
      '<div class="grid4" style="margin-top:10px"><div class="card kpi"><span>绿灯 · 达到满分值</span><b class="g">' + cnt.ok + '</b><em>' + (dk === 'lead' ? '三位班长 × ' + R.length + ' 项 = ' + cells.length + ' 格' : h(R.filter(r => r.light === 'ok').map(r => r.n).join('、') || '无')) + '</em></div><div class="card kpi"><span>黄灯 · 达到基础值</span><b class="w">' + cnt.w + '</b><em>' + (dk === 'lead' ? '' : h(R.filter(r => r.light === 'w').map(r => r.n).join('、') || '无')) + '</em></div><div class="card kpi"><span>红灯 · 未达基础值</span><b class="bad">' + cnt.bad + '</b><em>' + h(R.filter(r => r.light === 'bad').map(r => r.n).join('、') || '无') + '</em></div><div class="card kpi"><span>已督办</span><b>' + urged + '</b><em>督办发到责任班长的通知里</em></div></div>' +
      '<div class="card"><div class="h"><b>' + h(D.n) + '考核指标 · ' + h(D.who) + '</b><span>' + h(D.doc) + ' · 考核指标占总权重 ' + D.share + '% · 点一行看评分标准' + (dk === 'lead' ? '，点格看该班长' : '') + '</span></div>' + KPIPG.table(dk) + KPIPG.legend() + '</div>' +
      '<div class="grid2" style="grid-template-columns:1fr 1.3fr"><div class="card"><div class="h"><b>预计得分</b><span>虚线 = 100 分</span></div>' + (dk === 'lead' ? CH.mini.group(R.filter(r => !r.risk).map(r => r.n.slice(0, 6)), TEAMS.map((t, i) => ({ n: MGR.leaderOf(t.n), vals: R.filter(r => !r.risk).map(r => r.teams[t.n].s), c: CPAL[i] })), { h: 140, max: 120 }) + CH.mini.legend(TEAMS.map((t, i) => ({ n: MGR.leaderOf(t.n) + ' · ' + t.n, c: CPAL[i] }))) : CH.mini.bars(R.filter(r => !r.risk).map(r => ({ n: r.n.slice(0, 8), v: r.s, c: r.light === 'ok' ? SEM.ok : r.light === 'w' ? '#d97706' : '#e5484d', act: 'kpi-open', k: r.k, tip: r.n + ' · ' + r.vTxt })), { x0: 96, limit: 100, max: 120, unit: ' 分' })) + '<div class="legend-note">' + (dk === 'lead' ? '颜色说明：三种颜色分别代表三位班长（' + TEAMS.map((t, i) => MGR.leaderOf(t.n)).join(' / ') + '），柱高为该项预计得分。' : '颜色说明：绿 = 达到满分值；黄 = 达到基础值；红 = 未达基础值。条长为预计得分，满分 120。') + '</div></div>' +
      '<div class="card"><div class="h"><b>评分标准</b><span>取责任书原文，规则公开到人</span></div>' + KPIPG.rules(dk) + '</div></div>'; },
  after() { CH.mount($('#main')); if (!S.briefed) { S.briefed = true; const G = goalsAll(); const bad = G.filter(g => g.light === 'bad'); XW.at(400, () => XW.answer('考核指标按责任书分三个维度：分管副总 4 项、主管 4 项、班长 4 项。现在亮红灯的有 ' + bad.length + ' 项：' + (bad.map(g => g.n).join('、') || '无') + '。快速复电成功率光明 ' + WK29.val('fastok') + '%，离满分值 88% 还差 ' + +(88 - WK29.val('fastok')).toFixed(1) + ' 个百分点，预计得分 ' + KPI_DEF.fast.score(WK29.val('fastok')).toFixed(0) + '。点任一行看评分标准，督办直接发到班长。', null, { confirm: false })); } }
};
Object.assign(ACT, {
  'kpi-open'(el) { const dk = el.dataset.dim || KPIPG.tab(); const k = el.dataset.k; const team = el.dataset.team; const R = kpiRows(dk); const r = R.find(x => x.k === k); if (!r) return; const D = KPI_LV.find(x => x.k === dk);
    const rows = dk === 'lead' ? TEAMS.map(t => r.teams[t.n]) : [r];
    modal('<div class="t">' + MG.light(r.light, r.lightN + '灯') + '　' + h(D.n) + ' · ' + h(r.n) + (r.star ? ' *' : '') + '</div><div class="note" style="margin-bottom:6px">' + h(D.doc) + ' · ' + (r.risk ? '风险指标' : '权重 ' + r.w + '%') + ' · 基础值 ' + KPIPG.tgt(r, r.base) + ' · 满分值 ' + KPIPG.tgt(r, r.full) + (r.chal != null ? ' · 挑战值 ' + KPIPG.tgt(r, r.chal) : '') + '</div>' +
      '<div class="tbl"><table class="t"><tr><th>' + (dk === 'lead' ? '班长 · 班组' : '口径') + '</th><th>当前值</th><th>预计得分</th><th>取数</th><th></th></tr>' + rows.map(c => '<tr class="' + (team && c.team === team ? 'hl' : '') + '"><td><b>' + h(c.team ? MGR.leaderOf(c.team) + ' · ' + c.team : '光明供电局') + '</b></td><td>' + MG.light(c.light) + '<span class="mono">' + h(c.vTxt) + '</span></td><td class="mono">' + (c.risk ? (c.s < 0 ? '扣 ' + (-c.s) : '不扣分') : c.s) + '</td><td class="note">' + h(c.src) + '</td><td>' + (c.light === 'ok' ? '' : KPIPG.urged(dk, k, c.team) ? '<span class="tag ok">已督办</span>' : '<button class="s g" data-act="goal-urge" data-dim="' + dk + '" data-k="' + k + '"' + (c.team ? ' data-team="' + h(c.team) + '"' : '') + '>督办' + (c.team ? h(MGR.leaderOf(c.team)) : '三位班长') + '</button>') + '</td></tr>').join('') + '</table></div>' +
      '<div class="tbl" style="margin-top:8px"><table class="t"><tr><th style="width:86px">评分标准</th><td class="note">' + h(r.rule) + '</td></tr></table></div>' + KPIPG.legend());
    const c = team ? r.teams[team] : r; XW.answer((team ? MGR.leaderOf(team) + '（' + team + '）' : '') + r.n + '：当前 ' + c.vTxt + '，' + (c.risk ? (c.s < 0 ? '低于 50 分，扣 ' + (-c.s) + ' 分' : '不低于 50 分，不扣分') : '按责任书预计得 ' + c.s + ' 分') + '，' + c.lightN + '灯。' + (c.light === 'ok' ? '' : '满分值是 ' + KPIPG.tgt(r, r.full) + '。'), null, { confirm: false, speak: false }); },
  'goal-open'(el) { ACT['kpi-open'](el); },
  'goal-urge'(el) { const dk = el.dataset.dim || KPIPG.tab(); const k = el.dataset.k; const R = kpiRows(dk); const r = R.find(x => x.k === k); if (!r) return; const teams = el.dataset.team ? [el.dataset.team] : TEAMS.map(t => t.n); const u = LS.get('goal_urge', {});
    teams.forEach(t => { const c = dk === 'lead' ? r.teams[t] : r; DB.notify(MGR.leaderOf(t), '督办 · ' + r.n + '：当前 ' + c.vTxt + '，满分值 ' + KPIPG.tgt(r, r.full) + '，预计得分 ' + c.s + '。请本周报一次措施和进度', '已发', true); if (dk === 'lead') u[KPIPG.urgeKey(dk, k, t)] = DB.now(); });
    if (dk !== 'lead' || !el.dataset.team) u[KPIPG.urgeKey(dk, k)] = DB.now(); LS.set('goal_urge', u); DB.log('督办', r.n + ' → ' + teams.map(t => MGR.leaderOf(t)).join('、')); $('#modal').hidden = true; if (S.page === 'goals') render(); XW.fly('督办已发 · ' + teams.map(t => MGR.leaderOf(t)).join('、')); XW.answer('督办发给' + teams.map(t => MGR.leaderOf(t)).join('、') + '了，班长的工作台会看到，评分标准一并带过去。', null, { confirm: false }); }
});

/* ---------- 同类班组横向对比看板 ---------- */
PAGES.compare = {
  render() { const R = compareRows(); const A = compareAdvice(); const names = MGR.teamOrder; const sent = LS.get('cmp_sent', {});
    return cmdHTML(['哪个班组最忙', '要不要跨班组调人', '人均实操量三个班组差多少']) + pageHead('班组横向对比', '配网资产部三个班组 · 本月任务 / 外勤工时（班组约定每人每周 ≤ 24 小时）/ 两票 / 缺陷 / 实操量 / 证书 / 在岗 / 技能结构 · 用于判断是否跨班组调配资源', '<button class="s g" data-act="nav" data-to="ledger" data-sub="transfer">调配台账</button>') +
      '<div class="card"><div class="h"><b>对比看板</b><span>绿 = 三班组最好 · 红 = 最需关注 · 点格看取数</span></div><div class="tbl"><table class="t cmp"><tr><th>维度</th>' + names.map(n => '<th>' + h(n) + '<br><span class="note">' + h(MGR.leaderOf(n)) + ' · ' + (TEAMS.find(t => t.n === n) || {}).size + ' 人</span></th>').join('') + '<th>说明</th></tr>' + R.map(r => '<tr><td><b>' + h(r.n) + '</b>' + (r.unit ? '<span class="note">（' + h(r.unit) + '）</span>' : '') + '</td>' + names.map(n => { const v = r.vals ? r.vals[n] : r.num[n]; const cls = r.best.includes(n) ? 'ok' : r.worst.includes(n) ? 'bad' : ''; return '<td data-act="cmp-cell" data-k="' + r.k + '" data-n="' + h(n) + '" style="cursor:pointer"><span class="cmpv ' + cls + '">' + h(v == null ? '—' : v) + '</span></td>'; }).join('') + '<td class="note">' + h(r.note || '') + '</td></tr>').join('') + '</table></div></div>' +
      '<div class="grid2" style="grid-template-columns:1fr 1.2fr"><div class="card"><div class="h"><b>人均外勤工时 · 本周</b><span>虚线 = 约定上限的 75%</span></div>' + CH.mini.bars(names.map((n, i) => ({ n, v: R.find(r => r.k === 'load').num[n], c: CPAL[i], unit: 'h', act: 'cmp-cell', k: 'load' })), { x0: 82, limit: WEEK_LIMIT * 0.75, max: WEEK_LIMIT, unit: 'h' }) + '<div class="h" style="margin-top:8px"><b>人均核心技能实操量</b></div>' + CH.mini.bars(names.map((n, i) => ({ n, v: R.find(r => r.k === 'cap').num[n], c: CPAL[i], act: 'cmp-cell', k: 'cap' })), { x0: 82, unit: ' 次' }) + '</div>' +
      '<div class="card"><div class="h"><b>分析与参谋</b><span>是否需要跨班组调配</span></div><div class="advbox"><p><b>' + h(A.busy) + '</b>本周人均外勤 ' + R.find(r => r.k === 'load').num[A.busy] + ' 小时，' + (R.find(r => r.k === 'over').num[A.busy] ? '有 ' + R.find(r => r.k === 'over').num[A.busy] + ' 人超 24 小时，' : '') + '原因是' + h(A.need) + '；<b>' + h(A.idle) + '</b>人均 ' + R.find(r => r.k === 'load').num[A.idle] + ' 小时，相差 ' + A.gap + ' 小时。</p><p>建议：从' + h(A.idle) + '借 <b>' + h(A.who) + '</b> 到' + h(A.busy) + ' 3 天（下周一起），借出后' + h(A.idle) + '人均工时仍在约定内；影响测算与替代人选在发起前会算给你看。</p><p class="note">两位班长各收一条待确认，确认或退回后调配台账同步。</p></div><div class="bt">' + (sent[A.who] ? '<span class="tag ok">已发起 ' + h(sent[A.who]) + '</span>' : '<button data-act="cmp-transfer" data-who="' + h(A.who) + '" data-from="' + h(A.idle) + '" data-to="' + h(A.busy) + '">发起跨班组调配</button>') + '<button class="g" data-act="nav" data-to="structure">看结构对比</button></div></div></div>'; },
  after() { CH.mount($('#main')); }
};
Object.assign(ACT, {
  'cmp-cell'(el) { const r = compareRows().find(x => x.k === el.dataset.k); const n = el.dataset.n; if (!r) return; const src = { jobs: '任务台账 · 本月', load: '工时台账 · 本周', over: '工时台账 · 约定 24 小时', tk: '两票台账 · 本月', df: '缺陷台账', cap: '作业授权台账', cert: '证书台账 · 90 天内', on: '人员名册', high: '技能等级认定台账' }[r.k]; XW.answer((n || '三班组') + '的' + r.n + (n ? '是 ' + (r.vals ? r.vals[n] : r.num[n]) + (r.unit || '') : '') + '，取自' + src + '。三班组里最好的是' + r.best.join('、') + (r.worst.length ? '，最需关注' + r.worst.join('、') : '') + '。', null, { confirm: false }); },
  'cmp-transfer'(el) { const who = el.dataset.who, from = el.dataset.from, to = el.dataset.to; const A = compareAdvice(); SUPER.simState = { from, who, to, days: 3, start: '2026-08-10', why: A.need }; const sent = LS.get('cmp_sent', {}); sent[who] = DB.now(); LS.set('cmp_sent', sent); ensure('risk', () => { const host = $('#riskbody'); if (host) { host.innerHTML = SUPER.simHTML(); CH.mount(host); } XW.at(300, () => ACT['sim-say']()); }, 'sim'); }
});

/* ---------- 团队画像总览 + 班长队伍管理 ---------- */
PAGES.portrait = {
  render() { const st = leaderStat(); const B = buildScore(); const pre = { '配电自动化班': B.pct, '试验班': 93.2, '配电运维一班': 76.4 };
    return cmdHTML(['三个班组各是什么类型', '班长后备够不够', '给陈志远排后备培养']) + pageHead('团队画像总览', '星级班组 · 集体荣誉 · 班组特色标签 · 班长队伍基本情况与梯队建设', '<button class="s g" data-act="nav" data-to="staff">人员总览</button><button class="s g" data-act="nav" data-to="structure">结构对比</button>') +
      '<div class="grid3">' + MGR.teamOrder.map(n => { const T = TEAM_TAGS[n]; const s = teamStat(n); return '<div class="card tcard"><div class="h"><b>' + h(n) + '</b><span>' + h(MGR.leaderOf(n)) + ' · ' + s.n + ' 人</span></div><div class="hstar">' + MG.starTag(T.star) + '<span class="note">' + h(T.starD) + ' · 初步评分 <b>' + pre[n] + '</b></span></div><div class="honors small">' + T.honors.map(x => '<div class="hitem"><b>' + h(x[0]) + '</b><span class="note">' + h(x[1]) + ' · ' + h(x[2]) + '</span></div>').join('') + '</div><div class="kindrow">' + MG.kindTag(T.kind) + '<span class="note">' + h(T.why) + '</span></div><div class="trow"><span>技师及以上 <b>' + s.senior + '</b></span><span>高级工及以上 <b>' + s.high + '</b></span><span>星级工程师 <b>' + s.eng + '</b></span><span>专家 <b>' + s.expert + '</b></span><span>平均 <b>' + s.avgAge + '</b> 岁</span></div><div class="bt"><button class="s g" data-act="pt-team" data-n="' + h(n) + '">看班组画像</button><button class="s g" data-act="st-team" data-n="' + h(n) + '">人员清单</button></div></div>'; }).join('') + '</div>' +
      '<div class="grid2" style="grid-template-columns:1.6fr 1fr"><div class="card"><div class="h"><b>班长队伍管理</b><span>基本情况 · 后备与梯队</span></div><div class="tbl"><table class="t"><tr><th>班长</th><th>班组</th><th>年龄 / 工龄</th><th>任班长</th><th>技能等级</th><th>星级工程师</th><th>党员</th><th>副班长</th><th>后备梯队</th><th>距退休</th><th></th></tr>' + LEADERS.map((l, i) => '<tr><td><b data-act="st-person" data-who="' + l.n + '">' + h(l.n) + '</b></td><td>' + h(l.team) + '</td><td class="mono">' + l.age + ' / ' + l.yrs + '</td><td class="mono">' + l.asLeader + ' 年</td><td>' + h(l.lv) + '</td><td><span class="tag v">' + h(l.star) + '</span></td><td>' + (l.party ? '是' : '否') + '</td><td>' + h(l.deputy) + '</td><td>' + l.backup.map(b => '<span class="tag ' + (b[1] === '可接任' ? 'ok' : 'w') + '" title="' + h(b[2]) + '">' + h(b[0]) + ' · ' + h(b[1]) + '</span>').join('') + '</td><td class="mono">' + l.retireIn + ' 年</td><td><button class="s g" data-act="pt-backup" data-i="' + i + '">后备培养</button></td></tr>').join('') + '</table></div></div>' +
      '<div><div class="card"><div class="h"><b>班长队伍基本情况</b></div><div class="mets" style="grid-template-columns:repeat(3,1fr)"><div><b>' + st.avgAge + '</b><span>平均年龄</span></div><div><b>' + st.avgLead + '</b><span>平均任班长年限</span></div><div><b>' + st.senior + '/3</b><span>技师及以上</span></div><div><b>' + st.party + '/3</b><span>党员</span></div><div><b class="g">' + st.ready + '</b><span>可接任后备</span></div><div><b class="w">' + st.training + '</b><span>培养中后备</span></div></div><div class="note" style="margin-top:6px">10 年内退休 ' + st.retire10 + ' 人；配电运维一班后备只有 1 人且未取技师，是梯队最薄处。</div></div><div class="card" style="margin-top:10px"><div class="h"><b>梯队建设</b></div>' + CH.mini.funnel([{ k: '在任班长', v: 3 }, { k: '可接任', v: st.ready }, { k: '培养中', v: st.training }, { k: '骨干池（星级工程师）', v: Object.keys(STAR_ENG).length - 3 }]) + '</div></div></div>'; },
  after() { CH.mount($('#main')); }
};
Object.assign(ACT, {
  'pt-team'(el) { const n = el.dataset.n; if (n === TEAM.name) nav('team'); else XW.answer(n + '的班组画像按' + n + '名册与班务记录聚合：' + TEAM_TAGS[n].star + '、' + TEAM_TAGS[n].kind + '（' + TEAM_TAGS[n].why + '）。逐维度的初步评分需要该班组接入台账后才能像配电自动化班一样逐项对照。', null, { confirm: false }); },
  'pt-backup'(el) { const l = LEADERS[+el.dataset.i]; const b = l.backup.find(x => x[1] === '培养中') || l.backup[0]; const t = b[1] === '培养中' ? (/未取技师/.test(b[2]) ? '技师鉴定申报 + 主持 2 项作业组织' : '主持一次月度班务会 + 独立编制周计划') : '作为副班长代行班长职责一个月'; DB.notify(l.n, '班长后备培养 · ' + b[0] + '：' + t + '，请排进班组培养计划', '已发'); const s = LS.get('sup_talent', {}); s[b[0]] = { t, d: DB.now() }; LS.set('sup_talent', s); DB.log('梯队', l.team + ' 后备 ' + b[0] + '：' + t); XW.answer('给' + l.n + '发了：' + b[0] + '的后备培养任务"' + t + '"，由班长排进班组培养计划。', null, { confirm: false }); }
});


/* ---------- 班长绩效考评（管理者）：五维权重 · 逐条扣分与依据 · 确认 · 评价意见 · 下发与面谈 ---------- */
const LPERFPG = {
  all() { return lperfAll(); },
  okMap() { return LS.get('lperf_ok', {}); },
  fixMap() { return LS.get('lperf_fix', {}); },
  sentMap() { return LS.get('lperf_sent', {}); },
  dimTable() { const A = this.all();
    return '<div class="tbl"><table class="t cmp lpt"><tr><th>考核内容</th><th>权重</th>' + A.map(x => '<th>' + h(x.L.n) + '<br><span class="note">' + h(x.team) + '</span></th>').join('') + '<th>取数来源</th></tr>' +
      LPERF_DIMS.map((d, i) => '<tr><td><b>' + h(d.n) + '</b></td><td class="mono">' + d.pts + '%</td>' + A.map(x => { const dd = x.dims[i]; return '<td data-act="lp-dim" data-who="' + h(x.L.n) + '" data-k="' + d.k + '" style="cursor:pointer">' + MG.bar(dd.pct, dd.cls) + '<span class="mono">' + dd.sc + '</span><span class="note"> / ' + d.pts + '</span></td>'; }).join('') + '<td class="note">' + h(d.src) + '</td></tr>').join('') +
      '<tr><td><b>风险指标</b><br><span class="note">安全生产过程管理</span></td><td class="mono">扣分</td>' + A.map(x => '<td data-act="lp-dim" data-who="' + h(x.L.n) + '" data-k="kpi" style="cursor:pointer">' + MG.light(x.risk ? 'bad' : 'ok') + '<span class="mono">' + x.proc.fmt(x.proc.v) + ' 分</span><span class="note">' + (x.risk ? ' · 扣 ' + x.risk : ' · 不扣分') + '</span></td>').join('') + '<td class="note">安全生产过程管理考核（不低于 50 分不扣分）</td></tr>' +
      '<tr><td><b>加扣分项</b></td><td class="mono">±2</td>' + A.map(x => '<td>' + (x.adj ? '<b class="mono ' + (x.adj > 0 ? 'g' : 'b') + '">' + (x.adj > 0 ? '+' : '') + x.adj + '</b><br><span class="note">' + h(x.adjRows.map(r => r[0]).join('；')) + '</span>' : '<span class="note">无</span>') + '</td>').join('') + '<td class="note">个人最多加分不超过 2 分</td></tr>' +
      '<tr><td><b>红线事项</b></td><td class="mono">—</td>' + A.map(x => '<td>' + (x.red ? '<span class="tag bad">触发 · ' + h(x.red) + '</span>' : '<span class="tag ok">未触发</span>') + '</td>').join('') + '<td class="note">安全生产、合规经营等，与公司责任追究管理规定、处分清单衔接</td></tr>' +
      '<tr><td><b>综合得分</b></td><td class="mono">100</td>' + A.map(x => '<td><b class="mono ' + (x.gradeCls === 'ok' ? 'g' : x.gradeCls === 'bad' ? 'b' : '') + '" style="font-size:15px">' + x.total + '</b>　<span class="tag ' + x.gradeCls + '">' + h(x.grade) + '</span></td>').join('') + '<td class="note">三部分加总 − 风险扣分 ± 加扣分 · 由部门确认后使用</td></tr></table></div>' +
      '<div class="legend-note">颜色说明：条形与数字按得分率着色，绿 = 得分率 ≥ 90%；黄 = 75%–89%；红 = 低于 75%。风险指标绿灯 = 不低于 50 分不扣分，红灯 = 低于 50 分按差值扣分。分档：优秀 ≥ 90、良好 ≥ 80、合格 ≥ 70、需改进 < 70。</div>'; },
  kpiTable() { const A = this.all(); return '<div class="tbl"><table class="t lpt"><tr><th>指标</th><th>权重</th><th>基础值</th><th>满分值</th>' + A.map(x => '<th>' + h(x.L.n) + '<br><span class="note">' + h(x.team) + '</span></th>').join('') + '</tr>' + LPERF_KPI.map(([k, w], i) => { const d = KPI_DEF[k]; return '<tr><td><b>' + h(d.n) + '</b></td><td class="mono">' + w + '%</td><td class="mono">' + KPIPG.tgt(d, d.base) + '</td><td class="mono">' + KPIPG.tgt(d, d.full) + '</td>' + A.map(x => { const r = x.kpis[i]; return '<td data-act="lp-dim" data-who="' + h(x.L.n) + '" data-k="kpi" style="cursor:pointer">' + MG.light(r.light) + '<span class="mono">' + h(r.vTxt.replace(/^累计 [^·]+· 推算全年 /, '全年 ')) + '</span><br><span class="note">' + r.s + ' 分 · 折算 ' + r.pts + '</span></td>'; }).join('') + '</tr>'; }).join('') + '<tr><td><b>安全生产过程管理</b><br><span class="note">风险指标</span></td><td class="mono">扣分</td><td class="mono">—</td><td class="mono">50 分</td>' + A.map(x => '<td>' + MG.light(x.risk ? 'bad' : 'ok') + '<span class="mono">' + x.proc.fmt(x.proc.v) + ' 分</span><br><span class="note">' + (x.risk ? '扣 ' + x.risk + ' 分' : '不扣分') + '</span></td>').join('') + '</tr></table></div><div class="legend-note">颜色说明：绿灯 = 达到满分值；黄灯 = 达到基础值、未到满分值（快速复电成功率无基础值，得分 ≥ 108 为黄）；红灯 = 未达基础值。累计类指标按时间进度 ' + YEAR_PCT + '% 推算全年。</div>'; },
  sumTable() { const A = this.all(); const ok = this.okMap(); const sent = this.sentMap();
    return '<div class="tbl"><table class="t cand"><tr><th>班长</th><th>综合 / 分档</th><th>环比</th><th>强项</th><th>短板</th><th>绩效结果应用</th><th>状态</th><th></th></tr>' +
      A.map(x => '<tr class="' + (x.gradeCls === 'bad' ? 'hl' : '') + '"><td><b data-act="lp-who" data-who="' + h(x.L.n) + '" style="cursor:pointer">' + h(x.L.n) + '</b><br><span class="note">' + h(x.team) + ' · 任班长 ' + x.L.asLeader + ' 年</span></td>' +
        '<td><b class="mono" style="font-size:15px">' + x.total + '</b>　<span class="tag ' + x.gradeCls + '">' + h(x.grade) + '</span></td>' +
        '<td class="mono ' + (x.delta >= 0 ? 'g' : 'b') + '">' + (x.delta > 0 ? '+' : '') + x.delta + '</td>' +
        '<td>' + x.strong.map(d => '<span class="tag ok">' + h(d.n) + ' ' + d.sc + '</span>').join('') + '</td>' +
        '<td>' + x.weak.map(d => '<span class="tag ' + (d.cls === 'bad' ? 'bad' : d.cls === 'w' ? 'w' : '') + '" data-act="lp-dim" data-who="' + h(x.L.n) + '" data-k="' + d.k + '" style="cursor:pointer">' + h(d.n) + ' ' + d.sc + '</span>').join('') + '</td>' +
        '<td class="note" style="max-width:250px">' + h(x.apply) + '</td>' +
        '<td>' + (sent[x.L.n] ? '<span class="tag ok">已下发 ' + h(sent[x.L.n]) + '</span>' : ok[x.L.n] ? '<span class="tag">已确认 ' + h(ok[x.L.n]) + '</span>' : '<span class="tag w">待确认</span>') + '</td>' +
        '<td><div class="bt">' + (ok[x.L.n] ? '' : '<button class="s" data-act="lp-ok" data-who="' + h(x.L.n) + '">确认考评结果</button>') + '<button class="s g" data-act="lp-doc" data-who="' + h(x.L.n) + '">生成评价意见</button>' + (ok[x.L.n] && !sent[x.L.n] ? '<button class="s g" data-act="lp-send" data-who="' + h(x.L.n) + '">下发到本人</button>' : '') + '<button class="s g" data-act="lp-talk" data-who="' + h(x.L.n) + '">绩效面谈提纲</button></div></td></tr>').join('') + '</table></div>'; },
  fixHTML() { const A = this.all(); const fx = this.fixMap(); const rows = [];
    A.forEach(x => x.weak.filter(d => d.cls !== 'ok').forEach(d => rows.push({ who: x.L.n, team: x.team, d, key: x.L.n + '|' + d.k })));
    if (!rows.length) return '<div class="empty">三位班长三部分得分率都在 90% 以上，本季度无需列改进要求</div>';
    return rows.map(r => '<div class="fixrow"><div>' + MG.light(r.d.cls) + '<b>' + h(r.who) + ' · ' + h(r.d.n) + '</b><span class="note"> 得分 ' + r.d.sc + '/' + r.d.pts + '（' + r.d.pct + '%）</span><p>' + h(r.d.items.filter(i => i[1] >= 0.3).map(i => i[0]).join('；') || '按责任书规则折算') + '</p></div><div class="bt">' + (fx[r.key] ? '<span class="tag ok">已列入 ' + h(fx[r.key]) + '</span>' : '<button class="s" data-act="lp-fix" data-who="' + h(r.who) + '" data-k="' + r.d.k + '">列入下季度改进要求</button>') + '</div></div>').join(''); }
};
PAGES.lperf = {
  render() { const A = LPERFPG.all(); const ok = LPERFPG.okMap();
    return cmdHTML(['三位班长这季度谁的短板最大', '陈志远为什么考核指标扣分', '生成陈志远的绩效评价意见', '把改进要求全部列入下季度']) +
      pageHead('班长绩效', LPERF_Q.no + '（' + LPERF_Q.state + '）· 员工年度业绩责任书（班长）：考核指标 50% / 重点任务 10% / 综合评价 40% · 加扣分 · 红线 · 由部门确认后使用', '<button class="s g" data-act="nav" data-to="goals" data-sub="lead">考核指标</button><button class="s g" data-act="nav" data-to="portrait">班长队伍</button>') +
      '<div class="grid3">' + A.map(x => '<div class="card kpi" data-act="lp-who" data-who="' + h(x.L.n) + '" style="cursor:pointer"><span>' + h(x.L.n) + ' · ' + h(x.team) + '</span><b class="' + (x.gradeCls === 'ok' ? 'g' : x.gradeCls === 'bad' ? 'bad' : 'w') + '">' + x.total + '<span style="font-size:12px;font-weight:500"> ' + h(x.grade) + '</span></b><em>环比' + (x.delta > 0 ? '升 ' + x.delta : x.delta < 0 ? '降 ' + (-x.delta) : '持平') + ' · 得分率最低：' + h(x.lowSubs.slice(0, 2).map(s => s.n + ' ' + Math.round(s.p) + '%').join('、')) + (x.risk ? ' · 风险扣 ' + x.risk : '') + (ok[x.L.n] ? ' · 已确认' : ' · 待确认') + '</em></div>').join('') + '</div>' +
      '<div class="card"><div class="h"><b>考核内容与权重 · 逐项得分</b><span>结构照员工年度业绩责任书（班长） · 点格看逐项得分与依据</span></div>' + LPERFPG.dimTable() + '</div>' +
      '<div class="card"><div class="h"><b>考核指标 · 五项 + 风险指标</b><span>单项得分按责任书评分标准，最高 120 分；折算 = 单项得分 ÷ 1.2 × 权重</span><div class="r"><button class="s g" data-act="nav" data-to="goals" data-sub="lead">看考核指标页</button></div></div>' + LPERFPG.kpiTable() + '</div>' +
      '<div class="grid2"><div class="card"><div class="h"><b>近四季度综合得分</b><span>最后一组为本季度在评</span></div>' + CH.mini.group(LPERF_Q.qs, A.map((x, i) => ({ n: x.L.n, vals: x.hist, c: CPAL[i] })), { h: 150, max: 100 }) + CH.mini.legend(A.map((x, i) => ({ n: x.L.n, c: CPAL[i] }))) + '<div class="legend-note">颜色说明：三种颜色分别代表三位班长；分档线：优秀 ≥ 90 · 良好 ≥ 80 · 合格 ≥ 70 · 需改进 < 70。本季度在评，得分随台账变化。</div></div>' +
      '<div class="card"><div class="h"><b>三部分得分率</b><span>满分 100%</span></div>' + CH.mini.group(LPERF_DIMS.map(d => d.n), A.map((x, i) => ({ n: x.L.n, vals: x.dims.map(d => d.pct), c: CPAL[i] })), { h: 150, max: 100 }) + CH.mini.legend(A.map((x, i) => ({ n: x.L.n, c: CPAL[i] }))) + '<div class="legend-note">颜色说明：三种颜色分别代表三位班长，柱高为该部分得分率。</div></div></div>' +
      '<div class="card"><div class="h"><b>综合得分 · 分档 · 绩效结果应用</b><span>分档不排名次 · 结果应用按局绩效管理办法 · 由部门确认后使用</span><div class="r"><button class="s g" data-act="lp-okall">全部确认</button><button class="s" data-act="lp-sheet">生成班长绩效考评表</button></div></div>' + LPERFPG.sumTable() + '</div>' +
      '<div class="card"><div class="h"><b>下季度改进要求</b><span>取每位班长得分率最低的两部分 · 列入后发到本人并同步到班组计划</span><div class="r"><button class="s" data-act="lp-fixall">全部列入</button></div></div><div id="lpfix">' + LPERFPG.fixHTML() + '</div></div>' +
      '<div class="card"><div class="h"><b>计分规则与取数口径</b><span>规则公开到班长，可逐条核对</span></div><div class="tbl"><table class="t"><tr><th style="width:96px">考核内容</th><th style="width:52px">权重</th><th>计分规则</th><th style="width:230px">取数来源</th></tr>' + LPERF_DIMS.map(d => '<tr><td><b>' + h(d.n) + '</b></td><td class="mono">' + d.pts + '%</td><td>' + h(d.rule) + '</td><td class="note">' + h(d.src) + '</td></tr>').join('') +
        '<tr><td><b>加扣分项</b></td><td class="mono">±2</td><td>应用所在部门经营业绩考核中对应本人负责领域的加分；引领性工作取得示范成效、参与巡视巡察表现优秀可加分，个人最多加分不超过 2 分；应用所在部门考核处分结果，对负有责任的人员扣分</td><td class="note">部门经营业绩考核 · 本部门考核</td></tr>' +
        '<tr><td><b>红线事项</b></td><td class="mono">—</td><td>安全生产、合规经营等，与公司责任追究管理规定、公司处分清单衔接，按照责任界定对负有责任的人员进行责任追究</td><td class="note">公司责任追究管理规定、公司处分清单</td></tr></table></div><div class="note" style="margin-top:6px">年度经营业绩考核得分 = ∑考核指标得分 × 权重 + ∑重点任务得分 × 权重 + ∑综合评价 × 权重 − 风险指标扣分 + 加扣分项得分，按百分制折算（单项上限 120 分折为 100 分）。配电自动化班的快速复电、违章、派工、待审票、授权新增取本机台账实时值，班长在工作台处理后本页刷新即变；另两个班组的输入项取部门季度台账，右下角的状态清单里可核对每项的来源。</div></div>' +
      '<div class="card doc" id="lpdoc" hidden><div class="empty">点某位班长的"生成评价意见"，意见逐段写在这里</div></div>'; },
  after() { CH.mount($('#main')); if (!S.briefed) { S.briefed = true; const A = LPERFPG.all(); const low = A.slice().sort((a, b) => a.total - b.total)[0]; XW.at(400, () => XW.answer('三位班长本季度的初步得分：' + A.map(x => x.L.n + ' ' + x.total + '（' + x.grade + '）').join('、') + '。总分最低的是' + low.L.n + '，得分率最低的两项是' + low.lowSubs.slice(0, 2).map(s => s.n + ' ' + Math.round(s.p) + '%').join('、') + (low.risk ? '，安全生产过程管理低于 50 分，扣 ' + low.risk + ' 分' : '') + '。结构照班长责任书：考核指标 50%、重点任务 10%、综合评价 40%，每一格都能点开看依据，确认后可以下发到本人并约面谈。', null, { confirm: false })); } }
};
Object.assign(ACT, {
  'lp-dim'(el) { const x = lperfOf(el.dataset.who); const i = LPERF_DIMS.findIndex(d => d.k === el.dataset.k); if (i < 0) return; const d = x.dims[i]; const fx = LPERFPG.fixMap(); const key = x.L.n + '|' + d.k;
    const body = d.k === 'kpi' ? '<tr><th>指标</th><th>权重</th><th>满分值</th><th>当前值</th><th>单项得分</th><th>折算</th></tr>' + x.kpis.map(r => '<tr class="' + (r.light === 'bad' ? 'hl' : '') + '"><td>' + MG.light(r.light) + '<b>' + h(r.n) + '</b></td><td class="mono">' + r.w + '%</td><td class="mono">' + KPIPG.tgt(r, r.full) + '</td><td class="mono">' + h(r.vTxt) + '</td><td class="mono">' + r.s + '</td><td class="mono">' + r.pts + '</td></tr>').join('') + '<tr class="' + (x.risk ? 'hl' : '') + '"><td>' + MG.light(x.risk ? 'bad' : 'ok') + '<b>安全生产过程管理</b> <span class="note">风险指标</span></td><td class="mono">—</td><td class="mono">50 分</td><td class="mono">' + x.proc.fmt(x.proc.v) + ' 分</td><td class="mono">' + (x.risk ? '扣 ' + x.risk : '不扣分') + '</td><td class="mono ' + (x.risk ? 'b' : '') + '">' + (x.risk ? '−' + x.risk : '0') + '</td></tr>'
      : d.k === 'task' ? '<tr><th>重点任务</th><th>权重</th><th>完成情况</th><th>任务得分</th><th>折算</th></tr>' + x.tasks.map(r => '<tr><td><b>' + h(r.n) + '</b><br><span class="note">' + h(r.src) + '</span></td><td class="mono">' + r.w + '%</td><td class="note">' + h(r.txt) + '</td><td class="mono">' + r.s + '</td><td class="mono">' + r.pts + '</td></tr>').join('')
      : '<tr><th>评价项</th><th>权重</th><th>台账证据（基准分 ± 证据项）</th><th>初步分</th><th>折算</th></tr>' + x.evals.map(r => '<tr><td><b>' + h(r.n) + '</b></td><td class="mono">' + r.w + '%</td><td class="note">基准 ' + r.base + '；' + h(r.items.map(it => it[0] + (it[1] ? '（' + (it[1] > 0 ? '+' : '') + it[1] + '）' : '')).join('；')) + '</td><td class="mono">' + r.s + '</td><td class="mono">' + r.pts + '</td></tr>').join('');
    modal('<div class="t">' + h(x.L.n) + ' · ' + h(d.n) + '　' + MG.light(d.cls, d.sc + ' / ' + d.pts + '（' + d.pct + '%）') + '</div>' +
      '<div class="tbl"><table class="t">' + body + '<tr><td><b>本部分得分</b></td><td colspan="' + (d.k === 'kpi' ? 4 : d.k === 'task' ? 2 : 3) + '"></td><td class="mono" colspan="' + (d.k === 'task' ? 2 : 1) + '"><b>' + d.sc + '</b></td></tr></table></div>' +
      (d.k === 'eval' ? '<div class="tbl" style="margin-top:8px"><table class="t">' + x.evals.map(r => '<tr><th style="width:86px">' + h(r.n) + '</th><td class="note">' + h(r.pt) + '</td></tr>').join('') + '</table></div>' : '') +
      '<div class="tbl" style="margin-top:8px"><table class="t"><tr><th style="width:86px">计分规则</th><td class="note">' + h(d.rule) + '</td></tr><tr><th>取数来源</th><td class="note">' + h(d.src) + '</td></tr></table></div>' +
      '<div class="legend-note">' + (d.k === 'kpi' ? '颜色说明：绿灯 = 达到满分值；黄灯 = 达到基础值；红灯 = 未达基础值，整行浅色底标出。折算 = 单项得分 ÷ 1.2 × 权重。' : d.k === 'task' ? '说明：任务得分按各项里程碑计分规则计算，单项最高 120 分；折算 = 任务得分 ÷ 1.2 × 权重。' : '说明：综合评价由部门评价，页面按台账证据给初步分：基准分加减证据项（括号内为加减分），折算 = 初步分 × 权重。') + '</div>' +
      '<div class="bt">' + (fx[key] ? '<span class="tag ok">已列入改进要求 ' + h(fx[key]) + '</span>' : '<button data-act="lp-fix" data-who="' + h(x.L.n) + '" data-k="' + d.k + '">列入下季度改进要求</button>') + (d.k === 'kpi' ? '<button class="g" data-act="nav" data-to="goals" data-sub="lead">看考核指标</button>' : d.k === 'task' ? '<button class="g" data-act="nav" data-to="ledger" data-sub="weekly">看周报指标</button>' : '<button class="g" data-act="nav" data-to="ledger">看台账</button>') + '<span class="cf">初步评分由部门确认后使用</span></div>');
    XW.answer(x.L.n + '的' + d.n + '得 ' + d.sc + ' 分（满分 ' + d.pts + '）。' + (d.k === 'kpi' ? '失分在：' + (x.kpis.filter(r => r.light !== 'ok').map(r => r.n + ' ' + r.vTxt + '（' + r.s + ' 分）').join('；') || '无') + (x.risk ? '；安全生产过程管理 ' + x.proc.v + ' 分，低于 50 分扣 ' + x.risk + ' 分' : '') : d.k === 'task' ? x.tasks.map(r => r.n + ' ' + r.s + ' 分').join('、') : x.evals.map(r => r.n + ' ' + r.s).join('、') + '，依据是' + x.evals.map(r => r.items.filter(it => it[1]).map(it => it[0]).join('、')).filter(Boolean).join('；')) + '。', null, { confirm: false, speak: false }); },
  'lp-who'(el) { const x = lperfOf(el.dataset.who); const L = x.L;
    modal('<div class="t">' + h(L.n) + ' · ' + h(x.team) + '　<b class="mono" style="font-size:16px">' + x.total + '</b> <span class="tag ' + x.gradeCls + '">' + h(x.grade) + '</span><span class="note">　' + LPERF_Q.no + ' · 由部门确认后使用</span></div>' +
      '<div class="tbl"><table class="t"><tr><th style="width:96px">基本情况</th><td>' + L.age + ' 岁 · 工龄 ' + L.yrs + ' 年 · 任班长 ' + L.asLeader + ' 年 · ' + h(L.lv) + ' · ' + h(L.star) + ' · ' + h(L.edu) + (L.party ? ' · 党员' : '') + ' · 副班长 ' + h(L.deputy) + '</td></tr></table></div>' +
      '<div class="sixrows" style="margin-top:8px">' + x.dims.map(d => '<div data-act="lp-dim" data-who="' + h(L.n) + '" data-k="' + d.k + '" style="cursor:pointer"><span>' + h(d.n) + '</span>' + MG.bar(d.pct, d.cls) + '<b class="mono">' + d.sc + '</b><i class="note">满分 ' + d.pts + ' · 得分率 ' + d.pct + '%</i></div>').join('') + '</div>' +
      '<div class="hexsum">风险指标：安全生产过程管理 ' + x.proc.fmt(x.proc.v) + ' 分' + (x.risk ? '，扣 ' + x.risk + ' 分' : '，不扣分') + '　加扣分：' + (x.adj ? (x.adj > 0 ? '+' : '') + x.adj + '（' + h(x.adjRows.map(r => r[0]).join('；')) + '）' : '无') + '　红线：' + (x.red ? h(x.red) : '未触发') + '</div>' +
      '<div class="hexsum"><b style="color:var(--ok)">强项：</b>' + x.strong.map(d => h(d.n) + ' ' + d.pct + '%').join('、') + '　<b style="color:var(--warn)">得分率最低的三项：</b>' + x.lowSubs.map(s => h(s.n) + ' ' + Math.round(s.p) + '%').join('、') + '</div>' +
      '<div class="alert" style="margin-top:8px">结果应用：' + h(x.apply) + '</div>' +
      '<div class="bt"><button data-act="lp-doc" data-who="' + h(L.n) + '">生成评价意见</button><button class="g" data-act="lp-talk" data-who="' + h(L.n) + '">绩效面谈提纲</button><button class="g" data-act="pt-backup" data-i="' + LEADERS.indexOf(L) + '">看后备梯队</button></div>');
    XW.answer(L.n + '本季度 ' + x.total + ' 分，' + x.grade + '档；强在' + x.strong.map(d => d.n).join('、') + '，得分率最低的是' + x.lowSubs.slice(0, 2).map(s => s.n + ' ' + Math.round(s.p) + '%').join('、') + '。' + x.apply, null, { confirm: false, speak: false }); },
  'lp-ok'(el) { const who = el.dataset.who; const ok = LPERFPG.okMap(); ok[who] = DB.now(); LS.set('lperf_ok', ok); DB.log('班长绩效', who + ' 考评结果已确认'); render(); XW.fly('已确认 · ' + who); XW.answer(who + '的考评结果确认了，接下来可以下发到本人并约绩效面谈。', null, { confirm: false }); },
  'lp-okall'() { const ok = LPERFPG.okMap(); let n = 0; LEADERS.forEach(l => { if (!ok[l.n]) { ok[l.n] = DB.now(); n++; } }); LS.set('lperf_ok', ok); DB.log('班长绩效', '三位班长考评结果已确认'); render(); XW.fly('已确认 ' + n + ' 位'); XW.answer(n ? n + ' 位班长的考评结果都确认了。下一步下发到本人，需改进档的还要约谈并限期整改。' : '三位都已确认。', null, { confirm: false }); },
  'lp-send'(el) { const who = el.dataset.who; const ok = LPERFPG.okMap(); if (!ok[who]) { XW.answer('先确认' + who + '的考评结果再下发，未确认的结果不下发到本人。', null, { confirm: false }); return; } const x = lperfOf(who); const sent = LPERFPG.sentMap(); sent[who] = DB.now(); LS.set('lperf_sent', sent);
    DB.notify(who, LPERF_Q.no + '绩效考评结果 · 综合 ' + x.total + ' 分（' + x.grade + '）：强项 ' + x.strong.map(d => d.n).join('、') + '，短板 ' + x.weak.map(d => d.n).join('、') + '；' + x.apply + '。请在三个工作日内确认或提出申诉', '待确认', true);
    DB.log('班长绩效', who + ' 考评结果已下发'); render(); XW.fly('已下发 · ' + who); XW.answer(who + '的考评结果下发了：综合 ' + x.total + ' 分、' + x.grade + '档，短板' + x.weak.map(d => d.n).join('、') + '，三个工作日内确认或申诉。', null, { confirm: false }); },
  'lp-doc'(el) { const who = el.dataset.who; const x = lperfOf(who); const host = $('#lpdoc'); if (!host) return; host.hidden = false; host.innerHTML = ''; host.scrollIntoView({ block: 'nearest' });
    const paras = ['一、考评期与口径：' + LPERF_Q.no + '（' + LPERF_Q.range + '），按员工年度业绩责任书（班长）评价：考核指标 50%（第三方客户满意度、中压客户平均停电时间、快速复电成功率、中压线路故障跳闸次数、故障平均停电用户数降幅各 10%，安全生产过程管理为风险指标）、重点任务 10%、综合评价 40%，另计加扣分与红线事项。',
      '二、总体评价：' + who + '任' + x.team + '班长 ' + x.L.asLeader + ' 年，本季度初步综合得分 ' + x.total + ' 分，' + x.grade + '档，环比' + (x.delta > 0 ? '上升 ' + x.delta + ' 分' : x.delta < 0 ? '下降 ' + (-x.delta) + ' 分' : '持平') + '。',
      '三、做得好的：' + x.strong.map(d => d.n + ' ' + d.sc + '/' + d.pts + '（' + d.pct + '%）').join('、') + '。' + (x.kpis.filter(r => r.light === 'ok').length ? '考核指标中' + x.kpis.filter(r => r.light === 'ok').map(r => r.n).join('、') + '达到满分值。' : ''),
      '四、需要改进的：' + x.lowSubs.map(s => s.n + '（得分率 ' + Math.round(s.p) + '%）').join('、') + (x.risk ? '；安全生产过程管理 ' + x.proc.v + ' 分，低于 50 分扣 ' + x.risk + ' 分' : '') + '。',
      '五、下季度要求：' + x.weak.map(d => LPERFPG_REQ(d.k, x)).join('；') + '。',
      '六、结果应用：' + x.apply + '。以上为初步评价意见，由部门确认后与本人面谈并归档。'];
    MG.stream(host, paras, { title: who + ' ' + LPERF_Q.no + '绩效评价意见', done() { host.insertAdjacentHTML('beforeend', '<div class="bt"><button data-act="lp-docsave" data-who="' + h(who) + '">存入文稿中心</button><button class="g" data-act="lp-talk" data-who="' + h(who) + '">转绩效面谈提纲</button></div>'); } });
    XW.answer(who + '的绩效评价意见按六段写在右边的卡片里了：口径、总体评价、做得好的、需要改进的、下季度要求、结果应用。存入文稿中心后可以直接用于面谈。', null, { confirm: false }); },
  'lp-docsave'(el) { const who = el.dataset.who; MG.saveDoc('lperf-' + who, who + ' ' + LPERF_Q.no + '绩效评价意见', $('#lpdoc')); XW.fly('已存入文稿中心'); XW.answer('存好了，在文稿中心能找到' + who + '这一份。', null, { confirm: false }); },
  'lp-talk'(el) { const who = el.dataset.who; const x = lperfOf(who); const g = TALK_GUIDES['绩效面谈']; const host = document.createElement('div'); host.className = 'doc'; const d = XW.msg('a', who + ' · 班长绩效面谈提纲：'); d.appendChild(host); if ($('#modal')) $('#modal').hidden = true;
    MG.stream(host, ['开场：' + g.open].concat(g.items.map((it, i) => (i + 1) + '. ' + it), ['本人情况：' + LPERF_Q.no + '综合 ' + x.total + ' 分（' + x.grade + '）；强项 ' + x.strong.map(t => t.n).join('、') + '；短板 ' + x.weak.map(t => t.n + ' ' + t.pct + '%').join('、') + '；' + x.apply], ['下季度要求：' + x.weak.map(t => LPERFPG_REQ(t.k, x)).join('；')], ['沟通要点：' + g.tips.join('；')]), { title: who + ' 班长绩效面谈提纲', done() { d.insertAdjacentHTML('beforeend', '<div class="bt"><button data-act="guide-save" data-who="' + h(who) + '" data-kind="班长绩效面谈">存入文稿中心</button><button class="g" data-act="lp-send" data-who="' + h(who) + '">下发考评结果</button></div>'); XW.scrollChat(); } }); },
  'lp-fix'(el) { const who = el.dataset.who; const k = el.dataset.k; const x = lperfOf(who); const d = x.dims.find(q => q.k === k); if (!d) return; const fx = LPERFPG.fixMap(); fx[who + '|' + k] = DB.now(); LS.set('lperf_fix', fx);
    const req = LPERFPG_REQ(k, x); DB.notify(who, '下季度改进要求 · ' + d.n + '（本季度 ' + d.pct + '%）：' + req, '待确认', true); if (x.team === TEAM.name) MG.planPush('班组', d.n + '改进：' + req, '班长绩效改进要求'); DB.log('班长绩效', who + ' ' + d.n + ' 改进要求已列入');
    if ($('#modal')) $('#modal').hidden = true; if ($('#lpfix')) $('#lpfix').innerHTML = LPERFPG.fixHTML(); XW.fly('已列入 · ' + who); XW.answer(who + '的' + d.n + '列入下季度改进要求了：' + req + '。已发到本人待确认' + (x.team === TEAM.name ? '，同时排进了班组计划' : '') + '。', null, { confirm: false }); },
  'lp-fixall'() { const A = LPERFPG.all(); const fx = LPERFPG.fixMap(); let n = 0;
    A.forEach(x => x.weak.filter(d => d.cls !== 'ok').forEach(d => { const key = x.L.n + '|' + d.k; if (!fx[key]) { fx[key] = DB.now(); const req = LPERFPG_REQ(d.k, x); DB.notify(x.L.n, '下季度改进要求 · ' + d.n + '（本季度 ' + d.pct + '%）：' + req, '待确认', true); if (x.team === TEAM.name) MG.planPush('班组', d.n + '改进：' + req, '班长绩效改进要求'); n++; } }));
    LS.set('lperf_fix', fx); DB.log('班长绩效', '改进要求 ' + n + ' 条已列入'); if ($('#lpfix')) $('#lpfix').innerHTML = LPERFPG.fixHTML(); XW.fly('已列入 ' + n + ' 条'); XW.answer(n ? n + ' 条改进要求都列入下季度了，每条都发到对应班长待确认。' : '改进要求都已列入。', null, { confirm: false }); },
  'lp-sheet'() { const A = LPERFPG.all(); const ok = LPERFPG.okMap(); const miss = LEADERS.filter(l => !ok[l.n]);
    if (miss.length) { XW.answer('还有 ' + miss.map(l => l.n).join('、') + ' 的考评结果没确认，考评表要三位都确认后才生成。点"全部确认"或逐个确认。', null, { confirm: false }); return; }
    modal('<div class="t">' + LPERF_Q.no + ' 班长绩效考评表　<span class="note">由部门确认后使用 · 分档不排名次</span></div><div class="tbl"><table class="t"><tr><th>班长</th><th>班组</th>' + LPERF_DIMS.map(d => '<th>' + h(d.n) + '<br><span class="note">' + d.pts + '</span></th>').join('') + '<th>风险扣分</th><th>加扣分</th><th>综合</th><th>分档</th><th>结果应用</th></tr>' + A.map(x => '<tr><td><b>' + h(x.L.n) + '</b></td><td class="note">' + h(x.team) + '</td>' + x.dims.map(d => '<td class="mono ' + (d.cls === 'ok' ? 'g' : d.cls === 'bad' ? 'b' : '') + '">' + d.sc + '</td>').join('') + '<td class="mono ' + (x.risk ? 'b' : '') + '">' + (x.risk ? '−' + x.risk : '0') + '</td><td class="mono">' + (x.adj > 0 ? '+' : '') + x.adj + '</td><td class="mono"><b>' + x.total + '</b></td><td><span class="tag ' + x.gradeCls + '">' + h(x.grade) + '</span></td><td class="note" style="max-width:220px">' + h(x.apply) + '</td></tr>').join('') + '</table></div><div class="bt"><button data-act="lp-sheetsave">存入文稿中心并报部门</button></div>');
    XW.answer('考评表出来了：' + A.map(x => x.L.n + ' ' + x.total + '（' + x.grade + '）').join('、') + '。存入文稿中心后报部门，分档不排名次。', null, { confirm: false }); },
  'lp-sheetsave'() { const A = LPERFPG.all(); const body = LPERF_Q.no + ' 班长绩效考评表\n' + A.map(x => x.L.n + ' ' + x.team + '：' + x.dims.map(d => d.n + ' ' + d.sc).join('、') + (x.risk ? '、风险扣分 ' + x.risk : '') + (x.adj ? '、加扣分 ' + x.adj : '') + '，综合 ' + x.total + '，' + x.grade + '，' + x.apply).join('\n'); const docs = LS.get('docs', {}); docs['lperf-sheet'] = { t: LPERF_Q.no + ' 班长绩效考评表', ts: Date.now(), body: body }; LS.set('docs', docs); DB.log('文稿', '班长绩效考评表已保存'); if ($('#modal')) $('#modal').hidden = true; XW.fly('已存入文稿中心'); XW.answer('考评表存入文稿中心了，可以直接报部门。', null, { confirm: false }); }
});
function LPERFPG_REQ(k, x) {
  const I = x.input;
  if (k === 'kpi') { const bad = x.kpis.filter(r => r.light !== 'ok'); return (bad.length ? bad.map(r => r.n + '从 ' + r.vTxt.replace(/^累计 [^·]+· 推算全年 /, '全年 ') + ' 追到满分值 ' + KPIPG.tgt(r, r.full)).join('、') : '考核指标保持满分值') + (x.risk ? '；安全生产过程管理补到 50 分以上' : '') + '，每两周报一次进度'; }
  if (k === 'task') { const low = x.tasks.filter(r => r.s < 110); return (low.length ? low.map(r => r.n + '（' + r.txt + '）').join('；') + '，里程碑逐月对账' : '重点任务里程碑按期推进，逐月对账'); }
  return [I.late ? '到期任务当日派完' : '', I.pend ? '两票当日审完' : '', I.wkMiss ? '周报按期报送' : '', I.vio ? '一般违章压到 1 起以内' : '', I.absent ? '安全活动与党建学习全员到位' : ''].filter(Boolean).join('、') || '保持"马上就办、办就办好"，每月登记一项改进或创新';
}

/* ---------- 多班组人员总览仪表盘 + 下钻 + 员工画像（综合画像 + 专业画像） ---------- */
const STAFFPG = {
  all() { return MGR.teamOrder.reduce((a, t) => a.concat(teamPeople(t).map(p => Object.assign({ team: t }, p))), []); },
  listHTML(team) { const ps = teamPeople(team); return '<div class="tbl"><table class="t"><tr><th>姓名</th><th>岗位</th><th>年龄</th><th>工龄</th><th>技能等级</th><th>星级工程师</th><th>证书</th><th>优势特长</th><th>状态</th></tr>' + ps.map(p => '<tr data-act="st-person" data-who="' + p.n + '" style="cursor:pointer" class="' + (STAFFPG.cur === p.n ? 'hl' : '') + '"><td><b>' + h(p.n) + '</b></td><td class="note">' + h(p.post) + '</td><td class="mono">' + p.age + '</td><td class="mono">' + p.yrs + '</td><td>' + h(skillLvOf(p.n)) + '</td><td>' + (STAR_ENG[p.n] ? '<span class="tag v">' + h(STAR_ENG[p.n]) + '</span>' : '—') + '</td><td class="mono">' + p.cert.length + '</td><td>' + portTop(p.n).map(x => '<span class="tag ok">' + h(x[0].replace(/（.*$/, '')) + ' L' + x[1] + '</span>').join('') + '</td><td>' + h(team === TEAM.name ? p.status : team === LAB.name ? (LAB.borrowed.some(b => b.n === p.n) ? '借调' : p.n === '何静' ? '病假' : '在岗') : (p.n === '谭俊' ? '外勤' : '在岗')) + '</td></tr>').join('') + '</table></div>'; },
  hexHTML(n) { const p = personAny(n); if (!p) return '<div class="empty">点左侧任一人，看员工画像</div>'; const team = teamOfPerson(n); return '<div class="hexhead"><b>' + h(n) + '</b><span class="note">' + h(team) + ' · ' + h(p.post) + ' · ' + p.age + ' 岁 · 工龄 ' + p.yrs + ' 年 · ' + h(skillLvOf(n)) + (STAR_ENG[n] ? ' · ' + h(STAR_ENG[n]) : '') + (EXPERTS[n] ? ' · ' + h(EXPERTS[n]) : '') + '</span></div>' + SKILLPG.portHTML(n, { list: teamPeople(team), avgN: team + '均值', act: 'st-dim' }) + '<div class="bt">' + (P[n] ? '<button class="s g" data-act="sk-person" data-who="' + n + '">人员档案</button>' : '') + '<button class="s g" data-act="st-say" data-who="' + n + '">她怎么看</button></div>'; }
};
PAGES.staff = {
  render() { const all = STAFFPG.all(); const team = S.sub && MGR.teamOrder.includes(S.sub) ? S.sub : TEAM.name; const lv = {}; all.forEach(p => { const l = skillLvOf(p.n); lv[l] = (lv[l] || 0) + 1; }); const posts = {}; all.forEach(p => { const k = postClass(p); posts[k] = (posts[k] || 0) + 1; }); const on = MGR.teamOrder.reduce((s, t) => s + teamStat(t).on, 0); const out = PEOPLE.filter(p => p.status === '外勤').length + 1; const leave = PEOPLE.filter(p => p.status === '休假').length + 1;
    return cmdHTML(['三个班组一共多少人在岗', '技师有几个', '看韩雪的员工画像']) + pageHead('人员总览', '三个班组 ' + all.length + ' 人 · 在岗 / 技能结构 / 专助责与班员 · 点班组看人员清单，点人看员工画像') +
      '<div class="grid4"><div class="card kpi"><span>在岗人数</span><b>' + on + '/' + all.length + '</b><em>外勤 ' + out + ' · 休假 / 病假 ' + leave + ' · 借调 ' + LAB.borrowed.length + '</em></div><div class="card kpi"><span>技师及以上</span><b>' + ((lv['技师'] || 0) + (lv['高级技师'] || 0)) + '</b><em>高级工 ' + (lv['高级工'] || 0) + ' · 中级工 ' + (lv['中级工'] || 0) + ' · 初级工 ' + (lv['初级工'] || 0) + ' · 未定级 ' + (lv['未定级'] || 0) + '</em></div><div class="card kpi"><span>班长 / 专责 / 班员</span><b>' + (posts['班长'] || 0) + ' / ' + (posts['专责'] || 0) + ' / ' + (all.length - (posts['班长'] || 0) - (posts['专责'] || 0)) + '</b><em>高级作业员 ' + (posts['高级作业员'] || 0) + ' · 中级 ' + (posts['中级作业员'] || 0) + ' · 初级 ' + (posts['初级作业员'] || 0) + '</em></div><div class="card kpi"><span>星级工程师 / 专家</span><b>' + all.filter(p => STAR_ENG[p.n]).length + ' / ' + all.filter(p => EXPERTS[p.n] && /^专家（/.test(EXPERTS[p.n])).length + '</b><em>专家候选 ' + all.filter(p => EXPERTS[p.n] && /候选/.test(EXPERTS[p.n])).length + ' 人</em></div></div>' +
      '<div class="grid3"><div class="card"><div class="h"><b>技能结构</b><span>三班组</span></div>' + CH.mini.donut(SKILL_LADDER.filter(l => lv[l]).map((l, i) => ({ k: l, v: lv[l], c: RAMP[Math.min(5, i + 1)], act: 'st-seg', k2: l })), { sub: '人' }) + '</div><div class="card"><div class="h"><b>专助责与班员结构</b></div>' + CH.mini.donut(Object.keys(posts).map((k, i) => ({ k, v: posts[k], c: CPAL[i % 6] })), { sub: '人' }) + '</div><div class="card"><div class="h"><b>各班组在岗</b><span>点柱看清单</span></div>' + CH.mini.group(MGR.teamOrder.map(t => t.replace('配电', '')), [{ n: '在编', vals: MGR.teamOrder.map(t => teamStat(t).n) }, { n: '在岗', vals: MGR.teamOrder.map(t => teamStat(t).on), c: CPAL[4] }], { h: 120 }) + CH.mini.legend([{ n: '在编' }, { n: '在岗', c: CPAL[4] }]) + '</div></div>' +
      '<div class="grid2" style="grid-template-columns:1.5fr 1fr"><div class="card"><div class="h"><b>人员清单</b><div class="tabs" style="border:0;padding:0;margin-left:8px">' + MGR.teamOrder.map(t => '<button class="' + (t === team ? 'on' : '') + '" data-act="st-team" data-n="' + h(t) + '">' + h(t) + ' ' + teamPeople(t).length + '</button>').join('') + '</div></div><div id="stlist">' + STAFFPG.listHTML(team) + '</div></div><div class="card"><div class="h"><b>员工画像</b><span>综合画像（通用素质模型）· 专业画像（岗位说明书）</span></div><div id="hexhost">' + STAFFPG.hexHTML(STAFFPG.cur) + '</div></div></div>'; },
  after() { CH.mount($('#main')); }
};
Object.assign(ACT, {
  'st-team'(el) { const n = el.dataset.n; if (S.page !== 'staff') { nav('staff', n); return; } S.sub = n; $$('#main .tabs button').forEach(b => b.classList.toggle('on', b.dataset.n === n)); $('#stlist').innerHTML = STAFFPG.listHTML(n); const s = teamStat(n); XW.answer(n + ' ' + s.n + ' 人，在岗 ' + s.on + '，平均 ' + s.avgAge + ' 岁，技师及以上 ' + s.senior + '、高级工及以上 ' + s.high + '，30 岁以下 ' + s.young + ' 人。点任一人看员工画像。', null, { confirm: false, speak: false }); },
  'st-person'(el) { const n = el.dataset.who; STAFFPG.cur = n; if (S.page !== 'staff') { nav('staff', teamOfPerson(n)); return; } const host = $('#hexhost'); if (host) { host.innerHTML = STAFFPG.hexHTML(n); CH.mount(host); } $$('#stlist tr').forEach(r => r.classList.toggle('hl', r.dataset.who === n)); const top = portTop(n), low = portLow(n); XW.answer(n + '的优势在' + top.map(x => x[0] + '（L' + x[1] + '）').join('、') + '，' + low[0] + '（L' + low[1] + '）偏弱' + (proGap(n).length ? '，专业画像 ' + proGap(n).length + ' 项未到本岗级要求' : '') + '。综合画像按通用素质模型，专业画像按岗位说明书二级业务。', null, { confirm: false, speak: false }); },
  'st-say'(el) { const n = el.dataset.who; const p = personAny(n); const g = genOf(n), pr = proOf(n); const team = teamOfPerson(n); const low = portLow(n); const gap = proGap(n); const pa = pr.reduce((t, x) => t + x, 0) / pr.length; XW.answer(n + '：' + (pa >= 3 ? '专业上能独当一面，' : '专业还在成长期，') + (g[0] >= 3 ? '执行上靠得住，' : '') + (gap.length ? '专业画像有 ' + gap.length + ' 项没到本岗级要求，' : '') + '最弱的是' + low[0] + '。' + (team === TEAM.name && STAR_ENG[n] ? '已是' + STAR_ENG[n] + '，' : '') + (p.age <= 30 ? '30 岁以下，适合排进培养对象。' : p.age >= 45 ? '经验最足，适合带徒。' : '正当年，可作骨干培养。'), null, { confirm: false }); },
  'st-dim'(el) { ACT['sk-dim'](el); },
  'st-seg'(el) { const l = el.dataset.k2 || el.dataset.k; const all = STAFFPG.all().filter(p => skillLvOf(p.n) === l); XW.answer(l + ' ' + all.length + ' 人：' + all.map(p => p.n + '（' + p.team.replace('配电', '') + '）').join('、'), null, { confirm: false }); }
});

/* ---------- 班组结构对比画像 ---------- */
const STRUCPG = {
  rows() { const names = MGR.teamOrder; const st = {}; names.forEach(n => { st[n] = teamStat(n); }); const R = [
    { n: '人数 / 在岗', num: names.reduce((a, n) => (a[n] = st[n].on, a), {}), vals: names.reduce((a, n) => (a[n] = st[n].n + ' / ' + st[n].on, a), {}), high: true, w: 0 },
    { n: '平均年龄', num: names.reduce((a, n) => (a[n] = st[n].avgAge, a), {}), unit: '岁', high: false, w: 1, note: '越接近 35 越均衡' },
    { n: '30 岁以下占比', num: names.reduce((a, n) => (a[n] = Math.round(st[n].young / st[n].n * 100), a), {}), unit: '%', high: true, w: 1 },
    { n: '平均工龄', num: names.reduce((a, n) => (a[n] = st[n].stable.avgYrs, a), {}), unit: '年', high: true, w: 1 },
    { k: 'new', n: '近 1 年 / 3 年入职新员工', num: names.reduce((a, n) => (a[n] = newHires(n).y3, a), {}), vals: names.reduce((a, n) => (a[n] = newHires(n).y1 + ' / ' + newHires(n).y3, a), {}), unit: '人', high: true, w: 1, note: '按入职年月统计近 12 个月 / 36 个月；点格看名单' },
    { n: '近三年离职', num: names.reduce((a, n) => (a[n] = st[n].stable.leave3y, a), {}), unit: '人', high: false, w: 2 },
    { n: '借调 / 长病 / 转岗意向', num: names.reduce((a, n) => (a[n] = st[n].stable.borrowed + st[n].stable.longSick + st[n].stable.intent, a), {}), vals: names.reduce((a, n) => (a[n] = st[n].stable.borrowed + ' / ' + st[n].stable.longSick + ' / ' + st[n].stable.intent, a), {}), high: false, w: 2 },
    { n: '高级工及以上占比', num: names.reduce((a, n) => (a[n] = Math.round(st[n].high / st[n].n * 100), a), {}), unit: '%', high: true, w: 2 },
    { n: '技师及以上', num: names.reduce((a, n) => (a[n] = st[n].senior, a), {}), unit: '人', high: true, w: 2 },
    { n: '星级工程师 / 专家', num: names.reduce((a, n) => (a[n] = st[n].eng + st[n].expert, a), {}), vals: names.reduce((a, n) => (a[n] = st[n].eng + ' / ' + st[n].expert, a), {}), high: true, w: 1 },
    { n: '人均核心技能实操量', num: { '配电自动化班': skill9PerCap(), '试验班': 34.5, '配电运维一班': 18.2 }, unit: '次', high: true, w: 2 }
  ]; R.forEach(r => { const nums = names.map(n => r.num[n]); const best = r.high ? Math.max.apply(null, nums) : Math.min.apply(null, nums); const worst = r.high ? Math.min.apply(null, nums) : Math.max.apply(null, nums); r.best = names.filter(n => r.num[n] === best && best !== worst); r.worst = names.filter(n => r.num[n] === worst && best !== worst); }); return R; },
  strength() { const R = this.rows(); const names = MGR.teamOrder; const sc = {}; names.forEach(n => { sc[n] = 0; }); R.forEach(r => { r.best.forEach(n => { sc[n] += r.w; }); r.worst.forEach(n => { sc[n] -= r.w; }); }); return names.map(n => ({ n, sc: sc[n], tag: sc[n] >= 3 ? '强' : sc[n] <= -3 ? '弱' : '中' })); },
  advice() { const st = {}; MGR.teamOrder.forEach(n => { st[n] = teamStat(n); }); return [
    { t: '配电运维一班 年轻但技能弱：30 岁以下 ' + st['配电运维一班'].young + '/11，高级工及以上 ' + st['配电运维一班'].high + ' 人，人均实操 18.2 次（三班组最低）；近 3 年入职 ' + newHires('配电运维一班').y3 + ' 人全部未结对师傅', do: '先把 ' + newHires('配电运维一班').y3 + ' 名新员工逐人结对师傅；从配电自动化班派 1 名高级作业员（李文博）到配电运维一班轮岗 6 个月，带终端巡视与二次回路；同时接收该班 1 名初级作业员（罗天）到配电自动化班学动作分析', who: ['赵立群', '陈志远'], k: 'r1' },
    { t: '试验班 专家型但骨干集中：技师及以上 ' + st['试验班'].senior + '/8 全部 36 岁以上，30 岁以下 4 人中 3 人为初级工或学员，近 1 年无新进人员、近 3 年仅 ' + newHires('试验班').y3 + ' 人，学员有转岗意向', do: '试验班接收配电运维一班 1 名初级作业员（曾静）轮岗学交接试验 3 个月；刘畅借调到期返岗', who: ['周建国', '陈志远'], k: 'r2' },
    { t: '配电自动化班 骨干型：★模块中断层风险高的有 ' + SKILLPG.gaps().filter(g => g.risk === '高').length + ' 个，实操量集中在工作负责人', do: '班内轮岗：初级作业员按季度轮到工作负责人组；派工时把实操量低的人排进对应技能的活', who: ['赵立群'], k: 'r3' }
  ]; }
};
PAGES.structure = {
  render() { const R = STRUCPG.rows(); const names = MGR.teamOrder; const S3 = STRUCPG.strength(); const sent = LS.get('rotate_sugg', {}); const lvs = SKILL_LADDER.filter(l => names.some(n => teamStat(n).lv[l]));
    return cmdHTML(['哪个班组最弱', '轮岗建议', '三个班组年龄结构']) + pageHead('班组结构对比', '人员稳定性 · 年龄结构 · 技能结构 · 强弱差异 · 人力调配与班组轮岗建议', '<button class="s g" data-act="nav" data-to="compare">业务横向对比</button><button class="s g" data-act="nav" data-to="risk" data-sub="sim">跨班组调配</button>') +
      '<div class="grid3">' + S3.map(s => '<div class="card kpi"><span>' + h(s.n) + ' · ' + h(TEAM_TAGS[s.n].kind) + '</span><b class="' + (s.tag === '强' ? 'g' : s.tag === '弱' ? 'bad' : 'w') + '">' + h(s.tag) + '</b><em>综合 ' + (s.sc > 0 ? '+' : '') + s.sc + '（按维度权重：最好 +、最差 −）</em></div>').join('') + '</div>' +
      '<div class="card"><div class="h"><b>结构对比画像</b><span>绿 = 三班组最好 · 红 = 最需关注</span></div><div class="tbl"><table class="t cmp"><tr><th>维度</th>' + names.map(n => '<th>' + h(n) + '</th>').join('') + '<th>说明</th></tr>' + R.map(r => '<tr><td><b>' + h(r.n) + '</b>' + (r.unit ? '<span class="note">（' + h(r.unit) + '）</span>' : '') + '</td>' + names.map(n => '<td' + (r.k === 'new' ? ' data-act="stc-new" data-n="' + h(n) + '" style="cursor:pointer"' : '') + '><span class="cmpv ' + (r.best.includes(n) ? 'ok' : r.worst.includes(n) ? 'bad' : '') + '">' + h(r.vals ? r.vals[n] : r.num[n]) + '</span></td>').join('') + '<td class="note">' + h(r.note || '') + '</td></tr>').join('') + '</table></div></div>' +
      '<div class="grid2"><div class="card"><div class="h"><b>年龄结构</b><span>三班组</span></div>' + CH.mini.group(AGE_BANDS.map(b => b[0].replace(' 岁', '')), names.map((n, i) => ({ n: n.replace('配电', ''), vals: AGE_BANDS.map(b => teamPeople(n).filter(p => p.age >= b[1] && p.age <= b[2]).length), c: CPAL[i] })), { h: 130 }) + CH.mini.legend(names.map((n, i) => ({ n: n.replace('配电', ''), c: CPAL[i] }))) + '</div><div class="card"><div class="h"><b>技能等级结构</b></div>' + CH.mini.group(lvs, names.map((n, i) => ({ n: n.replace('配电', ''), vals: lvs.map(l => teamStat(n).lv[l] || 0), c: CPAL[i] })), { h: 130 }) + CH.mini.legend(names.map((n, i) => ({ n: n.replace('配电', ''), c: CPAL[i] }))) + '</div></div>' +
      '<div class="card"><div class="h"><b>人力调配与班组轮岗建议</b><span>由班长确认后执行</span></div>' + STRUCPG.advice().map(a => '<div class="fixrow"><div><b>' + h(a.t) + '</b><p>' + h(a.do) + '</p></div><div class="bt">' + (sent[a.k] ? '<span class="tag ok">已发 ' + h(sent[a.k]) + '</span>' : '<button class="s" data-act="stc-rotate" data-k="' + a.k + '">发轮岗建议给' + h(a.who.join('、')) + '</button>') + '</div></div>').join('') + '</div>'; },
  after() { CH.mount($('#main')); }
};
Object.assign(ACT, {
  'stc-new'(el) { const t = el.dataset.n; const N = newHires(t); const lead = MGR.leaderOf(t); const men = (typeof MENTORS !== 'undefined' ? MENTORS : []);
    modal('<div class="t">' + h(t) + ' · 近 3 年入职新员工　<span class="note">班长 ' + h(lead) + ' · 全班 ' + teamPeople(t).length + ' 人</span></div>' +
      '<div class="scorerow"><div class="big"><b>' + N.y1 + '</b><span>近 1 年入职（' + NEW_WIN.y1.replace('-', ' 年 ') + ' 月起）</span></div><div class="big"><b>' + N.y3 + '</b><span>近 3 年入职（' + NEW_WIN.y3.replace('-', ' 年 ') + ' 月起）</span></div><div class="big"><b>' + N.pct3 + '%</b><span>占全班人数</span></div></div>' +
      (N.y3 ? '<div class="tbl"><table class="t"><tr><th>姓名</th><th>入职年月</th><th>入职年限</th><th>岗位</th><th>年龄</th><th>职业技能等级</th><th>师傅</th></tr>' + N.list3.map(x => { const m = men.find(q => q.s === x.p.n); return '<tr class="' + (x.d >= NEW_WIN.y1 ? 'hl' : '') + '"><td><b>' + h(x.p.n) + '</b></td><td class="mono">' + h(x.d.replace('-', ' 年 ')) + ' 月</td><td class="mono">' + x.p.yrs + ' 年</td><td class="note">' + h(x.p.post) + '</td><td class="mono">' + x.p.age + '</td><td>' + h(skillLvOf(x.p.n)) + '</td><td>' + (m ? '<b>' + h(m.m) + '</b>' : '<span class="note">未结对</span>') + '</td></tr>'; }).join('') + '</table></div>'
        : '<div class="alert bad">' + MG.light('bad') + h(t) + '近 3 年无新进人员，骨干层退出后无人接续</div>') +
      '<div class="bt"><button data-act="stc-newnote" data-n="' + h(t) + '">发新员工带教提醒给' + h(lead) + '</button><button class="g" data-act="nav" data-to="staff">看人员总览</button></div>');
    XW.answer(t + '近 1 年入职 ' + N.y1 + ' 人、近 3 年 ' + N.y3 + ' 人，占全班 ' + N.pct3 + '%。' + (N.y1 ? '最近一位是' + N.list3[0].p.n + '，' + N.list3[0].d.replace('-', ' 年 ') + ' 月入职。' : '近一年没有新进人员，梯队补充要靠跨班组调配。'), null, { confirm: false, speak: false }); },
  'stc-newnote'(el) { const t = el.dataset.n; const N = newHires(t); const lead = MGR.leaderOf(t); DB.notify(lead, '新员工带教 · ' + t + '近 3 年入职 ' + N.y3 + ' 人（' + (N.list3.map(x => x.p.n).join('、') || '无') + '），请逐人结对师傅并报培养计划', '待确认', true); DB.log('新员工带教提醒', t + ' → ' + lead); $('#modal').hidden = true; XW.fly('已发 · ' + lead); XW.answer('提醒发给' + lead + '了：' + t + '近 3 年入职 ' + N.y3 + ' 人，逐人结对师傅后报培养计划，确认回来会落到班组计划。', null, { confirm: false }); },
  'stc-rotate'(el) { const a = STRUCPG.advice().find(x => x.k === el.dataset.k); if (!a) return; a.who.forEach(n => DB.notify(n, '轮岗建议 · ' + a.do, '待确认', true)); const s = LS.get('rotate_sugg', {}); s[a.k] = DB.now(); LS.set('rotate_sugg', s); DB.log('轮岗建议', a.do); render(); XW.fly('已发 · ' + a.who.join('、')); XW.answer('轮岗建议发给' + a.who.join('、') + '了，两位班长确认后走跨班组调配。', null, { confirm: false }); }
});

/* ---------- 团队风险画像聚合 ---------- */
PAGES.risks = {
  render() { const R = riskAgg(); const groups = ['敏感岗位轮岗', '考勤异常', '绩效持续偏低', '队伍稳定性']; const sent = LS.get('risk_sent', {}); const AN = { rotate: '发轮岗提醒', care: '发关怀提醒', remind: '提醒班长', talk: '面谈提纲', transfer: '催返岗', ladder: '看结构对比' };
    return cmdHTML(['哪位班长该轮岗了', '考勤异常有谁', '刘畅借调多久了']) + pageHead('团队风险画像', '班长敏感岗位轮岗 · 考勤异常 · 绩效持续偏低 · 队伍稳定性 · 三班组台账自动聚合，每项对应一个动作', '<button class="s g" data-act="nav" data-to="mcare">员工关怀</button>') +
      '<div class="grid4">' + groups.map(g => { const l = R.filter(r => r.g === g); return '<div class="card kpi"><span>' + h(g) + '</span><b class="' + (l.some(r => r.lv === '高') ? 'bad' : l.length ? 'w' : 'g') + '">' + l.length + '</b><em>' + h(l.map(r => r.who).filter(w => w !== '—').join('、') || '无') + '</em></div>'; }).join('') + '</div>' +
      '<div class="card"><div class="h"><b>风险清单 · ' + R.length + ' 项</b><span>高 ' + R.filter(r => r.lv === '高').length + ' · 中 ' + R.filter(r => r.lv === '中').length + ' · 低 ' + R.filter(r => r.lv === '低').length + '</span></div><div class="tbl"><table class="t"><tr><th>类别</th><th>等级</th><th>班组</th><th>人</th><th>事项</th><th>来源</th><th>动作</th></tr>' + R.map((r, i) => '<tr class="' + (r.lv === '高' ? 'hl' : '') + '"><td><span class="tag ' + ({ 敏感岗位轮岗: 'v', 考勤异常: 'c', 绩效持续偏低: '', 队伍稳定性: 'c' }[r.g]) + '">' + h(r.g) + '</span></td><td>' + MG.light(r.lv === '高' ? 'bad' : r.lv === '中' ? 'w' : 'ok', r.lv) + '</td><td>' + h(r.team) + '</td><td>' + (r.who !== '—' ? '<b data-act="st-person" data-who="' + r.who + '">' + h(r.who) + '</b>' : '—') + '</td><td>' + h(r.t) + '</td><td class="note">' + h(r.src) + '</td><td>' + (sent[i] ? '<span class="tag ok">' + h(sent[i]) + '</span>' : '<button class="s g" data-act="rk-act" data-i="' + i + '">' + AN[r.act] + '</button>') + '</td></tr>').join('') + '</table></div></div>' +
      '<div class="grid2"><div class="card"><div class="h"><b>按班组</b></div>' + CH.mini.group(MGR.teamOrder.map(t => t.replace('配电', '')), groups.map((g, i) => ({ n: g, vals: MGR.teamOrder.map(t => R.filter(r => r.g === g && r.team === t).length), c: CPAL[i] })), { h: 120 }) + CH.mini.legend(groups.map((g, i) => ({ n: g, c: CPAL[i] }))) + '</div><div class="card"><div class="h"><b>班长任职年限 · 敏感岗位轮岗</b><span>虚线 = ' + ROT_LIMIT + ' 年轮岗期</span></div>' + CH.mini.bars(SENSITIVE_POSTS.map(s => ({ n: s.who + ' · ' + s.team.replace('配电', ''), v: yearsSince(s.since), c: yearsSince(s.since) >= s.limit ? '#e5484d' : CPAL[0], unit: ' 年', act: 'st-person', who: s.who })), { x0: 110, limit: ROT_LIMIT, max: 14, unit: ' 年' }) + '<div class="legend-note">敏感岗位轮岗只针对班长（班组负责人），普通作业人员不涉及。颜色说明：红 = 任职已超过轮岗期、蓝 = 未超。</div></div></div>'; },
  after() { CH.mount($('#main')); }
};
Object.assign(ACT, {
  'rk-act'(el) { const i = +el.dataset.i; const r = riskAgg()[i]; if (!r) return; const leader = MGR.leaderOf(r.team); const sent = LS.get('risk_sent', {}); const mark = () => { sent[i] = DB.now(); LS.set('risk_sent', sent); DB.log('风险治理', r.g + ' · ' + r.who + ' · ' + r.t); if (S.page === 'risks') render(); };
    if (r.act === 'rotate') { DB.notify(r.who, '敏感岗位轮岗提醒 · ' + r.who + '：' + r.t + '，部门将在本年度内研究轮岗交流安排，请提前准备班组交接', '已发'); mark(); XW.answer('轮岗提醒发给' + r.who + '本人了：' + r.t.split('；')[0] + '。' + (r.t.includes('后备') ? '后备人选' + r.t.split('后备 ')[1] + '，团队画像总览里能看后备梯队。' : ''), null, { confirm: false }); }
    else if (r.act === 'care') { DB.notify(leader, '员工关怀提醒 · ' + r.who + '：' + r.t + '，请安排关怀面谈', '已发'); mark(); XW.answer('关怀提醒发给' + leader + '了，员工关怀页有面谈提纲。', null, { confirm: false }); }
    else if (r.act === 'remind') { DB.notify(leader, '考勤提醒 · ' + r.who + '：' + r.t, '已发'); mark(); XW.answer('提醒发给' + leader + '了。', null, { confirm: false }); }
    else if (r.act === 'talk') { mark(); nav('mcare'); XW.at(600, () => { const f = FOCUS_PEOPLE.find(x => x.who === r.who); ACT['mc-guide']({ dataset: { who: r.who, tag: f ? f.tag : '低绩效' } }); }); }
    else if (r.act === 'transfer') { DB.notify(TEAM3.leader, '借调返岗 · ' + r.who + '（试验班）借调已超 50 天，请确定返岗时间', '已发'); DB.notify(LAB.leader, '借调返岗 · ' + r.who + ' 返岗时间已向配电运维一班催问', '已发', true); mark(); XW.answer('催返岗发给' + TEAM3.leader + '了，' + LAB.leader + '同步知道。', null, { confirm: false }); }
    else { mark(); nav('structure'); }
  }
});

/* ---------- 员工关怀：面谈提纲 · 重点关注人员 · 文化活动管理 ---------- */
const MCAREPG = {
  cult() { const ov = LS.get('culture_dept', {}); return CULTURE_DEPT.concat(LS.get('culture_dept_add', [])).map((c, i) => Object.assign({ i }, c, ov[i] || {})); },
  cultHTML() { return '<div class="tbl"><table class="t"><tr><th>日期</th><th>类型</th><th>活动</th><th>范围</th><th>负责人</th><th>人数</th><th>状态</th><th></th></tr>' + this.cult().map(c => '<tr><td class="mono">' + h(c.d) + '</td><td><span class="tag ' + ({ 主题党日: 'c', 座谈会: 'c', 团建: 'v', 迎新会: 'v', 欢送会: '' }[c.kind] || '') + '">' + h(c.kind) + '</span></td><td><b>' + h(c.t) + '</b></td><td>' + h(c.team) + '</td><td>' + h(c.who) + '</td><td class="mono">' + c.n + '</td><td><span class="tag ' + (/已举办|已批/.test(c.st) ? 'ok' : /待/.test(c.st) ? 'w' : '') + '">' + h(c.st) + '</span></td><td>' + (c.st === '待审批' ? '<button class="s g" data-act="cd-approve" data-i="' + c.i + '">批准</button>' : c.st === '待通知' || c.st === '计划中' || c.st === '已批' ? '<button class="s g" data-act="cd-notify" data-i="' + c.i + '">发通知</button>' : '') + '</td></tr>').join('') + '</table></div>'; }
};
PAGES.mcare = {
  render() { const C = MCAREPG.cult(); return cmdHTML(['给王安写绩效面谈提纲', '新员工座谈会发通知', '长病的人有谁']) + pageHead('员工关怀', '团队关系维护：辅导面谈（绩效 / 关键事件 / 关怀）提纲与沟通要点 · 重点关注人员提醒 · 部门文化活动管理', '<button class="s" data-act="cd-add">新增活动</button>') +
      '<div class="grid2" style="grid-template-columns:1.4fr 1fr"><div class="card"><div class="h"><b>重点关注人员</b><span>长病 / 高绩效 / 低绩效 / 借调 / 新员工 · 三班组</span></div>' + FOCUS_PEOPLE.map(f => '<div class="focusrow"><span class="tag ' + ({ 长病: 'bad', 高绩效: 'ok', 低绩效: 'w', 新员工: 'c', 借调: 'v' }[f.tag]) + '">' + h(f.tag) + '</span><b data-act="st-person" data-who="' + f.who + '">' + h(f.who) + '</b><span class="note">' + h(f.team) + ' · ' + h(f.t) + '</span><p>' + h(f.do) + '</p><div class="bt"><button class="s" data-act="mc-guide" data-who="' + f.who + '" data-tag="' + f.tag + '">面谈提纲</button><button class="s g" data-act="mc-remind" data-who="' + f.who + '" data-team="' + h(f.team) + '">提醒班长</button></div></div>').join('') + '</div>' +
      '<div><div class="card"><div class="h"><b>面谈类型与沟通要点</b></div>' + Object.keys(TALK_GUIDES).map(k => '<details class="fold"><summary>' + h(k) + '</summary><div style="padding:4px 10px 8px;font-size:11.5px"><div><b>开场：</b>' + h(TALK_GUIDES[k].open) + '</div><ol style="margin:4px 0;padding-left:18px">' + TALK_GUIDES[k].items.map(x => '<li>' + h(x) + '</li>').join('') + '</ol><div class="note"><b>要点：</b>' + h(TALK_GUIDES[k].tips.join('；')) + '</div></div></details>').join('') + '</div><div class="card doc" id="mcdoc" hidden style="margin-top:10px"></div></div></div>' +
      '<div class="card"><div class="h"><b>部门文化活动管理</b><span>主题党日 · 座谈会 · 团建 · 迎新 / 欢送会 · 本年 ' + C.filter(c => /已举办/.test(c.st)).length + ' 场已办 · ' + C.filter(c => /计划|待/.test(c.st)).length + ' 场在办</span></div>' + MCAREPG.cultHTML() + '</div>'; },
  after() { CH.mount($('#main')); }
};
Object.assign(ACT, {
  'mc-guide'(el) { const who = el.dataset.who, tag = el.dataset.tag; const kind = /高绩效|低绩效/.test(tag) ? '绩效面谈' : /关键/.test(tag) ? '关键事件面谈' : '关怀面谈'; const g = TALK_GUIDES[kind]; const f = FOCUS_PEOPLE.find(x => x.who === who); const host = $('#mcdoc'); if (!host) { ensure('mcare', () => ACT['mc-guide'](el)); return; } host.hidden = false; host.scrollIntoView({ block: 'nearest' }); const who2 = f ? MGR.leaderOf(f.team) : '班长';
    MG.stream(host, ['面谈人：' + who2 + '（班长）· 对象：' + who + (f ? '（' + f.team + '，' + f.tag + '）' : '') + ' · 时间：本周内 · 地点：班组会议室', '开场：' + g.open].concat(g.items.map((it, i) => (i + 1) + '. ' + it), ['本人情况：' + (f ? f.t + '。建议：' + f.do : '见人员档案')], ['沟通要点：' + g.tips.join('；')]), { title: who + ' · ' + kind + '提纲', done() { host.insertAdjacentHTML('beforeend', '<div class="bt"><button data-act="mc-guide-send" data-who="' + who + '" data-kind="' + kind + '" data-to="' + h(who2) + '">发给' + h(who2) + '</button><button class="g" data-act="mc-guide-save" data-who="' + who + '" data-kind="' + kind + '">存入文稿中心</button></div>'); } }); },
  'mc-guide-save'(el) { MG.saveDoc('guide-' + el.dataset.who, el.dataset.who + ' ' + el.dataset.kind + '提纲', $('#mcdoc')); XW.answer('提纲存到文稿中心了。', null, { confirm: false }); },
  'mc-guide-send'(el) { MG.saveDoc('guide-' + el.dataset.who, el.dataset.who + ' ' + el.dataset.kind + '提纲', $('#mcdoc')); DB.notify(el.dataset.to, el.dataset.kind + '提纲 · ' + el.dataset.who + '：已生成，请本周内约谈并把结论写进谈心记录', '已发'); XW.answer('提纲发给' + el.dataset.to + '了，谈完的结论会回到谈心记录。', null, { confirm: false }); },
  'mc-remind'(el) { const f = FOCUS_PEOPLE.find(x => x.who === el.dataset.who); const leader = MGR.leaderOf(el.dataset.team); DB.notify(leader, '重点关注 · ' + f.who + '（' + f.tag + '）：' + f.t + '。' + f.do, '已发'); DB.log('员工关怀', '提醒 ' + leader + ' 关注 ' + f.who); XW.answer('提醒发给' + leader + '了。', null, { confirm: false }); },
  'cd-notify'(el) { const i = +el.dataset.i; const c = MCAREPG.cult().find(x => x.i === i); const ov = LS.get('culture_dept', {}); ov[i] = Object.assign(ov[i] || {}, { st: '已通知' }); LS.set('culture_dept', ov); MGR.teamOrder.forEach(t => DB.notify(MGR.leaderOf(t), '文化活动通知 · ' + c.d + ' ' + c.t + '，请统计参加人员', '已发', true)); DB.log('文化活动', c.t + ' 已通知三个班组'); render(); XW.fly('已通知三位班长'); XW.answer('"' + c.t + '"的通知发给三位班长了，人数统计回来后我更新到表里。', null, { confirm: false }); },
  'cd-approve'(el) { const i = +el.dataset.i; const c = MCAREPG.cult().find(x => x.i === i); const ov = LS.get('culture_dept', {}); ov[i] = Object.assign(ov[i] || {}, { st: '已批' }); LS.set('culture_dept', ov); DB.log('文化活动', c.t + ' 已批准'); render(); XW.answer('"' + c.t + '"批了，接下来点发通知。', null, { confirm: false }); },
  'cd-add'() { modal('<div class="t">新增文化活动</div><div class="jf"><label>类型</label><select id="cd-k"><option>主题党日</option><option>座谈会</option><option>团建</option><option>迎新会</option><option>欢送会</option></select><label>活动</label><input id="cd-t" placeholder="如 班长与青年员工座谈"><label>日期</label><input id="cd-d" value="2026-09-05"><label>负责人</label><input id="cd-w" value="陈国安"><label>预计人数</label><input id="cd-n" type="number" value="20"></div><div class="bt"><button data-act="cd-add-ok">保存</button></div>'); },
  'cd-add-ok'() { const t = ($('#cd-t') || {}).value || ''; if (t.trim().length < 2) { XW.answer('活动名称要写清楚。', null, { confirm: false }); return; } const a = LS.get('culture_dept_add', []); a.push({ d: $('#cd-d').value, kind: $('#cd-k').value, t: t.trim(), team: '三班组', st: '待审批', who: $('#cd-w').value, n: +$('#cd-n').value || 0 }); LS.set('culture_dept_add', a); DB.log('文化活动', '新增 ' + t); $('#modal').hidden = true; render(); XW.answer('加上了，状态待审批。', null, { confirm: false }); }
});

/* ---------- 分析参谋：综合分析报告 + 近五年业务量与人力配置趋势 ---------- */
PAGES.madvise = {
  TABS: [{ k: 'report', n: '综合分析报告' }, { k: 'trend', n: '近五年业务量与人力配置' }],
  render() { const s = S.sub || 'report'; const T = TREND5; const C = trendCalc(); const docs = LS.get('docs', {});
    return cmdHTML(['生成部门综合分析报告', '五年人均工作量涨了多少', '2027 年要不要补人']) + pageHead('分析参谋', '按部门业务指标综合分析 · 近三年 / 五年业务量与人力资源配置变化 · 供后续人力配置作参谋预警') + tabsHTML(this.TABS, s) +
      (s === 'trend' ? '<div class="grid4"><div class="card kpi"><span>业务量（工单）五年</span><b class="' + (C.jobsG > 30 ? 'bad' : 'w') + '">+' + C.jobsG + '%</b><em>' + T.jobs[0] + ' → ' + T.jobs[4] + '（2026 预计）</em></div><div class="card kpi"><span>在编人数五年</span><b>+' + C.headsG + '%</b><em>' + T.heads[0] + ' → ' + T.heads[4] + ' 人</em></div><div class="card kpi"><span>人均工单五年</span><b class="bad">+' + C.perG + '%</b><em>' + C.per[0] + ' → ' + C.per[4] + ' 单 / 人</em></div><div class="card kpi"><span>2027 预警</span><b class="bad">缺 ' + C.need + ' 人</b><em>按 2025 年人均负荷折算；技师及以上 ' + T.senior[0] + ' → ' + T.senior[4] + '</em></div></div>' +
        '<div class="grid2"><div class="card"><div class="h"><b>业务量</b><span>工单 · 缺陷 · 终端数</span></div>' + CH.mini.line([{ n: '工单', vals: T.jobs, c: CPAL[0], area: true }, { n: '终端数', vals: T.terms, c: CPAL[2] }, { n: '缺陷', vals: T.defects, c: CPAL[1] }], T.years, { h: 140 }) + CH.mini.legend([{ n: '工单', c: CPAL[0] }, { n: '终端数', c: CPAL[2] }, { n: '缺陷', c: CPAL[1] }]) + '</div><div class="card"><div class="h"><b>人力配置</b><span>人数 · 平均年龄 · 技师及以上</span></div>' + CH.mini.line([{ n: '在编人数', vals: T.heads, c: CPAL[4] }, { n: '平均年龄', vals: T.avgAge, c: CPAL[3] }, { n: '技师及以上', vals: T.senior, c: CPAL[5] }], T.years, { h: 140, max: 45 }) + CH.mini.legend([{ n: '在编人数', c: CPAL[4] }, { n: '平均年龄', c: CPAL[3] }, { n: '技师及以上', c: CPAL[5] }]) + '</div></div>' +
        '<div class="grid2" style="grid-template-columns:1fr 1.3fr"><div class="card"><div class="h"><b>人均工单</b><span>单 / 人 · 年</span></div>' + CH.mini.cols(T.years.map((y, i) => ({ n: y.replace(' 预计', ''), v: C.per[i], c: i === 4 ? CPAL[1] : CPAL[0] })), { labels: true, h: 130 }) + '<div class="tbl" style="margin-top:6px"><table class="t"><tr><th>班组</th>' + T.years.map(y => '<th>' + h(y.replace(' 预计', '')) + '</th>').join('') + '</tr>' + Object.keys(T.teams).map(n => '<tr><td>' + h(n) + '</td>' + T.teams[n].map(v => '<td class="mono">' + v + '</td>').join('') + '</tr>').join('') + '</table></div></div>' +
        '<div class="card"><div class="h"><b>人力资源配置参谋预警</b><span>由部门确认后使用</span></div><div class="advbox"><p>近五年部门工单 <b>+' + C.jobsG + '%</b>、终端数 <b>+' + C.termsG + '%</b>，在编人数只 <b>+' + C.headsG + '%</b>，人均工单从 ' + C.per[0] + ' 升到 ' + C.per[4] + '（<b>+' + C.perG + '%</b>）；平均年龄从 ' + T.avgAge[0] + ' 升到 ' + T.avgAge[4] + '。</p><p>按当前增速，2027 年人均工单约 <b>' + C.next + '</b>；要维持 2025 年的人均负荷，需增加 <b>' + C.need + '</b> 人；不全靠补人，则需把核心业务自主实施比例再提高约 8 个百分点（减少外委等待）并用跨班组柔性支援削峰。</p><p>建议：① 2027 年编制申请 2 人，优先配电运维一班（人均实操最低、近三年离职 2 人）；② 试验班 2029 年前有 2 名骨干进入退休窗口，2027 年起每年接收 1 名轮岗学员；③ 配电自动化班终端数五年翻 1.7 倍，先用跨班组柔性支援过 2026 年高峰，2027 年再评估定编。</p></div><div class="bt"><button data-act="ma-gen" data-k="hr">生成人力配置参谋报告</button></div></div></div>' +
        '<div class="card doc" id="madoc" hidden></div>'
      : '<div class="grid2" style="grid-template-columns:1fr 1.2fr"><div class="card"><div class="h"><b>综合分析报告</b><span>取数：考核指标 · 班组横向对比 · 结构对比 · 风险画像 · 星级建设 · 班长队伍</span></div><div class="jobs">' + [['指标', '年度指标 ' + goalsAll().length + ' 项：红 ' + goalsAll().filter(g => g.light === 'bad').length + ' · 黄 ' + goalsAll().filter(g => g.light === 'w').length + ' · 绿 ' + goalsAll().filter(g => g.light === 'ok').length], ['班组', '最忙 ' + compareAdvice().busy + ' · 最需关注 ' + STRUCPG.strength().filter(s => s.tag === '弱').map(s => s.n).join('、')], ['风险', riskAgg().length + ' 项，高 ' + riskAgg().filter(r => r.lv === '高').length], ['星级', TEAM.name + ' 初步评分 ' + buildScore().pct + '，必备条件缺 ' + buildScore().mustBad.length + ' 项'], ['梯队', '可接任后备 ' + leaderStat().ready + '，培养中 ' + leaderStat().training]].map(x => '<div><span style="white-space:normal;color:var(--ink)"><b>' + h(x[0]) + '</b>　' + h(x[1]) + '</span></div>').join('') + '</div><div class="bt"><button data-act="ma-gen" data-k="all">生成综合分析报告</button>' + (docs['m-all'] ? '<span class="tag ok">上次 ' + new Date(docs['m-all'].ts).toTimeString().slice(0, 5) + '</span>' : '') + '</div></div><div class="card doc" id="madoc"><div class="empty">点"生成综合分析报告"，报告逐段写在这里</div></div></div>'); },
  after() { CH.mount($('#main')); }
};
Object.assign(ACT, {
  'ma-gen'(el) { const k = el.dataset.k; const host = $('#madoc'); if (!host) return; host.hidden = false; host.scrollIntoView({ block: 'nearest' }); const G = goalsAll(); const bad = G.filter(g => g.light === 'bad'), w = G.filter(g => g.light === 'w'); const A = compareAdvice(); const R = riskAgg(); const B = buildScore(); const st = leaderStat(); const S3 = STRUCPG.strength(); const C = trendCalc(); const T = TREND5;
    const paras = k === 'hr' ? ['一、业务量变化：2022–2026 年部门工单 ' + T.jobs[0] + ' → ' + T.jobs[4] + '（+' + C.jobsG + '%），终端数 ' + T.terms[0] + ' → ' + T.terms[4] + '（+' + C.termsG + '%），缺陷 ' + T.defects[0] + ' → ' + T.defects[4] + '。', '二、人力配置变化：在编 ' + T.heads[0] + ' → ' + T.heads[4] + ' 人（+' + C.headsG + '%），平均年龄 ' + T.avgAge[0] + ' → ' + T.avgAge[4] + ' 岁，技师及以上 ' + T.senior[0] + ' → ' + T.senior[4] + ' 人；人均工单 ' + C.per[0] + ' → ' + C.per[4] + '（+' + C.perG + '%）。', '三、预警：按增速 2027 年人均工单约 ' + C.next + '；维持 2025 年人均负荷需增加 ' + C.need + ' 人，建议编制申请 2 人、其余靠自主实施比例与柔性支援消化。试验班平均 ' + teamStat('试验班').avgAge + ' 岁，2029 年前 2 名骨干进入退休窗口；配电运维一班近三年离职 2 人，人均实操最低。', '四、建议：① 2027 年编制申请 2 人，优先配电运维一班；② 试验班 2027 年起每年接收 1 名轮岗学员；③ 2026 年高峰用跨班组柔性支援（本周建议：' + A.idle + ' 借 ' + A.who + ' 到 ' + A.busy + '）；④ 核心业务自主实施比例每年提高 4 个百分点，减少外委等待。以上由部门确认后使用。']
      : ['一、考核指标（分管副总 / 主管 / 班长三个维度）：' + G.length + ' 项中红灯 ' + bad.length + ' 项（' + bad.map(g => g.n).join('、') + '），黄灯 ' + w.length + ' 项（' + w.map(g => g.n).join('、') + '）。时间进度 ' + YEAR_PCT + '%。', '二、班组横向对比：' + A.busy + '本周人均外勤最高（' + compareRows().find(r => r.k === 'load').num[A.busy] + ' 小时），' + A.idle + '最低，建议借 ' + A.who + ' 支援 3 天。人均核心技能实操量：' + MGR.teamOrder.map(t => t + ' ' + compareRows().find(r => r.k === 'cap').num[t]).join('、') + '。', '三、团队结构：' + S3.map(s => s.n + ' ' + s.tag).join('、') + '；' + STRUCPG.advice()[0].t + '。', '四、风险画像：' + R.length + ' 项，高风险 ' + R.filter(r => r.lv === '高').map(r => r.who + '（' + r.g + '）').join('、') + '；敏感岗位超轮岗期 ' + R.filter(r => r.g === '敏感岗位轮岗').length + ' 个。', '五、星级建设与梯队：' + TEAM.name + ' 初步评分 ' + B.pct + '（' + B.lv + '线），必备条件不满足 ' + B.mustBad.map(d => d.n).join('、') + '；班长后备可接任 ' + st.ready + ' 人、培养中 ' + st.training + ' 人，配电运维一班后备最薄。', '六、本周部署：① 督办红灯指标到责任班组；② 发起 ' + A.who + ' 跨班组调配；③ 敏感岗位轮岗提醒 ' + R.filter(r => r.g === '敏感岗位轮岗').map(r => r.who).join('、') + '；④ 长病与低绩效人员本周面谈。以上由部门确认后使用。'];
    MG.stream(host, paras, { title: TEAM.dept + (k === 'hr' ? ' 人力资源配置参谋报告' : ' 综合分析报告') + ' · ' + TODAY, done() { host.insertAdjacentHTML('beforeend', '<div class="bt"><button data-act="ma-save" data-k="' + k + '">存入文稿中心</button><button class="g" data-act="ma-send" data-k="' + k + '">发三位班长</button></div>'); } }); },
  'ma-save'(el) { MG.saveDoc('m-' + el.dataset.k, TEAM.dept + (el.dataset.k === 'hr' ? ' 人力资源配置参谋报告' : ' 综合分析报告'), $('#madoc')); XW.answer('存到文稿中心了。', null, { confirm: false }); },
  'ma-send'(el) { MG.saveDoc('m-' + el.dataset.k, TEAM.dept + (el.dataset.k === 'hr' ? ' 人力资源配置参谋报告' : ' 综合分析报告'), $('#madoc')); MGR.teamOrder.forEach(t => DB.notify(MGR.leaderOf(t), (el.dataset.k === 'hr' ? '人力资源配置参谋报告' : '部门综合分析报告') + ' 已发，请查看涉及本班组的部署', '已发', true)); XW.fly('已发三位班长'); XW.answer('发给三位班长了。', null, { confirm: false }); }
});
