/* ===== 班组长 · 班组管理六页（9/21 客户口径）：班组画像（荣誉标签 + 星级评价维度初步评分与建设差距）/ 班员画像（员工画像：综合画像 + 专业画像 + 技能矩阵 + 人才断层）/ 培养与梯队（师带徒 + 骨干培养）/ 绩效与激励 / 关怀与文化 / 分析参谋（队伍诊断 + 培养参谋）===== */
const MG = {
  light(cls, txt) { return '<i class="rag ' + cls + '"></i>' + (txt ? '<span class="ragt">' + h(txt) + '</span>' : ''); },
  bar(pct, cls) { return '<div class="dimbar ' + (cls || '') + '"><i style="width:' + Math.max(2, Math.min(100, pct)) + '%"></i></div>'; },
  genRadar(name, opt) { opt = opt || {}; const series = [{ n: name, vals: genOf(name), c: opt.c || CPAL[0] }]; if (opt.avg) series.push({ n: opt.avgN || '班组均值', vals: opt.avg, c: '#9aa1b8', dash: true }); return CH.mini.radar(GEN5.map(d => d.n), series, { max: 4, rings: 4, fmt: v => 'L' + v }); },
  proRadar(name, opt) { opt = opt || {}; const series = [{ n: name, vals: proOf(name), c: opt.c || CPAL[2] }]; if (opt.req) series.push({ n: '本岗级要求', vals: PRO9.map(() => opt.req), c: '#e5484d', dash: true }); if (opt.avg) series.push({ n: opt.avgN || '班组均值', vals: opt.avg, c: '#9aa1b8', dash: true }); return CH.mini.radar(PRO9.map(d => d.s), series, { max: 4, rings: 4, fmt: v => 'L' + v }); },
  portAvg(list) { const avg = (fn, len) => Array.from({ length: len }, (x, i) => +(list.reduce((s, p) => s + fn(p.n)[i], 0) / list.length).toFixed(1)); return { gen: avg(genOf, GEN5.length), pro: avg(proOf, PRO9.length) }; },
  planPush(who, t, why) { const plan = LS.get('plan', []); if (!plan.some(x => x.who === who && x.t === t)) { plan.push({ who, t, why: why || '', by: '班组管理', d: TODAY, st: '待办' }); LS.set('plan', plan); DB.log('班组计划', who + '：' + t); return true; } return false; },
  stream(host, paras, opt) { DOCGEN.stream(host, paras, opt); },
  saveDoc(key, title, host) { const docs = LS.get('docs', {}); docs[key] = { t: title, ts: Date.now(), body: host ? host.innerText : '' }; LS.set('docs', docs); DB.log('文稿', title + ' 已保存'); },
  kindTag(k) { return '<span class="tag ' + ({ 专家型: 'v', 骨干型: 'c', 基础型: '' }[k] || '') + '">' + h(k) + '</span>'; },
  starTag(s) { return '<span class="startag">' + '★'.repeat({ 五星班组: 5, 四星班组: 4, 三星班组: 3 }[s] || 2) + ' ' + h(s) + '</span>'; }
};

/* ---------- 班组画像：荣誉标签 + 星级评价维度初步评分 + 建设差距标识 ---------- */
const TEAMPG = {
  dimsHTML() { const D = buildDims(); const grp = ['必备条件', '通用部分', '专业部分', '加分'];
    return '<div class="tbl"><table class="t dims"><tr><th>目录</th><th>评价维度</th><th>标准分</th><th>初步得分</th><th style="min-width:120px">得分率</th><th>标识</th><th>差距摘要</th><th></th></tr>' + grp.map(g => D.filter(d => d.l1 === g).map((d, i) => '<tr class="' + (d.cls === 'bad' ? 'hl' : '') + '"><td class="note">' + (i === 0 ? h(g) : '') + '</td><td><b>' + h(d.n) + '</b></td><td class="mono">' + (d.pts || '—') + '</td><td class="mono">' + (d.pts ? d.scV : d.okV ? '满足' : '不满足') + '</td><td>' + MG.bar(d.pct, d.cls) + '</td><td>' + MG.light(d.cls, d.cls === 'ok' ? (d.pts ? '达标' : '满足') : d.cls === 'w' ? '接近' : '差距') + '</td><td class="note" style="max-width:300px">' + h(d.gapV || '—') + '</td><td><button class="s g" data-act="team-dim" data-k="' + d.k + '">差距明细</button></td></tr>').join('')).join('') + '</table></div>'; },
  fixList() { return buildDims().filter(d => d.cls !== 'ok').sort((a, b) => ((b.pts || 0) - (b.scV || 0)) - ((a.pts || 0) - (a.scV || 0))); },
  fixHTML() { const L = this.fixList(); const done = LS.get('team_fix', {}); return L.map(d => '<div class="fixrow"><div>' + MG.light(d.cls) + '<b>' + h(d.n) + '</b><span class="note">' + (d.pts ? ' 差 ' + (d.pts - d.scV) + ' 分' : ' 必备条件') + '</span><p>' + h(d.fix || '') + '</p></div><div class="bt">' + (done[d.k] ? '<span class="tag ok">已排进计划 ' + h(done[d.k]) + '</span>' : '<button class="s" data-act="team-fix" data-k="' + d.k + '">排进班组计划</button>') + '</div></div>').join(''); }
};
PAGES.team = {
  render() { const T = TEAM_TAGS[TEAM.name]; const B = buildScore(); const must = B.dims.filter(d => d.must); const okMust = must.filter(d => d.okV).length; const gen = B.dims.filter(d => d.l1 === '通用部分'), pro = B.dims.filter(d => d.l1 === '专业部分'), add = B.dims.filter(d => d.l1 === '加分'); const sum = l => l.reduce((s, d) => s + d.scV, 0), full = l => l.reduce((s, d) => s + d.pts, 0);
    return cmdHTML(['离五星还差什么', '党建水平怎么补', '核心能力建设差距明细', '把提升建议全部排进计划']) + pageHead('班组画像', TEAM.full + ' · 荣誉标签 · 星级班组评价维度初步评分 · 建设差距', '<button class="s g" data-act="nav" data-to="people">人员档案</button><button class="s g" data-act="nav" data-to="star">对标分册原文</button>') +
      '<div class="grid2" style="grid-template-columns:1fr 1.3fr"><div class="card"><div class="h"><b>班组荣誉标签</b><span>局级人才与荣誉台账</span></div><div class="honors"><div class="hstar" data-act="team-honor" data-k="star">' + MG.starTag(T.star) + '<span class="note">' + h(T.starD) + '</span></div>' + T.honors.map(x => '<div class="hitem" data-act="team-honor" data-k="' + h(x[0]) + '"><b>' + h(x[0]) + '</b><span class="note">' + h(x[1]) + ' · ' + h(x[2]) + '</span></div>').join('') + '</div><div class="kindrow" data-act="team-kind"><span class="note">班组特色</span>' + MG.kindTag(T.kind) + '<span class="note">' + h(T.why) + '</span></div></div>' +
      '<div class="card"><div class="h"><b>建设差距标识</b><span>按《星级班组评价标准》维度初步评分 · 由班组长确认后使用</span></div><div class="scorerow"><div class="big"><b>' + B.pct + '</b><span>初步评分 / 100</span></div><div class="big"><b>' + h(B.lv) + '</b><span>初步判定' + (B.lv !== T.star.replace('班组', '') ? '（现为' + h(T.star) + '）' : '') + '</span></div><div class="big ' + (B.gapTo5 ? 'w' : 'ok') + '"><b>' + (B.gapTo5 || 0) + '</b><span>距五星线 90 分</span></div><div class="big ' + (B.mustBad.length ? 'bad' : 'ok') + '"><b>' + okMust + '/' + must.length + '</b><span>必备条件满足</span></div></div>' +
      '<div class="grid3" style="margin-top:8px"><div class="mini3"><span>通用部分</span><b>' + sum(gen) + '/' + full(gen) + '</b>' + MG.bar(sum(gen) / full(gen) * 100) + '</div><div class="mini3"><span>专业部分</span><b>' + sum(pro) + '/' + full(pro) + '</b>' + MG.bar(sum(pro) / full(pro) * 100) + '</div><div class="mini3"><span>加分项</span><b>' + sum(add) + '/' + full(add) + '</b>' + MG.bar(sum(add) / full(add) * 100) + '</div></div>' + (B.mustBad.length ? '<div class="alert bad" style="margin-top:8px">' + MG.light('bad') + '必备条件不满足：' + B.mustBad.map(d => '<b>' + h(d.n) + '</b>').join('、') + ' — 五星一票否决，先补这两项</div>' : '') + '</div></div>' +
      '<div class="card"><div class="h"><b>星级评价维度 · 初步评分与差距</b><span>标准分取自分册；现状取本班台账与班务记录；颜色：绿 ≥ 90% · 黄 75–89% · 红 < 75%</span></div>' + TEAMPG.dimsHTML() + '</div>' +
      '<div class="card"><div class="h"><b>提升建议</b><span>按差距分从大到小</span><div class="r"><button class="s" data-act="team-fixall">全部排进班组计划</button></div></div><div id="fixlist">' + TEAMPG.fixHTML() + '</div></div>'; },
  after() { CH.mount($('#main')); if (!S.briefed) { S.briefed = true; const B = buildScore(); XW.at(400, () => XW.answer('班组画像按星级班组评价标准的维度重新算过了：初步评分 ' + B.pct + '，' + B.lv + '线；必备条件有 ' + B.mustBad.length + ' 项不满足，通用部分差得最多的是' + TEAMPG.fixList().filter(d => d.pts)[0].n + '。每一行都能点差距明细，提升建议可以直接排进班组计划。', null, { confirm: false })); } }
};
Object.assign(ACT, {
  'team-dim'(el) { const d = buildDims().find(x => x.k === el.dataset.k); if (!d) return; modal('<div class="t">' + h(d.l1) + ' › ' + h(d.n) + '　' + MG.light(d.cls, d.cls === 'ok' ? '达标' : d.cls === 'w' ? '接近' : '差距') + '</div><div class="tbl"><table class="t"><tr><th style="width:110px">建设标准</th><td>' + h(d.std) + '</td></tr><tr><th>标准分 / 初步得分</th><td class="mono">' + (d.pts ? d.pts + ' / ' + d.scV + '（' + d.pct + '%）' : '必备条件 · ' + (d.okV ? '满足' : '不满足')) + '</td></tr><tr><th>本班现状</th><td>' + h(d.nowV || d.gapV || '按台账对照') + '</td></tr><tr><th>差距</th><td>' + h(d.gapV || '无') + '</td></tr><tr><th>提升建议</th><td>' + h(d.fix || '保持') + '</td></tr><tr><th>查评路径</th><td class="note">' + h(d.path) + '</td></tr></table></div>' + (d.fix ? '<div class="bt"><button data-act="team-fix" data-k="' + d.k + '">排进班组计划</button><button class="g" data-act="nav" data-to="ledger">看台账</button></div>' : '')); XW.answer(d.n + '：' + (d.gapV || '达标') + (d.fix ? '。建议：' + d.fix : ''), null, { confirm: false, speak: false }); },
  'team-fix'(el) { const d = buildDims().find(x => x.k === el.dataset.k); if (!d) return; const done = LS.get('team_fix', {}); done[d.k] = DB.now(); LS.set('team_fix', done); MG.planPush('班组', d.n + '：' + d.fix, '星级建设差距'); DB.notify('韩雪', '星级建设差距整改 · ' + d.n + '：' + d.fix, '已发'); $('#modal').hidden = true; if ($('#fixlist')) $('#fixlist').innerHTML = TEAMPG.fixHTML(); XW.answer('排进班组计划了：' + d.n + ' — ' + d.fix + '。同时发给韩雪一条。', null, { confirm: false }); },
  'team-fixall'() { const L = TEAMPG.fixList(); const done = LS.get('team_fix', {}); let n = 0; L.forEach(d => { if (!done[d.k] && d.fix) { done[d.k] = DB.now(); MG.planPush('班组', d.n + '：' + d.fix, '星级建设差距'); n++; } }); LS.set('team_fix', done); if ($('#fixlist')) $('#fixlist').innerHTML = TEAMPG.fixHTML(); XW.fly('已排进计划 ' + n + ' 条'); XW.answer(n ? n + ' 条提升建议都排进班组计划了，培养与梯队、关怀与文化两页里对应的事会带上这个来源。' : '都已经在计划里了。', null, { confirm: false }); },
  'team-honor'(el) { const k = el.dataset.k; XW.answer(k === 'star' ? TEAM.name + '现为' + TEAM_TAGS[TEAM.name].star + '，' + TEAM_TAGS[TEAM.name].starD + '；按分册维度初步评分 ' + buildScore().pct + '，复评时间取近两年。' : '"' + k + '"来自荣誉台账，评价周期内有效，可在台账中心的荣誉表里核对。', null, { confirm: false }); },
  'team-kind'() { XW.answer('班组特色标签按三条规则判：' + KIND_RULE.map(r => r[0] + '＝' + r[1]).join('；') + '。本班' + TEAM_TAGS[TEAM.name].why + '，判为' + TEAM_TAGS[TEAM.name].kind + '。', null, { confirm: false }); }
});

/* ---------- 班员画像：员工画像（综合画像 + 专业画像）+ 技能矩阵 + ★模块断层风险 ---------- */
const SKILLPG = {
  cur: null,
  who() { return this.cur && P[this.cur] ? this.cur : '韩雪'; },
  avg() { return MG.portAvg(PEOPLE); },
  /* 员工画像：综合画像（通用素质模型 5 项）+ 专业画像（岗位说明书 9 项），点人切换，点某一项看定义、分级与本班排序 */
  rowCls(kind, v, req) { return kind === 'gen' ? (v >= 3 ? 'ok' : v <= 1 ? 'w' : '') : (v < req ? 'w' : v > req ? 'ok' : ''); },
  portHTML(n, opt) { opt = opt || {}; const p = personAny(n); const team = teamOfPerson(n) || TEAM.name; const list = opt.list || PEOPLE; const avg = MG.portAvg(list); const g = genOf(n), pr = proOf(n), req = proReq(p); const top = portTop(n), low = portLow(n); const act = opt.act || 'sk-dim';
    const row = (kind, d, i, v, a) => '<div data-act="' + act + '" data-g="' + kind + '" data-i="' + i + '" data-who="' + h(n) + '" style="cursor:pointer"><span title="' + h(d.d || d.sub.join('、')) + '">' + h(kind === 'gen' ? d.n : d.s) + '</span>' + MG.bar(v / 4 * 100, this.rowCls(kind, v, req)) + '<b class="mono">L' + v + '</b><i class="note">' + h(lvName(kind, i, v)) + ' · 均值 ' + a + (kind === 'pro' && v < req ? ' · <em class="bad">未到位</em>' : '') + '</i></div>';
    return '<div class="port2"><div class="portcol"><div class="ph3"><b>综合画像</b><span>通用素质模型 · L1–L4</span></div>' + MG.genRadar(n, { avg: avg.gen, avgN: opt.avgN }) + CH.mini.legend([{ n: n }, { n: opt.avgN || '本班均值', c: '#9aa1b8' }]) + '<div class="sixrows">' + GEN5.map((d, i) => row('gen', d, i, g[i], avg.gen[i])).join('') + '</div></div>' +
      '<div class="portcol"><div class="ph3"><b>专业画像</b><span>岗位说明书 · 本岗级要求 L' + req + '（' + PRO_LV[req - 1] + '）</span></div>' + MG.proRadar(n, { req }) + CH.mini.legend([{ n: n, c: CPAL[2] }, { n: '本岗级要求', c: '#e5484d' }]) + '<div class="sixrows">' + PRO9.map((d, i) => row('pro', d, i, pr[i], avg.pro[i])).join('') + '</div></div></div>' +
      '<div class="hexsum"><b style="color:var(--ok)">优势特长：</b>' + top.map(x => h(x[0]) + ' L' + x[1]).join('、') + '　<b style="color:var(--warn)">可提升：</b>' + h(low[0]) + ' L' + low[1] + (proGap(n).length ? '　<b style="color:var(--bad)">专业未到位 ' + proGap(n).length + ' 项</b>' : '') + '</div>'; },
  hexHTML() {
    const n = this.who(), p = P[n]; const s9 = skill9Of(p), pe = postEvalOf(p);
    return '<div class="hexwrap1"><div class="hexhead"><b>' + h(n) + '</b><span class="note">' + h(p.post) + ' · ' + p.age + ' 岁 · 工龄 ' + p.yrs + ' 年 · ' + h(skillLvOf(n)) + (STAR_ENG[n] ? ' · ' + h(STAR_ENG[n]) : '') + (EXPERTS[n] ? ' · ' + h(EXPERTS[n]) : '') + ' · 岗评' + h(pe.concl || '待评') + ' · ' + h(authLvName(p)) + '核心业务自主实施率 ' + s9.rate + '%</span></div>' + this.portHTML(n) +
      '<div class="bt"><button class="s" data-act="sk-plan" data-who="' + h(n) + '">按短板排培养任务</button><button class="s g" data-act="sk-talk" data-who="' + h(n) + '">写进面谈提纲</button><button class="s g" data-act="sk-person" data-who="' + h(n) + '">人员档案</button><span class="cf">由班组长确认后使用</span></div></div>' +
      '<div class="legend-note">颜色说明：综合画像 绿 = L3 及以上，蓝 = L2，黄 = L1；专业画像 绿 = 高于本岗级要求，蓝 = 达到要求，黄 = 低于要求（标"未到位"）。雷达图实线为本人，灰色虚线为本班均值，红色虚线为本岗级要求。等级依据来自台账，点某一项看定义、分级描述和本班排序。</div>';
  },
  matrix() { return '<div class="tbl"><table class="t skm"><tr><th>姓名</th><th>岗位</th><th>岗评结论</th><th>职业技能等级</th><th>星级工程师</th><th>专家</th><th>证书</th><th style="min-width:170px">作业授权 · 本岗级★模块</th></tr>' + PEOPLE.map(p => { const pe = postEvalOf(p); const s9 = skill9Of(p); return '<tr data-act="sk-pick" data-who="' + p.n + '" class="' + (SKILLPG.who() === p.n ? 'on' : '') + '" style="cursor:pointer"><td><b>' + h(p.n) + '</b></td><td class="note">' + h(p.post) + '</td><td><span class="tag ' + (/胜任$/.test(pe.concl || '') ? 'ok' : /基本/.test(pe.concl || '') ? 'w' : 'bad') + '">' + h(pe.concl || '待评') + '</span></td><td>' + h(skillLvOf(p.n)) + '</td><td>' + (STAR_ENG[p.n] ? '<span class="tag v">' + h(STAR_ENG[p.n]) + '</span>' : '<span class="note">—</span>') + '</td><td>' + (EXPERTS[p.n] ? '<span class="tag v" title="' + h(EXPERTS[p.n]) + '">' + h(EXPERTS[p.n].replace(/（.*$/, '')) + '</span>' : '<span class="note">—</span>') + '</td><td class="mono">' + p.cert.length + '/6</td><td><div class="aurow">' + MG.bar(s9.rate, s9.rate >= 80 ? 'ok' : s9.rate < 50 ? 'bad' : 'w') + '<span class="mono">' + s9.mustA + '/' + s9.mustN + ' · ' + s9.rate + '%</span></div><span class="note">' + h(authLvName(p)) + (s9.mustB ? ' · 培训中 ' + s9.mustB : '') + '</span></td></tr>'; }).join('') + '</table></div>'; },
  /* ★模块断层风险统一由授权认证页计算 */
  gaps() { return AUTHPG.gaps().map(g => Object.assign({}, g, { why: g.a.length <= 2 ? '已授权仅 ' + g.a.length + ' 人' : g.young >= 35 && g.a.length <= 4 ? '已授权 ' + g.a.length + ' 人全部 35 岁以上' : g.a.length <= 4 ? '已授权 ' + g.a.length + ' 人，无冗余' : '' })); }
};
PAGES.skills = {
  render() { const G = SKILLPG.gaps(); const hi = G.filter(g => g.risk === '高'), mid = G.filter(g => g.risk === '中'); const lv = {}; PEOPLE.forEach(p => { const l = skillLvOf(p.n); lv[l] = (lv[l] || 0) + 1; }); const pe = PEOPLE.map(postEvalOf); const peOK = pe.filter(x => /胜任$/.test(x.concl || '')).length;
    return cmdHTML(['韩雪的员工画像', '本班谁的安全意识最弱', '哪些★模块只有一两个人授权', '把高风险模块都排带教']) + pageHead('班员画像', '员工画像（综合画像 + 专业画像） · 岗评 · 职业技能等级 · 星级工程师 · 专家 · 作业授权 · 核心业务自主实施率', '<button class="s g" data-act="nav" data-to="auth">作业授权认证表</button>') +
      '<div class="grid4"><div class="card kpi"><span>核心业务自主实施率</span><b class="' + (authRate() >= 80 ? 'g' : authRate() >= 60 ? 'w' : 'bad') + '">' + authRate() + '%</b><em>已授权★模块 ÷ 本岗级应授权★模块</em></div><div class="card kpi"><span>★模块断层风险 高 / 中</span><b class="bad">' + hi.length + ' / ' + mid.length + '</b><em>' + h(hi.map(g => g.s.k + ' ' + g.s.n).join('、') || '无') + '</em></div><div class="card kpi"><span>岗评胜任</span><b>' + peOK + '/12</b><em>其余为基本胜任或待提升</em></div><div class="card kpi"><span>技师及以上 / 高级工</span><b>' + ((lv['技师'] || 0) + (lv['高级技师'] || 0)) + ' / ' + (lv['高级工'] || 0) + '</b><em>星级工程师 ' + PEOPLE.filter(p => STAR_ENG[p.n]).length + ' 人 · 专家候选 ' + PEOPLE.filter(p => EXPERTS[p.n]).length + ' 人</em></div></div>' +
      '<div class="card"><div class="h"><b>员工画像 · 综合画像 + 专业画像</b><span>综合画像取通用素质模型 5 项，专业画像取岗位说明书 9 项二级业务　点下方名单任一人切换</span></div>' + SKILLPG.hexHTML() + '</div>' +
      '<div class="card"><div class="h"><b>技能矩阵 · 12 人</b><span>点一行看这个人的员工画像</span></div>' + SKILLPG.matrix() + '</div>' +
      '<div class="grid2"><div class="card"><div class="h"><b>核心业务自主实施率 · 12 人</b><span>虚线 = 80%　点一人看还差哪些★模块</span></div>' + CH.mini.bars(PEOPLE.map(p => { const x = skill9Of(p); return { n: p.n, v: x.rate, c: x.rate >= 80 ? SEM.ok : x.rate < 50 ? '#e5484d' : '#d97706', act: 'au-person', who: p.n, txt: x.mustA + '/' + x.mustN + ' · ' + x.rate + '%', tip: authLvName(p) }; }), { x0: 52, limit: 80, max: 100 }) + '<div class="legend-note">颜色说明：绿 = 自主实施率 ≥ 80%；黄 = 50%–79%；红 = 低于 50%。分母按本人岗级（高 / 中 / 初级作业员）的★模块数。</div></div>' +
      '<div class="card"><div class="h"><b>职业技能等级结构</b><span>12 人按职业技能等级分布</span></div>' + CH.mini.donut(SKILL_LADDER.filter(l => lv[l]).map((l, i) => ({ k: l, v: lv[l], c: RAMP[Math.min(5, i + 1)] })), { sub: '人' }) + '</div></div>' +
      '<div class="card"><div class="h"><b>人才断层风险 · ★模块</b><span>已授权 ≤ 2 人，或 ≤ 4 人且全部 35 岁以上为高；≤ 4 人为中</span><div class="r"><button class="s" data-act="sk-teachall">高风险全部排带教取证</button><button class="s g" data-act="nav" data-to="auth" data-sub="gap">全部★模块</button></div></div>' + AUTHPG.gapHTML(hi.concat(mid)) + '<div class="legend-note">颜色说明：红灯 = 断层风险高；黄灯 = 断层风险中。绿标签为已授权人员，黄标签为培训中人员；整行底色标出高风险模块。</div></div>'; },
  after() { CH.mount($('#main')); }
};
Object.assign(ACT, {
  'sk-person'(el) { ensure('people', () => PEOPLEPG.show(el.dataset.who)); },
  'sk-pick'(el) { SKILLPG.cur = el.dataset.who; if ($('#modal')) $('#modal').hidden = true; if (S.page !== 'skills') { nav('skills'); return; } render(); const n = SKILLPG.who(); const t = portTop(n), low = portLow(n), gap = proGap(n); XW.answer(n + '的员工画像：强在' + t.map(x => x[0] + '（L' + x[1] + '）').join('、') + '；' + low[0] + '（L' + low[1] + '）是下一步要补的' + (gap.length ? '，专业画像有 ' + gap.length + ' 项没到本岗级要求' : '') + '。综合画像按通用素质模型，专业画像按岗位说明书的二级业务，等级依据都指到台账。', null, { confirm: false, speak: false }); },
  'sk-dim'(el) { const kind = el.dataset.g === 'pro' ? 'pro' : 'gen'; const i = +el.dataset.i; const d = kind === 'gen' ? GEN5[i] : PRO9[i]; const fn = kind === 'gen' ? genOf : proOf; const who = el.dataset.who || SKILLPG.who(); const team = teamOfPerson(who) || TEAM.name; const L = team === TEAM.name ? PEOPLE : teamPeople(team); const rows = L.map(p => ({ p, v: fn(p.n)[i] })).sort((a, b) => b.v - a.v); const avg = MG.portAvg(L)[kind][i]; const pick = team === TEAM.name && S.page !== 'staff' ? 'sk-pick' : 'st-person';
    const lvs = kind === 'gen' ? d.lv : PRO_LV;
    modal('<div class="t">' + (kind === 'gen' ? '综合画像' : '专业画像') + ' · ' + h(d.n) + ' · ' + h(team) + ' ' + L.length + ' 人排序</div>' +
      '<div class="note" style="margin-bottom:6px">' + (kind === 'gen' ? '定义（' + h(PORT_GEN_SRC) + '）：' + h(d.d) : h(d.l1) + ' · 三级业务：' + h(d.sub.join('、')) + '<br>到位标准：' + h(d.std)) + '</div>' +
      '<div class="lvline">' + lvs.map((x, k) => '<span><b>L' + (k + 1) + '</b> ' + h(x) + '</span>').join('') + '</div>' +
      '<div class="note" style="margin:6px 0 8px">依据：' + h(d.ev) + '　' + (team === TEAM.name ? '本班' : team) + '均值 L' + avg + '　评价结论由' + (role() === 'manager' ? '部门' : '班组长') + '确认后使用</div>' +
      '<div class="tbl"><table class="t"><tr><th>排序</th><th>姓名</th><th>岗位</th><th style="width:160px">' + h(kind === 'gen' ? d.n : d.s) + '</th><th>对均值</th>' + (kind === 'pro' ? '<th>本岗级要求</th>' : '') + '<th></th></tr>' +
      rows.map((r, j) => { const req = proReq(r.p); return '<tr class="' + (r.p.n === who ? 'hl' : '') + '"><td class="mono">' + (j + 1) + '</td><td><b>' + h(r.p.n) + '</b></td><td class="note">' + h(r.p.post) + '</td><td class="rk">' + MG.bar(r.v / 4 * 100, SKILLPG.rowCls(kind, r.v, req)) + '<span class="mono">L' + r.v + ' ' + h(lvName(kind, i, r.v)) + '</span></td><td class="mono ' + (r.v >= avg ? 'g' : 'b') + '">' + (r.v >= avg ? '+' : '') + (+(r.v - avg).toFixed(1)) + '</td>' + (kind === 'pro' ? '<td>' + (r.v >= req ? '<span class="tag ok">L' + req + ' 到位</span>' : '<span class="tag w">L' + req + ' 未到位</span>') + '</td>' : '') + '<td><button class="s g" data-act="' + pick + '" data-who="' + h(r.p.n) + '">看画像</button></td></tr>'; }).join('') + '</table></div>' +
      '<div class="legend-note">颜色说明：' + (kind === 'gen' ? '绿 = L3 及以上，蓝 = L2，黄 = L1' : '绿 = 高于本岗级要求，蓝 = 达到要求，黄 = 低于要求') + '；"对均值"绿色为高于或等于本班均值，红色为低于。</div>');
    XW.answer(d.n + '这一项' + (team === TEAM.name ? '本班' : team) + '最强的是' + rows[0].p.n + '（L' + rows[0].v + '），最弱的是' + rows[rows.length - 1].p.n + '（L' + rows[rows.length - 1].v + '），均值 L' + avg + '。', null, { confirm: false, speak: false }); },
  'sk-plan'(el) { const n = el.dataset.who; const low = portLow(n);
    const MAP = { 忠诚执行: '牵头一项上级交办事项并按期闭环', 不断求进: '本季度补齐学时并申请一个授权模块', 安全意识: '主讲一次班前会风险交底', 客户导向: '跟一次抢修复电并回访客户', 沟通协作: '牵头一次跨班组协同并记录', 抢修管理: '跟一次中压故障急修，独立完成故障排查记录', 设备隐患管理: '负责一处隐患的临时措施与整改跟踪', 设备缺陷管理: '独立完成一次消缺并做验收评价', 操作管理: '在监护下完成两次中压操作', 巡视管理: '参加一次特殊巡视并做红外测温', 维护管理: '参加一次保供电特殊维护', '作业文件管理（两书、两票）': '起草一张工作票和一份施工方案，由班长审核', 安全工器具及生产机具管理: '负责一个月工器具检测与领用登记', 作业现场管理: '担任一次工作负责人（由班长监护）' };
    const t = low[0] + '：' + (MAP[low[0]] || '跟班实操一次并由师傅签字');
    if (MG.planPush(n, t, '画像短板')) { const avg = SKILLPG.avg()[low[2]][low[3]]; DB.notify(n, '培养任务 · ' + t, '已发'); XW.answer('给' + n + '排了：' + t + '。这一项' + (low[2] === 'pro' ? '（专业画像）' : '（综合画像）') + '现在 L' + low[1] + '，本班均值 L' + avg + '，培养与梯队页能看到。', null, { confirm: false }); }
    else XW.answer('这条已经在计划里了。', null, { confirm: false, speak: false }); },
  'sk-talk'(el) { const n = el.dataset.who; const top = portTop(n); const low = portLow(n);
    const f = { who: n, team: TEAM.name, tag: P[n] && /学员/.test(P[n].post) ? '新员工' : '高绩效', t: '员工画像：强在' + top.map(x => x[0]).join('、') + '，' + low[0] + '偏弱（L' + low[1] + '，本班均值 L' + SKILLPG.avg()[low[2]][low[3]] + '）', do: '谈' + low[0] + '怎么补：给一件具体的事、给时间节点、约回访' };
    const i = FOCUS_PEOPLE.findIndex(x => x.who === n); if (i >= 0) FOCUS_PEOPLE[i] = Object.assign({}, FOCUS_PEOPLE[i], f); else FOCUS_PEOPLE.push(f);
    S.pending = () => ACT['focus-guide']({ dataset: { who: n, tag: f.tag } }); nav('care'); },
  'sk-teachall'() { ACT['au-teachall'](); },
});

/* ---------- 培养与梯队：师带徒 + 骨干培养计划 ---------- */
const GROWPG = {
  mentees() { return MENTORS.map(m => Object.assign({ m: m.m, s: m.s, since: m.since, focus: m.focus }, MENTEE[m.s] || {})).concat(Object.keys(MENTEE).filter(n => !MENTORS.some(m => m.s === n)).map(n => Object.assign({ m: '待定', s: n, since: '—', focus: '—' }, MENTEE[n]))); },
  menteeHTML() { const plan = LS.get('plan', []); return this.mentees().map(x => { const p = P[x.s]; const hs = SCORE_HIST[x.s] || []; const last = hs[hs.length - 1]; return '<div class="mcard"><div class="mh"><b data-act="sk-person" data-who="' + x.s + '">' + h(x.s) + '</b><span class="tag ' + (x.stage === '新员工' ? 'c' : '') + '">' + h(x.stage) + '</span><span class="note">' + h(p.post) + ' · 入职 ' + p.yrs + ' 年</span><span class="note" style="margin-left:auto">师傅 <b data-act="sk-person" data-who="' + x.m + '">' + h(x.m) + '</b> · 自 ' + h(x.since) + ' · ' + h(x.focus) + '</span></div><div class="mrow"><div><span>培训</span><b>' + x.train + '</b><em>学时 / 年度 60</em>' + MG.bar(x.train / 60 * 100, x.train >= 36 ? 'ok' : 'w') + '</div><div><span>项目参与</span><b>' + x.proj + '</b><em>' + h(x.lastProj) + '</em></div><div><span>竞赛</span><b>' + x.contest + '</b><em>' + (x.contest ? '局级竞赛 ' + x.contest + ' 次' : '未参加') + '</em></div><div><span>理论最近</span><b class="' + (x.theory < 60 ? 'bad' : '') + '">' + x.theory + '</b><em>' + h(last ? last.t : '') + '</em></div><div><span>资质</span><b class="note" style="font-size:11px">' + h(x.cert) + '</b></div></div><div class="bt"><button class="s" data-act="grow-task" data-who="' + x.s + '">排带教任务</button><button class="s g" data-act="grow-remind" data-who="' + x.s + '" data-m="' + x.m + '">提醒师傅</button><button class="s g" data-act="rec-row" data-who="' + x.s + '">看成绩</button>' + (plan.filter(q => q.who === x.s).length ? '<span class="note">计划中 ' + plan.filter(q => q.who === x.s).length + ' 项</span>' : '') + '</div></div>'; }).join(''); },
  backboneHTML() { const done = LS.get('backbone', {}); return BACKBONE.map((b, i) => { const d = done[b.who] != null ? done[b.who] : b.done; return '<div class="bbrow"><div class="bbh"><b data-act="sk-person" data-who="' + b.who + '">' + h(b.who) + '</b><span class="note">' + h(b.now) + '</span><span class="arrow">→</span><span class="tag v">' + h(b.next) + '</span><span class="note">' + h(b.when) + '</span></div><ul class="bbitems">' + b.items.map((it, j) => '<li class="' + (j < d ? 'done' : '') + '">' + h(it) + '</li>').join('') + '</ul><div class="bt"><span class="note">进度 ' + d + '/' + b.items.length + '</span>' + (d < b.items.length ? '<button class="s g" data-act="grow-bb" data-i="' + i + '">记一项完成</button>' : '<span class="tag ok">条件齐</span>') + '<button class="s g" data-act="grow-bb-send" data-i="' + i + '">发给本人</button></div></div>'; }).join(''); }
};
PAGES.grow = {
  render() { const M = GROWPG.mentees(); const newN = M.filter(x => x.stage === '新员工').length; const stars = PEOPLE.filter(p => STAR_ENG[p.n]); const lad = [{ k: '局级专家候选', v: PEOPLE.filter(p => EXPERTS[p.n]).length }, { k: '三星工程师', v: stars.filter(p => /三星/.test(STAR_ENG[p.n])).length }, { k: '二星工程师', v: stars.filter(p => /二星/.test(STAR_ENG[p.n])).length }, { k: '一星工程师', v: stars.filter(p => /一星/.test(STAR_ENG[p.n])).length }, { k: '骨干培养中', v: BACKBONE.length }];
    return cmdHTML(['刘一鸣带得怎么样', '骨干培养计划谁最接近申报', '给周明排一次终端调试带教']) + pageHead('培养与梯队', '师带徒（新员工 ' + newN + ' · 次新员工 ' + (M.length - newN) + '）· 骨干培养计划 ' + BACKBONE.length + ' 人 · 星级工程师与专家梯队', '<button class="s g" data-act="nav" data-to="train" data-sub="write">考评定级与实操量回写</button><button class="s g" data-act="nav" data-to="train" data-sub="plan">年度培训计划</button>') +
      '<div class="card"><div class="h"><b>师带徒 · 新员工与次新员工培养</b><span>培训学时 · 项目参与 · 竞赛 · 资质 · 理论成绩</span></div><div class="mlist">' + GROWPG.menteeHTML() + '</div></div>' +
      '<div class="grid2" style="grid-template-columns:1.5fr 1fr"><div class="card"><div class="h"><b>骨干培养计划 · 星级工程师与专家梯队</b><span>评聘条件来自《技术技能人才评聘管理办法》</span></div>' + GROWPG.backboneHTML() + '</div><div><div class="card"><div class="h"><b>梯队</b><span>本班</span></div>' + CH.mini.funnel(lad) + '</div><div class="card" style="margin-top:10px"><div class="h"><b>近四季度模块等级变化</b><span>三名徒弟</span></div>' + CH.mini.line(['刘一鸣', '陈浩', '周明'].map((n, i) => ({ n, vals: LEVEL_HIST[n].map(q => +(q.reduce((s, x) => s + x, 0) / q.length).toFixed(2)), c: CPAL[i] })), QUARTERS, { max: 4, h: 120 }) + CH.mini.legend(['刘一鸣', '陈浩', '周明'].map((n, i) => ({ n, c: CPAL[i] }))) + '</div></div></div>'; },
  after() { CH.mount($('#main')); }
};
Object.assign(ACT, {
  'grow-task'(el) { const n = el.dataset.who; const x = MENTEE[n]; const m = MENTORS.find(q => q.s === n); const s9 = skill9Of(P[n]); let bi = s9.q.findIndex((q, i) => q === 'B' && s9.must[i]); if (bi < 0) bi = s9.q.findIndex((q, i) => q !== 'A' && s9.must[i]); if (bi < 0) bi = s9.q.indexOf('B'); const sk = bi >= 0 ? SKILL9[bi].k + ' ' + SKILL9[bi].n : SKILL9[0].k + ' ' + SKILL9[0].n; const t = sk + ' 现场带教一次（' + (m ? m.m : '韩雪') + ' 带）'; MG.planPush(n, t, '师带徒'); if (m) DB.notify(m.m, '带教任务 · ' + n + '：' + t, '已发'); XW.answer('给' + n + '排了：' + t + '，下次派这类活时我会把' + (m ? m.m + '和' + n : n) + '放到一起。' + (x && x.theory < 60 ? '他上次理论 ' + x.theory + ' 分，先补课再上手。' : ''), null, { confirm: false }); },
  'grow-remind'(el) { const n = el.dataset.who, m = el.dataset.m; DB.notify(m, '师带徒提醒 · ' + n + ' 本月带教记录待填，理论成绩 ' + (MENTEE[n] || {}).theory, '已发'); XW.answer('提醒发给' + m + '了：' + n + '本月带教记录待填。', null, { confirm: false }); },
  'grow-bb'(el) { const b = BACKBONE[+el.dataset.i]; const done = LS.get('backbone', {}); done[b.who] = Math.min(b.items.length, (done[b.who] != null ? done[b.who] : b.done) + 1); LS.set('backbone', done); DB.log('骨干培养', b.who + ' 完成一项：' + b.items[done[b.who] - 1]); if (S.page === 'grow') render(); XW.answer(b.who + '的"' + b.items[done[b.who] - 1] + '"记为完成，' + (done[b.who] >= b.items.length ? '申报条件齐了，' + b.when + '可以报。' : '还差 ' + (b.items.length - done[b.who]) + ' 项。'), null, { confirm: false }); },
  'grow-bb-send'(el) { const b = BACKBONE[+el.dataset.i]; DB.notify(b.who, '骨干培养计划 · 目标 ' + b.next + '（' + b.when + '）：' + b.items.join('；'), '已发'); XW.answer('培养计划发给' + b.who + '本人了。', null, { confirm: false }); }
});

/* ---------- 绩效与激励 ---------- */
const PERFPG = {
  table() { const R = perfAlloc(); return '<div class="tbl"><table class="t perf"><tr><th>姓名</th><th>证据条数</th><th>初步系数</th><th>依据</th><th>物质激励（月度）</th><th>非物质激励</th><th>确认</th></tr>' + R.map(r => '<tr class="' + (r.ok ? '' : '') + '"><td><b data-act="sk-person" data-who="' + r.p.n + '">' + h(r.p.n) + '</b><br><span class="note">' + h(r.p.post) + '</span></td><td class="mono" data-act="rate-evid" data-who="' + r.p.n + '" style="cursor:pointer"><u class="num">' + r.evid + '</u></td><td><b class="mono ' + (r.co >= 1.05 ? 'g' : r.co < 1 ? 'b' : '') + '">' + r.co.toFixed(2) + '</b> <button class="s g" data-act="perf-adj" data-who="' + r.p.n + '" data-v="-0.02">−</button><button class="s g" data-act="perf-adj" data-who="' + r.p.n + '" data-v="0.02">＋</button></td><td>' + (r.why.map(w => '<span class="tag ' + (/超|达|≥|荣誉|带徒/.test(w) ? 'ok' : 'bad') + '">' + h(w) + '</span>').join('') || '<span class="note">按基准</span>') + '</td><td><span class="mono">¥' + r.money + '</span>' + MG.bar(r.money / 1500 * 100) + '</td><td><span class="tag ' + (/评优/.test(r.nonm) ? 'v' : /表扬/.test(r.nonm) ? 'ok' : /补课/.test(r.nonm) ? 'bad' : '') + '">' + h(r.nonm) + '</span></td><td>' + (r.ok ? '<span class="tag ok">已确认</span>' : '<button class="s" data-act="perf-ok" data-who="' + r.p.n + '">确认</button>') + '</td></tr>').join('') + '</table></div>'; }
};
PAGES.perf = {
  render() { const R = perfAlloc(); const okN = R.filter(r => r.ok).length; const nm = {}; R.forEach(r => { nm[r.nonm] = (nm[r.nonm] || 0) + 1; });
    return cmdHTML(['王安的系数为什么低', '生成本月激励分配表', '全部确认']) + pageHead('绩效与激励', '月度绩效考评（' + TODAY.slice(0, 7) + '）· 系数由五类履职证据推导 · 由班组长确认后使用', '<button class="s g" data-act="nav" data-to="people">履职证据</button>') +
      '<div class="grid4"><div class="card kpi"><span>月度绩效池</span><b>¥' + PERF_POOL.toLocaleString() + '</b><em>按确认后的系数分配</em></div><div class="card kpi"><span>系数已确认</span><b>' + okN + '/12</b><em>' + (okN === 12 ? '可生成分配表' : '确认完才能生成分配表') + '</em></div><div class="card kpi"><span>系数 ≥ 1.05</span><b class="g">' + R.filter(r => r.co >= 1.05).length + '</b><em>' + h(R.filter(r => r.co >= 1.05).map(r => r.p.n).join('、')) + '</em></div><div class="card kpi"><span>系数 < 1.00</span><b class="bad">' + R.filter(r => r.co < 1).length + '</b><em>' + h(R.filter(r => r.co < 1).map(r => r.p.n).join('、') || '无') + '</em></div></div>' +
      '<div class="card"><div class="h"><b>员工绩效考评 · 系数与激励分配</b><span>基准 1.00；外勤超 24 小时 +0.05 · 实操量达人均 +0.05 · 学时 ≥ 5 +0.03 · 本年荣誉 +0.05 · 带徒 +0.03 · 学时 0 −0.05 · 实操量低于人均 30% −0.05</span><div class="r"><button class="s g" data-act="perf-okall">全部确认</button><button class="s" data-act="perf-sheet">生成激励分配表</button></div></div>' + PERFPG.table() + '</div>' +
      '<div class="grid2"><div class="card"><div class="h"><b>物质激励分配</b><span>按系数占比</span></div>' + CH.mini.bars(R.slice().sort((a, b) => b.money - a.money).map(r => ({ n: r.p.n, v: r.money, txt: '¥' + r.money, act: 'sk-person', who: r.p.n })), { x0: 48, h: 13 }) + '</div><div class="card"><div class="h"><b>非物质激励</b><span>评优推荐 / 班务会表扬 / 培训机会 / 补课与带教任务</span></div>' + CH.mini.donut(Object.keys(nm).map((k, i) => ({ k, v: nm[k], c: CPAL[i % 6] })), { sub: '人' }) + '<div class="note" style="margin-top:6px">评优推荐的人同步进骨干培养计划；补课与带教任务的人进关怀与文化页的回访。</div></div></div>'; },
  after() { CH.mount($('#main')); }
};
Object.assign(ACT, {
  'perf-adj'(el) { const adj = LS.get('perf_adj', {}); adj[el.dataset.who] = +((adj[el.dataset.who] || 0) + +el.dataset.v).toFixed(2); LS.set('perf_adj', adj); DB.log('绩效', el.dataset.who + ' 系数调整 ' + (+el.dataset.v > 0 ? '+' : '') + el.dataset.v); render(); },
  'perf-ok'(el) { const ok = LS.get('perf_ok', {}); ok[el.dataset.who] = DB.now(); LS.set('perf_ok', ok); DB.log('绩效', el.dataset.who + ' 月度系数已确认'); render(); },
  'perf-okall'() { const ok = LS.get('perf_ok', {}); PEOPLE.forEach(p => { ok[p.n] = ok[p.n] || DB.now(); }); LS.set('perf_ok', ok); DB.log('绩效', '12 人月度系数已确认'); render(); XW.answer('12 个人的系数都确认了，分配表现在可以生成。', null, { confirm: false }); },
  'perf-sheet'() { const R = perfAlloc(); if (R.some(r => !r.ok)) { XW.answer('还有 ' + R.filter(r => !r.ok).length + ' 个人的系数没确认，先确认再生成。', null, { confirm: false }); return; } XW.state('write'); const d = XW.msg('a', TODAY.slice(0, 7) + ' 激励分配表我按确认后的系数算好了：<div class="draft"><span></span></div>'); const txt = R.map(r => r.p.n + '　系数 ' + r.co.toFixed(2) + '　¥' + r.money + '　' + r.nonm).join('\n') + '\n合计 ¥' + R.reduce((s, r) => s + r.money, 0) + ' / 池 ¥' + PERF_POOL; XW.type(d.querySelector('.draft span'), txt, 8, () => { XW.state(''); d.insertAdjacentHTML('beforeend', '<div class="bt"><button data-act="perf-sheet-save">存入文稿中心并报部门</button><button class="g" data-act="no" data-t="再改改">再改改</button></div>'); XW.scrollChat(); }); },
  'perf-sheet-save'() { const el = $$('.msg .draft').pop(); const docs = LS.get('docs', {}); docs['perf-' + TODAY.slice(0, 7)] = { t: TODAY.slice(0, 7) + ' 激励分配表', ts: Date.now(), body: el ? el.textContent : '' }; LS.set('docs', docs); DB.notify('陈国安', TEAM.name + ' ' + TODAY.slice(0, 7) + ' 激励分配表已报', '已发'); DB.log('绩效', '激励分配表已存并报部门'); XW.answer('存了，也报给陈国安了。', null, { confirm: false }); }
});

/* ---------- 关怀与文化 ---------- */
const CAREPG = {
  key(c) { return c.k + '|' + c.who + '|' + c.when; },
  list() { const done = LS.get('care_done', {}); return careList().map(c => Object.assign(c, { done: done[this.key(c)] })); },
  careHTML() { const L = this.list(); const KN = { year: '入职关键年份', follow: '回访提醒', load: '高强度关怀' }; return L.length ? L.map(c => '<div class="carerow ' + (c.done ? 'done' : '') + '"><span class="tag ' + ({ year: 'v', follow: 'c', load: 'w' }[c.k]) + '">' + KN[c.k] + '</span><b data-act="sk-person" data-who="' + c.who + '">' + h(c.who) + '</b><span>' + h(c.t) + '</span><em>' + h(c.act) + '</em><i class="note">' + h(c.sug) + '</i><div class="bt">' + (c.done ? '<span class="tag ok">已办 ' + h(c.done) + '</span>' : '<button class="s" data-act="care-done" data-key="' + h(this.key(c)) + '">已办</button><button class="s g" data-act="care-msg" data-who="' + c.who + '" data-k="' + c.k + '">写一段话</button>' + (c.k !== 'follow' ? '<button class="s g" data-act="care-follow" data-who="' + c.who + '">排回访</button>' : '')) + '</div></div>').join('') : '<div class="empty">本季没有关怀提醒</div>'; },
  cultAll() { return CULTURE_TEAM.concat(LS.get('culture_add', [])).sort((a, b) => b.d.localeCompare(a.d)); },
  cultHTML() { return '<div class="tbl"><table class="t"><tr><th>日期</th><th>类型</th><th>活动</th><th>主持</th><th>参加</th><th>备注</th></tr>' + this.cultAll().map(c => '<tr><td class="mono">' + h(c.d) + '</td><td><span class="tag ' + ({ 学习: 'c', 分享: 'v', 座谈: '', 帮扶: 'v' }[c.kind] || '') + '">' + h(c.kind) + '</span></td><td><b>' + h(c.t) + '</b></td><td>' + h(c.host) + '</td><td class="mono">' + c.n + '/12</td><td class="note">' + h(c.note || '') + '</td></tr>').join('') + '</table></div>'; }
};
PAGES.care = {
  render() { const L = CAREPG.list(); const todo = L.filter(c => !c.done); const focus = FOCUS_PEOPLE.filter(f => f.team === TEAM.name); const C = CAREPG.cultAll(); const byM = {}; C.forEach(c => { const m = c.d.slice(5, 7) + '月'; byM[m] = (byM[m] || 0) + 1; });
    return cmdHTML(['这个月谁入职满 15 年', '给韩雪写一段话', '记一次班组学习', '刘一鸣最近怎么样']) + pageHead('关怀与文化', '员工关怀提醒 ' + todo.length + ' 条待办 · 重点关注 ' + focus.length + ' 人 · 班组学习 / 分享 / 座谈记录 ' + C.length + ' 条', '<button class="s" data-act="cult-add">记一次活动</button>') +
      '<div class="grid2" style="grid-template-columns:1.5fr 1fr"><div class="card"><div class="h"><b>员工关怀提醒</b><span>入职 5 / 10 / 15 / 20 年 · 谈心回访 · 连续高强度外勤</span></div><div class="carelist">' + CAREPG.careHTML() + '</div></div>' +
      '<div class="card"><div class="h"><b>重点关注人员</b><span>长病 / 高绩效 / 低绩效 / 新员工</span></div>' + focus.map(f => '<div class="focusrow"><span class="tag ' + ({ 长病: 'bad', 高绩效: 'ok', 低绩效: 'w', 新员工: 'c', 借调: 'v' }[f.tag]) + '">' + h(f.tag) + '</span><b data-act="sk-person" data-who="' + f.who + '">' + h(f.who) + '</b><span class="note">' + h(f.t) + '</span><p>' + h(f.do) + '</p><div class="bt"><button class="s g" data-act="focus-guide" data-who="' + f.who + '" data-tag="' + f.tag + '">面谈提纲</button></div></div>').join('') + '</div></div>' +
      '<div class="grid2" style="grid-template-columns:1.5fr 1fr"><div class="card"><div class="h"><b>班组学习 · 分享 · 座谈记录</b><span>星级评价「会议管理」「班组帮扶」「人文关怀」取数于此</span></div>' + CAREPG.cultHTML() + '</div><div class="card"><div class="h"><b>活动次数 · 按月</b></div>' + CH.mini.cols(Object.keys(byM).sort().map(m => ({ n: m, v: byM[m] })), { labels: true, h: 110 }) + '<div class="note" style="margin-top:6px">类型：学习 ' + C.filter(c => c.kind === '学习').length + ' · 分享 ' + C.filter(c => c.kind === '分享').length + ' · 座谈 ' + C.filter(c => c.kind === '座谈').length + ' · 帮扶 ' + C.filter(c => c.kind === '帮扶').length + '</div></div></div>'; },
  after() { CH.mount($('#main')); }
};
Object.assign(ACT, {
  'care-done'(el) { const done = LS.get('care_done', {}); done[el.dataset.key] = DB.now(); LS.set('care_done', done); DB.log('员工关怀', el.dataset.key.split('|')[1] + ' 关怀已办'); render(); XW.fly('已记录'); },
  'care-msg'(el) { const n = el.dataset.who, k = el.dataset.k; const p = P[n]; const yrs = 2026 - +JOIN[n].slice(0, 4); const txt = k === 'year' ? n + '，今天满 ' + yrs + ' 年。这' + yrs + '年里' + (p.honors[0] ? '拿下了' + p.honors[0] + '，' : '') + '带出了' + (MENTORS.filter(m => m.m === n).map(m => m.s).join('、') || '一批新人') + '，班组的' + (skill9Of(p).a >= 5 ? '大半核心技能你都能独立干' : '很多活都有你的名字') + '。工牌我们下次班务会上发，谢谢你。——赵立群' : k === 'load' ? n + '，这周外勤 ' + p.week + ' 小时，超了。下周一、周二排你室内，家里的事先顾好。有需要直接说。——赵立群' : n + '，上次说的事我记着，' + (FOLLOWUPS.find(f => f.who === n) || {}).t.split('；')[0] + '。这周找个时间再聊一下。——赵立群'; XW.state('write'); const d = XW.msg('a', '给' + n + '的话我写了一段：<div class="draft"><span></span></div>'); XW.type(d.querySelector('.draft span'), txt, 26, () => { XW.state(''); d.insertAdjacentHTML('beforeend', '<div class="bt"><button data-act="care-send" data-who="' + n + '">发给本人</button><button class="g" data-act="no" data-t="我自己改">我自己改</button></div>'); XW.scrollChat(); }); },
  'care-send'(el) { const txt = ($$('.msg .draft').pop() || {}).textContent || ''; DB.notify(el.dataset.who, '班长的话：' + txt.slice(0, 40) + '…', '已发'); DB.log('员工关怀', '给 ' + el.dataset.who + ' 发了一段话'); XW.answer('发给' + el.dataset.who + '了。', null, { confirm: false }); },
  'care-follow'(el) { const n = el.dataset.who; DB.notify('赵立群', '回访提醒 · ' + n + '（两周后）', '已发', true); DB.log('员工关怀', n + ' 排回访 · 两周后'); XW.answer('两周后提醒你回访' + n + '。', null, { confirm: false }); },
  'focus-guide'(el) { const who = el.dataset.who, tag = el.dataset.tag; const kind = /高绩效|低绩效/.test(tag) ? '绩效面谈' : /关键/.test(tag) ? '关键事件面谈' : '关怀面谈'; const g = TALK_GUIDES[kind]; const f = FOCUS_PEOPLE.find(x => x.who === who); const host = document.createElement('div'); host.className = 'doc'; const d = XW.msg('a', who + ' · ' + kind + '提纲：'); d.appendChild(host); MG.stream(host, ['开场：' + g.open].concat(g.items.map((it, i) => (i + 1) + '. ' + it), ['本人情况：' + (f ? f.t + '；' + f.do : '')], ['沟通要点：' + g.tips.join('；')]), { title: who + ' ' + kind + '提纲', done() { d.insertAdjacentHTML('beforeend', '<div class="bt"><button data-act="guide-save" data-who="' + who + '" data-kind="' + kind + '">存入文稿中心</button><button class="g" data-act="care-follow" data-who="' + who + '">排回访</button></div>'); XW.scrollChat(); } }); },
  'guide-save'(el) { const host = $$('.msg .doc').pop(); MG.saveDoc('guide-' + el.dataset.who, el.dataset.who + ' ' + el.dataset.kind + '提纲', host); XW.answer('提纲存到文稿中心了，谈完把结论写进谈心记录。', null, { confirm: false }); },
  'cult-add'() { modal('<div class="t">记一次班组活动</div><div class="jf" id="cultf"><label>类型</label><select id="cu-k"><option>学习</option><option>分享</option><option>座谈</option><option>帮扶</option></select><label>活动</label><input id="cu-t" placeholder="如 终端调试跨班组带教（配电运维一班）"><label>主持</label><input id="cu-h" value="赵立群"><label>参加人数</label><input id="cu-n" type="number" value="12"><label>备注</label><input id="cu-note" placeholder="可不填"></div><div class="bt"><button data-act="cult-add-ok">保存</button></div>'); },
  'cult-add-ok'() { const t = ($('#cu-t') || {}).value || ''; if (t.trim().length < 2) { XW.answer('活动名称要写清楚。', null, { confirm: false }); return; } const a = LS.get('culture_add', []); a.push({ d: TODAY, kind: $('#cu-k').value, t: t.trim(), host: $('#cu-h').value || '赵立群', n: +$('#cu-n').value || 12, note: $('#cu-note').value || '', added: true }); LS.set('culture_add', a); DB.log('班组活动', $('#cu-k').value + '：' + t); $('#modal').hidden = true; render(); XW.answer('记上了。' + ($('#cu-k') && /帮扶/.test(a[a.length - 1].kind) ? '星级评价的"班组帮扶"这一项得分会跟着变，班组画像页能看到。' : ''), null, { confirm: false }); }
});

/* ---------- 分析参谋：队伍现状诊断 + 培养及队伍建设参谋 ---------- */
const ADVPG = {
  diag() { const st = ageStruct(); const in5 = ageIn(5); const cov = skillCover().filter(c => c.must); const hi = cov.filter(c => c.a.length <= 2); const g = certGap().filter(x => x.lack); const low = skill9Low(); const lag = PEOPLE.filter(p => p.hours.done / p.hours.req < 0.5); const lv = {}; PEOPLE.forEach(p => { const l = skillLvOf(p.n); lv[l] = (lv[l] || 0) + 1; }); const young = PEOPLE.filter(p => p.age <= 30); const youngOnly = young.filter(p => p.cert.length <= 1); const avgAge = ageAvg(PEOPLE); const over45in5 = PEOPLE.filter(p => p.age + 5 >= 46).length;
    const roots = []; if (hi.length) roots.push(['技能断层', hi.length + ' 个★模块已授权 ≤ 2 人']); if (youngOnly.length) roots.push(['资质集中', '30 岁以下 ' + youngOnly.length + ' 人只持准入证']); if (low.length) roots.push(['实操不均', low.length + ' 人实操量低于人均 30%']); if (lag.length) roots.push(['学时落后', lag.length + ' 人学时不到一半']); if (over45in5 >= 4) roots.push(['年龄断层', '5 年后 46 岁以上 ' + over45in5 + ' 人，骨干层将同期退出']); if (MENTORS.length < youngOnly.length) roots.push(['带教不足', '师徒对 ' + MENTORS.length + '，待带教新人 ' + youngOnly.length]);
    return { st, in5, cov, hi, g, low, lag, lv, young, youngOnly, avgAge, over45in5, roots, text: [
      '人员结构：12 人平均 ' + avgAge + ' 岁，30 岁以下 ' + young.length + ' 人、46 岁以上 ' + PEOPLE.filter(p => p.age >= 46).length + ' 人；5 年后 46 岁以上将有 ' + over45in5 + ' 人，' + (over45in5 >= 4 ? '骨干层同期进入退出窗口，梯队缺口在 2029–2031 年出现。' : '结构平稳。'),
      '技能结构：技师 ' + (lv['技师'] || 0) + '、高级工 ' + (lv['高级工'] || 0) + '、中级工 ' + (lv['中级工'] || 0) + '、初级工 ' + (lv['初级工'] || 0) + '、未定级 ' + (lv['未定级'] || 0) + '；核心业务自主实施率 ' + authRate() + '%，★模块已授权 ≤ 2 人的有 ' + hi.length + ' 个（' + hi.map(c => c.s.k + ' ' + c.s.n).join('、') + '），授权集中在 ' + (hi[0] ? hi[0].a.map(p => p.n).join('、') : '骨干') + '，一旦调动或退出即断层。',
      '资质与实操：' + (g.length ? g.map(x => x.k + ' 缺 ' + x.lack + ' 人').join('、') : '资质下限已满足') + '；人均实操 ' + skill9PerCap() + ' 次，' + low.length + ' 人低于人均 30%（' + low.map(p => p.n).join('、') + '），实操机会集中在工作负责人。',
      '演变趋势：按现有带教取证节奏，两年内已授权人数只在 ' + hi.map(c => c.s.k + ' ' + c.s.n).slice(0, 2).join('、') + ' 各增加 1 人；不调整派工方式，断层模块数不会减少。'
    ] }; },
  candidates() { return PEOPLE.filter(p => p.post !== '班长' && p.age <= 36).map(p => { const s9 = skill9Of(p); const hs = SCORE_HIST[p.n] || []; const avgS = hs.length ? Math.round(hs.reduce((s, x) => s + x.s, 0) / hs.length) : 0; const gen = genOf(p.n), pro = proOf(p.n); const proAvg = pro.reduce((t, x) => t + x, 0) / pro.length; const cov = skillCover(); const gapB = cov.filter(c => c.must && c.a.length <= 4 && s9.q[cov.indexOf(c)] === 'B'); const score = +(s9.mustB * 1.5 + s9.rate / 20 + (avgS >= 80 ? 2 : avgS >= 70 ? 1 : 0) + (36 - p.age) * 0.15 + p.hours.done / 60 * 2 + proAvg * 0.6 + gapB.length * 2).toFixed(1); const weak = []; if (avgS && avgS < 70) weak.push('理论成绩 ' + avgS); if (p.hours.done / p.hours.req < 0.5) weak.push('学时 ' + p.hours.done + '/60'); if (gen[0] <= 2) weak.push('忠诚执行 L' + gen[0]); if (gen[4] <= 2) weak.push('沟通协作 L' + gen[4]); if (proGap(p.n).length >= 3) weak.push('专业画像未到位 ' + proGap(p.n).length + ' 项'); if (p.cert.length <= 2) weak.push('证书 ' + p.cert.length + ' 本'); const plan = []; gapB.slice(0, 2).forEach(c => plan.push(c.s.k + ' ' + c.s.n + ' 带教取证（' + (c.a[0] ? c.a[0].n : '韩雪') + ' 带）')); const cg = certGap().find(x => x.lack && !p.cert.includes(x.k)); if (cg) plan.push('取证：' + cg.k); if (avgS && avgS < 70) plan.push('先补理论：' + (hs[hs.length - 1] || {}).t); if (!plan.length) plan.push('主持一次成套设备验收'); const risk = p.week > WEEK_LIMIT ? '本周外勤已超 24 小时，培养任务会加负荷' : p.age <= 26 ? '入职时间短，稳定性待观察' : gapB.length === 0 ? '当前没有培训中的断层★模块，培养回报慢' : ''; return { p, score, s9, avgS, gapB, weak, plan, risk, why: '自主实施率 ' + s9.rate + '%，★模块培训中 ' + s9.mustB + ' 个（其中断层模块 ' + gapB.length + ' 个）' + (avgS ? '，理论均分 ' + avgS : '') + '，' + p.age + ' 岁，优势 ' + portTop(p.n).map(x => x[0]).join('、') }; }).sort((a, b) => b.score - a.score); },
  diagHTML() { const D = this.diag(); return '<div class="grid2" style="grid-template-columns:1.4fr 1fr"><div class="card"><div class="h"><b>诊断结论</b><span>自动读取名册、技能台账、证书台账、学时与成绩记录</span><div class="r"><button class="s" data-act="adv-report" data-k="diag">生成诊断报告</button></div></div><div class="roots">' + D.roots.map(r => '<span class="root" data-act="adv-root" data-k="' + h(r[0]) + '"><b>' + h(r[0]) + '</b>' + h(r[1]) + '</span>').join('') + '</div><ol class="diagtext">' + D.text.map(t => '<li>' + h(t) + '</li>').join('') + '</ol></div>' +
    '<div><div class="card"><div class="h"><b>年龄结构 · 现在与 5 年后</b></div>' + CH.mini.group(AGE_BANDS.map(b => b[0].replace(' 岁', '')), [{ n: '现在', vals: D.st.map(s => s.list.length) }, { n: '5 年后', vals: D.in5, c: CPAL[1] }], { h: 120 }) + CH.mini.legend([{ n: '现在' }, { n: '5 年后', c: CPAL[1] }]) + '</div><div class="card" style="margin-top:10px"><div class="h"><b>★模块已授权人数 · 最少的 10 个</b><span>虚线 = 3 人</span></div>' + CH.mini.bars(D.cov.slice().sort((a, b) => a.a.length - b.a.length).slice(0, 10).map(c => ({ n: c.s.k + ' ' + c.s.n.slice(0, 6), v: c.a.length, c: c.a.length <= 2 ? '#e5484d' : c.a.length <= 4 ? '#d97706' : SEM.ok, tip: c.s.n })), { x0: 92, limit: 3, max: 12, unit: ' 人' }) + '<div class="legend-note">颜色说明：红 = 已授权 ≤ 2 人；黄 = 3–4 人；绿 = 5 人及以上。</div></div></div></div>'; },
  advHTML() { const C = this.candidates(); const plan = LS.get('plan', []); return '<div class="card"><div class="h"><b>推荐培养对象 · 排序</b><span>依据班员画像的断层项、建设差距、成绩与学时、员工画像优势 · 由班组长确认后使用</span><div class="r"><button class="s g" data-act="adv-report" data-k="grow">生成参谋报告</button><button class="s" data-act="adv-planall">前三名排进计划</button></div></div><div class="tbl"><table class="t cand"><tr><th>#</th><th>人</th><th>推荐理由</th><th>潜在短板</th><th>培养方案</th><th>风险提示</th><th></th></tr>' + C.map((c, i) => '<tr class="' + (i < 3 ? 'hl' : '') + '"><td class="mono">' + (i + 1) + '</td><td><b data-act="sk-person" data-who="' + c.p.n + '">' + h(c.p.n) + '</b><br><span class="note">' + h(c.p.post) + ' · 综合 ' + c.score + '</span></td><td class="note" style="color:var(--ink)">' + h(c.why) + '</td><td>' + (c.weak.map(w => '<span class="tag w">' + h(w) + '</span>').join('') || '<span class="note">无明显短板</span>') + '</td><td><ol class="planol">' + c.plan.map(x => '<li>' + h(x) + '</li>').join('') + '</ol></td><td class="note">' + h(c.risk || '—') + '</td><td>' + (plan.some(q => q.who === c.p.n && /参谋/.test(q.why || '')) ? '<span class="tag ok">已排</span>' : '<button class="s" data-act="adv-plan" data-who="' + c.p.n + '">排进计划</button>') + '</td></tr>').join('') + '</table></div></div>'; }
};
PAGES.advise = {
  TABS: [{ k: 'diag', n: '队伍现状诊断' }, { k: 'grow', n: '培养及队伍建设参谋' }],
  render() { const s = S.sub || 'diag'; return cmdHTML(['班组五年后缺什么', '谁最值得培养', '生成诊断报告']) + pageHead('分析参谋', '队伍现状诊断（归因 + 趋势 + 根因标签）· 培养及队伍建设参谋（推荐对象排序、理由、短板、方案、风险）') + tabsHTML(this.TABS, s) + (s === 'grow' ? ADVPG.advHTML() : ADVPG.diagHTML()) + '<div class="card doc" id="advdoc" hidden></div>'; },
  after() { CH.mount($('#main')); }
};
Object.assign(ACT, {
  'adv-root'(el) { const D = ADVPG.diag(); const k = el.dataset.k; const map = { 技能断层: () => nav('auth', 'gap'), 资质集中: () => ensure('people', () => {}), 实操不均: () => nav('ledger', 'skill9'), 学时落后: () => nav('ledger', 'hours'), 年龄断层: () => ensure('people', () => {}), 带教不足: () => nav('grow') }; XW.answer('根因"' + k + '"：' + (D.roots.find(r => r[0] === k) || [])[1] + '。我带你去对应的页面看明细。', null, { confirm: false }); XW.at(1200, () => (map[k] || (() => {}))()); },
  'adv-plan'(el) { const c = ADVPG.candidates().find(x => x.p.n === el.dataset.who); if (!c) return; c.plan.forEach(t => MG.planPush(c.p.n, t, '培养参谋')); DB.notify(c.p.n, '培养计划 · ' + c.plan.join('；'), '已发'); render(); XW.answer(c.p.n + '的培养方案排进计划了：' + c.plan.join('；') + '。' + (c.risk ? '注意：' + c.risk + '。' : ''), null, { confirm: false }); },
  'adv-planall'() { const C = ADVPG.candidates().slice(0, 3); let n = 0; C.forEach(c => c.plan.forEach(t => { if (MG.planPush(c.p.n, t, '培养参谋')) n++; })); render(); XW.answer('前三名 ' + C.map(c => c.p.n).join('、') + ' 共 ' + n + ' 项排进计划了，培养与梯队页和年度培训计划都能看到。', null, { confirm: false }); },
  'adv-report'(el) { const k = el.dataset.k; const host = $('#advdoc'); if (!host) return; host.hidden = false; host.scrollIntoView({ block: 'start' }); const D = ADVPG.diag(); const C = ADVPG.candidates().slice(0, 3); const B = buildScore();
    const paras = k === 'diag' ? ['一、总体判断：' + TEAM.name + '队伍规模 12 人，星级建设初步评分 ' + B.pct + '（' + B.lv + '线）。主要问题是技能断层与实操不均，根因标签：' + D.roots.map(r => r[0]).join('、') + '。'].concat(D.text.map((t, i) => '二' + '三四五'[i] + '、' + t), ['六、建议：① ★模块按"每个至少 3 人取得授权"排带教取证；② 派工时把实操量低于人均 30% 的人优先排进对应技能的活；③ 30 岁以下只持准入证的人 2026 年内完成岗位胜任能力证；④ 培养对象优先 ' + C.map(c => c.p.n).join('、') + '（见培养参谋）。以上由班组长确认后执行。']) : ['一、推荐培养对象（按综合排序）：' + C.map((c, i) => (i + 1) + '. ' + c.p.n + '（' + c.why + '）').join('；') + '。'].concat(C.map((c, i) => '二' + '三四'[i] + '、' + c.p.n + '：短板 ' + (c.weak.join('、') || '无') + '；方案 ' + c.plan.join('、') + '；风险 ' + (c.risk || '无') + '。'), ['五、配套：带教师傅按作业授权认证表的已授权人员安排，培训按年度计划的对应课程，取证按证书台账的到期与缺口；每季度在授权认证页复看一次断层模块数是否减少。以上由班组长确认后执行。']);
    MG.stream(host, paras, { title: TEAM.name + (k === 'diag' ? ' 队伍现状诊断报告' : ' 培养及队伍建设参谋报告') + ' · ' + TODAY, done() { host.insertAdjacentHTML('beforeend', '<div class="bt"><button data-act="adv-save" data-k="' + k + '">存入文稿中心</button><button class="g" data-act="adv-send" data-k="' + k + '">报陈国安</button></div>'); } }); },
  'adv-save'(el) { MG.saveDoc('adv-' + el.dataset.k, TEAM.name + (el.dataset.k === 'diag' ? ' 队伍现状诊断报告' : ' 培养及队伍建设参谋报告'), $('#advdoc')); XW.answer('报告存到文稿中心了。', null, { confirm: false }); },
  'adv-send'(el) { MG.saveDoc('adv-' + el.dataset.k, TEAM.name + (el.dataset.k === 'diag' ? ' 队伍现状诊断报告' : ' 培养及队伍建设参谋报告'), $('#advdoc')); DB.notify('陈国安', TEAM.name + (el.dataset.k === 'diag' ? ' 队伍现状诊断报告' : ' 培养参谋报告') + ' 已报', '已发'); XW.answer('报给陈国安了，他在分析参谋页能看到。', null, { confirm: false }); }
});
