/* ===== 管理者 · 八页（9/21 客户口径：业务功能减、管理功能加）：年度指标任务 / 班组横向对比 / 团队画像总览（星级 · 荣誉 · 特色 · 班长队伍与梯队）/ 人员总览仪表盘（下钻人员清单 · 六维个人画像）/ 班组结构对比 / 团队风险画像 / 员工关怀（面谈提纲 · 重点关注 · 文化活动）/ 分析参谋（分析报告 · 近五年趋势）===== */
SUPER.OM_PEOPLE = TEAM3_PEOPLE.map(p => p.n);
SUPER.personOf = function (team, n) { if (team === TEAM.name) return P[n]; if (team === LAB.name) return LAB.people.find(p => p.n === n); return TEAM3_PEOPLE.find(p => p.n === n) || { n, post: '中级作业员', age: 34, cert: ['高压电工作业证', '岗位胜任能力证'] }; };
const MGR = {
  teamOrder: TEAMS.map(t => t.n),
  leaderOf(team) { return (TEAMS.find(t => t.n === team) || {}).leader || '赵立群'; },
  goalRow(g) { return '<tr data-act="goal-open" data-k="' + g.k + '" style="cursor:pointer" class="' + (g.light === 'bad' ? 'hl' : '') + '"><td>' + MG.light(g.light) + '</td><td><b>' + h(g.n) + '</b><br><span class="note">' + h(g.src) + '</span></td><td class="mono">' + h(g.kind === 'text' ? g.target : g.target + g.unit) + '</td><td class="mono">' + h(g.kind === 'text' ? g.stretch : g.stretch + g.unit) + '</td><td><b class="mono">' + h(g.kind === 'text' ? g.v : g.v + g.unit) + '</b></td><td>' + (g.prog != null ? MG.bar(g.prog, g.light) + '<span class="note">' + g.prog + '%' + (g.kind === 'count' || g.kind === 'prog' ? ' · 时间 ' + YEAR_PCT + '%' : '') + '</span>' : '<span class="note">' + (g.kind === 'down' ? '越低越好' : '') + '</span>') + '</td><td>' + h(g.team) + '</td><td class="note" style="max-width:260px">' + h(g.note) + '</td><td>' + (LS.get('goal_urge', {})[g.k] ? '<span class="tag ok">已督办 ' + h(LS.get('goal_urge', {})[g.k]) + '</span>' : '<button class="s g" data-act="goal-urge" data-k="' + g.k + '">督办</button>') + '</td></tr>'; }
};

/* ---------- 年度指标任务 ---------- */
PAGES.goals = {
  render() { const G = goalsAll(); const cnt = { ok: 0, w: 0, bad: 0 }; G.forEach(g => cnt[g.light]++); const urged = LS.get('goal_urge', {});
    return cmdHTML(['哪几项亮红灯', '终端在线率下钻到班组', '督办中压停电时间', '生成本月指标分析']) + pageHead('年度指标任务', '来源：组织经营业绩指标 / 主管个人年度业绩责任书 · 时间进度 ' + YEAR_PCT + '% · 目标值 / 摸高值 / 当前 / 预警', '<button class="s g" data-act="nav" data-to="compare">班组横向对比</button><button class="s g" data-act="nav" data-to="madvise">分析参谋</button>') +
      '<div class="grid4"><div class="card kpi"><span>绿灯 · 达标或按进度</span><b class="g">' + cnt.ok + '</b><em>' + h(G.filter(g => g.light === 'ok').map(g => g.n).slice(0, 4).join('、')) + (cnt.ok > 4 ? ' 等' : '') + '</em></div><div class="card kpi"><span>黄灯 · 接近或略落后</span><b class="w">' + cnt.w + '</b><em>' + h(G.filter(g => g.light === 'w').map(g => g.n).join('、') || '无') + '</em></div><div class="card kpi"><span>红灯 · 落后</span><b class="bad">' + cnt.bad + '</b><em>' + h(G.filter(g => g.light === 'bad').map(g => g.n).join('、') || '无') + '</em></div><div class="card kpi"><span>已督办</span><b>' + Object.keys(urged).length + '</b><em>督办发到责任班组班长的通知里</em></div></div>' +
      '<div class="card"><div class="h"><b>分管业务年度指标 · ' + G.length + ' 项</b><span>点一行下钻到班组；红黄绿按目标值与时间进度判定</span></div><div class="tbl"><table class="t goals"><tr><th></th><th>指标任务</th><th>目标值</th><th>摸高值</th><th>当前</th><th style="min-width:130px">进度</th><th>责任班组</th><th>注意事项</th><th></th></tr>' + G.map(g => MGR.goalRow(g)).join('') + '</table></div></div>' +
      '<div class="grid2"><div class="card"><div class="h"><b>进度 · 数量类指标</b><span>灰线 = 时间进度</span></div>' + CH.mini.bars(G.filter(g => g.prog != null && g.kind !== 'rate').map(g => ({ n: g.n.slice(0, 9), v: Math.min(120, g.prog), txt: g.prog + '%', c: g.light === 'ok' ? '#18b97a' : g.light === 'w' ? '#d97706' : '#e5484d', act: 'goal-open', k: g.k })), { x0: 92, limit: YEAR_PCT, max: 120 }) + '</div><div class="card"><div class="h"><b>督办与注意事项</b><span>最近</span></div>' + (Object.keys(urged).length ? Object.keys(urged).map(k => { const g = G.find(x => x.k === k); return '<div class="jobs"><div><span style="white-space:normal">' + h(g ? g.n : k) + ' · 督办 → ' + h(g ? MGR.leaderOf(g.team === '三班组' ? TEAM.name : g.team) : '') + (g && g.team === '三班组' ? '、' + LAB.leader + '、' + TEAM3.leader : '') + '</span><span>' + h(urged[k]) + '</span></div></div>'; }).join('') : '<div class="empty">还没有督办记录，点表里的"督办"</div>') + '</div></div>'; },
  after() { CH.mount($('#main')); if (!S.briefed) { S.briefed = true; const G = goalsAll(); const bad = G.filter(g => g.light === 'bad'), w = G.filter(g => g.light === 'w'); XW.at(400, () => XW.answer('年度指标 ' + G.length + ' 项：红灯 ' + bad.length + ' 项（' + bad.map(g => g.n).join('、') + '），黄灯 ' + w.length + ' 项。时间进度 ' + YEAR_PCT + '%，数量类指标里' + (G.find(g => g.k === 'g6') ? '配网自动化改造投运 ' + G.find(g => g.k === 'g6').prog + '% 落后最多' : '') + '。点任一行能下钻到班组，督办直接发到班长。', null, { confirm: false })); } }
};
Object.assign(ACT, {
  'goal-open'(el) { const g = goalsAll().find(x => x.k === el.dataset.k); if (!g) return; const teams = Object.keys(g.teams); modal('<div class="t">' + MG.light(g.light, g.lightN + '灯') + '　' + h(g.n) + '</div><div class="note" style="margin-bottom:6px">' + h(g.src) + ' · 目标 ' + h(g.kind === 'text' ? g.target : g.target + g.unit) + ' · 摸高 ' + h(g.kind === 'text' ? g.stretch : g.stretch + g.unit) + '</div><div class="tbl"><table class="t"><tr><th>班组</th><th>当前</th><th>班长</th><th>对照</th><th></th></tr>' + teams.map(t => { const v = g.teams[t](); const ok = g.kind === 'text' ? null : g.kind === 'down' ? +v <= g.target : g.kind === 'rate' ? +v >= g.target : g.kind === 'prog' ? +v >= YEAR_PCT : +v / g.target * 100 >= YEAR_PCT; return '<tr><td><b>' + h(t) + '</b></td><td class="mono">' + h(g.kind === 'text' ? v : v + g.unit) + '</td><td>' + h(MGR.leaderOf(t)) + '</td><td>' + (ok == null ? '—' : ok ? '<span class="tag ok">达标</span>' : '<span class="tag bad">落后</span>') + '</td><td><button class="s g" data-act="goal-urge" data-k="' + g.k + '" data-team="' + h(t) + '">督办' + h(MGR.leaderOf(t)) + '</button>' + (t === TEAM.name ? ' <button class="s g" data-act="goal-team" data-k="' + g.k + '">看班组</button>' : '') + '</td></tr>'; }).join('') + '</table></div><div class="note" style="margin-top:8px"><b style="color:var(--ink)">注意事项：</b>' + h(g.note) + '</div>'); XW.answer(g.n + '：当前 ' + (g.kind === 'text' ? g.v : g.v + g.unit) + '，目标 ' + (g.kind === 'text' ? g.target : g.target + g.unit) + '，' + g.lightN + '灯。' + g.note, null, { confirm: false, speak: false }); },
  'goal-urge'(el) { const g = goalsAll().find(x => x.k === el.dataset.k); if (!g) return; const teams = el.dataset.team ? [el.dataset.team] : (g.team === '三班组' ? MGR.teamOrder : [g.team]); teams.forEach(t => DB.notify(MGR.leaderOf(t), '督办 · ' + g.n + '：当前 ' + (g.kind === 'text' ? g.teams[t] ? g.teams[t]() : g.v : (g.teams[t] ? g.teams[t]() : g.v) + g.unit) + '，目标 ' + (g.kind === 'text' ? g.target : g.target + g.unit) + '。' + g.note, '已发', true)); const u = LS.get('goal_urge', {}); u[g.k] = DB.now(); LS.set('goal_urge', u); DB.log('督办', g.n + ' → ' + teams.map(t => MGR.leaderOf(t)).join('、')); $('#modal').hidden = true; if (S.page === 'goals') render(); XW.fly('督办已发 · ' + teams.map(t => MGR.leaderOf(t)).join('、')); XW.answer('督办发给' + teams.map(t => MGR.leaderOf(t)).join('、') + '了，班长的工作台会看到；注意事项一并带过去。', null, { confirm: false }); },
  'goal-team'(el) { $('#modal').hidden = true; const g = goalsAll().find(x => x.k === el.dataset.k); if (/在线率|遥控|自愈|缺陷/.test(g.n)) nav('ledger', 'weekly'); else if (/星级/.test(g.n)) nav('team'); else if (/实操/.test(g.n)) nav('skills'); else nav('ledger'); }
});

/* ---------- 同类班组横向对比看板 ---------- */
PAGES.compare = {
  render() { const R = compareRows(); const A = compareAdvice(); const names = MGR.teamOrder; const sent = LS.get('cmp_sent', {});
    return cmdHTML(['哪个班组最忙', '要不要跨班组调人', '人均实操量三个班组差多少']) + pageHead('班组横向对比', '配网管理部三个班组 · 本月任务 / 外勤工时（班组约定每人每周 ≤ 24 小时）/ 两票 / 缺陷 / 实操量 / 证书 / 在岗 / 技能结构 · 用于判断是否跨班组调配资源', '<button class="s g" data-act="nav" data-to="ledger" data-sub="transfer">调配台账</button>') +
      '<div class="card"><div class="h"><b>对比看板</b><span>绿 = 三班组最好 · 红 = 最需关注 · 点格看取数</span></div><div class="tbl"><table class="t cmp"><tr><th>维度</th>' + names.map(n => '<th>' + h(n) + '<br><span class="note">' + h(MGR.leaderOf(n)) + ' · ' + (TEAMS.find(t => t.n === n) || {}).size + ' 人</span></th>').join('') + '<th>说明</th></tr>' + R.map(r => '<tr><td><b>' + h(r.n) + '</b>' + (r.unit ? '<span class="note">（' + h(r.unit) + '）</span>' : '') + '</td>' + names.map(n => { const v = r.vals ? r.vals[n] : r.num[n]; const cls = r.best.includes(n) ? 'ok' : r.worst.includes(n) ? 'bad' : ''; return '<td data-act="cmp-cell" data-k="' + r.k + '" data-n="' + h(n) + '" style="cursor:pointer"><span class="cmpv ' + cls + '">' + h(v == null ? '—' : v) + '</span></td>'; }).join('') + '<td class="note">' + h(r.note || '') + '</td></tr>').join('') + '</table></div></div>' +
      '<div class="grid2" style="grid-template-columns:1fr 1.2fr"><div class="card"><div class="h"><b>人均外勤工时 · 本周</b><span>虚线 = 约定上限的 75%</span></div>' + CH.mini.bars(names.map((n, i) => ({ n, v: R.find(r => r.k === 'load').num[n], c: CPAL[i], unit: 'h', act: 'cmp-cell', k: 'load' })), { x0: 82, limit: WEEK_LIMIT * 0.75, max: WEEK_LIMIT, unit: 'h' }) + '<div class="h" style="margin-top:8px"><b>人均核心技能实操量</b></div>' + CH.mini.bars(names.map((n, i) => ({ n, v: R.find(r => r.k === 'cap').num[n], c: CPAL[i], act: 'cmp-cell', k: 'cap' })), { x0: 82, unit: ' 次' }) + '</div>' +
      '<div class="card"><div class="h"><b>分析与参谋</b><span>是否需要跨班组调配</span></div><div class="advbox"><p><b>' + h(A.busy) + '</b>本周人均外勤 ' + R.find(r => r.k === 'load').num[A.busy] + ' 小时，' + (R.find(r => r.k === 'over').num[A.busy] ? '有 ' + R.find(r => r.k === 'over').num[A.busy] + ' 人超 24 小时，' : '') + '原因是' + h(A.need) + '；<b>' + h(A.idle) + '</b>人均 ' + R.find(r => r.k === 'load').num[A.idle] + ' 小时，相差 ' + A.gap + ' 小时。</p><p>建议：从' + h(A.idle) + '借 <b>' + h(A.who) + '</b> 到' + h(A.busy) + ' 3 天（下周一起），借出后' + h(A.idle) + '人均工时仍在约定内；影响测算与替代人选在发起前会算给你看。</p><p class="note">两位班长各收一条待确认，确认或退回后调配台账同步。</p></div><div class="bt">' + (sent[A.who] ? '<span class="tag ok">已发起 ' + h(sent[A.who]) + '</span>' : '<button data-act="cmp-transfer" data-who="' + h(A.who) + '" data-from="' + h(A.idle) + '" data-to="' + h(A.busy) + '">发起跨班组调配</button>') + '<button class="g" data-act="nav" data-to="structure">看结构对比</button></div></div></div>'; },
  after() { CH.mount($('#main')); }
};
Object.assign(ACT, {
  'cmp-cell'(el) { const r = compareRows().find(x => x.k === el.dataset.k); const n = el.dataset.n; if (!r) return; const src = { jobs: '任务台账 · 本月', load: '工时台账 · 本周', over: '工时台账 · 约定 24 小时', tk: '两票台账 · 本月', df: '缺陷台账', cap: '核心技能台账', cert: '证书台账 · 90 天内', on: '人员名册', high: '技能等级认定台账' }[r.k]; XW.answer((n || '三班组') + '的' + r.n + (n ? '是 ' + (r.vals ? r.vals[n] : r.num[n]) + (r.unit || '') : '') + '，取自' + src + '。三班组里最好的是' + r.best.join('、') + (r.worst.length ? '，最需关注' + r.worst.join('、') : '') + '。', null, { confirm: false }); },
  'cmp-transfer'(el) { const who = el.dataset.who, from = el.dataset.from, to = el.dataset.to; const A = compareAdvice(); SUPER.simState = { from, who, to, days: 3, start: '2026-08-10', why: A.need }; const sent = LS.get('cmp_sent', {}); sent[who] = DB.now(); LS.set('cmp_sent', sent); ensure('risk', () => { const host = $('#riskbody'); if (host) { host.innerHTML = SUPER.simHTML(); CH.mount(host); } XW.at(300, () => ACT['sim-say']()); }, 'sim'); }
});

/* ---------- 团队画像总览 + 班长队伍管理 ---------- */
PAGES.portrait = {
  render() { const st = leaderStat(); const B = buildScore(); const pre = { '配电自动化班': B.pct, '试验班': 93.2, '配电运维一班': 76.4 };
    return cmdHTML(['三个班组各是什么类型', '班长后备够不够', '给陈志远排后备培养']) + pageHead('团队画像总览', '星级班组 · 集体荣誉 · 班组特色标签 · 班长队伍基本情况与梯队建设', '<button class="s g" data-act="nav" data-to="staff">人员总览</button><button class="s g" data-act="nav" data-to="structure">结构对比</button>') +
      '<div class="grid3">' + MGR.teamOrder.map(n => { const T = TEAM_TAGS[n]; const s = teamStat(n); return '<div class="card tcard"><div class="h"><b>' + h(n) + '</b><span>' + h(MGR.leaderOf(n)) + ' · ' + s.n + ' 人</span></div><div class="hstar">' + MG.starTag(T.star) + '<span class="note">' + h(T.starD) + ' · 初步评分 <b>' + pre[n] + '</b></span></div><div class="honors small">' + T.honors.map(x => '<div class="hitem"><b>' + h(x[0]) + '</b><span class="note">' + h(x[1]) + ' · ' + h(x[2]) + '</span></div>').join('') + '</div><div class="kindrow">' + MG.kindTag(T.kind) + '<span class="note">' + h(T.why) + '</span></div><div class="trow"><span>技师及以上 <b>' + s.senior + '</b></span><span>高级工及以上 <b>' + s.high + '</b></span><span>星级工程师 <b>' + s.eng + '</b></span><span>专家 <b>' + s.expert + '</b></span><span>平均 <b>' + s.avgAge + '</b> 岁</span></div><div class="bt"><button class="s g" data-act="pt-team" data-n="' + h(n) + '">看班组画像</button><button class="s g" data-act="st-team" data-n="' + h(n) + '">人员清单</button></div></div>'; }).join('') + '</div>' +
      '<div class="grid2" style="grid-template-columns:1.6fr 1fr"><div class="card"><div class="h"><b>班长队伍管理</b><span>基本情况 · 后备与梯队</span></div><div class="tbl"><table class="t"><tr><th>班长</th><th>班组</th><th>年龄 / 工龄</th><th>任班长</th><th>技能等级</th><th>星级工程师</th><th>党员</th><th>副班长</th><th>后备梯队</th><th>距退休</th><th></th></tr>' + LEADERS.map((l, i) => '<tr><td><b data-act="st-person" data-who="' + l.n + '">' + h(l.n) + '</b></td><td>' + h(l.team) + '</td><td class="mono">' + l.age + ' / ' + l.yrs + '</td><td class="mono">' + l.asLeader + ' 年</td><td>' + h(l.lv) + '</td><td><span class="tag v">' + h(l.star) + '</span></td><td>' + (l.party ? '是' : '否') + '</td><td>' + h(l.deputy) + '</td><td>' + l.backup.map(b => '<span class="tag ' + (b[1] === '可接任' ? 'ok' : 'w') + '" title="' + h(b[2]) + '">' + h(b[0]) + ' · ' + h(b[1]) + '</span>').join('') + '</td><td class="mono">' + l.retireIn + ' 年</td><td><button class="s g" data-act="pt-backup" data-i="' + i + '">后备培养</button></td></tr>').join('') + '</table></div></div>' +
      '<div><div class="card"><div class="h"><b>班长队伍基本情况</b></div><div class="mets" style="grid-template-columns:repeat(3,1fr)"><div><b>' + st.avgAge + '</b><span>平均年龄</span></div><div><b>' + st.avgLead + '</b><span>平均任班长年限</span></div><div><b>' + st.senior + '/3</b><span>技师及以上</span></div><div><b>' + st.party + '/3</b><span>党员</span></div><div><b class="g">' + st.ready + '</b><span>可接任后备</span></div><div><b class="w">' + st.training + '</b><span>培养中后备</span></div></div><div class="note" style="margin-top:6px">10 年内退休 ' + st.retire10 + ' 人；配电运维一班后备只有 1 人且未取技师，是梯队最薄处。</div></div><div class="card" style="margin-top:10px"><div class="h"><b>梯队建设</b></div>' + CH.mini.funnel([{ k: '在任班长', v: 3 }, { k: '可接任', v: st.ready }, { k: '培养中', v: st.training }, { k: '骨干池（星级工程师）', v: Object.keys(STAR_ENG).length - 3 }]) + '</div></div></div>'; },
  after() { CH.mount($('#main')); }
};
Object.assign(ACT, {
  'pt-team'(el) { const n = el.dataset.n; if (n === TEAM.name) nav('team'); else XW.answer(n + '的班组画像按' + n + '名册与班务记录聚合：' + TEAM_TAGS[n].star + '、' + TEAM_TAGS[n].kind + '（' + TEAM_TAGS[n].why + '）。逐维度的初步评分需要该班组接入台账后才能像配电自动化班一样逐项对照。', null, { confirm: false }); },
  'pt-backup'(el) { const l = LEADERS[+el.dataset.i]; const b = l.backup.find(x => x[1] === '培养中') || l.backup[0]; const t = b[1] === '培养中' ? (/未取技师/.test(b[2]) ? '技师鉴定申报 + 主持 2 项作业组织' : '主持一次月度班务会 + 独立编制周计划') : '作为副班长代行班长职责一个月'; DB.notify(l.n, '班长后备培养 · ' + b[0] + '：' + t + '，请排进班组培养计划', '已发'); const s = LS.get('sup_talent', {}); s[b[0]] = { t, d: DB.now() }; LS.set('sup_talent', s); DB.log('梯队', l.team + ' 后备 ' + b[0] + '：' + t); XW.answer('给' + l.n + '发了：' + b[0] + '的后备培养任务"' + t + '"，由班长排进班组培养计划。', null, { confirm: false }); }
});

/* ---------- 多班组人员总览仪表盘 + 下钻 + 六维个人画像 ---------- */
const STAFFPG = {
  all() { return MGR.teamOrder.reduce((a, t) => a.concat(teamPeople(t).map(p => Object.assign({ team: t }, p))), []); },
  listHTML(team) { const ps = teamPeople(team); return '<div class="tbl"><table class="t"><tr><th>姓名</th><th>岗位</th><th>年龄</th><th>工龄</th><th>技能等级</th><th>星级工程师</th><th>证书</th><th>优势特长</th><th>状态</th></tr>' + ps.map(p => '<tr data-act="st-person" data-who="' + p.n + '" style="cursor:pointer" class="' + (STAFFPG.cur === p.n ? 'hl' : '') + '"><td><b>' + h(p.n) + '</b></td><td class="note">' + h(p.post) + '</td><td class="mono">' + p.age + '</td><td class="mono">' + p.yrs + '</td><td>' + h(skillLvOf(p.n)) + '</td><td>' + (STAR_ENG[p.n] ? '<span class="tag v">' + h(STAR_ENG[p.n]) + '</span>' : '—') + '</td><td class="mono">' + p.cert.length + '</td><td>' + sixTop(p.n).map(x => '<span class="tag ok">' + h(x[0]) + ' ' + x[1] + '</span>').join('') + '</td><td>' + h(team === TEAM.name ? p.status : team === LAB.name ? (LAB.borrowed.some(b => b.n === p.n) ? '借调' : p.n === '何静' ? '病假' : '在岗') : (p.n === '谭俊' ? '外勤' : '在岗')) + '</td></tr>').join('') + '</table></div>'; },
  hexHTML(n) { const p = personAny(n); if (!p) return '<div class="empty">点左侧任一人，看六维个人画像</div>'; const team = teamOfPerson(n); const v = sixOf(n); const avg = MG.sixAvg(teamPeople(team)); const top = sixTop(n); const low = v.map((x, i) => [SIX_DIMS[i], x]).sort((a, b) => a[1] - b[1])[0]; return '<div class="hexhead"><b>' + h(n) + '</b><span class="note">' + h(team) + ' · ' + h(p.post) + ' · ' + p.age + ' 岁 · 工龄 ' + p.yrs + ' 年 · ' + h(skillLvOf(n)) + (STAR_ENG[n] ? ' · ' + h(STAR_ENG[n]) : '') + (EXPERTS[n] ? ' · ' + h(EXPERTS[n]) : '') + '</span></div>' + MG.hex(n, { avg }) + CH.mini.legend([{ n: n }, { n: team + '均值', c: '#9aa1b8' }]) + '<div class="sixrows">' + SIX_DIMS.map((d, i) => '<div><span>' + h(d) + '</span>' + MG.bar(v[i] / 5 * 100, v[i] >= 4 ? 'ok' : v[i] <= 2 ? 'w' : '') + '<b class="mono">' + v[i] + '</b><i class="note">' + h(SIX_EVID[d]) + '</i></div>').join('') + '</div><div class="note" style="margin-top:6px"><b style="color:var(--ok)">优势特长：</b>' + top.map(x => x[0]).join('、') + '　<b style="color:var(--warn)">可提升：</b>' + low[0] + '</div><div class="bt">' + (P[n] ? '<button class="s g" data-act="sk-person" data-who="' + n + '">人员档案</button>' : '') + '<button class="s g" data-act="st-say" data-who="' + n + '">她怎么看</button></div>'; }
};
PAGES.staff = {
  render() { const all = STAFFPG.all(); const team = S.sub && MGR.teamOrder.includes(S.sub) ? S.sub : TEAM.name; const lv = {}; all.forEach(p => { const l = skillLvOf(p.n); lv[l] = (lv[l] || 0) + 1; }); const posts = {}; all.forEach(p => { const k = postClass(p); posts[k] = (posts[k] || 0) + 1; }); const on = MGR.teamOrder.reduce((s, t) => s + teamStat(t).on, 0); const out = PEOPLE.filter(p => p.status === '外勤').length + 1; const leave = PEOPLE.filter(p => p.status === '休假').length + 1;
    return cmdHTML(['三个班组一共多少人在岗', '技师有几个', '看韩雪的六维画像']) + pageHead('人员总览', '三个班组 ' + all.length + ' 人 · 在岗 / 技能结构 / 专助责与班员 · 点班组看人员清单，点人看六维个人画像') +
      '<div class="grid4"><div class="card kpi"><span>在岗人数</span><b>' + on + '/' + all.length + '</b><em>外勤 ' + out + ' · 休假 / 病假 ' + leave + ' · 借调 ' + LAB.borrowed.length + '</em></div><div class="card kpi"><span>技师及以上</span><b>' + ((lv['技师'] || 0) + (lv['高级技师'] || 0)) + '</b><em>高级工 ' + (lv['高级工'] || 0) + ' · 中级工 ' + (lv['中级工'] || 0) + ' · 初级工 ' + (lv['初级工'] || 0) + ' · 未定级 ' + (lv['未定级'] || 0) + '</em></div><div class="card kpi"><span>班长 / 专责 / 班员</span><b>' + (posts['班长'] || 0) + ' / ' + (posts['专责'] || 0) + ' / ' + (all.length - (posts['班长'] || 0) - (posts['专责'] || 0)) + '</b><em>高级作业员 ' + (posts['高级作业员'] || 0) + ' · 中级 ' + (posts['中级作业员'] || 0) + ' · 初级 ' + (posts['初级作业员'] || 0) + '</em></div><div class="card kpi"><span>星级工程师 / 专家</span><b>' + all.filter(p => STAR_ENG[p.n]).length + ' / ' + all.filter(p => EXPERTS[p.n] && /^局级专家（/.test(EXPERTS[p.n])).length + '</b><em>专家候选 ' + all.filter(p => EXPERTS[p.n] && /候选/.test(EXPERTS[p.n])).length + ' 人</em></div></div>' +
      '<div class="grid3"><div class="card"><div class="h"><b>技能结构</b><span>三班组</span></div>' + CH.mini.donut(SKILL_LADDER.filter(l => lv[l]).map((l, i) => ({ k: l, v: lv[l], c: RAMP[Math.min(5, i + 1)], act: 'st-seg', k2: l })), { sub: '人' }) + '</div><div class="card"><div class="h"><b>专助责与班员结构</b></div>' + CH.mini.donut(Object.keys(posts).map((k, i) => ({ k, v: posts[k], c: CPAL[i % 6] })), { sub: '人' }) + '</div><div class="card"><div class="h"><b>各班组在岗</b><span>点柱看清单</span></div>' + CH.mini.group(MGR.teamOrder.map(t => t.replace('配电', '')), [{ n: '在编', vals: MGR.teamOrder.map(t => teamStat(t).n) }, { n: '在岗', vals: MGR.teamOrder.map(t => teamStat(t).on), c: CPAL[4] }], { h: 120 }) + CH.mini.legend([{ n: '在编' }, { n: '在岗', c: CPAL[4] }]) + '</div></div>' +
      '<div class="grid2" style="grid-template-columns:1.5fr 1fr"><div class="card"><div class="h"><b>人员清单</b><div class="tabs" style="border:0;padding:0;margin-left:8px">' + MGR.teamOrder.map(t => '<button class="' + (t === team ? 'on' : '') + '" data-act="st-team" data-n="' + h(t) + '">' + h(t) + ' ' + teamPeople(t).length + '</button>').join('') + '</div></div><div id="stlist">' + STAFFPG.listHTML(team) + '</div></div><div class="card"><div class="h"><b>六维个人画像</b><span>业务技能 · 安全素质 · 领导力 · 沟通能力 · 写作能力 · 工作经验</span></div><div id="hexhost">' + STAFFPG.hexHTML(STAFFPG.cur) + '</div></div></div>'; },
  after() { CH.mount($('#main')); }
};
Object.assign(ACT, {
  'st-team'(el) { const n = el.dataset.n; if (S.page !== 'staff') { nav('staff', n); return; } S.sub = n; $$('#main .tabs button').forEach(b => b.classList.toggle('on', b.dataset.n === n)); $('#stlist').innerHTML = STAFFPG.listHTML(n); const s = teamStat(n); XW.answer(n + ' ' + s.n + ' 人，在岗 ' + s.on + '，平均 ' + s.avgAge + ' 岁，技师及以上 ' + s.senior + '、高级工及以上 ' + s.high + '，30 岁以下 ' + s.young + ' 人。点任一人看六维画像。', null, { confirm: false, speak: false }); },
  'st-person'(el) { const n = el.dataset.who; STAFFPG.cur = n; if (S.page !== 'staff') { nav('staff', teamOfPerson(n)); return; } const host = $('#hexhost'); if (host) { host.innerHTML = STAFFPG.hexHTML(n); CH.mount(host); } $$('#stlist tr').forEach(r => r.classList.toggle('hl', r.dataset.who === n)); const top = sixTop(n); XW.answer(n + '的优势在' + top.map(x => x[0] + '（' + x[1] + '）').join('、') + '，六维依据分别来自能力图谱、违章与两票、工作负责人次数、协同记录、文稿与案例、工龄与经手站点。', null, { confirm: false, speak: false }); },
  'st-say'(el) { const n = el.dataset.who; const p = personAny(n); const v = sixOf(n); const team = teamOfPerson(n); const low = v.map((x, i) => [SIX_DIMS[i], x]).sort((a, b) => a[1] - b[1])[0]; XW.answer(n + '：' + (v[0] >= 4 ? '业务上能独当一面，' : '业务还在成长期，') + (v[2] >= 4 ? '能带队，' : v[2] <= 1 ? '还没带过队，' : '') + '最弱的是' + low[0] + '。' + (team === TEAM.name && STAR_ENG[n] ? '已是' + STAR_ENG[n] + '，' : '') + (p.age <= 30 ? '30 岁以下，适合排进培养对象。' : p.age >= 45 ? '经验最足，适合带徒。' : '正当年，可作骨干培养。'), null, { confirm: false }); },
  'st-seg'(el) { const l = el.dataset.k2 || el.dataset.k; const all = STAFFPG.all().filter(p => skillLvOf(p.n) === l); XW.answer(l + ' ' + all.length + ' 人：' + all.map(p => p.n + '（' + p.team.replace('配电', '') + '）').join('、'), null, { confirm: false }); }
});

/* ---------- 班组结构对比画像 ---------- */
const STRUCPG = {
  rows() { const names = MGR.teamOrder; const st = {}; names.forEach(n => { st[n] = teamStat(n); }); const R = [
    { n: '人数 / 在岗', num: names.reduce((a, n) => (a[n] = st[n].on, a), {}), vals: names.reduce((a, n) => (a[n] = st[n].n + ' / ' + st[n].on, a), {}), high: true, w: 0 },
    { n: '平均年龄', num: names.reduce((a, n) => (a[n] = st[n].avgAge, a), {}), unit: '岁', high: false, w: 1, note: '越接近 35 越均衡' },
    { n: '30 岁以下占比', num: names.reduce((a, n) => (a[n] = Math.round(st[n].young / st[n].n * 100), a), {}), unit: '%', high: true, w: 1 },
    { n: '平均工龄', num: names.reduce((a, n) => (a[n] = st[n].stable.avgYrs, a), {}), unit: '年', high: true, w: 1 },
    { n: '近三年离职', num: names.reduce((a, n) => (a[n] = st[n].stable.leave3y, a), {}), unit: '人', high: false, w: 2 },
    { n: '借调 / 长病 / 转岗意向', num: names.reduce((a, n) => (a[n] = st[n].stable.borrowed + st[n].stable.longSick + st[n].stable.intent, a), {}), vals: names.reduce((a, n) => (a[n] = st[n].stable.borrowed + ' / ' + st[n].stable.longSick + ' / ' + st[n].stable.intent, a), {}), high: false, w: 2 },
    { n: '高级工及以上占比', num: names.reduce((a, n) => (a[n] = Math.round(st[n].high / st[n].n * 100), a), {}), unit: '%', high: true, w: 2 },
    { n: '技师及以上', num: names.reduce((a, n) => (a[n] = st[n].senior, a), {}), unit: '人', high: true, w: 2 },
    { n: '星级工程师 / 专家', num: names.reduce((a, n) => (a[n] = st[n].eng + st[n].expert, a), {}), vals: names.reduce((a, n) => (a[n] = st[n].eng + ' / ' + st[n].expert, a), {}), high: true, w: 1 },
    { n: '人均核心技能实操量', num: { '配电自动化班': skill9PerCap(), '试验班': 34.5, '配电运维一班': 18.2 }, unit: '次', high: true, w: 2 }
  ]; R.forEach(r => { const nums = names.map(n => r.num[n]); const best = r.high ? Math.max.apply(null, nums) : Math.min.apply(null, nums); const worst = r.high ? Math.min.apply(null, nums) : Math.max.apply(null, nums); r.best = names.filter(n => r.num[n] === best && best !== worst); r.worst = names.filter(n => r.num[n] === worst && best !== worst); }); return R; },
  strength() { const R = this.rows(); const names = MGR.teamOrder; const sc = {}; names.forEach(n => { sc[n] = 0; }); R.forEach(r => { r.best.forEach(n => { sc[n] += r.w; }); r.worst.forEach(n => { sc[n] -= r.w; }); }); return names.map(n => ({ n, sc: sc[n], tag: sc[n] >= 3 ? '强' : sc[n] <= -3 ? '弱' : '中' })); },
  advice() { const st = {}; MGR.teamOrder.forEach(n => { st[n] = teamStat(n); }); return [
    { t: '配电运维一班 年轻但技能弱：30 岁以下 ' + st['配电运维一班'].young + '/11，高级工及以上 ' + st['配电运维一班'].high + ' 人，人均实操 18.2 次（三班组最低）', do: '从配电自动化班派 1 名高级作业员（李文博）到配电运维一班轮岗 6 个月，带终端巡视与二次回路；同时接收该班 1 名初级作业员（罗天）到配电自动化班学动作分析', who: ['赵立群', '陈志远'], k: 'r1' },
    { t: '试验班 专家型但骨干集中：技师及以上 ' + st['试验班'].senior + '/8 全部 36 岁以上，30 岁以下 4 人中 3 人为初级工或学员，近一年无新进人员，学员有转岗意向', do: '试验班接收配电运维一班 1 名初级作业员（曾静）轮岗学交接试验 3 个月；刘畅借调到期返岗', who: ['周建国', '陈志远'], k: 'r2' },
    { t: '配电自动化班 骨干型：核心技能可自主 ≤ 2 人的有 ' + skillCover().filter(c => c.a.length <= 2).length + ' 类，实操量集中在工作负责人', do: '班内轮岗：初级作业员按季度轮到工作负责人组；派工时把实操量低的人排进对应技能的活', who: ['赵立群'], k: 'r3' }
  ]; }
};
PAGES.structure = {
  render() { const R = STRUCPG.rows(); const names = MGR.teamOrder; const S3 = STRUCPG.strength(); const sent = LS.get('rotate_sugg', {}); const lvs = SKILL_LADDER.filter(l => names.some(n => teamStat(n).lv[l]));
    return cmdHTML(['哪个班组最弱', '轮岗建议', '三个班组年龄结构']) + pageHead('班组结构对比', '人员稳定性 · 年龄结构 · 技能结构 · 强弱差异 · 人力调配与班组轮岗建议', '<button class="s g" data-act="nav" data-to="compare">业务横向对比</button><button class="s g" data-act="nav" data-to="risk" data-sub="sim">跨班组调配</button>') +
      '<div class="grid3">' + S3.map(s => '<div class="card kpi"><span>' + h(s.n) + ' · ' + h(TEAM_TAGS[s.n].kind) + '</span><b class="' + (s.tag === '强' ? 'g' : s.tag === '弱' ? 'bad' : 'w') + '">' + h(s.tag) + '</b><em>综合 ' + (s.sc > 0 ? '+' : '') + s.sc + '（按维度权重：最好 +、最差 −）</em></div>').join('') + '</div>' +
      '<div class="card"><div class="h"><b>结构对比画像</b><span>绿 = 三班组最好 · 红 = 最需关注</span></div><div class="tbl"><table class="t cmp"><tr><th>维度</th>' + names.map(n => '<th>' + h(n) + '</th>').join('') + '<th>说明</th></tr>' + R.map(r => '<tr><td><b>' + h(r.n) + '</b>' + (r.unit ? '<span class="note">（' + h(r.unit) + '）</span>' : '') + '</td>' + names.map(n => '<td><span class="cmpv ' + (r.best.includes(n) ? 'ok' : r.worst.includes(n) ? 'bad' : '') + '">' + h(r.vals ? r.vals[n] : r.num[n]) + '</span></td>').join('') + '<td class="note">' + h(r.note || '') + '</td></tr>').join('') + '</table></div></div>' +
      '<div class="grid2"><div class="card"><div class="h"><b>年龄结构</b><span>三班组</span></div>' + CH.mini.group(AGE_BANDS.map(b => b[0].replace(' 岁', '')), names.map((n, i) => ({ n: n.replace('配电', ''), vals: AGE_BANDS.map(b => teamPeople(n).filter(p => p.age >= b[1] && p.age <= b[2]).length), c: CPAL[i] })), { h: 130 }) + CH.mini.legend(names.map((n, i) => ({ n: n.replace('配电', ''), c: CPAL[i] }))) + '</div><div class="card"><div class="h"><b>技能等级结构</b></div>' + CH.mini.group(lvs, names.map((n, i) => ({ n: n.replace('配电', ''), vals: lvs.map(l => teamStat(n).lv[l] || 0), c: CPAL[i] })), { h: 130 }) + CH.mini.legend(names.map((n, i) => ({ n: n.replace('配电', ''), c: CPAL[i] }))) + '</div></div>' +
      '<div class="card"><div class="h"><b>人力调配与班组轮岗建议</b><span>由班长确认后执行</span></div>' + STRUCPG.advice().map(a => '<div class="fixrow"><div><b>' + h(a.t) + '</b><p>' + h(a.do) + '</p></div><div class="bt">' + (sent[a.k] ? '<span class="tag ok">已发 ' + h(sent[a.k]) + '</span>' : '<button class="s" data-act="stc-rotate" data-k="' + a.k + '">发轮岗建议给' + h(a.who.join('、')) + '</button>') + '</div></div>').join('') + '</div>'; },
  after() { CH.mount($('#main')); }
};
Object.assign(ACT, {
  'stc-rotate'(el) { const a = STRUCPG.advice().find(x => x.k === el.dataset.k); if (!a) return; a.who.forEach(n => DB.notify(n, '轮岗建议 · ' + a.do, '待确认', true)); const s = LS.get('rotate_sugg', {}); s[a.k] = DB.now(); LS.set('rotate_sugg', s); DB.log('轮岗建议', a.do); render(); XW.fly('已发 · ' + a.who.join('、')); XW.answer('轮岗建议发给' + a.who.join('、') + '了，两位班长确认后走跨班组调配。', null, { confirm: false }); }
});

/* ---------- 团队风险画像聚合 ---------- */
PAGES.risks = {
  render() { const R = riskAgg(); const groups = ['敏感岗位轮岗', '考勤异常', '绩效持续偏低', '队伍稳定性']; const sent = LS.get('risk_sent', {}); const AN = { rotate: '发轮岗提醒', care: '发关怀提醒', remind: '提醒班长', talk: '面谈提纲', transfer: '催返岗', ladder: '看结构对比' };
    return cmdHTML(['哪些敏感岗位该轮岗了', '考勤异常有谁', '刘畅借调多久了']) + pageHead('团队风险画像', '关键敏感岗位轮岗 · 考勤异常 · 绩效持续偏低 · 队伍稳定性 · 三班组台账自动聚合，每项对应一个动作', '<button class="s g" data-act="nav" data-to="mcare">员工关怀</button>') +
      '<div class="grid4">' + groups.map(g => { const l = R.filter(r => r.g === g); return '<div class="card kpi"><span>' + h(g) + '</span><b class="' + (l.some(r => r.lv === '高') ? 'bad' : l.length ? 'w' : 'g') + '">' + l.length + '</b><em>' + h(l.map(r => r.who).filter(w => w !== '—').join('、') || '无') + '</em></div>'; }).join('') + '</div>' +
      '<div class="card"><div class="h"><b>风险清单 · ' + R.length + ' 项</b><span>高 ' + R.filter(r => r.lv === '高').length + ' · 中 ' + R.filter(r => r.lv === '中').length + ' · 低 ' + R.filter(r => r.lv === '低').length + '</span></div><div class="tbl"><table class="t"><tr><th>类别</th><th>等级</th><th>班组</th><th>人</th><th>事项</th><th>来源</th><th>动作</th></tr>' + R.map((r, i) => '<tr class="' + (r.lv === '高' ? 'hl' : '') + '"><td><span class="tag ' + ({ 敏感岗位轮岗: 'v', 考勤异常: 'w', 绩效持续偏低: 'bad', 队伍稳定性: 'c' }[r.g]) + '">' + h(r.g) + '</span></td><td>' + MG.light(r.lv === '高' ? 'bad' : r.lv === '中' ? 'w' : 'ok', r.lv) + '</td><td>' + h(r.team) + '</td><td>' + (r.who !== '—' ? '<b data-act="st-person" data-who="' + r.who + '">' + h(r.who) + '</b>' : '—') + '</td><td>' + h(r.t) + '</td><td class="note">' + h(r.src) + '</td><td>' + (sent[i] ? '<span class="tag ok">' + h(sent[i]) + '</span>' : '<button class="s g" data-act="rk-act" data-i="' + i + '">' + AN[r.act] + '</button>') + '</td></tr>').join('') + '</table></div></div>' +
      '<div class="grid2"><div class="card"><div class="h"><b>按班组</b></div>' + CH.mini.group(MGR.teamOrder.map(t => t.replace('配电', '')), groups.map((g, i) => ({ n: g, vals: MGR.teamOrder.map(t => R.filter(r => r.g === g && r.team === t).length), c: CPAL[i] })), { h: 120 }) + CH.mini.legend(groups.map((g, i) => ({ n: g, c: CPAL[i] }))) + '</div><div class="card"><div class="h"><b>敏感岗位任职年限</b><span>虚线 = 3 年轮岗期</span></div>' + CH.mini.bars(SENSITIVE_POSTS.map(s => ({ n: s.who + ' · ' + s.post.slice(0, 5), v: yearsSince(s.since), c: yearsSince(s.since) >= s.limit ? '#e5484d' : CPAL[0], unit: ' 年' })), { x0: 96, limit: 3, max: 8, unit: ' 年' }) + '</div></div>'; },
  after() { CH.mount($('#main')); }
};
Object.assign(ACT, {
  'rk-act'(el) { const i = +el.dataset.i; const r = riskAgg()[i]; if (!r) return; const leader = MGR.leaderOf(r.team); const sent = LS.get('risk_sent', {}); const mark = () => { sent[i] = DB.now(); LS.set('risk_sent', sent); DB.log('风险治理', r.g + ' · ' + r.who + ' · ' + r.t); if (S.page === 'risks') render(); };
    if (r.act === 'rotate') { DB.notify(leader, '敏感岗位轮岗提醒 · ' + r.who + '：' + r.t + '，请在本季度内安排交接', '已发'); mark(); XW.answer('轮岗提醒发给' + leader + '了：' + r.who + '的' + r.t.split('，')[0] + '。', null, { confirm: false }); }
    else if (r.act === 'care') { DB.notify(leader, '员工关怀提醒 · ' + r.who + '：' + r.t + '，请安排关怀面谈', '已发'); mark(); XW.answer('关怀提醒发给' + leader + '了，员工关怀页有面谈提纲。', null, { confirm: false }); }
    else if (r.act === 'remind') { DB.notify(leader, '考勤提醒 · ' + r.who + '：' + r.t, '已发'); mark(); XW.answer('提醒发给' + leader + '了。', null, { confirm: false }); }
    else if (r.act === 'talk') { mark(); nav('mcare'); XW.at(600, () => { const f = FOCUS_PEOPLE.find(x => x.who === r.who); ACT['mc-guide']({ dataset: { who: r.who, tag: f ? f.tag : '低绩效' } }); }); }
    else if (r.act === 'transfer') { DB.notify(TEAM3.leader, '借调返岗 · ' + r.who + '（试验班）借调已超 50 天，请确定返岗时间', '已发'); DB.notify(LAB.leader, '借调返岗 · ' + r.who + ' 返岗时间已向配电运维一班催问', '已发', true); mark(); XW.answer('催返岗发给' + TEAM3.leader + '了，' + LAB.leader + '同步知道。', null, { confirm: false }); }
    else { mark(); nav('structure'); }
  }
});

/* ---------- 员工关怀：面谈提纲 · 重点关注人员 · 文化活动管理 ---------- */
const MCAREPG = {
  cult() { const ov = LS.get('culture_dept', {}); return CULTURE_DEPT.concat(LS.get('culture_dept_add', [])).map((c, i) => Object.assign({ i }, c, ov[i] || {})); },
  cultHTML() { return '<div class="tbl"><table class="t"><tr><th>日期</th><th>类型</th><th>活动</th><th>范围</th><th>负责人</th><th>人数</th><th>状态</th><th></th></tr>' + this.cult().map(c => '<tr><td class="mono">' + h(c.d) + '</td><td><span class="tag ' + ({ 主题党日: 'bad', 座谈会: 'c', 团建: 'ok', 迎新会: 'v', 欢送会: '' }[c.kind] || '') + '">' + h(c.kind) + '</span></td><td><b>' + h(c.t) + '</b></td><td>' + h(c.team) + '</td><td>' + h(c.who) + '</td><td class="mono">' + c.n + '</td><td><span class="tag ' + (/已举办|已批/.test(c.st) ? 'ok' : /待/.test(c.st) ? 'w' : '') + '">' + h(c.st) + '</span></td><td>' + (c.st === '待审批' ? '<button class="s g" data-act="cd-approve" data-i="' + c.i + '">批准</button>' : c.st === '待通知' || c.st === '计划中' || c.st === '已批' ? '<button class="s g" data-act="cd-notify" data-i="' + c.i + '">发通知</button>' : '') + '</td></tr>').join('') + '</table></div>'; }
};
PAGES.mcare = {
  render() { const C = MCAREPG.cult(); return cmdHTML(['给王安写绩效面谈提纲', '新员工座谈会发通知', '长病的人有谁']) + pageHead('员工关怀', '团队关系维护：辅导面谈（绩效 / 关键事件 / 关怀）提纲与沟通要点 · 重点关注人员提醒 · 部门文化活动管理', '<button class="s" data-act="cd-add">新增活动</button>') +
      '<div class="grid2" style="grid-template-columns:1.4fr 1fr"><div class="card"><div class="h"><b>重点关注人员</b><span>长病 / 高绩效 / 低绩效 / 借调 / 新员工 · 三班组</span></div>' + FOCUS_PEOPLE.map(f => '<div class="focusrow"><span class="tag ' + ({ 长病: 'bad', 高绩效: 'ok', 低绩效: 'w', 新员工: 'c', 借调: 'v' }[f.tag]) + '">' + h(f.tag) + '</span><b data-act="st-person" data-who="' + f.who + '">' + h(f.who) + '</b><span class="note">' + h(f.team) + ' · ' + h(f.t) + '</span><p>' + h(f.do) + '</p><div class="bt"><button class="s" data-act="mc-guide" data-who="' + f.who + '" data-tag="' + f.tag + '">面谈提纲</button><button class="s g" data-act="mc-remind" data-who="' + f.who + '" data-team="' + h(f.team) + '">提醒班长</button></div></div>').join('') + '</div>' +
      '<div><div class="card"><div class="h"><b>面谈类型与沟通要点</b></div>' + Object.keys(TALK_GUIDES).map(k => '<details class="fold"><summary>' + h(k) + '</summary><div style="padding:4px 10px 8px;font-size:11.5px"><div><b>开场：</b>' + h(TALK_GUIDES[k].open) + '</div><ol style="margin:4px 0;padding-left:18px">' + TALK_GUIDES[k].items.map(x => '<li>' + h(x) + '</li>').join('') + '</ol><div class="note"><b>要点：</b>' + h(TALK_GUIDES[k].tips.join('；')) + '</div></div></details>').join('') + '</div><div class="card doc" id="mcdoc" hidden style="margin-top:10px"></div></div></div>' +
      '<div class="card"><div class="h"><b>部门文化活动管理</b><span>主题党日 · 座谈会 · 团建 · 迎新 / 欢送会 · 本年 ' + C.filter(c => /已举办/.test(c.st)).length + ' 场已办 · ' + C.filter(c => /计划|待/.test(c.st)).length + ' 场在办</span></div>' + MCAREPG.cultHTML() + '</div>'; },
  after() { CH.mount($('#main')); }
};
Object.assign(ACT, {
  'mc-guide'(el) { const who = el.dataset.who, tag = el.dataset.tag; const kind = /高绩效|低绩效/.test(tag) ? '绩效面谈' : /关键/.test(tag) ? '关键事件面谈' : '关怀面谈'; const g = TALK_GUIDES[kind]; const f = FOCUS_PEOPLE.find(x => x.who === who); const host = $('#mcdoc'); if (!host) { ensure('mcare', () => ACT['mc-guide'](el)); return; } host.hidden = false; host.scrollIntoView({ block: 'nearest' }); const who2 = f ? MGR.leaderOf(f.team) : '班长';
    MG.stream(host, ['面谈人：' + who2 + '（班长）· 对象：' + who + (f ? '（' + f.team + '，' + f.tag + '）' : '') + ' · 时间：本周内 · 地点：班组会议室', '开场：' + g.open].concat(g.items.map((it, i) => (i + 1) + '. ' + it), ['本人情况：' + (f ? f.t + '。建议：' + f.do : '见人员档案')], ['沟通要点：' + g.tips.join('；')]), { title: who + ' · ' + kind + '提纲', done() { host.insertAdjacentHTML('beforeend', '<div class="bt"><button data-act="mc-guide-send" data-who="' + who + '" data-kind="' + kind + '" data-to="' + h(who2) + '">发给' + h(who2) + '</button><button class="g" data-act="mc-guide-save" data-who="' + who + '" data-kind="' + kind + '">存入文稿中心</button></div>'); } }); },
  'mc-guide-save'(el) { MG.saveDoc('guide-' + el.dataset.who, el.dataset.who + ' ' + el.dataset.kind + '提纲', $('#mcdoc')); XW.answer('提纲存到文稿中心了。', null, { confirm: false }); },
  'mc-guide-send'(el) { MG.saveDoc('guide-' + el.dataset.who, el.dataset.who + ' ' + el.dataset.kind + '提纲', $('#mcdoc')); DB.notify(el.dataset.to, el.dataset.kind + '提纲 · ' + el.dataset.who + '：已生成，请本周内约谈并把结论写进谈心记录', '已发'); XW.answer('提纲发给' + el.dataset.to + '了，谈完的结论会回到谈心记录。', null, { confirm: false }); },
  'mc-remind'(el) { const f = FOCUS_PEOPLE.find(x => x.who === el.dataset.who); const leader = MGR.leaderOf(el.dataset.team); DB.notify(leader, '重点关注 · ' + f.who + '（' + f.tag + '）：' + f.t + '。' + f.do, '已发'); DB.log('员工关怀', '提醒 ' + leader + ' 关注 ' + f.who); XW.answer('提醒发给' + leader + '了。', null, { confirm: false }); },
  'cd-notify'(el) { const i = +el.dataset.i; const c = MCAREPG.cult().find(x => x.i === i); const ov = LS.get('culture_dept', {}); ov[i] = Object.assign(ov[i] || {}, { st: '已通知' }); LS.set('culture_dept', ov); MGR.teamOrder.forEach(t => DB.notify(MGR.leaderOf(t), '文化活动通知 · ' + c.d + ' ' + c.t + '，请统计参加人员', '已发', true)); DB.log('文化活动', c.t + ' 已通知三个班组'); render(); XW.fly('已通知三位班长'); XW.answer('"' + c.t + '"的通知发给三位班长了，人数统计回来后我更新到表里。', null, { confirm: false }); },
  'cd-approve'(el) { const i = +el.dataset.i; const c = MCAREPG.cult().find(x => x.i === i); const ov = LS.get('culture_dept', {}); ov[i] = Object.assign(ov[i] || {}, { st: '已批' }); LS.set('culture_dept', ov); DB.log('文化活动', c.t + ' 已批准'); render(); XW.answer('"' + c.t + '"批了，接下来点发通知。', null, { confirm: false }); },
  'cd-add'() { modal('<div class="t">新增文化活动</div><div class="jf"><label>类型</label><select id="cd-k"><option>主题党日</option><option>座谈会</option><option>团建</option><option>迎新会</option><option>欢送会</option></select><label>活动</label><input id="cd-t" placeholder="如 班长与青年员工座谈"><label>日期</label><input id="cd-d" value="2026-09-05"><label>负责人</label><input id="cd-w" value="陈国安"><label>预计人数</label><input id="cd-n" type="number" value="20"></div><div class="bt"><button data-act="cd-add-ok">保存</button></div>'); },
  'cd-add-ok'() { const t = ($('#cd-t') || {}).value || ''; if (t.trim().length < 2) { XW.answer('活动名称要写清楚。', null, { confirm: false }); return; } const a = LS.get('culture_dept_add', []); a.push({ d: $('#cd-d').value, kind: $('#cd-k').value, t: t.trim(), team: '三班组', st: '待审批', who: $('#cd-w').value, n: +$('#cd-n').value || 0 }); LS.set('culture_dept_add', a); DB.log('文化活动', '新增 ' + t); $('#modal').hidden = true; render(); XW.answer('加上了，状态待审批。', null, { confirm: false }); }
});

/* ---------- 分析参谋：综合分析报告 + 近五年业务量与人力配置趋势 ---------- */
PAGES.madvise = {
  TABS: [{ k: 'report', n: '综合分析报告' }, { k: 'trend', n: '近五年业务量与人力配置' }],
  render() { const s = S.sub || 'report'; const T = TREND5; const C = trendCalc(); const docs = LS.get('docs', {});
    return cmdHTML(['生成部门综合分析报告', '五年人均工作量涨了多少', '2027 年要不要补人']) + pageHead('分析参谋', '按部门业务指标综合分析 · 近三年 / 五年业务量与人力资源配置变化 · 供后续人力配置作参谋预警') + tabsHTML(this.TABS, s) +
      (s === 'trend' ? '<div class="grid4"><div class="card kpi"><span>业务量（工单）五年</span><b class="' + (C.jobsG > 30 ? 'bad' : 'w') + '">+' + C.jobsG + '%</b><em>' + T.jobs[0] + ' → ' + T.jobs[4] + '（2026 预计）</em></div><div class="card kpi"><span>在编人数五年</span><b>+' + C.headsG + '%</b><em>' + T.heads[0] + ' → ' + T.heads[4] + ' 人</em></div><div class="card kpi"><span>人均工单五年</span><b class="bad">+' + C.perG + '%</b><em>' + C.per[0] + ' → ' + C.per[4] + ' 单 / 人</em></div><div class="card kpi"><span>2027 预警</span><b class="bad">缺 ' + C.need + ' 人</b><em>按 2025 年人均负荷折算；技师及以上 ' + T.senior[0] + ' → ' + T.senior[4] + '</em></div></div>' +
        '<div class="grid2"><div class="card"><div class="h"><b>业务量</b><span>工单 · 缺陷 · 终端数</span></div>' + CH.mini.line([{ n: '工单', vals: T.jobs, c: CPAL[0], area: true }, { n: '终端数', vals: T.terms, c: CPAL[2] }, { n: '缺陷', vals: T.defects, c: CPAL[1] }], T.years, { h: 140 }) + CH.mini.legend([{ n: '工单', c: CPAL[0] }, { n: '终端数', c: CPAL[2] }, { n: '缺陷', c: CPAL[1] }]) + '</div><div class="card"><div class="h"><b>人力配置</b><span>人数 · 平均年龄 · 技师及以上</span></div>' + CH.mini.line([{ n: '在编人数', vals: T.heads, c: CPAL[4] }, { n: '平均年龄', vals: T.avgAge, c: CPAL[3] }, { n: '技师及以上', vals: T.senior, c: CPAL[5] }], T.years, { h: 140, max: 45 }) + CH.mini.legend([{ n: '在编人数', c: CPAL[4] }, { n: '平均年龄', c: CPAL[3] }, { n: '技师及以上', c: CPAL[5] }]) + '</div></div>' +
        '<div class="grid2" style="grid-template-columns:1fr 1.3fr"><div class="card"><div class="h"><b>人均工单</b><span>单 / 人 · 年</span></div>' + CH.mini.cols(T.years.map((y, i) => ({ n: y.replace(' 预计', ''), v: C.per[i], c: i === 4 ? CPAL[1] : CPAL[0] })), { labels: true, h: 130 }) + '<div class="tbl" style="margin-top:6px"><table class="t"><tr><th>班组</th>' + T.years.map(y => '<th>' + h(y.replace(' 预计', '')) + '</th>').join('') + '</tr>' + Object.keys(T.teams).map(n => '<tr><td>' + h(n) + '</td>' + T.teams[n].map(v => '<td class="mono">' + v + '</td>').join('') + '</tr>').join('') + '</table></div></div>' +
        '<div class="card"><div class="h"><b>人力资源配置参谋预警</b><span>由部门确认后使用</span></div><div class="advbox"><p>近五年部门工单 <b>+' + C.jobsG + '%</b>、终端数 <b>+' + C.termsG + '%</b>，在编人数只 <b>+' + C.headsG + '%</b>，人均工单从 ' + C.per[0] + ' 升到 ' + C.per[4] + '（<b>+' + C.perG + '%</b>）；平均年龄从 ' + T.avgAge[0] + ' 升到 ' + T.avgAge[4] + '。</p><p>按当前增速，2027 年人均工单约 <b>' + C.next + '</b>；要维持 2025 年的人均负荷，需增加 <b>' + C.need + '</b> 人；不全靠补人，则需把核心业务自主实施比例再提高约 8 个百分点（减少外委等待）并用跨班组柔性支援削峰。</p><p>建议：① 2027 年编制申请 2 人，优先配电运维一班（人均实操最低、近三年离职 2 人）；② 试验班 2029 年前有 2 名骨干进入退休窗口，2027 年起每年接收 1 名轮岗学员；③ 配电自动化班终端数五年翻 1.7 倍，先用跨班组柔性支援过 2026 年高峰，2027 年再评估定编。</p></div><div class="bt"><button data-act="ma-gen" data-k="hr">生成人力配置参谋报告</button></div></div></div>' +
        '<div class="card doc" id="madoc" hidden></div>'
      : '<div class="grid2" style="grid-template-columns:1fr 1.2fr"><div class="card"><div class="h"><b>综合分析报告</b><span>取数：年度指标任务 · 班组横向对比 · 结构对比 · 风险画像 · 星级建设 · 班长队伍</span></div><div class="jobs">' + [['指标', '年度指标 ' + goalsAll().length + ' 项：红 ' + goalsAll().filter(g => g.light === 'bad').length + ' · 黄 ' + goalsAll().filter(g => g.light === 'w').length + ' · 绿 ' + goalsAll().filter(g => g.light === 'ok').length], ['班组', '最忙 ' + compareAdvice().busy + ' · 最需关注 ' + STRUCPG.strength().filter(s => s.tag === '弱').map(s => s.n).join('、')], ['风险', riskAgg().length + ' 项，高 ' + riskAgg().filter(r => r.lv === '高').length], ['星级', TEAM.name + ' 初步评分 ' + buildScore().pct + '，必备条件缺 ' + buildScore().mustBad.length + ' 项'], ['梯队', '可接任后备 ' + leaderStat().ready + '，培养中 ' + leaderStat().training]].map(x => '<div><span style="white-space:normal;color:var(--ink)"><b>' + h(x[0]) + '</b>　' + h(x[1]) + '</span></div>').join('') + '</div><div class="bt"><button data-act="ma-gen" data-k="all">生成综合分析报告</button>' + (docs['m-all'] ? '<span class="tag ok">上次 ' + new Date(docs['m-all'].ts).toTimeString().slice(0, 5) + '</span>' : '') + '</div></div><div class="card doc" id="madoc"><div class="empty">点"生成综合分析报告"，报告逐段写在这里</div></div></div>'); },
  after() { CH.mount($('#main')); }
};
Object.assign(ACT, {
  'ma-gen'(el) { const k = el.dataset.k; const host = $('#madoc'); if (!host) return; host.hidden = false; host.scrollIntoView({ block: 'nearest' }); const G = goalsAll(); const bad = G.filter(g => g.light === 'bad'), w = G.filter(g => g.light === 'w'); const A = compareAdvice(); const R = riskAgg(); const B = buildScore(); const st = leaderStat(); const S3 = STRUCPG.strength(); const C = trendCalc(); const T = TREND5;
    const paras = k === 'hr' ? ['一、业务量变化：2022–2026 年部门工单 ' + T.jobs[0] + ' → ' + T.jobs[4] + '（+' + C.jobsG + '%），终端数 ' + T.terms[0] + ' → ' + T.terms[4] + '（+' + C.termsG + '%），缺陷 ' + T.defects[0] + ' → ' + T.defects[4] + '。', '二、人力配置变化：在编 ' + T.heads[0] + ' → ' + T.heads[4] + ' 人（+' + C.headsG + '%），平均年龄 ' + T.avgAge[0] + ' → ' + T.avgAge[4] + ' 岁，技师及以上 ' + T.senior[0] + ' → ' + T.senior[4] + ' 人；人均工单 ' + C.per[0] + ' → ' + C.per[4] + '（+' + C.perG + '%）。', '三、预警：按增速 2027 年人均工单约 ' + C.next + '；维持 2025 年人均负荷需增加 ' + C.need + ' 人，建议编制申请 2 人、其余靠自主实施比例与柔性支援消化。试验班平均 ' + teamStat('试验班').avgAge + ' 岁，2029 年前 2 名骨干进入退休窗口；配电运维一班近三年离职 2 人，人均实操最低。', '四、建议：① 2027 年编制申请 2 人，优先配电运维一班；② 试验班 2027 年起每年接收 1 名轮岗学员；③ 2026 年高峰用跨班组柔性支援（本周建议：' + A.idle + ' 借 ' + A.who + ' 到 ' + A.busy + '）；④ 核心业务自主实施比例每年提高 4 个百分点，减少外委等待。以上由部门确认后使用。']
      : ['一、年度指标：' + G.length + ' 项中红灯 ' + bad.length + ' 项（' + bad.map(g => g.n).join('、') + '），黄灯 ' + w.length + ' 项（' + w.map(g => g.n).join('、') + '）。时间进度 ' + YEAR_PCT + '%。', '二、班组横向对比：' + A.busy + '本周人均外勤最高（' + compareRows().find(r => r.k === 'load').num[A.busy] + ' 小时），' + A.idle + '最低，建议借 ' + A.who + ' 支援 3 天。人均核心技能实操量：' + MGR.teamOrder.map(t => t + ' ' + compareRows().find(r => r.k === 'cap').num[t]).join('、') + '。', '三、团队结构：' + S3.map(s => s.n + ' ' + s.tag).join('、') + '；' + STRUCPG.advice()[0].t + '。', '四、风险画像：' + R.length + ' 项，高风险 ' + R.filter(r => r.lv === '高').map(r => r.who + '（' + r.g + '）').join('、') + '；敏感岗位超轮岗期 ' + R.filter(r => r.g === '敏感岗位轮岗').length + ' 个。', '五、星级建设与梯队：' + TEAM.name + ' 初步评分 ' + B.pct + '（' + B.lv + '线），必备条件不满足 ' + B.mustBad.map(d => d.n).join('、') + '；班长后备可接任 ' + st.ready + ' 人、培养中 ' + st.training + ' 人，配电运维一班后备最薄。', '六、本周部署：① 督办红灯指标到责任班组；② 发起 ' + A.who + ' 跨班组调配；③ 敏感岗位轮岗提醒 ' + R.filter(r => r.g === '敏感岗位轮岗').map(r => r.who).join('、') + '；④ 长病与低绩效人员本周面谈。以上由部门确认后使用。'];
    MG.stream(host, paras, { title: TEAM.dept + (k === 'hr' ? ' 人力资源配置参谋报告' : ' 综合分析报告') + ' · ' + TODAY, done() { host.insertAdjacentHTML('beforeend', '<div class="bt"><button data-act="ma-save" data-k="' + k + '">存入文稿中心</button><button class="g" data-act="ma-send" data-k="' + k + '">发三位班长</button></div>'); } }); },
  'ma-save'(el) { MG.saveDoc('m-' + el.dataset.k, TEAM.dept + (el.dataset.k === 'hr' ? ' 人力资源配置参谋报告' : ' 综合分析报告'), $('#madoc')); XW.answer('存到文稿中心了。', null, { confirm: false }); },
  'ma-send'(el) { MG.saveDoc('m-' + el.dataset.k, TEAM.dept + (el.dataset.k === 'hr' ? ' 人力资源配置参谋报告' : ' 综合分析报告'), $('#madoc')); MGR.teamOrder.forEach(t => DB.notify(MGR.leaderOf(t), (el.dataset.k === 'hr' ? '人力资源配置参谋报告' : '部门综合分析报告') + ' 已发，请查看涉及本班组的部署', '已发', true)); XW.fly('已发三位班长'); XW.answer('发给三位班长了。', null, { confirm: false }); }
});
