/* ===== 班组画像：六类信息一屏、12 人、能力图谱 8 模块 × L1–L5、她先说观察再展开图谱 ===== */
const PEOPLEPG = {
  cur: null,
  lv(p) { const conf = LS.get('levels', {})[p.n] || {}; return p.lv.map((v, i) => conf[MODS[i].k] != null ? conf[MODS[i].k] : v); },
  obs(p) {
    const lv = this.lv(p); const rows = HOURS.filter(r => r.who === p.n); const outs = rows.length; const wk = MODS.map((m, i) => ({ m, v: lv[i] })).sort((a, b) => a.v - b.v);
    const weak = wk[0], strong = wk[wk.length - 1]; const due = certsDueWithin(90).filter(c => c.who === p.n);
    if (p.n === '刘一鸣') return ['刘一鸣这两周跟了四次外勤，态度很好，负责人都说他肯问。', '但光差保护那门课的题他答对了两道，二次回路也弱，图谱上"二次及保护能力"还在 L1。', '我建议下周让他跟黄伟强做两次继保旁站，再考一次。要我排进计划吗？'];
    if (p.n === '黄伟强') return ['黄伟强这周已经 26 小时，是全班最多的，连续三周都排第一。', '他是带电作业和负责人资格都有的两个人之一，活自然往他身上堆；"故障分析与处理"L4 是班里最强的。', '我建议下周给他排两天室内，把凤凰线的活分一部分给李文博。要我在值班表里这么排吗？'];
    return [p.n + (p.post.includes('班长') ? '是' + p.post + '，' : '是' + p.post + '，') + '这周 ' + p.week + ' 小时，本月学时 ' + p.hours.m + '/5，年度 ' + p.hours.done + '/' + p.hours.req + '。', '图谱上最强是"' + strong.m.n + '"' + LV[strong.v].slice(0, 2) + '，最弱是"' + weak.m.n + '"' + LV[weak.v].slice(0, 2) + (due.length ? '；' + due[0].name + ' ' + due[0].due + ' 到期，还有 ' + daysTo(due[0].due) + ' 天' : '') + '。', (p.hours.m < 3 ? '这个月学时落后了，我建议把"' + weak.m.n + '"相关的一门课排给他。要我排进计划吗？' : outs >= 3 ? '外勤不少，短板那一格适合安排一次带教。要我排进计划吗？' : '状态平稳，短板那格可以安排一次旁站。要我排进计划吗？')];
  },
  evidence(p, mi) { const m = MODS[mi]; const lv = this.lv(p)[mi]; const rows = HOURS.filter(r => r.who === p.n).slice(0, 2); const ev = [];
    rows.forEach(r => ev.push({ t: r.d + ' ' + r.job + ' ' + r.h + 'h', s: '工时台账' }));
    const c = COURSES.find(c => c.mod === m.k); if (c) ev.push({ t: (p.n === '刘一鸣' && c.id === 'c5' ? '光差保护理论测试 40 分（2/5）' : c.n + ' 理论测试 ' + (60 + lv * 8) + ' 分'), s: '培训考评' });
    const sc = LS.get('scores', {})[p.n]; if (sc) ev.push({ t: sc.sheet + ' 实操 ' + sc.total + ' 分', s: '实操评分表' });
    if (m.k === 'site' && p.cert.includes('工作负责人资格')) ev.push({ t: '近 30 天担任工作负责人 2 次', s: '两票台账' });
    if (m.k === 'fault' && CASES.some(a => a.who === p.n)) ev.push({ t: CASES.find(a => a.who === p.n).t + '（案例）', s: '班组知识库' });
    return ev; },
  show(name) { const p = P[name]; if (!p) return; this.cur = p; $$('.pc').forEach(c => c.classList.toggle('on', c.dataset.who === name)); const lv = this.lv(p); const host = $('#pdetail'); host.scrollIntoView({ block: 'nearest' });
    host.innerHTML = '<div class="h"><b>' + h(p.n) + ' · ' + h(p.post) + '</b><span>' + p.age + ' 岁 · 工龄 ' + p.yrs + ' 年 · ' + h(p.cert.join('、')) + '</span></div><div class="grid2" style="grid-template-columns:1fr 1.2fr"><div><div class="tk on" id="pobs" style="margin:0;min-height:96px;font-style:normal;color:var(--ink)"><span class="lbl">小瓦特的观察</span><span></span></div><div class="bt" id="pbt" style="margin-top:8px"></div></div><div><div class="note" style="margin-bottom:4px">能力图谱 · 8 模块（点一格看依据）</div><div class="mods" id="pmods">' + MODS.map((m, i) => '<div class="mod' + (lv[i] <= 1 || lv[i] === Math.min.apply(null, lv) ? ' weak' : '') + '" data-act="mod" data-i="' + i + '"><span style="text-align:left;color:var(--ink);font-family:var(--sans);font-size:11.5px">' + h(m.n) + '</span><div class="bar"><i data-w="' + (lv[i] * 20) + '"></i></div><span>' + h(LV[lv[i]]) + '</span></div>').join('') + '</div><div class="ev" id="pev"></div></div></div>';
    const obs = this.obs(p); const o = $('#pobs span:last-child'); XW.state('talk'); let i = 0; const next = () => { if (i >= obs.length) { XW.state(''); $('#pbt').innerHTML = '<button data-act="p-plan">排进计划</button><button class="g" data-act="p-advice">培养建议</button><button class="g" data-act="p-talk">谈心提纲</button>'; return; } const s = document.createElement('span'); o.appendChild(s); if (i) s.insertAdjacentText('beforebegin', ' '); XW.type(s, obs[i], 40, () => XW.at(250, next)); if (i === 1) { XW.at(200, () => { $$('#pmods .mod').forEach((m, j) => XW.at(j * 120, () => { m.classList.add('in'); $('i', m).style.width = $('i', m).dataset.w + '%'; })); }); } if (i === 2) XW.at(100, () => $$('#pmods .mod.weak').forEach(m => m.classList.add('pulse'))); i++; }; next();
    XW.type($('#xwsub'), obs[0], 45);
  },
  six() { const due = certsDueWithin(90).length; const avgH = Math.round(PEOPLE.reduce((s, p) => s + p.hours.done / p.hours.req, 0) / PEOPLE.length * 100); const posts = {}; PEOPLE.forEach(p => { const k = p.post.replace(/副班长 · |（学员）/g, ''); posts[k] = (posts[k] || 0) + 1; });
    return [{ k: 'struct', b: PEOPLE.length, s: '人员结构', e: Object.keys(posts).map(k => k.replace('作业员', '') + posts[k]).join(' ') }, { k: 'cert', b: due, s: '证书 90 天内到期', e: certsDueWithin(90).map(c => c.who).join('、') || '无' }, { k: 'hours', b: avgH + '%', s: '年度学时完成', e: PEOPLE.filter(p => p.hours.m < 3).length + ' 人本月未完成' }, { k: 'safety', b: SAFETY_ACT.length, s: '本月安全活动', e: '安全日 ' + MONTH.safetyDays + '/' + MONTH.safetyDaysPlan + ' · 通报学习 1' }, { k: 'jobs', b: MONTH.jobsDone + '/' + MONTH.jobs, s: '本月任务完成', e: '两票合格 ' + MONTH.ticketsOK + '/' + MONTH.tickets }, { k: 'honor', b: HONORS.length, s: '荣誉', e: HONORS[0].who + ' · ' + HONORS[0].t.slice(-4) }]; },
  sixAsk(k) { const map = { struct: () => XW.spot({ title: '人员结构 · 12 人', cols: ['姓名', '岗位', '年龄', '工龄', '状态'], rows: PEOPLE.map(p => [p.n, p.post, p.age, p.yrs, p.status]), me: PEOPLE.map((p, i) => i), text: '一共 12 个人：班长 1、副班长 1、高级作业员 2、中级作业员 4、初级作业员 4（含 1 名学员）。平均年龄 32 岁，工龄 5 年以下的有 5 个，这几年新人多。' }),
      cert: () => { const list = certsDueWithin(90); XW.spot({ title: '资质证书台账 · 90 天内到期', cols: ['姓名', '证书', '取得', '复审期限', '剩余天数'], rows: CERTS.filter(c => !c.renewed).map(c => [c.who, c.name, c.got, c.due, daysTo(c.due)]), me: CERTS.filter(c => !c.renewed).map((c, i) => list.includes(c) ? i : -1).filter(i => i >= 0), text: '三个月内到期的有 ' + list.length + ' 个：' + list.map(c => c.who + '的' + c.name + '（' + c.due + '，还有 ' + daysTo(c.due) + ' 天）').join('、') + '。' + list[0].who + '的最急，复审要提前一个月报名，这周就得报。' }); XW.at(600, () => XW.card('<div class="bt" style="margin-top:0"><button data-act="cert-remind">提醒本人并报名复审</button><button class="g" data-act="nav" data-to="ledger" data-sub="cert">看证书台账</button></div>')); },
      hours: () => { const lag = PEOPLE.filter(p => p.hours.m < 3); XW.spot({ title: '学时台账 · 2026 年（要求 60 学时 / 年，5 学时 / 月）', cols: ['姓名', '本月', '年度已完成', '年度要求', '进度'], rows: PEOPLE.map(p => [p.n, p.hours.m + '/5', p.hours.done, p.hours.req, Math.round(p.hours.done / p.hours.req * 100) + '%']), me: PEOPLE.map((p, i) => lag.includes(p) ? i : -1).filter(i => i >= 0), text: '本月学时没完成的有 ' + lag.length + ' 个：' + lag.map(p => p.n + ' ' + p.hours.m + ' 学时').join('、') + '。按现在的进度，年底达不到 60 学时的是陈浩和周明，我建议把继保专才的课先排给他们。' }); },
      safety: () => XW.spot({ title: '安全活动台账 · 本月', cols: ['日期', '活动', '参加人数'], rows: SAFETY_ACT.map(a => [a.d, a.t, a.who]), me: [0, 1, 2], text: '本月开了一次安全日、一次事故通报学习，第二次安全日还没开，我建议放在周五，主题讲台风季登杆。' }),
      jobs: () => XW.spot({ title: '任务台账 · 本月', cols: ['项目', '数量'], rows: [['作业任务', MONTH.jobs], ['已完成', MONTH.jobsDone], ['工作票', MONTH.tickets], ['合格', MONTH.ticketsOK], ['缺陷发现', MONTH.defectsFound], ['缺陷闭环', MONTH.defectsClosed]], me: [0, 1, 4, 5], text: '本月 38 项任务完成了 35，没完成的三项里有一项超期，就是志远站那条缺陷。两票 12 张全部合格。' }),
      honor: () => XW.spot({ title: '荣誉台账', cols: ['获得者', '荣誉', '时间'], rows: HONORS.map(a => [a.who, a.t, a.d]), me: [0, 1, 2, 3], text: '班组去年拿了安全生产先进班组，韩雪上个月刚评上局级技术能手，李文博技能竞赛三等奖。竞赛人选的话，我会先想到李文博和郭子扬，由你定。' }) }; (map[k] || map.struct)(); },
  heatHTML() { return '<div class="heat" style="grid-template-columns:70px repeat(8,1fr)"><div></div>' + MODS.map(m => '<div class="hd">' + h(m.n.replace('能力', '')) + '</div>').join('') + PEOPLE.map(p => { const lv = this.lv(p); return '<div class="rn">' + h(p.n) + '</div>' + lv.map((v, i) => '<div class="c" data-act="heat" data-who="' + p.n + '" data-i="' + i + '" style="background:' + ['#e6e8f4', '#c9cbf5', '#9a9cf5', '#6f70f0', '#5a5bf0', '#3d3ec7'][v] + '">' + v + '</div>').join(''); }).join('') + '</div>'; }
};
PAGES.people = {
  render() { const six = PEOPLEPG.six(); return cmdHTML(['刘一鸣最近怎么样', '三个月内证书到期的有谁', '本月学时未完成的名单', '谁适合参加下季度的技能竞赛']) + pageHead('班组画像', TEAM.name + ' · 12 人 · 六类信息与能力图谱', '<div class="loop">' + LOOP.map((l, i) => '<div class="' + (i === 0 ? 'on' : '') + '">' + (i + 1) + ' ' + l + '</div>').join('') + '</div>') +
    '<div class="six">' + six.map(s => '<div data-act="six" data-k="' + s.k + '"><b>' + s.b + '</b><span>' + h(s.s) + '</span><em>' + h(s.e) + '</em></div>').join('') + '</div>' +
    '<div class="card"><div class="h"><b>成员</b><span>点一个人，她先说观察，再展开图谱</span></div><div class="pgrid">' + PEOPLE.map(p => '<div class="pc" data-act="person" data-who="' + p.n + '"><div class="av">' + h(p.n[0]) + '</div><div><b>' + h(p.n) + '</b><span>' + h(p.post) + ' · ' + p.week + 'h</span></div><span class="st ' + (p.status === '在岗' ? '' : p.status === '外勤' ? 'o' : 'x') + '">' + h(p.status) + '</span></div>').join('') + '</div></div>' +
    '<div class="card" id="pdetail"><div class="empty">点上面的人</div></div>' +
    '<div class="card"><div class="h"><b>班组能力热力 · 12 人 × 8 模块</b><span>L1 了解 · L2 掌握 · L3 熟练 · L4 精通 · L5 专家 · 点一格看依据</span></div>' + PEOPLEPG.heatHTML() + '</div>'; },
  after() { if (S.sub && P[S.sub]) XW.at(200, () => PEOPLEPG.show(S.sub)); }
};
Object.assign(ACT, {
  person(el) { ensure('people', () => PEOPLEPG.show(el.dataset.who)); },
  six(el) { PEOPLEPG.sixAsk(el.dataset.k); },
  heat(el) { ensure('people', () => { PEOPLEPG.show(el.dataset.who); XW.at(2600, () => ACT.mod({ dataset: { i: el.dataset.i } })); }); },
  mod(el) { const p = PEOPLEPG.cur; if (!p) return; const i = +el.dataset.i; const m = MODS[i]; const lv = PEOPLEPG.lv(p)[i]; const ev = PEOPLEPG.evidence(p, i); const host = $('#pev'); host.innerHTML = '<div class="note" style="opacity:1">' + h(m.n) + ' · ' + h(LV[lv]) + '（' + h(LVDESC[lv]) + '）· 要素：' + h(m.el.join(' / ')) + '</div>' + ev.map(e => '<div>' + h(e.t) + '<span>' + h(e.s) + '</span></div>').join('');
    XW.state('look', '正在指给你看'); $$('#pev div').forEach((d, j) => XW.at(300 + j * 500, () => d.classList.add('in')));
    XW.at(400, () => XW.answer(p.n + '的"' + m.n + '"我定在 ' + LV[lv] + '，依据是' + ev.map(e => e.t).join('、') + '。' + (lv <= 2 ? '往上一级要看下一次考评和一次独立完成的记录。' : '') + '这个等级等你确认。', null, { speak: false }));
    XW.at(900, () => XW.card('<div class="bt" style="margin-top:0"><button data-act="lv-confirm" data-i="' + i + '">确认 ' + h(LV[lv]) + '</button>' + (lv < 5 ? '<button class="g" data-act="lv-up" data-i="' + i + '">调为 ' + h(LV[lv + 1]) + '</button>' : '') + (lv > 1 ? '<button class="g" data-act="lv-down" data-i="' + i + '">调为 ' + h(LV[lv - 1]) + '</button>' : '') + '</div>')); },
  'lv-confirm'(el) { const p = PEOPLEPG.cur; const i = +el.dataset.i; const all = LS.get('levels', {}); all[p.n] = all[p.n] || {}; all[p.n][MODS[i].k] = PEOPLEPG.lv(p)[i]; LS.set('levels', all); XW.answer('记下了，' + p.n + '的"' + MODS[i].n + '"按 ' + LV[PEOPLEPG.lv(p)[i]] + ' 确认，确认人赵立群。', null, { confirm: false }); },
  'lv-up'(el) { const p = PEOPLEPG.cur; const i = +el.dataset.i; const v = PEOPLEPG.lv(p)[i] + 1; const all = LS.get('levels', {}); all[p.n] = all[p.n] || {}; all[p.n][MODS[i].k] = v; LS.set('levels', all); XW.answer('改成 ' + LV[v] + ' 了，确认人赵立群。我把这次调整记进图谱，下次考评再对一遍。', null, { confirm: false }); PEOPLEPG.show(p.n); },
  'lv-down'(el) { const p = PEOPLEPG.cur; const i = +el.dataset.i; const v = PEOPLEPG.lv(p)[i] - 1; const all = LS.get('levels', {}); all[p.n] = all[p.n] || {}; all[p.n][MODS[i].k] = v; LS.set('levels', all); XW.answer('改成 ' + LV[v] + ' 了，确认人赵立群。', null, { confirm: false }); PEOPLEPG.show(p.n); },
  'p-plan'() { const p = PEOPLEPG.cur; const lv = PEOPLEPG.lv(p); const wi = lv.indexOf(Math.min.apply(null, lv)); const c = COURSES.find(c => c.mod === MODS[wi].k) || COURSES[0]; const plan = LS.get('plan', []); plan.push({ who: p.n, t: c.n, when: '下周', ts: Date.now() }); LS.set('plan', plan); XW.fly('已加入下周培训计划 · ' + p.n); XW.answer('排进去了：下周' + p.n + '学《' + c.n + '》，' + (p.n === '刘一鸣' ? '跟黄伟强做两次继保旁站，周五再考一次。' : '学完考一次，成绩回到图谱。') + '培训计划里能看到。', null, { confirm: false }); },
  'p-advice'() { const p = PEOPLEPG.cur; const lv = PEOPLEPG.lv(p); const wi = lv.indexOf(Math.min.apply(null, lv)); const c = COURSES.find(c => c.mod === MODS[wi].k) || COURSES[0]; XW.state('write'); const d = XW.msg('a', p.n + '的培养建议我写一段：<div class="draft"><span></span></div>'); XW.type(d.querySelector('.draft span'), '培养重点：' + MODS[wi].n + '（现 ' + LV[lv[wi]] + '）。\n下季度安排：① 学《' + c.n + '》并通过理论测试；② 跟班内 ' + (p.n === '黄伟强' ? '韩雪' : '黄伟强') + ' 完成两次现场旁站；③ 独立完成一次同类作业并由负责人签字。\n目标：下次季度评价升至 ' + LV[Math.min(5, lv[wi] + 1)] + '。以上由班组长确认后使用。', 30, () => { XW.state(''); d.insertAdjacentHTML('beforeend', '<div class="bt"><button data-act="p-plan">排进计划</button><button class="g" data-act="doc-save-advice">存到文稿中心</button></div>'); }); },
  'p-talk'() { const p = PEOPLEPG.cur; XW.answer('谈心提纲我按他最近的记录列了三个问题：一、这周 ' + p.week + ' 小时外勤，身体和家里有没有吃紧的地方；二、' + (p.hours.m < 3 ? '本月学时只有 ' + p.hours.m + '，是没时间还是课不合适' : '最近哪次作业让他觉得最有把握') + '；三、下一步想往哪个方向走，图谱上最弱的那格他自己怎么看。谈完你说一句，我记进档案。', null, { confirm: false }); },
  'cert-remind'() { const list = certsDueWithin(90); list.forEach(c => XW.fly('已提醒 ' + c.who + ' · ' + c.name + ' 复审')); XW.answer('三个人都提醒了，复审报名我按最早到期的先排，' + list[0].who + '这周报，其他两个下周。', null, { confirm: false }); },
  'doc-save-advice'() { const docs = LS.get('docs', {}); docs['advice-' + PEOPLEPG.cur.n] = { t: PEOPLEPG.cur.n + ' 培养建议', ts: Date.now(), body: $$('.msg .draft').pop().textContent }; LS.set('docs', docs); XW.answer('存到文稿中心了，文件名"' + PEOPLEPG.cur.n + ' 培养建议"。', null, { confirm: false }); }
});
