/* ===== 班组画像：五类指标一屏（结构健康 / 资质底线 / 能力覆盖 / 工作量公平 / 人才培养与输出）、12 人、能力图谱 8 模块 × L1–L5、履职证据（只列证据不打分）、岗评、技能等级、九类核心技能资格与实操量、资质盘点、年龄梯队、指标模型确认记录 ===== */
const PEOPLEPG = {
  cur: null,
  lv(p) { const conf = LS.get('levels', {})[p.n] || {}; return p.lv.map((v, i) => conf[MODS[i].k] != null ? conf[MODS[i].k] : v); },
  obs(p) {
    const lv = this.lv(p); const rows = DB.hours().filter(r => r.who === p.n); const outs = rows.length; const wk = MODS.map((m, i) => ({ m, v: lv[i] })).sort((a, b) => a.v - b.v);
    const weak = wk[0], strong = wk[wk.length - 1]; const due = certsDueWithin(90).filter(c => c.who === p.n); const s9 = skill9Of(p);
    if (p.n === '刘一鸣') return ['刘一鸣这两周跟了四次外勤，态度很好，负责人都说他肯问。', '但光差保护那门课的题他答对了两道，二次回路也弱，图谱上"二次及保护能力"还在 L1；九类核心技能' + (s9.a ? '能自主实施的只有 ' + s9.a + ' 类' : '还没有一类能自主实施') + '。', '我建议下周让他跟黄伟强做两次继保旁站，再考一次；下周一田寮站验收让他随队看成套设备验收。要我排进计划吗？'];
    if (p.n === '黄伟强') return ['黄伟强这周已经 26 小时，是全班最多的，连续三周都排第一。', '他是继保资格和负责人资格都有的骨干，活自然往他身上堆；"故障分析与处理"L4 是班里最强的，九类核心技能里 ' + s9.a + ' 类能自主实施。', '我建议下周给他排两天室内，把永磁终端排查那批活分一部分给李文博。要我在值班表里这么排吗？'];
    return [p.n + '是' + p.post + '，这周 ' + p.week + ' 小时，本月学时 ' + p.hours.m + '/5，年度 ' + p.hours.done + '/' + p.hours.req + '，核心技能 ' + s9.a + ' 类可自主、本年实操 ' + s9.total + ' 次。', '图谱上最强是"' + strong.m.n + '"' + LV[strong.v].slice(0, 2) + '，最弱是"' + weak.m.n + '"' + LV[weak.v].slice(0, 2) + (due.length ? '；' + due[0].name + ' ' + due[0].due + ' 到期，还有 ' + daysTo(due[0].due) + ' 天' : '') + '。', (p.hours.m < 3 ? '这个月学时落后了，我建议把"' + weak.m.n + '"相关的一门课排给他。要我排进计划吗？' : outs >= 3 ? '外勤不少，短板那一格适合安排一次带教。要我排进计划吗？' : '状态平稳，短板那格可以安排一次旁站。要我排进计划吗？')];
  },
  evidence(p, mi) { const m = MODS[mi]; const lv = this.lv(p)[mi]; const rows = DB.hours().filter(r => r.who === p.n).slice(0, 2); const ev = [];
    rows.forEach(r => ev.push({ t: r.d + ' ' + r.job + ' ' + r.h + 'h', s: '工时台账' }));
    const c = COURSES.find(c => c.mod === m.k); if (c) ev.push({ t: (p.n === '刘一鸣' && c.id === 'c5' ? '光差保护理论测试 40 分（2/5）' : (TRAIN_DONE[p.n] || []).includes(c.id) ? c.n + ' 理论测试 ' + (60 + lv * 8) + ' 分' : c.n + ' 未学'), s: '培训考评' });
    const sc = LS.get('scores', {})[p.n]; if (sc) ev.push({ t: sc.sheet + ' 实操 ' + sc.total + ' 分', s: '实操评分表' });
    (SCORE_HIST[p.n] || []).slice(-1).forEach(s => ev.push({ t: s.d + ' ' + s.t + ' ' + s.s + ' 分', s: '成绩记录' }));
    if (m.k === 'site' && p.cert.includes('工作负责人资格')) ev.push({ t: '近 30 天担任工作负责人 ' + Math.max(1, DB.tickets().filter(t => t.lead === p.n).length) + ' 次', s: '两票台账' });
    if (m.k === 'fault' && CASES.concat(CASES2).some(a => a.who === p.n)) ev.push({ t: CASES.concat(CASES2).find(a => a.who === p.n).t + '（案例）', s: '班组知识库' });
    const s9 = skill9Of(p); const si = { ops: 8, com: 5, scada: 6, relay: 3, fault: 6, digi: 7, site: 1, learn: 1 }[m.k]; if (si != null && s9.n[si]) ev.push({ t: SKILL9[si].n + ' 本年实操 ' + s9.n[si] + ' 次（' + (s9.q[si] === 'A' ? '可自主实施' : s9.q[si] === 'B' ? '带教中' : '未具备资格') + '）', s: '工作票 · 实操量' });
    const men = MENTORS.find(x => x.s === p.n); if (men && men.focus === m.n) ev.push({ t: '师带徒：' + men.m + ' 带教（' + men.since + ' 起）', s: '师带徒' });
    return ev; },
  show(name) { const p = P[name]; if (!p) return; this.cur = p; $$('.pc').forEach(c => c.classList.toggle('on', c.dataset.who === name)); const lv = this.lv(p); const host = $('#pdetail'); host.scrollIntoView({ block: 'nearest' }); const hist = LEVEL_HIST[p.n]; const wi = lv.indexOf(Math.min.apply(null, lv)); const si = lv.indexOf(Math.max.apply(null, lv)); const att = ATTEND30[p.n];
    host.innerHTML = '<div class="h"><b>' + h(p.n) + ' · ' + h(p.post) + '</b><span>' + p.age + ' 岁 · 工龄 ' + p.yrs + ' 年 · ' + h(p.cert.join('、')) + '</span></div><div class="grid2" style="grid-template-columns:1fr 1.2fr"><div><div class="tk on" id="pobs" style="margin:0;min-height:96px;font-style:normal;color:var(--ink)"><span class="lbl">小瓦特的观察</span><span></span></div><div class="bt" id="pbt" style="margin-top:8px"></div>' +
      '<div class="note" style="margin:10px 0 2px">成长轨迹 · 近四个季度</div>' + CH.mini.line([{ n: MODS[si].n.replace('能力', ''), vals: hist.map(q => q[si]), c: CPAL[0] }, { n: MODS[wi].n.replace('能力', ''), vals: hist.map(q => q[wi]), c: CPAL[1] }], QUARTERS, { max: 5, h: 110 }) +
      '<div class="note" style="margin:8px 0 2px">近 30 天出勤 · 点一格她说那天</div><div class="att">' + att.map((v, i) => '<i class="a' + v + '" data-act="p-att" data-i="' + i + '" data-tip="' + h(p.n) + ' · ' + (30 - i) + ' 天前 · ' + ['休息', '在岗', '外勤', '休假'][v] + '"></i>').join('') + '</div><div class="legend" style="margin-top:4px"><span><i style="background:#c9cbf5"></i>在岗</span><span><i style="background:#5a5bf0"></i>外勤</span><span><i style="background:#e8791d"></i>休假</span><span><i style="background:#eef0fb"></i>休息</span></div></div>' +
      '<div><div class="note" style="margin-bottom:4px">能力图谱 · 8 模块（点一格看依据）</div><div class="mods" id="pmods">' + MODS.map((m, i) => '<div class="mod' + (lv[i] <= 1 || lv[i] === Math.min.apply(null, lv) ? ' weak' : '') + '" data-act="mod" data-i="' + i + '"><span style="text-align:left;color:var(--ink);font-family:var(--sans);font-size:11.5px">' + h(m.n) + '</span><div class="bar"><i data-w="' + (lv[i] * 20) + '"></i></div><span>' + h(LV[lv[i]]) + '</span></div>').join('') + '</div><div class="ev" id="pev"></div>' +
      '<div class="grid2" style="margin-top:8px"><div><div class="note" style="margin-bottom:2px">证书</div>' + CERTS.filter(c => c.who === p.n).map(c => '<div class="note" style="color:var(--ink);margin:2px 0">' + h(c.name) + ' <span class="tag ' + (c.renewed ? 'ok' : daysTo(c.due) <= 90 ? 'bad' : '') + '">' + (c.renewed ? '已复审' : c.due) + '</span></div>').join('') + '</div><div><div class="note" style="margin-bottom:2px">培训与成绩</div><div class="note" style="color:var(--ink)">已学 ' + (TRAIN_DONE[p.n] || []).length + '/7 门</div>' + (SCORE_HIST[p.n] || []).map(s => '<div class="note" style="color:var(--ink);margin:2px 0">' + h(s.d) + ' ' + h(s.t) + ' <b>' + s.s + '</b></div>').join('') + '</div></div></div></div>' + this.ratingHTML(p);
    const obs = this.obs(p); const o = $('#pobs span:last-child'); XW.state('talk'); let i = 0; const next = () => { if (i >= obs.length) { XW.state(''); $('#pbt').innerHTML = '<button data-act="p-plan">排进计划</button><button class="g" data-act="p-advice">培养建议</button><button class="g" data-act="p-talk">谈心提纲</button><button class="g" data-act="p-radar">图谱对比班组</button>'; return; } const s = document.createElement('span'); o.appendChild(s); if (i) s.insertAdjacentText('beforebegin', ' '); XW.type(s, obs[i], 40, () => XW.at(250, next)); if (i === 1) { XW.at(200, () => { $$('#pmods .mod').forEach((m, j) => XW.at(j * 120, () => { m.classList.add('in'); $('i', m).style.width = $('i', m).dataset.w + '%'; })); }); } if (i === 2) XW.at(100, () => $$('#pmods .mod.weak').forEach(m => m.classList.add('pulse'))); i++; }; next();
    XW.type($('#xwsub'), obs[0], 45);
  },

  /* ---------- 履职证据 · 岗评 · 技能等级 · 九类核心技能：四类都从台账推导，不出分数，结论由班组长确认 ---------- */
  rateCls(t) { return { '已核对': 'ok', '待核对': 'w', '胜任': 'ok', '基本胜任': 'v', '待提升': 'w' }[t] || ''; },
  discHTML(D) { return '<div class="disc"><div><i>数据授权</i><span>' + h(D.auth) + '</span></div><div><i>证据</i><span>' + h(D.ev) + '</span></div><div><i>用途</i><span>' + h(D.use) + '</span></div><div><i>复核</i><span>' + h(D.review) + '</span></div></div>'; },
  ratingHTML(p) {
    const ev = evidenceOf(p), pe = postEvalOf(p), sk = skillOf(p), s9 = skill9Of(p); const conf = LS.get('confirm', {})[p.n];
    const card = (k, n, sub, lvTxt, big, unit, note) => '<div class="rt" data-act="rate" data-k="' + k + '"><div class="rh"><b>' + h(n) + '</b><span>' + h(sub) + '</span></div><div class="rv"><span class="tag ' + this.rateCls(lvTxt) + '">' + h(lvTxt) + '</span><i>' + h(big) + '</i><u>' + h(unit) + '</u></div><div class="rn">' + h(note) + '</div><div class="rf">点开看内容与依据</div></div>';
    return '<div class="sec" style="margin-top:12px"><i class="v"></i><b>履职证据 · 岗评 · 技能等级 · 核心技能</b><span>四类都从台账推导，每条依据指到具体台账；不出分数，结论由班组长确认后使用</span></div><div class="rate3 r4">' +
      card('evid', '履职证据', '2026 年 8 月 · 五类', conf ? '已核对' : '待核对', ev.rows.reduce((s, r) => s + r.ev.length, 0), '条证据', EVID_ITEMS.map(x => x.n).join('、') + '；只列证据，不打分不出等级') +
      card('post', '岗位胜任评价', postKey(p) + ' · 岗位说明书', pe.concl, pe.ok + '/' + pe.n, '项达标', '对照资质准入、专业知识、技能操作、安全履职四类') +
      card('skill', '职业技能等级', '局技能鉴定站认定', sk.cur, sk.score || '—', sk.score ? '分' : '', sk.cur === '未定级' ? '入职满 1 年可申报初级工，' + p.n + '入职 ' + p.yrs + ' 年' : '本等级已 ' + sk.held + ' 年，申报' + sk.next + '需满 ' + sk.need + ' 年；岗位要求 ' + sk.reqLv) +
      card('skill9', '九类核心技能', '星级评价 · 配电自动化', s9.a + '/9 可自主', s9.total, '次实操 · 本年', '资格 A 可自主实施 / B 需带教，由班组长确认；实操量按工作票逐次回写') +
      '</div><div class="ratedet" id="prate"></div>';
  },
  rateDetail(p, k) {
    const ev = list => '<div class="evl">' + list.map(e => '<div><span>' + h(e.t) + '</span><i>' + h(e.s) + '</i></div>').join('') + '</div>';
    if (k === 'evid') { const E = evidenceOf(p); const conf = LS.get('confirm', {})[p.n];
      return '<div class="rdh"><b>履职证据 · 五类 · 只列证据不打分</b><span>2026 年 8 月 · 逐条来自台账 · ' + (conf ? '已核对 ' + h(conf.d) + ' ' + h(conf.by) : '待班组长核对') + '</span></div>' +
        '<div class="tbl"><table class="t rdt"><tr><th>类别</th><th>证据（来自台账）</th><th>取数台账</th></tr>' + E.rows.map(r => '<tr><td><b>' + h(r.n) + '</b></td><td>' + ev(r.ev) + '</td><td class="note">' + h(r.src) + '</td></tr>').join('') + '</table></div>' + this.discHTML(DISCLOSE.evid) +
        '<div class="bt"><button data-act="evid-ok">' + (conf ? '重新核对' : '核对完毕') + '</button><button class="g" data-act="evid-doc">写成履职沟通提纲</button><button class="g" data-act="nav" data-to="ledger" data-sub="task">看任务台账</button></div>'; }
    if (k === 'post') { const pe = postEvalOf(p);
      return '<div class="rdh"><b>岗位胜任能力评价 · 对照岗位说明书</b><span>' + h(postKey(p)) + ' · 局 2026 版岗位说明书 · 结论由班组长确认</span></div>' +
        '<div class="tbl"><table class="t rdt"><tr><th>对照项</th><th>岗位说明书要求</th><th>实际</th><th>依据（来自台账）</th></tr>' +
        pe.rows.map(r => '<tr><td><b>' + h(r.n) + '</b></td><td class="note">' + h(r.req) + '</td><td><span class="tag ' + (r.ok ? 'ok' : 'bad') + '">' + (r.ok ? '达标' : '未达标') + '</span></td><td>' + ev(r.ev) + '</td></tr>').join('') +
        '<tr class="hl"><td><b>结论</b></td><td colspan="3">' + h(pe.ok) + '/' + pe.n + ' 项达标 → <b>' + h(pe.concl) + '</b>' + (pe.concl === '胜任' ? '' : '；未达标项就是下一步的培养重点') + '</td></tr></table></div>' + this.discHTML(DISCLOSE.post) +
        '<div class="bt"><button data-act="post-ok">确认 ' + h(pe.concl) + '</button>' + (pe.concl !== '胜任' ? '<button class="g" data-act="p-plan">按未达标项排培养计划</button>' : '') + '<button class="g" data-act="nav" data-to="ledger" data-sub="cert">看证书台账</button></div>'; }
    if (k === 'skill9') { const s9 = skill9Of(p); const cov = skillCover(); const cap = skill9PerCap();
      return '<div class="rdh"><b>九类核心技能 · 资格与实操量</b><span>星级班组评价标准 · 配电自动化专业 · 资格由班组长确认，实操量按工作票逐次回写</span></div>' +
        '<div class="tbl"><table class="t rdt"><tr><th>核心技能</th><th>实施方式</th><th>需持证</th><th>资格</th><th>本年实操</th><th>班组可自主</th><th></th></tr>' + SKILL9.map((s, i) => { const q = s9.q[i]; const lack = s.need.filter(c => !p.cert.includes(c)); return '<tr><td><b>' + h(s.n) + '</b></td><td class="note">' + h(s.cls) + '</td><td class="note">' + (s.need.length ? h(s.need.join('、')) + (lack.length ? ' <span class="tag bad">缺</span>' : '') : '—') + '</td><td>' + (q === 'A' ? '<span class="tag ok">A 可自主实施</span>' : q === 'B' ? '<span class="tag w">B 需带教</span>' : '<span class="tag">— 不具备</span>') + '</td><td class="mono">' + s9.n[i] + '</td><td class="note">' + cov[i].a.length + ' 人</td><td>' + (q !== 'A' && !lack.length ? '<button class="s" data-act="skill9-set" data-k="' + s.k + '" data-v="A">确认 A</button>' : '') + (q === '-' ? '<button class="s g" data-act="skill9-set" data-k="' + s.k + '" data-v="B">记为带教中</button>' : '') + (q === 'A' ? '<button class="s g" data-act="skill9-set" data-k="' + s.k + '" data-v="B">调回 B</button>' : '') + '</td></tr>'; }).join('') +
        '<tr class="hl"><td><b>合计</b></td><td colspan="2"></td><td>A ' + s9.a + ' · B ' + s9.b + '</td><td class="mono"><b>' + s9.total + '</b></td><td colspan="2" class="note">班组人均 ' + cap + ' 次' + (s9.total < cap * 0.3 && p.post !== '班长' && !/学员/.test(p.post) ? ' · 低于人均 30%，派工时优先安排' : '') + '</td></tr></table></div>' + this.discHTML(DISCLOSE.skill9) +
        '<div class="bt"><button class="g" data-act="nav" data-to="train" data-sub="write">看实操量回写记录</button><button class="g" data-act="nav" data-to="ledger" data-sub="skill9">看核心技能台账</button></div>'; }
    const sk = skillOf(p);
    return '<div class="rdh"><b>职业技能等级 · 认定与申报</b><span>技能等级认定管理办法 · 申报条件</span></div>' +
      '<div class="ladd">' + SKILL_LADDER.slice(1).map((x, i) => '<div class="' + (i + 1 === sk.i ? 'on' : i + 1 < sk.i ? 'ok' : '') + '"><b>' + h(x) + '</b><span>' + (i + 1 === sk.i ? '当前' : i + 1 === sk.i + 1 ? '下一级' : '') + '</span></div>').join('') + '</div>' +
      '<div class="tbl"><table class="t rdt"><tr><th>项目</th><th>内容</th><th>依据</th></tr>' +
      [['现等级', sk.cur + (sk.got === '—' ? '' : '（' + sk.got + ' 取得）'), sk.by === '—' ? '尚未参加认定' : sk.by + ' 认定'],
       ['鉴定成绩', sk.score ? sk.score + ' 分' : '—', '技能等级认定成绩单'],
       ['岗位要求', sk.reqLv + (sk.gap > 0 ? '（还差 ' + sk.gap + ' 级）' : '（已达到）'), postKey(p) + ' 岗位说明书'],
       ['申报下一级', sk.cur === '未定级' ? '入职满 1 年可申报初级工' : '申报' + sk.next + '需本等级满 ' + sk.need + ' 年，现已 ' + sk.held + ' 年' + (sk.can ? '，具备申报条件' : '，还差 ' + (sk.need - sk.held).toFixed(1) + ' 年'), '技能等级认定管理办法 · 申报条件'],
       ['本年考试', ((SCORE_HIST[p.n] || []).map(x => x.d + ' ' + x.t + ' ' + x.s + ' 分').join('；') || '无'), '成绩记录'],
       ['实操考核', (LS.get('scores', {})[p.n] ? LS.get('scores', {})[p.n].sheet + ' ' + LS.get('scores', {})[p.n].total + ' 分' : '本年无实操评分记录'), '实操评分表']
      ].map(r => '<tr><td><b>' + h(r[0]) + '</b></td><td>' + h(r[1]) + '</td><td class="note">' + h(r[2]) + '</td></tr>').join('') + '</table></div>' + this.discHTML(DISCLOSE.skill) +
      '<div class="bt">' + (sk.can && sk.gap > 0 ? '<button data-act="skill-apply">报名下一级认定</button>' : '') + '<button class="g" data-act="nav" data-to="train" data-sub="record">看成绩记录</button><button class="g" data-act="nav" data-to="train" data-sub="sheet">去打实操分</button></div>';
  },
  /* ---------- 五类指标 ---------- */
  FIVE_TAB: { struct: 'hours', cert: 'cert', skill: 'skill9', load: 'hours', grow: 'train' },
  fivePanel() { const F = fiveOf();
    return '<div class="five">' + F.map(f => '<div class="fc"><b>' + h(f.n) + '</b><span>' + h(f.d) + '</span>' + f.items.map((it, i) => '<div class="fi" data-act="five-item" data-k="' + f.k + '" data-i="' + i + '"><i>' + h(it.val) + '</i><em>' + h(it.n) + '</em><u>阈值 ' + h(it.th) + '</u></div>').join('') + '<div class="fb"><button class="s g" data-act="nav" data-to="ledger" data-sub="' + this.FIVE_TAB[f.k] + '">看台账</button><button class="s g" data-act="five-log">指标确认记录</button></div></div>').join('') + '</div>'; },
  confirmPanel() { return '<div class="card"><div class="h"><b>指标模型确认记录</b><span>五类 15 项指标的阈值与取数口径 · 三轮确认 · 全员过目</span></div><div class="jobs">' + CONFIRM_LOG.map(c => '<div><span style="font-size:11.5px;color:var(--ink)">' + h(c.d) + ' · ' + h(c.who) + '<br><span class="note">' + h(c.what) + '</span></span><span class="tag ok">已确认</span></div>').join('') + '</div></div>'; },
  skillCoverHTML() { const cov = skillCover(); return CH.mini.bars(cov.map(c => ({ n: c.s.n.replace(/10kV |配电自动化/g, '').slice(0, 9), v: c.a.length, c: c.risk === '高' ? '#e5484d' : c.risk === '中' ? '#e8791d' : CPAL[4], act: 'skill-cover', k: c.s.k, tip: c.s.n + ' · 可自主 ' + c.a.length + ' 人 · 带教中 ' + c.b.length + ' 人 · 本年实操 ' + c.n + ' 次' })), { max: 12, limit: 3, unit: ' 人', h: 12, x0: 96 }) + '<div class="note" style="margin-top:4px">虚线 = 每类至少 3 人可自主实施；红色为高风险类别，先排带教。人均实操 ' + skill9PerCap() + ' 次，低于人均 30% 的 ' + skill9Low().length + ' 人：' + (skill9Low().map(p => p.n).join('、') || '无') + '。</div>'; },
  /* ---------- 班组资质盘点 ---------- */
  certPanel() { const g = certGap();
    return '<div class="card"><div class="h"><b>班组资质盘点</b><span>持证人数 / 作业下限 · 点一行看是谁</span><div class="r"><button class="s g" data-act="cert-plan">按缺口排取证计划</button></div></div>' +
      '<div class="tbl"><table class="t"><tr><th>资质</th><th>现有</th><th>下限</th><th>缺口</th><th>90 天内到期</th><th>建议培养</th></tr>' +
      g.map(x => '<tr data-act="cert-gap" data-k="' + h(x.k) + '" style="cursor:pointer"><td>' + h(x.k) + '</td><td class="mono">' + x.n + '</td><td class="mono">' + x.need + '</td><td>' + (x.lack ? '<span class="tag bad">缺 ' + x.lack + ' 人</span>' : '<span class="tag ok">满足</span>') + '</td><td>' + (x.due.length ? '<span class="tag w">' + h(x.due.map(c => c.who).join('、')) + '</span>' : '—') + '</td><td class="note">' + h(x.cand.map(p => p.n).join('、') || '—') + '</td></tr>').join('') + '</table></div>' +
      CH.mini.group(g.map(x => x.k.replace('作业', '').replace('资格', '').replace('能力证', '')), [{ n: '现有', vals: g.map(x => x.n), c: CPAL[0] }, { n: '下限', vals: g.map(x => x.need), c: RAMP[2] }], { h: 120, unit: ' 人' }) + CH.mini.legend([{ n: '现有持证', c: CPAL[0] }, { n: '作业下限', c: RAMP[2] }]) + '</div>';
  },
  focusPanel() { const f = trainFocus();
    return '<div class="card"><div class="h"><b>下次培训重点</b><span>资质缺口 + 核心技能带教 + 图谱短板 + 学时落后，合出来的</span><div class="r"><button class="s" data-act="focus-plan">全部排进计划</button></div></div><div class="focus">' +
      f.map((x, i) => '<div data-act="focus-row" data-i="' + i + '"><span class="tag ' + (x.kind === '取证' ? 'bad' : x.kind === '补短板' ? 'v' : x.kind === '核心技能' ? 'c' : 'w') + '">' + h(x.kind) + '</span><div><b>' + h(x.t) + '</b><span class="note">对象：' + h(x.who.join('、') || '待定') + '</span><span class="note">' + h(x.why) + '</span></div><i>' + h(x.when) + '</i></div>').join('') + '</div></div>';
  },
  /* ---------- 年龄结构与梯队 ---------- */
  agePanel() { const st = ageStruct(); const risks = ageRisk(); const ca = certAge(); const avg = ageAvg(PEOPLE);
    return '<div class="grid2" style="grid-template-columns:1fr 1.3fr"><div class="card"><div class="h"><b>年龄结构与五年后推演</b><span>平均 ' + avg + ' 岁 · 点一段看是谁</span></div>' +
      CH.mini.group(st.map(b => b.n.replace(' 岁', '')), [{ n: '现在', vals: st.map(b => b.list.length), c: CPAL[0], act: 'age-band' }, { n: '五年后', vals: ageIn(5), c: CPAL[3] }], { h: 130, max: 6, unit: ' 人' }) + CH.mini.legend([{ n: '现在', c: CPAL[0] }, { n: '五年后（不进人）', c: CPAL[3] }]) +
      '<div class="note" style="margin-top:6px">五年后 41 岁以上从 ' + st.filter(b => b.n === '41–45 岁' || b.n === '46 岁以上').reduce((s, b) => s + b.list.length, 0) + ' 人增到 ' + (ageIn(5)[4] + ageIn(5)[5]) + ' 人；30 岁以下从 ' + (st[0].list.length + st[1].list.length) + ' 人降到 ' + (ageIn(5)[0] + ageIn(5)[1]) + ' 人。不进新人的话，班组重心会整体上移。</div>' +
      '<div class="note" style="margin:8px 0 2px">关键资质持有人的年龄</div><div class="tbl"><table class="t"><tr><th>资质</th><th>持证</th><th>平均年龄</th><th>35 岁以下</th><th>断层风险</th></tr>' +
      ca.map(c => '<tr data-act="cert-gap" data-k="' + h(c.k) + '" style="cursor:pointer"><td>' + h(c.k.replace('作业', '')) + '</td><td class="mono">' + c.hold.length + '/' + c.need + '</td><td class="mono">' + c.avg + '</td><td class="mono ' + (c.young ? '' : 'b') + '">' + c.young + '</td><td><span class="tag ' + (c.risk === '高' ? 'bad' : c.risk === '中' ? 'w' : 'ok') + '">' + c.risk + '</span></td></tr>').join('') + '</table></div></div>' +
      '<div class="card"><div class="h"><b>梯队与断层 · 提前预防</b><span>' + risks.filter(r => r.lv === '高').length + ' 项高风险 · 点一条她给培养人选</span></div><div class="risk">' +
      risks.map((r, i) => '<div class="r" data-act="age-risk" data-i="' + i + '" style="cursor:pointer"><span><b>' + h(r.t) + '</b><br><span class="note">' + h(r.d) + '</span><br><span class="note" style="color:var(--pri)">' + h(r.fix) + '</span></span><span class="tag ' + (r.lv === '高' ? 'bad' : r.lv === '中' ? 'w' : 'ok') + '">' + h(r.lv) + '风险</span></div>').join('') + '</div></div></div>';
  },
  /* ---------- 与台账中心的指标对照 ---------- */
  metricPanel() { const m = metricMap();
    return '<div class="card"><div class="h"><b>指标对照 · 台账中心</b><span>画像上的每个数都来自台账，点「看台账」核对</span></div><div class="mets">' +
      m.map(x => '<div><b>' + h(x.v) + '</b><span>' + h(x.n) + '</span><em>' + h(x.d) + '</em><button class="s g" data-act="nav" data-to="ledger" data-sub="' + h(x.tab) + '">看台账</button></div>').join('') + '</div></div>';
  },
  posts() { const posts = {}; PEOPLE.forEach(p => { const k = postKey(p).replace('作业员', ''); posts[k] = (posts[k] || 0) + 1; }); return posts; },
  six() { const due = certsDueWithin(90).length; const avgH = Math.round(PEOPLE.reduce((s, p) => s + p.hours.done / p.hours.req, 0) / PEOPLE.length * 100); const posts = this.posts(); const m = DB.month();
    return [{ k: 'struct', b: PEOPLE.length, s: '人员结构', e: Object.keys(posts).map(k => k + posts[k]).join(' ') }, { k: 'cert', b: due, s: '证书 90 天内到期', e: certsDueWithin(90).map(c => c.who).join('、') || '无' }, { k: 'hours', b: avgH + '%', s: '年度学时完成', e: PEOPLE.filter(p => p.hours.m < 3).length + ' 人本月未完成' }, { k: 'safety', b: SAFETY_ACT.length, s: '本月安全活动', e: '安全日 ' + m.safetyDays + '/' + m.safetyDaysPlan + ' · 通报学习 1' }, { k: 'jobs', b: m.jobsDone + '/' + m.jobs, s: '本月任务完成', e: '两票合格 ' + m.ticketsOK + '/' + m.tickets }, { k: 'honor', b: HONORS.length, s: '荣誉', e: HONORS[0].who + ' · ' + HONORS[0].t.slice(-4) }]; },
  sixTab: { struct: 'hours', cert: 'cert', hours: 'study', safety: 'safety', jobs: 'task', honor: 'honor' },
  sixAsk(k) { const posts = this.posts(); const m = DB.month(); const map = { struct: () => XW.spot({ title: '人员结构 · 12 人', cols: ['姓名', '岗位', '年龄', '工龄', '状态'], rows: PEOPLE.map(p => [p.n, p.post, p.age, p.yrs, p.status]), me: PEOPLE.map((p, i) => i), text: '一共 12 个人：' + Object.keys(posts).map(k => k + ' ' + posts[k]).join('、') + '。平均年龄 ' + ageAvg(PEOPLE) + ' 岁，工龄 5 年以下的有 ' + PEOPLE.filter(p => p.yrs < 5).length + ' 个，这几年新人多；30 岁以下 ' + PEOPLE.filter(p => p.age <= 30).length + ' 人。' }),
      cert: () => { const list = certsDueWithin(90); XW.spot({ title: '资质证书台账 · 90 天内到期', cols: ['姓名', '证书', '取得', '复审期限', '剩余天数'], rows: CERTS.filter(c => !c.renewed).map(c => [c.who, c.name, c.got, c.due, daysTo(c.due)]), me: CERTS.filter(c => !c.renewed).map((c, i) => list.includes(c) ? i : -1).filter(i => i >= 0), text: '三个月内到期的有 ' + list.length + ' 个：' + list.map(c => c.who + '的' + c.name + '（' + c.due + '，还有 ' + daysTo(c.due) + ' 天）').join('、') + '。' + (list.length ? list[0].who + '的最急，复审要提前一个月报名，这周就得报。' : '') }); XW.at(600, () => XW.chart(CH.mini.timeline(CERTS.filter(c => !c.renewed && daysTo(c.due) <= 365).map(c => ({ n: c.who, t: daysTo(c.due), c: daysTo(c.due) <= 90 ? '#e5484d' : daysTo(c.due) <= 180 ? '#e8791d' : CPAL[0], lbl: daysTo(c.due) <= 90 ? c.who : '', tip: c.who + ' · ' + c.name + ' · ' + c.due })), {}), '未来一年证书到期')); XW.at(900, () => XW.card('<div class="bt" style="margin-top:0"><button data-act="cert-remind">提醒本人并报名复审</button><button class="g" data-act="nav" data-to="ledger" data-sub="cert">看证书台账</button></div>')); },
      hours: () => { const lag = PEOPLE.filter(p => p.hours.m < 3); const behind = PEOPLE.filter(p => p.hours.done < HOURS_DUE - 4); XW.spot({ title: '学时台账 · 2026 年（要求 60 学时 / 年，5 学时 / 月）', cols: ['姓名', '本月', '年度已完成', '年度要求', '进度'], rows: PEOPLE.map(p => [p.n, p.hours.m + '/5', p.hours.done, p.hours.req, Math.round(p.hours.done / p.hours.req * 100) + '%']), me: PEOPLE.map((p, i) => lag.includes(p) ? i : -1).filter(i => i >= 0), text: '本月学时没完成的有 ' + lag.length + ' 个：' + lag.map(p => p.n + ' ' + p.hours.m + ' 学时').join('、') + '。按现在的进度，年底达不到 60 学时的是' + (behind.map(p => p.n).join('、') || '没有人') + '，我建议把继保专才的课先排给他们。' }); XW.at(600, () => XW.chart(CH.mini.bars(PEOPLE.map(p => ({ n: p.n, v: p.hours.done, c: p.hours.done < HOURS_DUE ? '#e8791d' : CPAL[4], tip: p.n + ' 年度 ' + p.hours.done + '/60' })), { max: 60, limit: HOURS_DUE, h: 12 }), '年度学时 · 虚线为 8 月应达进度')); },
      safety: () => XW.spot({ title: '安全活动台账 · 近期', cols: ['日期', '活动', '参加人数'], rows: SAFETY_ACT.map(a => [a.d, a.t, a.who]), me: [0, 1, 2], text: '这个月开了一次安全日、一次事故通报学习，第二次安全日还没开，我建议放在下周五，主题讲二次室作业验电与交换机取电复核。' }),
      jobs: () => { XW.spot({ title: '任务台账 · 本月', cols: ['项目', '数量'], rows: [['作业任务', m.jobs], ['已完成', m.jobsDone], ['工作票', m.tickets], ['合格', m.ticketsOK], ['缺陷发现', m.defectsFound], ['缺陷闭环', m.defectsClosed]], me: [0, 1, 4, 5], text: '本月 ' + m.jobs + ' 项任务完成了 ' + m.jobsDone + '，没完成的里有一项超期，就是华发民公用柜那条应用失败。两票 ' + m.tickets + ' 张' + (m.ticketsOK === m.tickets ? '全部合格' : '，合格 ' + m.ticketsOK) + '。' }); XW.at(600, () => XW.chart(CH.mini.group(PLAN_M.map(p => p.k.slice(0, 4)), [{ n: '计划', vals: PLAN_M.map(p => p.plan), c: RAMP[2] }, { n: '完成', vals: PLAN_M.map(p => p.done), c: CPAL[0] }], { h: 120 }), '八类任务 · 计划 / 完成')); },
      honor: () => XW.spot({ title: '荣誉台账', cols: ['获得者', '荣誉', '时间'], rows: HONORS.map(a => [a.who, a.t, a.d]), me: [0, 1, 2, 3], text: '班组去年拿了安全生产先进班组，韩雪上个月刚评上局级技术能手，李文博技能竞赛三等奖。竞赛人选的话，我会先想到李文博和郭子扬，由你定。' }) }; (map[k] || map.struct)(); if (k !== 'cert') XW.at(1300, () => XW.card('<div class="bt" style="margin-top:0"><button class="g" data-act="nav" data-to="ledger" data-sub="' + (this.sixTab[k] || 'hours') + '">打开对应台账核对</button></div>')); },
  heatHTML() { return '<div class="heat" style="grid-template-columns:70px repeat(8,1fr)"><div></div>' + MODS.map(m => '<div class="hd">' + h(m.n.replace('能力', '')) + '</div>').join('') + PEOPLE.map(p => { const lv = this.lv(p); return '<div class="rn">' + h(p.n) + '</div>' + lv.map((v, i) => '<div class="c" data-act="heat" data-who="' + p.n + '" data-i="' + i + '" style="background:' + ['#e6e8f4', '#c9cbf5', '#9a9cf5', '#6f70f0', '#5a5bf0', '#3d3ec7'][v] + '">' + v + '</div>').join(''); }).join('') + '</div>'; },
  certMatrix() { const kinds = CERT_KINDS; return '<div class="tbl"><table class="t cmx"><tr><th></th>' + kinds.map(k => '<th>' + h(k.replace('作业', '').replace('资格', '').replace('能力证', '')) + '</th>').join('') + '</tr>' + PEOPLE.map(p => '<tr><td>' + h(p.n) + '</td>' + kinds.map(k => { const c = CERTS.find(x => x.who === p.n && x.name === k); const st = !c ? (p.cert.includes(k) ? 'ok' : 'no') : c.renewed ? 'ok' : daysTo(c.due) <= 90 ? 'due' : 'ok'; return '<td><i class="cm ' + st + '" data-act="p-cert" data-who="' + p.n + '" data-cert="' + k + '" data-tip="' + h(p.n) + ' · ' + h(k) + ' · ' + (st === 'no' ? '无' : !c ? '有效' : c.renewed ? '已复审' : c.due + '（' + daysTo(c.due) + ' 天）') + '"></i></td>'; }).join('') + '</tr>').join('') + '</table></div><div class="legend" style="margin-top:6px"><span><i style="background:#18b97a"></i>有效</span><span><i style="background:#e5484d"></i>90 天内到期</span><span><i style="background:#e6e8f4"></i>无</span></div>'; }
};
PAGES.people = {
  render() { const posts = PEOPLEPG.posts(); const ages = [['20–29', PEOPLE.filter(p => p.age < 30).length], ['30–39', PEOPLE.filter(p => p.age >= 30 && p.age < 40).length], ['40+', PEOPLE.filter(p => p.age >= 40).length]]; const yrs = [['≤2 年', PEOPLE.filter(p => p.yrs <= 2).length], ['3–9 年', PEOPLE.filter(p => p.yrs >= 3 && p.yrs < 10).length], ['10 年+', PEOPLE.filter(p => p.yrs >= 10).length]]; const avgW = PEOPLE.filter(p => p.post !== '班长').reduce((s, p) => s + p.week, 0) / 11;
    return cmdHTML(['刘一鸣最近怎么样', '三个月内证书到期的有谁', '本月学时未完成的名单', '谁适合参加下季度的技能竞赛', '黄伟强最近怎么样']) + pageHead('班组画像', TEAM.name + ' · 12 人 · 五类指标 · 能力图谱 · 九类核心技能', '<div class="loop">' + LOOP.map((l, i) => '<div class="' + (i === 0 ? 'on' : '') + '">' + (i + 1) + ' ' + l + '</div>').join('') + '</div>') +
    PEOPLEPG.fivePanel() +
    '<div class="grid3 charts"><div class="card chart"><div class="h"><b>岗位结构</b><span>点一段看人</span></div>' + CH.mini.donut(Object.keys(posts).map((k, i) => ({ k, v: posts[k], c: CPAL[i], act: 'p-post', tip: k + ' ' + posts[k] + ' 人' })), { sub: '人' }) + '</div><div class="card chart"><div class="h"><b>年龄 / 工龄</b><span>人数</span></div>' + CH.mini.group(['20–29', '30–39', '40+'], [{ n: '年龄段', vals: ages.map(a => a[1]), c: CPAL[2] }], { h: 100, max: 8 }) + CH.mini.group(yrs.map(y => y[0]), [{ n: '工龄段', vals: yrs.map(y => y[1]), c: CPAL[5] }], { h: 100, max: 8 }) + '</div><div class="card chart"><div class="h"><b>年度学时进度</b><span>虚线 = 8 月应达 ' + HOURS_DUE + '</span></div>' + CH.mini.bars(PEOPLE.map(p => ({ n: p.n, v: p.hours.done, c: p.hours.done < HOURS_DUE ? '#e8791d' : CPAL[4], act: 'p-hours', who: p.n, tip: p.n + ' 年度 ' + p.hours.done + '/60 · 本月 ' + p.hours.m + '/5' })), { max: 60, limit: HOURS_DUE, h: 12 }) + '</div></div>' +
    '<div class="grid2" style="grid-template-columns:1.3fr 1fr">' + PEOPLEPG.certPanel() + PEOPLEPG.focusPanel() + '</div>' + PEOPLEPG.agePanel() +
    '<div class="card"><div class="h"><b>成员</b><span>点一个人，她先说观察，再展开图谱</span></div><div class="pgrid">' + PEOPLE.map(p => '<div class="pc" data-act="person" data-who="' + p.n + '"><div class="av">' + h(p.n[0]) + '</div><div><b>' + h(p.n) + '</b><span>' + h(p.post) + ' · ' + p.week + 'h · 核心技能 ' + skill9Of(p).a + '/9</span></div><span class="st ' + (p.status === '在岗' ? '' : p.status === '外勤' ? 'o' : 'x') + '">' + h(p.status) + '</span></div>').join('') + '</div></div>' +
    '<div class="card" id="pdetail"><div class="empty">点上面的人</div></div>' +
    '<div class="grid2"><div class="card"><div class="h"><b>资质矩阵 · 12 人 × 6 类证书</b><span>点一格她说</span></div>' + PEOPLEPG.certMatrix() + '</div><div class="card"><div class="h"><b>工作量公平 · 本周</b><span>均值 ' + avgW.toFixed(1) + 'h · 点一条看台账</span></div>' + CH.mini.bars(PEOPLE.filter(p => p.post !== '班长').sort((a, b) => b.week - a.week).map(p => ({ n: p.n, v: p.week, c: p.week >= WEEK_LIMIT ? '#e5484d' : p.week < avgW / 2 ? RAMP[2] : CPAL[0], act: 'ch-hours', who: p.n, tip: p.n + ' 本周 ' + p.week + 'h' })), { limit: WEEK_LIMIT, unit: 'h', max: 30, h: 13 }) + '<div class="note" style="margin-top:4px">最高与最低相差 ' + (Math.max.apply(null, PEOPLE.map(p => p.week)) - Math.min.apply(null, PEOPLE.filter(p => p.post !== '班长' && p.status !== '休假').map(p => p.week))) + ' 小时；黄伟强连续三周最高。</div><div class="bt"><button class="s g" data-act="wk-balance">让她看下周是否均衡</button></div></div></div>' +
    '<div class="grid2"><div class="card"><div class="h"><b>核心技能覆盖 · 九类</b><span>可自主实施人数 · 点一类看是谁</span></div>' + PEOPLEPG.skillCoverHTML() + '</div><div class="card"><div class="h"><b>出勤 · 近 30 天</b><span>在岗 / 外勤 / 休假 · 点一格</span></div>' + CH.mini.heat(PEOPLE.map(p => p.n), [...Array(30)].map((_, i) => i % 5 === 0 ? (30 - i) + '天前' : ''), PEOPLE.map(p => ATTEND30[p.n]), { colors: ['#eef0fb', '#c9cbf5', '#5a5bf0', '#e8791d'], act: 'p-attcell', fmt: v => ['休息', '在岗', '外勤', '休假'][v] }) + '</div></div>' +
    '<div class="grid2"><div class="card"><div class="h"><b>师带徒 · 谈心 · 培养计划</b></div><div class="note" style="margin-bottom:2px">师带徒</div><div class="jobs">' + MENTORS.map(m => '<div data-act="mentor" data-m="' + m.m + '" style="cursor:pointer"><span style="font-size:11.5px;color:var(--ink)">' + h(m.m) + ' → ' + h(m.s) + '<br><span class="note">' + h(m.since) + ' 起 · ' + h(m.focus) + '</span></span><span class="tag v">带教中</span></div>').join('') + '</div><div class="note" style="margin:8px 0 2px">谈心记录</div><div class="jobs">' + TALKS.map(t => '<div><span style="font-size:11.5px;color:var(--ink)">' + h(t.who) + ' · ' + h(t.d) + '<br><span class="note">' + h(t.t) + '</span></span><span class="tag">' + h(t.by) + '</span></div>').join('') + '</div><div class="note" style="margin:8px 0 2px">培养计划</div><div class="jobs">' + (LS.get('plan', []).length ? LS.get('plan', []).map(p => '<div><span style="font-size:11.5px;color:var(--ink)">' + h(p.who) + ' · ' + h(p.t) + '</span><span class="tag">' + h(p.when) + '</span></div>').join('') : '<div class="note">还没有新增的培养计划；点上面的人，她会给建议</div>') + '</div></div>' + PEOPLEPG.confirmPanel() + '</div>' +
    PEOPLEPG.metricPanel() +
    '<div class="grid2" style="grid-template-columns:1fr 2fr"><div class="card"><div class="h"><b>荣誉墙</b></div>' + HONORS.map(a => '<div class="honor"><b>' + h(a.who) + '</b><span>' + h(a.t) + '</span><i>' + h(a.d) + '</i></div>').join('') + '</div><div class="card"><div class="h"><b>班组能力热力 · 12 人 × 8 模块</b><span>L1 了解 · L2 掌握 · L3 熟练 · L4 精通 · L5 专家 · 点一格看依据</span></div>' + PEOPLEPG.heatHTML() + '</div></div>'; },
  after() { CH.mount($('#main')); if (S.sub && P[S.sub]) XW.at(200, () => PEOPLEPG.show(S.sub)); }
};
Object.assign(ACT, {
  /* 四类：展开内容与依据 */
  rate(el) { const p = PEOPLEPG.cur; if (!p) return; const k = el.dataset.k; const host = $('#prate'); if (!host) return;
    $$('.rt').forEach(x => x.classList.toggle('on', x === el)); host.innerHTML = PEOPLEPG.rateDetail(p, k); CH.mount(host); host.scrollIntoView({ block: 'nearest' });
    if (k === 'evid') { const E = evidenceOf(p); const n = E.rows.reduce((s, r) => s + r.ev.length, 0);
      XW.answer(p.n + '的履职证据我列了 ' + n + ' 条，五类各有来源：' + E.rows.map(r => r.n + ' ' + r.ev.length + ' 条').join('、') + '。不打分不出等级，每条后面标着取数台账，你逐条核对后用于沟通；正式绩效走公司绩效系统。', null, { speak: false }); }
    else if (k === 'post') { const pe = postEvalOf(p); const bad = pe.rows.filter(r => !r.ok);
      XW.answer(p.n + '按' + postKey(p) + '的岗位说明书对了四类，' + pe.ok + ' 项达标，结论是' + pe.concl + '。' + (bad.length ? '没达标的是' + bad.map(r => r.n + '（' + r.req + '）').join('、') + '，这几项就是下一步的培养重点。' : '四类都达标。') + '结论等你确认。', null, { speak: false }); }
    else if (k === 'skill9') { const s9 = skill9Of(p); const cap = skill9PerCap(); const lack = SKILL9.filter((s, i) => s9.q[i] !== 'A' && s.need.some(c => !p.cert.includes(c)));
      XW.answer(p.n + '九类核心技能里 ' + s9.a + ' 类可自主实施、' + s9.b + ' 类带教中，本年实操 ' + s9.total + ' 次，班组人均 ' + cap + ' 次。' + (lack.length ? lack.map(s => s.n).join('、') + '要先取证才能算资格。' : '') + '资格要变由你确认，我只按工作票记实操次数。', null, { speak: false }); }
    else { const sk = skillOf(p);
      XW.answer(p.n + '现在是' + sk.cur + (sk.got === '—' ? '' : '，' + sk.got + ' 取得，鉴定成绩 ' + sk.score + ' 分') + '。岗位要求' + sk.reqLv + (sk.gap > 0 ? '，还差 ' + sk.gap + ' 级' : '，已经达到') + '。' + (sk.cur === '未定级' ? '入职满一年就能申报初级工，他现在 ' + p.yrs + ' 年。' : sk.can ? '本等级已满 ' + sk.held + ' 年，具备申报' + sk.next + '的条件，可以报名。' : '申报' + sk.next + '要满 ' + sk.need + ' 年，他现在 ' + sk.held + ' 年，还差 ' + (sk.need - sk.held).toFixed(1) + ' 年。'), null, { speak: false }); } },
  'evid-ok'() { const p = PEOPLEPG.cur; if (!p) return; const all = LS.get('confirm', {}); all[p.n] = { d: TODAY.slice(5), by: '赵立群', ts: Date.now() }; LS.set('confirm', all); DB.log('履职证据', p.n + ' 8 月证据核对完毕'); XW.fly('履职证据已核对 · ' + p.n); const host = $('#prate'); if (host) host.innerHTML = PEOPLEPG.rateDetail(p, 'evid'); const c = $('.rt[data-k="evid"] .rv .tag'); if (c) { c.textContent = '已核对'; c.className = 'tag ok'; } XW.answer('记下了：' + p.n + ' 8 月的履职证据核对完毕，核对人赵立群。这份不出等级，沟通的时候照着证据说。', null, { confirm: false }); },
  'evid-doc'() { const p = PEOPLEPG.cur; if (!p) return; const E = evidenceOf(p); const first = k => (E.rows.find(r => r.k === k) || { ev: [{ t: '' }] }).ev[0].t; const s9 = skill9Of(p);
    XW.state('write'); const d = XW.msg('a', p.n + ' 的履职沟通提纲：<div class="draft"><span></span></div>');
    XW.type(d.querySelector('.draft span'), '一、本月证据回顾：安全生产——' + first('safe') + '；任务完成——' + first('task') + '。\n二、做得好的：' + first('qual') + '；' + first('coop') + '。\n三、要跟进的：' + first('study') + (s9.a < 3 ? '；九类核心技能可自主实施 ' + s9.a + ' 类，先把带教中的那类做出独立记录' : '') + '。\n四、下月约定：' + (p.hours.m < 3 ? '每月学时不少于 5，缺的课这个月补齐' : '按派工按期完成，超期前提前说') + '；下次班组带教或案例提交一次。\n五、以上为沟通参考，只列证据不出等级，由班组长确认后使用。', 26, () => { XW.state(''); d.insertAdjacentHTML('beforeend', '<div class="bt"><button data-act="evid-ok">核对完毕</button><button class="g" data-act="doc-save-advice">存到文稿中心</button></div>'); }); },
  'post-ok'() { const p = PEOPLEPG.cur; const pe = postEvalOf(p); const all = LS.get('posteval', {}); all[p.n] = { concl: pe.concl, ok: pe.ok, ts: Date.now() }; LS.set('posteval', all); DB.log('岗评', p.n + ' ' + pe.concl); XW.fly('岗评已确认 · ' + p.n + ' ' + pe.concl); XW.answer('记下了：' + p.n + ' 岗位胜任评价' + pe.concl + '，确认人赵立群。' + (pe.concl !== '胜任' ? '没达标的那几项我放进了培养重点。' : ''), null, { confirm: false }); },
  'skill-apply'() { const p = PEOPLEPG.cur; const sk = skillOf(p); DB.notify(p.n, sk.next + ' 技能等级认定报名', '已读', true); DB.log('技能等级', p.n + ' 报名 ' + sk.next); XW.fly('已报名 · ' + p.n + ' ' + sk.next + ' 认定'); XW.answer('给' + p.n + '报了' + sk.next + '的认定，本等级已满 ' + sk.held + ' 年，符合申报条件。鉴定前他要补的是实操，我把对应的评分表排进培训计划。', null, { confirm: false }); },
  'skill9-set'(el) { const p = PEOPLEPG.cur; if (!p) return; const k = el.dataset.k, v = el.dataset.v; const s = SKILL9.find(x => x.k === k); DB.setSkillQ(p.n, k, v); XW.fly((v === 'A' ? '核心技能资格已确认 · ' : '记为带教中 · ') + p.n + ' · ' + s.n); const host = $('#prate'); if (host) { host.innerHTML = PEOPLEPG.rateDetail(p, 'skill9'); CH.mount(host); } const s9 = skill9Of(p); const c = $('.rt[data-k="skill9"] .rv .tag'); if (c) c.textContent = s9.a + '/9 可自主'; XW.answer('记下了：' + p.n + '的「' + s.n + '」' + (v === 'A' ? '按可自主实施确认，确认人赵立群。下次派这类活，他可以做负责人或独立班员，派工校验会按新资格算。' : '记为带教中，派工时随队，做满记录再确认。'), null, { confirm: false }); },
  /* 五类指标 */
  'five-item'(el) { const f = fiveOf().find(x => x.k === el.dataset.k); if (!f) return; const it = f.items[+el.dataset.i]; if (!it) return; XW.answer(f.n + ' · ' + it.n + '：现在 ' + it.val + '，阈值 ' + it.th + '。取数来自' + it.src + '；' + it.use + '，责任人' + it.who + '。', null, { confirm: false, done() { XW.card('<div class="bt" style="margin-top:0"><button class="g" data-act="nav" data-to="ledger" data-sub="' + PEOPLEPG.FIVE_TAB[f.k] + '">看台账核对</button><button class="g" data-act="five-log">看指标确认记录</button></div>'); } }); },
  'five-log'() { modal('<div class="t">指标模型确认记录</div><div class="note" style="margin-bottom:6px">五类 15 项指标的阈值与取数口径，三轮确认后全员过目；改阈值要重新走一遍确认。</div><div class="tbl"><table class="t"><tr><th>日期</th><th>确认人</th><th>内容</th></tr>' + CONFIRM_LOG.map(c => '<tr><td class="mono">' + h(c.d) + '</td><td>' + h(c.who) + '</td><td>' + h(c.what) + '</td></tr>').join('') + '</table></div>'); },
  'skill-cover'(el) { const c = skillCover().find(x => x.s.k === el.dataset.k); if (!c) return; const s = c.s;
    XW.spot({ title: '核心技能 · ' + s.n, cols: ['姓名', '岗位', '资格', '本年实操', '需持证'], rows: PEOPLE.map(p => { const q = skill9Of(p); const i = SKILL9.indexOf(s); return [p.n, p.post, q.q[i] === 'A' ? 'A 可自主' : q.q[i] === 'B' ? 'B 带教中' : '—', q.n[i], s.need.length ? (s.need.every(x => p.cert.includes(x)) ? '有' : '缺 ' + s.need.filter(x => !p.cert.includes(x)).join('、')) : '不需要']; }), me: PEOPLE.map((p, i) => skill9Of(p).q[SKILL9.indexOf(s)] === 'A' ? i : -1).filter(i => i >= 0),
      text: s.n + '：可自主实施 ' + c.a.length + ' 人（' + (c.a.map(p => p.n).join('、') || '无') + '），带教中 ' + c.b.length + ' 人（' + (c.b.map(p => p.n).join('、') || '无') + '），本年实操 ' + c.n + ' 次。' + (c.risk === '高' ? '不到 3 人能自主，这类活一旦碰上就只能靠这几个人，先排带教。' : c.risk === '中' ? '够用但不宽裕。' : '覆盖没问题。') });
    if (c.b.length) XW.at(1200, () => XW.card('<div class="bt" style="margin-top:0"><button data-act="skill-teach" data-k="' + s.k + '">给带教中的 ' + c.b.length + ' 人排实操</button><button class="g" data-act="nav" data-to="ledger" data-sub="skill9">看核心技能台账</button></div>')); },
  'skill-teach'(el) { const c = skillCover().find(x => x.s.k === el.dataset.k); if (!c) return; const plan = LS.get('plan', []); c.b.forEach(p => plan.push({ who: p.n, t: c.s.n + ' 带教实操', when: '9 月', ts: Date.now() })); LS.set('plan', plan); DB.log('培训计划', c.s.n + ' 带教实操：' + c.b.map(p => p.n).join('、')); XW.fly('已排进培养计划 · ' + c.b.map(p => p.n).join(' · ')); if (S.page === 'people') render(); XW.answer('排好了：9 月' + c.b.map(p => p.n).join('、') + '跟' + (c.a[0] ? c.a[0].n : '有资格的人') + '做「' + c.s.n + '」，做满两次独立记录你再确认 A。', null, { confirm: false }); },
  /* 资质盘点 */
  'cert-gap'(el) { const k = el.dataset.k; const g = certGap().find(x => x.k === k); const ca = certAge().find(x => x.k === k); if (!g) return;
    XW.spot({ title: '证书台账 · ' + k, cols: ['姓名', '岗位', '年龄', '取得', '复审期限', '剩余'], rows: PEOPLE.map(p => { const c = CERTS.find(x => x.who === p.n && x.name === k); return [p.n, p.post, p.age, c ? c.got : '—', c ? (c.renewed ? '已复审 ' + c.renewed : c.due) : (p.cert.includes(k) ? '有效' : '未取得'), c && !c.renewed ? daysTo(c.due) + ' 天' : '—']; }), me: PEOPLE.map((p, i) => p.cert.includes(k) ? i : -1).filter(i => i >= 0),
      text: k + '现在 ' + g.n + ' 人持证，班组下限是 ' + g.need + ' 人（' + g.why + '）。' + (g.lack ? '缺 ' + g.lack + ' 人。' : '够用。') + (ca ? '持证人平均 ' + ca.avg + ' 岁，35 岁以下 ' + ca.young + ' 人，断层风险' + ca.risk + '。' : '') + (g.lack ? '我建议先给' + g.cand.map(p => p.n + '（' + p.age + ' 岁 · ' + p.yrs + ' 年）').join('、') + '报名，人选由你定。' : '') });
    if (g.lack) XW.at(900 + PEOPLE.filter(p => p.cert.includes(k)).length * 1000, () => XW.card('<div class="bt" style="margin-top:0"><button data-act="cert-train" data-k="' + h(k) + '">排进取证计划</button><button class="g" data-act="nav" data-to="ledger" data-sub="cert">看证书台账</button></div>')); },
  'cert-train'(el) { const k = el.dataset.k; const g = certGap().find(x => x.k === k); const plan = LS.get('plan', []); g.cand.forEach(p => plan.push({ who: p.n, t: k + ' 取证培训', when: '10 月', ts: Date.now() })); LS.set('plan', plan); DB.log('培训计划', k + ' 取证：' + g.cand.map(p => p.n).join('、')); XW.fly('已排进取证计划 · ' + g.cand.map(p => p.n).join(' · ')); if (S.page === 'people') render(); XW.answer('排进去了：10 月' + g.cand.map(p => p.n).join('、') + '报' + k + '。取证后' + k + '就有 ' + (g.n + g.cand.length) + ' 人，达到下限。', null, { confirm: false }); },
  'cert-plan'() { const gaps = certGap().filter(g => g.lack); if (!gaps.length) { if (S.page === 'people') render(); XW.answer('六类资质现在都到下限了，没有要补的。', null, { confirm: false }); return; } const plan = LS.get('plan', []); gaps.forEach(g => g.cand.forEach(p => plan.push({ who: p.n, t: g.k + ' 取证培训', when: '10 月', ts: Date.now() }))); LS.set('plan', plan); DB.log('培训计划', '按资质缺口排取证：' + gaps.map(g => g.k).join('、')); XW.fly('取证计划已排 · ' + gaps.reduce((s, g) => s + g.cand.length, 0) + ' 人次'); XW.answer('按缺口排好了：' + gaps.map(g => g.k + '缺 ' + g.lack + ' 人，报' + g.cand.map(p => p.n).join('、')).join('；') + '。都排在 10 月，人选由你定。', null, { confirm: false, chart: CH.mini.group(certGap().map(x => x.k.replace('作业', '').replace('资格', '').replace('能力证', '')), [{ n: '现有', vals: certGap().map(x => x.n), c: CPAL[0] }, { n: '取证后', vals: certGap().map(x => x.n + x.cand.length), c: CPAL[4] }, { n: '下限', vals: certGap().map(x => x.need), c: RAMP[2] }], { h: 110, unit: ' 人' }) }); },
  'focus-row'(el) { const f = trainFocus()[+el.dataset.i]; if (!f) return; XW.answer(f.t + '：' + f.why + '。对象是' + (f.who.join('、') || '待定') + '，时间' + f.when + '。要排进培训计划吗？', h(f.t) + '：' + h(f.why) + '。对象' + h(f.who.join('、') || '待定') + '，' + h(f.when) + '。<div class="bt"><button data-act="focus-one" data-i="' + el.dataset.i + '">排进计划</button><button class="g" data-act="no" data-t="先不用">先不用</button></div>', { confirm: false }); },
  'focus-one'(el) { const f = trainFocus()[+el.dataset.i]; const plan = LS.get('plan', []); f.who.forEach(n => plan.push({ who: n, t: f.t, when: f.when, ts: Date.now() })); LS.set('plan', plan); DB.log('培训计划', f.t + '：' + f.who.join('、')); XW.fly('已排进培训计划 · ' + f.t); if (S.page === 'people') render(); XW.answer('排好了，' + f.who.join('、') + '，' + f.when + '。', null, { confirm: false }); },
  'focus-plan'() { const f = trainFocus(); const plan = LS.get('plan', []); f.forEach(x => x.who.forEach(n => plan.push({ who: n, t: x.t, when: x.when, ts: Date.now() }))); LS.set('plan', plan); DB.log('培训计划', '下次培训重点 ' + f.length + ' 项'); XW.fly('下次培训重点已全部排进计划'); if (S.page === 'people') render(); XW.answer(f.length + ' 条都排进去了：' + f.map(x => x.kind + '「' + x.t + '」给' + (x.who.join('、') || '待定')).join('；') + '。在培养与回写的培训计划里能看到，也能改。', null, { confirm: false }); },
  /* 年龄与梯队 */
  'age-band'(el) { const b = ageStruct().find(x => x.n.replace(' 岁', '') === el.dataset.k); if (!b) return; XW.answer(el.dataset.k + ' 有 ' + b.list.length + ' 人：' + (b.list.map(p => p.n + '（' + p.post.replace('副班长 · ', '') + ' · 工龄 ' + p.yrs + ' 年）').join('、') || '无') + '。' + (b.list.length && b.list[0].age >= 41 ? '这一段是班组的骨干层，持证也集中在他们身上。' : b.list.length && b.list[0].age <= 30 ? '这一段资质普遍还少，是要压担子的一批。' : ''), null, { confirm: false }); },
  'age-risk'(el) { const r = ageRisk()[+el.dataset.i]; if (!r) return; XW.answer(r.t + '。' + r.d + r.fix, r.who && r.who.length ? h(r.t) + '。' + h(r.d) + h(r.fix) + '<div class="bt"><button data-act="age-fix" data-i="' + el.dataset.i + '">按这个培养人选排计划</button><button class="g" data-act="no" data-t="再想想">再想想</button></div>' : null, { confirm: false }); },
  'age-fix'(el) { const r = ageRisk()[+el.dataset.i]; const plan = LS.get('plan', []); const t = r.t.split(' ')[0].replace(/持证人.*/, '') || '梯队培养'; r.who.forEach(n => plan.push({ who: n, t: (/资格|证/.test(t) ? t + ' 取证培训' : '骨干补位培养'), when: '10 月', ts: Date.now() })); LS.set('plan', plan); DB.log('梯队', r.t + ' → 培养 ' + r.who.join('、')); XW.fly('已排进培养计划 · ' + r.who.join(' · ')); if (S.page === 'people') render(); XW.answer('排好了：' + r.who.join('、') + '。这类事早一年动手就来得及，等到人退了再培养就晚了。', null, { confirm: false }); },
  /* 通用：不办 */
  no(el) { const t = (el.dataset.t || '').trim(); const say = { '不删': '好，留着。', '不挪': '好，日子不动。', '不换': '好，按原来的人。', '先不开工': '好，票审完再开工。', '先不用': '好，先不办。要办的时候再点我。', '再想想': '好，想好了再说。', '再改改': '好，你改完点保存。', '再等等': '好，我先不催。', '改一下': '你直接在上面那段里改，改完点发送。', '明天再说': '好，明天我再提你一次。', '不调': '好，人不动，这条按待确认放着。', '不发': '好，先不发。' }[t] || '好，这次不办。'; XW.answer(say, null, { confirm: false, speak: false }); }
});
Object.assign(ACT, {
  person(el) { ensure('people', () => PEOPLEPG.show(el.dataset.who)); },
  six(el) { PEOPLEPG.sixAsk(el.dataset.k); },
  heat(el) { ensure('people', () => { PEOPLEPG.show(el.dataset.who); XW.at(2600, () => ACT.mod({ dataset: { i: el.dataset.i } })); }); },
  mod(el) { const p = PEOPLEPG.cur; if (!p) return; const i = +el.dataset.i; const m = MODS[i]; const lv = PEOPLEPG.lv(p)[i]; const ev = PEOPLEPG.evidence(p, i); const host = $('#pev'); host.innerHTML = '<div class="note" style="opacity:1">' + h(m.n) + ' · ' + h(LV[lv]) + '（' + h(LVDESC[lv]) + '）· 要素：' + h(m.el.join(' / ')) + '</div>' + ev.map(e => '<div>' + h(e.t) + '<span>' + h(e.s) + '</span></div>').join('');
    XW.state('look', '正在指给你看'); $$('#pev div').forEach((d, j) => XW.at(300 + j * 500, () => d.classList.add('in')));
    XW.at(400, () => XW.answer(p.n + '的"' + m.n + '"我定在 ' + LV[lv] + '，依据是' + ev.map(e => e.t).join('、') + '。' + (lv <= 2 ? '往上一级要看下一次考评和一次独立完成的记录。' : '') + '这个等级等你确认。', null, { speak: false, chart: CH.mini.line([{ n: m.n.replace('能力', ''), vals: LEVEL_HIST[p.n].map(q => q[i]), c: CPAL[0] }, { n: '班组均值', vals: QUARTERS.map((q, qi) => +(PEOPLE.reduce((s, x) => s + LEVEL_HIST[x.n][qi][i], 0) / PEOPLE.length).toFixed(1)), c: '#7b849c' }], QUARTERS, { max: 5, h: 100 }) }));
    XW.at(900, () => XW.card('<div class="bt" style="margin-top:0"><button data-act="lv-confirm" data-i="' + i + '">确认 ' + h(LV[lv]) + '</button>' + (lv < 5 ? '<button class="g" data-act="lv-up" data-i="' + i + '">调为 ' + h(LV[lv + 1]) + '</button>' : '') + (lv > 1 ? '<button class="g" data-act="lv-down" data-i="' + i + '">调为 ' + h(LV[lv - 1]) + '</button>' : '') + '</div>')); },
  'lv-confirm'(el) { const p = PEOPLEPG.cur; const i = +el.dataset.i; const all = LS.get('levels', {}); all[p.n] = all[p.n] || {}; all[p.n][MODS[i].k] = PEOPLEPG.lv(p)[i]; LS.set('levels', all); XW.answer('记下了，' + p.n + '的"' + MODS[i].n + '"按 ' + LV[PEOPLEPG.lv(p)[i]] + ' 确认，确认人赵立群。', null, { confirm: false }); },
  'lv-up'(el) { const p = PEOPLEPG.cur; const i = +el.dataset.i; const v = PEOPLEPG.lv(p)[i] + 1; const all = LS.get('levels', {}); all[p.n] = all[p.n] || {}; all[p.n][MODS[i].k] = v; LS.set('levels', all); XW.answer('改成 ' + LV[v] + ' 了，确认人赵立群。我把这次调整记进图谱，下次考评再对一遍。', null, { confirm: false }); PEOPLEPG.show(p.n); },
  'lv-down'(el) { const p = PEOPLEPG.cur; const i = +el.dataset.i; const v = PEOPLEPG.lv(p)[i] - 1; const all = LS.get('levels', {}); all[p.n] = all[p.n] || {}; all[p.n][MODS[i].k] = v; LS.set('levels', all); XW.answer('改成 ' + LV[v] + ' 了，确认人赵立群。', null, { confirm: false }); PEOPLEPG.show(p.n); },
  'p-plan'() { const p = PEOPLEPG.cur; const lv = PEOPLEPG.lv(p); const wi = lv.indexOf(Math.min.apply(null, lv)); const c = COURSES.find(c => c.mod === MODS[wi].k) || COURSES[0]; const plan = LS.get('plan', []); plan.push({ who: p.n, t: c.n, when: '下周', ts: Date.now() }); LS.set('plan', plan); XW.fly('已加入下周培训计划 · ' + p.n); XW.answer('排进去了：下周' + p.n + '学《' + c.n + '》，' + (p.n === '刘一鸣' ? '跟黄伟强做两次继保旁站，周五再考一次；周一田寮站验收随队。' : '学完考一次，成绩回到图谱。') + '培训计划里能看到。', null, { confirm: false }); },
  'p-advice'() { const p = PEOPLEPG.cur; const lv = PEOPLEPG.lv(p); const wi = lv.indexOf(Math.min.apply(null, lv)); const c = COURSES.find(c => c.mod === MODS[wi].k) || COURSES[0]; const s9 = skill9Of(p); const bi = s9.q.indexOf('B'); XW.state('write'); const d = XW.msg('a', p.n + '的培养建议我写一段：<div class="draft"><span></span></div>'); XW.type(d.querySelector('.draft span'), '培养重点：' + MODS[wi].n + '（现 ' + LV[lv[wi]] + '）' + (bi >= 0 ? '；核心技能「' + SKILL9[bi].n + '」带教中' : '') + '。\n下季度安排：① 学《' + c.n + '》并通过理论测试；② 跟班内 ' + (p.n === '黄伟强' ? '韩雪' : '黄伟强') + ' 完成两次现场旁站；③ 独立完成一次同类作业并由负责人签字' + (bi >= 0 ? '，实操量回写满两次后确认资格 A' : '') + '。\n目标：下次季度评价升至 ' + LV[Math.min(5, lv[wi] + 1)] + '。以上由班组长确认后使用。', 30, () => { XW.state(''); d.insertAdjacentHTML('beforeend', '<div class="bt"><button data-act="p-plan">排进计划</button><button class="g" data-act="doc-save-advice">存到文稿中心</button></div>'); }); },
  'p-talk'() { const p = PEOPLEPG.cur; const last = TALKS.find(t => t.who === p.n); XW.answer('谈心提纲我按他最近的记录列了三个问题：一、这周 ' + p.week + ' 小时外勤，身体和家里有没有吃紧的地方；二、' + (p.hours.m < 3 ? '本月学时只有 ' + p.hours.m + '，是没时间还是课不合适' : '最近哪次作业让他觉得最有把握') + '；三、下一步想往哪个方向走，图谱上最弱的那格他自己怎么看。' + (last ? '上次 ' + last.d + ' 谈过，他说"' + last.t.split('；')[0] + '"，这次可以接着问。' : '') + '谈完你说一句，我记进档案。', null, { confirm: false }); },
  'p-radar'() { const p = PEOPLEPG.cur; const avg = MODS.map((m, i) => +(PEOPLE.reduce((s, x) => s + PEOPLEPG.lv(x)[i], 0) / PEOPLE.length).toFixed(1)); XW.answer(p.n + '和班组均值放在一张图上：高于均值的是' + (MODS.filter((m, i) => PEOPLEPG.lv(p)[i] > avg[i]).map(m => m.n.replace('能力', '')).join('、') || '无') + '，低于均值的是' + (MODS.filter((m, i) => PEOPLEPG.lv(p)[i] < avg[i]).map(m => m.n.replace('能力', '')).join('、') || '无') + '。', null, { confirm: false, chart: CH.mini.radar(MODS.map(m => m.n.replace('能力', '')), [{ n: p.n, vals: PEOPLEPG.lv(p), c: CPAL[0] }, { n: '班组均值', vals: avg, c: CPAL[1], dash: true }]) + CH.mini.legend([{ n: p.n, c: CPAL[0] }, { n: '班组均值', c: CPAL[1] }]) }); },
  'p-post'(el) { const k = el.dataset.k; const list = PEOPLE.filter(p => postKey(p).replace('作业员', '') === k); XW.answer(k + '有 ' + list.length + ' 人：' + list.map(p => p.n + '（' + p.yrs + ' 年）').join('、') + '。', null, { confirm: false }); },
  'p-hours'(el) { const p = P[el.dataset.who]; XW.answer(p.n + '年度学时 ' + p.hours.done + '/60，本月 ' + p.hours.m + '/5。' + (p.hours.done < HOURS_DUE ? '比 8 月应达的 ' + HOURS_DUE + ' 学时少 ' + (HOURS_DUE - p.hours.done) + '，剩下四个月每月要 ' + Math.ceil((60 - p.hours.done) / 4) + ' 学时才能达标。' : '进度正常。'), null, { confirm: false, chart: CH.mini.line([{ n: '累计学时', vals: [5, 10, 15, 20, 25, 30, p.hours.done - 3, p.hours.done].map(v => Math.max(0, Math.min(v, p.hours.done))), c: CPAL[0] }, { n: '应达', vals: [5, 10, 15, 20, 25, 30, 35, 40], c: '#7b849c' }], ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月'], { max: 60, h: 100 }) }); },
  'p-cert'(el) { const k = el.dataset.cert, who = el.dataset.who; const p = P[who]; const c = CERTS.find(x => x.who === who && x.name === k); const tip = { '登高架设作业证': '要派柱上 FTU 不停电检修的活得先考这个证，下一批培训在 10 月。', '电力电缆作业证': '交接试验和电缆相关的验收要这个证，班里只有 ' + certHold(k).length + ' 个人有。', '继电保护作业资格': '保护定检和定值管理要这个资格。', '工作负责人资格': '第一种工作票必须由持证人当负责人。' }[k] || ''; XW.answer(!c && !p.cert.includes(k) ? who + '没有' + k + '。' + tip : !c ? who + '的' + k + '在有效期内。' : c.renewed ? who + '的' + c.name + ' ' + c.renewed + ' 刚复审过，有效期到 ' + c.due + '。' : who + '的' + c.name + ' ' + c.got + ' 取得，' + c.due + ' 到期，还有 ' + daysTo(c.due) + ' 天。' + (daysTo(c.due) <= 90 ? '复审要提前一个月报名。' : ''), null, { confirm: false }); },
  'p-att'(el) { const p = PEOPLEPG.cur; const i = +el.dataset.i; const v = ATTEND30[p.n][i]; XW.answer((30 - i) + ' 天前' + p.n + ['休息', '在岗', '外勤', '休假'][v] + (v === 2 ? '，' + (HOURS.find(r => r.who === p.n) || { job: '终端巡视' }).job : '') + '。近 30 天他外勤 ' + ATTEND30[p.n].filter(x => x === 2).length + ' 天、在岗 ' + ATTEND30[p.n].filter(x => x === 1).length + ' 天。', null, { confirm: false }); },
  'p-attcell'(el) { const who = el.dataset.who; const i = +el.dataset.i; const v = ATTEND30[who][i]; XW.answer(who + ' ' + (30 - i) + ' 天前' + ['休息', '在岗', '外勤', '休假'][v] + '。近 30 天外勤 ' + ATTEND30[who].filter(x => x === 2).length + ' 天。', null, { confirm: false }); },
  mentor(el) { const m = MENTORS.find(x => x.m === el.dataset.m); const s = P[m.s]; const mi = MODS.findIndex(x => x.n === m.focus); XW.answer(m.m + '带' + m.s + '，' + m.since + ' 起，重点是' + m.focus + '。' + m.s + '这项从 ' + LV[LEVEL_HIST[m.s][0][mi]] + ' 到现在 ' + LV[PEOPLEPG.lv(s)[mi]] + '。' + (m.s === '刘一鸣' ? '下周两次继保旁站已经排了。' : '下季度可以安排一次独立完成的作业。'), null, { confirm: false, chart: CH.mini.line([{ n: m.s, vals: LEVEL_HIST[m.s].map(q => q[mi]), c: CPAL[0] }, { n: m.m, vals: LEVEL_HIST[m.m].map(q => q[mi]), c: CPAL[1] }], QUARTERS, { max: 5, h: 100 }) }); },
  'cert-remind'() { const list = certsDueWithin(90); list.forEach(c => XW.fly('已提醒 ' + c.who + ' · ' + c.name + ' 复审')); list.forEach(c => DB.notify(c.who, c.name + ' 复审报名（' + c.due + ' 到期）', '已读', true)); XW.answer(list.length + ' 个人都提醒了，复审报名我按最早到期的先排，' + (list[0] ? list[0].who + '这周报，其他的下周。' : ''), null, { confirm: false }); },
  'doc-save-advice'() { const docs = LS.get('docs', {}); const el = $$('.msg .draft').pop(); docs['advice-' + PEOPLEPG.cur.n] = { t: PEOPLEPG.cur.n + ' 培养与沟通材料', ts: Date.now(), body: el ? el.textContent : '' }; LS.set('docs', docs); XW.answer('存到文稿中心了，文件名"' + PEOPLEPG.cur.n + ' 培养与沟通材料"。', null, { confirm: false }); }
});
