/* ===== 班组画像：六类信息一屏、结构图表、12 人、能力图谱 8 模块 × L1–L5、成长轨迹、资质矩阵、工作量公平、出勤热力、师带徒、谈心、荣誉墙 ===== */
const PEOPLEPG = {
  cur: null,
  lv(p) { const conf = LS.get('levels', {})[p.n] || {}; return p.lv.map((v, i) => conf[MODS[i].k] != null ? conf[MODS[i].k] : v); },
  obs(p) {
    const lv = this.lv(p); const rows = HOURS.filter(r => r.who === p.n); const outs = rows.length; const wk = MODS.map((m, i) => ({ m, v: lv[i] })).sort((a, b) => a.v - b.v);
    const weak = wk[0], strong = wk[wk.length - 1]; const due = certsDueWithin(90).filter(c => c.who === p.n);
    if (p.n === '刘一鸣') return ['刘一鸣这两周跟了四次外勤，态度很好，负责人都说他肯问。', '但光差保护那门课的题他答对了两道，二次回路也弱，图谱上"二次及保护能力"还在 L1。', '我建议下周让他跟黄伟强做两次继保旁站，再考一次。要我排进计划吗？'];
    if (p.n === '黄伟强') return ['黄伟强这周已经 26 小时，是全班最多的，连续三周都排第一。', '他是带电作业和负责人资格都有的两个人之一，活自然往他身上堆；"故障分析与处理"L4 是班里最强的。', '我建议下周给他排两天室内，把凤凰线的活分一部分给李文博。要我在值班表里这么排吗？'];
    return [p.n + '是' + p.post + '，这周 ' + p.week + ' 小时，本月学时 ' + p.hours.m + '/5，年度 ' + p.hours.done + '/' + p.hours.req + '。', '图谱上最强是"' + strong.m.n + '"' + LV[strong.v].slice(0, 2) + '，最弱是"' + weak.m.n + '"' + LV[weak.v].slice(0, 2) + (due.length ? '；' + due[0].name + ' ' + due[0].due + ' 到期，还有 ' + daysTo(due[0].due) + ' 天' : '') + '。', (p.hours.m < 3 ? '这个月学时落后了，我建议把"' + weak.m.n + '"相关的一门课排给他。要我排进计划吗？' : outs >= 3 ? '外勤不少，短板那一格适合安排一次带教。要我排进计划吗？' : '状态平稳，短板那格可以安排一次旁站。要我排进计划吗？')];
  },
  evidence(p, mi) { const m = MODS[mi]; const lv = this.lv(p)[mi]; const rows = HOURS.filter(r => r.who === p.n).slice(0, 2); const ev = [];
    rows.forEach(r => ev.push({ t: r.d + ' ' + r.job + ' ' + r.h + 'h', s: '工时台账' }));
    const c = COURSES.find(c => c.mod === m.k); if (c) ev.push({ t: (p.n === '刘一鸣' && c.id === 'c5' ? '光差保护理论测试 40 分（2/5）' : (TRAIN_DONE[p.n] || []).includes(c.id) ? c.n + ' 理论测试 ' + (60 + lv * 8) + ' 分' : c.n + ' 未学'), s: '培训考评' });
    const sc = LS.get('scores', {})[p.n]; if (sc) ev.push({ t: sc.sheet + ' 实操 ' + sc.total + ' 分', s: '实操评分表' });
    (SCORE_HIST[p.n] || []).slice(-1).forEach(s => ev.push({ t: s.d + ' ' + s.t + ' ' + s.s + ' 分', s: '成绩记录' }));
    if (m.k === 'site' && p.cert.includes('工作负责人资格')) ev.push({ t: '近 30 天担任工作负责人 2 次', s: '两票台账' });
    if (m.k === 'fault' && CASES.concat(CASES2).some(a => a.who === p.n)) ev.push({ t: CASES.concat(CASES2).find(a => a.who === p.n).t + '（案例）', s: '班组知识库' });
    const men = MENTORS.find(x => x.s === p.n); if (men && men.focus === m.n) ev.push({ t: '师带徒：' + men.m + ' 带教（' + men.since + ' 起）', s: '师带徒' });
    return ev; },
  show(name) { const p = P[name]; if (!p) return; this.cur = p; $$('.pc').forEach(c => c.classList.toggle('on', c.dataset.who === name)); const lv = this.lv(p); const host = $('#pdetail'); host.scrollIntoView({ block: 'nearest' }); const hist = LEVEL_HIST[p.n]; const wi = lv.indexOf(Math.min.apply(null, lv)); const si = lv.indexOf(Math.max.apply(null, lv)); const att = ATTEND30[p.n];
    host.innerHTML = '<div class="h"><b>' + h(p.n) + ' · ' + h(p.post) + '</b><span>' + p.age + ' 岁 · 工龄 ' + p.yrs + ' 年 · ' + h(p.cert.join('、')) + '</span></div><div class="grid2" style="grid-template-columns:1fr 1.2fr"><div><div class="tk on" id="pobs" style="margin:0;min-height:96px;font-style:normal;color:var(--ink)"><span class="lbl">小瓦特的观察</span><span></span></div><div class="bt" id="pbt" style="margin-top:8px"></div>' +
      '<div class="note" style="margin:10px 0 2px">成长轨迹 · 近四个季度</div>' + CH.mini.line([{ n: MODS[si].n.replace('能力', ''), vals: hist.map(q => q[si]), c: CPAL[0] }, { n: MODS[wi].n.replace('能力', ''), vals: hist.map(q => q[wi]), c: CPAL[1] }], QUARTERS, { max: 5, h: 110 }) +
      '<div class="note" style="margin:8px 0 2px">近 30 天出勤 · 点一格她说那天</div><div class="att">' + att.map((v, i) => '<i class="a' + v + '" data-act="p-att" data-i="' + i + '" data-tip="' + h(p.n) + ' · ' + (30 - i) + ' 天前 · ' + ['休息', '在岗', '外勤', '休假'][v] + '"></i>').join('') + '</div><div class="legend" style="margin-top:4px"><span><i style="background:#c9cbf5"></i>在岗</span><span><i style="background:#5a5bf0"></i>外勤</span><span><i style="background:#e8791d"></i>休假</span><span><i style="background:#eef0fb"></i>休息</span></div></div>' +
      '<div><div class="note" style="margin-bottom:4px">能力图谱 · 8 模块（点一格看依据）</div><div class="mods" id="pmods">' + MODS.map((m, i) => '<div class="mod' + (lv[i] <= 1 || lv[i] === Math.min.apply(null, lv) ? ' weak' : '') + '" data-act="mod" data-i="' + i + '"><span style="text-align:left;color:var(--ink);font-family:var(--sans);font-size:11.5px">' + h(m.n) + '</span><div class="bar"><i data-w="' + (lv[i] * 20) + '"></i></div><span>' + h(LV[lv[i]]) + '</span></div>').join('') + '</div><div class="ev" id="pev"></div>' +
      '<div class="grid2" style="margin-top:8px"><div><div class="note" style="margin-bottom:2px">证书</div>' + CERTS.filter(c => c.who === p.n).map(c => '<div class="note" style="color:var(--ink);margin:2px 0">' + h(c.name) + ' <span class="tag ' + (c.renewed ? 'ok' : daysTo(c.due) <= 90 ? 'bad' : '') + '">' + (c.renewed ? '已复审' : c.due) + '</span></div>').join('') + '</div><div><div class="note" style="margin-bottom:2px">培训与成绩</div><div class="note" style="color:var(--ink)">已学 ' + (TRAIN_DONE[p.n] || []).length + '/7 门</div>' + (SCORE_HIST[p.n] || []).map(s => '<div class="note" style="color:var(--ink);margin:2px 0">' + h(s.d) + ' ' + h(s.t) + ' <b>' + s.s + '</b></div>').join('') + '</div></div></div></div>';
    const obs = this.obs(p); const o = $('#pobs span:last-child'); XW.state('talk'); let i = 0; const next = () => { if (i >= obs.length) { XW.state(''); $('#pbt').innerHTML = '<button data-act="p-plan">排进计划</button><button class="g" data-act="p-advice">培养建议</button><button class="g" data-act="p-talk">谈心提纲</button><button class="g" data-act="p-radar">图谱对比班组</button>'; return; } const s = document.createElement('span'); o.appendChild(s); if (i) s.insertAdjacentText('beforebegin', ' '); XW.type(s, obs[i], 40, () => XW.at(250, next)); if (i === 1) { XW.at(200, () => { $$('#pmods .mod').forEach((m, j) => XW.at(j * 120, () => { m.classList.add('in'); $('i', m).style.width = $('i', m).dataset.w + '%'; })); }); } if (i === 2) XW.at(100, () => $$('#pmods .mod.weak').forEach(m => m.classList.add('pulse'))); i++; }; next();
    XW.type($('#xwsub'), obs[0], 45);
  },
  six() { const due = certsDueWithin(90).length; const avgH = Math.round(PEOPLE.reduce((s, p) => s + p.hours.done / p.hours.req, 0) / PEOPLE.length * 100); const posts = {}; PEOPLE.forEach(p => { const k = p.post.replace(/副班长 · |（学员）/g, ''); posts[k] = (posts[k] || 0) + 1; });
    return [{ k: 'struct', b: PEOPLE.length, s: '人员结构', e: Object.keys(posts).map(k => k.replace('作业员', '') + posts[k]).join(' ') }, { k: 'cert', b: due, s: '证书 90 天内到期', e: certsDueWithin(90).map(c => c.who).join('、') || '无' }, { k: 'hours', b: avgH + '%', s: '年度学时完成', e: PEOPLE.filter(p => p.hours.m < 3).length + ' 人本月未完成' }, { k: 'safety', b: SAFETY_ACT.length, s: '本月安全活动', e: '安全日 ' + MONTH.safetyDays + '/' + MONTH.safetyDaysPlan + ' · 通报学习 1' }, { k: 'jobs', b: MONTH.jobsDone + '/' + MONTH.jobs, s: '本月任务完成', e: '两票合格 ' + MONTH.ticketsOK + '/' + MONTH.tickets }, { k: 'honor', b: HONORS.length, s: '荣誉', e: HONORS[0].who + ' · ' + HONORS[0].t.slice(-4) }]; },
  sixAsk(k) { const map = { struct: () => XW.spot({ title: '人员结构 · 12 人', cols: ['姓名', '岗位', '年龄', '工龄', '状态'], rows: PEOPLE.map(p => [p.n, p.post, p.age, p.yrs, p.status]), me: PEOPLE.map((p, i) => i), text: '一共 12 个人：班长 1、副班长 1、高级作业员 2、中级作业员 4、初级作业员 4（含 1 名学员）。平均年龄 32 岁，工龄 5 年以下的有 5 个，这几年新人多。' }),
      cert: () => { const list = certsDueWithin(90); XW.spot({ title: '资质证书台账 · 90 天内到期', cols: ['姓名', '证书', '取得', '复审期限', '剩余天数'], rows: CERTS.filter(c => !c.renewed).map(c => [c.who, c.name, c.got, c.due, daysTo(c.due)]), me: CERTS.filter(c => !c.renewed).map((c, i) => list.includes(c) ? i : -1).filter(i => i >= 0), text: '三个月内到期的有 ' + list.length + ' 个：' + list.map(c => c.who + '的' + c.name + '（' + c.due + '，还有 ' + daysTo(c.due) + ' 天）').join('、') + '。' + list[0].who + '的最急，复审要提前一个月报名，这周就得报。' }); XW.at(600, () => XW.chart(CH.mini.timeline(CERTS.filter(c => !c.renewed && daysTo(c.due) <= 365).map(c => ({ n: c.who, t: daysTo(c.due), c: daysTo(c.due) <= 90 ? '#e5484d' : daysTo(c.due) <= 180 ? '#e8791d' : CPAL[0], lbl: daysTo(c.due) <= 90 ? c.who : '', tip: c.who + ' · ' + c.name + ' · ' + c.due })), {}), '未来一年证书到期')); XW.at(900, () => XW.card('<div class="bt" style="margin-top:0"><button data-act="cert-remind">提醒本人并报名复审</button><button class="g" data-act="nav" data-to="ledger" data-sub="cert">看证书台账</button></div>')); },
      hours: () => { const lag = PEOPLE.filter(p => p.hours.m < 3); XW.spot({ title: '学时台账 · 2026 年（要求 60 学时 / 年，5 学时 / 月）', cols: ['姓名', '本月', '年度已完成', '年度要求', '进度'], rows: PEOPLE.map(p => [p.n, p.hours.m + '/5', p.hours.done, p.hours.req, Math.round(p.hours.done / p.hours.req * 100) + '%']), me: PEOPLE.map((p, i) => lag.includes(p) ? i : -1).filter(i => i >= 0), text: '本月学时没完成的有 ' + lag.length + ' 个：' + lag.map(p => p.n + ' ' + p.hours.m + ' 学时').join('、') + '。按现在的进度，年底达不到 60 学时的是陈浩和周明，我建议把继保专才的课先排给他们。' }); XW.at(600, () => XW.chart(CH.mini.bars(PEOPLE.map(p => ({ n: p.n, v: p.hours.done, c: p.hours.done < 40 ? '#e8791d' : CPAL[4], tip: p.n + ' 年度 ' + p.hours.done + '/60' })), { max: 60, limit: 40, h: 12 }), '年度学时 · 虚线为 9 月应达进度')); },
      safety: () => XW.spot({ title: '安全活动台账 · 本月', cols: ['日期', '活动', '参加人数'], rows: SAFETY_ACT.map(a => [a.d, a.t, a.who]), me: [0, 1, 2], text: '本月开了一次安全日、一次事故通报学习，第二次安全日还没开，我建议放在周五，主题讲台风季登杆。' }),
      jobs: () => { XW.spot({ title: '任务台账 · 本月', cols: ['项目', '数量'], rows: [['作业任务', MONTH.jobs], ['已完成', MONTH.jobsDone], ['工作票', MONTH.tickets], ['合格', MONTH.ticketsOK], ['缺陷发现', MONTH.defectsFound], ['缺陷闭环', MONTH.defectsClosed]], me: [0, 1, 4, 5], text: '本月 38 项任务完成了 35，没完成的三项里有一项超期，就是志远站那条缺陷。两票 12 张全部合格。' }); XW.at(600, () => XW.chart(CH.mini.group(PLAN_M.map(p => p.k.slice(0, 4)), [{ n: '计划', vals: PLAN_M.map(p => p.plan), c: RAMP[2] }, { n: '完成', vals: PLAN_M.map(p => p.done), c: CPAL[0] }], { h: 120 }), '八类任务 · 计划 / 完成')); },
      honor: () => XW.spot({ title: '荣誉台账', cols: ['获得者', '荣誉', '时间'], rows: HONORS.map(a => [a.who, a.t, a.d]), me: [0, 1, 2, 3], text: '班组去年拿了安全生产先进班组，韩雪上个月刚评上局级技术能手，李文博技能竞赛三等奖。竞赛人选的话，我会先想到李文博和郭子扬，由你定。' }) }; (map[k] || map.struct)(); },
  heatHTML() { return '<div class="heat" style="grid-template-columns:70px repeat(8,1fr)"><div></div>' + MODS.map(m => '<div class="hd">' + h(m.n.replace('能力', '')) + '</div>').join('') + PEOPLE.map(p => { const lv = this.lv(p); return '<div class="rn">' + h(p.n) + '</div>' + lv.map((v, i) => '<div class="c" data-act="heat" data-who="' + p.n + '" data-i="' + i + '" style="background:' + ['#e6e8f4', '#c9cbf5', '#9a9cf5', '#6f70f0', '#5a5bf0', '#3d3ec7'][v] + '">' + v + '</div>').join(''); }).join('') + '</div>'; },
  certMatrix() { const kinds = ['高压电工证', '登高作业证', '工作负责人资格', '带电作业资格', '电缆试验作业证']; return '<div class="tbl"><table class="t cmx"><tr><th></th>' + kinds.map(k => '<th>' + h(k.replace('作业', '').replace('资格', '')) + '</th>').join('') + '</tr>' + PEOPLE.map(p => '<tr><td>' + h(p.n) + '</td>' + kinds.map(k => { const c = CERTS.find(x => x.who === p.n && x.name === k); const st = !c ? 'no' : c.renewed ? 'ok' : daysTo(c.due) <= 90 ? 'due' : 'ok'; return '<td><i class="cm ' + st + '" data-act="p-cert" data-who="' + p.n + '" data-cert="' + k + '" data-tip="' + h(p.n) + ' · ' + h(k) + ' · ' + (!c ? '无' : c.renewed ? '已复审' : c.due + '（' + daysTo(c.due) + ' 天）') + '"></i></td>'; }).join('') + '</tr>').join('') + '</table></div><div class="legend" style="margin-top:6px"><span><i style="background:#18b97a"></i>有效</span><span><i style="background:#e5484d"></i>90 天内到期</span><span><i style="background:#e6e8f4"></i>无</span></div>'; }
};
PAGES.people = {
  render() { const six = PEOPLEPG.six(); const posts = {}; PEOPLE.forEach(p => { const k = p.post.replace(/副班长 · |（学员）/g, '').replace('作业员', ''); posts[k] = (posts[k] || 0) + 1; }); const ages = [['20–29', PEOPLE.filter(p => p.age < 30).length], ['30–39', PEOPLE.filter(p => p.age >= 30 && p.age < 40).length], ['40+', PEOPLE.filter(p => p.age >= 40).length]]; const yrs = [['≤2 年', PEOPLE.filter(p => p.yrs <= 2).length], ['3–9 年', PEOPLE.filter(p => p.yrs >= 3 && p.yrs < 10).length], ['10 年+', PEOPLE.filter(p => p.yrs >= 10).length]]; const avgW = PEOPLE.filter(p => p.post !== '班长').reduce((s, p) => s + p.week, 0) / 11;
    return cmdHTML(['刘一鸣最近怎么样', '三个月内证书到期的有谁', '本月学时未完成的名单', '谁适合参加下季度的技能竞赛', '黄伟强最近怎么样']) + pageHead('班组画像', TEAM.name + ' · 12 人 · 六类信息与能力图谱', '<div class="loop">' + LOOP.map((l, i) => '<div class="' + (i === 0 ? 'on' : '') + '">' + (i + 1) + ' ' + l + '</div>').join('') + '</div>') +
    '<div class="six">' + six.map(s => '<div data-act="six" data-k="' + s.k + '"><b>' + s.b + '</b><span>' + h(s.s) + '</span><em>' + h(s.e) + '</em></div>').join('') + '</div>' +
    '<div class="grid3 charts"><div class="card chart"><div class="h"><b>岗位结构</b><span>点一段看人</span></div>' + CH.mini.donut(Object.keys(posts).map((k, i) => ({ k, v: posts[k], c: CPAL[i], act: 'p-post', k, tip: k + ' ' + posts[k] + ' 人' })), { sub: '人' }) + '</div><div class="card chart"><div class="h"><b>年龄 / 工龄</b><span>人数</span></div>' + CH.mini.group(['20–29', '30–39', '40+'], [{ n: '年龄段', vals: ages.map(a => a[1]), c: CPAL[2] }], { h: 100, max: 8 }) + CH.mini.group(yrs.map(y => y[0]), [{ n: '工龄段', vals: yrs.map(y => y[1]), c: CPAL[5] }], { h: 100, max: 8 }) + '</div><div class="card chart"><div class="h"><b>年度学时进度</b><span>虚线 = 9 月应达 40</span></div>' + CH.mini.bars(PEOPLE.map(p => ({ n: p.n, v: p.hours.done, c: p.hours.done < 40 ? '#e8791d' : CPAL[4], act: 'p-hours', who: p.n, tip: p.n + ' 年度 ' + p.hours.done + '/60 · 本月 ' + p.hours.m + '/5' })), { max: 60, limit: 40, h: 12 }) + '</div></div>' +
    '<div class="card"><div class="h"><b>成员</b><span>点一个人，她先说观察，再展开图谱</span></div><div class="pgrid">' + PEOPLE.map(p => '<div class="pc" data-act="person" data-who="' + p.n + '"><div class="av">' + h(p.n[0]) + '</div><div><b>' + h(p.n) + '</b><span>' + h(p.post) + ' · ' + p.week + 'h</span></div><span class="st ' + (p.status === '在岗' ? '' : p.status === '外勤' ? 'o' : 'x') + '">' + h(p.status) + '</span></div>').join('') + '</div></div>' +
    '<div class="card" id="pdetail"><div class="empty">点上面的人</div></div>' +
    '<div class="grid2"><div class="card"><div class="h"><b>资质矩阵 · 12 人 × 5 类证书</b><span>点一格她说</span></div>' + PEOPLEPG.certMatrix() + '</div><div class="card"><div class="h"><b>工作量公平 · 本周</b><span>均值 ' + avgW.toFixed(1) + 'h · 点一条看台账</span></div>' + CH.mini.bars(PEOPLE.filter(p => p.post !== '班长').sort((a, b) => b.week - a.week).map(p => ({ n: p.n, v: p.week, c: p.week >= WEEK_LIMIT ? '#e5484d' : p.week < avgW / 2 ? RAMP[2] : CPAL[0], act: 'ch-hours', who: p.n, tip: p.n + ' 本周 ' + p.week + 'h' })), { limit: WEEK_LIMIT, unit: 'h', max: 30, h: 13 }) + '<div class="note" style="margin-top:4px">最高与最低相差 ' + (Math.max.apply(null, PEOPLE.map(p => p.week)) - Math.min.apply(null, PEOPLE.filter(p => p.post !== '班长' && p.status !== '休假').map(p => p.week))) + ' 小时；黄伟强连续三周最高。</div><div class="bt"><button class="s g" data-act="wk-balance">让她看下周是否均衡</button></div></div></div>' +
    '<div class="grid2"><div class="card"><div class="h"><b>出勤 · 近 30 天</b><span>在岗 / 外勤 / 休假 · 点一格</span></div>' + CH.mini.heat(PEOPLE.map(p => p.n), [...Array(30)].map((_, i) => i % 5 === 0 ? (30 - i) + '天前' : ''), PEOPLE.map(p => ATTEND30[p.n]), { colors: ['#eef0fb', '#c9cbf5', '#5a5bf0', '#e8791d'], act: 'p-attcell', fmt: v => ['休息', '在岗', '外勤', '休假'][v] }) + '</div><div class="card"><div class="h"><b>师带徒 · 谈心 · 培养计划</b></div><div class="note" style="margin-bottom:2px">师带徒</div><div class="jobs">' + MENTORS.map(m => '<div data-act="mentor" data-m="' + m.m + '" style="cursor:pointer"><span style="font-size:11.5px;color:var(--ink)">' + h(m.m) + ' → ' + h(m.s) + '<br><span class="note">' + h(m.since) + ' 起 · ' + h(m.focus) + '</span></span><span class="tag v">带教中</span></div>').join('') + '</div><div class="note" style="margin:8px 0 2px">谈心记录</div><div class="jobs">' + TALKS.map(t => '<div><span style="font-size:11.5px;color:var(--ink)">' + h(t.who) + ' · ' + h(t.d) + '<br><span class="note">' + h(t.t) + '</span></span><span class="tag">' + h(t.by) + '</span></div>').join('') + '</div><div class="note" style="margin:8px 0 2px">培养计划</div><div class="jobs">' + (LS.get('plan', []).length ? LS.get('plan', []).map(p => '<div><span style="font-size:11.5px;color:var(--ink)">' + h(p.who) + '《' + h(p.t) + '》</span><span class="tag ok">' + h(p.when) + '</span></div>').join('') : '<div class="note">点某个人的「排进计划」</div>') + '</div></div></div>' +
    '<div class="grid2" style="grid-template-columns:1fr 2fr"><div class="card"><div class="h"><b>荣誉墙</b></div>' + HONORS.map(a => '<div class="honor"><b>' + h(a.who) + '</b><span>' + h(a.t) + '</span><i>' + h(a.d) + '</i></div>').join('') + '</div><div class="card"><div class="h"><b>班组能力热力 · 12 人 × 8 模块</b><span>L1 了解 · L2 掌握 · L3 熟练 · L4 精通 · L5 专家 · 点一格看依据</span></div>' + PEOPLEPG.heatHTML() + '</div></div>'; },
  after() { CH.mount($('#main')); if (S.sub && P[S.sub]) XW.at(200, () => PEOPLEPG.show(S.sub)); }
};
Object.assign(ACT, {
  person(el) { ensure('people', () => PEOPLEPG.show(el.dataset.who)); },
  six(el) { PEOPLEPG.sixAsk(el.dataset.k); },
  heat(el) { ensure('people', () => { PEOPLEPG.show(el.dataset.who); XW.at(2600, () => ACT.mod({ dataset: { i: el.dataset.i } })); }); },
  mod(el) { const p = PEOPLEPG.cur; if (!p) return; const i = +el.dataset.i; const m = MODS[i]; const lv = PEOPLEPG.lv(p)[i]; const ev = PEOPLEPG.evidence(p, i); const host = $('#pev'); host.innerHTML = '<div class="note" style="opacity:1">' + h(m.n) + ' · ' + h(LV[lv]) + '（' + h(LVDESC[lv]) + '）· 要素：' + h(m.el.join(' / ')) + '</div>' + ev.map(e => '<div>' + h(e.t) + '<span>' + h(e.s) + '</span></div>').join('');
    XW.state('look', '正在指给你看'); $$('#pev div').forEach((d, j) => XW.at(300 + j * 500, () => d.classList.add('in')));
    XW.at(400, () => XW.answer(p.n + '的"' + m.n + '"我定在 ' + LV[lv] + '，依据是' + ev.map(e => e.t).join('、') + '。' + (lv <= 2 ? '往上一级要看下一次考评和一次独立完成的记录。' : '') + '这个等级等你确认。', null, { speak: false, chart: CH.mini.line([{ n: m.n.replace('能力', ''), vals: LEVEL_HIST[p.n].map(q => q[i]), c: CPAL[0] }, { n: '班组均值', vals: QUARTERS.map((q, qi) => +(PEOPLE.reduce((s, x) => s + LEVEL_HIST[x.n][qi][i], 0) / PEOPLE.length).toFixed(1)), c: '#7b849c' }], QUARTERS, { max: 5, h: 100 }) }));
    XW.at(900, () => XW.card('<div class="bt" style="margin-top:0"><button data-act="lv-confirm" data-i="' + i + '">确认 ' + h(LV[lv]) + '</button>' + (lv < 5 ? '<button class="g" data-act="lv-up" data-i="' + i + '">调为 ' + h(LV[lv + 1]) + '</button>' : '') + (lv > 1 ? '<button class="g" data-act="lv-down" data-i="' + i + '">调为 ' + h(LV[lv - 1]) + '</button>' : '') + '</div>')); },
  'lv-confirm'(el) { const p = PEOPLEPG.cur; const i = +el.dataset.i; const all = LS.get('levels', {}); all[p.n] = all[p.n] || {}; all[p.n][MODS[i].k] = PEOPLEPG.lv(p)[i]; LS.set('levels', all); XW.answer('记下了，' + p.n + '的"' + MODS[i].n + '"按 ' + LV[PEOPLEPG.lv(p)[i]] + ' 确认，确认人赵立群。', null, { confirm: false }); },
  'lv-up'(el) { const p = PEOPLEPG.cur; const i = +el.dataset.i; const v = PEOPLEPG.lv(p)[i] + 1; const all = LS.get('levels', {}); all[p.n] = all[p.n] || {}; all[p.n][MODS[i].k] = v; LS.set('levels', all); XW.answer('改成 ' + LV[v] + ' 了，确认人赵立群。我把这次调整记进图谱，下次考评再对一遍。', null, { confirm: false }); PEOPLEPG.show(p.n); },
  'lv-down'(el) { const p = PEOPLEPG.cur; const i = +el.dataset.i; const v = PEOPLEPG.lv(p)[i] - 1; const all = LS.get('levels', {}); all[p.n] = all[p.n] || {}; all[p.n][MODS[i].k] = v; LS.set('levels', all); XW.answer('改成 ' + LV[v] + ' 了，确认人赵立群。', null, { confirm: false }); PEOPLEPG.show(p.n); },
  'p-plan'() { const p = PEOPLEPG.cur; const lv = PEOPLEPG.lv(p); const wi = lv.indexOf(Math.min.apply(null, lv)); const c = COURSES.find(c => c.mod === MODS[wi].k) || COURSES[0]; const plan = LS.get('plan', []); plan.push({ who: p.n, t: c.n, when: '下周', ts: Date.now() }); LS.set('plan', plan); XW.fly('已加入下周培训计划 · ' + p.n); XW.answer('排进去了：下周' + p.n + '学《' + c.n + '》，' + (p.n === '刘一鸣' ? '跟黄伟强做两次继保旁站，周五再考一次。' : '学完考一次，成绩回到图谱。') + '培训计划里能看到。', null, { confirm: false }); },
  'p-advice'() { const p = PEOPLEPG.cur; const lv = PEOPLEPG.lv(p); const wi = lv.indexOf(Math.min.apply(null, lv)); const c = COURSES.find(c => c.mod === MODS[wi].k) || COURSES[0]; XW.state('write'); const d = XW.msg('a', p.n + '的培养建议我写一段：<div class="draft"><span></span></div>'); XW.type(d.querySelector('.draft span'), '培养重点：' + MODS[wi].n + '（现 ' + LV[lv[wi]] + '）。\n下季度安排：① 学《' + c.n + '》并通过理论测试；② 跟班内 ' + (p.n === '黄伟强' ? '韩雪' : '黄伟强') + ' 完成两次现场旁站；③ 独立完成一次同类作业并由负责人签字。\n目标：下次季度评价升至 ' + LV[Math.min(5, lv[wi] + 1)] + '。以上由班组长确认后使用。', 30, () => { XW.state(''); d.insertAdjacentHTML('beforeend', '<div class="bt"><button data-act="p-plan">排进计划</button><button class="g" data-act="doc-save-advice">存到文稿中心</button></div>'); }); },
  'p-talk'() { const p = PEOPLEPG.cur; const last = TALKS.find(t => t.who === p.n); XW.answer('谈心提纲我按他最近的记录列了三个问题：一、这周 ' + p.week + ' 小时外勤，身体和家里有没有吃紧的地方；二、' + (p.hours.m < 3 ? '本月学时只有 ' + p.hours.m + '，是没时间还是课不合适' : '最近哪次作业让他觉得最有把握') + '；三、下一步想往哪个方向走，图谱上最弱的那格他自己怎么看。' + (last ? '上次 ' + last.d + ' 谈过，他说"' + last.t.split('；')[0] + '"，这次可以接着问。' : '') + '谈完你说一句，我记进档案。', null, { confirm: false }); },
  'p-radar'() { const p = PEOPLEPG.cur; const avg = MODS.map((m, i) => +(PEOPLE.reduce((s, x) => s + PEOPLEPG.lv(x)[i], 0) / PEOPLE.length).toFixed(1)); XW.answer(p.n + '和班组均值放在一张图上：高于均值的是' + MODS.filter((m, i) => PEOPLEPG.lv(p)[i] > avg[i]).map(m => m.n.replace('能力', '')).join('、') + '，低于均值的是' + MODS.filter((m, i) => PEOPLEPG.lv(p)[i] < avg[i]).map(m => m.n.replace('能力', '')).join('、') + '。', null, { confirm: false, chart: CH.mini.radar(MODS.map(m => m.n.replace('能力', '')), [{ n: p.n, vals: PEOPLEPG.lv(p), c: CPAL[0] }, { n: '班组均值', vals: avg, c: CPAL[1], dash: true }]) + CH.mini.legend([{ n: p.n, c: CPAL[0] }, { n: '班组均值', c: CPAL[1] }]) }); },
  'p-post'(el) { const k = el.dataset.k; const list = PEOPLE.filter(p => p.post.replace(/副班长 · |（学员）/g, '').replace('作业员', '') === k); XW.answer(k + '有 ' + list.length + ' 人：' + list.map(p => p.n + '（' + p.yrs + ' 年）').join('、') + '。', null, { confirm: false }); },
  'p-hours'(el) { const p = P[el.dataset.who]; XW.answer(p.n + '年度学时 ' + p.hours.done + '/60，本月 ' + p.hours.m + '/5。' + (p.hours.done < 40 ? '比 9 月应达的 40 学时少 ' + (40 - p.hours.done) + '，剩下四个月每月要 ' + Math.ceil((60 - p.hours.done) / 4) + ' 学时才能达标。' : '进度正常。'), null, { confirm: false, chart: CH.mini.line([{ n: '累计学时', vals: [8, 14, 20, 26, 32, 38, p.hours.done - 4, p.hours.done].map(v => Math.min(v, p.hours.done)), c: CPAL[0] }, { n: '应达', vals: [5, 10, 15, 20, 25, 30, 35, 40], c: '#7b849c' }], ['2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月'], { max: 60, h: 100 }) }); },
  'p-cert'(el) { const c = CERTS.find(x => x.who === el.dataset.who && x.name === el.dataset.cert); XW.answer(!c ? el.dataset.who + '没有' + el.dataset.cert + '。' + (el.dataset.cert === '登高作业证' ? '要派登杆的活得先考这个证，下一批培训在 10 月。' : '') : c.renewed ? el.dataset.who + '的' + c.name + ' ' + c.renewed + ' 刚复审过，有效期到 ' + c.due + '。' : el.dataset.who + '的' + c.name + ' ' + c.got + ' 取得，' + c.due + ' 到期，还有 ' + daysTo(c.due) + ' 天。' + (daysTo(c.due) <= 90 ? '复审要提前一个月报名。' : ''), null, { confirm: false }); },
  'p-att'(el) { const p = PEOPLEPG.cur; const i = +el.dataset.i; const v = ATTEND30[p.n][i]; XW.answer((30 - i) + ' 天前' + p.n + ['休息', '在岗', '外勤', '休假'][v] + (v === 2 ? '，' + (HOURS.find(r => r.who === p.n) || { job: '线路巡视' }).job : '') + '。近 30 天他外勤 ' + ATTEND30[p.n].filter(x => x === 2).length + ' 天、在岗 ' + ATTEND30[p.n].filter(x => x === 1).length + ' 天。', null, { confirm: false }); },
  'p-attcell'(el) { const who = el.dataset.who; const i = +el.dataset.i; const v = ATTEND30[who][i]; XW.answer(who + ' ' + (30 - i) + ' 天前' + ['休息', '在岗', '外勤', '休假'][v] + '。近 30 天外勤 ' + ATTEND30[who].filter(x => x === 2).length + ' 天。', null, { confirm: false }); },
  mentor(el) { const m = MENTORS.find(x => x.m === el.dataset.m); const s = P[m.s]; const mi = MODS.findIndex(x => x.n === m.focus); XW.answer(m.m + '带' + m.s + '，' + m.since + ' 起，重点是' + m.focus + '。' + m.s + '这项从 ' + LV[LEVEL_HIST[m.s][0][mi]] + ' 到现在 ' + LV[PEOPLEPG.lv(s)[mi]] + '。' + (m.s === '刘一鸣' ? '下周两次继保旁站已经排了。' : '下季度可以安排一次独立完成的作业。'), null, { confirm: false, chart: CH.mini.line([{ n: m.s, vals: LEVEL_HIST[m.s].map(q => q[mi]), c: CPAL[0] }, { n: m.m, vals: LEVEL_HIST[m.m].map(q => q[mi]), c: CPAL[1] }], QUARTERS, { max: 5, h: 100 }) }); },
  'cert-remind'() { const list = certsDueWithin(90); list.forEach(c => XW.fly('已提醒 ' + c.who + ' · ' + c.name + ' 复审')); XW.answer('三个人都提醒了，复审报名我按最早到期的先排，' + list[0].who + '这周报，其他两个下周。', null, { confirm: false }); },
  'doc-save-advice'() { const docs = LS.get('docs', {}); docs['advice-' + PEOPLEPG.cur.n] = { t: PEOPLEPG.cur.n + ' 培养建议', ts: Date.now(), body: $$('.msg .draft').pop().textContent }; LS.set('docs', docs); XW.answer('存到文稿中心了，文件名"' + PEOPLEPG.cur.n + ' 培养建议"。', null, { confirm: false }); }
});
