/* ===== 安全管理：隐患照片、风险作业定级、安全日讲稿、安规考问 ===== */
const SAFETYPG = {
  tabs: [{ k: 'photo', n: '隐患照片' }, { k: 'risk', n: '风险作业' }, { k: 'day', n: '安全日' }, { k: 'quiz', n: '安规考问' }],
  RISKS: [{ id: 'r1', t: '10kV 凤凰线更换 #12 杆刀闸', when: '明日 09:00', fac: ['登杆作业', '台风蓝色预警', '拉线 #9 杆刚更换', '负责人韩雪 · 4 人'], lv: '高' }, { id: 'r2', t: '光明变 10kV 出线柜检查', when: '今日 14:00', fac: ['开关柜内作业', '室内', '陈浩 · 周明 均为初级'], lv: '中' }, { id: 'r3', t: '塘尾线巡视', when: '今日 09:00', fac: ['沿线巡视不登杆', '34℃ 高温', '3 人含学员'], lv: '低' }],
  photos() { const hz = LS.get('hazards', {}); return '<div class="wall">' + ['p7', 'tree', 'lock'].map(k => { const d = DEFECTS.find(x => x.photo === k); return '<div class="card"><div class="h"><b>' + h(d.t.split('（')[0]) + '</b><span>' + h(hz[k] || d.st) + '</span></div>' + PHOTO.html(k, true) + PHOTO.rowsHTML(k) + '<div class="bt" style="margin-top:8px"><button data-act="photo" data-key="' + k + '">核对</button><button class="g" data-act="hz-ask" data-key="' + k + '">让现场确认</button></div></div>'; }).join('') + '</div><div class="card"><div class="h"><b>隐患台账</b><span>本月发现 ' + MONTH.defectsFound + ' · 闭环 ' + MONTH.defectsClosed + '</span></div><div class="tbl"><table class="t"><tr><th>缺陷</th><th>等级</th><th>登记</th><th>时限</th><th>状态</th><th>来源</th></tr>' + DEFECTS.map(d => '<tr><td>' + h(d.t) + '</td><td><span class="tag ' + (d.lv === '紧急' ? 'bad' : 'w') + '">' + h(d.lv) + '</span></td><td>' + h(d.reg) + '</td><td>' + d.limit + ' 天</td><td>' + h((LS.get('defects', {})[d.id] || {}).st || (d.photo && hz[d.photo]) || d.st) + '</td><td class="note">' + h(d.src) + '</td></tr>').join('') + '</table></div></div>'; },
  risk() { const rk = LS.get('risk', {}); return '<div class="card"><div class="h"><b>近两天风险作业</b><span>等级由她建议，班组长确认</span></div><div class="risk">' + this.RISKS.map(r => '<div class="r"><span><b>' + h(r.t) + '</b> · ' + h(r.when) + '<br><span class="note">' + h(r.fac.join(' · ')) + '</span></span>' + (rk[r.id] ? '<span class="tag ' + (rk[r.id] === '高' ? 'bad' : rk[r.id] === '中' ? 'w' : 'ok') + '">' + rk[r.id] + '风险 · 已确认</span>' : '<span class="tag">待定级</span>') + '<div class="bt" style="margin:0;padding:0"><button class="s" data-act="risk-grade" data-id="' + r.id + '">定级</button></div></div>').join('') + '</div></div>'; },
  day() { const sd = LS.get('docs', {})['safetyday']; return '<div class="card"><div class="h"><b>安全日 · 周五 15:00 · 台风季线路巡视与登杆作业</b><span id="sdst">' + (sd ? (sd.adopted ? '已定稿并通知' : '草稿') : '还没写') + '</span></div><div class="doc" id="sddoc">' + (sd ? sd.body.split('\n').map(p => '<p>' + h(p) + '</p>').join('') + '<div class="foot">以上内容为初稿与参考，由班组长确认后使用</div>' : '<div class="empty">点「写讲稿」</div>') + '</div><div class="bt" id="sdbt" style="margin-top:8px"><button data-act="sd-draft">写讲稿</button><button class="g" data-act="sd-adopt"' + (sd ? '' : ' disabled') + '>采用并通知全班</button></div></div>'; },
  DOC: ['各位，今天安全日讲台风季的线路巡视和登杆作业。', '先看上个月：[取一下上月登杆相关隐患……] 2 起，都是拉线锈蚀。田寮线 #7 杆昨晚又发现一处锈断，所以拉线是这个季度巡视的重点。', '安全方面：登杆前先验电，接地线要写清装在哪一档；登杆必须系安全带，杆根有锈蚀先做杆根检查。', '最后，明天凤凰线换刀闸，负责人韩雪，请大家配合现场安措布置。'],
  draft() { const host = $('#sddoc'); if (!host) return; DOCGEN.stream(host, this.DOC, { chips: [{ k: 'typhoon', n: '安全那段加上台风应对' }, { k: 'short', n: '口气再简短些' }, { k: 'data', n: '补上本月两票数据' }], done: () => { const docs = LS.get('docs', {}); docs['safetyday'] = { t: '安全日讲稿 · 台风季线路巡视与登杆作业', body: DOCGEN.text(host), ts: Date.now() }; LS.set('docs', docs); $('#sdst').textContent = '草稿'; $('[data-act="sd-adopt"]').disabled = false; XW.answer('讲稿写了一版，哪段不合适点那段下面的芯片，我只改那段。', null, { speak: false, confirm: false }); } }); DOCS.host = host; DOCS.kind = 'safetyday'; XW.type($('#xwsub'), '讲稿我写一版，写到数字的地方我要取一下数。', 45); },
  quizQ() { const pool = COURSES[0].qs.concat(COURSES[6].qs, [{ q: '停电作业装设接地线之前必须先（ ）。', a: ['验电', '挂标示牌', '拆围栏'], k: 0, pg: '作业指导书 · 停电作业安措' }, { q: '台风影响期间，登杆作业应（ ）。', a: ['停止，风停后先巡后登', '照常进行', '减少一人'], k: 0, pg: '班组约定 · 台风季登杆' }]); const done = LS.get('quiz', []); const q = pool[(done.length) % pool.length]; return { q, idx: done.length % pool.length }; },
  quiz() { const { q, idx } = this.quizQ(); return '<div class="card quiz"><div class="h"><b>安规考问 · 第 ' + (LS.get('quiz', []).length + 1) + ' 题</b><span>按岗位随机出题 · 答错她念原文</span></div><div style="font-size:13px;margin-bottom:6px" id="qtext">' + h(q.q) + '</div>' + q.a.map((a, i) => '<button class="opt" data-act="quiz-ans" data-idx="' + idx + '" data-i="' + i + '">' + String.fromCharCode(65 + i) + '. ' + h(a) + '</button>').join('') + '<div class="note" style="margin-top:6px">出处：' + h(q.pg) + '</div><div class="bt" id="qbt" style="margin-top:8px"></div></div>'; },
  draw() { const host = $('#safbody'); const s = S.sub || 'photo'; host.innerHTML = s === 'risk' ? this.risk() : s === 'day' ? this.day() : s === 'quiz' ? this.quiz() : this.photos(); const hz = LS.get('hazards', {}); if (s === 'photo') Object.keys(hz).forEach(k => { const ph = $('#ph-' + k), rd = $('#rd-' + k); if (ph) ph.classList.add('done'); if (rd) rd.classList.add('done'); }); }
};
PAGES.safety = {
  render() { return cmdHTML(['田寮线那张照片再认一遍', '明天凤凰线换刀闸是什么风险等级', '写本周安全日讲稿', '考我一道安规题']) + pageHead('安全管理', '隐患照片 · 风险作业 · 安全日 · 安规考问') + tabsHTML(SAFETYPG.tabs, S.sub || 'photo') + '<div id="safbody"></div>'; },
  after() { SAFETYPG.draw(); }
};
Object.assign(ACT, {
  'risk-grade'(el) { const r = SAFETYPG.RISKS.find(x => x.id === el.dataset.id); const txt = r.id === 'r1' ? '凤凰线换刀闸要登杆，明天台风蓝色预警，风力可能到 6 级；#9 杆的拉线 9 月 1 日刚换，说明这段线路拉线普遍老化；负责人韩雪有资格，4 个人里有 1 个学员。登杆加台风，这是高风险，管控措施得写台风期间停止登杆、风停后先巡后登。' : r.id === 'r2' ? '开关柜内检查，室内不受天气影响；但陈浩和周明都是初级作业员，没有负责人资格，柜内带电部位多。我定中风险，措施是加一名高级作业员监护。' : '沿线巡视不登杆，34 度高温，三个人里刘一鸣是学员。低风险，但要按高温约定三小时轮换。';
    XW.think(txt, () => { XW.answer('我建议定为' + r.lv + '风险。' + (r.id === 'r1' ? '管控措施：台风影响期间停止登杆，风停后先巡后登；登杆前验电、接地线写明档位；杆根检查。' : r.id === 'r2' ? '管控措施：增加韩雪监护，柜内作业前核对运行方式。' : '管控措施：11:00 轮换，随身带水，学员不单独行动。') + '等你确认。', null, { speak: false }); XW.card('<div class="bt" style="margin-top:0"><button data-act="risk-ok" data-id="' + r.id + '" data-lv="' + r.lv + '">确认' + r.lv + '风险</button><button class="g" data-act="risk-ok" data-id="' + r.id + '" data-lv="' + (r.lv === '高' ? '中' : '高') + '">改为' + (r.lv === '高' ? '中' : '高') + '风险</button></div>'); }); },
  'risk-ok'(el) { const rk = LS.get('risk', {}); rk[el.dataset.id] = el.dataset.lv; LS.set('risk', rk); XW.answer('记为' + el.dataset.lv + '风险，确认人赵立群。管控措施我写进了明天的派工单安措要点。', null, { confirm: false }); SAFETYPG.draw(); },
  'sd-draft'() { SAFETYPG.draft(); },
  'sd-adopt'() { const docs = LS.get('docs', {}); if (docs['safetyday']) { docs['safetyday'].adopted = true; docs['safetyday'].body = DOCGEN.text($('#sddoc')) || docs['safetyday'].body; LS.set('docs', docs); } XW.fly('安全日通知已发全班 · 周五 15:00'); XW.answer('定稿了，通知发给全班 12 个人，周五下午三点，会议室。讲稿在文稿中心也能找到。', null, { confirm: false }); $('#sdst').textContent = '已定稿并通知'; badgeSync(); },
  'quiz-ans'(el) { const { q } = SAFETYPG.quizQ(); const i = +el.dataset.i; $$('.quiz .opt').forEach(b => b.disabled = true); el.classList.add(i === q.k ? 'ok' : 'bad'); if (i !== q.k) $$('.quiz .opt')[q.k].classList.add('ok'); const done = LS.get('quiz', []); done.push({ i, ok: i === q.k }); LS.set('quiz', done);
    const kb = KB.find(k => q.pg.includes('停电') ? k.id === 'k6' : q.pg.includes('台风') ? k.id === 'k8' : q.pg.includes('电缆') ? k.id === 'k7' : k.id === 'k1'); const orig = q.pg.includes('停电') ? '停电 → 验电 → 装设接地线 → 悬挂标示牌与装设围栏。接地线装设位置应在工作票上写明。' : q.pg.includes('台风') ? EXPERIENCE[0].body : q.pg.includes('电缆') ? KB[6].body : '继电保护的基本要求是选择性、快速性、可靠性、灵敏性；正确切断离故障点最近的断路器体现选择性。';
    if (i === q.k) XW.answer('对。' + (q.pg.includes('作业') || q.pg.includes('班组') ? '原文是：' + orig : '这道出自' + q.pg + '。'), null, { confirm: false }); else XW.answer('不对，答案是 ' + String.fromCharCode(65 + q.k) + '。我把原文念一遍：' + orig, null, { confirm: false });
    $('#qbt').innerHTML = '<button data-act="nav" data-to="safety" data-sub="quiz">下一题</button>'; }
});
