/* ===== 安全管理：隐患照片墙、隐患闭环看板、风险作业与天气、两票与违章、安全日、安规考问 ===== */
const SAFETYPG = {
  tabs: [{ k: 'photo', n: '隐患照片' }, { k: 'flow', n: '隐患闭环' }, { k: 'risk', n: '风险作业' }, { k: 'ticket', n: '两票与违章' }, { k: 'day', n: '安全日' }, { k: 'quiz', n: '安规考问' }],
  filter: '全部',
  RISKS: [{ id: 'r1', t: '10kV 凤凰线更换 #12 杆刀闸', when: '明日 09:00', fac: ['登杆作业', '台风黄色预警', '拉线 #9 杆刚更换', '负责人韩雪 · 4 人'], lv: '高' }, { id: 'r2', t: '光明变 10kV 出线柜检查', when: '今日 14:00', fac: ['开关柜内作业', '室内', '陈浩 · 周明 均为初级'], lv: '中' }, { id: 'r3', t: '塘尾线巡视', when: '今日 09:00', fac: ['沿线巡视不登杆', '34℃ 高温', '3 人含学员'], lv: '低' }, { id: 'r4', t: '凤凰线电缆段振荡波试验', when: '下周四', fac: ['高压试验', '停电作业', '韩雪 · 王安 · 吴倩'], lv: '高' }, { id: 'r5', t: '光明变出线柜局放检测', when: '下周三', fac: ['带电检测', '室内', '韩雪 · 郭子扬'], lv: '中' }],
  allDefects() { return DEFECTS.concat(DEFECTS2); },
  stOf(d) { const hz = LS.get('hazards', {}); const df = LS.get('defects', {}); return (df[d.id] || {}).st || (d.photo && hz[d.photo]) || d.st; },
  photos() { const hz = LS.get('hazards', {}); const list = this.allDefects().filter(d => d.photo); const f = this.filter; const shown = list.filter(d => f === '全部' || (f === '紧急' && d.lv === '紧急') || (f === '一般' && d.lv === '一般') || (f === '待确认' && /待确认|已登记|待验收/.test(this.stOf(d))) || (f === '已关闭' && /已关闭|已消缺/.test(this.stOf(d))));
    return '<div class="kbq" style="margin-bottom:8px">' + ['全部', '紧急', '一般', '待确认', '已关闭'].map(k => '<b data-act="hz-filter" data-k="' + k + '" style="' + (k === f ? 'background:var(--tint);color:var(--pri);border-color:#c9cbf5' : '') + '">' + k + '</b>').join('') + '<span class="note" style="align-self:center">' + shown.length + ' 张 · 点照片她重新认一遍</span></div><div class="wall">' + shown.map(d => '<div class="card"><div class="h"><b>' + h(d.t.split('（')[0]) + '</b><span>' + h(hz[d.photo] || this.stOf(d)) + '</span></div>' + PHOTO.html(d.photo, true) + PHOTO.rowsHTML(d.photo) + '<div class="bt" style="margin-top:8px"><button data-act="photo" data-key="' + d.photo + '">核对</button><button class="g" data-act="hz-ask" data-key="' + d.photo + '">让现场确认</button></div></div>').join('') + '</div>' +
      '<div class="card"><div class="h"><b>隐患台账</b><span>本月发现 ' + MONTH.defectsFound + ' · 闭环 ' + MONTH.defectsClosed + ' · 点一行她说</span></div><div class="tbl"><table class="t"><tr><th>缺陷</th><th>等级</th><th>登记</th><th>时限</th><th>状态</th><th>来源</th></tr>' + this.allDefects().map(d => '<tr data-act="hz-row" data-id="' + d.id + '" style="cursor:pointer"><td>' + h(d.t) + '</td><td><span class="tag ' + (d.lv === '紧急' ? 'bad' : 'w') + '">' + h(d.lv) + '</span></td><td>' + h(d.reg) + '</td><td>' + d.limit + ' 天</td><td>' + h(this.stOf(d)) + '</td><td class="note">' + h(d.src) + '</td></tr>').join('') + '</table></div></div>'; },
  flow() { const all = this.allDefects(); const cols = [['已登记', /待确认|已登记/], ['处理中', /处理中|已催办/], ['待验收', /待验收/], ['已关闭', /已关闭|已消缺|已撤销/], ['超期', /超期/]]; const byLine = {}; all.forEach(d => { const l = d.t.split(' ')[0]; byLine[l] = (byLine[l] || 0) + 1; });
    return '<div class="grid2" style="grid-template-columns:1fr 1.6fr"><div><div class="card"><div class="h"><b>闭环漏斗 · 本月</b><span>发现 → 关闭</span></div>' + CH.mini.funnel(HZ_FLOW.map((s, i) => ({ k: s.k, v: s.v, act: 'hz-stage', tip: s.k + ' ' + s.v + ' 处 · 点开她说' }))) + '</div><div class="card" style="margin-top:10px"><div class="h"><b>按线路 · 站</b><span>本月</span></div>' + CH.mini.bars(Object.keys(byLine).map((k, i) => ({ n: k, v: byLine[k], c: CPAL[i % 6], act: 'hz-line', k, tip: k + ' ' + byLine[k] + ' 处 · 点开看' })), { max: 5, unit: ' 处', h: 14 }) + '</div><div class="card" style="margin-top:10px"><div class="h"><b>按等级</b></div>' + CH.mini.donut([{ k: '紧急', v: all.filter(d => d.lv === '紧急').length, c: '#e5484d' }, { k: '一般', v: all.filter(d => d.lv === '一般').length, c: CPAL[1] }], { sub: '处' }) + '</div></div>' +
      '<div class="card"><div class="h"><b>隐患看板</b><span>点一张卡她说下一步</span></div><div class="kan">' + cols.map(([n, re]) => { const items = all.filter(d => re.test(this.stOf(d))); return '<div class="kcol"><div class="kh">' + n + ' <em>' + items.length + '</em></div>' + items.map(d => '<div class="kc ' + (d.lv === '紧急' ? 'bad' : '') + '" data-act="hz-card" data-id="' + d.id + '"><b>' + h(d.t.split(' ').slice(0, 2).join(' ')) + '</b><span>' + h(d.t.split(' ').slice(2).join(' ')) + '</span><i>' + h(d.reg.slice(5)) + ' · ' + d.limit + ' 天</i></div>').join('') + '</div>'; }).join('') + '</div></div></div>'; },
  risk() { const rk = LS.get('risk', {}); const cnt = { 高: 0, 中: 0, 低: 0 }; this.RISKS.forEach(r => cnt[rk[r.id] || r.lv]++);
    return '<div class="card"><div class="h"><b>未来 7 天天气</b><span>点一天她说对作业的影响</span></div><div class="wx">' + WEATHER7.map((w, i) => '<div class="wxd ' + (w.warn ? (/橙|黄/.test(w.warn) ? 'w' : 'c') : '') + '" data-act="wx-day" data-i="' + i + '"><b>' + h(w.d) + '</b><span>' + h(w.w) + '</span><em>' + w.t + '℃ · ' + w.wind + ' 级</em>' + (w.warn ? '<i>' + h(w.warn) + '</i>' : '') + '</div>').join('') + '</div></div>' +
      '<div class="grid2" style="grid-template-columns:1.6fr 1fr"><div class="card"><div class="h"><b>近期风险作业</b><span>等级由她建议，班组长确认</span></div><div class="risk">' + this.RISKS.map(r => '<div class="r"><span><b>' + h(r.t) + '</b> · ' + h(r.when) + '<br><span class="note">' + h(r.fac.join(' · ')) + '</span></span>' + (rk[r.id] ? '<span class="tag ' + (rk[r.id] === '高' ? 'bad' : rk[r.id] === '中' ? 'w' : 'ok') + '">' + rk[r.id] + '风险 · 已确认</span>' : '<span class="tag">待定级</span>') + '<div class="bt" style="margin:0;padding:0"><button class="s" data-act="risk-grade" data-id="' + r.id + '">定级</button></div></div>').join('') + '</div></div>' +
      '<div><div class="card"><div class="h"><b>风险分布</b></div>' + CH.mini.donut([{ k: '高风险', v: cnt.高, c: '#e5484d' }, { k: '中风险', v: cnt.中, c: CPAL[1] }, { k: '低风险', v: cnt.低, c: CPAL[4] }], { sub: '项作业' }) + '</div><div class="card" style="margin-top:10px"><div class="h"><b>台风管控措施</b><span>预警期间</span></div><div class="jobs">' + [['台风影响期间停止登杆作业，风停后先巡后登', true], ['沿海段拉线专项巡视（台风前）', true], ['配电房、电缆沟排水检查', false], ['抢修物资与车辆备勤', true], ['高温三小时轮换', true]].map(([t, ok]) => '<div><span style="font-size:11.5px;color:var(--ink)">' + h(t) + '</span><span class="tag ' + (ok ? 'ok' : 'w') + '">' + (ok ? '已落实' : '待落实') + '</span></div>').join('') + '</div><div class="bt"><button class="s g" data-act="typhoon-check">让她核一遍</button></div></div></div></div>'; },
  ticketTab() { const all = LS.get('tickets', {}); return '<div class="grid2"><div><div class="card"><div class="h"><b>两票 · 本月</b><span>' + MONTH.tickets + ' 张 · 合格 ' + MONTH.ticketsOK + '</span></div><div class="tbl"><table class="t"><tr><th>票号</th><th>类型</th><th>任务</th><th>负责人</th><th>状态</th></tr>' + TICKETS.map(t => '<tr data-act="tk-open" data-no="' + h(t.no) + '" style="cursor:pointer"><td>' + h(t.no) + '</td><td>' + h(t.kind) + '</td><td>' + h(t.task) + '</td><td>' + h(t.lead) + '</td><td>' + ((all[t.no] || {}).st ? '<span class="tag ok">已审核</span>' : '<span class="tag w">待审</span>') + '</td></tr>').join('') + [['配一 2026-0901-02', '第一种工作票', '凤凰线 #9 杆拉线更换', '黄伟强'], ['配一 2026-0902-01', '第二种工作票', '志远站 F14 消缺', '黄伟强'], ['配一 2026-0902-03', '第二种工作票', '光明变出线柜检查', '韩雪']].map(r => '<tr><td>' + r.join('</td><td>') + '</td><td><span class="tag ok">合格</span></td></tr>').join('') + '</table></div></div>' +
      '<div class="card" style="margin-top:10px"><div class="h"><b>两票合格率 · 逐月</b><span>点一个月她说</span></div>' + CH.mini.line([{ n: '合格率', vals: TICKET_M.n.map((n, i) => Math.round(TICKET_M.ok[i] / n * 100)), c: CPAL[0], area: true, act: 'tk-month' }], TICKET_M.m, { max: 100, pct: true, h: 120 }) + '</div></div>' +
      '<div><div class="card"><div class="h"><b>违章记录 · 本年</b><span>' + VIOLATIONS.length + ' 起 · 点一条她说处理</span></div><div class="tbl"><table class="t"><tr><th>日期</th><th>人员</th><th>违章</th><th>等级</th></tr>' + VIOLATIONS.map((v, i) => '<tr data-act="vio-row" data-i="' + i + '" style="cursor:pointer"><td>' + h(v.d) + '</td><td>' + h(v.who) + '</td><td>' + h(v.t) + '</td><td><span class="tag ' + (v.lv === '严重' ? 'bad' : 'w') + '">' + h(v.lv) + '</span></td></tr>').join('') + '</table></div></div>' +
      '<div class="card" style="margin-top:10px"><div class="h"><b>违章趋势 · 逐月</b></div>' + CH.mini.cols(TICKET_M.m.map((m, i) => ({ n: m, v: VIO_M[i], c: VIO_M[i] ? '#e5484d' : RAMP[1] })), { max: 3, h: 110, labels: true }) + '<div class="bt"><button class="s g" data-act="tk-report">生成两票与违章月报</button></div><div class="doc" id="tkrep" style="margin-top:6px"></div></div></div></div>'; },
  day() { const sd = LS.get('docs', {})['safetyday']; const sign = LS.get('sign', {}); return '<div class="grid2" style="grid-template-columns:1.5fr 1fr"><div class="card"><div class="h"><b>安全日 · 周五 15:00 · 台风季线路巡视与登杆作业</b><span id="sdst">' + (sd ? (sd.adopted ? '已定稿并通知' : '草稿') : '还没写') + '</span></div><div class="doc" id="sddoc">' + (sd ? sd.body.split('\n').map(p => '<p>' + h(p) + '</p>').join('') + '<div class="foot">以上内容为初稿与参考，由班组长确认后使用</div>' : '<div class="empty">点「写讲稿」</div>') + '</div><div class="bt" id="sdbt" style="margin-top:8px"><button data-act="sd-draft">写讲稿</button><button class="g" data-act="sd-adopt"' + (sd ? '' : ' disabled') + '>采用并通知全班</button></div></div>' +
      '<div><div class="card"><div class="h"><b>签到</b><span>' + Object.values(sign).filter(Boolean).length + '/' + PEOPLE.length + ' · 点名字签到</span></div><div class="ppl on" style="margin:0;border:0;padding:0"><div class="row">' + PEOPLE.map(p => '<div class="chip" data-act="sd-sign" data-who="' + p.n + '" style="width:auto;flex-direction:row;align-items:center;gap:6px"><b>' + h(p.n) + '</b><span class="tag ' + (sign[p.n] ? 'ok' : '') + '" style="margin:0">' + (sign[p.n] ? '已签' : '未签') + '</span></div>').join('') + '</div></div></div>' +
      '<div class="card" style="margin-top:10px"><div class="h"><b>历史活动</b><span>点一条她复述要点</span></div><div class="jobs">' + SAFETY_HIST.map((x, i) => '<div data-act="sd-hist" data-i="' + i + '" style="cursor:pointer"><span style="font-size:11.5px;color:var(--ink)">' + h(x.t) + '<br><span class="note">' + h(x.d) + ' · 主持 ' + h(x.host) + '</span></span><span class="tag">' + x.n + ' 人</span></div>').join('') + '</div>' + CH.mini.cols(SAFETY_HIST.slice().reverse().map(x => ({ n: x.d, v: x.n, c: CPAL[4] })), { max: 12, h: 90 }) + '</div></div></div>'; },
  DOC: ['各位，今天安全日讲台风季的线路巡视和登杆作业。', '先看上个月：[取一下上月登杆相关隐患……] 2 起，都是拉线锈蚀。田寮线 #7 杆昨晚又发现一处锈断，所以拉线是这个季度巡视的重点。', '安全方面：登杆前先验电，接地线要写清装在哪一档；登杆必须系安全带，杆根有锈蚀先做杆根检查。', '最后，明天凤凰线换刀闸，负责人韩雪，请大家配合现场安措布置。'],
  draft() { const host = $('#sddoc'); if (!host) return; DOCGEN.stream(host, this.DOC, { chips: [{ k: 'typhoon', n: '安全那段加上台风应对' }, { k: 'short', n: '口气再简短些' }, { k: 'data', n: '补上本月两票数据' }], done: () => { const docs = LS.get('docs', {}); docs['safetyday'] = { t: '安全日讲稿 · 台风季线路巡视与登杆作业', body: DOCGEN.text(host), ts: Date.now() }; LS.set('docs', docs); $('#sdst').textContent = '草稿'; $('[data-act="sd-adopt"]').disabled = false; XW.answer('讲稿写了一版，哪段不合适点那段下面的芯片，我只改那段。', null, { speak: false, confirm: false }); } }); DOCS.host = host; DOCS.kind = 'safetyday'; XW.type($('#xwsub'), '讲稿我写一版，写到数字的地方我要取一下数。', 45); },
  pool() { return COURSES[0].qs.concat(COURSES[6].qs, [{ q: '停电作业装设接地线之前必须先（ ）。', a: ['验电', '挂标示牌', '拆围栏'], k: 0, pg: '作业指导书 · 停电作业安措' }, { q: '台风影响期间，登杆作业应（ ）。', a: ['停止，风停后先巡后登', '照常进行', '减少一人'], k: 0, pg: '班组约定 · 台风季登杆' }, { q: '气温 33℃ 以上连续作业不超过（ ）小时应轮换。', a: ['三', '五', '八'], k: 0, pg: '班组约定 · 高温' }, { q: '需要停电的作业应使用（ ）。', a: ['第一种工作票', '第二种工作票', '口头指令'], k: 0, pg: '作业指导书 · 两票' }]); },
  quizQ() { const pool = this.pool(); const done = LS.get('quiz', []); const idx = done.length % pool.length; return { q: pool[idx], idx, pool }; },
  quiz() { const { q, idx, pool } = this.quizQ(); const done = LS.get('quiz', []); const ok = done.filter(d => d.ok).length; const wrong = done.map((d, i) => d.ok ? null : pool[i % pool.length]).filter(Boolean);
    return '<div class="grid2" style="grid-template-columns:1.4fr 1fr"><div class="card quiz"><div class="h"><b>安规考问 · 第 ' + (done.length + 1) + ' 题</b><span>按岗位随机出题 · 答错她念原文</span></div><div style="font-size:13px;margin-bottom:6px" id="qtext">' + h(q.q) + '</div>' + q.a.map((a, i) => '<button class="opt" data-act="quiz-ans" data-idx="' + idx + '" data-i="' + i + '">' + String.fromCharCode(65 + i) + '. ' + h(a) + '</button>').join('') + '<div class="note" style="margin-top:6px">出处：' + h(q.pg) + '</div><div class="bt" id="qbt" style="margin-top:8px"></div></div>' +
      '<div><div class="card"><div class="h"><b>本轮成绩</b><span>' + done.length + ' 题</span></div>' + CH.meters([{ k: 'q', n: '答对', v: done.length ? ok / done.length : 0, txt: ok + '/' + done.length, tip: '本轮答对 ' + ok + ' 题' }]) + '<div class="note" style="margin-top:6px">题库 ' + pool.length + ' 题 · 来自故障分析、电缆试验课件与作业指导书</div>' + CH.mini.donut([{ k: '故障分析', v: 5, c: CPAL[0] }, { k: '电缆试验', v: 4, c: CPAL[2] }, { k: '安措与约定', v: 4, c: CPAL[1] }], { sub: '题' }) + '</div>' +
      '<div class="card" style="margin-top:10px"><div class="h"><b>错题本</b><span>' + wrong.length + ' 题</span></div>' + (wrong.length ? wrong.map(w => '<div class="note" style="margin:4px 0;color:var(--ink)">· ' + h(w.q) + ' <b>' + h(w.a[w.k]) + '</b></div>').join('') : '<div class="empty">还没有错题</div>') + '</div></div></div>'; },
  draw() { const host = $('#safbody'); const s = S.sub || 'photo'; host.innerHTML = s === 'risk' ? this.risk() : s === 'day' ? this.day() : s === 'quiz' ? this.quiz() : s === 'flow' ? this.flow() : s === 'ticket' ? this.ticketTab() : this.photos(); const hz = LS.get('hazards', {}); if (s === 'photo') { this.allDefects().forEach(d => { if (d.photo && (hz[d.photo] || /已关闭|已消缺|待验收/.test(d.st))) { const ph = $('#ph-' + d.photo), rd = $('#rd-' + d.photo); if (ph) ph.classList.add('done'); if (rd) rd.classList.add('done'); } }); } CH.mount(host); }
};
PAGES.safety = {
  render() { return cmdHTML(['田寮线那张照片再认一遍', '明天凤凰线换刀闸是什么风险等级', '写本周安全日讲稿', '考我一道安规题', '本月两票合格率']) + pageHead('安全管理', '隐患照片 · 隐患闭环 · 风险作业 · 两票与违章 · 安全日 · 安规考问') + tabsHTML(SAFETYPG.tabs, S.sub || 'photo') + '<div id="safbody"></div>'; },
  after() { SAFETYPG.draw(); }
};
Object.assign(ACT, {
  'hz-filter'(el) { SAFETYPG.filter = el.dataset.k; SAFETYPG.draw(); },
  'hz-row'(el) { const d = SAFETYPG.allDefects().find(x => x.id === el.dataset.id); XW.answer(d.t + '，' + d.lv + '缺陷，' + d.reg.slice(5) + ' 登记，时限 ' + d.limit + ' 天，现在' + SAFETYPG.stOf(d) + '。来源是' + d.src + '。' + (/超期/.test(SAFETYPG.stOf(d)) ? '要我发催办吗？' : ''), /超期/.test(SAFETYPG.stOf(d)) ? h(d.t) + '现在超期，要我发催办吗？<div class="bt"><button data-act="urge">发出催办</button><button class="g">先不用</button></div>' : null, { confirm: false }); },
  'hz-card'(el) { const d = SAFETYPG.allDefects().find(x => x.id === el.dataset.id); const st = SAFETYPG.stOf(d); const next = /登记|待确认/.test(st) ? '下一步是派人处理，' + (d.photo ? '现场确认后' : '') + '我可以直接生成派工。' : /处理中|催办/.test(st) ? '下一步等回传处理照片，回传后转待验收。' : /待验收/.test(st) ? '下一步验收，验收人建议韩雪。' : '已经关闭，可以存为案例。'; XW.answer(d.t + '现在' + st + '。' + next, h(d.t) + '现在' + h(st) + '。' + h(next) + '<div class="bt">' + (/登记|待确认/.test(st) ? '<button data-act="nav" data-to="sched" data-sub="pool">去派工</button>' : /待验收/.test(st) ? '<button data-act="hz-accept" data-id="' + d.id + '">验收通过</button>' : /关闭/.test(st) ? '<button data-act="nav" data-to="know">存为案例</button>' : '<button data-act="hz-ask" data-key="' + (d.photo || 'p7') + '">催回传</button>') + '</div>', { confirm: false }); },
  'hz-accept'(el) { const df = LS.get('defects', {}); df[el.dataset.id] = { st: '已关闭 · 验收 韩雪', ts: Date.now() }; LS.set('defects', df); XW.fly('缺陷已关闭 · 验收人 韩雪'); XW.answer('验收通过，这条关闭了，同步到 OMS 的处理记录。', null, { confirm: false }); SAFETYPG.draw(); },
  'hz-stage'(el) { const s = HZ_FLOW.find(x => x.k === el.dataset.k); XW.answer('本月' + s.k + ' ' + s.v + ' 处。' + (s.k === '处理中' ? '四处里志远站 F14 超期，其他三处在时限内。' : s.k === '待验收' ? '凤凰线 #18 绝缘子已更换，等韩雪验收。' : s.k === '已关闭' ? '关闭的四处平均用了 4.5 天，最快的是电缆沟积水，两天。' : '发现的九处里六处来自巡视，两处来自群照片，一处来自 OMS。'), null, { confirm: false, chart: s.k === '已关闭' ? CH.mini.bars([{ n: '电缆沟积水', v: 2 }, { n: '凤凰线 #9', v: 6 }, { n: '志远站遥控', v: 3 }, { n: '塘尾 #22', v: 7 }].map(x => ({ n: x.n, v: x.v, c: CPAL[4] })), { unit: ' 天', max: 8, h: 13 }) : null }); },
  'hz-line'(el) { const k = el.dataset.k; const list = SAFETYPG.allDefects().filter(d => d.t.startsWith(k)); XW.answer(k + '本月 ' + list.length + ' 处：' + list.map(d => d.t.replace(k, '').trim() + '（' + SAFETYPG.stOf(d) + '）').join('、') + '。', null, { confirm: false }); },
  'wx-day'(el) { const w = WEATHER7[+el.dataset.i]; const js = JOBS_WEEK.filter(j => j.d0 <= (+el.dataset.i - 4) && (+el.dataset.i - 4) <= j.d1); XW.answer(w.d + ' ' + w.w + '，' + w.t + '℃，风 ' + w.wind + ' 级' + (w.warn ? '，' + w.warn + '预警' : '') + '。' + (w.wind >= 6 ? '登杆作业要停，' + (js.filter(j => /登杆|绝缘子|拉线|刀闸/.test(j.t)).map(j => j.t).join('、') || '明天凤凰线换刀闸') + '看风停再上。' : w.t >= 33 ? '高温，三小时轮换。' : '适合作业。' + (js.length ? '那天排了' + js.map(j => j.t).join('、') + '。' : '')), null, { confirm: false }); },
  'typhoon-check'() { XW.think('五条措施……停止登杆已经写进明天派工单的安措；沿海段拉线专项巡视，塘尾线排在下周一到周三，台风前来不及全巡完；配电房和电缆沟排水检查还没派人；物资和车辆备勤是抢修班负责，已确认；高温轮换今天已经执行一次。', () => { XW.answer('五条里四条落实了，配电房和电缆沟排水检查还没派人。志远站电缆沟上个月刚积过水，我建议今天下午让陈浩、周明检查完出线柜顺路看一下。要派吗？', '五条里四条落实了，配电房和电缆沟排水检查还没派人。我建议今天下午让陈浩、周明顺路看一下。要派吗？<div class="bt"><button data-act="typhoon-go">派</button><button class="g">明天再说</button></div>', { confirm: false }); }); },
  'typhoon-go'() { XW.fly('已通知 陈浩 · 周明 · 下午顺路检查志远站电缆沟排水'); XW.answer('派了，陈浩和周明下午检查完出线柜去看电缆沟，拍照回传。', null, { confirm: false }); },
  'tk-open'(el) { SCHEDPG.ticketNo = el.dataset.no; nav('sched', 'ticket'); },
  'tk-month'(el) { const i = +el.dataset.i; XW.answer(TICKET_M.m[i] + '开出 ' + TICKET_M.n[i] + ' 张票，合格 ' + TICKET_M.ok[i] + ' 张' + (TICKET_M.ok[i] < TICKET_M.n[i] ? '，不合格的一张是郭子扬那张未签字开工的第二种工作票，已经通报。' : '，全部合格。'), null, { confirm: false }); },
  'vio-row'(el) { const v = VIOLATIONS[+el.dataset.i]; XW.answer(v.d + ' ' + v.who + '，' + v.t + '，' + v.lv + '违章，处理是' + v.fix + '。' + (v.lv === '严重' ? '这条已经进了他的年度记录，季度评价时会看到。' : '之后没有再犯。'), null, { confirm: false }); },
  'tk-report'() { const host = $('#tkrep'); DOCGEN.stream(host, ['两票与违章月报 · 2026 年 8 月', '一、两票：本月开出工作票 [取一下两票台账……] ' + MONTH.tickets + ' 张（第一种 5、第二种 7），合格 ' + MONTH.ticketsOK + ' 张，合格率 100%；操作票 8 张，合格 8 张。', '二、违章：本月无违章；本年累计 3 起（一般 2、严重 1），均已处理并通报。', '三、问题与措施：8 月两张票的接地线位置描述不完整，已在班前会强调"接地线写清档位"；9 月起工作票由她先审一遍再签发。'], { chips: [{ k: 'short', n: '口气再简短些' }], done() { XW.answer('月报写好了，数字从两票台账和违章记录取的。', null, { speak: false, confirm: false }); } }); DOCS.host = host; DOCS.kind = 'tkreport'; },
  'risk-grade'(el) { const r = SAFETYPG.RISKS.find(x => x.id === el.dataset.id); const txt = r.id === 'r1' ? '凤凰线换刀闸要登杆，明天台风黄色预警，风力可能到 6 级；#9 杆的拉线 9 月 1 日刚换，说明这段线路拉线普遍老化；负责人韩雪有资格，4 个人里有 1 个学员。登杆加台风，这是高风险，管控措施得写台风期间停止登杆、风停后先巡后登。' : r.id === 'r2' ? '开关柜内检查，室内不受天气影响；但陈浩和周明都是初级作业员，没有负责人资格，柜内带电部位多。我定中风险，措施是加一名高级作业员监护。' : r.id === 'r3' ? '沿线巡视不登杆，34 度高温，三个人里刘一鸣是学员。低风险，但要按高温约定三小时轮换。' : r.id === 'r4' ? '振荡波试验是高压试验，电缆两端要验电放电接地，人员站在围栏外；韩雪有电缆试验证，王安、吴倩也有。停电作业加高压，定高风险。' : '局放检测是带电检测，不停电；韩雪、郭子扬都做过。中风险，措施是保持安全距离、仪器校验。';
    const fac = r.id === 'r1' ? [['作业类型', 4], ['天气', 4], ['设备状态', 3], ['人员', 2]] : r.id === 'r2' ? [['作业类型', 3], ['天气', 1], ['设备状态', 2], ['人员', 3]] : r.id === 'r3' ? [['作业类型', 1], ['天气', 3], ['设备状态', 1], ['人员', 2]] : r.id === 'r4' ? [['作业类型', 4], ['天气', 2], ['设备状态', 3], ['人员', 1]] : [['作业类型', 3], ['天气', 1], ['设备状态', 2], ['人员', 1]];
    XW.think(txt, () => { XW.answer('我建议定为' + r.lv + '风险。' + (r.id === 'r1' ? '管控措施：台风影响期间停止登杆，风停后先巡后登；登杆前验电、接地线写明档位；杆根检查。' : r.id === 'r2' ? '管控措施：增加韩雪监护，柜内作业前核对运行方式。' : r.id === 'r3' ? '管控措施：11:00 轮换，随身带水，学员不单独行动。' : r.id === 'r4' ? '管控措施：试验前后各放电一次，围栏外留人，数据当场记。' : '管控措施：仪器校验，保持安全距离，评估背景干扰。') + '等你确认。', null, { speak: false, chart: CH.mini.bars(fac.map(([n, v]) => ({ n, v, c: v >= 4 ? '#e5484d' : v >= 3 ? CPAL[1] : CPAL[4], tip: n + ' 风险因子 ' + v + '/4' })), { max: 4.5, h: 13, x0: 56 }) }); XW.card('<div class="bt" style="margin-top:0"><button data-act="risk-ok" data-id="' + r.id + '" data-lv="' + r.lv + '">确认' + r.lv + '风险</button><button class="g" data-act="risk-ok" data-id="' + r.id + '" data-lv="' + (r.lv === '高' ? '中' : '高') + '">改为' + (r.lv === '高' ? '中' : '高') + '风险</button></div>'); }); },
  'risk-ok'(el) { const rk = LS.get('risk', {}); rk[el.dataset.id] = el.dataset.lv; LS.set('risk', rk); XW.answer('记为' + el.dataset.lv + '风险，确认人赵立群。管控措施我写进了派工单的安措要点。', null, { confirm: false }); SAFETYPG.draw(); },
  'sd-draft'() { SAFETYPG.draft(); },
  'sd-adopt'() { const docs = LS.get('docs', {}); if (docs['safetyday']) { docs['safetyday'].adopted = true; docs['safetyday'].body = DOCGEN.text($('#sddoc')) || docs['safetyday'].body; LS.set('docs', docs); } XW.fly('安全日通知已发全班 · 周五 15:00'); XW.answer('定稿了，通知发给全班 12 个人，周五下午三点，会议室。讲稿在文稿中心也能找到。', null, { confirm: false }); $('#sdst').textContent = '已定稿并通知'; badgeSync(); },
  'sd-sign'(el) { const sign = LS.get('sign', {}); sign[el.dataset.who] = !sign[el.dataset.who]; LS.set('sign', sign); SAFETYPG.draw(); },
  'sd-hist'(el) { const x = SAFETY_HIST[+el.dataset.i]; XW.answer(x.d + ' 的安全日讲的是"' + x.t + '"，' + x.host + '主持，' + x.n + ' 人参加。' + (x.t.includes('拉线') ? '要点是拉线根部和抱箍两处看锈蚀、推杆看晃动、沿海段两年一换。' : x.t.includes('高温') ? '要点是 33 度以上三小时轮换、随身带水、学员不单独行动。' : x.t.includes('电缆') ? '要点是试验前后放电、围栏外留人、数据当场记。' : x.t.includes('坠落') ? '要点是安全带二次保护、登杆前查杆根。' : x.t.includes('两票') ? '要点是接地线写清档位、验电项不能漏。' : '要点是汛期前检查配电房与电缆沟排水。'), null, { confirm: false }); },
  'quiz-ans'(el) { const { q } = SAFETYPG.quizQ(); const i = +el.dataset.i; $$('.quiz .opt').forEach(b => b.disabled = true); el.classList.add(i === q.k ? 'ok' : 'bad'); if (i !== q.k) $$('.quiz .opt')[q.k].classList.add('ok'); const done = LS.get('quiz', []); done.push({ i, ok: i === q.k }); LS.set('quiz', done);
    const orig = q.pg.includes('停电') ? '停电 → 验电 → 装设接地线 → 悬挂标示牌与装设围栏。接地线装设位置应在工作票上写明。' : q.pg.includes('台风') ? EXPERIENCE[0].body : q.pg.includes('高温') ? KB2.find(k => k.id === 'k22').body : q.pg.includes('两票') ? KB2.find(k => k.id === 'k19').body : q.pg.includes('电缆') ? KB[6].body : '继电保护的基本要求是选择性、快速性、可靠性、灵敏性；正确切断离故障点最近的断路器体现选择性。';
    if (i === q.k) XW.answer('对。' + (q.pg.includes('作业') || q.pg.includes('班组') ? '原文是：' + orig : '这道出自' + q.pg + '。'), null, { confirm: false }); else XW.answer('不对，答案是 ' + String.fromCharCode(65 + q.k) + '。我把原文念一遍：' + orig, null, { confirm: false });
    $('#qbt').innerHTML = '<button data-act="nav" data-to="safety" data-sub="quiz">下一题</button>'; }
});
