/* ===== 用工安排：任务池派工、周关键节点（A/B · 管控周期 · 周报出处 · 本周闭环）、下周计划、值班表、审票（多票）、现场进度、班前班后会 ===== */
const TYPE_C = { 建设: CPAL[0], 消缺: CPAL[1], 维护: CPAL[2], 专项: CPAL[3], 试验验收: CPAL[4], 培训: CPAL[5], 值班: '#7b849c' };
const SCHEDPG = {
  tabs: [{ k: 'pool', n: '任务池' }, { k: 'nodes', n: '周关键节点' }, { k: 'week', n: '下周计划' }, { k: 'duty', n: '值班表' }, { k: 'ticket', n: '审票' }, { k: 'prog', n: '现场进度' }, { k: 'meet', n: '班前班后会' }],
  ticketNo: null,
  pool() { return (typeof SUPER !== 'undefined' ? SUPER.transferBlock() : '') + this.pool0(); },
  pool0() { const jobs = DB.jobs(); const disp = LS.get('dispatch', {}); const recs = Object.values(disp).sort((a, b) => b.ts - a.ts); const tc = DB.typeCounts(); const m = DB.month(); const cnt = k => jobs.filter(j => k.test(j.st)).length;
    return '<div class="grid2" style="grid-template-columns:1.1fr 1fr"><div><div class="card"><div class="h"><b>任务池</b><span>' + jobs.length + ' 项 · 待派 ' + cnt(/待派/) + ' · 进行中 ' + cnt(/进行中/) + ' · 已完成 ' + cnt(/已完成|已关闭/) + '</span><div class="r"><button class="s" data-act="job-new">添加任务</button></div></div><div class="jobs" id="joblist">' + jobs.map(j => TASKS.row(j)).join('') + '</div></div>' +
      '<div class="card" style="margin-top:10px"><div class="h"><b>任务类型 · 本月</b><span>点一段看明细</span></div>' + CH.mini.donut(tc.map(([k, v], i) => ({ k, v, c: TYPE_C[k] || CPAL[i], act: 'ch-task', tip: k + ' ' + v + ' 项 · 点开看明细' })), { hero: String(m.jobs), sub: '本月 · 完成 ' + m.jobsDone }) + '</div></div>' +
      '<div><div id="jobhost"></div><div class="card" id="dcard"><div class="h"><b id="dtitle">派工</b><span id="dsub">点左边的「派工」，她按四条规则逐人对：证书 · 核心技能 · 工时 · 冲突</span></div><div class="ppl" id="ppl"><div class="row"></div><div class="tk"><span class="lbl">小瓦特在想</span><span></span></div><div class="xpl" id="xpl"></div></div><div id="dform"><div class="empty">她会先把人排在这里，给出每个人推荐或排除的理由，再填派工单</div></div></div>' +
      '<div class="card" style="margin-top:10px"><div class="h"><b>派工记录</b><span>' + recs.length + ' 单 · 点一单看理由</span></div>' + (recs.length ? '<div class="jobs">' + recs.map(r => '<div data-act="disp-rec" data-id="' + r.job + '" style="cursor:pointer"><span style="font-size:11.5px;color:var(--ink)">' + h(r.t) + '<br><span class="note">' + h(r.date) + ' · ' + h(r.lead) + ' / ' + h(r.crew.join('、')) + (r.learn ? ' · 随队 ' + h(r.learn) : '') + '</span></span><span class="tag ok">已发</span></div>').join('') + '</div>' : '<div class="empty">还没有派工记录</div>') + '</div>' +
      '<div class="card" style="margin-top:10px"><div class="h"><b>通知记录</b><span>她发出去的</span></div><div class="jobs">' + DB.notices().slice(0, 8).map(n => '<div><span style="font-size:11.5px;color:var(--ink)">' + h(n.t) + '<br><span class="note">' + h(n.d) + ' → ' + h(n.to) + '</span></span><span class="tag c">' + h(n.st) + '</span></div>').join('') + '</div></div></div></div>'; },
  nodes() { const done = DB.nodesDone(); const focus = LS.get('nodefocus', []); const nr = DB.nodeRate(); const cyc = {}; NODES.forEach(n => cyc[n.cyc] = (cyc[n.cyc] || 0) + 1);
    const row = n => { const wk = n.wk ? WK29.item(n.wk) : null; const r = wk ? WK29.rank(wk.k) : null; const isDone = done.includes(n.id); return '<tr class="' + (focus.includes(n.id) ? 'focus' : '') + (isDone ? ' done' : '') + '" data-act="node-open" data-id="' + n.id + '"><td><b>' + h(n.t) + '</b>' + (n.note ? '<br><span class="note">' + h(n.note.length > 40 ? n.note.slice(0, 40) + '…' : n.note) + '</span>' : '') + '</td>' + [0, 1, 2, 3, 4].map(d => '<td class="c">' + (n.days.includes(d) ? '<i class="dot' + (isDone ? ' ok' : '') + '"></i>' : '') + '</td>').join('') + '<td><span class="ab">A</span> ' + h(n.a) + '<br><span class="ab b">B</span> ' + h(n.b) + '</td><td><span class="tag ' + (/日日清|周周清|限时清/.test(n.cyc) ? 'w' : '') + '">' + h(n.cyc) + '</span></td><td class="note">' + (wk ? '<span class="' + (r >= 9 ? 'b' : '') + '">周报 · ' + h(wk.n.slice(0, 10)) + ' 第 ' + r + '</span>' : h(n.src)) + '</td><td>' + (isDone ? '<span class="tag ok">已清</span><button class="s g" data-act="node-undo" data-id="' + n.id + '">撤销</button>' : '<button class="s" data-act="node-done" data-id="' + n.id + '">本周已清</button>') + '</td></tr>'; };
    return '<div class="card"><div class="h"><b>周关键节点 · ' + NODE_DAYS[0].slice(3) + ' 至 ' + NODE_DAYS[4].slice(3) + '</b><span>' + NODES.length + ' 项固定工作 · A 主责 B 顶上 · 管控周期到了就要清 · 本周已清 ' + nr.done + '/' + nr.n + '</span><div class="r">' + (focus.length ? '<span class="tag v">周报提级 ' + focus.length + ' 项</span>' : '<button class="s" data-act="nodes-plan">按周报第 ' + WK29.no + ' 期提本周重点</button>') + '<button class="s g" data-act="node-check">周五核一遍</button></div></div>' +
      '<div class="tbl"><table class="t nodes"><tr><th>工作内容</th>' + NODE_DAYS.map(d => '<th class="c">' + h(d.slice(0, 2)) + '</th>').join('') + '<th>责任人</th><th>管控</th><th>出处</th><th>本周</th></tr>' + NODE_CATS.map(c => '<tr class="cat"><td colspan="10">' + c + '类 · ' + NODES.filter(n => n.cat === c).length + ' 项</td></tr>' + NODES.filter(n => n.cat === c).map(row).join('')).join('') + '</table></div></div>' +
      '<div class="grid3"><div class="card"><div class="h"><b>管控周期</b><span>项数</span></div>' + CH.mini.donut(Object.keys(cyc).map((k, i) => ({ k, v: cyc[k], c: CPAL[i % 6] })), { sub: '项' }) + '</div><div class="card"><div class="h"><b>A 责任分布</b><span>四位骨干各扛几项</span></div>' + CH.mini.bars(['韩雪', '黄伟强', '李文博', '吴倩'].map((n, i) => ({ n, v: NODES.filter(x => x.a === n).length, c: CPAL[i], act: 'person', who: n, tip: n + ' A 责任 ' + NODES.filter(x => x.a === n).length + ' 项 · B ' + NODES.filter(x => x.b === n).length + ' 项' })), { max: 8, unit: ' 项', h: 14 }) + '</div><div class="card"><div class="h"><b>本周闭环</b><span>周管控 / 日日清 / 周周清 / 限时清</span></div>' + CH.meters([{ k: 'nodes', n: '本周已清', v: nr.pct / 100, txt: nr.done + '/' + nr.n, tip: '按管控周期应清 ' + nr.n + ' 项，已清 ' + nr.done }]) + '<div class="note" style="margin-top:6px">周报第 ' + WK29.no + ' 期发布日是周五，下周一开始按这张表走；A 不在 B 顶上。</div></div></div>'; },
  week() { const JOBS_WEEK = DB.weekPlan(); const load = {}; JOBS_WEEK.forEach(j => j.who.forEach(w => { if (w === '全班') PEOPLE.forEach(p => load[p.n] = (load[p.n] || 0) + j.h); else load[w] = (load[w] || 0) + j.h * (j.d1 - j.d0 + 1); })); const bars = PEOPLE.filter(p => p.post !== '班长').map(p => ({ n: p.n, v: load[p.n] || 0, c: (load[p.n] || 0) > WEEK_LIMIT ? '#e5484d' : CPAL[0], act: 'wk-person', who: p.n, tip: p.n + ' 下周计划 ' + (load[p.n] || 0) + ' h · 点开看安排' }));
    return '<div class="card"><div class="h"><b>下周计划 · 8-10 至 8-16</b><span>' + JOBS_WEEK.length + ' 项 · 固定节点见「周关键节点」· 点一条她说安排</span><div class="r"><button class="s" data-act="wk-gen">生成下周计划文稿</button><button class="s g" data-act="wk-balance">看工作量是否均衡</button></div></div>' + CH.mini.gantt(JOBS_WEEK.map(j => ({ n: (j.added ? '＋ ' : '') + j.t, d0: j.d0, d1: j.d1, c: TYPE_C[j.type] || CPAL[5], act: 'wk-item', id: j.id, tip: j.t + ' · ' + j.who.join('、') + ' · ' + j.h + 'h/天' })), DAYS7.map(d => d.slice(0, 2)), { w: 680, L: 170, maxn: 16 }) + CH.mini.legend(Object.keys(TYPE_C).map(k => ({ n: k, c: TYPE_C[k] }))) + '</div>' +
      '<div class="grid2"><div class="card"><div class="h"><b>按天</b><span>点一天她汇总</span></div><div class="wkdays">' + DAYS7.map((d, i) => { const js = JOBS_WEEK.filter(j => j.d0 <= i && i <= j.d1); return '<div class="wkd" data-act="wk-day" data-i="' + i + '"><b>' + h(d) + '</b>' + js.map(j => '<span style="border-left:3px solid ' + TYPE_C[j.type] + '">' + h(j.t.length > 12 ? j.t.slice(0, 12) + '…' : j.t) + '</span>').join('') + (js.length ? '' : '<span class="note">无安排</span>') + '</div>'; }).join('') + '</div></div>' +
      '<div class="card"><div class="h"><b>下周工作量</b><span>约定 ' + WEEK_LIMIT + 'h · 点一条看安排</span></div>' + CH.mini.bars(bars, { limit: WEEK_LIMIT, unit: 'h', max: 30 }) + '</div></div>' +
      '<div class="grid2"><div class="card"><div class="h"><b>年度重点 · 进度</b><span>五项 · 与周报口径一致</span></div>' + CH.meters(PLAN_Y.map(p => ({ k: p.n, n: p.n, v: p.pct / 100, txt: p.pct + '%', tip: p.n + ' · 截止 ' + p.due }))) + '</div>' +
      '<div class="card"><div class="h"><b>本月八类任务 · 计划 / 完成</b><span>点一根柱她说差在哪</span><div class="r"><button class="s g" data-act="plan-next">生成下月计划</button></div></div>' + CH.mini.group(PLAN_M.map(p => p.k.slice(0, 4)), [{ n: '计划', vals: PLAN_M.map(p => p.plan), c: RAMP[2], act: 'plan-cat' }, { n: '完成', vals: PLAN_M.map(p => p.done), c: CPAL[0], act: 'plan-cat' }], { h: 140 }) + CH.mini.legend([{ n: '计划', c: RAMP[2] }, { n: '完成', c: CPAL[0] }]) + '<div class="doc" id="planhost" style="margin-top:6px"></div></div></div>'; },
  duty() { const nights = PEOPLE.filter(p => p.post !== '班长').map((p, i) => ({ n: p.n, v: [3, 4, 3, 2, 3, 2, 3, 2, 2, 1, 2][i] || 2, c: CPAL[5] })); return '<div class="card"><div class="h"><b>下周值班表 · 8-10 至 8-16</b><span>约束：有资质 · 每人每周不超三班 · 夜班不排本周已超 24h 的人 · 避开个人冲突 · 点一格换人</span></div><div id="dutyhost"></div></div><div class="grid2"><div class="card"><div class="h"><b>本月夜班次数</b><span>公平性参考</span></div>' + CH.mini.bars(nights, { unit: ' 次', max: 6, h: 13 }) + '</div><div class="card"><div class="h"><b>个人冲突登记</b><span>排班时避开</span></div><div class="jobs">' + Object.keys(DUTY_CONFLICT).map(n => '<div><span style="font-size:11.5px;color:var(--ink)">' + h(n) + '<br><span class="note">' + h(DUTY_CONFLICT[n].join('、')) + '</span></span><span class="tag w">避开</span></div>').join('') + '</div><div class="note" style="margin-top:8px">成员在群里报冲突，她自动记到这里；也可以在对话框里说"周三韩雪有培训"。</div></div></div>'; },
  ticket() { const TK = DB.tickets(); const cur = TK.find(t => t.no === this.ticketNo) || TK[0]; const tm = DB.ticketM(); return '<div class="grid2" style="grid-template-columns:1fr 2fr"><div><div class="card"><div class="h"><b>两票 · 待审与本周</b><span>' + TK.length + ' 张 · 待审 ' + TK.filter(t => t.st === '待审').length + '</span></div><div class="crs">' + TK.map(t => '<a data-act="tk-pick" data-no="' + h(t.no) + '" class="' + (t.no === cur.no ? 'on' : '') + '"><span style="font-size:12px;color:var(--ink)">' + h(t.task) + '<br><span class="note">' + h(t.kind) + ' · ' + h(t.no) + ' · ' + h(t.lead) + (t.uploaded ? ' · 上传' : t.drafted ? ' · 派工起草' : '') + '</span></span><span class="tag ' + (/已审核|已签发|已执行/.test(t.st) ? 'ok' : t.st === '已退回' ? 'bad' : 'w') + '">' + h(t.st) + '</span></a>').join('') + '</div></div>' +
      '<div class="card" style="margin-top:10px"><div class="h"><b>上传两票</b><span>Word · Excel · 文本 · 照片</span></div><label class="drop" id="tkdrop"><input type="file" id="tkfile" accept=".docx,.xlsx,.txt,.csv,.jpg,.jpeg,.png,.webp,.pdf" hidden><b>把操作票或工作票拖到这里</b><span>或点这里选文件 · 她读完票面逐条对规程</span></label><div class="note" id="tkupst" style="margin-top:6px"></div></div>' +
      '<div class="card" style="margin-top:10px"><div class="h"><b>两票 · 逐月</b><span>合格 / 开出</span></div>' + CH.mini.line([{ n: '开出', vals: tm.n, c: RAMP[2] }, { n: '合格', vals: tm.ok, c: CPAL[0] }], tm.m, { h: 120 }) + '</div></div><div class="card"><div class="h"><b>审票</b><span>票在左，规程在右，她的目光来回对</span></div><div id="tkhost"></div></div></div>'; },
  prog() { const g = DB.progressAll(); const hr = new Date().getHours(); const extra = g.filter(x => !PROGRESS.some(b => b.id === x.id)).map(x => ({ n: x.t.length > 10 ? x.t.slice(0, 10) + '…' : x.t, d0: Math.max(0, Math.min(8, (+x.start.slice(0, 2) || hr) - 9)), d1: Math.max(0, Math.min(8, (x.done ? +x.start.slice(0, 2) + 1 : hr) - 9)), c: CPAL[3], tip: x.t + ' · ' + x.start + ' 开工' })); return '<div class="grid2" style="grid-template-columns:1.2fr 1fr"><div class="card"><div class="h"><b>现场进度</b><span>成员回传的照片和一句话，她归成一条 · 点一组看回传</span></div><div class="prog">' + g.map(x => '<div data-act="prog-group" data-id="' + x.id + '" style="cursor:pointer"><span><b>' + h(x.t) + '</b> · ' + h(x.who) + '<br><span class="note">' + h(x.ev[x.ev.length - 1][0] + ' ' + x.ev[x.ev.length - 1][1] + '：' + x.ev[x.ev.length - 1][2]) + '</span></span><div class="pb"><i class="' + (x.warn ? 'w' : '') + '" style="width:' + x.pct + '%"></i></div><span class="note">' + x.pct + '% · ' + x.hrs + 'h</span></div>').join('') + '</div><div class="bt" id="progbt" style="margin-top:8px"><button data-act="prog-check">让她看一遍</button></div></div>' +
      '<div><div class="card"><div class="h"><b>今日时间轴</b><span>09:00 – 18:00</span></div>' + CH.mini.gantt([{ n: '晨操遥控验证', d0: 0, d1: 3, c: CPAL[0], tip: '09:00 开工，已 3.5h' }, { n: '交换机取电排查', d0: 5, d1: 7, c: CPAL[2], tip: '14:00 开工' }, { n: '华发民公用柜 现场确认', d0: 2, d1: 2, c: CPAL[1], tip: '韩雪路过时确认' }, { n: '安全日 · 交换机取电规范', d0: 6, d1: 6, c: CPAL[5], tip: '15:00' }, { n: '班后会', d0: 8, d1: 8, c: '#7b849c', tip: '17:40' }].concat(extra), ['9', '10', '11', '12', '13', '14', '15', '16', '17']) + '</div>' +
      '<div class="card" style="margin-top:10px"><div class="h"><b>回传记录</b><span id="evtitle">全部</span></div><div class="ev" id="evlist">' + g.reduce((a, x) => a.concat(x.ev.map(e => [x.t].concat(e))), []).map(e => '<div class="in">' + h(e[1]) + ' <b>' + h(e[2]) + '</b> ' + h(e[3]) + '<span>' + h(e[0]) + '</span></div>').join('') + '</div></div></div></div>'; },
  meet() { const m = MEETINGS[0]; const absent = ['林芷若']; return '<div class="grid2"><div class="card"><div class="h"><b>今日班前会 · 07:50</b><span>主持 ' + h(m.host) + ' · 到会 ' + m.n + ' 人</span></div><div class="ppl on" style="margin:0;border:0;padding:0"><div class="row">' + PEOPLE.map(p => '<div class="chip" style="width:auto;flex-direction:row;align-items:center;gap:6px;cursor:default"><b>' + h(p.n) + '</b><span class="tag ' + (absent.includes(p.n) ? '' : 'ok') + '" style="margin:0">' + (absent.includes(p.n) ? '休假' : '到会') + '</span></div>').join('') + '</div></div><div style="margin-top:8px;font-weight:600;font-size:12px">交底事项</div><ol style="margin:4px 0;padding-left:18px;font-size:12px">' + m.items.map(i => '<li>' + h(i) + '</li>').join('') + '</ol><div class="bt"><button class="g" data-act="meet-minutes" data-kind="班前会">生成班前会纪要</button><button data-act="meet-after">记录班后会</button></div><div class="doc" id="meethost" style="margin-top:8px"></div></div>' +
      '<div class="card"><div class="h"><b>会议记录</b><span>近 5 次 · 点一条她复述</span></div><div class="jobs">' + MEETINGS.map((x, i) => '<div data-act="meet-open" data-i="' + i + '" style="cursor:pointer"><span style="font-size:11.5px;color:var(--ink)">' + h(x.kind) + ' · ' + h(x.d) + '<br><span class="note">' + h(x.items.join('；')) + '</span></span><span class="tag">' + x.n + ' 人</span></div>').join('') + '</div><div style="margin-top:10px"><div class="note" style="margin-bottom:4px">到会人数 · 近 5 次</div>' + CH.mini.cols(MEETINGS.slice().reverse().map(x => ({ n: x.d.slice(5, 10), v: x.n, c: CPAL[4] })), { h: 100, max: 12, labels: true }) + '</div></div></div>'; },
  draw() { const host = $('#schedbody'); const s = S.sub || 'pool';
    if (s === 'duty') { host.innerHTML = this.duty(); DUTY.render($('#dutyhost')); }
    else if (s === 'ticket') { host.innerHTML = this.ticket(); const cur = DB.ticket(this.ticketNo) || DB.tickets()[0]; this.cur = cur; if (cur.uploaded) TICKETUP.render($('#tkhost'), cur); else TICKETREV.render($('#tkhost'), cur); TICKETUP.bind(); }
    else if (s === 'prog') host.innerHTML = this.prog();
    else if (s === 'week') host.innerHTML = this.week();
    else if (s === 'nodes') host.innerHTML = this.nodes();
    else if (s === 'meet') host.innerHTML = this.meet();
    else host.innerHTML = this.pool(); CH.mount(host); }
};
PAGES.sched = {
  render() { return cmdHTML(['加一个任务：光侨路 3# 公用柜 频繁投退消缺', '安排下周一田寮站 F02 的交接试验与验收', '排下周值班表', '审一下今天的工作票', '上传一张操作票', '下周谁的活最多']) + pageHead('用工安排', '任务池 · 周关键节点 · 下周计划 · 值班表 · 审票 · 现场进度 · 班前班后会') + tabsHTML(SCHEDPG.tabs, S.sub || 'pool') + '<div id="schedbody"></div>'; },
  after() { SCHEDPG.draw(); }
};
Object.assign(ACT, {
  'pool-dispatch'(el) { const job = DB.job(el.dataset.id); if (!job) return; TASKFORM.close(); DISPATCH.job = job; $('#dtitle').textContent = '派工 · ' + job.t; $('#dsub').textContent = job.when + (job.need && job.need.length ? ' · 要 ' + job.need.map(c => c.replace('作业证', '证')).join('、') : '') + (job.skill ? ' · 核心技能「' + SKILL9.find(s => s.k === job.skill).n + '」' : ''); $('#dform').innerHTML = '<div class="empty">点一个人，或直接「按她的安排」</div><div class="bt" style="justify-content:center"><button data-act="dispatch-go">按她的安排</button></div>'; const host = $('#ppl'); host.classList.remove('on'); $('.tk span:last-child', host).textContent = ''; const x = $('#xpl'); if (x) { x.innerHTML = ''; x.classList.remove('in'); } DISPATCH.open(host, job); },
  'disp-rec'(el) { const r = LS.get('dispatch', {})[el.dataset.id]; if (!r) return; const rs = (r.reasons || []); XW.answer(r.t + '：负责人 ' + r.lead + '，班员 ' + r.crew.join('、') + (r.follows && r.follows.length ? '，随队 ' + r.follows.join('、') : '') + '。' + (rs.length ? '推荐的理由：' + rs.filter(x => x.role === 'lead' || x.role === 'crew').map(x => x.n + '——' + x.why.slice(0, 2).join('，')).join('；') + '。排除了 ' + rs.filter(x => x.role === 'out' || x.role === 'over').length + ' 人，理由随单存着。' : ''), null, { confirm: false, done() { if (rs.length) XW.card('<div class="tbl"><table class="t xpl">' + rs.map(x => '<tr class="' + (x.role === 'lead' || x.role === 'crew' ? 'in' : x.role === 'follow' ? 'fo' : x.role === 'over' ? 'ov' : 'ex') + '"><td><b>' + h(x.n) + '</b></td><td><span class="tag ' + (x.role === 'lead' || x.role === 'crew' ? 'ok' : x.role === 'follow' ? 'v' : x.role === 'over' ? 'w' : 'bad') + '">' + ({ lead: '负责人', crew: '班员', follow: '随队', over: '排除 · 超工时', out: '排除' }[x.role]) + '</span></td><td class="note">' + h(x.why.join('；')) + '</td></tr>').join('') + '</table></div>'); } }); },
  /* 周关键节点 */
  'node-open'(el) { const n = NODES.find(x => x.id === el.dataset.id); if (!n) return; const wk = n.wk ? WK29.item(n.wk) : null; const r = wk ? WK29.rank(wk.k) : null; XW.answer('「' + n.t + '」' + n.cat + '类，' + n.cyc + '，' + NODE_DAYS.filter((d, i) => n.days.includes(i)).map(d => d.slice(0, 2)).join('、') + '做，A ' + n.a + '、B ' + n.b + '。' + (n.note ? '注意事项：' + n.note + '。' : '') + (wk ? '周报第 ' + WK29.no + ' 期对应「' + wk.n + '」，光明 ' + (typeof wk.vals[0] === 'number' ? wk.vals[WK29.gm()] + wk.unit : wk.vals[WK29.gm()]) + '，全市第 ' + r + '，' + wk.detail + '。' : '出处是' + n.src + '。'), null, { confirm: false, chart: wk && typeof wk.vals[0] === 'number' ? CH.mini.bars(WK29.bureaus.map((b, i) => ({ n: b, v: wk.vals[i], c: b === '光明' ? '#e5484d' : CPAL[0] })), { max: Math.max.apply(null, wk.vals) * 1.05, h: 10, x0: 40, unit: wk.unit }) : null }); },
  'node-done'(el) { const n = NODES.find(x => x.id === el.dataset.id); DB.nodeDone(n.id, n.a); XW.fly('已清 · ' + n.t + ' · ' + n.a); SCHEDPG.draw(); XW.answer('「' + n.t + '」记为本周已清，' + n.a + '经手。本周已清 ' + DB.nodeRate().done + '/' + DB.nodeRate().n + '。', null, { confirm: false, speak: false }); badgeSync(); },
  'node-undo'(el) { DB.nodeUndo(el.dataset.id); SCHEDPG.draw(); },
  'node-check'() { const nr = DB.nodeRate(); const left = NODES.filter(n => /周|限时|日日清/.test(n.cyc) && !DB.nodesDone().includes(n.id)); XW.think('按管控周期应清 ' + nr.n + ' 项，已清 ' + nr.done + '……没清的是' + left.slice(0, 5).map(n => n.t + '（A ' + n.a + '）').join('、') + (left.length > 5 ? '等 ' + left.length + ' 项' : '') + '。', () => { XW.answer(left.length ? '还有 ' + left.length + ' 项没清：' + left.map(n => n.t).join('、') + '。我把没清的按 A 责任人分组发提醒？' : '本周该清的都清了。', left.length ? '<div class="bt"><button data-act="node-remind">按责任人发提醒</button><button class="g" data-act="no" data-t="先不用">先不用</button></div>' : null, { confirm: false, chart: CH.mini.bars(['韩雪', '黄伟强', '李文博', '吴倩'].map((n, i) => ({ n, v: left.filter(x => x.a === n).length, c: CPAL[i], tip: n + ' 未清 ' + left.filter(x => x.a === n).length + ' 项' })), { max: 6, unit: ' 项', h: 13 }) }); }); },
  'node-remind'() { const left = NODES.filter(n => /周|限时|日日清/.test(n.cyc) && !DB.nodesDone().includes(n.id)); const by = {}; left.forEach(n => { (by[n.a] = by[n.a] || []).push(n.t); }); Object.keys(by).forEach(n => DB.notify(n, '本周未清关键节点：' + by[n].join('、'), '已发', true)); XW.fly('提醒已发 · ' + Object.keys(by).join(' · ')); XW.answer('发了，' + Object.keys(by).map(n => n + ' ' + by[n].length + ' 项').join('、') + '。', null, { confirm: false }); },
  'wk-item'(el) { const j = DB.weekPlan().find(x => x.id === el.dataset.id); const risk = /试验|验收/.test(j.t) ? '要停电，第一种工作票，试验前验电放电接地' : /排查|终端|柜/.test(j.t) ? '二次室作业，第二种工作票' : '常规'; XW.answer(j.t + '排在' + DAYS7[j.d0] + (j.d1 > j.d0 ? '到' + DAYS7[j.d1] : '') + '，' + j.who.join('、') + '，每天 ' + j.h + ' 小时。' + risk + '。', null, { confirm: false, chart: CH.mini.bars(j.who.filter(w => P[w]).map(w => ({ n: w, v: P[w].week, c: P[w].week >= WEEK_LIMIT ? '#e5484d' : CPAL[0], tip: w + ' 本周已 ' + P[w].week + 'h' })), { limit: WEEK_LIMIT, unit: 'h', max: 30 }), done() { XW.card('<div class="bt" style="margin-top:0"><button data-act="nav" data-to="sched" data-sub="pool">去派工</button><button class="g" data-act="wk-move" data-id="' + j.id + '">挪一天</button></div>'); } }); },
  'wk-move'(el) { const j = DB.weekPlan().find(x => x.id === el.dataset.id); XW.answer(j.t + '往后挪一天的话，' + DAYS7[Math.min(6, j.d1 + 1)] + '没有冲突，' + j.who[0] + '那天也空。要挪吗？', j.t + '往后挪一天的话，' + DAYS7[Math.min(6, j.d1 + 1)] + '没有冲突。要挪吗？<div class="bt"><button data-act="wk-move-ok" data-id="' + j.id + '">挪到' + DAYS7[Math.min(6, j.d1 + 1)].slice(0, 2) + '</button><button class="g" data-act="no" data-t="不挪">不挪</button></div>', { confirm: false }); },
  'wk-move-ok'(el) { const j = DB.weekPlan().find(x => x.id === el.dataset.id); j.d0 = Math.min(6, j.d0 + 1); j.d1 = Math.min(6, j.d1 + 1); DB.setWeek(j.id, { d0: j.d0, d1: j.d1 }); if (j.added) DB.updAdded(j.id, { dateIso: '2026-08-' + String(10 + j.d0).padStart(2, '0') }); DB.notify(j.who.filter(w => P[w]).join(' · ') || '全班', j.t + ' 挪到 ' + DAYS7[j.d0], '已发', true); SCHEDPG.draw(); XW.fly('周计划已更新 · ' + j.t + ' → ' + DAYS7[j.d0]); XW.answer('挪好了，相关的人我都通知了。', null, { confirm: false }); },
  'wk-day'(el) { const i = +el.dataset.i; const js = DB.weekPlan().filter(j => j.d0 <= i && i <= j.d1); const ns = i <= 4 ? NODES.filter(n => n.days.includes(i)) : []; const ppl = {}; js.forEach(j => j.who.forEach(w => { if (w === '全班') PEOPLE.forEach(p => ppl[p.n] = (ppl[p.n] || 0) + j.h); else ppl[w] = (ppl[w] || 0) + j.h; })); XW.answer(DAYS7[i] + '有 ' + js.length + ' 项作业：' + js.map(j => j.t).join('、') + '。' + (ns.length ? '固定节点 ' + ns.length + ' 项：' + ns.map(n => n.t).join('、') + '。' : '') + '出勤 ' + Object.keys(ppl).length + ' 人，' + (WEATHER7[i + 3] ? '天气' + WEATHER7[i + 3].w + ' ' + WEATHER7[i + 3].t + '℃' + (WEATHER7[i + 3].warn ? '，' + WEATHER7[i + 3].warn + '预警' : '') + '。' : ''), null, { confirm: false, chart: Object.keys(ppl).length ? CH.mini.bars(Object.keys(ppl).map(n => ({ n, v: ppl[n], c: CPAL[2], tip: n + ' ' + ppl[n] + 'h' })), { unit: 'h', max: 12, h: 13 }) : null }); },
  'wk-person'(el) { const w = el.dataset.who; const js = DB.weekPlan().filter(j => j.who.includes(w) || j.who.includes('全班')); const na = NODES.filter(n => n.a === w); XW.answer(w + '下周 ' + js.length + ' 项作业：' + js.map(j => DAYS7[j.d0].slice(0, 2) + j.t).join('、') + '。' + (na.length ? '另有关键节点 A 责任 ' + na.length + ' 项。' : '') + (P[w].week >= WEEK_LIMIT ? '他这周已经 ' + P[w].week + ' 小时，下周前两天我建议排室内。' : ''), null, { confirm: false, chart: CH.mini.gantt(js.map(j => ({ n: j.t, d0: j.d0, d1: j.d1, c: TYPE_C[j.type] })), DAYS7.map(d => d.slice(0, 2))) }); },
  'wk-balance'() { const load = {}; DB.weekPlan().forEach(j => j.who.forEach(w => { if (w !== '全班') load[w] = (load[w] || 0) + j.h * (j.d1 - j.d0 + 1); })); const top = Object.keys(load).sort((a, b) => load[b] - load[a]); XW.think('下周排下来，' + top.slice(0, 3).map(n => n + ' ' + load[n]).join('、') + '……' + top[0] + '最多，' + (load[top[0]] > WEEK_LIMIT ? '超过 24 小时了' : '没超') + '。最少的是' + top[top.length - 1] + ' ' + load[top[top.length - 1]] + '。' + (load[top[0]] > WEEK_LIMIT ? '把' + top[0] + '周三那项换给' + top[top.length - 1] + '，两边就都在约定内了。' : '总体是均衡的。'), () => { XW.answer(load[top[0]] > WEEK_LIMIT ? top[0] + '下周 ' + load[top[0]] + ' 小时超了约定，我建议把他周三的活换给' + top[top.length - 1] + '（' + load[top[top.length - 1]] + ' 小时）。要换吗？' : '下周工作量是均衡的，最多' + top[0] + ' ' + load[top[0]] + ' 小时，最少' + top[top.length - 1] + ' ' + load[top[top.length - 1]] + ' 小时，都在约定内。', load[top[0]] > WEEK_LIMIT ? '<div class="bt"><button data-act="wk-swap" data-a="' + top[0] + '" data-b="' + top[top.length - 1] + '">换</button><button class="g" data-act="no" data-t="不换">不换</button></div>' : null, { confirm: false, chart: CH.mini.bars(top.map(n => ({ n, v: load[n], c: load[n] > WEEK_LIMIT ? '#e5484d' : CPAL[0] })), { limit: WEEK_LIMIT, unit: 'h', max: 30, h: 13 }) }); }); },
  'wk-swap'(el) { const a = el.dataset.a, b = el.dataset.b; const W = DB.weekPlan(); const j = W.find(x => x.who.includes(a) && x.d0 <= 2 && x.d1 >= 2) || W.find(x => x.who.includes(a)); if (j) { j.who = j.who.map(w => w === a ? b : w); DB.setWeek(j.id, { who: j.who }); DB.notify(a + ' · ' + b, j.t + ' ' + a + ' 换 ' + b, '已发', true); } SCHEDPG.draw(); XW.fly('周计划已更新 · ' + (j ? j.t : '') + ' ' + a + ' → ' + b); XW.answer('换好了，' + a + '和' + b + '都收到通知。', null, { confirm: false }); },
  'wk-gen'() { if (DB.ext()) ensure('docs', () => DOCS.gen('weekplan')); else { const host = $('#planhost') || $('#schedbody'); DOCGEN.stream(host, DOCS.paras('weekplan'), { chips: [{ k: 'short', n: '口气再简短些' }], done() { XW.answer('下周计划写好了，固定节点按关键节点表，作业按下周计划。', null, { speak: false, confirm: false }); } }); DOCS.host = host; DOCS.kind = 'weekplan'; } },
  'plan-cat'(el) { const p = PLAN_M.find(x => x.k.startsWith(el.dataset.k)); if (!p) return; XW.answer('本月' + p.k + '计划 ' + p.plan + ' 项，完成 ' + p.done + ' 项' + (p.done < p.plan ? '，差 ' + (p.plan - p.done) + ' 项：' + (p.k === '终端投运' ? '存量 14 台，光侨路、东明大道两处等停电' : p.k === '缺陷消缺' ? '华发民公用柜电容故障、光侨路 3# 频繁投退' : p.k === '专项整改' ? '交换机取电排查剩 111 台' : p.k === '晨操遥控' ? '两单潮流不通过取消' : p.k === '培训考评' ? '光差保护补考，下周五' : '第二次安全日，今天下午') : '，全部完成') + '。', null, { confirm: false }); },
  'plan-next'() { const host = $('#planhost'); DOCGEN.stream(host, DOCS.paras('monthplan'), { chips: [{ k: 'short', n: '口气再简短些' }, { k: 'data', n: '补上人员安排' }], done() { XW.answer('下月计划写了一版，五节，数字都是从周报和台账取的。要改哪一节点那段下面的芯片。', null, { speak: false, confirm: false }); } }); DOCS.host = host; DOCS.kind = 'monthplan'; XW.type($('#xwsub'), '下月计划我按部里的格式写一版。', 45); },
  'duty-run'() { DUTY.run(); }, 'duty-save'() { DUTY.save(); const b = $('[data-act="duty-save"]'); if (b) b.disabled = true; }, 'duty-adjust'() { XW.answer('你点表上的任何一格，我给你换成合适的人。', null, { confirm: false }); },
  'duty-cell'(el) { const who = el.textContent.trim(); if (!who) return; const alt = PEOPLE.filter(p => p.post !== '班长' && p.n !== who && p.status !== '休假' && p.week < WEEK_LIMIT).sort((a, b) => a.week - b.week)[0]; XW.answer('这一格是' + who + '。要换的话我建议' + alt.n + '，他本周 ' + alt.week + ' 小时、这周只有一班，没有冲突。换吗？', '这一格是' + who + '。要换的话我建议' + alt.n + '，他本周 ' + alt.week + ' 小时、没有冲突。换吗？<div class="bt"><button data-act="duty-swap" data-cell="' + el.id + '" data-who="' + alt.n + '">换成' + alt.n + '</button><button class="g" data-act="no" data-t="不换">不换</button></div>', { confirm: false }); },
  'duty-swap'(el) { const c = $('#' + el.dataset.cell); if (c) { c.textContent = el.dataset.who; c.classList.add('fill'); c.classList.remove('conf'); } DUTY.last = null; XW.fly('值班表已更新 · ' + el.dataset.who); XW.answer('换好了，' + el.dataset.who + '收到通知。记得点「保存并发布」。', null, { confirm: false }); const b = $('[data-act="duty-save"]'); if (b) b.disabled = false; },
  'tk-pick'(el) { SCHEDPG.ticketNo = el.dataset.no; SCHEDPG.draw(); },
  'ticket-review'() { if (SCHEDPG.cur && SCHEDPG.cur.uploaded) TICKETUP.run(); else TICKETREV.run(); }, 'ticket-fix'() { TICKETREV.fix(); }, 'ticket-back'() { const t = TICKETREV.t || TICKET; DB.setTicket(t.no, '已退回'); DB.notify(t.lead, t.kind + ' ' + t.no + ' 退回修改：' + t.missing.map(m => m.why).join('；'), '已读', true); XW.fly('工作票已退回 ' + t.lead + ' · 附修改意见', 'w'); XW.answer('退回' + t.lead + '了，缺项我写在退回意见里，补完我再对一遍。这张票没审过，对应的任务开不了工。', null, { confirm: false }); SCHEDPG.draw(); },
  'prog-group'(el) { const g = DB.progressAll().find(x => x.id === el.dataset.id); $('#evtitle').textContent = g.t; $('#evlist').innerHTML = g.ev.map(e => '<div class="in">' + h(e[0]) + ' <b>' + h(e[1]) + '</b> ' + h(e[2]) + '</div>').join(''); XW.answer(g.t + '，' + g.who + '，' + g.start + '开工，现在 ' + g.pct + '%。最近一条是 ' + g.ev[g.ev.length - 1][0] + ' ' + g.ev[g.ev.length - 1][1] + '说"' + g.ev[g.ev.length - 1][2] + '"。' + (g.warn ? '已经连续 ' + g.hrs + ' 小时，我建议轮换。' : ''), null, { confirm: false }); },
  'prog-check'() { XW.think('晨操那组 09:00 开工，到现在 3 个半小时，8 单做了 6 单。陈浩是初级作业员，第一次连续跟这么久。按班组约定，连续作业超过三小时要轮换。谁能替？赵敏在岗，这周 8 小时，晨操遥控验证可自主实施，可以。', () => { XW.answer('晨操那组已经连续干了 3 个半小时，我建议让赵敏去换陈浩，剩下两单午饭后接着做。要我通知吗？', '晨操那组已经连续干了 3 个半小时，我建议让赵敏去换陈浩，午饭后再接着做。要我通知吗？<div class="bt"><button data-act="prog-rotate">通知轮换</button><button class="g" data-act="no" data-t="再等等">再等等</button></div>', { confirm: false, chart: CH.mini.bars(DB.progressAll().map(g => ({ n: g.t.slice(0, 6), v: g.hrs, c: g.warn ? '#e5484d' : CPAL[0], tip: g.t + ' 连续 ' + g.hrs + 'h' })), { limit: 3, unit: 'h', max: 5, x0: 60 }) }); }); },
  'prog-rotate'() { XW.fly('已通知 赵敏 · 11:00 接替陈浩'); XW.fly('已通知 韩雪 · 赵敏 11:00 到'); XW.answer('通知发了，赵敏 11 点接替，陈浩回班里吃饭。', null, { confirm: false }); },
  'meet-open'(el) { const m = MEETINGS[+el.dataset.i]; XW.answer(m.d + ' 的' + m.kind + '，' + m.host + '主持，到会 ' + m.n + ' 人，讲了 ' + m.items.length + ' 件事：' + m.items.join('；') + '。', null, { confirm: false }); },
  'meet-minutes'(el) { const host = $('#meethost'); const m = MEETINGS[0]; const rec = LS.get('dispatch', {})[MAINLINE]; DOCGEN.stream(host, ['班前会纪要 · ' + m.d + ' · 主持 ' + m.host + ' · 到会 ' + m.n + ' 人，林芷若休假。'].concat(m.items.map((it, i) => (i + 1) + '. ' + it + (i === 3 && rec ? '（负责人' + rec.lead + '，班员' + rec.crew.join('、') + '）' : ''))), { chips: [{ k: 'short', n: '口气再简短些' }], done() { XW.answer('纪要写好了，随票归档。', null, { speak: false, confirm: false }); } }); DOCS.host = host; DOCS.kind = 'minutes'; },
  'meet-after'() { const host = $('#meethost'); const ev = DB.progressAll().reduce((a, g) => a.concat(g.ev.map(e => g.t + '：' + e[2])), []); const lg = DB.logs().filter(l => /完工|开工|派工|两票|添加任务|关闭|关键节点|能力回写/.test(l.kind)).slice(0, 4).map(l => l.kind + ' ' + l.text); DOCGEN.stream(host, ['班后会纪要 · 2026-08-07 17:40 · 主持 赵立群'].concat(['1. 今日完成：晨操遥控验证 8 单；交换机取电排查玉律片区 4 台；固加厂旁 5# 公用柜消缺复查。', '2. 现场回传要点：[取一下今天的回传……] ' + ev.slice(-3).join('；') + '。' + (lg.length ? '今日经手：' + lg.join('；') + '。' : ''), '3. 周报第 ' + WK29.no + ' 期：新建终端投运率全市第 ' + WK29.rank('newrun') + '，下周终端投运、十五类异常信号、晨操三项提级。', '4. 下周一：田寮站 F02 交接试验与验收' + (rec => rec ? '，' + rec.lead + '带队' : '，待派')(LS.get('dispatch', {})[MAINLINE]) + '；华发民公用柜电容故障消缺。']), { chips: [{ k: 'short', n: '口气再简短些' }, { k: 'data', n: '补上明日派工' }], done() { XW.answer('班后会纪要我按今天的回传和派工写的，你补两句就能发。', null, { speak: false, confirm: false }); } }); DOCS.host = host; DOCS.kind = 'minutes'; XW.type($('#xwsub'), '班后会纪要我按今天的回传写。', 45); }
});
