/* ===== 班务日程：任务池派工、周计划甘特、月计划、值班表、审票（多票）、现场进度、班前班后会 ===== */
const TYPE_C = { 巡视: CPAL[0], 消缺: CPAL[1], 检查: CPAL[2], 检修: CPAL[3], 培训: CPAL[4], 值班: CPAL[5] };
const SCHEDPG = {
  tabs: [{ k: 'pool', n: '任务池' }, { k: 'week', n: '周计划' }, { k: 'duty', n: '值班表' }, { k: 'ticket', n: '审票' }, { k: 'prog', n: '现场进度' }, { k: 'meet', n: '班前班后会' }],
  ticketNo: null,
  pool() { const disp = LS.get('dispatch', {}); const recs = Object.values(disp).sort((a, b) => b.ts - a.ts);
    return '<div class="grid2" style="grid-template-columns:1.1fr 1fr"><div><div class="card"><div class="h"><b>任务池</b><span>' + JOBS.length + ' 项 · 待派 ' + JOBS.filter(j => j.st === '待派' && !disp[j.id]).length + '</span></div><div class="jobs">' + JOBS.map(j => { const d = disp[j.id]; return '<div><span style="color:var(--ink);font-size:11.5px">' + h(j.t) + '<br><span class="note">' + h(j.when) + (j.who ? ' · ' + j.who.join(' ') : d ? ' · ' + d.lead + ' ' + d.crew.join(' ') + ' · ' + d.learn + '（随队）' : '') + '</span></span>' + (d ? '<span class="tag ok">已派</span>' : j.st === '待派' ? '<div class="bt"><button class="s" data-act="pool-dispatch" data-id="' + j.id + '">派工</button></div>' : '<span class="tag ' + (j.lv === '超期' ? 'bad' : '') + '">' + h(j.st) + '</span>') + '</div>'; }).join('') + '</div></div>' +
      '<div class="card" style="margin-top:10px"><div class="h"><b>任务类型 · 本月</b><span>点一段看明细</span></div>' + CH.mini.donut([['巡视', 14], ['消缺', 9], ['检查', 9], ['检修', 6]].map(([k, v], i) => ({ k, v, c: CPAL[i], act: 'ch-task', tip: k + ' ' + v + ' 项 · 点开看明细' })), { hero: '38', sub: '本月' }) + '</div></div>' +
      '<div><div class="card" id="dcard"><div class="h"><b id="dtitle">派工</b><span id="dsub">点左边的「派工」</span></div><div class="ppl" id="ppl"><div class="row"></div><div class="tk"><span class="lbl">小瓦特在想</span><span></span></div></div><div id="dform"><div class="empty">她会先把人排在这里，再填派工单</div></div></div>' +
      '<div class="card" style="margin-top:10px"><div class="h"><b>派工记录</b><span>' + recs.length + ' 单</span></div>' + (recs.length ? '<div class="jobs">' + recs.map(r => '<div><span style="font-size:11.5px;color:var(--ink)">' + h(r.t) + '<br><span class="note">' + h(r.date) + ' · ' + h(r.lead) + ' / ' + h(r.crew.join('、')) + ' · 随队 ' + h(r.learn) + '</span></span><span class="tag ok">已发</span></div>').join('') + '</div>' : '<div class="empty">还没有派工记录</div>') + '</div>' +
      '<div class="card" style="margin-top:10px"><div class="h"><b>通知记录</b><span>她发出去的</span></div><div class="jobs">' + NOTICES.map(n => '<div><span style="font-size:11.5px;color:var(--ink)">' + h(n.t) + '<br><span class="note">' + h(n.d) + ' → ' + h(n.to) + '</span></span><span class="tag c">' + h(n.st) + '</span></div>').join('') + '</div></div></div></div>'; },
  week() { const load = {}; JOBS_WEEK.forEach(j => j.who.forEach(w => { if (w === '全班') PEOPLE.forEach(p => load[p.n] = (load[p.n] || 0) + j.h); else load[w] = (load[w] || 0) + j.h * (j.d1 - j.d0 + 1); })); const bars = PEOPLE.filter(p => p.post !== '班长').map(p => ({ n: p.n, v: load[p.n] || 0, c: (load[p.n] || 0) > WEEK_LIMIT ? '#e5484d' : CPAL[0], act: 'wk-person', who: p.n, tip: p.n + ' 下周计划 ' + (load[p.n] || 0) + ' h · 点开看安排' }));
    return '<div class="card"><div class="h"><b>下周计划 · 9-7 至 9-13</b><span>' + JOBS_WEEK.length + ' 项 · 点一条她说安排</span><div class="r"><button class="s" data-act="wk-gen">生成下周计划文稿</button><button class="s g" data-act="wk-balance">看工作量是否均衡</button></div></div>' + CH.mini.gantt(JOBS_WEEK.map(j => ({ n: j.t, d0: j.d0, d1: j.d1, c: TYPE_C[j.type], act: 'wk-item', id: j.id, tip: j.t + ' · ' + j.who.join('、') + ' · ' + j.h + 'h/天' })), DAYS7.map(d => d.slice(0, 2)), { w: 680, L: 170, maxn: 16 }) + CH.mini.legend(Object.keys(TYPE_C).map(k => ({ n: k, c: TYPE_C[k] }))) + '</div>' +
      '<div class="grid2"><div class="card"><div class="h"><b>按天</b><span>点一天她汇总</span></div><div class="wkdays">' + DAYS7.map((d, i) => { const js = JOBS_WEEK.filter(j => j.d0 <= i && i <= j.d1); return '<div class="wkd" data-act="wk-day" data-i="' + i + '"><b>' + h(d) + '</b>' + js.map(j => '<span style="border-left:3px solid ' + TYPE_C[j.type] + '">' + h(j.t.length > 12 ? j.t.slice(0, 12) + '…' : j.t) + '</span>').join('') + (js.length ? '' : '<span class="note">无安排</span>') + '</div>'; }).join('') + '</div></div>' +
      '<div class="card"><div class="h"><b>下周工作量</b><span>约定 ' + WEEK_LIMIT + 'h · 点一条看安排</span></div>' + CH.mini.bars(bars, { limit: WEEK_LIMIT, unit: 'h', max: 30 }) + '</div></div>' +
      '<div class="grid2"><div class="card"><div class="h"><b>年度重点 · 进度</b><span>五项</span></div>' + CH.meters(PLAN_Y.map(p => ({ k: p.n, n: p.n, v: p.pct / 100, txt: p.pct + '%', tip: p.n + ' · 截止 ' + p.due }))) + '</div>' +
      '<div class="card"><div class="h"><b>本月八类任务 · 计划 / 完成</b><span>点一根柱她说差在哪</span><div class="r"><button class="s g" data-act="plan-next">生成下月计划</button></div></div>' + CH.mini.group(PLAN_M.map(p => p.k.slice(0, 4)), [{ n: '计划', vals: PLAN_M.map(p => p.plan), c: RAMP[2], act: 'plan-cat' }, { n: '完成', vals: PLAN_M.map(p => p.done), c: CPAL[0], act: 'plan-cat' }], { h: 140 }) + CH.mini.legend([{ n: '计划', c: RAMP[2] }, { n: '完成', c: CPAL[0] }]) + '<div class="doc" id="planhost" style="margin-top:6px"></div></div></div>'; },
  duty() { const nights = PEOPLE.filter(p => p.post !== '班长').map((p, i) => ({ n: p.n, v: [3, 4, 3, 2, 3, 2, 3, 2, 2, 1, 2][i] || 2, c: CPAL[5] })); return '<div class="card"><div class="h"><b>下周值班表 · 9-7 至 9-13</b><span>约束：有资质 · 每人每周不超三班 · 夜班不排本周已超 24h 的人 · 避开个人冲突 · 点一格换人</span></div><div id="dutyhost"></div></div><div class="grid2"><div class="card"><div class="h"><b>本月夜班次数</b><span>公平性参考</span></div>' + CH.mini.bars(nights, { unit: ' 次', max: 6, h: 13 }) + '</div><div class="card"><div class="h"><b>个人冲突登记</b><span>排班时避开</span></div><div class="jobs">' + Object.keys(DUTY_CONFLICT).map(n => '<div><span style="font-size:11.5px;color:var(--ink)">' + h(n) + '<br><span class="note">' + h(DUTY_CONFLICT[n].join('、')) + '</span></span><span class="tag w">避开</span></div>').join('') + '</div><div class="note" style="margin-top:8px">成员在群里报冲突，她自动记到这里；也可以在对话框里说"周三韩雪有培训"。</div></div></div>'; },
  ticket() { const all = LS.get('tickets', {}); const cur = TICKETS.find(t => t.no === this.ticketNo) || TICKETS[0]; return '<div class="grid2" style="grid-template-columns:1fr 2fr"><div><div class="card"><div class="h"><b>待审工作票</b><span>' + TICKETS.length + ' 张</span></div><div class="crs">' + TICKETS.map(t => { const st = (all[t.no] || {}).st || (t.no === TICKET.no && LS.get('ticket') ? '已审核' : '待审'); return '<a data-act="tk-pick" data-no="' + h(t.no) + '" class="' + (t === cur ? 'on' : '') + '"><span style="font-size:12px;color:var(--ink)">' + h(t.task) + '<br><span class="note">' + h(t.kind) + ' · ' + h(t.no) + ' · ' + h(t.lead) + '</span></span><span class="tag ' + (st === '已审核' ? 'ok' : 'w') + '">' + h(st) + '</span></a>'; }).join('') + '</div></div><div class="card" style="margin-top:10px"><div class="h"><b>两票 · 逐月</b><span>合格 / 开出</span></div>' + CH.mini.line([{ n: '开出', vals: TICKET_M.n, c: RAMP[2] }, { n: '合格', vals: TICKET_M.ok, c: CPAL[0] }], TICKET_M.m, { h: 120 }) + '</div></div><div class="card"><div class="h"><b>审票</b><span>票在左，作业指导书在右，她的目光来回对</span></div><div id="tkhost"></div></div></div>'; },
  prog() { const g = PROGRESS; return '<div class="grid2" style="grid-template-columns:1.2fr 1fr"><div class="card"><div class="h"><b>现场进度</b><span>成员回传的照片和一句话，她归成一条 · 点一组看回传</span></div><div class="prog">' + g.map(x => '<div data-act="prog-group" data-id="' + x.id + '" style="cursor:pointer"><span><b>' + h(x.t) + '</b> · ' + h(x.who) + '<br><span class="note">' + h(x.ev[x.ev.length - 1][0] + ' ' + x.ev[x.ev.length - 1][1] + '：' + x.ev[x.ev.length - 1][2]) + '</span></span><div class="pb"><i class="' + (x.warn ? 'w' : '') + '" style="width:' + x.pct + '%"></i></div><span class="note">' + x.pct + '% · ' + x.hrs + 'h</span></div>').join('') + '</div><div class="bt" id="progbt" style="margin-top:8px"><button data-act="prog-check">让她看一遍</button></div></div>' +
      '<div><div class="card"><div class="h"><b>今日时间轴</b><span>09:00 – 18:00</span></div>' + CH.mini.gantt([{ n: '塘尾线巡视', d0: 0, d1: 3, c: CPAL[0], tip: '09:00 开工，已 3.5h，34℃' }, { n: '光明变出线柜检查', d0: 5, d1: 7, c: CPAL[2], tip: '14:00 开工' }, { n: '田寮线 #7 现场确认', d0: 2, d1: 2, c: CPAL[1], tip: '王安路过时确认' }, { n: '班后会', d0: 8, d1: 8, c: CPAL[5], tip: '17:40' }], ['9', '10', '11', '12', '13', '14', '15', '16', '17']) + '</div>' +
      '<div class="card" style="margin-top:10px"><div class="h"><b>回传记录</b><span id="evtitle">全部</span></div><div class="ev" id="evlist">' + g.reduce((a, x) => a.concat(x.ev.map(e => [x.t].concat(e))), []).map(e => '<div class="in">' + h(e[1]) + ' <b>' + h(e[2]) + '</b> ' + h(e[3]) + '<span>' + h(e[0]) + '</span></div>').join('') + '</div></div></div></div>'; },
  meet() { const m = MEETINGS[0]; const absent = ['林芷若']; return '<div class="grid2"><div class="card"><div class="h"><b>今日班前会 · 07:50</b><span>主持 ' + h(m.host) + ' · 到会 ' + m.n + ' 人</span></div><div class="ppl on" style="margin:0;border:0;padding:0"><div class="row">' + PEOPLE.map(p => '<div class="chip" style="width:auto;flex-direction:row;align-items:center;gap:6px;cursor:default"><b>' + h(p.n) + '</b><span class="tag ' + (absent.includes(p.n) ? '' : 'ok') + '" style="margin:0">' + (absent.includes(p.n) ? '休假' : '到会') + '</span></div>').join('') + '</div></div><div style="margin-top:8px;font-weight:600;font-size:12px">交底事项</div><ol style="margin:4px 0;padding-left:18px;font-size:12px">' + m.items.map(i => '<li>' + h(i) + '</li>').join('') + '</ol><div class="bt"><button class="g" data-act="meet-minutes" data-kind="班前会">生成班前会纪要</button><button data-act="meet-after">记录班后会</button></div><div class="doc" id="meethost" style="margin-top:8px"></div></div>' +
      '<div class="card"><div class="h"><b>会议记录</b><span>近 5 次 · 点一条她复述</span></div><div class="jobs">' + MEETINGS.map((x, i) => '<div data-act="meet-open" data-i="' + i + '" style="cursor:pointer"><span style="font-size:11.5px;color:var(--ink)">' + h(x.kind) + ' · ' + h(x.d) + '<br><span class="note">' + h(x.items.join('；')) + '</span></span><span class="tag">' + x.n + ' 人</span></div>').join('') + '</div><div style="margin-top:10px"><div class="note" style="margin-bottom:4px">到会人数 · 近 5 次</div>' + CH.mini.cols(MEETINGS.slice().reverse().map(x => ({ n: x.d.slice(5, 10), v: x.n, c: CPAL[4] })), { h: 100, max: 12, labels: true }) + '</div></div></div>'; },
  draw() { const host = $('#schedbody'); const s = S.sub || 'pool';
    if (s === 'duty') { host.innerHTML = this.duty(); DUTY.render($('#dutyhost')); }
    else if (s === 'ticket') { host.innerHTML = this.ticket(); TICKETREV.render($('#tkhost'), TICKETS.find(t => t.no === this.ticketNo) || TICKETS[0]); }
    else if (s === 'prog') host.innerHTML = this.prog();
    else if (s === 'week') host.innerHTML = this.week();
    else if (s === 'meet') host.innerHTML = this.meet();
    else host.innerHTML = this.pool(); CH.mount(host); }
};
PAGES.sched = {
  render() { return cmdHTML(['安排明天凤凰线换刀闸', '排下周值班表', '审一下明天的工作票', '塘尾线那组干了多久了', '下周谁的活最多']) + pageHead('班务日程', '任务池 · 周计划 · 值班表 · 审票 · 现场进度 · 班前班后会') + tabsHTML(SCHEDPG.tabs, S.sub || 'pool') + '<div id="schedbody"></div>'; },
  after() { SCHEDPG.draw(); }
};
Object.assign(ACT, {
  'pool-dispatch'(el) { const job = JOBS.find(j => j.id === el.dataset.id); DISPATCH.job = job; $('#dtitle').textContent = '派工 · ' + job.t; $('#dsub').textContent = job.when; $('#dform').innerHTML = '<div class="empty">点一个人，或直接「按她的安排」</div><div class="bt" style="justify-content:center"><button data-act="dispatch-go">按她的安排</button></div>'; const host = $('#ppl'); host.classList.remove('on'); $('.tk span:last-child', host).textContent = ''; DISPATCH.open(host, job); },
  'wk-item'(el) { const j = JOBS_WEEK.find(x => x.id === el.dataset.id); const risk = /登杆|绝缘子|拉线/.test(j.t) ? '要登杆，台风预警解除后才能上' : /试验/.test(j.t) ? '要停电，工作票已开' : '常规'; XW.answer(j.t + '排在' + DAYS7[j.d0] + (j.d1 > j.d0 ? '到' + DAYS7[j.d1] : '') + '，' + j.who.join('、') + '，每天 ' + j.h + ' 小时。' + risk + '。', null, { confirm: false, chart: CH.mini.bars(j.who.filter(w => P[w]).map(w => ({ n: w, v: P[w].week, c: P[w].week >= WEEK_LIMIT ? '#e5484d' : CPAL[0], tip: w + ' 本周已 ' + P[w].week + 'h' })), { limit: WEEK_LIMIT, unit: 'h', max: 30 }), done() { XW.card('<div class="bt" style="margin-top:0"><button data-act="nav" data-to="sched" data-sub="pool">去派工</button><button class="g" data-act="wk-move" data-id="' + j.id + '">挪一天</button></div>'); } }); },
  'wk-move'(el) { const j = JOBS_WEEK.find(x => x.id === el.dataset.id); XW.answer(j.t + '往后挪一天的话，' + DAYS7[Math.min(6, j.d1 + 1)] + '没有冲突，' + j.who[0] + '那天也空。要挪吗？', j.t + '往后挪一天的话，' + DAYS7[Math.min(6, j.d1 + 1)] + '没有冲突。要挪吗？<div class="bt"><button data-act="wk-move-ok" data-id="' + j.id + '">挪到' + DAYS7[Math.min(6, j.d1 + 1)].slice(0, 2) + '</button><button class="g">不挪</button></div>', { confirm: false }); },
  'wk-move-ok'(el) { const j = JOBS_WEEK.find(x => x.id === el.dataset.id); j.d0 = Math.min(6, j.d0 + 1); j.d1 = Math.min(6, j.d1 + 1); SCHEDPG.draw(); XW.fly('周计划已更新 · ' + j.t + ' → ' + DAYS7[j.d0]); XW.answer('挪好了，相关的人我都通知了。', null, { confirm: false }); },
  'wk-day'(el) { const i = +el.dataset.i; const js = JOBS_WEEK.filter(j => j.d0 <= i && i <= j.d1); const ppl = {}; js.forEach(j => j.who.forEach(w => { if (w === '全班') PEOPLE.forEach(p => ppl[p.n] = (ppl[p.n] || 0) + j.h); else ppl[w] = (ppl[w] || 0) + j.h; })); XW.answer(DAYS7[i] + '有 ' + js.length + ' 项：' + js.map(j => j.t).join('、') + '。出勤 ' + Object.keys(ppl).length + ' 人，' + (WEATHER7[i + 4] ? '天气' + WEATHER7[i + 4].w + ' ' + WEATHER7[i + 4].t + '℃' + (WEATHER7[i + 4].warn ? '，' + WEATHER7[i + 4].warn + '预警' : '') + '。' : ''), null, { confirm: false, chart: Object.keys(ppl).length ? CH.mini.bars(Object.keys(ppl).map(n => ({ n, v: ppl[n], c: CPAL[2], tip: n + ' ' + ppl[n] + 'h' })), { unit: 'h', max: 12, h: 13 }) : null }); },
  'wk-person'(el) { const w = el.dataset.who; const js = JOBS_WEEK.filter(j => j.who.includes(w) || j.who.includes('全班')); XW.answer(w + '下周 ' + js.length + ' 项：' + js.map(j => DAYS7[j.d0].slice(0, 2) + j.t).join('、') + '。' + (P[w].week >= WEEK_LIMIT ? '他这周已经 ' + P[w].week + ' 小时，下周前两天我建议排室内。' : ''), null, { confirm: false, chart: CH.mini.gantt(js.map(j => ({ n: j.t, d0: j.d0, d1: j.d1, c: TYPE_C[j.type] })), DAYS7.map(d => d.slice(0, 2))) }); },
  'wk-balance'() { const load = {}; JOBS_WEEK.forEach(j => j.who.forEach(w => { if (w !== '全班') load[w] = (load[w] || 0) + j.h * (j.d1 - j.d0 + 1); })); const top = Object.keys(load).sort((a, b) => load[b] - load[a]); XW.think('下周排下来，' + top.slice(0, 3).map(n => n + ' ' + load[n]).join('、') + '……' + top[0] + '最多，' + (load[top[0]] > WEEK_LIMIT ? '超过 24 小时了' : '没超') + '。最少的是' + top[top.length - 1] + ' ' + load[top[top.length - 1]] + '。' + (load[top[0]] > WEEK_LIMIT ? '把' + top[0] + '周三那项换给' + top[top.length - 1] + '，两边就都在约定内了。' : '总体是均衡的。'), () => { XW.answer(load[top[0]] > WEEK_LIMIT ? top[0] + '下周 ' + load[top[0]] + ' 小时超了约定，我建议把他周三的活换给' + top[top.length - 1] + '（' + load[top[top.length - 1]] + ' 小时）。要换吗？' : '下周工作量是均衡的，最多' + top[0] + ' ' + load[top[0]] + ' 小时，最少' + top[top.length - 1] + ' ' + load[top[top.length - 1]] + ' 小时，都在约定内。', load[top[0]] > WEEK_LIMIT ? '<div class="bt"><button data-act="wk-swap" data-a="' + top[0] + '" data-b="' + top[top.length - 1] + '">换</button><button class="g">不换</button></div>' : null, { confirm: false, chart: CH.mini.bars(top.map(n => ({ n, v: load[n], c: load[n] > WEEK_LIMIT ? '#e5484d' : CPAL[0] })), { limit: WEEK_LIMIT, unit: 'h', max: 30, h: 13 }) }); }); },
  'wk-swap'(el) { const a = el.dataset.a, b = el.dataset.b; const j = JOBS_WEEK.find(x => x.who.includes(a) && x.d0 <= 2 && x.d1 >= 2) || JOBS_WEEK.find(x => x.who.includes(a)); if (j) { j.who = j.who.map(w => w === a ? b : w); } SCHEDPG.draw(); XW.fly('周计划已更新 · ' + (j ? j.t : '') + ' ' + a + ' → ' + b); XW.answer('换好了，' + a + '和' + b + '都收到通知。', null, { confirm: false }); },
  'wk-gen'() { ensure('docs', () => DOCS.gen('weekplan')); },
  'plan-cat'(el) { const p = PLAN_M.find(x => x.k.startsWith(el.dataset.k)); if (!p) return; XW.answer('本月' + p.k + '计划 ' + p.plan + ' 项，完成 ' + p.done + ' 项' + (p.done < p.plan ? '，差 ' + (p.plan - p.done) + ' 项：' + (p.k === '线路巡视' ? '田寮线剩余段和凤凰线电缆段，台风后补' : p.k === '缺陷消缺' ? '志远站 F14 蓄电池，已催办' : p.k === '业扩配合' ? '塘家新装配合，等客户侧' : p.k === '培训考评' ? '光差保护补考，下周五' : '第二次安全日，周五') : '，全部完成') + '。', null, { confirm: false }); },
  'plan-next'() { const host = $('#planhost'); DOCGEN.stream(host, ['10 月工作计划（初稿）', '一、重点：台风季拉线与杆根专项巡视收尾（剩余凤凰线 #20 至 #40 杆）；配网自动化终端年度巡检第三批 [取一下终端台账……] 48 台；电缆振荡波试验 3 段。', '二、缺陷：志远站 F14 蓄电池更换验收；塘家公用柜锁具；凤凰线 #15 树障复查。', '三、培训：继保专才《配网保护整定实用化》全员；实操：开关柜局放检测考核（吴倩、郭子扬）。', '四、安全：安全日 2 次（10-9 汛后配电房检查、10-23 登杆作业专题）；两票合格率保持 100%。', '五、人员：黄伟强、赵敏证书复审；王安、陈浩、周明学时补课。'], { chips: [{ k: 'short', n: '口气再简短些' }, { k: 'data', n: '补上人员安排' }], done() { XW.answer('下月计划写了一版，五节，数字都是从台账取的。要改哪一节点那段下面的芯片。', null, { speak: false, confirm: false }); } }); DOCS.host = host; DOCS.kind = 'monthplan'; XW.type($('#xwsub'), '下月计划我按所里的格式写一版。', 45); },
  'duty-run'() { DUTY.run(); }, 'duty-save'() { DUTY.save(); const b = $('[data-act="duty-save"]'); if (b) b.disabled = true; }, 'duty-adjust'() { XW.answer('你点表上的任何一格，我给你换成合适的人。', null, { confirm: false }); },
  'duty-cell'(el) { const who = el.textContent.trim(); if (!who) return; const alt = PEOPLE.filter(p => p.post !== '班长' && p.n !== who && p.status !== '休假' && p.week < WEEK_LIMIT).sort((a, b) => a.week - b.week)[0]; XW.answer('这一格是' + who + '。要换的话我建议' + alt.n + '，他本周 ' + alt.week + ' 小时、这周只有一班，没有冲突。换吗？', '这一格是' + who + '。要换的话我建议' + alt.n + '，他本周 ' + alt.week + ' 小时、没有冲突。换吗？<div class="bt"><button data-act="duty-swap" data-cell="' + el.id + '" data-who="' + alt.n + '">换成' + alt.n + '</button><button class="g">不换</button></div>', { confirm: false }); },
  'duty-swap'(el) { const c = $('#' + el.dataset.cell); if (c) { c.textContent = el.dataset.who; c.classList.add('fill'); c.classList.remove('conf'); } DUTY.last = null; XW.fly('值班表已更新 · ' + el.dataset.who); XW.answer('换好了，' + el.dataset.who + '收到通知。记得点「保存并发布」。', null, { confirm: false }); const b = $('[data-act="duty-save"]'); if (b) b.disabled = false; },
  'tk-pick'(el) { SCHEDPG.ticketNo = el.dataset.no; SCHEDPG.draw(); },
  'ticket-review'() { TICKETREV.run(); }, 'ticket-fix'() { TICKETREV.fix(); }, 'ticket-back'() { const t = TICKETREV.t || TICKET; XW.fly('工作票已退回 ' + t.lead + ' · 附修改意见', 'w'); XW.answer('退回' + t.lead + '了，缺项我写在票的备注里，补完我再对一遍。', null, { confirm: false }); },
  'prog-group'(el) { const g = PROGRESS.find(x => x.id === el.dataset.id); $('#evtitle').textContent = g.t; $('#evlist').innerHTML = g.ev.map(e => '<div class="in">' + h(e[0]) + ' <b>' + h(e[1]) + '</b> ' + h(e[2]) + '</div>').join(''); XW.answer(g.t + '，' + g.who + '，' + g.start + '开工，现在 ' + g.pct + '%。最近一条是 ' + g.ev[g.ev.length - 1][0] + ' ' + g.ev[g.ev.length - 1][1] + '说"' + g.ev[g.ev.length - 1][2] + '"。' + (g.warn ? '已经连续 ' + g.hrs + ' 小时，我建议轮换。' : ''), null, { confirm: false }); },
  'prog-check'() { XW.think('塘尾线那组 09:00 开工，到现在 3 个半小时，气温 34 度，台风来之前又闷。三个人里刘一鸣是学员，第一次这么长时间。按班组约定，高温连续作业超过三小时要轮换。谁能替？赵敏在岗，这周 8 小时，有登高证，可以。', () => { XW.answer('塘尾线那组已经连续干了 3 个半小时，34 度，我建议让赵敏去换刘一鸣，午饭后再接着巡。要我通知吗？', '塘尾线那组已经连续干了 3 个半小时，34 度，我建议让赵敏去换刘一鸣，午饭后再接着巡。要我通知吗？<div class="bt"><button data-act="prog-rotate">通知轮换</button><button class="g">再等等</button></div>', { confirm: false, chart: CH.mini.bars(PROGRESS.map(g => ({ n: g.t.slice(0, 6), v: g.hrs, c: g.warn ? '#e5484d' : CPAL[0], tip: g.t + ' 连续 ' + g.hrs + 'h' })), { limit: 3, unit: 'h', max: 5, x0: 60 }) }); }); },
  'prog-rotate'() { XW.fly('已通知 赵敏 · 11:00 到塘尾线 #30 杆接替刘一鸣'); XW.fly('已通知 吴倩 · 赵敏 11:00 到'); XW.answer('通知发了，赵敏 11 点到 #30 杆，刘一鸣回所里吃饭。', null, { confirm: false }); },
  'meet-open'(el) { const m = MEETINGS[+el.dataset.i]; XW.answer(m.d + ' 的' + m.kind + '，' + m.host + '主持，到会 ' + m.n + ' 人，讲了 ' + m.items.length + ' 件事：' + m.items.join('；') + '。', null, { confirm: false }); },
  'meet-minutes'(el) { const host = $('#meethost'); const m = MEETINGS[0]; DOCGEN.stream(host, ['班前会纪要 · ' + m.d + ' · 主持 ' + m.host + ' · 到会 ' + m.n + ' 人，林芷若休假。'].concat(m.items.map((it, i) => (i + 1) + '. ' + it + (i === 1 ? '（负责人韩雪，班员' + ((LS.get('dispatch', {})['j5'] || {}).crew || ['郭子扬', '赵敏']).join('、') + '）' : ''))), { chips: [{ k: 'short', n: '口气再简短些' }], done() { XW.answer('纪要写好了，随票归档。', null, { speak: false, confirm: false }); } }); DOCS.host = host; DOCS.kind = 'minutes'; },
  'meet-after'() { const host = $('#meethost'); const ev = PROGRESS.reduce((a, g) => a.concat(g.ev.map(e => g.t + '：' + e[2])), []); DOCGEN.stream(host, ['班后会纪要 · 2026-09-03 17:40 · 主持 赵立群'].concat(['1. 今日完成：塘尾线巡视 #1 至 #30 杆；志远站 F14 复查；光明变出线柜检查。', '2. 现场回传要点：[取一下今天的回传……] ' + ev.slice(0, 3).join('；') + '。', '3. 新发现：田寮线 #7 杆拉线锈断（紧急，已登记）；塘尾线 #31 杆鸟巢（一般）。', '4. 明日：凤凰线换刀闸，台风黄色预警，登杆看风停；志远站 F14 吴倩处理。']), { chips: [{ k: 'short', n: '口气再简短些' }, { k: 'data', n: '补上明日派工' }], done() { XW.answer('班后会纪要我按今天的回传和派工写的，你补两句就能发。', null, { speak: false, confirm: false }); } }); DOCS.host = host; DOCS.kind = 'minutes'; XW.type($('#xwsub'), '班后会纪要我按今天的回传写。', 45); }
});
