/* ===== 班务日程：任务池派工、值班表、审票、现场进度 ===== */
const SCHEDPG = {
  tabs: [{ k: 'pool', n: '任务池' }, { k: 'duty', n: '值班表' }, { k: 'ticket', n: '审票' }, { k: 'prog', n: '现场进度' }],
  pool() { const disp = LS.get('dispatch', {}); return '<div class="grid2" style="grid-template-columns:1.1fr 1fr"><div class="card"><div class="h"><b>任务池</b><span>' + JOBS.length + ' 项 · 待派 ' + JOBS.filter(j => j.st === '待派' && !disp[j.id]).length + '</span></div><div class="jobs">' + JOBS.map(j => { const d = disp[j.id]; return '<div><span style="color:var(--ink);font-size:11.5px">' + h(j.t) + '<br><span class="note">' + h(j.when) + (j.who ? ' · ' + j.who.join(' ') : d ? ' · ' + d.lead + ' ' + d.crew.join(' ') + ' · ' + d.learn + '（随队）' : '') + '</span></span>' + (d ? '<span class="tag ok">已派</span>' : j.st === '待派' ? '<div class="bt"><button class="s" data-act="pool-dispatch" data-id="' + j.id + '">派工</button></div>' : '<span class="tag ' + (j.lv === '超期' ? 'bad' : '') + '">' + h(j.st) + '</span>') + '</div>'; }).join('') + '</div></div>' +
    '<div class="card" id="dcard"><div class="h"><b id="dtitle">派工</b><span id="dsub">点左边的「派工」</span></div><div class="ppl" id="ppl"><div class="row"></div><div class="tk"><span class="lbl">小瓦特在想</span><span></span></div></div><div id="dform"><div class="empty">她会先把人排在这里，再填派工单</div></div></div></div>'; },
  prog() { const groups = [{ t: '塘尾线巡视', who: '吴倩 · 王安 · 刘一鸣', pct: 70, hrs: 3.5, warn: true, last: '10:12 王安：#22 杆到 #30 杆巡完，无异常' }, { t: '光明变 10kV 出线柜检查', who: '陈浩 · 周明', pct: 0, hrs: 0, last: '14:00 开工' }, { t: '志远站 F14 消缺复查', who: '王安 · 陈浩', pct: 100, hrs: 4, last: '昨 16:40 完成，待吴倩处理蓄电池' }]; return '<div class="card"><div class="h"><b>现场进度</b><span>成员回传的照片和一句话，她归成一条</span></div><div class="prog">' + groups.map((g, i) => '<div><span><b>' + h(g.t) + '</b> · ' + h(g.who) + '<br><span class="note">' + h(g.last) + '</span></span><div class="pb"><i class="' + (g.warn ? 'w' : '') + '" style="width:' + g.pct + '%"></i></div><span class="note">' + g.pct + '% · ' + g.hrs + 'h</span></div>').join('') + '</div><div class="bt" id="progbt" style="margin-top:8px"><button data-act="prog-check">让她看一遍</button></div></div>'; },
  draw() { const host = $('#schedbody'); if (S.sub === 'duty') { host.innerHTML = '<div class="card"><div class="h"><b>下周值班表 · 9-7 至 9-13</b><span>约束：有资质 · 每人每周不超三班 · 夜班不排本周已超 24h 的人 · 避开个人冲突</span></div><div id="dutyhost"></div></div>'; DUTY.render($('#dutyhost')); }
    else if (S.sub === 'ticket') { host.innerHTML = '<div class="card"><div class="h"><b>待审工作票</b><span>票在左，作业指导书在右，她的目光来回对</span></div><div id="tkhost"></div></div>'; TICKETREV.render($('#tkhost')); const t = LS.get('ticket'); if (t) { $('#tm1').textContent = '2. 装设接地线三组（#11、#13 档）'; $('#tmiss').innerHTML = '<div class="it" style="background:var(--okbg)">5. 验电：作业前在 #11、#13 档验明无电</div>'; $('#tkbt').innerHTML = '<span class="tag ok">已审核 · ' + h(t.no) + '</span>'; } }
    else if (S.sub === 'prog') host.innerHTML = this.prog();
    else host.innerHTML = this.pool(); }
};
PAGES.sched = {
  render() { return cmdHTML(['安排明天凤凰线换刀闸', '排下周值班表', '审一下明天的工作票', '塘尾线那组干了多久了']) + pageHead('班务日程', '任务池 · 值班表 · 审票 · 现场进度') + tabsHTML(SCHEDPG.tabs, S.sub || 'pool') + '<div id="schedbody"></div>'; },
  after() { SCHEDPG.draw(); }
};
Object.assign(ACT, {
  'pool-dispatch'(el) { const job = JOBS.find(j => j.id === el.dataset.id); DISPATCH.job = job; $('#dtitle').textContent = '派工 · ' + job.t; $('#dsub').textContent = job.when; $('#dform').innerHTML = '<div class="empty">点一个人，或直接「按她的安排」</div><div class="bt" style="justify-content:center"><button data-act="dispatch-go">按她的安排</button></div>'; const host = $('#ppl'); host.classList.remove('on'); $('.tk span:last-child', host).textContent = ''; DISPATCH.open(host, job); },
  'duty-run'() { DUTY.run(); }, 'duty-save'() { DUTY.save(); $('[data-act="duty-save"]').disabled = true; }, 'duty-adjust'() { XW.answer('你点表上的任何一格，我给你换成合适的人。', null, { confirm: false }); },
  'ticket-review'() { TICKETREV.run(); }, 'ticket-fix'() { TICKETREV.fix(); $('#tkbt').innerHTML = '<span class="tag ok">已审核 · ' + h(TICKET.no) + '</span>'; }, 'ticket-back'() { XW.fly('工作票已退回 韩雪 · 附两处修改意见', 'w'); XW.answer('退回韩雪了，两处缺项我写在票的备注里，她补完我再对一遍。', null, { confirm: false }); },
  'prog-check'() { XW.think('塘尾线那组 09:00 开工，到现在 3 个半小时，气温 34 度，台风来之前又闷。三个人里刘一鸣是学员，第一次这么长时间。按班组约定，高温连续作业超过三小时要轮换。谁能替？赵敏在岗，这周 8 小时，有登高证，可以。', () => { XW.answer('塘尾线那组已经连续干了 3 个半小时，34 度，我建议让赵敏去换刘一鸣，午饭后再接着巡。要我通知吗？', '塘尾线那组已经连续干了 3 个半小时，34 度，我建议让赵敏去换刘一鸣，午饭后再接着巡。要我通知吗？<div class="bt"><button data-act="prog-rotate">通知轮换</button><button class="g">再等等</button></div>', { confirm: false }); }); },
  'prog-rotate'() { XW.fly('已通知 赵敏 · 11:00 到塘尾线 #30 杆接替刘一鸣'); XW.fly('已通知 吴倩 · 赵敏 11:00 到'); XW.answer('通知发了，赵敏 11 点到 #30 杆，刘一鸣回所里吃饭。', null, { confirm: false }); }
});
