/* ===== 管理者视角（配网管理部 · 管辖三个班组）：部门态势 · 全流程俯瞰 · 风险与统筹（跨班组调配 · 柔性团队）· 班长履职 · 人才梯队 · 星级对标 · 组织效能 · 参谋输出 · 配置与权限。全部只读班组长那边的同一套 DB；涉及人的动作都落到"班组长确认" ===== */
const SUPER = {
  wk: 'online', simState: null, starProf: 'auto',
  OM_PEOPLE: ['陈志远', '周涛', '林小江', '梁伟', '许静', '罗文', '黄嘉', '钟晓', '邓海', '曾琪', '朱宁'],
  /* ---------- 三个班组的五类指标：配电自动化班全量计算，试验班按名册与试验记录，配电运维一班轻量 ---------- */
  labAges() { return LAB.people.map(p => p.age); },
  labCertAvg() { const l = LAB.people.filter(p => p.cert.includes('电力电缆作业证')); return l.length ? +(l.reduce((s, p) => s + p.age, 0) / l.length).toFixed(1) : 0; },
  labFive() { const ps = LAB.people; const size = LAB.size; const out = LAB.borrowed.length; const young = ps.filter(p => p.age <= 30).length; const bk = ps.filter(p => /班长|高级/.test(p.post)); const cable = ps.filter(p => p.cert.includes('电力电缆作业证')).length; const post = ps.filter(p => p.cert.includes('岗位胜任能力证')).length; const wk = Object.keys(LAB.week).filter(n => n !== LAB.leader); const over = wk.filter(n => LAB.week[n] > WEEK_LIMIT).length; const diff = Math.max.apply(null, wk.map(n => LAB.week[n])) - Math.min.apply(null, wk.map(n => LAB.week[n]));
    return { struct: [{ n: '缺编率', val: Math.round(out / size * 100) + '%', th: '≤10%（星级班组必备条件）', d: '刘畅借在配电运维一班未归' }, { n: '30 岁以下占比', val: Math.round(young / size * 100) + '%', th: '≥30%' }, { n: '骨干层平均年龄', val: ageAvg(bk) + ' 岁', th: '<38 岁；≥38 岁提示补位' }],
      cert: [{ n: '岗位胜任能力证覆盖', val: post + '/' + (size - 1), th: '在岗人员（新员工除外）100%' }, { n: '90 天内到期', val: TEAM_CERTS['试验班'] + ' 人', th: '到期前 30 天完成复审报名' }, { n: '作业下限缺口', val: (cable < 4 ? 1 : 0) + ' 类', th: '0 类', d: '电力电缆作业证 ' + cable + '/4' }],
      skill: [{ n: '核心试验项目可自主', val: LAB.items.length + '/' + LAB.items.length + ' 类', th: '每类 ≥3 人可自主实施' }, { n: '人均试验实操量', val: Math.round(LAB.total / size) + ' 次', th: '具备资格者不低于人均 30%', d: '2025 年 1–8 月交接试验 ' + LAB.total + ' 条' }, { n: '图谱最弱模块', val: '数字化应用 L2.7', th: '均值 ≥ L3' }],
      load: [{ n: '本周超约定人数', val: over + ' 人', th: '0 人（每周 ≤24h）', d: wk.filter(n => LAB.week[n] > WEEK_LIMIT).map(n => n + ' ' + LAB.week[n] + 'h').join('、') }, { n: '最高与最低工时差', val: diff + ' 小时', th: '≤12 小时' }, { n: '借出未归', val: out + ' 人', th: '0 人' }],
      grow: [{ n: '培养计划在办', val: '3 项', th: '每人至少 1 项' }, { n: '近三年人才输出', val: '1 人', th: '每年 ≥1 人', d: '罗海 2024-11 由配电自动化班输入任副班长' }, { n: '新员工培养周期', val: '16 个月', th: '≤18 个月取得岗位胜任能力证' }] }; },
  OM_FIVE: { struct: [{ n: '缺编率', val: '0%', th: '≤10%' }, { n: '30 岁以下占比', val: '27%', th: '≥30%' }, { n: '骨干层平均年龄', val: '36.5 岁', th: '<38 岁' }], cert: [{ n: '岗位胜任能力证覆盖', val: '10/10', th: '100%' }, { n: '90 天内到期', val: '2 人', th: '到期前 30 天报名' }, { n: '作业下限缺口', val: '0 类', th: '0 类' }], skill: [{ n: '核心技能可自主实施覆盖', val: '6/9 类', th: '每类 ≥3 人' }, { n: '人均核心技能实操量', val: '22 次', th: '不低于人均 30%' }, { n: '图谱最弱模块', val: '数字化应用 L2.4', th: '≥ L3' }], load: [{ n: '本周超约定人数', val: '0 人', th: '0 人' }, { n: '最高与最低工时差', val: '9 小时', th: '≤12 小时' }, { n: '连续作业超 3 小时', val: '0 组', th: '0 组' }], grow: [{ n: '培养计划在办', val: '4 项', th: '每人 ≥1 项' }, { n: '近三年人才输出', val: '2 人', th: '每年 ≥1 人' }, { n: '新员工培养周期', val: '13 个月', th: '≤18 个月' }] },
  judge(k, items) { const v = i => parseFloat(String(items[i].val).replace(/[^\d.]/g, '')) || 0;
    if (k === 'struct') return v(0) > 10 ? 'bad' : v(1) < 30 || v(2) >= 38 ? 'warn' : 'ok';
    if (k === 'cert') return v(2) > 0 ? (v(1) >= 2 ? 'bad' : 'warn') : v(1) >= 3 ? 'warn' : 'ok';
    if (k === 'skill') { const a = String(items[0].val).split('/')[0]; return +a < 4 ? 'bad' : +a < 7 ? 'warn' : 'ok'; }
    if (k === 'load') return v(0) >= 2 || (v(0) >= 1 && v(1) > 12) ? 'bad' : v(0) >= 1 || v(1) > 12 ? 'warn' : 'ok';
    return v(0) >= 1 && v(1) >= 1 ? 'ok' : 'warn'; },
  five(n) { let src; if (n === TEAM.name) { const F = fiveOf(); src = {}; F.forEach(f => { src[f.k] = f.items.map(it => ({ n: it.n, val: it.val, th: it.th, d: it.use, who: it.who })); }); } else if (n === LAB.name) src = this.labFive(); else src = this.OM_FIVE;
    return FIVE.map(f => ({ k: f.k, n: f.n, d: f.d, items: src[f.k], st: this.judge(f.k, src[f.k]) })); },
  teams() { return TEAMS.map(t => Object.assign({}, t, { five: this.five(t.n) })); },
  stName(st) { return st === 'ok' ? '稳健' : st === 'warn' ? '关注' : '待治理'; },
  /* ---------- 本周关注（跨班组自动汇总） ---------- */
  risks() { const R = []; const d5 = DB.defect('d5'); const undone = NODES.filter(n => /周周清|限时清/.test(n.cyc) && !DB.nodesDone().includes(n.id)); const over = PEOPLE.filter(p => p.week > WEEK_LIMIT); const lw = Object.keys(LAB.week).filter(n => LAB.week[n] > WEEK_LIMIT); const worst = WK29.items.filter(i => WK29.rank(i.k) >= 9);
    if (d5 && !/已关闭|已验证|待验收/.test(d5.st)) R.push({ lv: '高', team: TEAM.name, t: '应用失败缺陷超期：华发民公用柜 电容故障', d: '8-2 登记，重大缺陷 72 小时时限，现在「' + d5.st + '」；周报口径光明累计未消缺 17 单', fix: '督办班组长今日闭环；超 72 小时的单子每天 9 点提示', who: '赵立群', act: 'sup-urge', arg: 'd5', bt: '发督办' });
    if (over.length) R.push({ lv: '中', team: TEAM.name, t: '工作量集中：' + over.map(p => p.n + ' ' + p.week + 'h').join('、'), d: '超过班组约定 ' + WEEK_LIMIT + 'h，连续三周最高', fix: '下周计划均衡，永磁终端排查分给李文博；派工校验自动避开', who: '赵立群', act: 'sup-notify', arg: '工作量均衡：' + over.map(p => p.n).join('、') + '本周超约定，下周计划请均衡', bt: '发提醒' });
    if (lw.length) R.push({ lv: '中', team: LAB.name, t: '工作量集中：' + lw.map(n => n + ' ' + LAB.week[n] + 'h').join('、'), d: '刘畅借在配电运维一班未归，8 月交接试验 60 条集中在张伟', fix: '刘畅 8-15 归队；8 月交接试验高峰按周排', who: LAB.leader, act: 'sup-notify', arg: '试验班工作量：张伟本周 28h，请安排轮换', bt: '发提醒' });
    certAge().filter(c => c.risk === '高').forEach(c => R.push({ lv: '高', team: TEAM.name, t: '资质断层：' + c.k + ' 持证 ' + c.hold.length + '/' + c.need + '，平均 ' + c.avg + ' 岁', d: '35 岁以下 ' + c.young + ' 人', fix: '按缺口排取证（10 月批次）；高峰期跨班组借人过渡', who: '赵立群 · 管理者', act: 'nav', to: 'talent', sub: 'cert', bt: '看梯队' }));
    R.push({ lv: '高', team: LAB.name, t: '资质断层：电力电缆作业证 持证 ' + LAB.people.filter(p => p.cert.includes('电力电缆作业证')).length + '/8，作业下限 4 人', d: '持证人 ' + LAB.people.filter(p => p.cert.includes('电力电缆作业证')).map(p => p.n + ' ' + p.age + ' 岁').join('、') + '；8 月交接试验高峰', fix: '吴磊、孙倩 10 月取证；高峰期两个班互借电缆证人员各 2 天', who: LAB.leader + ' · 管理者', act: 'nav', to: 'risk', sub: 'sim', bt: '去调配' });
    if (undone.length) R.push({ lv: '中', team: TEAM.name, t: '关键节点未清 ' + undone.length + ' 项：' + undone.map(n => n.t).join('、'), d: '本周已清 ' + DB.nodeRate() + '%', fix: '周五 17:00 前逐项清零；A 责任人收到提醒', who: '赵立群', act: 'sup-notify', arg: '关键节点：' + undone.map(n => n.t).join('、') + ' 本周未清，请周五前闭环', bt: '发提醒' });
    if (worst.length) R.push({ lv: '中', team: TEAM.name, t: '周报排名靠后 ' + worst.length + ' 项：' + worst.map(i => i.n).join('、'), d: '第 ' + WK29.no + ' 期全市 11 局中第 9 名以后', fix: '对应关键节点列为本周重点，班组长已在用工安排里标记', who: '赵立群', act: 'nav', to: 'ledger', sub: 'weekly', bt: '看周报台账' });
    R.push({ lv: '低', team: TEAM3.name, t: '证书 90 天内到期 2 人', d: '复审报名提前 30 天', fix: '班组长本周报名', who: TEAM3.leader, act: 'sup-notify', arg: '证书复审：2 人 90 天内到期，请本周报名', bt: '发提醒' });
    return R.map((r, i) => Object.assign({ id: 'rk' + i }, r)); },
  riskHTML() { const R = this.risks(); const cnt = { 高: 0, 中: 0, 低: 0 }; R.forEach(r => cnt[r.lv]++); const sent = LS.get('sup_sent', {});
    return '<div class="grid2" style="grid-template-columns:1.7fr 1fr"><div class="card"><div class="h"><b>风险清单 · 本周</b><span>' + R.length + ' 项 · 从三个班组的台账自动汇出 · 每项对应一个治理动作</span></div><div class="tbl"><table class="t"><tr><th>等级</th><th>班组</th><th>风险</th><th>依据</th><th>治理动作</th><th>责任</th><th></th></tr>' +
      R.map(r => '<tr><td><span class="tag ' + (r.lv === '高' ? 'bad' : r.lv === '中' ? 'w' : 'ok') + '">' + r.lv + '</span></td><td class="note">' + h(r.team) + '</td><td><b>' + h(r.t) + '</b></td><td class="note">' + h(r.d) + '</td><td style="font-size:11px">' + h(r.fix) + '</td><td class="note">' + h(r.who) + '</td><td>' + (sent[r.id] ? '<span class="tag ok">已发 ' + h(sent[r.id]) + '</span>' : r.act === 'nav' ? '<button class="s g" data-act="nav" data-to="' + r.to + '" data-sub="' + (r.sub || '') + '">' + r.bt + '</button>' : '<button class="s" data-act="' + r.act + '" data-id="' + r.id + '" data-arg="' + h(r.arg || '') + '" data-who="' + h(r.who.split(' · ')[0]) + '">' + r.bt + '</button>') + '</td></tr>').join('') + '</table></div></div>' +
      '<div><div class="card"><div class="h"><b>风险分布</b></div>' + CH.mini.donut([{ k: '高', v: cnt.高, c: '#e5484d' }, { k: '中', v: cnt.中, c: '#e8791d' }, { k: '低', v: cnt.低, c: CPAL[4] }], { sub: '项' }) + '</div><div class="card" style="margin-top:10px"><div class="h"><b>组织弹性度</b><span>能跨班组顶上的人</span></div>' + this.flexGauges() + '</div></div></div>'; },
  flexGauges() { const cross = PEOPLE.filter(p => p.cert.includes('电力电缆作业证') || p.cert.includes('继电保护作业资格')).length + LAB.people.filter(p => p.cert.includes('电力电缆作业证')).length + 1; const tr = DB.transfers(); return '<div class="gauge3"><div><b>' + cross + '</b><span>可跨班组作业人数</span><em>持电缆 / 继保等跨专业资质</em></div><div><b>' + tr.filter(t => t.st === '已确认').length + '/' + tr.length + '</b><span>调配已确认 / 发起</span><em>柔性团队在办</em></div><div><b>' + (LAB.borrowed.length + tr.filter(t => t.st === '已确认').length) + '</b><span>在借人员</span><em>' + LAB.borrowed.map(b => b.n + '→' + b.to).join('、') + '</em></div></div>'; },
  /* ---------- 跨班组调配模拟 → 发起（待两位班长确认） ---------- */
  peopleOf(team) { return team === TEAM.name ? PEOPLE.map(p => p.n) : team === LAB.name ? LAB.people.map(p => p.n) : this.OM_PEOPLE; },
  personOf(team, n) { if (team === TEAM.name) return P[n]; if (team === LAB.name) return LAB.people.find(p => p.n === n); return { n, post: n === TEAM3.leader ? '班长' : '中级作业员', age: 34, cert: ['高压电工作业证', '岗位胜任能力证'].concat(n === '周涛' ? ['电力电缆作业证'] : []) }; },
  weekOf(team, n) { return team === TEAM.name ? (P[n] ? P[n].week : 0) : team === LAB.name ? (LAB.week[n] || 0) : 16; },
  cableOf(team) { return team === TEAM.name ? certHold('电力电缆作业证').length : team === LAB.name ? LAB.people.filter(p => p.cert.includes('电力电缆作业证')).length : 1; },
  simDefault() { return { from: LAB.name, who: '张伟', to: TEAM.name, days: 3, start: '2026-08-10', why: '田寮站 F02 交接试验与成套设备验收，需电力电缆作业证' }; },
  simImpact(f) { const p = this.personOf(f.from, f.who); const wk = this.weekOf(f.from, f.who); const hasCable = !!(p && p.cert.includes('电力电缆作业证')); const fromCable = this.cableOf(f.from), toCable = this.cableOf(f.to); const warns = [].concat(wk > WEEK_LIMIT ? [f.who + ' 本周已 ' + wk + ' 小时，超过约定，借出等于继续加码'] : [], !hasCable ? [f.who + ' 没有电力电缆作业证，到了也做不了交接试验'] : [], hasCable && fromCable - 1 < 2 ? [f.from + '借出后电缆证持证只剩 ' + (fromCable - 1) + ' 人'] : [], p && /班长/.test(p.post) ? [f.who + '是班长，借出期间' + f.from + '现场无人签发'] : []);
    const alt = this.peopleOf(f.from).filter(n => n !== f.who).map(n => ({ n, p: this.personOf(f.from, n), wk: this.weekOf(f.from, n) })).filter(x => x.p && x.p.cert.includes('电力电缆作业证') && x.wk <= WEEK_LIMIT)[0];
    return { p, wk, hasCable, fromCable, toCable, warns, ok: !warns.length, alt }; },
  simHTML() { const f = this.simState || this.simDefault(); const teams = TEAMS.map(t => t.n); const imp = this.simState ? this.simImpact(f) : null; const tr = DB.transfers();
    return '<div class="grid2" style="grid-template-columns:1.3fr 1fr"><div class="card"><div class="h"><b>跨班组调配 · 先看影响，再发起</b><span>发起后由借出、借入两位班长确认；人选与期间由班长最终定</span></div><div class="sim">' +
      '<label>从班组</label><select id="sm-from" data-act="sim-from">' + teams.map(t => '<option' + (t === f.from ? ' selected' : '') + '>' + h(t) + '</option>').join('') + '</select><label>人员</label><select id="sm-who">' + this.peopleOf(f.from).map(n => '<option' + (n === f.who ? ' selected' : '') + '>' + h(n) + '</option>').join('') + '</select>' +
      '<label>到班组</label><select id="sm-to">' + teams.map(t => '<option' + (t === f.to ? ' selected' : '') + '>' + h(t) + '</option>').join('') + '</select><label>起始</label><input type="date" id="sm-start" value="' + h(f.start) + '" min="' + TODAY + '">' +
      '<label>天数</label><input type="number" id="sm-days" min="1" max="30" value="' + f.days + '"><label>理由</label><input id="sm-why" value="' + h(f.why) + '">' +
      '</div><div class="bt"><button data-act="sim-run">模拟影响</button>' + (imp ? '<button ' + (imp.ok ? '' : 'class="g" ') + 'data-act="sim-go">发起调配（待两位班长确认）</button>' : '') + (imp && imp.alt ? '<button class="g" data-act="sim-alt" data-who="' + h(imp.alt.n) + '">改为借 ' + h(imp.alt.n) + '</button>' : '') + '</div>' +
      (imp ? '<div class="impact"><div class="' + (imp.wk > WEEK_LIMIT ? 'bad' : 'ok') + '"><b>' + h(f.who) + ' · ' + h(imp.p ? imp.p.post : '') + '</b>本周 <i>' + imp.wk + 'h</i> · 电缆证 <i>' + (imp.hasCable ? '有' : '无') + '</i><br>借出 ' + f.days + ' 天 ≈ 再加 <i>' + f.days * 8 + 'h</i></div><div class="' + (imp.fromCable - (imp.hasCable ? 1 : 0) < 2 ? 'bad' : '') + '"><b>' + h(f.from) + '（借出）</b>电缆证持证 <i>' + imp.fromCable + ' → ' + (imp.fromCable - (imp.hasCable ? 1 : 0)) + '</i> 人<br>在岗 ' + (f.from === LAB.name ? LAB.size - LAB.borrowed.length : f.from === TEAM.name ? PEOPLE.filter(p => p.status !== '休假').length : 11) + ' → 少 1 人</div><div class="ok"><b>' + h(f.to) + '（借入）</b>电缆证持证 <i>' + imp.toCable + ' → ' + (imp.toCable + (imp.hasCable ? 1 : 0)) + '</i> 人<br>' + (f.to === TEAM.name ? '田寮站验收可派人 ' + certHold('电力电缆作业证').filter(p => p.week + 8 <= WEEK_LIMIT + 8).length + ' → ' + (certHold('电力电缆作业证').length + (imp.hasCable ? 1 : 0)) : '高峰期人手 +1') + '</div></div>' + (imp.warns.length ? '<div class="note" style="margin-top:6px;color:var(--bad)">' + imp.warns.map(w => '· ' + h(w)).join('<br>') + '</div>' : '<div class="note" style="margin-top:6px;color:var(--ok)">没有冲突：证书够、工时在约定内、借出班组下限仍满足。</div>') : '<div class="empty">选好人和期间，点「模拟影响」，先看两边班组的证书覆盖和工时变化</div>') + '</div>' +
      '<div class="card"><div class="h"><b>调配记录</b><span>' + tr.length + ' 条 · 状态由班组长改</span></div>' + (tr.length ? '<div class="jobs">' + tr.map(t => '<div><span style="font-size:11.5px;color:var(--ink)">' + h(t.who) + '：' + h(t.from) + ' → ' + h(t.to) + '<br><span class="note">' + h(t.start) + ' 起 ' + t.days + ' 天 · ' + h(t.why) + (t.note ? ' · ' + h(t.note) : '') + '</span></span><span><span class="tag ' + (t.st === '已确认' ? 'ok' : t.st === '已退回' ? 'bad' : 'w') + '">' + h(t.st) + '</span>' + (t.st === '待确认' ? '<button class="s g" data-act="tr-remind" data-id="' + t.id + '">催一下</button>' : '') + '</span></div>').join('') + '</div>' : '<div class="empty">还没有发起过调配</div>') + '<div class="note" style="margin-top:8px">柔性团队五步：需求识别 → 人选匹配 → 班长确认 → 执行与回传 → 回写与评价。班长在自己的用工安排里点确认或退回。</div></div></div>'; },
  readSim() { const g = id => { const e = $(id); return e ? e.value : ''; }; return { from: g('#sm-from'), who: g('#sm-who'), to: g('#sm-to'), days: +g('#sm-days') || 3, start: g('#sm-start') || '2026-08-10', why: g('#sm-why') }; },
  simPreset(who, days) { const f = this.simDefault(); f.who = who || f.who; f.days = days || f.days; const team = TEAMS.map(t => t.n).find(t => this.peopleOf(t).includes(f.who)); if (team) f.from = team; this.simState = f; const host = $('#riskbody'); if (host) { host.innerHTML = this.simHTML(); CH.mount(host); } ACT['sim-say'](); },
  flexHTML() { const tr = DB.transfers(); const last = tr[0]; const st = [true, !!(this.simState || tr.length), !!last, !!(last && last.st === '已确认'), !!(last && last.st === '已确认' && last.done)];
    return '<div class="card"><div class="h"><b>柔性团队 · 五步</b><span>跨班组调配走完整链条才算数，每步都有记录</span></div><div class="steps5">' + [['需求识别', '田寮站 F02 交接试验需电力电缆作业证；配电自动化班持证 3 人，其中 1 人本周已满'], ['人选匹配', '按证书、工时、借出班组下限自动筛，管理者看影响'], ['班长确认', '借出、借入两位班长各自确认或退回，附意见'], ['执行与回传', '借入班组按本班派工、审票、开工、回传'], ['回写与评价', '工时记回本人，实操量回写本人画像；用后评价一次']].map((s, i) => '<div class="' + (st[i] ? (i === 2 && last && last.st === '待确认' ? 'on' : 'ok') : '') + '"><b>' + (i + 1) + ' ' + s[0] + '</b>' + s[1] + '</div>').join('') + '</div>' +
      '<div class="grid2" style="margin-top:10px"><div><div class="note" style="margin-bottom:4px">在办的柔性团队</div>' + (tr.length ? '<div class="jobs">' + tr.map(t => '<div><span style="font-size:11.5px;color:var(--ink)">' + h(t.who) + ' · ' + h(t.from) + ' → ' + h(t.to) + '<br><span class="note">' + h(t.start) + ' 起 ' + t.days + ' 天</span></span><span class="tag ' + (t.st === '已确认' ? 'ok' : t.st === '已退回' ? 'bad' : 'w') + '">' + h(t.st) + '</span></div>').join('') + '</div>' : '<div class="empty">还没有在办的调配</div>') + '<div class="jobs">' + LAB.borrowed.map(b => '<div><span style="font-size:11.5px;color:var(--ink)">' + h(b.n) + ' · ' + LAB.name + ' → ' + h(b.to) + '<br><span class="note">' + h(b.since) + ' 起 · ' + h(b.why) + '</span></span><span class="tag ok">执行中</span></div>').join('') + '</div></div><div>' + this.flexGauges() + '</div></div></div>'; },
  transferBlock() { const tr = DB.transfers().filter(t => t.st === '待确认' && (t.to === TEAM.name || t.from === TEAM.name)); if (!tr.length) return ''; return '<div class="card" id="trblock"><div class="h"><b>跨班组调配 · 待你确认</b><span>' + tr.length + ' 条 · 由' + TEAM.dept + '发起，人选和期间你可以改</span></div><div class="jobs">' + tr.map(t => '<div class="job"><span style="font-size:11.5px;color:var(--ink);white-space:normal">' + h(t.who) + '：' + h(t.from) + ' → ' + h(t.to) + '，' + h(t.start) + ' 起 ' + t.days + ' 天<br><span class="note">' + h(t.why) + '</span></span><span class="ops"><button data-act="tr-ok" data-id="' + t.id + '">确认</button><button class="g" data-act="tr-back" data-id="' + t.id + '">退回</button></span></div>').join('') + '</div></div>'; },
  /* ---------- 班长履职（客观数，不排名） ---------- */
  dutyRows() { const jobs = DB.jobs(); const tk = DB.tickets(); const plan = LS.get('plan', []); const docs = LS.get('docs', {}); const conf = LS.get('confirm', {});
    const zl = [{ k: 'dispatch', n: '派工及时', v: jobs.filter(j => j.st === '待派' && j.dateIso <= TODAY).length + ' 项待派已到期', ok: !jobs.filter(j => j.st === '待派' && j.dateIso <= TODAY).length, src: '任务台账' }, { k: 'ticket', n: '两票审核', v: '待审 ' + tk.filter(t => t.st === '待审').length + ' 张', ok: !tk.filter(t => t.st === '待审').length, src: '两票台账' }, { k: 'node', n: '关键节点周清', v: DB.nodeRate() + '%', ok: DB.nodeRate() >= 80, src: '关键节点管控表' }, { k: 'defect', n: '缺陷超期', v: DB.defects().filter(d => /超期/.test(d.st)).length + ' 单', ok: !DB.defects().filter(d => /超期/.test(d.st)).length, src: '缺陷台账' }, { k: 'load', n: '工时均衡', v: PEOPLE.filter(p => p.week > WEEK_LIMIT).length + ' 人超约定', ok: !PEOPLE.filter(p => p.week > WEEK_LIMIT).length, src: '工时台账' }, { k: 'grow', n: '培养在办', v: (plan.length + MENTORS.length) + ' 项', ok: plan.length + MENTORS.length >= 3, src: '培训计划 · 师带徒' }, { k: 'evid', n: '履职证据核对', v: Object.keys(conf).length + '/12 人', ok: Object.keys(conf).length >= 1, src: '班组画像' }];
    const node3 = t => [{ k: 'premeet', n: '班前会材料', ok: t === TEAM.name ? !!docs.premeet : true }, { k: 'weekplan', n: '周计划', ok: t === TEAM.name ? !!docs.weekplan : true }, { k: 'monthly', n: '月度总结', ok: t === TEAM.name ? !!docs.monthly : t !== TEAM3.name }];
    return [{ who: '赵立群', team: TEAM.name, m: zl, n3: node3(TEAM.name) },
      { who: LAB.leader, team: LAB.name, m: [{ k: 'dispatch', n: '派工及时', v: '0 项到期未派', ok: true, src: '试验计划' }, { k: 'ticket', n: '两票审核', v: '待审 0 张', ok: true, src: '两票台账' }, { k: 'node', n: '试验计划完成', v: '8 月 60/60', ok: true, src: '试验记录' }, { k: 'defect', n: '缺陷超期', v: '0 单', ok: true, src: '缺陷台账' }, { k: 'load', n: '工时均衡', v: '1 人超约定', ok: false, src: '工时台账' }, { k: 'grow', n: '培养在办', v: '3 项', ok: true, src: '培训计划' }, { k: 'evid', n: '履职证据核对', v: '2/8 人', ok: true, src: '班组画像' }], n3: node3(LAB.name) },
      { who: TEAM3.leader, team: TEAM3.name, m: [{ k: 'dispatch', n: '派工及时', v: '0 项到期未派', ok: true, src: '任务台账' }, { k: 'ticket', n: '两票审核', v: '待审 1 张', ok: false, src: '两票台账' }, { k: 'node', n: '计划完成', v: '42/42', ok: true, src: '任务台账' }, { k: 'defect', n: '缺陷超期', v: '0 单', ok: true, src: '缺陷台账' }, { k: 'load', n: '工时均衡', v: '0 人超约定', ok: true, src: '工时台账' }, { k: 'grow', n: '培养在办', v: '4 项', ok: true, src: '培训计划' }, { k: 'evid', n: '履职证据核对', v: '6/11 人', ok: true, src: '班组画像' }], n3: node3(TEAM3.name) }]; },
  /* ---------- 人才梯队 ---------- */
  ageOf(list) { return AGE_BANDS.map(b => list.filter(a => a >= b[1] && a <= b[2]).length); },
  OM_AGES: [26, 27, 29, 31, 33, 35, 36, 38, 42, 44, 47],
  talentPlan() { const s9 = skill9Of(P['刘一鸣']); return [{ who: '吴倩', team: TEAM.name, t: '试验班跨班锻炼两周（电缆试验）已完成，8 月再随交接试验一次', why: '电缆证持证人里最年轻，补试验班的电缆证断层', act: 'tal-plan', when: '8 月' }, { who: '刘一鸣', team: TEAM.name, t: '随队田寮站成套设备验收 + 继保旁站两次', why: '九类核心技能可自主 ' + s9.a + ' 类，先把验收做出独立记录', act: 'tal-plan', when: '8 月' }, { who: '郭子扬 · 赵敏', team: TEAM.name, t: '登高架设作业证取证（10 月批次）', why: '柱上 FTU 不停电检修可自主实施只有 2 人', act: 'tal-plan', when: '10 月' }, { who: '吴磊 · 孙倩', team: LAB.name, t: '电力电缆作业证取证（10 月批次）', why: '试验班电缆证只有 2 人，且均在 40 岁以上', act: 'tal-notify', when: '10 月' }, { who: '张伟', team: LAB.name, t: '压担子：8 月交接试验高峰后转带教，不再连续满负荷', why: '本周 28 小时，连续两周最高', act: 'tal-notify', when: '9 月' }]; },
  certByTeam() { const om = { '高压电工作业证': 11, '岗位胜任能力证': 10, '工作负责人资格': 4, '继电保护作业资格': 1, '电力电缆作业证': 1, '登高架设作业证': 6 }; const need = { [TEAM.name]: CERT_NEED, [LAB.name]: { '高压电工作业证': 8, '岗位胜任能力证': 7, '工作负责人资格': 3, '继电保护作业资格': 1, '电力电缆作业证': 4, '登高架设作业证': 2 }, [TEAM3.name]: { '高压电工作业证': 11, '岗位胜任能力证': 10, '工作负责人资格': 4, '继电保护作业资格': 1, '电力电缆作业证': 1, '登高架设作业证': 6 } };
    return CERT_KINDS.map(k => ({ k, t: [{ n: TEAM.name, v: certHold(k).length, need: need[TEAM.name][k] }, { n: LAB.name, v: LAB.people.filter(p => p.cert.includes(k)).length, need: need[LAB.name][k] }, { n: TEAM3.name, v: om[k], need: need[TEAM3.name][k] }] })); },
  /* ---------- 星级对标 ---------- */
  band(r) { const pct = r / WK29.bureaus.length * 100; return pct <= 1 ? 97 : pct <= 12.5 ? 87 : pct <= 25 ? 75 : pct <= 50 ? 65 : pct <= 75 ? 55 : 45; },
  star8() { const m = DB.month(); const onDuty = PEOPLE.filter(p => p.status !== '休假').length; const vals = { '两票合格率(%)': +(m.ticketsOK / m.tickets * 100).toFixed(1), '消缺率(%)': WK29.val('close'), '配电自动化终端在线率(%)': WK29.val('online'), '遥控成功率(%)': WK29.val('remote'), '自愈有效复电率(%)': WK29.val('heal'), '员工技能水平': skillEqAvg(), '人员实际在岗率（%）': +(onDuty / 12 * 100).toFixed(1), '生产工作计划完成率(%)': +(m.jobsDone / m.jobs * 100).toFixed(1) };
    const rk = { '消缺率(%)': WK29.rank('close'), '配电自动化终端在线率(%)': WK29.rank('online'), '遥控成功率(%)': WK29.rank('remote'), '自愈有效复电率(%)': WK29.rank('heal') };
    const src = { '两票合格率(%)': '两票台账 · 本月', '消缺率(%)': '周报第 29 期 缺陷闭环率', '配电自动化终端在线率(%)': '周报第 29 期 终端平均在线率', '遥控成功率(%)': '周报第 29 期 遥控成功率', '自愈有效复电率(%)': '周报第 29 期 自愈正确应用率', '员工技能水平': '技能等级认定台账 · 素质当量均值', '人员实际在岗率（%）': '人员名册 · 在岗 / 定编 12', '生产工作计划完成率(%)': '任务台账 · 本月' };
    return STAR8.map(s => { const v = vals[s.n]; const r = rk[s.n]; let sc; if (/在岗率/.test(s.n)) sc = v >= 80 ? 100 : 95; else if (/技能水平/.test(s.n)) sc = Math.min(100, Math.round(v / 1.2 * 100)); else if (r) sc = this.band(r); else sc = v >= 100 ? 97 : v >= 95 ? 87 : v >= 90 ? 75 : 60; return Object.assign({}, s, { v, r, sc, wsc: +(sc * s.w).toFixed(1), src: src[s.n] }); }); },
  starTotal() { return +this.star8().reduce((s, x) => s + x.wsc, 0).toFixed(1); },
  buildCheck(b) { const m = DB.month(); if (/岗位证书/.test(b.n)) return { v: '岗位胜任能力证 ' + certHold('岗位胜任能力证').length + '/11（新员工除外）', ok: certHold('岗位胜任能力证').length >= 11 }; if (/核心业务要求/.test(b.n)) return { v: '九类核心技能可自主 ' + skillCover().filter(c => c.a.length >= 3).length + '/9 类；低于人均 30% 实操量 ' + skill9Low().length + ' 人', ok: !skill9Low().length }; if (/人员配置/.test(b.n)) return { v: '缺编率 ' + Math.round((12 - PEOPLE.filter(p => p.status !== '休假').length) / 12 * 100) + '%，到岗 ' + PEOPLE.filter(p => p.status !== '休假').length + ' 人', ok: true }; if (/作业违章/.test(b.n)) return { v: '本年 A、B 类违章 0 起；一般 ' + VIOLATIONS.length + ' 起（本班自查）', ok: true }; if (/培训管理/.test(b.n)) return { v: '年度学时均值 ' + Math.round(PEOPLE.reduce((s, p) => s + p.hours.done / p.hours.req, 0) / PEOPLE.length * 100) + '%，本月未完成 ' + PEOPLE.filter(p => p.hours.m < 3).length + ' 人', ok: PEOPLE.filter(p => p.hours.m < 3).length <= 2 }; if (/缺陷管理/.test(b.n)) return { v: '闭环 ' + m.defectsClosed + '/' + m.defectsFound + '，超期 ' + DB.defects().filter(d => /超期/.test(d.st)).length + ' 单', ok: !DB.defects().filter(d => /超期/.test(d.st)).length }; if (/两票/.test(b.n)) return { v: '本月 ' + m.ticketsOK + '/' + m.tickets + ' 合格', ok: m.ticketsOK === m.tickets }; if (/计划管理/.test(b.n)) return { v: '年、月、周计划齐；本月完成 ' + m.jobsDone + '/' + m.jobs, ok: true }; if (/绩效管理/.test(b.n)) return { v: '履职证据已核对 ' + Object.keys(LS.get('confirm', {})).length + '/12 人', ok: Object.keys(LS.get('confirm', {})).length > 0 }; if (/实操量/.test(b.n)) return { v: '人均 ' + skill9PerCap() + ' 次；低于 30% ' + skill9Low().length + ' 人', ok: !skill9Low().length }; return null; },
  starHTML() { if (this.starProf === 'om') return this.starOmHTML(); const S8 = this.star8(); const tot = this.starTotal(); const B = STAR_BUILD; const ch = B.map(b => this.buildCheck(b)); const okN = ch.filter(c => c && c.ok).length, badN = ch.filter(c => c && !c.ok).length;
    return '<div class="grid2" style="grid-template-columns:1.8fr 1fr"><div class="card"><div class="h"><b>指标 · 配电自动化专业 8 项</b><span>' + h(STAR_SRC) + ' · 权重合计 1.0</span></div><div class="tbl"><table class="t star8"><tr><th>指标</th><th>权重</th><th>当前</th><th>全市排名</th><th>评分</th><th>加权</th><th>取数</th></tr>' + S8.map((s, i) => '<tr data-act="star-row" data-i="' + i + '" style="cursor:pointer"><td><b>' + h(s.n) + '</b><br><span class="note">' + h(s.cat) + '</span></td><td class="mono">' + s.w + '</td><td class="mono">' + s.v + '</td><td>' + (s.r ? '<span class="tag ' + (s.r <= 3 ? 'ok' : s.r >= 9 ? 'bad' : '') + '">第 ' + s.r + ' / 11</span>' : '<span class="note">—</span>') + '</td><td><div class="barw ' + (s.sc >= 80 ? 'ok' : s.sc < 60 ? 'bad' : '') + '"><i style="width:' + s.sc + '%"></i></div><span class="note">' + s.sc + '</span></td><td class="mono"><b>' + s.wsc + '</b></td><td class="note">' + h(s.src) + '</td></tr>').join('') + '<tr class="hl"><td><b>合计</b></td><td class="mono">1.0</td><td colspan="3" class="note">排名类按周报 11 区局位次套用评分区间（评价范围排名待正式口径）</td><td class="mono"><b>' + tot + '</b></td><td></td></tr></table></div>' +
      '<details class="fold"><summary>建设工作评价标准 · ' + B.length + ' 条（必备条件 ' + B.filter(b => /^1/.test(b.l1)).length + ' · 通用部分 ' + B.filter(b => /^2/.test(b.l1)).length + ' · 专业部分 ' + B.filter(b => /^3/.test(b.l1)).length + ' · 加分项 ' + B.filter(b => /^4/.test(b.l1)).length + '）· 本班台账可对照 ' + ch.filter(Boolean).length + ' 条：达标 ' + okN + ' · 未达标 ' + badN + '</summary><div class="tbl"><table class="t"><tr><th>#</th><th>目录</th><th>规范名称</th><th>建设标准（摘）</th><th>标准分</th><th>本班对照（台账）</th></tr>' + B.map((b, i) => { const c = ch[i]; return '<tr' + (c ? ' class="' + (c.ok ? '' : 'hl') + '"' : '') + '><td class="mono">' + (i + 1) + '</td><td class="note">' + h(b.l1.replace(/^\d\.?\s*/, '')) + ' › ' + h(b.l2.replace(/^\d\.\d\s*/, '')) + (b.l3 ? ' › ' + h(b.l3.replace(/^[\d.]+\s*/, '')) : '') + '</td><td><b>' + h(b.n) + '</b>' + (b.l4 ? '<br><span class="note">' + h(b.l4) + '</span>' : '') + '</td><td style="font-size:11px">' + h(b.std) + '</td><td class="mono">' + h(b.pts || '—') + '</td><td>' + (c ? '<span class="tag ' + (c.ok ? 'ok' : 'bad') + '">' + (c.ok ? '达标' : '未达标') + '</span> <span class="note">' + h(c.v) + '</span>' : '<span class="note">—</span>') + '</td></tr>'; }).join('') + '</table></div></details></div>' +
      '<div><div class="card"><div class="h"><b>星级对标 · 得分构成</b><span>' + TEAM.name + '</span></div>' + CH.mini.donut(S8.map((s, i) => ({ k: s.n.replace(/\(.*\)|（.*）/g, '').slice(0, 6), v: s.wsc, c: CPAL[i % 6], tip: s.n + ' ' + s.wsc })), { hero: String(tot), sub: '加权分' }) + '<div class="bt"><button data-act="star-gap">生成差距清单</button><button class="g" data-act="star-prof" data-p="om">切到配电运维专业口径</button></div></div>' +
      '<div class="card" style="margin-top:10px"><div class="h"><b>取数口径</b></div><div class="note" style="color:var(--ink);line-height:1.6">指标值来自本机台账与周报第 ' + WK29.no + ' 期；排名类指标以周报 11 区局位次代替"评价范围"位次；员工技能水平按素质当量（高级技师 1.8 / 技师 1.2 / 高级工 0.7 / 中级工 0.5 / 初级工 0.3）取均值；建设工作条目对照只标注本班台账能查到的项。</div></div></div></div>'; },
  starOmHTML() { const vals = { '两票合格率': '100%', '设备台账（图纸）准确率': '98.6%', '线路故障率': '0.62 次/百公里', '客户平均停电时间（中压）': '1.8 h', '故障缺陷比': '0.35', '居民端电压合格率': '99.7%', '员工技能水平（专业技术等级）': '0.72', '人员实际在岗率': '100%', '生产计划完成率': '100%' };
    return '<div class="grid2" style="grid-template-columns:1.6fr 1fr"><div class="card"><div class="h"><b>五星班组评价维度 · 配电运维专业</b><span>' + TEAM3.name + ' · 班长 ' + TEAM3.leader + '</span></div><div class="tbl"><table class="t"><tr><th>维度</th><th>评价指标</th><th>当前</th><th>取数</th></tr>' + STAR_OM.metrics.map(g => g.items.map((it, i) => '<tr>' + (i === 0 ? '<td rowspan="' + g.items.length + '"><b>' + h(g.cat) + '</b></td>' : '') + '<td>' + h(it) + '</td><td class="mono">' + h(vals[it] || '—') + '</td><td class="note">' + (/两票/.test(it) ? '两票台账' : /技能/.test(it) ? '技能等级认定台账' : /在岗/.test(it) ? '人员名册' : /计划/.test(it) ? '任务台账' : '电网管理平台 · 配电运维一班') + '</td></tr>').join('')).join('') + '</table></div>' +
      '<details class="fold" open><summary>建设工作评价标准 · 目录</summary><div class="tbl"><table class="t"><tr><th>部分</th><th>条目</th></tr>' + STAR_OM.build.map(b => '<tr><td><b>' + h(b.l1) + '</b></td><td>' + (b.items.length ? b.items.map(x => '<span class="tag">' + h(x) + '</span>').join(' ') : '<span class="note">按局年度评价通知执行</span>') + '</td></tr>').join('') + '</table></div></details></div>' +
      '<div class="card"><div class="h"><b>口径切换</b></div><div class="note" style="color:var(--ink);line-height:1.6">配电运维专业的指标与建设工作目录按部门口径列出；数值来自配电运维一班台账。切回配电自动化专业看 8 项指标和 ' + STAR_BUILD.length + ' 条建设工作的逐条对照。</div><div class="bt"><button data-act="star-prof" data-p="auto">切回配电自动化专业</button></div></div></div>'; },
  /* ---------- 参谋输出 ---------- */
  repParas(k) { const R = this.risks(); const tot = this.starTotal(); const S8 = this.star8().slice().sort((a, b) => a.sc - b.sc); const tr = DB.transfers(); const m = DB.month();
    if (k === 'review') return ['组织效能复盘 · ' + TEAM.dept + ' · 第 ' + WK29.no + ' 周', '一、结果：配电自动化班本月任务 ' + m.jobsDone + '/' + m.jobs + '，两票 ' + m.ticketsOK + '/' + m.tickets + '，关键节点周清 ' + DB.nodeRate() + '%；试验班交接试验 8 月 60 条完成；配电运维一班计划 42/42。', '二、短板（分层不排名）：[取一下五类指标……] ' + this.teams().map(t => t.n + '：' + t.five.filter(f => f.st !== 'ok').map(f => f.n + '（' + this.stName(f.st) + '）').join('、')).join('；') + '。', '三、风险治理：本周识别 ' + R.length + ' 项，高风险 ' + R.filter(r => r.lv === '高').length + ' 项；已发督办 / 提醒 ' + Object.keys(LS.get('sup_sent', {})).length + ' 条；跨班组调配发起 ' + tr.length + ' 条，确认 ' + tr.filter(t => t.st === '已确认').length + ' 条。', '四、班长履职：三个班长的客观指标里未达项 ' + this.dutyRows().reduce((s, r) => s + r.m.filter(x => !x.ok).length, 0) + ' 项，主要是工时均衡与两票待审。', '五、下周改进：电缆证持证人跨班组互借形成常态；周报排名靠后项对应关键节点由班长在周计划里标记；履职证据核对推进到全员。'];
    if (k === 'deploy') return [TEAM.dept + ' 下周工作部署 · 8-10 至 8-16', '一、重点作业：田寮站 F02 田玉四线自动化改造工程交接试验与成套设备验收（配电自动化班 + 试验班配合）；西德电气永磁驱动终端批量排查；存量未投运终端 14 台投运。', '二、指标：终端在线率保持全市前 5；缺陷闭环率 ≥98%；十五类异常信号周周清；交换机取电排查完成率提升到 70% 以上。', '三、人员统筹：' + (tr.length ? tr.map(t => t.who + ' ' + t.from + '→' + t.to + ' ' + t.days + ' 天（' + t.st + '）').join('；') : '电缆证持证人按需跨班组互借') + '；黄伟强、张伟下周安排室内两天。', '四、培养：刘一鸣随队验收；郭子扬、赵敏登高架设作业证 10 月取证；试验班吴磊、孙倩电缆证取证报名。', '五、安全：雷雨期间停止柱上作业；二次室作业验电与围栏；高温连续作业三小时轮换。'];
    return [TEAM.dept + ' 周汇报 · 第 ' + WK29.no + ' 周（' + WK29.period + '）', '一、指标：光明局终端在线率 ' + WK29.val('online') + '%（全市第 ' + WK29.rank('online') + '）、遥控成功率 ' + WK29.val('remote') + '%（第 ' + WK29.rank('remote') + '）、缺陷闭环率 ' + WK29.val('close') + '%（第 ' + WK29.rank('close') + '）；排名靠后：' + WK29.items.filter(i => WK29.rank(i.k) >= 9).map(i => i.n + '第 ' + WK29.rank(i.k)).join('、') + '。星级对标 8 项指标加权 [取一下星级对标……] ' + tot + ' 分，最弱两项：' + S8.slice(0, 2).map(s => s.n).join('、') + '。', '二、组织：三个班组 31 人；五类指标待治理格 ' + this.teams().reduce((s, t) => s + t.five.filter(f => f.st === 'bad').length, 0) + ' 个、关注格 ' + this.teams().reduce((s, t) => s + t.five.filter(f => f.st === 'warn').length, 0) + ' 个；本周风险 ' + R.length + ' 项（高 ' + R.filter(r => r.lv === '高').length + '）。', '三、统筹：' + (tr.length ? '跨班组调配 ' + tr.length + ' 条（' + tr.map(t => t.who + ' ' + t.st).join('、') + '）' : '本周未发起跨班组调配') + '；刘畅借在配电运维一班 8-15 归队。', '四、人才：近三年输出 ' + OUTPUT3.length + ' 人；电力电缆作业证三个班组合计 ' + (certHold('电力电缆作业证').length + LAB.people.filter(p => p.cert.includes('电力电缆作业证')).length + 1) + ' 人、持证人平均年龄偏大，10 月取证批次已报 4 人。', '五、需要部门决定：交接试验高峰期电缆证人员互借机制；西德电气永磁终端排查的厂家配合。'];
  }
};
/* ---------- 页面 ---------- */
PAGES.super = {
  render() { const T = SUPER.teams(); const tot = T.reduce((s, t) => s + t.size, 0); const it = WK29.item(SUPER.wk); const R = SUPER.risks(); const tiers = { ok: [], warn: [], bad: [] }; T.forEach(t => t.five.forEach(f => tiers[f.st].push(t.n.replace('配电', '') + ' · ' + f.n)));
    return cmdHTML(['三个班组这周的风险在哪', '光明局在线率全市第几', '哪个班组证书到期的最多', '下个月人力缺口在哪', '写一份部门周汇报']) + pageHead('部门态势', TEAM.dept + ' · ' + T.length + ' 个班组 ' + tot + ' 人 · 五类指标分层，不排名 · 周报第 ' + WK29.no + ' 期') +
      '<div class="teams">' + T.map((t, i) => '<div class="tc" data-act="sup-team" data-n="' + h(t.n) + '"><h5>' + h(t.n) + ' <span class="note">班长 ' + h(t.leader) + ' · ' + t.size + ' 人 · ' + h(t.prof) + '</span></h5><div><span>年度学时完成</span><b>' + t.hours + '%</b></div><div><span>证书 90 天内到期</span><b>' + t.certsDue + ' 人</b></div><div><span>本月两票 / 任务</span><b>' + h(t.ticketsOK) + ' · ' + h(t.jobs) + '</b></div><div><span>' + (t.n === TEAM.name ? '关键节点周清' : t.n === LAB.name ? '8 月交接试验' : '本月计划完成') + '</span><b>' + (t.n === TEAM.name ? DB.nodeRate() + '%' : t.n === LAB.name ? '60 条' : '42/42') + '</b></div><div><span>五类分层</span><b>' + t.five.map(f => '<i class="tag ' + (f.st === 'ok' ? 'ok' : f.st === 'warn' ? 'w' : 'bad') + '" style="margin:0 1px">' + f.n.slice(0, 2) + '</i>').join('') + '</b></div></div>').join('') + '</div>' +
      '<div class="grid2" style="grid-template-columns:1.5fr 1fr"><div class="card"><div class="h"><b>五类指标 · 分层热力</b><span>稳健 / 关注 / 待治理 · 点一格看三项指标与责任人</span></div><div class="sheat"><div></div>' + FIVE.map(f => '<div class="hd">' + h(f.n) + '</div>').join('') + T.map(t => '<div class="rn">' + h(t.n) + '<span>' + h(t.leader) + ' · ' + t.size + ' 人</span></div>' + t.five.map(f => '<div class="c ' + f.st + '" data-act="sup-cell" data-n="' + h(t.n) + '" data-k="' + f.k + '"><b>' + SUPER.stName(f.st) + '</b>' + h(f.items[0].n.slice(0, 7)) + ' ' + h(f.items[0].val) + '</div>').join('')).join('') + '</div><div class="tier" style="margin-top:10px"><div class="ok"><b>稳健 ' + tiers.ok.length + '</b>' + tiers.ok.map(x => '<span>' + h(x) + '</span>').join('') + '</div><div class="warn"><b>关注 ' + tiers.warn.length + '</b>' + tiers.warn.map(x => '<span>' + h(x) + '</span>').join('') + '</div><div class="bad"><b>待治理 ' + tiers.bad.length + '</b>' + tiers.bad.map(x => '<span>' + h(x) + '</span>').join('') + '</div></div></div>' +
      '<div class="card"><div class="h"><b>光明局在全市 11 局的位置</b><span>周报第 ' + WK29.no + ' 期 · 点指标切换</span></div><div class="kbq" style="margin-bottom:6px">' + WK29.items.filter(i => i.star).map(i => '<b data-act="sup-wk" data-k="' + i.k + '" style="' + (i.k === SUPER.wk ? 'background:var(--tint);color:var(--pri);border-color:#c9cbf5' : '') + '">' + h(i.n.replace(/（.*）/, '').slice(0, 8)) + '</b>').join('') + '</div><div id="supwk">' + LEDGERPG.wkChart(SUPER.wk) + CH.mini.legend([{ n: '光明', c: CPAL[1] }, { n: '其他区局', c: CPAL[0] }]) + '<div class="note" style="margin-top:4px">' + h(it.n) + '：光明 ' + it.vals[WK29.gm()] + it.unit + '，全市 ' + it.total + it.unit + '，第 ' + WK29.rank(it.k) + ' 名。' + h(it.detail) + '</div></div></div></div>' +
      '<div class="card"><div class="h"><b>本周关注 · 跨班组</b><span>' + R.length + ' 项 · 高 ' + R.filter(r => r.lv === '高').length + ' · 治理动作在「风险与统筹」</span><div class="r"><button class="s" data-act="nav" data-to="risk">去治理</button></div></div><div class="jobs">' + R.slice(0, 6).map(r => '<div><span style="font-size:11.5px;color:var(--ink)"><span class="tag ' + (r.lv === '高' ? 'bad' : r.lv === '中' ? 'w' : 'ok') + '">' + r.lv + '</span>' + h(r.t) + '<br><span class="note">' + h(r.team) + ' · ' + h(r.fix) + '</span></span><span class="note">' + h(r.who) + '</span></div>').join('') + '</div></div>'; },
  after() { CH.mount($('#main')); if (!S.briefed) { S.briefed = true; XW.at(400, () => XW.answer('三个班组的五类指标放在一张热力图上，红色是待治理：' + SUPER.teams().map(t => t.n + ' ' + (t.five.filter(f => f.st === 'bad').map(f => f.n).join('、') || '无')).join('；') + '。分层不排名，点一格看指标和责任人；本周风险 ' + SUPER.risks().length + ' 项在下面，治理动作在风险与统筹。', null, { confirm: false })); } }
};
PAGES.flow = {
  render() { const jobs = DB.jobs().filter(j => j.st !== '已删除'); const tk = DB.tickets(); const sw = DB.skillWrites(); const plan = LS.get('plan', []); const disp = LS.get('dispatch', {}); const tr = DB.transfers(); const prog = DB.progressAll();
    const steps = [{ k: 'task', n: '任务', v: jobs.length, e: '待派 ' + jobs.filter(j => j.st === '待派').length }, { k: 'dispatch', n: '派工', v: Object.keys(disp).length + jobs.filter(j => j.who && !j.added).length, e: '带推荐 / 排除理由' }, { k: 'ticket', n: '审票', v: tk.filter(t => /已审核|已签发|已执行/.test(t.st)).length + '/' + tk.length, e: '待审 ' + tk.filter(t => t.st === '待审').length }, { k: 'start', n: '开工', v: jobs.filter(j => /进行中|已完成|已关闭/.test(j.st)).length, e: '在现场 ' + jobs.filter(j => j.st === '进行中').length }, { k: 'report', n: '回传', v: prog.reduce((s, g) => s + g.ev.length, 0), e: '连续超 3h ' + prog.filter(g => g.warn).length + ' 组' }, { k: 'finish', n: '完工', v: jobs.filter(j => /已完成|已关闭/.test(j.st)).length, e: '工时已记' }, { k: 'write', n: '实操回写', v: sw.length, e: '九类核心技能' }, { k: 'profile', n: '画像', v: PEOPLE.length, e: '五类指标 · 四卡' }, { k: 'grow', n: '培养', v: plan.length + MENTORS.length, e: '计划 + 师带徒' }];
    return cmdHTML(['田寮站验收现在走到哪一步', '待确认的调配有几条', '这周谁的实操量回写了', '三个班本月两票合格率']) + pageHead('全流程俯瞰', '任务 → 派工 → 审票 → 开工 → 回传 → 完工 → 实操回写 → 画像 → 培养 · 每一格都是班组长那边此刻的数，点格看明细') +
      '<div class="flowbar">' + steps.map(s => '<div data-act="sup-flow" data-k="' + s.k + '"><b>' + s.v + '</b><span>' + s.n + '</span><em>' + h(s.e) + '</em></div>').join('') + '</div>' +
      '<div class="grid2" style="grid-template-columns:1.6fr 1fr"><div class="card"><div class="h"><b>' + TEAM.name + ' · 任务链</b><span>' + jobs.length + ' 项 · 只读</span></div><div class="tbl"><table class="t"><tr><th>任务</th><th>状态</th><th>负责人 / 班员</th><th>工作票</th><th>关键节点</th><th>回写</th></tr>' + jobs.map(j => { const t = j.ticketNo ? DB.ticket(j.ticketNo) : null; const nd = j.node ? NODES.find(n => n.id === j.node) : null; const w = sw.find(x => x.job === j.t); return '<tr' + (j.id === MAINLINE ? ' class="hl"' : '') + '><td><b>' + h(j.t) + '</b><br><span class="note">' + h(j.when) + (j.src ? ' · ' + h(j.src) : '') + '</span></td><td><span class="tag ' + (/已完成|已关闭/.test(j.st) ? 'ok' : /进行中/.test(j.st) ? 'c' : j.lv === '超期' ? 'bad' : 'w') + '">' + h(j.st) + '</span></td><td class="note">' + h(DB.crewOf(j).join('、') || '待派') + '</td><td class="note">' + (t ? h(t.no) + ' <span class="tag ' + (/已审核|已签发|已执行/.test(t.st) ? 'ok' : 'w') + '">' + h(t.st) + '</span>' : j.ticket ? h(j.ticket) + '（待拟）' : '—') + '</td><td class="note">' + (nd ? h(nd.t) + ' · ' + h(nd.cyc) + (DB.nodesDone().includes(nd.id) ? ' <span class="tag ok">已清</span>' : '') : '—') + '</td><td class="note">' + (w ? h((SKILL9.find(s => s.k === w.k) || { n: w.k }).n) + ' +1' : j.skill ? '完工后回写「' + h((SKILL9.find(s => s.k === j.skill) || { n: j.skill }).n) + '」' : '—') + '</td></tr>'; }).join('') + '</table></div></div>' +
      '<div><div class="card"><div class="h"><b>跨班组调配</b><span>' + tr.filter(t => t.st === '待确认').length + ' 条待班长确认</span></div>' + (tr.length ? '<div class="jobs">' + tr.map(t => '<div><span style="font-size:11.5px;color:var(--ink)">' + h(t.who) + ' · ' + h(t.from) + ' → ' + h(t.to) + '<br><span class="note">' + h(t.start) + ' 起 ' + t.days + ' 天' + (t.note ? ' · ' + h(t.note) : '') + '</span></span><span><span class="tag ' + (t.st === '已确认' ? 'ok' : t.st === '已退回' ? 'bad' : 'w') + '">' + h(t.st) + '</span>' + (t.st === '待确认' ? '<button class="s g" data-act="tr-remind" data-id="' + t.id + '">催一下</button>' : '') + '</span></div>').join('') + '</div>' : '<div class="empty">没有待确认的调配；在风险与统筹里发起</div>') + '</div>' +
      '<div class="card" style="margin-top:10px"><div class="h"><b>' + LAB.name + ' · 本周工时</b><span>' + LAB.leader + ' · 借出 ' + LAB.borrowed.length + ' 人</span></div>' + CH.mini.bars(Object.keys(LAB.week).map(n => ({ n, v: LAB.week[n], c: LAB.week[n] > WEEK_LIMIT ? '#e5484d' : CPAL[2], tip: n + ' 本周 ' + LAB.week[n] + 'h' })), { limit: WEEK_LIMIT, unit: 'h', max: 32, h: 11 }) + '</div>' +
      '<div class="card" style="margin-top:10px"><div class="h"><b>操作流水 · 两个角色</b><span>最近 10 条</span></div>' + (DB.logs().length ? '<div class="jobs">' + DB.logs().slice(0, 10).map(l => '<div><span style="font-size:11px;color:var(--ink)"><span class="tag ' + (l.role === 'manager' ? 'v' : '') + '">' + (l.role === 'manager' ? '管理者' : '班组长') + '</span>' + h(l.kind) + '：' + h(l.text) + '</span><span class="note">' + h(l.d) + '</span></div>').join('') + '</div>' : '<div class="empty">还没有操作。班组长那边派一次工，这里就有</div>') + '</div></div></div>'; },
  after() { CH.mount($('#main')); }
};
PAGES.risk = {
  tabs: [{ k: 'list', n: '风险清单' }, { k: 'sim', n: '跨班组调配' }, { k: 'flex', n: '柔性团队' }],
  render() { return cmdHTML(['试验班张伟借到自动化班三天', '田寮站交接试验缺电缆证的人怎么办', '给赵立群发一条督办', '哪个班组工时最不均衡']) + pageHead('风险与统筹', '风险识别 → 治理动作 → 跨班组资源统筹（柔性团队五步）· 人选与期间由班组长确认') + tabsHTML(this.tabs, S.sub || 'list') + '<div id="riskbody">' + this.body() + '</div>'; },
  body() { const s = S.sub || 'list'; return s === 'sim' ? SUPER.simHTML() : s === 'flex' ? SUPER.flexHTML() : SUPER.riskHTML(); },
  after() { CH.mount($('#main')); }
};
PAGES.duty = {
  render() { const rows = SUPER.dutyRows();
    return cmdHTML(['三个班长这周的履职情况', '赵立群的关键节点周清率', '给周建国发工时均衡提醒']) + pageHead('班长履职', '三个班长的客观履职数 · 不排名 · 每格点开有台账来源 · 提醒发给本人') +
      '<div class="card"><div class="h"><b>履职指标 · 七项</b><span>取自任务、两票、关键节点、缺陷、工时、培训计划、班组画像</span></div><div class="tbl"><table class="t"><tr><th>班长</th>' + rows[0].m.map(x => '<th>' + h(x.n) + '</th>').join('') + '<th></th></tr>' + rows.map(r => '<tr><td><b>' + h(r.who) + '</b><br><span class="note">' + h(r.team) + '</span></td>' + r.m.map(x => '<td data-act="sup-duty" data-who="' + h(r.who) + '" data-k="' + x.k + '" style="cursor:pointer"><span class="tag ' + (x.ok ? 'ok' : 'w') + '">' + h(x.v) + '</span></td>').join('') + '<td><button class="s g" data-act="sup-remind" data-who="' + h(r.who) + '">发提醒</button></td></tr>').join('') + '</table></div></div>' +
      '<div class="grid2"><div class="card"><div class="h"><b>组织节点 · 三项</b><span>班前会材料 / 周计划 / 月度总结</span></div><div class="tbl"><table class="t"><tr><th>班长</th><th>班前会材料</th><th>周计划</th><th>月度总结</th></tr>' + rows.map(r => '<tr><td><b>' + h(r.who) + '</b></td>' + r.n3.map(x => '<td><span class="tag ' + (x.ok ? 'ok' : 'w') + '">' + (x.ok ? '已交' : '待交') + '</span></td>').join('') + '</tr>').join('') + '</table></div><div class="note" style="margin-top:6px">配电自动化班的三项读文稿中心；另两个班组按各自文稿记录。</div></div>' +
      '<div class="card"><div class="h"><b>未达项 · 汇总</b></div>' + CH.mini.bars(rows.map(r => ({ n: r.who, v: r.m.filter(x => !x.ok).length, c: r.m.filter(x => !x.ok).length >= 3 ? '#e5484d' : r.m.filter(x => !x.ok).length ? '#e8791d' : CPAL[4], tip: r.who + ' 未达 ' + r.m.filter(x => !x.ok).length + ' 项' })), { max: 7, unit: ' 项', h: 14 }) + '<div class="note" style="margin-top:6px">未达项只是提醒的依据，不做班长之间的排名；每一项点开能看到台账。</div></div></div>'; },
  after() { CH.mount($('#main')); }
};
PAGES.talent = {
  tabs: [{ k: 'ladder', n: '梯队与输出' }, { k: 'age', n: '年龄结构与预测' }, { k: 'cert', n: '关键资质' }],
  render() { return cmdHTML(['近三年人才输出有哪些', '五年后哪个班组骨干断层最重', '电力电缆作业证三个班组各几人']) + pageHead('人才梯队', '近三年输出 · 三个班组年龄结构与五年后推演 · 关键资质分布 · 梯队建议由班组长确认') + tabsHTML(this.tabs, S.sub || 'ladder') + '<div id="talbody">' + this.body() + '</div>'; },
  body() { const s = S.sub || 'ladder';
    if (s === 'age') { const A = [{ n: TEAM.name, now: SUPER.ageOf(PEOPLE.map(p => p.age)), later: ageIn(5) }, { n: LAB.name, now: SUPER.ageOf(SUPER.labAges()), later: SUPER.ageOf(SUPER.labAges().map(a => a + 5)) }, { n: TEAM3.name, now: SUPER.ageOf(SUPER.OM_AGES), later: SUPER.ageOf(SUPER.OM_AGES.map(a => a + 5)) }];
      return '<div class="grid3">' + A.map((t, i) => '<div class="card"><div class="h"><b>' + h(t.n) + '</b><span>平均 ' + (t.n === TEAM.name ? ageAvg(PEOPLE) : t.n === LAB.name ? ageAvg(LAB.people) : (SUPER.OM_AGES.reduce((s, a) => s + a, 0) / SUPER.OM_AGES.length).toFixed(1)) + ' 岁</span></div>' + CH.mini.group(AGE_BANDS.map(b => b[0].replace(' 岁', '')), [{ n: '现在', vals: t.now, c: CPAL[i] }, { n: '五年后', vals: t.later, c: CPAL[3] }], { h: 120, max: 6, unit: ' 人' }) + CH.mini.legend([{ n: '现在', c: CPAL[i] }, { n: '五年后（不进人）', c: CPAL[3] }]) + '<div class="note" style="margin-top:4px">五年后 41 岁以上 ' + (t.now[4] + t.now[5]) + ' → ' + (t.later[4] + t.later[5]) + ' 人；30 岁以下 ' + (t.now[0] + t.now[1]) + ' → ' + (t.later[0] + t.later[1]) + ' 人。</div></div>').join('') + '</div>' +
        '<div class="grid2"><div class="card"><div class="h"><b>岗位结构 · 环比上季度</b><span>三个班组</span></div><div class="tbl"><table class="t"><tr><th>班组</th><th>班长 / 技术员</th><th>高级</th><th>中级</th><th>初级（含学员）</th><th>上季度变化</th></tr>' + TEAMS.map(t => { const p = TEAMS2[t.n].posts; return '<tr><td><b>' + h(t.n) + '</b></td><td class="mono">' + ((p.班长 || 0) + (p.技术员 || 0)) + '</td><td class="mono">' + (p.高级 || 0) + '</td><td class="mono">' + (p.中级 || 0) + '</td><td class="mono">' + (p.初级 || 0) + '</td><td class="note">' + (t.n === TEAM.name ? '中级 +1（郭子扬晋级）' : t.n === LAB.name ? '刘畅借出 −1' : '无变化') + '</td></tr>'; }).join('') + '</table></div></div>' +
        '<div class="card"><div class="h"><b>预测 · 未来 12 个月</b><span>从名册与证书台账推</span></div><div class="jobs">' + [['证书到期', '三个班组 ' + (TEAMS.reduce((s, t) => s + t.certsDue, 0)) + ' 人 90 天内到期；全年到期 ' + CERTS.filter(c => !c.renewed && daysTo(c.due) <= 365).length + ' 张（配电自动化班）'], ['岗位缺口', '试验班 8 月交接试验高峰缺电缆证 2 人；配电自动化班 9 月终端投运高峰缺 1–2 人'], ['退休 / 流出', '五年内到 60 岁：0 人；近三年输出 4 人，主要流向部门技术专责与试验班'], ['骨干断层', '试验班电缆证持证人平均 ' + SUPER.labCertAvg() + ' 岁，35 岁以下 0 人 → 高风险']].map(r => '<div><span style="font-size:11.5px;color:var(--ink)">' + h(r[0]) + '<br><span class="note">' + h(r[1]) + '</span></span></div>').join('') + '</div></div></div>'; }
    if (s === 'cert') { const C = SUPER.certByTeam();
      return '<div class="grid2" style="grid-template-columns:1.6fr 1fr"><div class="card"><div class="h"><b>关键资质 · 三个班组</b><span>持证 / 作业下限 · 点一行看是谁</span></div><div class="tbl"><table class="t"><tr><th>资质</th>' + TEAMS.map(t => '<th>' + h(t.n) + '</th>').join('') + '<th>合计</th></tr>' + C.map(c => '<tr data-act="tal-cert" data-k="' + h(c.k) + '" style="cursor:pointer"><td><b>' + h(c.k) + '</b></td>' + c.t.map(x => '<td>' + (x.v < x.need ? '<span class="tag bad">' : '<span class="tag ok">') + x.v + '/' + x.need + '</span></td>').join('') + '<td class="mono">' + c.t.reduce((s, x) => s + x.v, 0) + '</td></tr>').join('') + '</table></div></div>' +
        '<div class="card"><div class="h"><b>电力电缆作业证</b><span>交接试验的关口</span></div>' + CH.mini.cols(TEAMS.map((t, i) => { const c = C.find(x => x.k === '电力电缆作业证').t[i]; return { n: t.n.replace('配电', ''), v: c.v, c: c.v < c.need ? '#e5484d' : CPAL[i], tip: t.n + ' ' + c.v + '/' + c.need }; }), { max: 5, h: 110, labels: true }) + '<div class="note" style="margin-top:6px">配电自动化班 3 人（韩雪 38、吴倩、赵敏），试验班 2 人（' + LAB.people.filter(p => p.cert.includes('电力电缆作业证')).map(p => p.n + ' ' + p.age).join('、') + '），配电运维一班 1 人。8 月交接试验高峰两个班互借，10 月取证批次报 4 人。</div><div class="bt"><button data-act="nav" data-to="risk" data-sub="sim">去发起调配</button></div></div></div>'; }
    const TP = SUPER.talentPlan(); const done = LS.get('sup_talent', {});
    return '<div class="grid2" style="grid-template-columns:1fr 1.4fr"><div class="card"><div class="h"><b>近三年人才输出</b><span>' + OUTPUT3.length + ' 人 · 人员异动台账</span></div><div class="jobs">' + OUTPUT3.map(o => '<div><span style="font-size:11.5px;color:var(--ink)">' + h(o.n) + ' · ' + h(o.to) + '<br><span class="note">' + h(o.d) + '</span></span><span class="tag ' + (o.kind === '晋升' ? 'ok' : o.kind === '输出' ? 'v' : 'c') + '">' + h(o.kind) + '</span></div>').join('') + '</div>' + CH.mini.donut([{ k: '晋升', v: OUTPUT3.filter(o => o.kind === '晋升').length, c: CPAL[4] }, { k: '输出', v: OUTPUT3.filter(o => o.kind === '输出').length, c: CPAL[0] }, { k: '跨班锻炼', v: OUTPUT3.filter(o => o.kind === '跨班锻炼').length, c: CPAL[2] }], { sub: '人' }) + '</div>' +
      '<div class="card"><div class="h"><b>梯队建议</b><span>' + TP.length + ' 条 · 配电自动化班的写进培养计划，其他班组发给班长</span></div><div class="focus">' + TP.map((x, i) => '<div><span class="tag ' + (x.team === TEAM.name ? 'v' : 'c') + '">' + h(x.team.replace('配电', '')) + '</span><div><b>' + h(x.who) + ' · ' + h(x.t) + '</b><span class="note">' + h(x.why) + '</span></div><i>' + (done[i] ? '<span class="tag ok">' + h(done[i]) + '</span>' : '<button class="s g" data-act="' + x.act + '" data-i="' + i + '">' + (x.act === 'tal-plan' ? '排进计划' : '发给班长') + '</button>') + '</i></div>').join('') + '</div></div></div>'; },
  after() { CH.mount($('#main')); }
};
PAGES.star = {
  render() { return cmdHTML(['生成星级对标差距清单', '切到配电运维专业口径', '终端在线率的评分怎么算']) + pageHead('星级对标', h(STAR_SRC) + ' · 8 项指标按权重加权 · ' + STAR_BUILD.length + ' 条建设工作可对照本班台账 · 可切配电运维专业') + '<div id="starbody">' + SUPER.starHTML() + '</div>'; },
  after() { CH.mount($('#main')); }
};
PAGES.effect = {
  render() { const m = DB.month(); const T = SUPER.teams(); const R = SUPER.risks(); const tr = DB.transfers(); const rows = SUPER.dutyRows(); const diff = Math.max.apply(null, PEOPLE.map(p => p.week)) - Math.min.apply(null, PEOPLE.filter(p => p.post !== '班长' && p.status !== '休假').map(p => p.week));
    const G = [['任务完成率', Math.round(m.jobsDone / m.jobs * 100) + '%', '本月 ' + m.jobsDone + '/' + m.jobs], ['两票合格率', Math.round(m.ticketsOK / m.tickets * 100) + '%', m.ticketsOK + '/' + m.tickets], ['关键节点周清率', DB.nodeRate() + '%', '周周清 · 日日清 · 限时清'], ['缺陷闭环率', WK29.val('close') + '%', '周报第 ' + WK29.no + ' 期 · 全市第 ' + WK29.rank('close')], ['人均核心技能实操', skill9PerCap() + ' 次', '低于 30% ' + skill9Low().length + ' 人'], ['学时完成', Math.round(PEOPLE.reduce((s, p) => s + p.hours.done / p.hours.req, 0) / PEOPLE.length * 100) + '%', '本月未完成 ' + PEOPLE.filter(p => p.hours.m < 3).length + ' 人'], ['工时均衡度', Math.max(0, 100 - diff * 4) + '', '最高最低差 ' + diff + 'h'], ['组织弹性度', (PEOPLE.filter(p => p.cert.includes('电力电缆作业证') || p.cert.includes('继电保护作业资格')).length + 3) + ' 人', '可跨班组作业'], ['星级对标加权', SUPER.starTotal() + '', '8 项指标']];
    const six = [['组织层面分层短板', T.reduce((s, t) => s + t.five.filter(f => f.st !== 'ok').length, 0) + ' 格', '关注 + 待治理', 'super'], ['风险识别与治理', R.length + ' 项 · 已办 ' + Object.keys(LS.get('sup_sent', {})).length, '本周', 'risk'], ['班长履职监督', rows.reduce((s, r) => s + r.m.filter(x => !x.ok).length, 0) + ' 项未达', '三个班长', 'duty'], ['跨班组资源统筹', tr.length + ' 条 · 确认 ' + tr.filter(t => t.st === '已确认').length, '柔性团队', 'risk'], ['人才梯队建设', OUTPUT3.length + ' 人输出 · 4 人取证', '近三年 · 10 月批次', 'talent'], ['组织态势研判与参谋输出', Object.keys(LS.get('docs', {})).filter(k => /^sup-/.test(k)).length + ' 份', '周汇报 / 复盘 / 部署', 'report']];
    return cmdHTML(['写一份组织效能复盘', '三个班本月两票合格率', '哪个班组工时最不均衡']) + pageHead('组织效能', '一屏看结果、过程与组织状态 · 全部同源于班组长的台账 · 点数字去对应模块') +
      '<div class="gauge3" style="grid-template-columns:repeat(3,1fr)">' + G.map(g => '<div><b>' + h(g[1]) + '</b><span>' + h(g[0]) + '</span><em>' + h(g[2]) + '</em></div>').join('') + '</div>' +
      '<div class="grid2"><div class="card"><div class="h"><b>三个班组 · 六个月</b><span>年度学时完成 %</span></div>' + CH.mini.group(MONTHS6, Object.keys(TEAMS2).map((n, i) => ({ n: n.replace('配电', ''), vals: TEAMS2[n].hoursM, c: CPAL[i] })), { max: 100, unit: '%', h: 130 }) + CH.mini.legend(Object.keys(TEAMS2).map((n, i) => ({ n: n.replace('配电', ''), c: CPAL[i] }))) + '</div><div class="card"><div class="h"><b>三个班组 · 任务与两票</b><span>本月</span></div>' + CH.mini.group(MONTHS6, Object.keys(TEAMS2).map((n, i) => ({ n: n.replace('配电', ''), vals: TEAMS2[n].jobsM, c: CPAL[i] })), { h: 130 }) + '</div></div>' +
      '<div class="card"><div class="h"><b>组织管理六维 · 本周状态</b><span>点一行去对应模块</span></div><div class="mets" style="grid-template-columns:repeat(3,1fr)">' + six.map(s => '<div><b>' + h(s[1]) + '</b><span>' + h(s[0]) + '</span><em>' + h(s[2]) + '</em><button class="s g" data-act="nav" data-to="' + s[3] + '">打开</button></div>').join('') + '</div></div>'; },
  after() { CH.mount($('#main')); }
};
PAGES.report = {
  KINDS: [{ k: 'brief', n: '部门周汇报' }, { k: 'review', n: '组织效能复盘' }, { k: 'deploy', n: '下周部署稿' }],
  render() { const docs = LS.get('docs', {}); return cmdHTML(['写一份部门周汇报', '写一份组织效能复盘', '写下周部署稿']) + pageHead('参谋输出', '汇报 · 复盘 · 部署三类稿逐段生成，每个数字可追溯到台账与周报 · 由管理者确认后使用') +
      '<div class="grid2" style="grid-template-columns:220px 1fr;align-items:start"><div><div class="card"><div class="h"><b>稿件类型</b></div><div class="doclist">' + this.KINDS.map(t => '<a data-act="rep-gen" data-k="' + t.k + '"><b>' + h(t.n) + '</b><span>' + (docs['sup-' + t.k] ? '已生成' : '未生成') + '</span></a>').join('') + '</div></div><div class="card" style="margin-top:10px"><div class="h"><b>取数</b></div><div class="note" style="color:var(--ink);line-height:1.6">五类指标热力、风险清单、班长履职、调配记录、星级对标，都是此刻的数；周报第 ' + WK29.no + ' 期指标按原文。</div></div></div>' +
      '<div class="card"><div class="h"><b id="reptitle">稿件</b><span>由管理者确认后使用</span><div class="r" id="repbt"></div></div><div class="doc" id="rephost"><div class="empty">点左边的类型，她当着你的面写</div></div></div></div>'; },
  after() { CH.mount($('#main')); if (S.sub && this.KINDS.some(t => t.k === S.sub)) XW.at(200, () => ACT['rep-gen']({ dataset: { k: S.sub } })); }
};
PAGES.config = {
  MODS: ['今日工作台', '用工安排', '班组画像', '培养与回写', '班组知识库', '台账中心', '部门态势', '全流程俯瞰', '风险与统筹', '班长履职', '人才梯队', '星级对标', '组织效能', '参谋输出', '配置与权限'],
  ROLE_ROWS: [['班组长', '赵立群 · 周建国 · 陈志远', ['写', '写', '写', '写', '写', '写', '—', '—', '确认', '—', '—', '读', '—', '—', '—']], ['管理者', '陈国安', ['读', '读', '读', '读', '读', '读', '写', '读', '写', '读', '写', '写', '读', '写', '写']], ['数据专责', '周小敏', ['—', '—', '读', '—', '—', '写', '读', '读', '—', '—', '—', '读', '读', '—', '写']], ['班员', '本班成员', ['读', '读', '本人', '本人', '写', '本人', '—', '—', '—', '—', '—', '—', '—', '—', '—']]],
  render() { const add = LS.get('teams_add', []); const prof = LS.get('cfg_prof', '配电自动化');
    return cmdHTML(['新增一个班组接入', '配电运维专业用哪套指标', '谁能改五类指标的阈值']) + pageHead('配置与权限', '角色与权限 · 职责与接口一张图 · 班组接入与专业口径 · 指标阈值走三上三下确认') +
      '<div class="card"><div class="h"><b>角色与权限</b><span>写 = 可操作并留名 · 确认 = 结论由其确认 · 本人 = 只看本人</span></div><div class="tbl"><table class="t perm"><tr><th>角色</th><th>人员</th>' + this.MODS.map(m => '<th style="font-size:10px">' + h(m) + '</th>').join('') + '</tr>' + this.ROLE_ROWS.map(r => '<tr><td><b>' + h(r[0]) + '</b></td><td class="note">' + h(r[1]) + '</td>' + r[2].map(x => '<td><span class="tag ' + (x === '写' ? 'ok' : x === '确认' ? 'v' : x === '读' || x === '本人' ? '' : 'dim') + '">' + x + '</span></td>').join('') + '</tr>').join('') + '</table></div></div>' +
      '<div class="grid2"><div class="card"><div class="h"><b>职责与接口 · 一张图</b></div><div class="rmap"><div><b>班组长</b><span>派工、审票、开工、完工、验收</span><span>确认能力 / 资格 / 履职证据结论</span><span>确认或退回跨班组调配</span></div><div><b>管理者</b><span>看三个班组态势与全流程</span><span>识别风险、发督办与提醒</span><span>发起跨班组调配、参谋输出</span></div><div class="arrow">↑ 小瓦特：看、想、写、办，结论由人确认；每一步进操作流水 ↑</div><div><b>台账与系统</b><span>OMS 缺陷与工单 · OCS 终端状态</span><span>电网管理平台两票与计划 · 证书与学时台账</span><span>配网自动化周报（每周导入）</span></div><div><b>数据专责</b><span>核对指标取数字段与来源</span><span>维护台账导入与阈值版本</span><span>指标模型确认记录留档</span></div></div></div>' +
      '<div class="card"><div class="h"><b>班组接入与专业口径</b><span>' + (TEAMS.length + add.length) + ' 个班组</span><div class="r"><button class="s" data-act="cfg-add">新增班组接入</button></div></div><div class="tbl"><table class="t"><tr><th>班组</th><th>专业</th><th>指标模型</th><th>星级评价标准</th><th>核心技能清单</th></tr>' + TEAMS.concat(add).map(t => '<tr><td><b>' + h(t.n) + '</b><br><span class="note">' + h(t.leader) + ' · ' + t.size + ' 人</span></td><td>' + h(t.prof) + '</td><td class="note">五类 15 项（V1，' + CONFIRM_LOG[3].d + ' 全员确认）</td><td class="note">' + (t.prof === '配电自动化' ? '配电自动化专业分册 · 8 项 + ' + STAR_BUILD.length + ' 条' : t.prof === '配电运维' ? '配电运维专业 · 9 项指标 + 建设工作目录' : '电气试验 · 按部门口径') + '</td><td class="note">' + (t.prof === '配电自动化' ? '九类核心技能' : t.prof === '电气试验' ? '八类试验项目' : '九类核心技能（配电运维）') + '</td></tr>').join('') + '</table></div>' +
      '<div class="note" style="margin:8px 0 4px">五类指标阈值</div><div class="tbl"><table class="t"><tr><th>指标</th><th>阈值</th><th>责任</th></tr>' + FIVE.map(f => f.items.map(it => '<tr><td>' + h(f.n) + ' · ' + h(it.n) + '</td><td class="note">' + h(it.th) + '</td><td class="note">' + h(it.who) + '</td></tr>').join('')).join('') + '</table></div><div class="bt"><button class="g" data-act="five-log">看指标确认记录</button></div></div></div>'; },
  after() { CH.mount($('#main')); }
};
/* ---------- 动作 ---------- */
Object.assign(ACT, {
  'sup-team'(el) { const n = el.dataset.n; const t = SUPER.teams().find(x => x.n === n); if (!t) return; XW.answer(n + '：' + t.size + ' 人，班长' + t.leader + '。五类里' + (t.five.filter(f => f.st === 'bad').length ? '待治理的是' + t.five.filter(f => f.st === 'bad').map(f => f.n).join('、') + '，' : '') + (t.five.filter(f => f.st === 'warn').length ? '要关注的是' + t.five.filter(f => f.st === 'warn').map(f => f.n).join('、') + '。' : '其余稳健。') + (n === TEAM.name ? '明细在班组画像里。' : '明细要班长' + t.leader + '授权后看。'), null, { confirm: false, done() { if (n === TEAM.name) XW.card('<div class="bt" style="margin-top:0"><button class="g" data-act="nav" data-to="people">进班组画像</button></div>'); } }); },
  'sup-cell'(el) { const t = SUPER.teams().find(x => x.n === el.dataset.n); const f = t && t.five.find(x => x.k === el.dataset.k); if (!f) return;
    XW.spot({ title: t.n + ' · ' + f.n + '（' + SUPER.stName(f.st) + '）', cols: ['指标', '现在', '阈值', '责任'], rows: f.items.map(it => [it.n, it.val, it.th, it.who || (t.n === TEAM.name ? '班组长' : t.leader)]), me: f.items.map((it, i) => i), text: t.n + '的' + f.n + '是' + SUPER.stName(f.st) + '：' + f.items.map(it => it.n + ' ' + it.val + '（阈值 ' + it.th + '）').join('，') + '。' + (f.st !== 'ok' ? '治理动作在风险与统筹里，责任人是' + t.leader + '。' : '') });
    XW.at(900, () => XW.card('<div class="bt" style="margin-top:0">' + (t.n === TEAM.name ? '<button class="g" data-act="nav" data-to="people">看班组画像</button>' : '') + (f.st !== 'ok' ? '<button data-act="nav" data-to="risk">去治理</button>' : '') + '</div>')); },
  'sup-wk'(el) { SUPER.wk = el.dataset.k; const it = WK29.item(SUPER.wk); $$('[data-act="sup-wk"]').forEach(b => { b.style.cssText = b.dataset.k === SUPER.wk ? 'background:var(--tint);color:var(--pri);border-color:#c9cbf5' : ''; }); const host = $('#supwk'); if (host) { host.innerHTML = LEDGERPG.wkChart(SUPER.wk) + CH.mini.legend([{ n: '光明', c: CPAL[1] }, { n: '其他区局', c: CPAL[0] }]) + '<div class="note" style="margin-top:4px">' + h(it.n) + '：光明 ' + it.vals[WK29.gm()] + it.unit + '，全市 ' + it.total + it.unit + '，第 ' + WK29.rank(it.k) + ' 名。' + h(it.detail) + '</div>'; CH.mount(host); } XW.answer(it.n + '光明 ' + it.vals[WK29.gm()] + it.unit + '，全市第 ' + WK29.rank(it.k) + '。' + it.detail + '。', null, { confirm: false, speak: false }); },
  'sup-flow'(el) { const k = el.dataset.k; const jobs = DB.jobs().filter(j => j.st !== '已删除'); const map = {
      task: () => XW.spot({ title: '任务 · ' + TEAM.name, cols: ['任务', '状态', '人员'], rows: jobs.map(j => [j.t, j.st, DB.crewOf(j).join('、') || '待派']), me: jobs.map((j, i) => j.st === '待派' ? i : -1).filter(i => i >= 0), text: '任务 ' + jobs.length + ' 项，待派的照亮了。' }),
      dispatch: () => { const d = Object.values(LS.get('dispatch', {})); XW.spot({ title: '派工记录', cols: ['任务', '负责人', '班员', '理由'], rows: d.map(r => [r.t, r.lead, (r.crew || []).join('、'), (r.reasons || []).slice(0, 2).join('；')]), me: d.map((r, i) => i), text: d.length ? '本周派工 ' + d.length + ' 单，推荐和排除的理由都随单存了。' : '这周班组长还没派工；田寮站验收派了就会出现在这里。' }); },
      ticket: () => { const tk = DB.tickets(); XW.spot({ title: '两票', cols: ['票号', '任务', '负责人', '状态'], rows: tk.map(t => [t.no, t.task, t.lead, t.st]), me: tk.map((t, i) => t.st === '待审' ? i : -1).filter(i => i >= 0), text: '两票 ' + tk.length + ' 张，待审的照亮了。' }); },
      start: () => XW.spot({ title: '开工与在场', cols: ['任务', '状态', '人员'], rows: jobs.filter(j => /进行中|已完成|已关闭/.test(j.st)).map(j => [j.t, j.st, DB.crewOf(j).join('、')]), me: jobs.filter(j => /进行中|已完成|已关闭/.test(j.st)).map((j, i) => j.st === '进行中' ? i : -1).filter(i => i >= 0), text: '开过工的任务，在现场的照亮了。' }),
      report: () => { const g = DB.progressAll(); XW.spot({ title: '现场回传', cols: ['任务', '进度', '累计小时', '最近一条'], rows: g.map(x => [x.t, x.pct + '%', x.hrs, x.ev.length ? x.ev[x.ev.length - 1][2] : '—']), me: g.map((x, i) => x.warn ? i : -1).filter(i => i >= 0), text: '现场回传 ' + g.reduce((s, x) => s + x.ev.length, 0) + ' 条，连续超 3 小时的组照亮了。' }); },
      finish: () => { const H = DB.hours().filter(r => r.added); XW.spot({ title: '完工记工时', cols: ['日期', '人员', '作业', '小时'], rows: H.map(r => [r.d, r.who, r.job, r.h]), me: H.map((r, i) => i), sumCol: 3, unit: 'h', text: H.length ? '今天完工记了 ' + H.length + ' 条工时。' : '今天还没有完工记录。' }); },
      write: () => { const sw = DB.skillWrites(); XW.spot({ title: '实操量回写', cols: ['时间', '核心技能', '人员', '任务'], rows: sw.map(w => [w.d, (SKILL9.find(s => s.k === w.k) || { n: w.k }).n, w.who.join('、'), w.job]), me: sw.map((w, i) => i), text: sw.length ? '回写 ' + sw.length + ' 条，对应人的画像实操次数已加。' : '还没有回写；任务完工就会有。' }); },
      profile: () => ensure('people'),
      grow: () => { const plan = LS.get('plan', []); XW.spot({ title: '培养在办', cols: ['人员', '内容', '时间'], rows: MENTORS.map(m => [m.s, '师带徒 · ' + m.m + ' · ' + m.focus, m.since + ' 起']).concat(plan.map(p => [p.who, p.t, p.when])), me: plan.map((p, i) => MENTORS.length + i), text: '师带徒 ' + MENTORS.length + ' 对，新增培养计划 ' + plan.length + ' 项。' }); } };
    (map[k] || map.task)(); },
  'sup-urge'(el) { const sent = LS.get('sup_sent', {}); sent[el.dataset.id] = DB.now(); LS.set('sup_sent', sent); DB.notify('赵立群', '督办：华发民公用柜 电容故障已超期，请今日闭环并回传（' + TEAM.dept + '）', '已读', true); DB.log('督办', '华发民公用柜 电容故障 → 赵立群'); XW.fly('督办已发 · 赵立群'); const host = $('#riskbody'); if (host) { host.innerHTML = PAGES.risk.body(); CH.mount(host); } XW.answer('督办发给赵立群了，他那边今日工作台的催办卡会亮；闭环后这条自动消掉。', null, { confirm: false }); },
  'sup-notify'(el) { const sent = LS.get('sup_sent', {}); sent[el.dataset.id] = DB.now(); LS.set('sup_sent', sent); DB.notify(el.dataset.who, el.dataset.arg + '（' + TEAM.dept + '）', '已读', true); DB.log('提醒', el.dataset.arg + ' → ' + el.dataset.who); XW.fly('提醒已发 · ' + el.dataset.who); const host = $('#riskbody'); if (host) { host.innerHTML = PAGES.risk.body(); CH.mount(host); } XW.answer('发给' + el.dataset.who + '了：' + el.dataset.arg + '。', null, { confirm: false }); },
  'sim-from'(el) { const from = el.value; const who = $('#sm-who'); if (who) who.innerHTML = SUPER.peopleOf(from).map(n => '<option>' + h(n) + '</option>').join(''); },
  'sim-run'() { SUPER.simState = SUPER.readSim(); const host = $('#riskbody'); if (host) { host.innerHTML = SUPER.simHTML(); CH.mount(host); } ACT['sim-say'](); },
  'sim-say'() { const f = SUPER.simState; if (!f) return; const imp = SUPER.simImpact(f); XW.answer(f.who + '从' + f.from + '借到' + f.to + ' ' + f.days + ' 天：' + (imp.ok ? '证书够、工时在约定内、借出班组下限仍满足，可以发起，等两位班长确认。' : imp.warns.join('；') + '。' + (imp.alt ? '同班里' + imp.alt.n + '有电缆证、本周 ' + imp.alt.wk + ' 小时，改借他更稳。' : '')), null, { confirm: false }); },
  'sim-alt'(el) { SUPER.simState = Object.assign(SUPER.readSim(), { who: el.dataset.who }); const host = $('#riskbody'); if (host) { host.innerHTML = SUPER.simHTML(); CH.mount(host); } ACT['sim-say'](); },
  'sim-go'() { const f = SUPER.readSim(); const imp = SUPER.simImpact(f); const t = DB.addTransfer({ from: f.from, to: f.to, who: f.who, days: f.days, start: f.start, why: f.why, d: DB.now(), warns: imp.warns }); const leaders = { [TEAM.name]: '赵立群', [LAB.name]: LAB.leader, [TEAM3.name]: TEAM3.leader }; [leaders[f.from], leaders[f.to]].forEach(n => DB.notify(n, '跨班组调配待确认：' + f.who + ' ' + f.from + ' → ' + f.to + '，' + f.start + ' 起 ' + f.days + ' 天', '已读', true)); DB.log('跨班组调配', f.who + ' ' + f.from + ' → ' + f.to + ' ' + f.days + ' 天，待 ' + leaders[f.from] + '、' + leaders[f.to] + ' 确认'); XW.fly('调配已发起 · 待 ' + leaders[f.from] + ' · ' + leaders[f.to] + ' 确认'); SUPER.simState = null; badgeSync(); const host = $('#riskbody'); if (host) { host.innerHTML = SUPER.simHTML(); CH.mount(host); } XW.answer('发起了，' + leaders[f.from] + '和' + leaders[f.to] + '各收到一条待确认。' + (imp.warns.length ? '我把冲突写在单子上了：' + imp.warns.join('；') + '，班长可以改人选或天数。' : '') + '确认后工时记回本人，实操量回写本人画像。', null, { confirm: false, done() { XW.card('<div class="bt" style="margin-top:0"><button class="g" data-act="nav" data-to="flow">看全流程里的待确认</button></div>'); } }); },
  'tr-remind'(el) { const t = DB.transfers().find(x => x.id === el.dataset.id); if (!t) return; DB.notify(t.to === TEAM.name ? '赵立群' : t.to === LAB.name ? LAB.leader : TEAM3.leader, '调配待确认：' + t.who + ' ' + t.from + ' → ' + t.to, '已读', true); XW.fly('已催 · ' + t.who + ' 的调配'); XW.answer('催了一次，班长那边用工安排里能看到。', null, { confirm: false }); },
  'tr-ok'(el) { const t = DB.transfers().find(x => x.id === el.dataset.id); if (!t) return; DB.setTransfer(t.id, '已确认', { by: '赵立群', note: '确认人 赵立群' }); DB.notify('陈国安', '调配已确认：' + t.who + ' ' + t.from + ' → ' + t.to + '（' + t.days + ' 天）', '已读', true); XW.fly('调配已确认 · ' + t.who); badgeSync(); if (S.page === 'sched') SCHEDPG.draw(); else if (S.page === 'home') render(); XW.answer('确认了：' + t.who + ' ' + t.start + ' 起到本班 ' + t.days + ' 天。' + (t.to === TEAM.name ? '下周一田寮站验收派工时，他会出现在候选里，资格按' + t.from + '的证书台账算。' : '') + '工时记回本人，实操量回写本人画像。', null, { confirm: false }); },
  'tr-back'(el) { const t = DB.transfers().find(x => x.id === el.dataset.id); if (!t) return; DB.setTransfer(t.id, '已退回', { by: '赵立群', note: '退回：本周' + (t.who) + '工时已满，建议改借期或换人' }); DB.notify('陈国安', '调配已退回：' + t.who + '，理由见单', '已读', true); XW.fly('调配已退回 · ' + t.who, 'w'); badgeSync(); if (S.page === 'sched') SCHEDPG.draw(); else if (S.page === 'home') render(); XW.answer('退回了，理由写在单上：本周' + t.who + '工时已满，建议改借期或换人。管理者那边会看到。', null, { confirm: false }); },
  'sup-duty'(el) { const r = SUPER.dutyRows().find(x => x.who === el.dataset.who); const m = r && r.m.find(x => x.k === el.dataset.k); if (!m) return; XW.answer(r.who + '的「' + m.n + '」：' + m.v + '，' + (m.ok ? '达标' : '未达') + '，来源' + m.src + '。' + (r.team === TEAM.name ? '数就是他工作台此刻的数。' : '数按' + r.team + '的台账。'), null, { confirm: false, done() { if (r.team === TEAM.name) XW.card('<div class="bt" style="margin-top:0"><button class="g" data-act="nav" data-to="ledger" data-sub="' + ({ dispatch: 'dispatch', ticket: 'ticket', node: 'task', defect: 'defect', load: 'hours', grow: 'train', evid: 'task' }[m.k] || 'task') + '">看台账</button></div>'); } }); },
  'sup-remind'(el) { const r = SUPER.dutyRows().find(x => x.who === el.dataset.who); if (!r) return; const bad = r.m.filter(x => !x.ok); DB.notify(r.who, '履职提醒：' + (bad.map(x => x.n + ' ' + x.v).join('、') || '本周各项达标') + '（' + TEAM.dept + '）', '已读', true); DB.log('履职提醒', r.who + '：' + (bad.map(x => x.n).join('、') || '达标')); XW.fly('提醒已发 · ' + r.who); XW.answer((bad.length ? '发给' + r.who + '了：' + bad.map(x => x.n + ' ' + x.v).join('、') + '。' : r.who + '这周各项都达标，发了一条肯定。') + '不排名，只提醒本人。', null, { confirm: false }); },
  'tal-plan'(el) { const x = SUPER.talentPlan()[+el.dataset.i]; if (!x) return; const plan = LS.get('plan', []); x.who.split(' · ').forEach(n => plan.push({ who: n, t: x.t, when: x.when, ts: Date.now(), by: '管理者建议' })); LS.set('plan', plan); const done = LS.get('sup_talent', {}); done[el.dataset.i] = '已排 ' + x.when; LS.set('sup_talent', done); DB.log('梯队建议', x.who + '：' + x.t); XW.fly('已排进培养计划 · ' + x.who); if (S.page === 'talent') { $('#talbody').innerHTML = PAGES.talent.body(); CH.mount($('#talbody')); } XW.answer('排进' + TEAM.name + '的培养计划了：' + x.who + '，' + x.t + '，' + x.when + '。班组长在培养与回写里能看到、能改。', null, { confirm: false }); },
  'tal-notify'(el) { const x = SUPER.talentPlan()[+el.dataset.i]; if (!x) return; DB.notify(LAB.leader, '梯队建议：' + x.who + ' ' + x.t + '（' + TEAM.dept + '）', '已读', true); const done = LS.get('sup_talent', {}); done[el.dataset.i] = '已发 ' + LAB.leader; LS.set('sup_talent', done); DB.log('梯队建议', x.who + '：' + x.t + ' → ' + LAB.leader); XW.fly('已发给 ' + LAB.leader); if (S.page === 'talent') { $('#talbody').innerHTML = PAGES.talent.body(); CH.mount($('#talbody')); } XW.answer('发给' + LAB.leader + '了：' + x.who + '，' + x.t + '。人选由他定。', null, { confirm: false }); },
  'tal-cert'(el) { const k = el.dataset.k || '电力电缆作业证'; const c = SUPER.certByTeam().find(x => x.k === k); if (!c) return; const lack = c.t.filter(x => x.v < x.need); XW.answer(k + '：' + c.t.map(x => x.n + ' ' + x.v + '/' + x.need).join('、') + '。' + (lack.length ? lack.map(x => x.n + '缺 ' + (x.need - x.v) + ' 人').join('，') + '。' + (k === '电力电缆作业证' ? '短期靠两个班互借顶田寮站交接试验，长期 10 月取证批次。' : '按缺口排取证。') : '三个班组都到下限。'), null, { confirm: false, chart: CH.mini.cols(c.t.map((x, i) => ({ n: x.n.replace('配电', ''), v: x.v, c: x.v < x.need ? '#e5484d' : CPAL[i], tip: x.n + ' ' + x.v + '/' + x.need })), { max: 13, h: 100, labels: true }), done() { if (lack.length) XW.card('<div class="bt" style="margin-top:0"><button data-act="nav" data-to="risk" data-sub="sim">去发起调配</button><button class="g" data-act="nav" data-to="people">看班组画像取证计划</button></div>'); } }); },
  'star-row'(el) { const s = SUPER.star8()[+el.dataset.i]; if (!s) return; XW.answer(s.n + '：当前 ' + s.v + (s.r ? '，全市第 ' + s.r : '') + '，评分 ' + s.sc + '，权重 ' + s.w + '，加权 ' + s.wsc + '。评分标准：' + s.std.slice(0, 60) + '……查评方法：' + s.method.slice(0, 60) + '。取数：' + s.src + '。', null, { confirm: false, speak: false }); },
  'star-gap'() { const S8 = SUPER.star8().slice().sort((a, b) => a.sc - b.sc); const low = S8.slice(0, 3); const B = STAR_BUILD.map(b => ({ b, c: SUPER.buildCheck(b) })).filter(x => x.c && !x.c.ok);
    XW.state('write'); const d = XW.msg('a', '星级对标差距清单：<div class="draft"><span></span></div>'); XW.type(d.querySelector('.draft span'), '一、指标差距（加权 ' + SUPER.starTotal() + ' 分）：\n' + low.map((s, i) => (i + 1) + '. ' + s.n + '：当前 ' + s.v + (s.r ? '（全市第 ' + s.r + '）' : '') + '，评分 ' + s.sc + '；对应关键节点由班组长周清。').join('\n') + '\n二、建设工作未达标（本班台账可查）：\n' + (B.length ? B.map((x, i) => (i + 1) + '. ' + x.b.n + '：' + x.c.v).join('\n') : '无') + '\n三、动作：排名靠后指标对应的关键节点列入周计划重点；未达标条目责任到班长，下次对标前复核。\n以上由管理者确认后使用。', 22, () => { XW.state(''); d.insertAdjacentHTML('beforeend', '<div class="bt"><button data-act="rep-gen" data-k="brief">写进部门周汇报</button><button class="g" data-act="nav" data-to="ledger" data-sub="weekly">看周报台账</button></div>'); }); },
  'star-prof'(el) { SUPER.starProf = el.dataset.p; const host = $('#starbody'); if (host) { host.innerHTML = SUPER.starHTML(); CH.mount(host); } XW.answer(SUPER.starProf === 'om' ? '切到配电运维专业口径了：9 项评价指标和建设工作目录，数值按配电运维一班台账。' : '切回配电自动化专业了：8 项指标加权 ' + SUPER.starTotal() + ' 分，' + STAR_BUILD.length + ' 条建设工作逐条对照。', null, { confirm: false, speak: false }); },
  'rep-gen'(el) { const k = el.dataset.k || 'brief'; if (S.page !== 'report') { ensure('report', () => ACT['rep-gen']({ dataset: { k } })); return; } const t = PAGES.report.KINDS.find(x => x.k === k); $$('.doclist a').forEach(a => a.classList.toggle('on', a.dataset.k === k)); $('#reptitle').textContent = t.n; const host = $('#rephost'); DOCS.host = host; DOCS.kind = null;
    DOCGEN.stream(host, SUPER.repParas(k), { title: t.n + ' · ' + TODAY, chips: [{ k: 'short', n: '口气再简短些' }], done: () => { const docs = LS.get('docs', {}); docs['sup-' + k] = { t: t.n, ts: Date.now(), body: DOCGEN.text(host) }; LS.set('docs', docs); DB.log('参谋输出', t.n); $('#repbt').innerHTML = '<button data-act="doc-export">导出 / 打印</button><button class="g" data-act="rep-send">发给三位班长</button>'; XW.answer(t.n + '写好了，每个数都是此刻台账和周报里的；哪段不合适点芯片改那一段。', null, { speak: false, confirm: false }); } }); },
  'rep-send'() { ['赵立群', LAB.leader, TEAM3.leader].forEach(n => DB.notify(n, ($('#reptitle') ? $('#reptitle').textContent : '稿件') + '（' + TEAM.dept + '）', '已读', true)); DB.log('参谋输出', '发给三位班长'); XW.fly('已发送 · 三位班长'); XW.answer('发给三位班长了，他们在通知里能看到。', null, { confirm: false }); },
  'cfg-add'() { modal('<div class="t">新增班组接入</div><div class="jf" id="cfgf"><label>班组名称</label><input id="cf-n" class="wide" placeholder="如 配电运维二班"><label>专业</label><select id="cf-p"><option>配电自动化</option><option>配电运维</option><option>电气试验</option></select><label>班长</label><input id="cf-l" placeholder="姓名"><label>人数</label><input id="cf-s" type="number" min="3" max="30" value="10"><label>接入台账</label><div class="chk wide"><label><input type="checkbox" checked disabled>人员名册</label><label><input type="checkbox" checked disabled>证书台账</label><label><input type="checkbox" checked>OMS 缺陷与工单</label><label><input type="checkbox" checked>电网管理平台两票</label><label><input type="checkbox">配网自动化周报</label></div></div><div class="bt"><button data-act="cfg-add-ok">接入</button></div>'); },
  'cfg-add-ok'() { const n = ($('#cf-n') || {}).value || ''; if (n.trim().length < 2) { XW.answer('班组名称要写。', null, { confirm: false }); return; } const add = LS.get('teams_add', []); add.push({ n: n.trim(), prof: $('#cf-p').value, leader: ($('#cf-l').value || '待定'), size: +$('#cf-s').value || 10 }); LS.set('teams_add', add); DB.log('配置', '新增班组接入：' + n.trim()); $('#modal').hidden = true; render(); XW.answer(n.trim() + '接入了，专业' + $('#cf-p') ? add[add.length - 1].prof : '' + '，指标模型用五类 15 项，星级标准按专业分册。台账导入由数据专责在台账中心配置。', null, { confirm: false }); }
});
