/* ===== 任务流转：任务池每一行的按钮（派工 → 审票 → 开工 → 回传 → 完工 → 验收关闭 → 实操量回写）、添加任务表单、上传两票（真实读文件、逐条审核、补齐或退回） ===== */
const TASKS = {
  row(j) { const tk = j.ticketNo ? DB.ticket(j.ticketNo) : null; const who = DB.crewOf(j); const st = j.st; const tag = st === '已派' ? (tk && /已审核|已签发/.test(tk.st) ? 'ok' : 'w') : /进行中/.test(st) ? 'c' : /已完成|已关闭|票已审/.test(st) ? 'ok' : j.lv === '超期' || j.lv === '紧急' ? 'bad' : '';
    const node = j.node ? NODES.find(n => n.id === j.node) : null;
    return '<div class="job' + (j.added ? ' add' : '') + (j.id === MAINLINE ? ' main' : '') + '" data-id="' + j.id + '"><span style="color:var(--ink);font-size:11.5px;white-space:normal">' + h(j.t) + (j.added ? ' <i class="tag v">新</i>' : '') + (j.lv ? ' <em>' + h(j.lv) + '</em>' : '') + '<br><span class="note">' + h(j.when) + (who.length ? ' · ' + h(who.join(' ')) : '') + (node ? ' · <i class="tag n">' + h(node.cyc) + '</i>' : '') + (j.src ? ' · ' + h(j.src) : '') + (tk ? ' · ' + h(tk.no) + ' <b class="tag ' + (/已审核|已签发|已执行/.test(tk.st) ? 'ok' : tk.st === '已退回' ? 'bad' : 'w') + '">' + h(tk.st) + '</b>' : '') + '</span></span><span class="ops"><b class="tag ' + tag + '">' + h(st) + '</b>' + this.btns(j, tk) + '</span></div>'; },
  btns(j, tk) { const st = j.st; const b = (act, n, g) => '<button' + (g ? ' class="g"' : '') + ' data-act="' + act + '" data-id="' + j.id + '">' + n + '</button>'; let s = '';
    if (st === '待派') s += b('pool-dispatch', '派工'); else if (st === '已派' || st === '票已审' || st === '待开工') { s += b('job-start', '开工'); if (tk && !/已审核|已签发|已执行/.test(tk.st)) s += b('job-ticket', '去审票', true); } else if (st === '进行中') s += b('job-report', '回传一条', true) + b('job-finish', '完工'); else if (st === '已完成') s += b('job-close', DB.linkedDefect(j) ? '验收关闭' : '关闭'); else if (st === '待安排') s += '<button class="g" data-act="nav" data-to="sched" data-sub="week">去安排</button>';
    if (j.added && /待派|已派/.test(st)) s += b('job-edit', '改', true) + b('job-del', '删', true); return s; },
  redraw() { if (S.page === 'sched') SCHEDPG.draw(); else if (S.page === 'home' || S.page === 'flow') render(); badgeSync(); }
};

/* ---------- 添加任务：表单 + 校验 + 她按名称帮填 + 保存进任务池 / 周计划 / 今日作业 / 任务台账 ---------- */
const TASKFORM = {
  id: null, LINES: ['田寮站 F02', '玉律片区', '楼村片区', '光侨路', '东明大道', '民生站 F03', '主站', '全区', '其他'], TYPES: ['建设', '消缺', '维护', '专项', '试验验收', '培训', '其他'], NEEDS: ['电力电缆作业证', '继电保护作业资格', '登高架设作业证', '工作负责人资格'],
  opts(list, cur) { return list.map(x => '<option' + (x === cur ? ' selected' : '') + '>' + h(x) + '</option>').join(''); },
  html(j) { j = j || {}; const need = j.need || []; const defs = DB.defects().filter(d => !/已关闭|已消缺|已撤销|已验证/.test(d.st));
    return '<div class="card" id="jobnew"><div class="h"><b>' + (j.id ? '修改任务' : '添加任务') + '</b><span>她按名称帮你填，你改，保存进任务池</span><div class="r"><button class="s g" data-act="job-assist">让她帮我填</button></div></div><div class="jf" id="jf">' +
      '<label>任务名称</label><input id="jf-t" class="wide" placeholder="站点 / 片区 + 设备 + 作业内容" value="' + h(j.t || '') + '">' +
      '<label>类型</label><select id="jf-type">' + this.opts(this.TYPES, j.type) + '</select><label>站点 / 片区</label><select id="jf-line">' + this.opts(this.LINES, j.line) + '</select>' +
      '<label>日期</label><input type="date" id="jf-date" min="' + TODAY + '" value="' + h(j.dateIso || '') + '"><label>时间</label><input type="time" id="jf-time" value="' + h(j.time || '09:00') + '">' +
      '<label>预计工时</label><input type="number" id="jf-h" min=".5" max="12" step=".5" value="' + (j.h || '') + '" placeholder="每人小时"><label>工作票</label><select id="jf-ticket">' + this.opts(['不需要', '第一种工作票', '第二种工作票', '操作票'], j.ticket || '不需要') + '</select>' +
      '<label>资质要求</label><div class="chk wide"><label><input type="checkbox" checked disabled>高压电工作业证</label>' + this.NEEDS.map(c => '<label><input type="checkbox" class="jf-need" value="' + c + '"' + (need.includes(c) ? ' checked' : '') + '>' + c + '</label>').join('') + '</div>' +
      '<label>核心技能</label><select id="jf-skill"><option value="">不对应</option>' + SKILL9.map(s => '<option value="' + s.k + '"' + (j.skill === s.k ? ' selected' : '') + '>' + h(s.n) + '</option>').join('') + '</select><label>风险等级</label><select id="jf-lv">' + this.opts(['低', '中', '高'], j.risk || '低') + '</select>' +
      '<label>关联缺陷</label><select id="jf-def" class="wide"><option value="">无</option>' + defs.map(d => '<option value="' + d.id + '"' + (j.defectId === d.id ? ' selected' : '') + '>' + h(d.t.length > 26 ? d.t.slice(0, 26) + '…' : d.t) + '</option>').join('') + '</select>' +
      '<label>说明</label><textarea id="jf-desc" class="wide" rows="2" placeholder="安措要点、注意事项">' + h(j.desc || '') + '</textarea>' +
      '<div class="err" id="jf-err"></div><div class="btnrow bt"><button data-act="job-save">保存</button><button data-act="job-save" data-go="1">保存并立即派工</button><button class="g" data-act="job-cancel">取消</button></div></div></div>'; },
  open(id) { this.id = id || null; const j = id ? DB.job(id) : null; const host = $('#jobhost'); if (!host) return; host.innerHTML = this.html(j); host.scrollIntoView({ block: 'nearest' }); const t = $('#jf-t'); if (t && !id) t.focus(); XW.answer(id ? '改哪一项直接改，保存后任务池、周计划和台账一起更新。' : '任务名称写清站点、设备和作业内容。其他的不想填就点「让她帮我填」，我按名称猜，猜错你改。核心技能选上，完工后实操量自动回写到画像。', null, { confirm: false, speak: false }); },
  close() { const host = $('#jobhost'); if (host) host.innerHTML = ''; this.id = null; },
  v(sel) { const e = $(sel); return e ? e.value : ''; },
  read() { return { t: this.v('#jf-t').trim(), type: this.v('#jf-type'), line: this.v('#jf-line'), dateIso: this.v('#jf-date'), time: this.v('#jf-time') || '09:00', h: +this.v('#jf-h'), ticket: this.v('#jf-ticket'), need: $$('.jf-need:checked').map(c => c.value), skill: this.v('#jf-skill'), risk: this.v('#jf-lv'), defectId: this.v('#jf-def'), desc: this.v('#jf-desc').trim() }; },
  validate(d) { const errs = [], warns = []; $$('#jf .bad').forEach(e => e.classList.remove('bad')); const bad = (sel, m) => { errs.push(m); const e = $(sel); if (e) e.classList.add('bad'); }; const tick = c => { if (!d.need.includes(c)) { d.need.push(c); const x = $$('.jf-need').find(x => x.value === c); if (x) { x.checked = true; x.parentElement.classList.add('fill'); } } };
    if (d.t.length < 4) bad('#jf-t', '任务名称至少写清站点和作业内容'); if (!d.dateIso) bad('#jf-date', '要有作业日期'); else if (d.dateIso < TODAY) bad('#jf-date', '日期不能早于今天'); if (!(d.h >= .5 && d.h <= 12)) bad('#jf-h', '预计工时填 0.5 到 12 小时');
    if (/试验|验收|更换|检修|定检/.test(d.t) && d.ticket === '不需要') { d.ticket = '第一种工作票'; const e = $('#jf-ticket'); if (e) { e.value = d.ticket; e.classList.add('fill'); } warns.push('这类作业要停电，我把工作票改成了第一种'); }
    if (/杆|FTU|柱上/.test(d.t) && !d.need.includes('登高架设作业证')) { tick('登高架设作业证'); warns.push('柱上作业要登杆，勾上了登高架设作业证'); }
    if (/电缆/.test(d.t) && !d.need.includes('电力电缆作业证')) { tick('电力电缆作业证'); warns.push('涉及电缆，勾上了电力电缆作业证'); }
    if (/保护|定检|定值/.test(d.t) && !d.need.includes('继电保护作业资格')) { tick('继电保护作业资格'); warns.push('保护类作业勾上了继电保护作业资格'); }
    if (d.ticket === '第一种工作票') tick('工作负责人资格');
    if (/杆|FTU|柱上/.test(d.t) && (d.dateIso === TODAY || d.dateIso === '2026-08-08')) warns.push('今明两天有雷阵雨，柱上作业等雨停再上');
    return { errs, warns }; },
  guess(t) { const g = { t }; g.type = /验收|试验/.test(t) ? '试验验收' : /排查|整改|专项|批量/.test(t) ? '专项' : /投运|光纤|审图|调试|新建/.test(t) ? '建设' : /消缺|故障|异常|失败|缺陷|卡涩|锈蚀|投退/.test(t) ? '消缺' : /培训|考|安全日/.test(t) ? '培训' : '维护'; g.line = (t.match(/田寮站 F02|玉律片区|楼村片区|光侨路|东明大道|民生站 F03|主站|全区/) || [/柜/.test(t) ? '其他' : '其他'])[0]; const climb = /杆|FTU|柱上/.test(t); const cab = /柜|站|终端|DTU|交换机|蓄电池|电源|环网/.test(t); const remote = /主站|在线率|信号|定值|遥信|遥控验证/.test(t);
    g.ticket = /试验|验收|更换|检修|定检/.test(t) ? '第一种工作票' : cab || climb ? '第二种工作票' : '不需要'; if (remote && !cab && !climb) g.ticket = '不需要'; g.need = climb ? ['登高架设作业证'] : []; if (g.ticket === '第一种工作票') g.need.push('工作负责人资格'); if (/电缆/.test(t)) g.need.push('电力电缆作业证'); if (/保护|定检|定值/.test(t)) g.need.push('继电保护作业资格');
    g.skill = /FTU|柱上/.test(t) ? 's1' : /验收/.test(t) ? 's2' : /DTU|配电房/.test(t) ? 's3' : /定检/.test(t) ? 's4' : /定值/.test(t) ? 's5' : /巡视|巡检|信号|投退/.test(t) ? 's6' : /动作分析|故障定位|跳闸/.test(t) ? 's7' : /自愈|复电/.test(t) ? 's8' : /消缺|排查|维护|更换|投运|故障|失败/.test(t) ? 's9' : ''; const sn = g.skill ? SKILL9.find(s => s.k === g.skill).n : '';
    g.h = g.type === '试验验收' ? 8 : g.type === '建设' ? 6 : g.type === '专项' ? 4 : g.type === '消缺' ? 3 : g.type === '维护' ? 4 : 2; g.risk = climb && g.ticket === '第一种工作票' ? '高' : climb || cab ? '中' : '低'; g.dateIso = g.type === '消缺' ? '2026-08-10' : '2026-08-11'; g.time = '09:00';
    const key = (t.match(/[一-龥]+(?:\s*\d+#)?\s*公用柜|[一-龥]+站 F\d+/) || [''])[0].replace(/\s/g, ''); const d = key && DB.defects().find(x => !/已关闭|已验证|已撤销/.test(x.st) && x.t.replace(/\s/g, '').includes(key)); g.defectId = d ? d.id : '';
    g.desc = climb ? '登杆前检查杆根、拉线；验电后装设接地线并写明位置；作业照片回传。' : cab ? '开关分闸、验电后作业；柜前设围栏；二次回路作业先用万用表复核电源。' : remote ? '主站侧操作先核对设备名称、编号，遥控前后遥信位置对得上；截图回传。' : '作业前核对设备名称、编号；照片回传。';
    g.why = '"' + t + '"：' + (climb ? '柱上作业，要登杆，得有登高证' : cab ? '柜内或站内作业，不登杆' : remote ? '主站侧作业' : '不登杆') + '；' + (g.ticket === '不需要' ? '不用票' : g.ticket === '第一种工作票' ? '要停电，第一种工作票，负责人要有资格' : '不停电，第二种工作票') + '；' + g.type + '一般 ' + g.h + ' 小时；' + (g.type === '消缺' ? '缺陷类的排下周一' : '排下周二') + '。' + (sn ? '对应核心技能「' + sn + '」，完工后实操量回写。' : '') + (g.defectId ? '台账里有对应的缺陷，我关联上。' : ''); return g; },
  sample() { return { t: '光侨路 3# 公用柜 频繁投退处理（十五类异常信号）', type: '消缺', line: '光侨路', dateIso: '2026-08-10', time: '09:00', h: 3, ticket: '第二种工作票', need: [], skill: 's6', risk: '中', defectId: 'd8', desc: '先查遥信回路和终端定值，再查一次机构；处理完在主站核对信号不再频繁投退，截图回传关闭缺陷。', why: '名称是空的，我挑一件该排还没排的：主站站端巡检 8-4 报的光侨路 3# 公用柜频繁投退，十五类异常信号里的一项，周报要求周周清，这周还没清。柜内作业，第二种工作票，三个小时，对应核心技能「配电自动化设备巡视」。' }; },
  assist() { if (!$('#jf')) return; const cur = this.v('#jf-t').trim(); const g = cur.length >= 4 ? this.guess(cur) : this.sample(); const set = (sel, val, ms) => { const e = $(sel); if (!e) return; XW.cursorTo(e, 20, 8); if (e.tagName === 'SELECT') { e.value = val; e.classList.add('fill'); } else XW.fill(e, String(val), ms || 26); };
    XW.state('think'); XW.think(g.why, () => { XW.state('work', '正在填表'); let k = 0; const step = (fn, gap) => { XW.at(k, fn); k += gap || 650; };
      if (!cur) step(() => set('#jf-t', g.t, 34), 1600); step(() => set('#jf-type', g.type)); step(() => set('#jf-line', g.line)); step(() => set('#jf-date', g.dateIso)); step(() => set('#jf-time', g.time)); step(() => set('#jf-h', g.h)); step(() => set('#jf-ticket', g.ticket)); step(() => { $$('.jf-need').forEach(c => { c.checked = g.need.includes(c.value); if (c.checked) c.parentElement.classList.add('fill'); }); XW.cursorTo($('.jf .chk'), 20, 8); }); step(() => set('#jf-skill', g.skill || '')); step(() => set('#jf-lv', g.risk)); step(() => { const e = $('#jf-def'); if (e) { e.value = g.defectId || ''; if (g.defectId) e.classList.add('fill'); XW.cursorTo(e, 20, 8); } }); step(() => set('#jf-desc', g.desc, 20), 1800);
      step(() => { XW.cursorOff(); XW.state(''); const wk = ['周日', '周一', '周二', '周三', '周四', '周五', '周六']; XW.answer('填好了：' + g.type + '，' + g.dateIso.slice(5) + '（' + wk[new Date(g.dateIso).getDay()] + '）' + g.time + '，每人 ' + g.h + ' 小时，' + g.ticket + (g.need.length ? '，要' + g.need.join('、') : '') + '。不对的地方直接改，改完点保存。', null, { confirm: false }); }); }); },
  label(dateIso, time) { const wk = ['周日', '周一', '周二', '周三', '周四', '周五', '周六']; const d = new Date(dateIso); return (dateIso === TODAY ? '今日' : dateIso === '2026-08-08' ? '明日' : (DB.dayIdx(dateIso) != null ? '下' : '') + wk[d.getDay()] + ' ' + dateIso.slice(5)) + ' ' + time; },
  save(go) { const d = this.read(); const { errs, warns } = this.validate(d); const eb = $('#jf-err'); if (errs.length) { if (eb) eb.textContent = errs.join('；'); XW.answer('还差：' + errs.join('；') + '。', null, { confirm: false }); return; } if (eb) eb.textContent = '';
    const job = { t: d.t, type: d.type, line: d.line, dateIso: d.dateIso, time: d.time, when: this.label(d.dateIso, d.time), h: d.h, ticket: d.ticket === '不需要' ? '' : d.ticket, need: ['高压电工作业证'].concat(d.need), skill: d.skill || undefined, lead: d.ticket === '第一种工作票' || d.need.includes('工作负责人资格'), risk: d.risk, defectId: d.defectId || undefined, desc: d.desc }; let id = this.id;
    if (id) { DB.updAdded(id, job); XW.fly('任务已修改 · ' + job.t); } else { id = DB.addJob(job).id; XW.fly('任务已加入任务池 · ' + job.t); }
    if (job.defectId) DB.setDefect(job.defectId, '已登记 · 已排任务'); this.close(); TASKS.redraw();
    const where = ['任务池'].concat(DB.dayIdx(job.dateIso) != null ? ['下周计划'] : [], job.dateIso === TODAY ? ['今日工作台'] : [], ['任务台账']);
    if (go) { XW.answer('记好了，' + job.t + '排在' + job.when + '，' + where.join('、') + '里都有了。现在派人。', null, { confirm: false, done() { ACT['pool-dispatch']({ dataset: { id } }); } }); }
    else XW.answer('记好了，' + job.t + '排在' + job.when + '，' + where.join('、') + '里都有了' + (warns.length ? '。' + warns.join('；') : '') + '。现在派人，还是先放着？', null, { confirm: false, done() { XW.card('<div class="bt" style="margin-top:0"><button data-act="pool-dispatch" data-id="' + id + '">现在派工</button><button class="g" data-act="job-later">先放着</button></div>'); } }); }
};

/* ---------- 上传两票：读 Word / Excel / 文本 / 照片 → 解析票面 → 逐项对规程 → 缺项圈出 → 补齐并通过 / 退回 ---------- */
const TICKETUP = {
  t: null, res: null,
  RULES: { 操作票: ['票面要素齐全：编号、发令人、受令人、发令时间、操作任务、操作人、监护人', '停电操作先断开开关（断路器），再拉隔离开关', '拉隔离开关先负荷侧、后电源侧', '合接地开关（装设接地线）之前必须验电', '接地开关（接地线）写明编号或位置', '悬挂"禁止合闸，线路有人工作"标示牌', '每步操作之后有检查项', '操作完毕向调度汇报'], 工作票: ['票面要素：编号、工作负责人、工作任务', '停电（开关分闸）', '验电', '装设接地线并写明位置', '悬挂标示牌', '装设围栏', '验电在装设接地线之前'] },
  FIELDS: { 操作票: [['编号', 'no'], ['发令人', 'issuer'], ['受令人', 'receiver'], ['发令时间', 'issueTime'], ['操作任务', 'task'], ['操作人', 'operator'], ['监护人', 'guard'], ['值班负责人', 'duty']], 工作票: [['编号', 'no'], ['工作负责人', 'lead'], ['工作班成员', 'crew'], ['工作任务', 'task']] },
  key(t) { return t.kind === '操作票' ? '操作票' : '工作票'; },
  ruleIdx(t, i) { if (this.key(t) === '操作票') return i.rule === '票面要素' ? 0 : i.rule === '操作顺序' ? (/负荷侧/.test(i.text) ? 2 : 1) : i.rule === '验电' || i.rule === '接地' ? 3 : i.rule === '接地编号' ? 4 : i.rule === '标示牌' ? 5 : i.rule === '检查项' ? 6 : i.rule === '汇报' ? 7 : -1; return i.rule === '票面要素' ? 0 : /停电/.test(i.text) ? 1 : /验电/.test(i.text) && i.rule !== '顺序' ? 2 : /接地/.test(i.text) ? 3 : /标示牌/.test(i.text) ? 4 : /围栏/.test(i.text) ? 5 : i.rule === '顺序' ? 6 : -1; },
  itemRule(t, text) { if (this.key(t) === '操作票') return /汇报/.test(text) ? 7 : /检查/.test(text) ? 6 : /标示牌|标志牌/.test(text) ? 5 : /接地/.test(text) ? 4 : /验电/.test(text) ? 3 : /负荷侧|电源侧/.test(text) ? 2 : /断开|拉开|合上/.test(text) ? 1 : 0; return /围栏/.test(text) ? 5 : /标示牌/.test(text) ? 4 : /接地/.test(text) ? 3 : /验电/.test(text) ? 2 : /停电|分闸|断开/.test(text) ? 1 : 0; },
  fieldOf(text) { const m = { 编号: 'no', 发令人: 'issuer', 受令人: 'receiver', 发令时间: 'issueTime', 操作任务: 'task', 操作人: 'operator', 监护人: 'guard', 工作负责人: 'lead', 工作任务: 'task' }; const k = Object.keys(m).find(k => text.startsWith(k)); return k ? m[k] : null; },
  bind() { const inp = $('#tkfile'), dz = $('#tkdrop'); if (!inp || inp._b) return; inp._b = 1; inp.addEventListener('change', () => { if (inp.files && inp.files[0]) this.handle(inp.files[0]); inp.value = ''; }); if (dz) { dz.addEventListener('dragover', e => { e.preventDefault(); dz.classList.add('over'); }); dz.addEventListener('dragleave', () => dz.classList.remove('over')); dz.addEventListener('drop', e => { e.preventDefault(); dz.classList.remove('over'); const f = e.dataTransfer && e.dataTransfer.files[0]; if (f) this.handle(f); }); } },
  async handle(file) { const st = $('#tkupst'); const say = m => { if (st) st.textContent = m; }; XW.state('look', '正在读票'); say('正在读 ' + file.name + ' …');
    try { const r = await UPLOAD.read(file);
      if (r.kind === 'image') { const m = DB.tickets().find(t => r.name.replace(/\s/g, '').includes(t.no.replace(/\s/g, ''))); const host = $('#tkhost'); if (host) host.innerHTML = '<div class="tkpre"><img src="' + r.dataUrl + '" alt=""><div class="note" style="margin-top:6px">' + h(file.name) + ' · 已存为附件</div></div>'; say(file.name + ' · 照片已存为附件'); XW.state(''); if (m) { SCHEDPG.ticketNo = m.no; XW.answer('照片文件名里的票号我认出是 ' + m.no + '，台账里有这张电子票，我按电子票审。', null, { confirm: false, done: () => { SCHEDPG.draw(); XW.at(400, () => ACT['ticket-review']()); } }); } else XW.answer('照片收到了，存在附件里。票面上的字我离线认不出来，发我这张票的 Word 或 Excel 版，或者在左边点对应的电子票，我逐条审。', null, { confirm: false }); return; }
      if (r.kind === 'pdf') { say(file.name + ' · PDF 正文读不出'); XW.state(''); XW.answer('这份是 PDF，正文我离线读不出来。发我 Word 或 Excel 版的票，我逐条审。', null, { confirm: false }); return; }
      const p = UPLOAD.parse(r.text, r.name);
      if (p.kind === '未知' || !p.items.length) { say(file.name + ' · 没认出票面'); XW.state(''); XW.answer('这份文件里我没认出票面：' + (p.kind === '未知' ? '没有"操作票"或"工作票"字样' : '没有带序号的操作项目') + '。你确认一下是不是这张票，或者发我另一份。', null, { confirm: false }); return; }
      const rec = { no: p.f.no || ('上传 ' + r.name.replace(/\.[^.]+$/, '')), kind: p.kind, task: p.f.task || r.name, lead: p.f.operator || p.f.lead || '—', crew: p.kind === '操作票' ? '监护人 ' + (p.f.guard || '未填') : (p.f.crew || '—'), time: p.f.issueTime || p.f.start || '', items: p.items, f: p.f, uploaded: true, file: r.name, ts: Date.now() };
      const exist = DB.ticket(rec.no); if (exist && exist.uploaded) { DB.putTicket(rec); DB.setTicket(rec.no, '待审'); DB.log('上传两票', rec.no + ' 重新上传'); } else if (exist) { rec.no += '（上传）'; DB.addTicket(rec); } else DB.addTicket(rec);
      say('读到 ' + rec.kind + ' ' + rec.no + ' · ' + rec.items.length + ' 项'); SCHEDPG.ticketNo = rec.no; SCHEDPG.draw(); const s2 = $('#tkupst'); if (s2) s2.textContent = '读到 ' + rec.kind + ' ' + rec.no + ' · ' + rec.items.length + ' 项操作项目 · ' + file.name;
      XW.answer('读到了：' + rec.kind + ' ' + rec.no + '，' + rec.task + '，' + rec.items.length + ' 项操作项目，' + (rec.kind === '操作票' ? '操作人 ' + rec.lead + '、' + rec.crew : '负责人 ' + rec.lead) + '。我现在逐项对规程。', null, { confirm: false, done: () => this.run() });
    } catch (e) { say('读不了：' + e.message); XW.state(''); XW.answer('这份文件我读不了：' + e.message + '。', null, { confirm: false }); } },
  render(host, t) { this.t = t; this.res = null; const k = this.key(t); const done = /已审核|已签发|已执行|已退回/.test(t.st);
    host.innerHTML = '<div class="ticket" id="tk"><div class="pane"><h5>' + h(t.kind) + ' · ' + h(t.no) + '</h5><div class="note" style="margin-bottom:6px">来自上传 · ' + h(t.file || '') + (t.fixed ? ' · 已补齐' : '') + '</div>' + this.FIELDS[k].map(([n, key]) => '<div class="fr" id="tf-' + key + '"><i>' + n + '</i><span>' + (t.f[key] ? h(t.f[key]) : '<em class="none">未填</em>') + '</span></div>').join('') + '<div style="margin-top:6px;font-weight:600">' + (k === '操作票' ? '操作项目' : '安全措施') + '</div>' + t.items.map((it, i) => '<div class="it' + (it.added ? ' add' : '') + '" id="tm' + i + '"><span class="n">' + it.n + '.</span>' + h(it.text) + (it.done ? '<span class="ex">√ 已执行</span>' : '') + '</div>').join('') + '<div id="tmiss"></div></div>' +
      '<div class="pane"><h5>审核要点 · ' + (k === '操作票' ? '倒闸操作票' : '工作票安措') + '</h5>' + this.RULES[k].map((r, i) => '<div class="it" id="tr' + i + '">' + h(r) + '</div>').join('') + '</div><svg class="gaze"></svg></div><div class="bt" id="tkbt" style="margin-top:8px">' + (done ? '<span class="tag ' + (t.st === '已退回' ? 'bad' : 'ok') + '">' + h(t.st) + ' · ' + h(t.no) + '</span>' : '<button data-act="ticket-review">审票</button><button class="g" data-act="tku-back" disabled>退回修改</button>') + '</div>'; },
  run() { const t = this.t; if (!t || !$('#tk')) return; XW.state('look', '正在审票'); $$('#tk .it, #tk .fr').forEach(d => d.classList.remove('lit', 'miss', 'bad', 'tip', 'ok')); $('#tmiss').innerHTML = ''; $('#tk svg.gaze').innerHTML = ''; const n = t.items.length;
    t.items.forEach((it, i) => XW.at(300 + i * 600, () => { $$('#tk .it').forEach(d => d.classList.remove('lit')); const a = $('#tm' + i), b = $('#tr' + this.itemRule(t, it.text)); if (a) a.classList.add('lit'); if (b) b.classList.add('lit'); if (a && b) TICKETREV.line('#tm' + i, '#tr' + this.itemRule(t, it.text)); }));
    XW.at(300 + n * 600 + 200, () => { $$('#tk .it').forEach(d => d.classList.remove('lit')); const res = UPLOAD.audit(t); this.res = res; const badRules = new Set();
      res.iss.forEach(i => { const cls = i.lv === '错' ? 'bad' : i.lv === '提示' ? 'tip' : 'miss'; if (i.idx != null && $('#tm' + i.idx)) $('#tm' + i.idx).classList.add(cls); else if (i.rule === '票面要素' && this.fieldOf(i.text) && $('#tf-' + this.fieldOf(i.text))) $('#tf-' + this.fieldOf(i.text)).classList.add('miss'); else if (i.lv !== '提示' || i.rule !== '执行栏') $('#tmiss').insertAdjacentHTML('beforeend', '<div class="it ' + cls + '">' + h(i.text) + '</div>'); const ri = this.ruleIdx(t, i); if (ri >= 0 && i.lv !== '提示') badRules.add(ri); });
      this.RULES[this.key(t)].forEach((r, i) => { const e = $('#tr' + i); if (e) e.classList.add(badRules.has(i) ? 'bad' : 'ok'); });
      XW.state(''); const nb = res.iss.filter(i => i.lv !== '提示'), tips = res.iss.filter(i => i.lv === '提示'); const who = t.f.operator || t.f.lead || '负责人';
      const chart = CH.mini.bars([{ n: '通过', v: res.ok.length, c: CPAL[4] }, { n: '缺项', v: nb.filter(i => i.lv === '缺').length, c: '#e5484d' }, { n: '错误', v: nb.filter(i => i.lv === '错').length, c: '#e5484d' }, { n: '提示', v: tips.length, c: CPAL[1] }], { max: Math.max(6, res.ok.length + 1), unit: ' 项', h: 13, x0: 40 });
      if (nb.length) { const txt = '这张' + t.kind + '我逐项对了 ' + n + ' 条，有 ' + nb.length + ' 处要改：' + nb.map((i, k) => (k + 1) + '）' + i.text).join('；') + '。' + (tips.length ? '另外提醒：' + tips.map(i => i.text).join('；') + '。' : '') + '缺的我能补、顺序我能调，补完你再看一遍；或者退回' + who + '改。'; XW.answer(txt, h(txt) + '<div class="bt"><button data-act="tku-fix">补齐并通过</button><button class="g" data-act="tku-back">退回' + h(who) + '</button></div>', { speak: false, confirm: false, chart }); }
      else { const txt = '这张' + t.kind + '我逐项对了 ' + n + ' 条：票面要素齐全，' + res.ok.filter(o => /顺序|验电|编号|标示牌|检查|汇报|围栏|接地/.test(o)).join('、') + '，可以通过。' + (tips.length ? '提醒：' + tips.map(i => i.text).join('；') + '。' : ''); XW.answer(txt, h(txt) + '<div class="bt"><button data-act="tku-pass">通过并签发</button><button class="g" data-act="tku-back">退回' + h(who) + '</button></div>', { speak: false, confirm: false, chart }); }
      const b = $('#tkbt button.g'); if (b) b.disabled = false; }); },
  fix() { const t = this.t, res = this.res; if (!t || !res) return; const hadOrder = res.iss.some(i => i.rule === '操作顺序' && i.lv === '错'), hadGuard = res.iss.some(i => /监护人/.test(i.text)), hadNo = res.iss.some(i => i.rule === '接地编号'); UPLOAD.fix(t, res); t.fixed = true; DB.putTicket(t); DB.setTicket(t.no, '已审核'); const who = t.f.operator || t.f.lead || '负责人'; DB.notify(who, t.kind + ' ' + t.no + ' 审核通过（已补齐）', '已读', true);
    const host = $('#tkhost'); if (host) this.render(host, DB.ticket(t.no)); const added = t.items.filter(i => i.added); const parts = []; if (added.length) parts.push('补了 ' + added.length + ' 项：' + added.map(i => '"' + i.text + '"').join('、')); if (hadOrder) parts.push('把"断开开关"调到了拉隔离开关前面'); if (hadNo) parts.push('接地开关补了编号'); if (hadGuard) parts.push('监护人填了韩雪');
    const again = UPLOAD.audit(t).iss.filter(i => i.lv !== '提示'); XW.fly(t.kind + ' ' + t.no + ' 已审核 · 已通知 ' + who); XW.answer((parts.join('；') || '按你的意见改了') + '。' + (again.length ? '再对一遍还有 ' + again.length + ' 处：' + again.map(i => i.text).join('；') + '，得' + who + '本人改。' : '再对一遍没问题了，票通过审核，' + who + '收到通知，操作前在现场再核一遍。') + ' 补的项目我标成了绿色。', null, { confirm: false }); TASKS.redraw(); },
  pass() { const t = this.t; if (!t) return; DB.setTicket(t.no, '已审核'); const who = t.f.operator || t.f.lead || '负责人'; DB.notify(who, t.kind + ' ' + t.no + ' 审核通过', '已读', true); const host = $('#tkhost'); if (host) this.render(host, DB.ticket(t.no)); XW.fly(t.kind + ' ' + t.no + ' 已审核 · 已通知 ' + who); XW.answer('票通过审核，' + who + '收到通知，操作前在现场再核一遍。两票台账和本月合格率都更新了。', null, { confirm: false }); TASKS.redraw(); },
  back() { const t = this.t; if (!t) return; const iss = this.res ? this.res.iss.filter(i => i.lv !== '提示').map(i => i.text) : []; DB.setTicket(t.no, '已退回'); const who = t.f.operator || t.f.lead || '负责人'; DB.notify(who, t.kind + ' ' + t.no + ' 退回修改' + (iss.length ? '：' + iss.join('；') : ''), '已读', true); const host = $('#tkhost'); if (host) this.render(host, DB.ticket(t.no)); XW.fly(t.kind + ' ' + t.no + ' 已退回 ' + who + ' · 附修改意见', 'w'); XW.answer('退回' + who + '了，' + (iss.length ? '要改的 ' + iss.length + ' 处我写在退回意见里，' : '') + '改完重新上传我再对一遍。', null, { confirm: false }); TASKS.redraw(); }
};

/* ---------- 流程按钮 ---------- */
Object.assign(ACT, {
  'job-new'() { TASKFORM.open(); }, 'job-assist'() { TASKFORM.assist(); }, 'job-save'(el) { TASKFORM.save(el.dataset.go === '1'); }, 'job-cancel'() { TASKFORM.close(); }, 'job-later'() { XW.answer('好，放在任务池里，派的时候点那一行的「派工」。', null, { confirm: false }); },
  'job-edit'(el) { TASKFORM.open(el.dataset.id); },
  'job-del'(el) { const j = DB.job(el.dataset.id); if (!j) return; XW.answer('要删掉"' + j.t + '"吗？删了任务池、周计划和台账里都会去掉。', '要删掉"' + h(j.t) + '"吗？<div class="bt"><button data-act="job-del-ok" data-id="' + j.id + '">删除</button><button class="g" data-act="no" data-t="不删">不删</button></div>', { confirm: false }); },
  'job-del-ok'(el) { const j = DB.job(el.dataset.id); DB.removeJob(el.dataset.id); XW.fly('任务已删除 · ' + (j ? j.t : ''), 'w'); TASKS.redraw(); XW.answer('删掉了。', null, { confirm: false }); },
  'job-open'(el) { const j = DB.job(el.dataset.id); if (!j) return; const next = j.st === '待派' ? '下一步派工。' : /已派|待开工/.test(j.st) ? (j.ticketNo && !/已审核|已签发|已执行/.test((DB.ticket(j.ticketNo) || {}).st) ? '工作票 ' + j.ticketNo + ' 还没审，审过才能开工。' : '可以开工了。') : j.st === '进行中' ? '在现场，等回传。' : /已完成/.test(j.st) ? '等验收关闭。' : ''; ensure('sched', () => XW.answer(j.t + '现在' + j.st + '。' + next, null, { confirm: false }), 'pool'); },
  'job-ticket'(el) { const j = DB.job(el.dataset.id); if (j && j.ticketNo) { SCHEDPG.ticketNo = j.ticketNo; nav('sched', 'ticket'); } },
  'job-start'(el) { const r = DB.start(el.dataset.id); if (!r.ok) { if (r.ticket) { XW.answer(r.why + '。我把票调出来，你审完再开工。', h(r.why) + '。<div class="bt"><button data-act="job-ticket" data-id="' + el.dataset.id + '">去审票</button><button class="g" data-act="no" data-t="先不开工">先不开工</button></div>', { confirm: false }); } else XW.answer(r.why + '。', null, { confirm: false }); return; }
    const j = r.job; XW.fly('已开工 · ' + j.t + ' · ' + r.who.join(' · ')); TASKS.redraw(); XW.answer('开工了，' + r.who.join('、') + '在现场，人员去向里标成了外勤。现场进度多了这一组，他们回传我归到那里。', null, { confirm: false, done() { XW.card('<div class="bt" style="margin-top:0"><button class="g" data-act="nav" data-to="sched" data-sub="prog">看现场进度</button></div>'); } }); },
  'job-report'(el) { const j = DB.job(el.dataset.id); const g = DB.report(el.dataset.id); if (!g) return; const ev = g.ev[g.ev.length - 1]; XW.fly('回传 · ' + ev[1] + '：' + ev[2]); TASKS.redraw(); XW.answer(ev[1] + '回传："' + ev[2] + '"。' + j.t + '现在 ' + g.pct + '%，累计 ' + g.hrs + ' 小时' + (g.warn ? '，连续超过三小时了，' + (WEATHER.includes('34') ? '今天 34 度，' : '') + '按班组约定要轮换。' : '。'), null, { confirm: false, chart: CH.mini.bars([{ n: j.t.slice(0, 8), v: g.hrs, c: g.warn ? '#e5484d' : CPAL[0], tip: '连续 ' + g.hrs + 'h' }], { limit: 3, unit: 'h', max: 6, x0: 70, h: 13 }) }); },
  'job-finish'(el) { const j = DB.job(el.dataset.id); const r = DB.finish(el.dataset.id); if (!r) { XW.answer('这项任务还没开工，完不了工。', null, { confirm: false }); return; } XW.fly('完工 · ' + j.t + ' · ' + r.who.join(' · ') + ' 各记 ' + r.hrs + 'h'); TASKS.redraw(); const sk = r.skill ? SKILL9.find(s => s.k === r.skill) : null; const nd = j.node ? NODES.find(n => n.id === j.node) : null;
    const txt = '完工了。' + r.who.join('、') + '各记 ' + r.hrs + ' 小时，工时台账和本周工时图都更新了' + (r.over.length ? '；' + r.over.map(n => n + '本周到了 ' + DB.week(n) + ' 小时').join('、') + '，超过约定，下次派工我会避开' : '') + '。' + (sk ? '核心技能「' + sk.n + '」的实操量给' + r.who.filter(n => P[n]).join('、') + '各记了一次，资格等级不自动变，要升 A 由你在培养页确认。' : '') + (j.ticketNo ? '工作票 ' + j.ticketNo + ' 记为已执行。' : '') + (r.linked ? '关联的缺陷"' + r.linked.t + '"转到待验收，验收人建议韩雪。' : '') + (nd ? '关键节点「' + nd.t + '」可以勾成本周已清。' : '');
    XW.answer(txt, null, { chart: CH.mini.bars(r.who.filter(n => P[n]).map(n => ({ n, v: DB.week(n), c: DB.week(n) > WEEK_LIMIT ? '#e5484d' : CPAL[0], act: 'hours', who: n, tip: n + ' 本周 ' + DB.week(n) + 'h · 点开看台账' })), { limit: WEEK_LIMIT, unit: 'h', max: 32, h: 13 }), done() { XW.card('<div class="bt" style="margin-top:0"><button class="g" data-act="hours" data-who="' + r.who[0] + '">看' + r.who[0] + '的工时台账</button>' + (sk ? '<button class="g" data-act="nav" data-to="train" data-sub="write">看实操量回写</button>' : '') + (r.linked ? '<button data-act="job-close" data-id="' + j.id + '">验收关闭</button>' : '') + (nd ? '<button data-act="node-done" data-id="' + nd.id + '" data-who="' + r.who[0] + '">节点勾已清</button>' : '') + '</div>'); } }); },
  'job-close'(el) { const j = DB.job(el.dataset.id); const linked = DB.close(el.dataset.id); XW.fly('已关闭 · ' + j.t + (linked ? ' · 缺陷验收 韩雪' : '')); TASKS.redraw(); XW.answer('关闭了。' + (linked ? '缺陷"' + linked.t + '"同步关闭，验收人韩雪，缺陷台账的处理记录我填好了；应用失败未消缺数减一，周报口径的闭环数加一。' : '任务台账里记为已关闭。'), null, { confirm: false }); },
  'hz-job'(el) { const d = DB.defect(el.dataset.id); if (!d) return; const exist = DB.jobs().find(x => x.defectId === d.id && !/已关闭|已删除/.test(x.st)); if (exist) { ensure('sched', () => XW.answer('这条缺陷已经有消缺任务"' + exist.t + '"，现在' + exist.st + '。' + (exist.st === '待派' ? '直接派人。' : ''), null, { confirm: false, done() { if (exist.st === '待派') XW.card('<div class="bt" style="margin-top:0"><button data-act="pool-dispatch" data-id="' + exist.id + '">现在派工</button></div>'); } }), 'pool'); return; }
    const climb = /杆|FTU|柱上/.test(d.t); const base = d.t.replace(/（[^）]*）/g, '').trim(); const urgent = d.lv === '重大' || d.lv === '紧急'; const dateIso = urgent ? TODAY : '2026-08-10';
    const job = DB.addJob({ t: base + ' 消缺', type: '消缺', line: DB.lineOf({ t: d.t }), dateIso, time: urgent ? '10:00' : '09:00', when: (urgent ? '今日 10:00' : '下周一 09:00'), h: 4, ticket: climb ? '第一种工作票' : '第二种工作票', need: ['高压电工作业证'].concat(climb ? ['登高架设作业证', '工作负责人资格'] : []), skill: 's9', lead: climb, risk: urgent ? '高' : '中', defectId: d.id, desc: '处理完拍照回传，缺陷转待验收；验收后在主站做一次遥控验证。' }); DB.setDefect(d.id, '已登记 · 已排任务'); XW.fly('消缺任务已加入任务池 · ' + job.t);
    ensure('sched', () => XW.answer('按这条缺陷加了消缺任务"' + job.t + '"，' + (urgent ? d.lv + '缺陷，排在今天，' : '排在下周一，') + (climb ? '要登杆，第一种工作票。' : '柜内作业，第二种工作票。') + '现在派人？', null, { confirm: false, done() { XW.card('<div class="bt" style="margin-top:0"><button data-act="pool-dispatch" data-id="' + job.id + '">现在派工</button><button class="g" data-act="job-later">先放着</button></div>'); } }), 'pool'); },
  'tku-fix'() { TICKETUP.fix(); }, 'tku-pass'() { TICKETUP.pass(); }, 'tku-back'() { TICKETUP.back(); }
});
