/* ===== 培训考评：年度计划热力、课程出题、题库与按短板组卷、判卷与错题、三套实操评分表、成绩记录、回写图谱 ===== */
const TRAINPG = {
  tabs: [{ k: 'course', n: '课程与出题' }, { k: 'plan', n: '培训计划' }, { k: 'bank', n: '题库' }, { k: 'grade', n: '判卷' }, { k: 'sheet', n: '实操评分表' }, { k: 'record', n: '成绩记录' }, { k: 'write', n: '回写图谱' }],
  course: null, sheet: null, bankCourse: 'c5',
  plan() { const MONTHS = ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月']; const vals = TRAIN_Y.map(r => r.m.map((v, mi) => v ? (mi < 8 ? 2 : mi === 8 ? 3 : 1) : 0)); const plan = LS.get('plan', []);
    return '<div class="card"><div class="h"><b>年度培训计划 · 2026</b><span>点一格她说安排 · 绿=已完成 · 橙=本月 · 蓝=计划</span><div class="r"><button class="s g" data-act="train-plan-next">生成下月计划</button></div></div>' + CH.mini.heat(TRAIN_Y.map(r => r.c.length > 14 ? r.c.slice(0, 14) + '…' : r.c), MONTHS, vals, { colors: ['#eef0fb', '#9a9cf5', '#18b97a', '#e8791d'], act: 'train-cell', fmt: v => ['无', '计划', '已完成', '本月'][v], w: 680, L: 150, rh: 16, cwmax: 44 }) + '</div>' +
      '<div class="grid2"><div class="card"><div class="h"><b>本月与新增计划</b><span>' + (4 + plan.length) + ' 项</span></div><div class="jobs">' + [['《10kV 光纤电流差动保护》', '刘一鸣 · 陈浩 · 周明', '9-15 前理论测试'], ['《配网 10kV 电力电缆试验》', '王安 · 吴倩', '配合电缆试验旁站'], ['实操：中压倒闸操作考核', '郭子扬 · 赵敏', '9-20'], ['师带徒：继保旁站两次', '刘一鸣（黄伟强带）', '本周']].map(r => '<div><span style="font-size:11.5px;color:var(--ink)">' + h(r[0]) + '<br><span class="note">' + h(r[1]) + '</span></span><span class="tag">' + h(r[2]) + '</span></div>').join('') + plan.map(p => '<div><span style="font-size:11.5px;color:var(--ink)">《' + h(p.t) + '》<br><span class="note">' + h(p.who) + '</span></span><span class="tag ok">' + h(p.when) + '</span></div>').join('') + '</div><div class="doc" id="tplanhost" style="margin-top:6px"></div></div>' +
      '<div class="card"><div class="h"><b>课程完成 · 每人</b><span>7 门 · 点一条看他学了哪些</span></div>' + CH.mini.bars(PEOPLE.map(p => ({ n: p.n, v: (TRAIN_DONE[p.n] || []).length, c: (TRAIN_DONE[p.n] || []).length <= 2 ? '#e8791d' : CPAL[4], act: 'train-person', who: p.n, tip: p.n + ' 已学 ' + (TRAIN_DONE[p.n] || []).length + '/7 门' })), { max: 7, unit: ' 门', h: 12 }) + '</div></div>'; },
  courses() { return '<div class="grid2" style="grid-template-columns:1fr 1.4fr"><div class="card"><div class="h"><b>课程库 · 继保专才 6 门 + 运维 1 门</b><span>点一门，她出 5 道新题</span></div><div class="crs">' + COURSES.map(c => { const n = PEOPLE.filter(p => (TRAIN_DONE[p.n] || []).includes(c.id)).length; return '<a data-act="course" data-id="' + c.id + '" class="' + (this.course === c.id ? 'on' : '') + '"><span style="font-size:12px;color:var(--ink)">' + h(c.n) + '<br><span class="note">' + c.pages + ' 页 · ' + h(MODS.find(m => m.k === c.mod).n.replace('能力', '')) + ' · ' + h(c.src) + '</span></span><span>' + n + '/12 已学</span></a>'; }).join('') + '</div><div style="margin-top:8px">' + CH.mini.bars(COURSES.map((c, i) => ({ n: c.n.slice(0, 6), v: PEOPLE.filter(p => (TRAIN_DONE[p.n] || []).includes(c.id)).length, c: CPAL[i % 6] })), { max: 12, unit: ' 人', h: 12, x0: 56 }) + '</div></div><div class="card" id="qcard"><div class="h"><b id="qtitle">出题</b><span id="qsub"></span></div><div class="qs" id="qs"><div class="empty">点左边的课程</div></div><div class="bt" id="qbt2" style="margin-top:8px"></div></div></div>'; },
  genQ(id, target) { const c = COURSES.find(x => x.id === id); this.course = id; $$('.crs a').forEach(a => a.classList.toggle('on', a.dataset.id === id)); const qt = $('#qtitle'); if (!qt) { ensure('train', () => this.genQ(id, target), 'course'); return; } qt.textContent = c.n + ' · 出 5 题' + (target ? ' · 给' + target : ''); $('#qsub').textContent = '出处 ' + c.src; const host = $('#qs'); host.innerHTML = ''; XW.state('write'); XW.type($('#xwsub'), '我从《' + c.n + '》的课件里出 5 道题，每题标出处页码。', 45);
    c.qs.slice(0, 5).forEach((q, i) => XW.at(400 + i * 1500, () => { const d = document.createElement('div'); d.className = 'q'; d.innerHTML = '<b></b><span>' + q.a.map((a, j) => String.fromCharCode(65 + j) + '. ' + h(a)).join('　') + '</span><em>出处：' + h(c.src) + ' ' + h(q.pg) + '</em>'; host.appendChild(d); requestAnimationFrame(() => d.classList.add('in')); XW.type($('b', d), (i + 1) + '. ' + q.q, 22); }));
    XW.at(400 + Math.min(5, c.qs.length) * 1500 + 400, () => { XW.state(''); $('#qbt2').innerHTML = '<button data-act="q-send" data-who="' + (target || '刘一鸣') + '">发给' + (target || '刘一鸣') + '</button><button class="g" data-act="q-more">换一批</button>'; XW.answer('五道题出好了，都是课件里有原文的，第 ' + (c.qs.length > 4 ? '3' : '2') + ' 题偏难。' + (target ? '这套是按' + target + '的短板组的。' : '发给谁？'), null, { confirm: false, chart: CH.mini.donut([{ k: '选择题', v: c.qs.filter(q => q.a.length > 2).length, c: CPAL[0] }, { k: '判断题', v: c.qs.filter(q => q.a.length === 2).length, c: CPAL[2] }], { sub: '题型' }) }); }); },
  bank() { const c = COURSES.find(x => x.id === this.bankCourse); return '<div class="grid2" style="grid-template-columns:1fr 1.6fr"><div><div class="card"><div class="h"><b>题库</b><span>' + COURSES.reduce((s, c) => s + c.qs.length, 0) + ' 题 · 按课程</span></div><div class="kbq">' + COURSES.map(x => '<b data-act="bank-course" data-id="' + x.id + '" style="' + (x.id === this.bankCourse ? 'background:var(--tint);color:var(--pri);border-color:#c9cbf5' : '') + '">' + h(x.n.slice(0, 8)) + ' ' + x.qs.length + '</b>').join('') + '</div><div style="margin-top:8px">' + CH.mini.donut(COURSES.map((x, i) => ({ k: x.n.slice(0, 6), v: x.qs.length, c: CPAL[i % 6], act: 'bank-course', id: x.id })), { sub: '题' }) + '</div></div>' +
      '<div class="card" style="margin-top:10px"><div class="h"><b>按短板组卷</b><span>她按图谱最弱的模块选课</span></div><div class="kbq">' + PEOPLE.filter(p => p.post !== '班长').map(p => '<b data-act="bank-target" data-who="' + p.n + '">' + h(p.n) + '</b>').join('') + '</div></div></div>' +
      '<div class="card"><div class="h"><b>' + h(c.n) + '</b><span>' + c.qs.length + ' 题 · 出处 ' + h(c.src) + '</span></div><div class="qs">' + c.qs.map((q, i) => '<div class="q in"><b>' + (i + 1) + '. ' + h(q.q) + '</b><span>' + q.a.map((a, j) => (j === q.k ? '<u class="num">' : '') + String.fromCharCode(65 + j) + '. ' + h(a) + (j === q.k ? '</u>' : '')).join('　') + '</span><em>答案 ' + String.fromCharCode(65 + q.k) + ' · ' + h(q.pg) + '</em></div>').join('') + '</div></div></div>'; },
  grade() { const c = COURSES.find(x => x.id === ANSWER_SAMPLE.course); const g = LS.get('grades', {}); return '<div class="grid2" style="grid-template-columns:1.5fr 1fr"><div class="card"><div class="h"><b>判卷 · ' + h(ANSWER_SAMPLE.who) + ' · ' + h(c.n) + '</b><span>他的答卷已回收，她逐题对要点</span></div><div class="qs" id="gqs">' + c.qs.map((q, i) => '<div class="q in"><b>' + (i + 1) + '. ' + h(q.q) + '</b><span>他答：' + String.fromCharCode(65 + ANSWER_SAMPLE.ans[i]) + '. ' + h(q.a[ANSWER_SAMPLE.ans[i]]) + '<span class="mark" id="gm' + i + '" style="display:none"></span></span><em id="gr' + i + '"></em></div>').join('') + '</div><div class="bt" style="margin-top:8px" id="gbt">' + (g[ANSWER_SAMPLE.who] ? '<span class="tag ok">已判 · ' + g[ANSWER_SAMPLE.who].score + ' 分</span><button class="g" data-act="grade-run">再判一遍</button>' : '<button data-act="grade-run">判卷</button>') + '</div><div class="sheet"><div class="tot" id="gtot"></div></div></div>' +
      '<div><div class="card"><div class="h"><b>待判答卷</b><span>3 份</span></div><div class="jobs">' + [['刘一鸣', '光差保护理论', '08-28 回收'], ['陈浩', '光差保护理论', '08-28 回收'], ['周明', '光差保护理论', '08-29 回收']].map((r, i) => '<div><span style="font-size:11.5px;color:var(--ink)">' + h(r[0]) + ' · ' + h(r[1]) + '<br><span class="note">' + h(r[2]) + '</span></span>' + (i === 0 ? (g[r[0]] ? '<span class="tag ok">已判</span>' : '<span class="tag w">待判</span>') : '<span class="tag">待判</span>') + '</div>').join('') + '</div></div><div class="card" style="margin-top:10px"><div class="h"><b>错题本 · 刘一鸣</b><span>判完自动归集</span></div><div id="wrong">' + (g[ANSWER_SAMPLE.who] ? c.qs.filter((q, i) => ANSWER_SAMPLE.ans[i] !== q.k).map(q => '<div class="note" style="color:var(--ink);margin:4px 0">· ' + h(q.q) + ' <b>' + h(q.a[q.k]) + '</b> <span class="note">' + h(q.pg) + '</span></div>').join('') : '<div class="empty">判完卷再看</div>') + '</div></div><div class="card" style="margin-top:10px"><div class="h"><b>理论成绩 · 班组逐月均分</b></div>' + CH.mini.line([{ n: '均分', vals: [68, 71, 74, 72, 76, 70], c: CPAL[0], area: true }], ['3月', '4月', '5月', '6月', '7月', '8月'], { max: 100, h: 110 }) + '</div></div></div>'; },
  gradeRun() { const c = COURSES.find(x => x.id === ANSWER_SAMPLE.course); XW.state('look', '正在判卷'); let ok = 0; c.qs.forEach((q, i) => XW.at(600 + i * 1300, () => { const good = ANSWER_SAMPLE.ans[i] === q.k; if (good) ok++; const m = $('#gm' + i); m.style.display = ''; m.textContent = good ? '对' : '错 · 应为 ' + String.fromCharCode(65 + q.k); m.className = 'mark' + (good ? '' : ' bad'); $('#gr' + i).textContent = good ? '' : '要点：' + q.a[q.k] + '（' + c.src + ' ' + q.pg + '）'; $('#gtot').innerHTML = '<span>已判 ' + (i + 1) + '/' + c.qs.length + '</span><b>' + Math.round(ok / c.qs.length * 100) + '</b><span>分</span>'; }));
    XW.at(600 + c.qs.length * 1300 + 200, () => { XW.state(''); const sc = Math.round(ok / c.qs.length * 100); const g = LS.get('grades', {}); g[ANSWER_SAMPLE.who] = { course: c.n, score: sc, ok, n: c.qs.length, ts: Date.now() }; LS.set('grades', g); const wrong = $('#wrong'); if (wrong) wrong.innerHTML = c.qs.filter((q, i) => ANSWER_SAMPLE.ans[i] !== q.k).map(q => '<div class="note" style="color:var(--ink);margin:4px 0">· ' + h(q.q) + ' <b>' + h(q.a[q.k]) + '</b> <span class="note">' + h(q.pg) + '</span></div>').join(''); XW.answer('刘一鸣 ' + c.qs.length + ' 题对了 ' + ok + ' 道，' + sc + ' 分。错的都在差动判据和光纤参数这两处，说明原理没吃透。我建议这门课重学第 8 页和第 15 页，再考一次；图谱上"二次及保护能力"暂时保持 L1。', null, { speak: false, chart: CH.mini.donut([{ k: '答对', v: ok, c: CPAL[4] }, { k: '答错', v: c.qs.length - ok, c: '#e5484d' }], { hero: sc, sub: '分' }) }); XW.card('<div class="bt" style="margin-top:0"><button data-act="nav" data-to="train" data-sub="write">去回写图谱</button><button class="g" data-act="grade-retest">安排补考</button></div>'); $('#gbt').innerHTML = '<span class="tag ok">已判 · ' + sc + ' 分</span>'; }); },
  sheets() { const sh = this.sheet ? SHEETS.find(s => s.id === this.sheet) : null; const sc = LS.get('scores', {}); const hist = []; Object.keys(SCORE_HIST).forEach(n => SCORE_HIST[n].filter(s => /实操/.test(s.t)).forEach(s => hist.push({ n: n + ' ' + s.t.replace('实操', ''), v: s.s, c: s.s >= 90 ? CPAL[4] : CPAL[0] }))); return '<div class="grid2" style="grid-template-columns:1fr 2fr"><div><div class="card"><div class="h"><b>实操评分表</b><span>三套 · 逐项打分</span></div><div class="crs">' + SHEETS.map(s => '<a data-act="sheet" data-id="' + s.id + '" class="' + (this.sheet === s.id ? 'on' : '') + '"><span style="font-size:12px;color:var(--ink)">' + h(s.n) + '</span><span>' + s.rows.length + ' 项 · ' + h(s.time) + '</span></a>').join('') + '</div><div class="note" style="margin-top:8px">' + Object.keys(sc).map(k => k + '：' + sc[k].sheet.split(' · ')[1] + ' ' + sc[k].total + ' 分').join('；') + '</div></div><div class="card" style="margin-top:10px"><div class="h"><b>实操成绩 · 本年</b></div>' + CH.mini.bars(hist, { max: 100, h: 12, x0: 96 }) + '</div></div>' +
    '<div class="card sheet" id="sheetcard">' + (sh ? '<div class="h"><b>' + h(sh.n) + '</b><span>考评对象 <select id="shwho" style="font:inherit">' + PEOPLE.filter(p => !/班长/.test(p.post)).map(p => '<option' + (p.n === '郭子扬' ? ' selected' : '') + '>' + h(p.n) + '</option>').join('') + '</select></span></div><div class="tbl"><table class="t"><tr><th>项目</th><th>考核要求</th><th>分值</th><th>评分标准</th><th>得分</th></tr>' + sh.rows.map((r, i) => '<tr><td><b>' + h(r.it) + '</b><br><span class="note">' + h(r.g) + '</span></td><td style="font-size:11px">' + h(r.req) + '</td><td style="font-family:var(--mono)">' + r.max + '</td><td style="font-size:11px;color:var(--ink3)">' + h(r.std) + '</td><td><input data-act="sh-in" data-i="' + i + '" data-max="' + r.max + '" value="' + r.max + '" inputmode="numeric"></td></tr>').join('') + (sh.extra.length ? sh.extra.map(e => '<tr><td colspan="4" class="note">' + h(e.it) + '：' + h(e.std) + '</td><td class="note">' + e.max + '</td></tr>').join('') : '') + '</table></div><div class="tot"><label class="veto" id="veto"><input type="checkbox" data-act="sh-veto"> 否决项：' + h(sh.veto) + '</label><span style="margin-left:auto">合计</span><b id="shtot">100</b><span>/ 100</span><button data-act="sh-save">保存成绩</button></div>' : '<div class="empty">点左边的评分表</div>') + '</div></div>'; },
  total() { const sh = SHEETS.find(s => s.id === this.sheet); if (!sh) return 0; let t = 0; $$('input[data-act="sh-in"]').forEach(inp => { let v = +inp.value; const mx = +inp.dataset.max; if (isNaN(v) || v < 0) v = 0; if (v > mx) { inp.classList.add('bad'); v = mx; } else inp.classList.remove('bad'); t += v; }); if ($('#veto input').checked) t = 0; $('#shtot').textContent = t; return t; },
  record() { const g = LS.get('grades', {}); const sc = LS.get('scores', {}); return '<div class="grid2" style="grid-template-columns:1.4fr 1fr"><div class="card"><div class="h"><b>成绩记录 · 每人</b><span>点一行她说趋势 · 不排名</span></div><div class="tbl"><table class="t"><tr><th>姓名</th><th>已学</th><th>本年考试</th><th>最近一次</th><th>实操</th></tr>' + PEOPLE.map(p => { const hs = (SCORE_HIST[p.n] || []).slice(); if (g[p.n]) hs.push({ d: '今天', t: g[p.n].course.slice(0, 6) + '理论', s: g[p.n].score }); if (sc[p.n]) hs.push({ d: '今天', t: sc[p.n].sheet.split(' · ')[1] + '实操', s: sc[p.n].total }); const last = hs[hs.length - 1]; const pr = hs.filter(x => /实操/.test(x.t)); return '<tr data-act="rec-row" data-who="' + p.n + '" style="cursor:pointer"><td>' + h(p.n) + '</td><td>' + (TRAIN_DONE[p.n] || []).length + '/7</td><td>' + hs.length + ' 次</td><td>' + (last ? h(last.d + ' ' + last.t) + ' <b>' + last.s + '</b>' : '—') + '</td><td>' + (pr.length ? pr.map(x => x.s).join(' / ') : '—') + '</td></tr>'; }).join('') + '</table></div></div><div><div class="card"><div class="h"><b>本年考试分布</b><span>理论 / 实操</span></div>' + CH.mini.cols([['<60', 0], ['60–69', 0], ['70–79', 0], ['80–89', 0], ['90+', 0]].map(b => { const all = []; Object.values(SCORE_HIST).forEach(a => a.forEach(x => all.push(x.s))); const [lo, hi] = b[0] === '<60' ? [0, 59] : b[0] === '90+' ? [90, 100] : b[0].split('–').map(Number); return { n: b[0], v: all.filter(s => s >= lo && s <= hi).length, c: b[0] === '<60' ? '#e5484d' : b[0] === '90+' ? CPAL[4] : CPAL[0] }; }), { max: 8, h: 120, labels: true }) + '</div><div class="card" style="margin-top:10px"><div class="h"><b>竞赛人选参考</b><span>由班长与所里定</span></div><div class="note" style="color:var(--ink)">按实操 90 分以上和图谱 L4 筛：<b>李文博</b>（局放 93、去年三等奖）、<b>韩雪</b>（合环 96，可做指导）、<b>黄伟强</b>（合环 95）。青年组：<b>郭子扬</b>（倒闸 88，两年进步最快）。</div><div class="bt"><button class="s g" data-act="say" data-say="谁适合参加下季度的技能竞赛">让她再说一遍</button></div></div></div></div>'; },
  writeTab() { const g = LS.get('grades', {}); const sc = LS.get('scores', {}); const sugg = []; Object.keys(g).forEach(n => sugg.push({ who: n, mod: 'relay', from: PEOPLEPG.lv(P[n])[3], to: g[n].score >= 80 ? Math.min(5, PEOPLEPG.lv(P[n])[3] + 1) : PEOPLEPG.lv(P[n])[3], why: g[n].course + ' 理论 ' + g[n].score + ' 分' })); Object.keys(sc).forEach(n => { const mi = sc[n].sheet.includes('局放') ? 0 : 6; sugg.push({ who: n, mod: MODS[mi].k, from: PEOPLEPG.lv(P[n])[mi], to: sc[n].total >= 85 ? Math.min(5, PEOPLEPG.lv(P[n])[mi] + 1) : PEOPLEPG.lv(P[n])[mi], why: sc[n].sheet.split(' · ')[1] + ' 实操 ' + sc[n].total + ' 分' + (sc[n].veto ? '（否决）' : '') }); }); const conf = LS.get('levels', {});
    return '<div class="grid2" style="grid-template-columns:1.6fr 1fr"><div class="card"><div class="h"><b>回写图谱 · 等级建议</b><span>成绩进图谱前先经班组长确认</span></div>' + (sugg.length ? '<div class="tbl"><table class="t"><tr><th>人员</th><th>模块</th><th>现等级</th><th>建议</th><th>依据</th><th></th></tr>' + sugg.map((s, i) => '<tr><td>' + h(s.who) + '</td><td>' + h(MODS.find(m => m.k === s.mod).n) + '</td><td>' + h(LV[s.from]) + '</td><td>' + (s.to > s.from ? '<span class="tag ok">升 ' + h(LV[s.to]) + '</span>' : '<span class="tag">保持 ' + h(LV[s.to]) + '</span>') + '</td><td class="note">' + h(s.why) + '</td><td>' + ((conf[s.who] || {})[s.mod] === s.to ? '<span class="tag ok">已确认</span>' : '<button class="s" data-act="lvw-confirm" data-who="' + s.who + '" data-mod="' + s.mod + '" data-to="' + s.to + '">确认</button>') + '</td></tr>').join('') + '</table></div>' : '<div class="empty">判一次卷或打一次实操分，建议就出现在这里</div>') + '<div class="loop" style="margin-top:8px">' + LOOP.map((l, i) => '<div class="' + (i === 3 || i === 5 ? 'on' : '') + '">' + (i + 1) + ' ' + l + '</div>').join('') + '</div></div>' +
      '<div class="card"><div class="h"><b>本季度已确认的等级变化</b></div>' + (Object.keys(conf).length ? '<div class="jobs">' + Object.keys(conf).map(n => Object.keys(conf[n]).map(k => '<div><span style="font-size:11.5px;color:var(--ink)">' + h(n) + ' · ' + h(MODS.find(m => m.k === k).n) + '</span><span class="tag ok">' + h(LV[conf[n][k]]) + '</span></div>').join('')).join('') + '</div>' : '<div class="empty">还没有确认过的变化</div>') + '<div style="margin-top:8px">' + CH.mini.radar(MODS.map(m => m.n.replace('能力', '')), [{ n: '本季度均值', vals: MODS.map((m, i) => +(PEOPLE.reduce((s, p) => s + PEOPLEPG.lv(p)[i], 0) / PEOPLE.length).toFixed(1)), c: CPAL[0] }, { n: '上季度均值', vals: MODS.map((m, i) => +(PEOPLE.reduce((s, p) => s + LEVEL_HIST[p.n][2][i], 0) / PEOPLE.length).toFixed(1)), c: '#7b849c', dash: true }]) + CH.mini.legend([{ n: '本季度均值', c: CPAL[0] }, { n: '上季度均值', c: '#7b849c' }]) + '</div></div></div>'; },
  draw() { const host = $('#trbody'); const s = S.sub || 'course'; host.innerHTML = s === 'grade' ? this.grade() : s === 'sheet' ? this.sheets() : s === 'write' ? this.writeTab() : s === 'plan' ? this.plan() : s === 'bank' ? this.bank() : s === 'record' ? this.record() : this.courses(); if (s === 'sheet' && this.sheet) this.total(); CH.mount(host); }
};
PAGES.train = {
  render() { return cmdHTML(['从光差保护课件出五道题', '判一下刘一鸣的卷子', '给郭子扬打倒闸操作实操分', '刘一鸣最近怎么样', '按陈浩的短板组一套卷']) + pageHead('培训考评', '课程出题 · 培训计划 · 题库 · 判卷 · 实操评分表 · 成绩记录 · 回写图谱') + tabsHTML(TRAINPG.tabs, S.sub || 'course') + '<div id="trbody"></div>'; },
  after() { TRAINPG.draw(); }
};
document.addEventListener('input', e => { if (e.target.dataset && e.target.dataset.act === 'sh-in') TRAINPG.total(); });
Object.assign(ACT, {
  course(el) { TRAINPG.genQ(el.dataset.id); },
  'q-send'(el) { const who = el.dataset.who || '刘一鸣'; const plan = LS.get('plan', []); plan.push({ who, t: COURSES.find(c => c.id === TRAINPG.course).n + ' 测试', when: '本周', ts: Date.now() }); LS.set('plan', plan); XW.fly('试卷已发 ' + who + ' · 周五前完成'); XW.answer('发给' + who + '了，周五前做完，做完我判。', null, { confirm: false }); },
  'q-more'() { TRAINPG.genQ(TRAINPG.course); },
  'grade-run'() { TRAINPG.gradeRun(); },
  'grade-retest'() { const plan = LS.get('plan', []); plan.push({ who: '刘一鸣', t: '光差保护补考', when: '下周五', ts: Date.now() }); LS.set('plan', plan); XW.fly('补考已安排 · 刘一鸣 · 下周五'); XW.answer('补考排在下周五，我先让他重看第 8 页和第 15 页。', null, { confirm: false }); },
  sheet(el) { TRAINPG.sheet = el.dataset.id; TRAINPG.draw(); XW.answer('这张表 ' + SHEETS.find(s => s.id === el.dataset.id).rows.length + ' 项，满分默认填好了，扣分的地方你改数字就行，超过分值我会拦住。否决项一勾，整张表按不合格算。', null, { confirm: false }); },
  'sh-in'() {},
  'sh-veto'(el) { const on = el.checked; $('#veto').classList.toggle('on', on); TRAINPG.total(); if (on) XW.answer('勾了否决项，这次考核按不合格算，合计归零。评分标准写的是"出现恶性误操作扣 50 分"，但按考核办法否决项直接不通过，扣分的记录我保留在表里。', null, { confirm: false }); },
  'sh-save'() { const sh = SHEETS.find(s => s.id === TRAINPG.sheet); const who = $('#shwho').value; const t = TRAINPG.total(); const veto = $('#veto input').checked; const rows = sh.rows.map((r, i) => ({ r, v: +$$('input[data-act="sh-in"]')[i].value })); const lost = rows.filter(x => x.v < x.r.max).map(x => x.r.it + '扣 ' + (x.r.max - x.v)); const sc = LS.get('scores', {}); sc[who] = { sheet: sh.n, total: t, veto, lost, ts: Date.now() }; LS.set('scores', sc); XW.fly('成绩已保存 · ' + who + ' · ' + t + ' 分'); XW.answer(who + '的' + sh.n.split(' · ')[1] + '记了 ' + t + ' 分' + (lost.length ? '，扣分项：' + lost.join('、') + '，扣分理由我按评分标准写进备注了。' : '，满分。') + (veto ? '否决项已勾，按不合格记。' : '') + '等级建议在"回写图谱"里。', null, { confirm: false, chart: CH.mini.bars(rows.map(x => ({ n: x.r.it.slice(0, 6), v: x.v, txt: x.v + '/' + x.r.max, c: x.v < x.r.max ? '#e8791d' : CPAL[4] })), { max: 22, h: 12, x0: 70 }) }); },
  'lvw-confirm'(el) { const all = LS.get('levels', {}); all[el.dataset.who] = all[el.dataset.who] || {}; all[el.dataset.who][el.dataset.mod] = +el.dataset.to; LS.set('levels', all); XW.answer('记下了，' + el.dataset.who + '的"' + MODS.find(m => m.k === el.dataset.mod).n + '"按 ' + LV[+el.dataset.to] + ' 写进图谱，确认人赵立群。班组画像里那一格已经变了。', null, { confirm: false }); el.outerHTML = '<span class="tag ok">已确认</span>'; },
  'train-cell'(el) { const r = TRAIN_Y.find(x => x.c.startsWith(el.dataset.who.replace('…', ''))); const m = +el.dataset.i; const v = r ? r.m[m] : 0; XW.answer((m + 1) + ' 月' + (r ? '《' + r.c + '》' : '') + (v ? (m < 8 ? '已完成，' + PEOPLE.filter(p => (TRAIN_DONE[p.n] || []).some(id => (COURSES.find(c => c.n === r.c) || {}).id === id)).length + ' 人通过。' : m === 8 ? '本月进行中，刘一鸣、陈浩、周明 9-15 前考。' : '计划安排，对象是图谱上这一模块 L2 以下的人。') : '没有安排。要加的话我把它排进去。'), null, { confirm: false }); },
  'train-person'(el) { const n = el.dataset.who; const done = (TRAIN_DONE[n] || []).map(id => COURSES.find(c => c.id === id).n); const left = COURSES.filter(c => !(TRAIN_DONE[n] || []).includes(c.id)); XW.answer(n + '学了 ' + done.length + ' 门：' + (done.map(x => x.slice(0, 8)).join('、') || '无') + '。还有 ' + left.length + ' 门没学' + (left.length ? '，我建议先学《' + left[0].n + '》，对应他图谱最弱的模块。' : '。'), left.length ? '<div class="bt"><button data-act="train-assign" data-who="' + n + '" data-id="' + left[0].id + '">排给他</button></div>' : null, { confirm: false, chart: CH.mini.donut([{ k: '已学', v: done.length, c: CPAL[4] }, { k: '未学', v: left.length, c: RAMP[1] }], { sub: '门' }) }); },
  'train-assign'(el) { const plan = LS.get('plan', []); plan.push({ who: el.dataset.who, t: COURSES.find(c => c.id === el.dataset.id).n, when: '下周', ts: Date.now() }); LS.set('plan', plan); XW.fly('已加入下周培训计划 · ' + el.dataset.who); XW.answer('排进去了。', null, { confirm: false }); },
  'train-plan-next'() { const host = $('#tplanhost'); DOCGEN.stream(host, ['10 月培训计划（初稿）', '1. 继保专才《配网保护整定实用化》：全员，10-20 前理论测试；重点对象 [取一下图谱……] 陈浩、周明、刘一鸣（二次及保护 L1）。', '2. 《故障跳闸波形分析》：郭子扬、赵敏、王安。', '3. 实操：开关柜局放检测考核，吴倩、郭子扬，10-16。', '4. 师带徒：刘一鸣跟黄伟强继保旁站两次；陈浩跟韩雪现场组织一次。', '5. 安全日与安规考问：每周五一次，题库轮换。'], { chips: [{ k: 'short', n: '口气再简短些' }], done() { XW.answer('下月培训计划写好了，对象都是按图谱短板挑的。', null, { speak: false, confirm: false }); } }); DOCS.host = host; DOCS.kind = 'plan'; },
  'bank-course'(el) { TRAINPG.bankCourse = el.dataset.id; TRAINPG.draw(); },
  'bank-target'(el) { const p = P[el.dataset.who]; const lv = PEOPLEPG.lv(p); const wi = lv.indexOf(Math.min.apply(null, lv)); const c = COURSES.find(c => c.mod === MODS[wi].k) || COURSES[0]; XW.think(p.n + '图谱上最弱的是' + MODS[wi].n + '，' + LV[lv[wi]] + '。对应的课是《' + c.n + '》，他' + ((TRAIN_DONE[p.n] || []).includes(c.id) ? '学过，可以出难一点的' : '还没学，先出基础题') + '。', () => { ensure('train', () => TRAINPG.genQ(c.id, p.n), 'course'); }); },
  'rec-row'(el) { const n = el.dataset.who; const hs = (SCORE_HIST[n] || []); if (!hs.length) { XW.answer(n + '本年还没有考试记录。', null, { confirm: false }); return; } XW.answer(n + '本年考了 ' + hs.length + ' 次：' + hs.map(x => x.d + ' ' + x.t + ' ' + x.s + ' 分').join('、') + '。' + (hs[hs.length - 1].s < hs[0].s ? '最近一次比第一次低，要看看是不是那门课没跟上。' : hs.length > 1 ? '趋势是往上的。' : ''), null, { confirm: false, chart: CH.mini.line([{ n: '成绩', vals: hs.map(x => x.s), c: CPAL[0] }], hs.map(x => x.d), { max: 100, h: 100 }) }); }
});
