/* ===== 培训考评：从课件出题、判卷、三套实操评分表、回写图谱 ===== */
const TRAINPG = {
  tabs: [{ k: 'course', n: '课程与出题' }, { k: 'grade', n: '判卷' }, { k: 'sheet', n: '实操评分表' }, { k: 'write', n: '回写图谱' }],
  course: null, sheet: null,
  courses() { return '<div class="grid2" style="grid-template-columns:1fr 1.4fr"><div class="card"><div class="h"><b>课程库 · 继保专才 6 门 + 运维 1 门</b><span>点一门，她出 5 道新题</span></div><div class="crs">' + COURSES.map(c => '<a data-act="course" data-id="' + c.id + '" class="' + (this.course === c.id ? 'on' : '') + '"><span style="font-size:12px;color:var(--ink)">' + h(c.n) + '</span><span>' + c.pages + ' 页 · ' + h(MODS.find(m => m.k === c.mod).n.replace('能力', '')) + '</span></a>').join('') + '</div><div class="note" style="margin-top:8px">培训计划：' + (LS.get('plan', []).map(p => p.who + '《' + p.t + '》' + p.when).join('；') || '暂无') + '</div></div><div class="card" id="qcard"><div class="h"><b id="qtitle">出题</b><span id="qsub"></span></div><div class="qs" id="qs"><div class="empty">点左边的课程</div></div><div class="bt" id="qbt2" style="margin-top:8px"></div></div></div>'; },
  genQ(id) { const c = COURSES.find(x => x.id === id); this.course = id; $$('.crs a').forEach(a => a.classList.toggle('on', a.dataset.id === id)); $('#qtitle').textContent = c.n + ' · 出 5 题'; $('#qsub').textContent = '出处 ' + c.src; const host = $('#qs'); host.innerHTML = ''; XW.state('write'); XW.type($('#xwsub'), '我从《' + c.n + '》的课件里出 5 道题，每题标出处页码。', 45);
    c.qs.slice(0, 5).forEach((q, i) => XW.at(400 + i * 1500, () => { const d = document.createElement('div'); d.className = 'q'; d.innerHTML = '<b></b><span>' + q.a.map((a, j) => String.fromCharCode(65 + j) + '. ' + h(a)).join('　') + '</span><em>出处：' + h(c.src) + ' ' + h(q.pg) + '</em>'; host.appendChild(d); requestAnimationFrame(() => d.classList.add('in')); XW.type($('b', d), (i + 1) + '. ' + q.q, 22); }));
    XW.at(400 + Math.min(5, c.qs.length) * 1500 + 400, () => { XW.state(''); $('#qbt2').innerHTML = '<button data-act="q-send">发给刘一鸣</button><button class="g" data-act="q-more">换一批</button>'; XW.answer('五道题出好了，都是课件里有原文的，第 ' + (c.qs.length > 4 ? '3' : '2') + ' 题偏难。发给谁？', null, { confirm: false }); }); },
  grade() { const c = COURSES.find(x => x.id === ANSWER_SAMPLE.course); return '<div class="card"><div class="h"><b>判卷 · ' + h(ANSWER_SAMPLE.who) + ' · ' + h(c.n) + '</b><span>他的答卷已回收，她逐题对要点</span></div><div class="qs" id="gqs">' + c.qs.map((q, i) => '<div class="q in"><b>' + (i + 1) + '. ' + h(q.q) + '</b><span>他答：' + String.fromCharCode(65 + ANSWER_SAMPLE.ans[i]) + '. ' + h(q.a[ANSWER_SAMPLE.ans[i]]) + '<span class="mark" id="gm' + i + '" style="display:none"></span></span><em id="gr' + i + '"></em></div>').join('') + '</div><div class="bt" style="margin-top:8px" id="gbt"><button data-act="grade-run">判卷</button></div><div class="sheet"><div class="tot" id="gtot"></div></div></div>'; },
  gradeRun() { const c = COURSES.find(x => x.id === ANSWER_SAMPLE.course); XW.state('look', '正在判卷'); let ok = 0; c.qs.forEach((q, i) => XW.at(600 + i * 1300, () => { const good = ANSWER_SAMPLE.ans[i] === q.k; if (good) ok++; const m = $('#gm' + i); m.style.display = ''; m.textContent = good ? '对' : '错 · 应为 ' + String.fromCharCode(65 + q.k); m.className = 'mark' + (good ? '' : ' bad'); $('#gr' + i).textContent = good ? '' : '要点：' + q.a[q.k] + '（' + c.src + ' ' + q.pg + '）'; $('#gtot').innerHTML = '<span>已判 ' + (i + 1) + '/' + c.qs.length + '</span><b>' + Math.round(ok / c.qs.length * 100) + '</b><span>分</span>'; }));
    XW.at(600 + c.qs.length * 1300 + 200, () => { XW.state(''); const sc = Math.round(ok / c.qs.length * 100); const g = LS.get('grades', {}); g[ANSWER_SAMPLE.who] = { course: c.n, score: sc, ok, n: c.qs.length, ts: Date.now() }; LS.set('grades', g); XW.answer('刘一鸣 ' + c.qs.length + ' 题对了 ' + ok + ' 道，' + sc + ' 分。错的都在差动判据和光纤参数这两处，说明原理没吃透。我建议这门课重学第 8 页和第 15 页，再考一次；图谱上"二次及保护能力"暂时保持 L1。', null, { speak: false }); XW.card('<div class="bt" style="margin-top:0"><button data-act="nav" data-to="train" data-sub="write">去回写图谱</button><button class="g" data-act="grade-retest">安排补考</button></div>'); $('#gbt').innerHTML = '<span class="tag ok">已判 · ' + sc + ' 分</span>'; }); },
  sheets() { const sh = this.sheet ? SHEETS.find(s => s.id === this.sheet) : null; const sc = LS.get('scores', {}); return '<div class="grid2" style="grid-template-columns:1fr 2fr"><div class="card"><div class="h"><b>实操评分表</b><span>三套 · 逐项打分</span></div><div class="crs">' + SHEETS.map(s => '<a data-act="sheet" data-id="' + s.id + '" class="' + (this.sheet === s.id ? 'on' : '') + '"><span style="font-size:12px;color:var(--ink)">' + h(s.n) + '</span><span>' + s.rows.length + ' 项 · ' + h(s.time) + '</span></a>').join('') + '</div><div class="note" style="margin-top:8px">' + Object.keys(sc).map(k => k + '：' + sc[k].sheet.split(' · ')[1] + ' ' + sc[k].total + ' 分').join('；') + '</div></div>' +
    '<div class="card sheet" id="sheetcard">' + (sh ? '<div class="h"><b>' + h(sh.n) + '</b><span>考评对象 <select id="shwho" style="font:inherit">' + PEOPLE.filter(p => !/班长/.test(p.post)).map(p => '<option' + (p.n === '郭子扬' ? ' selected' : '') + '>' + h(p.n) + '</option>').join('') + '</select></span></div><div class="tbl"><table class="t"><tr><th>项目</th><th>考核要求</th><th>分值</th><th>评分标准</th><th>得分</th></tr>' + sh.rows.map((r, i) => '<tr><td><b>' + h(r.it) + '</b><br><span class="note">' + h(r.g) + '</span></td><td style="font-size:11px">' + h(r.req) + '</td><td style="font-family:var(--mono)">' + r.max + '</td><td style="font-size:11px;color:var(--ink3)">' + h(r.std) + '</td><td><input data-act="sh-in" data-i="' + i + '" data-max="' + r.max + '" value="' + r.max + '" inputmode="numeric"></td></tr>').join('') + '</table></div><div class="tot"><label class="veto" id="veto"><input type="checkbox" data-act="sh-veto"> 否决项：' + h(sh.veto) + '</label><span style="margin-left:auto">合计</span><b id="shtot">100</b><span>/ 100</span><button data-act="sh-save">保存成绩</button></div>' : '<div class="empty">点左边的评分表</div>') + '</div></div>'; },
  total() { const sh = SHEETS.find(s => s.id === this.sheet); if (!sh) return 0; let t = 0; $$('input[data-act="sh-in"]').forEach(inp => { let v = +inp.value; const mx = +inp.dataset.max; if (isNaN(v) || v < 0) v = 0; if (v > mx) { inp.classList.add('bad'); v = mx; } else inp.classList.remove('bad'); t += v; }); if ($('#veto input').checked) t = 0; $('#shtot').textContent = t; return t; },
  writeTab() { const g = LS.get('grades', {}); const sc = LS.get('scores', {}); const sugg = []; Object.keys(g).forEach(n => sugg.push({ who: n, mod: 'relay', from: PEOPLEPG.lv(P[n])[3], to: g[n].score >= 80 ? Math.min(5, PEOPLEPG.lv(P[n])[3] + 1) : PEOPLEPG.lv(P[n])[3], why: g[n].course + ' 理论 ' + g[n].score + ' 分' })); Object.keys(sc).forEach(n => { const mi = sc[n].sheet.includes('局放') ? 0 : 6; sugg.push({ who: n, mod: MODS[mi].k, from: PEOPLEPG.lv(P[n])[mi], to: sc[n].total >= 85 ? Math.min(5, PEOPLEPG.lv(P[n])[mi] + 1) : PEOPLEPG.lv(P[n])[mi], why: sc[n].sheet.split(' · ')[1] + ' 实操 ' + sc[n].total + ' 分' + (sc[n].veto ? '（否决）' : '') }); });
    return '<div class="card"><div class="h"><b>回写图谱 · 等级建议</b><span>成绩进图谱前先经班组长确认</span></div>' + (sugg.length ? '<div class="tbl"><table class="t"><tr><th>人员</th><th>模块</th><th>现等级</th><th>建议</th><th>依据</th><th></th></tr>' + sugg.map((s, i) => '<tr><td>' + h(s.who) + '</td><td>' + h(MODS.find(m => m.k === s.mod).n) + '</td><td>' + h(LV[s.from]) + '</td><td>' + (s.to > s.from ? '<span class="tag ok">升 ' + h(LV[s.to]) + '</span>' : '<span class="tag">保持 ' + h(LV[s.to]) + '</span>') + '</td><td class="note">' + h(s.why) + '</td><td><button class="s" data-act="lvw-confirm" data-who="' + s.who + '" data-mod="' + s.mod + '" data-to="' + s.to + '">确认</button></td></tr>').join('') + '</table></div>' : '<div class="empty">判一次卷或打一次实操分，建议就出现在这里</div>') + '<div class="loop" style="margin-top:8px">' + LOOP.map((l, i) => '<div class="' + (i === 3 || i === 5 ? 'on' : '') + '">' + (i + 1) + ' ' + l + '</div>').join('') + '</div></div>'; },
  draw() { const host = $('#trbody'); const s = S.sub || 'course'; host.innerHTML = s === 'grade' ? this.grade() : s === 'sheet' ? this.sheets() : s === 'write' ? this.writeTab() : this.courses(); if (s === 'sheet' && this.sheet) this.total(); }
};
PAGES.train = {
  render() { return cmdHTML(['从光差保护课件出五道题', '判一下刘一鸣的卷子', '给郭子扬打倒闸操作实操分', '刘一鸣最近怎么样']) + pageHead('培训考评', '课程出题 · 判卷 · 实操评分表 · 回写图谱') + tabsHTML(TRAINPG.tabs, S.sub || 'course') + '<div id="trbody"></div>'; },
  after() { TRAINPG.draw(); }
};
document.addEventListener('input', e => { if (e.target.dataset && e.target.dataset.act === 'sh-in') TRAINPG.total(); });
Object.assign(ACT, {
  course(el) { TRAINPG.genQ(el.dataset.id); },
  'q-send'() { const plan = LS.get('plan', []); plan.push({ who: '刘一鸣', t: COURSES.find(c => c.id === TRAINPG.course).n + ' 测试', when: '本周', ts: Date.now() }); LS.set('plan', plan); XW.fly('试卷已发 刘一鸣 · 周五前完成'); XW.answer('发给刘一鸣了，周五前做完，做完我判。', null, { confirm: false }); },
  'q-more'() { TRAINPG.genQ(TRAINPG.course); },
  'grade-run'() { TRAINPG.gradeRun(); },
  'grade-retest'() { const plan = LS.get('plan', []); plan.push({ who: '刘一鸣', t: '光差保护补考', when: '下周五', ts: Date.now() }); LS.set('plan', plan); XW.fly('补考已安排 · 刘一鸣 · 下周五'); XW.answer('补考排在下周五，我先让他重看第 8 页和第 15 页。', null, { confirm: false }); },
  sheet(el) { TRAINPG.sheet = el.dataset.id; TRAINPG.draw(); XW.answer('这张表 ' + SHEETS.find(s => s.id === el.dataset.id).rows.length + ' 项，满分默认填好了，扣分的地方你改数字就行，超过分值我会拦住。否决项一勾，整张表按不合格算。', null, { confirm: false }); },
  'sh-in'() {},
  'sh-veto'(el) { const on = el.checked; $('#veto').classList.toggle('on', on); TRAINPG.total(); if (on) XW.answer('勾了否决项，这次考核按不合格算，合计归零。评分标准写的是"出现恶性误操作扣 50 分"，但按考核办法否决项直接不通过，扣分的记录我保留在表里。', null, { confirm: false }); },
  'sh-save'() { const sh = SHEETS.find(s => s.id === TRAINPG.sheet); const who = $('#shwho').value; const t = TRAINPG.total(); const veto = $('#veto input').checked; const lost = sh.rows.map((r, i) => ({ r, v: +$$('input[data-act="sh-in"]')[i].value })).filter(x => x.v < x.r.max).map(x => x.r.it + '扣 ' + (x.r.max - x.v)); const sc = LS.get('scores', {}); sc[who] = { sheet: sh.n, total: t, veto, lost, ts: Date.now() }; LS.set('scores', sc); XW.fly('成绩已保存 · ' + who + ' · ' + t + ' 分'); XW.answer(who + '的' + sh.n.split(' · ')[1] + '记了 ' + t + ' 分' + (lost.length ? '，扣分项：' + lost.join('、') + '，扣分理由我按评分标准写进备注了。' : '，满分。') + (veto ? '否决项已勾，按不合格记。' : '') + '等级建议在"回写图谱"里。', null, { confirm: false }); },
  'lvw-confirm'(el) { const all = LS.get('levels', {}); all[el.dataset.who] = all[el.dataset.who] || {}; all[el.dataset.who][el.dataset.mod] = +el.dataset.to; LS.set('levels', all); XW.answer('记下了，' + el.dataset.who + '的"' + MODS.find(m => m.k === el.dataset.mod).n + '"按 ' + LV[+el.dataset.to] + ' 写进图谱，确认人赵立群。班组画像里那一格已经变了。', null, { confirm: false }); el.outerHTML = '<span class="tag ok">已确认</span>'; }
});
