/* 冒烟回归（9/21 口径）：班组长 · 班组管理六页（班组画像 / 班员画像 / 培养与梯队 / 绩效与激励 / 关怀与文化 / 分析参谋）+ 日常业务主线（工作台派工 → 审票 → 开工 → 完工 → 回写）+ 知识库三类；管理者 · 八页（年度指标 / 横向对比 → 跨班组调配 / 团队画像 / 人员总览与六维画像 / 结构对比 / 风险画像 / 员工关怀 / 分析参谋）· 刷新持久 · 讲师演示台 · 界面禁词
   用法：node smoke.cjs  （需要 /home/user/-/node_modules/playwright 与 /opt/pw-browsers）期望：FAILS 0 ERR none */
const { chromium } = require(process.env.PW || '/home/user/-/node_modules/playwright');
const path = require('path');
const file = 'file://' + path.join(__dirname, 'dist', '小瓦特班_班组长AI助手_高保真原型.html');
const fs = require('fs'); const SHOT = path.join(__dirname, 'shots'); fs.mkdirSync(SHOT, { recursive: true });
const BAN = /演示|待建|下一版本|比赛|评委|一期|门禁|手术|骨架|人力资源部|上帝|发起方|所里|所长|凤凰线|塘尾线|志远站|光明变|塘家/;
(async () => {
  const br = await chromium.launch(); const ctx = await br.newContext({ viewport: { width: 1440, height: 900 } }); const pg = await ctx.newPage();
  const errs = []; pg.on('pageerror', e => errs.push('pageerror ' + e.message)); pg.on('console', m => { if (m.type() === 'error') errs.push('console ' + m.text()); });
  await pg.addInitScript(() => { window.__XW_SPEED = 0.03; });
  let fails = 0; const t = async (name, cond) => { let ok = false; try { ok = await cond(); } catch (e) { ok = false; errs.push('test ' + name + ': ' + e.message.slice(0, 160)); } console.log((ok ? 'PASS ' : 'FAIL ') + name); if (!ok) fails++; };
  const w = ms => pg.waitForTimeout(ms); const ws = async (sel, ms) => { try { await pg.waitForSelector(sel, { timeout: ms || 8000 }); } catch (e) { errs.push('wait ' + sel); } };
  const go = async (hs, ms) => { await pg.evaluate(x => { location.hash = x; }, hs); await w(ms || 500); };
  const LS = k => pg.evaluate(k => JSON.parse(localStorage.getItem('xwb_' + k) || 'null'), k);
  const main = () => pg.locator('#main').innerText();
  const ev = f => pg.evaluate(f);
  const clean = async (name) => { const txt = (await main()) + ' ' + (await pg.locator('#sb').innerText()) + ' ' + (await pg.locator('#chat').innerText().catch(() => '')) + ' ' + (await pg.locator('#modal').innerText().catch(() => '')); const m = txt.match(BAN); await t('禁词 ' + name, async () => { if (m) errs.push('ban ' + name + ': ' + m[0]); return !m; }); };
  await pg.goto(file); await w(2500);
  /* ---------- 班组长 · 班组画像（落地页） ---------- */
  await t('shell 班组长 11 项 · 落地班组画像', async () => (await pg.locator('#sb a').count()) === 11 && (await pg.locator('#sb a.on').textContent()).includes('班组画像') && (await pg.locator('#xw').count()) === 1);
  await t('荣誉标签 · 星级 + 集体荣誉 2 + 特色标签', async () => (await pg.locator('.startag').count()) === 1 && (await pg.locator('.hitem').count()) === 2 && (await pg.locator('.kindrow .tag').textContent()) === '骨干型');
  await t('建设差距标识 · 初步评分四星 · 必备条件 6/7', async () => { const B = await ev(() => buildScore()); return B.pct >= 80 && B.pct < 90 && B.lv === '四星' && B.mustBad.length === 1 && (await pg.locator('.alert.bad').count()) === 1; });
  await t('星级维度 20 行 · 红黄绿标识', async () => (await pg.locator('table.dims tr').count()) === 21 && (await pg.locator('table.dims .rag.bad').count()) >= 1 && (await pg.locator('table.dims .rag.w').count()) >= 3 && (await pg.locator('table.dims .rag.ok').count()) >= 8);
  await pg.click('[data-act="team-dim"][data-k="b14"]'); await w(400);
  await t('差距明细弹层 · 标准 / 现状 / 差距 / 建议 / 路径', async () => (await pg.locator('#modal:not([hidden]) table tr').count()) === 6 && (await pg.locator('#modal').textContent()).includes('提升建议'));
  await pg.click('#modal [data-act="team-fix"]'); await w(500);
  await t('排进班组计划 · 写 plan + 通知副班长', async () => { const p = await LS('plan'); const f = await LS('team_fix'); const n = await LS('notices'); return p && p.some(x => /党建水平/.test(x.t)) && f && f.b14 && n.some(x => x.to === '韩雪' && /星级建设差距/.test(x.t)); });
  await pg.click('[data-act="team-fixall"]'); await w(500);
  await t('全部排进计划 · 提升建议全部标记', async () => (await pg.locator('#fixlist .tag.ok').count()) >= 5 && (await pg.locator('#fixlist button').count()) === 0);
  await clean('班组画像');
  await pg.screenshot({ path: SHOT + '/01_team.png' });
  /* ---------- 班员画像：六维个人画像 + 技能矩阵 + 人才断层 ---------- */
  await go('#skills', 700);
  await t('左栏改名班员画像 · 路由不变', async () => (await pg.locator('#sb a').nth(1).innerText()).includes('班员画像') && (await ev(() => location.hash)) === '#skills' && (await main()).includes('六维个人画像'));
  await t('六维雷达 + 六维条 6 行 · 默认韩雪 · 由班组长确认后使用', async () => (await pg.locator('.hexl svg').count()) >= 1 && (await pg.locator('.sixrows>div').count()) === 6 && (await pg.locator('.hexhead b').innerText()) === '韩雪' && (await pg.locator('.hexwrap .cf').innerText()).includes('由班组长确认后使用'));
  await t('优势特长 / 可提升 + 均值对照', async () => { const x = await pg.locator('.hexwrap').innerText(); return /优势特长/.test(x) && /可提升/.test(x) && /均值/.test(x); });
  await t('技能矩阵 12 行 · 断层视图 9 类 · 高风险 ≥ 1', async () => (await pg.locator('table.skm tr').count()) === 13 && (await pg.locator('[data-act="skill-teach"]').count()) >= 1 && (await pg.locator('.s9').count()) === 12 && (await main()).includes('断层风险'));
  await pg.click('table.skm tr[data-who="刘一鸣"]'); await w(600);
  await t('点名单行切画像 · 当前行高亮', async () => (await pg.locator('.hexhead b').innerText()) === '刘一鸣' && (await pg.locator('table.skm tr.on').count()) === 1 && (await pg.locator('table.skm tr.on').getAttribute('data-who')) === '刘一鸣');
  await pg.click('.sixrows>div[data-i="4"]'); await w(500);
  await t('点某一维 · 本班 12 人排序弹层 + 差值', async () => (await pg.locator('#modal:not([hidden]) table tr').count()) === 13 && (await pg.locator('#modal .mono.g, #modal .mono.b').count()) >= 10 && (await pg.locator('#modal').innerText()).includes('写作能力'));
  await pg.click('#modal table tr:last-child [data-act="sk-pick"]'); await w(600);
  await t('弹层里看画像 · 切到该员工', async () => (await pg.locator('#modal').isHidden()) && (await pg.locator('table.skm tr.on').count()) === 1 && (await pg.locator('.hexhead b').innerText()) === (await pg.locator('table.skm tr.on td b').innerText()));
  const who1 = await pg.locator('.hexhead b').innerText();
  await pg.click('[data-act="sk-plan"]'); await w(600);
  await t('按短板排培养任务 · 写 plan + 通知', async () => { const p = await LS('plan'); const n = await LS('notices'); return p.some(x => x.who === who1 && x.why === '六维短板') && n.some(x => x.to === who1); });
  await pg.click('[data-act="sk-talk"]'); await w(1600);
  await t('写进面谈提纲 · 跳关怀与文化并出提纲', async () => { const h = await ev(() => location.hash); const c = await pg.locator('#chat').innerText(); return h.startsWith('#care') && c.includes(who1 + ' · ') && /提纲/.test(c) && (await pg.locator('#chat .doc').count()) >= 1; });
  await t('重点关注名单已写入该员工', async () => (await main()).includes(who1));
  await ev(() => XW.clearChat()); await go('#skills', 600);
  await pg.click('[data-act="sk-teachall"]'); await w(500);
  await t('高风险全部排带教 · 写 plan', async () => { const p = await LS('plan'); return p.filter(x => x.why === '断层风险 高').length >= 1; });
  await clean('班员画像');
  await pg.screenshot({ path: SHOT + '/02_skills.png' });
  /* ---------- 培养与梯队 ---------- */
  await go('#grow', 700);
  await t('师带徒 4 卡 · 骨干培养 4 人 · 梯队漏斗', async () => (await pg.locator('.mcard').count()) === 4 && (await pg.locator('.bbrow').count()) === 4 && (await pg.locator('.mrow').count()) === 4);
  await pg.click('[data-act="grow-task"][data-who="刘一鸣"]'); await w(500);
  await t('排带教任务 · plan + 师傅通知', async () => { const p = await LS('plan'); const n = await LS('notices'); return p.some(x => x.who === '刘一鸣' && x.why === '师带徒') && n.some(x => x.to === '黄伟强' && /带教任务/.test(x.t)); });
  await pg.click('[data-act="grow-bb"][data-i="0"]'); await w(600);
  await t('骨干培养记一项完成 · 进度 3/3', async () => { const b = await LS('backbone'); return b && b['韩雪'] === 3 && (await main()).includes('条件齐'); });
  await clean('培养与梯队');
  await pg.screenshot({ path: SHOT + '/03_grow.png' });
  /* ---------- 绩效与激励 ---------- */
  await go('#perf', 700);
  await t('绩效表 12 行 · 系数 · 物质 / 非物质', async () => (await pg.locator('table.perf tr').count()) === 13 && (await main()).includes('评优推荐') && (await main()).includes('¥'));
  await pg.click('[data-act="perf-adj"][data-who="王安"][data-v="0.02"]'); await w(500);
  await t('系数调整落 perf_adj', async () => { const a = await LS('perf_adj'); return a && a['王安'] === 0.02; });
  await pg.click('[data-act="perf-sheet"]'); await w(600);
  await t('未确认不能生成分配表', async () => (await pg.locator('.msg.a').last().textContent()).includes('没确认'));
  await pg.click('[data-act="perf-okall"]'); await w(500);
  await t('全部确认 · 12 人', async () => { const o = await LS('perf_ok'); return o && Object.keys(o).length === 12; });
  await pg.click('[data-act="perf-sheet"]'); await ws('[data-act="perf-sheet-save"]', 20000); await pg.click('[data-act="perf-sheet-save"]'); await w(500);
  await t('激励分配表存文稿 · 报陈国安', async () => { const d = await LS('docs'); const n = await LS('notices'); return d && d['perf-2026-08'] && /¥/.test(d['perf-2026-08'].body) && n.some(x => x.to === '陈国安' && /激励分配表/.test(x.t)); });
  await clean('绩效与激励');
  await pg.screenshot({ path: SHOT + '/04_perf.png' });
  /* ---------- 关怀与文化 ---------- */
  await go('#care', 700);
  const careN = await pg.locator('.carerow').count();
  await t('关怀提醒 ≥ 6 · 三类 · 重点关注 3 · 活动记录 5', async () => careN >= 6 && (await main()).includes('入职关键年份') && (await main()).includes('回访提醒') && (await main()).includes('高强度关怀') && (await pg.locator('.focusrow').count()) === 3);
  await pg.click('[data-act="care-done"] >> nth=0'); await w(500);
  await t('关怀已办 · 写 care_done · 左栏角标减一', async () => { const d = await LS('care_done'); return d && Object.keys(d).length === 1 && (await pg.locator('.carerow.done').count()) === 1; });
  await pg.click('[data-act="care-msg"] >> nth=0'); await ws('[data-act="care-send"]', 20000); await pg.click('[data-act="care-send"]'); await w(400);
  await t('写一段话 · 发给本人', async () => { const n = await LS('notices'); return n.some(x => /班长的话/.test(x.t)); });
  await pg.click('[data-act="focus-guide"][data-who="王安"]'); await ws('[data-act="guide-save"]', 20000); await pg.click('[data-act="guide-save"]'); await w(400);
  await t('绩效面谈提纲 · 逐段生成 · 存文稿', async () => { const d = await LS('docs'); return (await pg.locator('.msg .doc p').count()) >= 6 && d['guide-王安'] && /绩效面谈/.test(d['guide-王安'].t); });
  await pg.click('[data-act="cult-add"]'); await ws('#cu-t'); await pg.selectOption('#cu-k', '帮扶'); await pg.fill('#cu-t', '终端调试跨班组带教（配电运维一班）'); await pg.click('[data-act="cult-add-ok"]'); await w(600);
  await t('记一次帮扶活动 · 星级「班组帮扶」得分 2 → 5', async () => { const a = await LS('culture_add'); const d = await ev(() => buildDims().find(x => x.k === 'b26')); return a && a.length === 1 && d.scV === 5 && d.cls === 'ok'; });
  await clean('关怀与文化');
  await pg.screenshot({ path: SHOT + '/05_care.png' });
  /* ---------- 分析参谋 ---------- */
  await go('#advise', 700);
  await t('队伍诊断 · 根因标签 ≥ 3 · 四段结论 · 两图', async () => (await pg.locator('.root').count()) >= 3 && (await pg.locator('.diagtext li').count()) === 4 && (await pg.locator('#main svg.ch').count()) >= 2);
  await pg.click('[data-act="adv-report"][data-k="diag"]'); await ws('[data-act="adv-save"]', 30000); await pg.click('[data-act="adv-save"]'); await w(400);
  await t('诊断报告逐段生成 · 存文稿', async () => { const d = await LS('docs'); return (await pg.locator('#advdoc p').count()) >= 6 && d['adv-diag']; });
  await go('#advise/grow', 700);
  await t('培养参谋 · 推荐排序 ≥ 6 · 理由 / 短板 / 方案 / 风险', async () => (await pg.locator('table.cand tr').count()) >= 7 && (await main()).includes('推荐理由') && (await main()).includes('潜在短板') && (await main()).includes('风险提示'));
  await pg.click('[data-act="adv-planall"]'); await w(600);
  await t('前三名排进计划', async () => { const p = await LS('plan'); return p.filter(x => x.why === '培养参谋').length >= 3 && (await pg.locator('table.cand .tag.ok').count()) >= 3; });
  await clean('分析参谋');
  await pg.screenshot({ path: SHOT + '/06_advise.png' });
  /* ---------- 日常业务主线：工作台派工 → 周节点 → 催办 ---------- */
  await go('#home', 800);
  await t('工作台三张决策卡 · 六张图', async () => (await pg.locator('#dec .dc.in').count()) === 3 && (await pg.locator('#d1').textContent()).includes('田寮站 F02') && (await pg.locator('.charts .card.chart').count()) === 6);
  await pg.click('[data-act="home-swap"]'); await ws('#xpl.in', 20000); await w(300);
  await t('派工理由表 推荐 2 · 随队 1 · 排除 9', async () => (await pg.locator('#xpl tr.in').count()) === 2 && (await pg.locator('#xpl tr.fo').count()) === 1 && (await pg.locator('#xpl tr.ex').count()) === 9);
  await pg.click('#ppl .chip[data-who="韩雪"]'); await w(600);
  await pg.click('[data-act="home-go"]'); await ws('#d1.ok', 20000); await w(400);
  await t('派工单落 DB · 票据草稿', async () => { const d = await LS('dispatch'); const tk = await LS('tickets_add'); return d && d.j1 && d.j1.lead === '韩雪' && Array.isArray(tk) && tk.some(x => x.jobId === 'j1'); });
  await pg.click('[data-act="nodes-plan"]'); await w(2500);
  await t('周报靠后项写成本周重点', async () => { const f = await LS('nodefocus'); return Array.isArray(f) && f.length >= 3; });
  await pg.click('[data-act="urge"]'); await ws('[data-act="urge-send"]'); await pg.click('[data-act="urge-send"]'); await w(500);
  await t('催办已发 · 缺陷状态改', async () => { const d = await LS('defects'); return d && d.d5 && /催办/.test(d.d5.st); });
  await clean('工作台');
  await pg.screenshot({ path: SHOT + '/07_home.png' });
  /* ---------- 审票 → 开工 → 回传 → 完工 → 实操量回写 ---------- */
  await go('#sched/pool', 700);
  await t('任务池 7 项', async () => (await pg.locator('.job').count()) === 7);
  await pg.click('[data-act="job-start"][data-id="j4"]'); await ws('.msg.a [data-act="job-ticket"]');
  await pg.click('.msg.a [data-act="job-ticket"]'); await w(800);
  await pg.click('[data-act="ticket-review"]'); await ws('[data-act="ticket-fix"]', 20000); await w(300); await pg.click('[data-act="ticket-fix"]'); await w(800);
  await t('审票补齐 · 票已审核', async () => { const s = await LS('tickets'); return s && s['配自 2026-0807-01'] && s['配自 2026-0807-01'].st === '已审核'; });
  await go('#sched/pool', 700);
  await pg.click('[data-act="job-start"][data-id="j4"]'); await w(900); await pg.click('[data-act="job-report"][data-id="j4"]'); await w(900); await pg.click('[data-act="job-finish"][data-id="j4"]'); await w(1200);
  await t('完工 · 工时 · 实操量回写', async () => { const h = await LS('hours_add'); const sw = await LS('skillw'); return h && h.some(r => r.who === '吴倩') && sw && sw.length === 1; });
  await t('完工后星级「作业实施」得分随回写变化', async () => { const d = await ev(() => buildDims().find(x => x.k === 'b32')); return d.scV === 447; });
  await clean('用工安排');
  /* ---------- 知识库三类 ---------- */
  await go('#know', 700);
  await t('知识库三类卡 · 计数', async () => (await pg.locator('.kb3c').count()) === 3 && (await main()).includes('制度政策类') && (await main()).includes('生产技术类') && (await main()).includes('行政办公类'));
  await pg.click('.kb3c[data-k="行政办公类"]'); await w(400);
  await t('行政办公类 5 条', async () => (await pg.locator('.kbitem').count()) === 5 && (await pg.locator('.kb3c.on').count()) === 1);
  await pg.click('[data-act="kb-ask"][data-q="差旅报销要附什么"]'); await ws('#kba .src'); await w(600);
  await t('行政办公问答 · 出处', async () => (await pg.locator('#kbtext').textContent()).includes('派工单') && (await pg.locator('#kba .src').textContent()).includes('费用报销管理办法'));
  await pg.click('.kb3c[data-k="制度政策类"]'); await w(300);
  await t('制度政策类含星级评价与轮岗', async () => { const txt = await pg.locator('#kblist').innerText(); return txt.includes('星级班组评价') && txt.includes('敏感岗位轮岗'); });
  await clean('知识库');
  await pg.screenshot({ path: SHOT + '/08_know.png' });
  /* ---------- 刷新持久 ---------- */
  await go('#team', 300); await pg.reload(); await w(2500);
  await t('刷新后班组画像 · 计划与确认仍在', async () => (await pg.locator('#sb a.on').textContent()).includes('班组画像') && (await pg.locator('#fixlist .tag.ok').count()) >= 5 && Object.keys(await LS('perf_ok')).length === 12);
  /* ---------- 管理者 ---------- */
  await pg.click('.rsw button[data-r="manager"]'); await w(1800);
  await t('切到管理者 · 10 项 · 年度指标任务', async () => (await pg.locator('#sb a').count()) === 10 && (await ev(() => location.hash)) === '#goals' && (await pg.locator('table.goals tr').count()) === 13 && (await pg.locator('.card.kpi').count()) === 4);
  await t('红黄绿 · 目标值 / 摸高值 / 注意事项', async () => (await pg.locator('table.goals .rag.bad').count()) >= 2 && (await pg.locator('table.goals .rag.ok').count()) >= 5 && (await main()).includes('摸高值') && (await main()).includes('注意事项'));
  await pg.click('[data-act="goal-open"][data-k="g4"]'); await w(400);
  await t('指标下钻到班组 · 三班组行', async () => (await pg.locator('#modal:not([hidden]) table tr').count()) === 4 && (await pg.locator('#modal').textContent()).includes('陈志远'));
  await pg.click('#modal [data-act="goal-urge"] >> nth=0'); await w(600);
  await t('督办 → 班长通知 · 记录', async () => { const n = await LS('notices'); const u = await LS('goal_urge'); return u && u.g4 && n.some(x => x.to === '赵立群' && /督办 · 缺陷限时闭环率/.test(x.t)); });
  await clean('年度指标任务');
  await pg.screenshot({ path: SHOT + '/09_goals.png' });
  await go('#compare', 700);
  await t('横向对比 9 维 × 3 班组 · 最好 / 最需关注', async () => (await pg.locator('table.cmp tr').count()) === 10 && (await pg.locator('.cmpv.ok').count()) >= 8 && (await pg.locator('.cmpv.bad').count()) >= 5 && (await main()).includes('是否需要跨班组调配'));
  await pg.click('[data-act="cmp-transfer"]'); await ws('.impact > div', 20000); await w(600);
  await t('发起跨班组调配 → 影响测算三格', async () => (await ev(() => location.hash)) === '#risk/sim' && (await pg.locator('.impact > div').count()) === 3);
  await pg.click('[data-act="sim-go"]'); await w(800);
  await t('调配待确认 · 两位班长收通知', async () => { const tr = await LS('transfers'); const n = await LS('notices'); return tr && tr.length === 1 && tr[0].st === '待确认' && tr[0].who === '郑浩' && tr[0].from === '配电运维一班' && n.filter(x => /调配待确认/.test(x.t)).length >= 2; });
  await pg.screenshot({ path: SHOT + '/10_compare_sim.png' });
  await go('#portrait', 700);
  await t('团队画像 3 卡 · 星级 / 荣誉 / 特色 · 班长队伍 3 行', async () => (await pg.locator('.tcard').count()) === 3 && (await pg.locator('.tcard .startag').count()) === 3 && (await main()).includes('专家型') && (await main()).includes('基础型') && (await pg.locator('[data-act="pt-backup"]').count()) === 3);
  await pg.click('[data-act="pt-backup"][data-i="2"]'); await w(500);
  await t('后备培养 → 班长通知', async () => { const n = await LS('notices'); const s = await LS('sup_talent'); return n.some(x => x.to === '陈志远' && /后备培养 · 林小虎/.test(x.t)) && s && s['林小虎']; });
  await clean('团队画像总览');
  await pg.screenshot({ path: SHOT + '/11_portrait.png' });
  await go('#staff', 700);
  await t('人员总览 · 31 人 · 三图 · 清单 12', async () => (await main()).includes('31') && (await pg.locator('#main svg.ch').count()) >= 3 && (await pg.locator('#stlist tr').count()) === 13);
  await pg.click('[data-act="st-team"][data-n="试验班"]'); await w(500);
  await t('下钻试验班 8 人', async () => (await pg.locator('#stlist tr').count()) === 9);
  await pg.click('#stlist tr[data-who="张伟"]'); await w(600);
  await t('六维个人画像 · 六边形 + 均值 + 优势', async () => (await pg.locator('#hexhost svg polygon').count()) >= 7 && (await pg.locator('.sixrows > div').count()) === 6 && (await pg.locator('#hexhost').textContent()).includes('优势特长'));
  await clean('人员总览');
  await pg.screenshot({ path: SHOT + '/12_staff.png' });
  await go('#structure', 700);
  await t('结构对比 · 强 / 弱标识 · 10 维', async () => (await main()).match(/弱/) && (await pg.locator('table.cmp tr').count()) === 11 && (await pg.locator('[data-act="stc-rotate"]').count()) === 3);
  await pg.click('[data-act="stc-rotate"][data-k="r1"]'); await w(500);
  await t('轮岗建议 → 两位班长待确认', async () => { const n = await LS('notices'); const s = await LS('rotate_sugg'); return s && s.r1 && n.filter(x => /轮岗建议/.test(x.t) && x.st === '待确认').length === 2; });
  await clean('班组结构对比');
  await pg.screenshot({ path: SHOT + '/13_structure.png' });
  await go('#risks', 700);
  await t('风险画像 四类 · 清单 ≥ 10', async () => (await pg.locator('.card.kpi').count()) === 4 && (await pg.locator('#main table tr').first().count()) === 1 && (await pg.locator('[data-act="rk-act"]').count()) >= 10);
  await pg.click('[data-act="rk-act"] >> nth=0'); await w(500);
  await t('敏感岗位轮岗提醒 → 班长', async () => { const n = await LS('notices'); return n.some(x => /敏感岗位轮岗提醒/.test(x.t)); });
  await clean('团队风险画像');
  await pg.screenshot({ path: SHOT + '/14_risks.png' });
  await go('#mcare', 700);
  await t('员工关怀 · 重点关注 7 · 三类提纲 · 文化活动 6', async () => (await pg.locator('.focusrow').count()) === 7 && (await pg.locator('details.fold').count()) === 3 && (await pg.locator('#main table tr').count()) === 7);
  await pg.click('[data-act="mc-guide"][data-who="何静"]'); await ws('[data-act="mc-guide-send"]', 30000); await pg.click('[data-act="mc-guide-send"]'); await w(500);
  await t('关怀面谈提纲 · 发给班长', async () => { const n = await LS('notices'); const d = await LS('docs'); return (await pg.locator('#mcdoc p').count()) >= 6 && n.some(x => x.to === '周建国' && /关怀面谈提纲 · 何静/.test(x.t)) && d['guide-何静']; });
  await pg.click('[data-act="cd-approve"]'); await w(400); await pg.click('[data-act="cd-notify"] >> nth=0'); await w(500);
  await t('文化活动 · 批准 · 发通知三位班长', async () => { const c = await LS('culture_dept'); const n = await LS('notices'); return c && Object.values(c).some(x => x.st === '已批') && n.filter(x => /文化活动通知/.test(x.t)).length >= 3; });
  await clean('员工关怀');
  await pg.screenshot({ path: SHOT + '/15_mcare.png' });
  await go('#madvise', 700);
  await pg.click('[data-act="ma-gen"][data-k="all"]'); await ws('[data-act="ma-send"]', 40000); await pg.click('[data-act="ma-send"]'); await w(500);
  await t('综合分析报告六段 · 发三位班长', async () => { const d = await LS('docs'); const n = await LS('notices'); return (await pg.locator('#madoc p').count()) >= 6 && d['m-all'] && n.filter(x => /综合分析报告/.test(x.t)).length >= 3; });
  await go('#madvise/trend', 700);
  await t('近五年趋势 · 四项 · 两线图 · 参谋预警', async () => (await pg.locator('.card.kpi').count()) === 4 && (await pg.locator('#main svg.ch').count()) >= 3 && (await main()).includes('人力资源配置参谋预警') && (await main()).includes('编制申请'));
  await clean('分析参谋（管理者）');
  await pg.screenshot({ path: SHOT + '/16_madvise.png' });
  /* ---------- 回到班组长：通知与计划都在 ---------- */
  await pg.click('.rsw button[data-r="leader"]'); await w(1800);
  await t('切回班组长 · 收到督办与培养提醒', async () => { const n = await LS('notices'); return (await pg.locator('#sb a').count()) === 11 && n.some(x => x.to === '赵立群' && /督办/.test(x.t)); });
  /* ---------- 讲师演示台 ---------- */
  await pg.click('.stagebtn'); await w(300);
  await pg.click('#stage [data-act="stage-status"]'); await w(300);
  await t('功能实现状态清单 四类', async () => (await pg.locator('#modal .stl').count()) === 4 && (await pg.locator('#modal').textContent()).includes('六维个人画像'));
  await pg.click('[data-act="modal-close"]');
  await pg.click('#stage [data-act="stage-ext"]'); await w(500);
  await t('扩展模块打开 · 15 项（人员档案 / 培训考评 / 安全 / 文稿）', async () => (await pg.locator('#sb a').count()) === 15);
  await pg.click('.stagebtn'); await w(200);
  console.log('FAILS', fails, 'ERR', errs.length ? errs.slice(0, 12).join('\n  ') : 'none');
  await br.close();
})();
