/* 冒烟回归：两个角色 · 主线闭环（周报驱动 → 派工带推荐/排除理由 → 审票 → 开工 → 回传 → 完工 → 实操量回写 → 画像）· 周关键节点 · 五类画像与四卡 · 知识库经验闭环 · 管理者九页 · 跨班组调配双向确认 · 刷新持久 · 界面禁词
   用法：node smoke.cjs  （需要 /home/user/-/node_modules/playwright 与 /opt/pw-browsers）期望：FAILS 0 ERR none */
const { chromium } = require(process.env.PW || '/home/user/-/node_modules/playwright');
const path = require('path');
const file = 'file://' + path.join(__dirname, 'dist', '小瓦特班_班组长AI助手_高保真原型.html');
const fs = require('fs'); const SHOT = path.join(__dirname, 'shots'); fs.mkdirSync(SHOT, { recursive: true });
const BAN = /演示|待建|下一版本|比赛|评委|一期|门禁|手术|骨架|人力资源部|上帝|发起方|所里|所长|凤凰线|塘尾线|志远站|光明变|塘家/;
(async () => {
  const br = await chromium.launch(); const ctx = await br.newContext({ viewport: { width: 1440, height: 900 } }); const pg = await ctx.newPage();
  const errs = []; pg.on('pageerror', e => errs.push('pageerror ' + e.message)); pg.on('console', m => { if (m.type() === 'error') errs.push('console ' + m.text()); });
  await pg.addInitScript(() => { window.__XW_SPEED = 0.03; });
  let fails = 0; const t = async (name, cond) => { let ok = false; try { ok = await cond(); } catch (e) { ok = false; errs.push('test ' + name + ': ' + e.message.slice(0, 160)); } console.log((ok ? 'PASS ' : 'FAIL ') + name); if (!ok) fails++; };
  const w = ms => pg.waitForTimeout(ms); const ws = async (sel, ms) => { try { await pg.waitForSelector(sel, { timeout: ms || 8000 }); } catch (e) { errs.push('wait ' + sel); } };
  const go = async (hs, ms) => { await pg.evaluate(x => { location.hash = x; }, hs); await w(ms || 500); };
  const LS = k => pg.evaluate(k => JSON.parse(localStorage.getItem('xwb_' + k) || 'null'), k);
  const main = () => pg.locator('#main').innerText();
  const clean = async (name) => { const txt = (await main()) + ' ' + (await pg.locator('#sb').innerText()) + ' ' + (await pg.locator('#chat').innerText().catch(() => '')); const m = txt.match(BAN); await t('禁词 ' + name, async () => { if (m) errs.push('ban ' + name + ': ' + m[0]); return !m; }); };
  await pg.goto(file); await w(3500);
  /* ---------- 班组长 · 今日工作台（周报驱动） ---------- */
  await t('shell 班组长 6 项', async () => (await pg.locator('#sb a').count()) === 7 && (await pg.locator('#xw').count()) === 1 && (await pg.locator('.rsw button').count()) === 2);
  await t('三张决策卡', async () => (await pg.locator('#dec .dc.in').count()) === 3 && (await pg.locator('#d1').textContent()).includes('田寮站 F02'));
  await t('周报靠后项 5 条', async () => (await pg.locator('.wkl div').count()) === 5 && (await pg.locator('#d2').textContent()).includes('第 29 期'));
  await t('六张图', async () => (await pg.locator('.charts .card.chart').count()) === 6);
  await clean('工作台');
  await pg.screenshot({ path: SHOT + '/01_home.png' });
  // 派工：四条规则 → 推荐 / 随队 / 排除理由表
  await pg.click('[data-act="home-swap"]'); await ws('#xpl.in', 20000); await w(300);
  await t('人员卡 12 · 负责人 1 · 随队 1 · 排除 9', async () => (await pg.locator('#ppl .chip').count()) === 12 && (await pg.locator('#ppl .chip.lead').count()) === 1 && (await pg.locator('#ppl .chip.fo').count()) === 1 && (await pg.locator('#ppl .chip.dim').count()) === 9);
  await t('理由表 推荐 2 · 随队 1 · 排除 9', async () => (await pg.locator('#xpl tr.in').count()) === 2 && (await pg.locator('#xpl tr.fo').count()) === 1 && (await pg.locator('#xpl tr.ex').count()) === 9 && (await pg.locator('#xpl').textContent()).includes('无电力电缆证'));
  await pg.screenshot({ path: SHOT + '/02_dispatch_rules.png' });
  await pg.click('#ppl .chip[data-who="李文博"]'); await w(900);
  await t('点排除的人 · 说理由', async () => (await pg.locator('.msg.a').last().textContent()).includes('电缆'));
  await pg.click('#ppl .chip[data-who="韩雪"]'); await w(900);
  await pg.click('[data-act="home-go"]'); await ws('#d1.ok', 20000); await w(400);
  await t('派工单落 DB · 负责人韩雪 · 理由随单', async () => { const d = await LS('dispatch'); return d && d.j1 && d.j1.lead === '韩雪' && d.j1.crew.includes('吴倩') && Array.isArray(d.j1.reasons) && d.j1.reasons.length >= 3; });
  await t('票据草稿已拟', async () => { const tk = await LS('tickets_add'); return Array.isArray(tk) && tk.some(x => x.jobId === 'j1'); });
  await pg.screenshot({ path: SHOT + '/03_dispatched.png' });
  // 周报 → 周关键节点
  await pg.click('[data-act="nodes-plan"]'); await w(2500);
  await t('周报靠后项写成本周重点', async () => { const f = await LS('nodefocus'); return Array.isArray(f) && f.length >= 3; });
  await go('#sched/nodes', 700);
  await t('关键节点 19 行 · 重点标记', async () => (await pg.locator('.t.nodes tr[data-act="node-open"]').count()) === 19 && (await pg.locator('.t.nodes tr.focus').count()) >= 3);
  await pg.click('[data-act="node-done"] >> nth=0'); await w(400);
  await t('节点勾已清 · 写 DB', async () => { const n = await LS('nodes'); return Array.isArray(n) && n.length === 1 && (await pg.locator('.t.nodes tr.done').count()) === 1; });
  await clean('用工安排 · 关键节点');
  await pg.screenshot({ path: SHOT + '/04_nodes.png' });
  // 催办（应用失败超期）
  await go('#home', 800);
  await pg.click('[data-act="urge"]'); await ws('[data-act="urge-send"]'); await pg.click('[data-act="urge-send"]'); await w(500);
  await t('催办已发 · 缺陷状态改', async () => { const d = await LS('defects'); return d && d.d5 && /催办/.test(d.d5.st); });
  /* ---------- 主线：审票 → 开工 → 回传 → 完工 → 实操量回写 ---------- */
  await go('#sched/pool', 700);
  await t('任务池 7 项 · 主线高亮', async () => (await pg.locator('.job').count()) === 7 && (await pg.locator('.job.main').count()) === 1);
  await pg.click('[data-act="job-start"][data-id="j4"]'); await ws('.msg.a [data-act="job-ticket"]');
  await t('票未审 · 拦开工', async () => (await pg.locator('.msg.a [data-act="job-ticket"]').count()) >= 1);
  await pg.click('.msg.a [data-act="job-ticket"]'); await w(800);
  await pg.click('[data-act="ticket-review"]'); await ws('[data-act="ticket-fix"]', 20000); await w(300);
  await t('审票 · 圈出缺项', async () => (await pg.locator('#tk .miss, #tk .bad').count()) >= 1);
  await pg.click('[data-act="ticket-fix"]'); await w(800);
  await t('补齐并通过 · 票已审核', async () => { const s = await LS('tickets'); return s && s['配自 2026-0807-01'] && s['配自 2026-0807-01'].st === '已审核'; });
  await pg.screenshot({ path: SHOT + '/05_ticket.png' });
  await go('#sched/pool', 700);
  await pg.click('[data-act="job-start"][data-id="j4"]'); await w(900);
  await t('开工 · 进行中 · 外勤', async () => { const st = await LS('jobst'); const ps = await LS('pstatus'); return st && st.j4 && st.j4.st === '进行中' && ps && ps['吴倩'] === '外勤'; });
  await pg.click('[data-act="job-report"][data-id="j4"]'); await w(900);
  await t('回传一条 · 进度', async () => { const g = await LS('prog'); const ov = await LS('prog_ov'); return (g && g.length) || (ov && Object.keys(ov).length); });
  await pg.click('[data-act="job-finish"][data-id="j4"]'); await w(1200);
  await t('完工 · 工时 · 票已执行', async () => { const h = await LS('hours_add'); const s = await LS('tickets'); return h && h.some(r => r.who === '吴倩' && r.d === '8-7') && s['配自 2026-0807-01'].st === '已执行'; });
  await t('实操量回写 · 九类核心技能', async () => { const sw = await LS('skillw'); const n = await LS('skill9n'); return sw && sw.length === 1 && sw[0].who.includes('吴倩') && n && n['吴倩'] && n['吴倩'][sw[0].k] === 1; });
  await t('完工话里说了回写', async () => (await pg.locator('.msg.a').last().textContent()).includes('实操量'));
  await pg.screenshot({ path: SHOT + '/06_finish.png' });
  await go('#train/write', 800);
  await t('结果回写页 · 列出回写', async () => { const txt = await main(); return txt.includes('实操量回写') && txt.includes('各 +1'); });
  await clean('培养与回写');
  await go('#train', 700);
  await t('缺口识别 · 四块', async () => { const txt = await main(); return txt.includes('资质缺口') && txt.includes('核心技能覆盖缺口') && txt.includes('实操量偏低'); });
  /* ---------- 班组画像：五类指标 · 四卡 ---------- */
  await go('#people', 800);
  await t('五类指标 5 × 3', async () => (await pg.locator('.five .fc').count()) === 5 && (await pg.locator('.five .fi').count()) === 15);
  await pg.click('.five .fi >> nth=0'); await w(600);
  await t('指标点开 · 阈值与来源', async () => (await pg.locator('.msg.a', { hasText: '阈值' }).count()) >= 1);
  await t('资质矩阵 6 类 · 核心技能覆盖', async () => (await pg.locator('table.cmx th').count()) === 7 && (await main()).includes('核心技能覆盖'));
  await pg.click('.pc[data-who="韩雪"]'); await w(3200);
  await t('四卡 · 履职证据不打分', async () => (await pg.locator('.rt').count()) === 4 && (await pg.locator('.rt[data-k="evid"]').textContent()).includes('条证据') && !/分$/.test(await pg.locator('.rt[data-k="evid"] .rv').textContent()));
  await pg.click('.rt[data-k="evid"]'); await w(500);
  await t('证据五类 · 授权说明', async () => (await pg.locator('#prate table tr').count()) === 6 && (await pg.locator('#prate .disc').count()) === 1);
  await pg.click('[data-act="evid-ok"]'); await w(400);
  await t('核对完毕 · 确认人留名', async () => { const c = await LS('confirm'); return c && c['韩雪'] && c['韩雪'].by === '赵立群'; });
  await pg.click('.rt[data-k="skill9"]'); await w(500);
  await t('九类核心技能表', async () => (await pg.locator('#prate table tr').count()) === 11);
  const setBtn = pg.locator('[data-act="skill9-set"]').first(); const sk = await setBtn.getAttribute('data-k'); const sv = await setBtn.getAttribute('data-v'); await setBtn.click(); await w(400);
  await t('资格变更 · 由班长确认', async () => { const q = await LS('skill9'); return q && q['韩雪'] && q['韩雪'][sk] === sv && (await pg.locator('.rt[data-k="skill9"] .rv .tag').textContent()).includes('/9'); });
  await pg.screenshot({ path: SHOT + '/07_people.png' });
  await clean('班组画像');
  /* ---------- 台账中心 · 周报指标 ---------- */
  await go('#ledger/weekly', 800);
  await t('周报台账 21 项', async () => (await pg.locator('#ledtable table tr').count()) === 22);
  await pg.click('u.num[data-act="wk29"][data-k="online"]'); await w(700);
  await t('周报指标点开 · 在线率', async () => (await pg.locator('.msg.a', { hasText: '99.82' }).count()) >= 1);
  await go('#ledger/skill9', 600);
  await t('核心技能台账 12 行', async () => (await pg.locator('#ledtable table tr').count()) === 13);
  await clean('台账中心');
  /* ---------- 知识库：周报案例 · 经验闭环 ---------- */
  await go('#know', 700);
  await pg.click('.kbq b >> nth=0'); await ws('#kba .src'); await w(600);
  await t('规程问答 · 出处', async () => (await pg.locator('#kbtext').textContent()).includes('2200A'));
  await pg.click('[data-act="case-new"]'); await ws('[data-act="case-save"]', 20000); await pg.click('[data-act="case-save"]'); await w(300);
  await t('案例沉淀 5 例', async () => (await pg.locator('#cases .casec').count()) === 5);
  await pg.click('[data-act="exp-use"] >> nth=0'); await w(300); await pg.click('[data-act="exp-rate"][data-v="1"] >> nth=0'); await w(300);
  await t('经验闭环 · 引用与评价', async () => { const u = await LS('expuse'); return u && u.e1 && u.e1.used === 1 && u.e1.up === 1 && (await pg.locator('#explist').textContent()).includes('引用 7 次'); });
  await clean('知识库');
  await pg.screenshot({ path: SHOT + '/08_know.png' });
  /* ---------- 刷新持久 ---------- */
  await go('#home', 300); await pg.reload(); await w(3500);
  await t('刷新后派工仍在 · 卡片已派', async () => (await pg.locator('#d1.ok').count()) === 1 && (await LS('dispatch')).j1.lead === '韩雪');
  /* ---------- 管理者 ---------- */
  await pg.click('.rsw button[data-r="manager"]'); await w(1800);
  await t('切到管理者 · 12 项 · 部门态势', async () => (await pg.locator('#sb a').count()) === 12 && (await pg.evaluate(() => location.hash)) === '#super' && (await pg.locator('.sheat .c').count()) === 15 && (await pg.locator('.teams .tc').count()) === 3);
  await t('分层不排名', async () => { const txt = await main(); return txt.includes('稳健') && txt.includes('待治理') && !txt.includes('排名第'); });
  await pg.click('.sheat .c >> nth=0'); await w(500);
  await t('热力格下钻', async () => (await pg.locator('#spot.on').count()) === 1);
  await pg.click('[data-act="unspot"]');
  await pg.click('[data-act="sup-wk"][data-k="remote"]'); await w(400);
  await t('11 局位置切换', async () => (await pg.locator('#supwk').textContent()).includes('遥控成功率'));
  await clean('部门态势');
  await pg.screenshot({ path: SHOT + '/09_super.png' });
  await go('#flow', 800);
  await t('全流程 9 格 · 任务链', async () => (await pg.locator('.flowbar > div').count()) === 9 && (await main()).includes('已执行'));
  await pg.click('.flowbar > div[data-k="write"]'); await w(500);
  await t('回写下钻', async () => (await pg.locator('#spot.on').count()) === 1);
  await pg.click('[data-act="unspot"]');
  await go('#risk', 800);
  await t('风险清单 ≥ 6', async () => (await pg.locator('#riskbody table tr').count()) >= 7);
  await pg.click('[data-act="sup-urge"]'); await w(500);
  await t('督办 → 班组长通知', async () => { const n = await LS('notices'); return n && n.some(x => x.to === '赵立群' && /督办/.test(x.t)); });
  await go('#risk/sim', 600);
  await pg.click('[data-act="sim-run"]'); await w(600);
  await t('调配模拟 · 三格影响 · 冲突', async () => (await pg.locator('.impact > div').count()) === 3 && (await main()).includes('超过约定'));
  await pg.click('[data-act="sim-alt"]'); await w(500);
  await pg.click('[data-act="sim-go"]'); await w(700);
  await t('发起调配 · 待确认 · 两位班长收通知', async () => { const tr = await LS('transfers'); const n = await LS('notices'); return tr && tr.length === 1 && tr[0].st === '待确认' && tr[0].who === '周建国' && n.filter(x => /调配待确认/.test(x.t)).length >= 2; });
  await pg.screenshot({ path: SHOT + '/10_sim.png' });
  await go('#risk/flex', 600);
  await t('柔性团队五步 · 第三步在办', async () => (await pg.locator('.steps5 > div.on').count()) === 1);
  await go('#duty', 800);
  await t('班长履职 3 行 × 7', async () => (await pg.locator('#main table').first().locator('tr').count()) === 4 && (await pg.locator('[data-act="sup-duty"]').count()) === 21);
  await pg.click('[data-act="sup-remind"] >> nth=1'); await w(400);
  await t('履职提醒发本人', async () => { const n = await LS('notices'); return n.some(x => x.to === '周建国' && /履职提醒/.test(x.t)); });
  await clean('班长履职');
  await go('#talent', 800);
  await pg.click('[data-act="tal-plan"] >> nth=0'); await w(500);
  await t('梯队建议 → 班组培养计划', async () => { const p = await LS('plan'); return p && p.some(x => x.by === '管理者建议'); });
  await go('#talent/cert', 600);
  await t('关键资质三班组表', async () => (await pg.locator('[data-act="tal-cert"]').count()) === 6);
  await go('#star', 800);
  await t('星级 8 项加权 · 64 条建设工作', async () => (await pg.locator('table.star8 tr').count()) === 10 && (await main()).includes('64 条'));
  await pg.click('[data-act="star-gap"]'); await ws('.msg.a [data-act="rep-gen"]', 20000);
  await t('差距清单', async () => (await pg.locator('.msg.a .draft').last().textContent()).includes('指标差距'));
  await pg.click('[data-act="star-prof"][data-p="om"]'); await w(500);
  await t('切配电运维口径', async () => (await main()).includes('配电运维专业') && (await main()).includes('居民端电压合格率'));
  await clean('星级对标');
  await pg.screenshot({ path: SHOT + '/11_star.png' });
  await go('#effect', 700);
  await t('组织效能 9 表 + 六维', async () => (await pg.locator('.gauge3 > div').count()) === 9 && (await pg.locator('.mets > div').count()) === 6);
  await go('#report', 700);
  await pg.click('[data-act="rep-gen"][data-k="brief"]'); await ws('#repbt button', 30000);
  await t('部门周汇报生成', async () => { const d = await LS('docs'); return d && d['sup-brief'] && (await pg.locator('#rephost p').count()) >= 5; });
  await go('#config', 700);
  await t('角色与权限 4 行 · 接入表', async () => (await pg.locator('table.perm tr').count()) === 5 && (await main()).includes('三上三下'));
  await clean('配置与权限');
  await go('#ledger/transfer', 600);
  await t('调配台账 1 行', async () => (await pg.locator('#ledtable table tr').count()) === 2);
  /* ---------- 班组长确认调配 ---------- */
  await pg.click('.rsw button[data-r="leader"]'); await w(2000);
  await t('切回班组长 · 待确认卡', async () => (await pg.locator('#trblock').count()) === 1 && (await pg.locator('#sb a').count()) === 7);
  await pg.click('[data-act="tr-ok"]'); await w(500);
  await t('班长确认 · 管理者收通知', async () => { const tr = await LS('transfers'); const n = await LS('notices'); return tr[0].st === '已确认' && n.some(x => x.to === '陈国安' && /已确认/.test(x.t)); });
  await go('#sched/pool', 600);
  await t('确认后待确认卡消失', async () => (await pg.locator('#trblock').count()) === 0);
  await pg.screenshot({ path: SHOT + '/12_leader_after.png' });
  /* ---------- 讲师演示台 ---------- */
  await pg.click('.stagebtn'); await w(300);
  await t('讲师演示台 · 角色 · 扩展模块 · 状态清单', async () => (await pg.locator('#stage.on').count()) === 1 && (await pg.locator('#stage [data-act="stage-ext"]').count()) === 1 && (await pg.locator('#stage [data-act="stage-status"]').count()) === 1);
  await pg.click('#stage [data-act="stage-ext"]'); await w(500);
  await t('扩展模块打开 · 8 项', async () => (await pg.locator('#sb a').count()) === 9);
  await pg.click('.stagebtn'); await w(200);
  console.log('FAILS', fails, 'ERR', errs.length ? errs.slice(0, 12).join('\n  ') : 'none');
  await br.close();
})();
