/* ===== 上传两票：真实读取 Word / Excel / 文本（zip + DecompressionStream，纯浏览器离线），解析票面，按规则审核 ===== */
const UPLOAD = {
  async read(file) { const name = file.name; const ext = (name.split('.').pop() || '').toLowerCase(); if (/^(png|jpe?g|webp|gif|bmp)$/.test(ext)) return { name, kind: 'image', dataUrl: await this.dataUrl(file), text: '' }; if (ext === 'pdf') return { name, kind: 'pdf', text: '' }; if (ext === 'docx') return { name, kind: 'docx', text: await this.docx(file) }; if (ext === 'xlsx') return { name, kind: 'xlsx', text: await this.xlsx(file) }; return { name, kind: 'text', text: await file.text() }; },
  dataUrl(file) { return new Promise(r => { const fr = new FileReader(); fr.onload = () => r(fr.result); fr.readAsDataURL(file); }); },
  /* ---- zip：中央目录 → 条目 → deflate-raw 解压 ---- */
  async zipEntries(buf) { const dv = new DataView(buf); const u8 = new Uint8Array(buf); let eocd = -1; for (let i = buf.byteLength - 22; i >= Math.max(0, buf.byteLength - 66000); i--) { if (dv.getUint32(i, true) === 0x06054b50) { eocd = i; break; } } if (eocd < 0) throw new Error('不是有效的压缩文档'); const n = dv.getUint16(eocd + 10, true); let off = dv.getUint32(eocd + 16, true); const out = {}; const td = new TextDecoder();
    for (let i = 0; i < n; i++) { if (dv.getUint32(off, true) !== 0x02014b50) break; const method = dv.getUint16(off + 10, true), csize = dv.getUint32(off + 20, true), nlen = dv.getUint16(off + 28, true), elen = dv.getUint16(off + 30, true), clen = dv.getUint16(off + 32, true), loc = dv.getUint32(off + 42, true); const nm = td.decode(u8.subarray(off + 46, off + 46 + nlen)); out[nm] = { method, csize, loc }; off += 46 + nlen + elen + clen; }
    return { entries: out, u8, dv }; },
  async zipRead(z, name) { const e = z.entries[name]; if (!e) return null; const dv = z.dv; const nlen = dv.getUint16(e.loc + 26, true), elen = dv.getUint16(e.loc + 28, true); const start = e.loc + 30 + nlen + elen; const data = z.u8.subarray(start, start + e.csize); if (e.method === 0) return new TextDecoder().decode(data); const ds = new DecompressionStream('deflate-raw'); const w = ds.writable.getWriter(); w.write(data); w.close(); const buf = await new Response(ds.readable).arrayBuffer(); return new TextDecoder().decode(buf); },
  async docx(file) { const z = await this.zipEntries(await file.arrayBuffer()); const xml = await this.zipRead(z, 'word/document.xml'); if (!xml) throw new Error('Word 文档里没有正文'); const lines = []; const body = xml.split(/<w:tbl>|<\/w:tbl>/);
    const para = s => (s.match(/<w:p[ >][\s\S]*?<\/w:p>/g) || []).map(p => (p.match(/<w:t[^>]*>([^<]*)<\/w:t>/g) || []).map(t => t.replace(/<[^>]+>/g, '')).join('')).filter(t => t.trim());
    body.forEach((seg, i) => { if (i % 2 === 0) lines.push.apply(lines, para(seg)); else (seg.match(/<w:tr[ >][\s\S]*?<\/w:tr>/g) || []).forEach(tr => { const cells = (tr.match(/<w:tc[ >][\s\S]*?<\/w:tc>/g) || []).map(tc => para(tc).join(' ')); lines.push(cells.join(' | ')); }); });
    return lines.map(l => l.replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"')).join('\n'); },
  async xlsx(file) { const z = await this.zipEntries(await file.arrayBuffer()); const ss = await this.zipRead(z, 'xl/sharedStrings.xml'); const strs = ss ? (ss.match(/<si>[\s\S]*?<\/si>/g) || []).map(si => (si.match(/<t[^>]*>([^<]*)<\/t>/g) || []).map(t => t.replace(/<[^>]+>/g, '')).join('')) : []; const sheet = await this.zipRead(z, 'xl/worksheets/sheet1.xml'); if (!sheet) throw new Error('Excel 里没有工作表'); const rows = (sheet.match(/<row[ >][\s\S]*?<\/row>/g) || []).map(r => (r.match(/<c [^>]*?(?:\/>|>[\s\S]*?<\/c>)/g) || []).map(c => { const t = (c.match(/ t="([^"]+)"/) || [])[1]; const v = (c.match(/<v>([^<]*)<\/v>/) || [])[1]; const is = (c.match(/<is><t[^>]*>([^<]*)<\/t>/) || [])[1]; if (is != null) return is; if (v == null) return ''; return t === 's' ? (strs[+v] || '') : v; }).filter(x => x !== '').join(' | ')).filter(r => r.trim());
    return rows.map(l => l.replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')).join('\n'); },
  /* ---- 解析票面 ---- */
  parse(text, name) { const lines = text.split(/\r?\n/).map(l => l.trim()).filter(Boolean); const all = lines.join('\n'); const flat = all.replace(/\s/g, ''); const kind = /操作票/.test(flat) ? '操作票' : /第一种工作票/.test(flat) ? '第一种工作票' : /第二种工作票/.test(flat) ? '第二种工作票' : /工作票/.test(flat) ? '工作票' : '未知';
    const field = re => { const m = all.match(re); return m ? m[1].replace(/[|]/g, '').replace(/\s{2,}.*$/, '').trim() : ''; };
    const f = { no: field(/编号[:：][ \t]*([^|\n]+)/), unit: field(/单位[:：][ \t]*([^|\n]+)/), issuer: field(/发令人[:：][ \t]*([^|\n]*)/), receiver: field(/受令人[:：][ \t]*([^|\n]*)/), issueTime: field(/发令时间[:：][ \t]*([^|\n]+)/), start: field(/操作开始时间[:：][ \t]*([^|\n]+)/), task: field(/(?:操作任务|工作任务|工作内容)[:：][ \t]*([^|\n]+)/), operator: field(/操作人[:：][ \t]*([^|\n]*)/), guard: field(/监护人[:：][ \t]*([^|\n]*)/), duty: field(/(?:值班负责人|值长)[^:：\n]*[:：][ \t]*([^|\n]*)/), lead: field(/工作负责人[^:：\n]*[:：][ \t]*([^|\n]*)/), crew: field(/(?:工作班成员|班员)[:：][ \t]*([^|\n]+)/), remark: field(/备注[:：][ \t]*([^|\n]+)/) };
    Object.keys(f).forEach(k => { if (/^[\s年月日时分]*$/.test(f[k])) f[k] = ''; });
    const items = []; lines.forEach(l => { const m = l.match(/^(\d{1,2})\s*[.、．|]\s*(.+)$/) || l.match(/^(\d{1,2})\s*\|\s*(.+)$/); if (m && !/^(\d{4})/.test(l)) { const parts = m[2].split('|').map(s => s.trim()).filter(Boolean); items.push({ n: +m[1], text: parts[0], done: parts.slice(1).some(p => /√|✓|执行|是/.test(p)) }); } });
    return { kind, f, items, raw: lines, name }; },
  /* ---- 审核：操作票按倒闸操作规则，工作票按安措要素 ---- */
  audit(t) { const iss = [], ok = []; const has = re => t.items.findIndex(i => re.test(i.text)); const push = (lv, rule, text, idx) => iss.push({ lv, rule, text, idx });
    if (t.kind === '操作票') {
      ['no|编号', 'issuer|发令人', 'receiver|受令人', 'issueTime|发令时间', 'task|操作任务', 'operator|操作人', 'guard|监护人'].forEach(s => { const [k, n] = s.split('|'); if (!t.f[k]) push('缺', '票面要素', n + '未填写'); else ok.push(n + ' ' + t.f[k]); });
      if (!t.items.length) { push('错', '操作项目', '没有解析到操作项目'); return { iss, ok }; }
      const power = /由运行转检修|停电|转检修|转冷备用/.test(t.f.task); const open = has(/断开.*?(开关|断路器)/), pullLoad = has(/拉开.*?(负荷侧|线路侧).*?(隔离开关|刀闸)/), pullSrc = has(/拉开.*?(电源侧|母线侧).*?(隔离开关|刀闸)/), pull = has(/拉开.*?(隔离开关|刀闸)/), test = has(/验电/), gnd = has(/(合上|装设).*?(接地|地刀)/), sign = has(/标示牌|标志牌/), chk = has(/检查.*?(确已|位置|分闸|断开)/), report = has(/汇报/);
      if (power) { if (open < 0) push('缺', '操作顺序', '停电操作缺"断开开关（断路器）"一项'); if (pull >= 0 && open >= 0 && pull < open) push('错', '操作顺序', '第 ' + t.items[pull].n + ' 项先拉开了隔离开关，第 ' + t.items[open].n + ' 项才断开开关——顺序反了，隔离开关不能带负荷拉合，应先断开开关再拉隔离开关', pull); else if (open >= 0 && pull >= 0) ok.push('先断开开关、后拉隔离开关，顺序正确'); if (pullLoad >= 0 && pullSrc >= 0 && pullSrc < pullLoad) push('错', '操作顺序', '停电应先拉负荷侧隔离开关、再拉电源侧，票面顺序相反', pullSrc); else if (pullLoad >= 0 && pullSrc >= 0) ok.push('先负荷侧、后电源侧隔离开关，顺序正确'); }
      if (gnd >= 0 && test < 0) push('缺', '验电', '第 ' + t.items[gnd].n + ' 项合接地开关（装设接地线）之前没有验电项，必须先验明无电', gnd); else if (gnd >= 0 && test > gnd) push('错', '验电', '验电排在了接地之后（第 ' + t.items[test].n + ' 项），应在第 ' + t.items[gnd].n + ' 项之前', test); else if (gnd >= 0 && test >= 0) ok.push('验电在接地之前');
      if (gnd >= 0 && !/[#＃]\s*\d|编号|[A-Z]\d+-\d|F\d{2}-\d/.test(t.items[gnd].text)) push('缺', '接地编号', '第 ' + t.items[gnd].n + ' 项接地开关（接地线）没有写编号或位置', gnd); else if (gnd >= 0) ok.push('接地开关编号已写明');
      if (gnd < 0 && power) push('缺', '接地', '停电转检修没有合接地开关（装设接地线）的项目');
      if (sign < 0) push('缺', '标示牌', '没有悬挂"禁止合闸，线路有人工作"标示牌的项目'); else ok.push('标示牌已列');
      if (open >= 0 && chk < 0) push('提示', '检查项', '断开开关后缺"检查确已断开"的检查项'); else if (chk >= 0) ok.push('操作后有检查项');
      if (report < 0) push('提示', '汇报', '缺"向配调汇报操作完毕"一项'); else ok.push('操作完毕汇报已列');
      const und = t.items.filter(i => !i.done).length; if (und === t.items.length) push('提示', '执行栏', '执行栏全部为空，按未执行票审核');
    } else {
      ['no|编号', 'lead|工作负责人', 'task|工作任务'].forEach(s => { const [k, n] = s.split('|'); if (!t.f[k]) push('缺', '票面要素', n + '未填写'); else ok.push(n + ' ' + t.f[k]); });
      const txt = t.items.map(i => i.text).join('\n') + '\n' + t.raw.join('\n'); const need = [['停电|分闸', '停电（开关分闸）'], ['验电', '验电'], ['接地', '装设接地线'], ['标示牌|标志牌', '悬挂标示牌'], ['围栏', '装设围栏']]; need.forEach(([re, n]) => { if (!new RegExp(re).test(txt)) push('缺', '安全措施', '安措里没有"' + n + '"'); else ok.push(n); });
      const gi = has(/接地/); if (gi >= 0 && !/[#＃]\s*\d|档|编号/.test(t.items[gi].text)) push('缺', '接地位置', '接地线没有写装设位置（档位或编号）', gi);
      const ti = has(/验电/); if (gi >= 0 && ti >= 0 && ti > gi) push('错', '顺序', '验电应在装设接地线之前', ti);
    }
    return { iss, ok }; },
  /* ---- 补齐：把缺项写进票面 ---- */
  fix(t, res) { const items = t.items.slice(); const ins = []; res.iss.forEach(i => { if (i.rule === '验电') { const gi = items.findIndex(x => /(合上|装设).*?(接地|地刀)/.test(x.text)); if (gi >= 0 && !items.some(x => /验电/.test(x.text))) ins.push([gi, '在' + (t.f.task.match(/F\d{2}|#\d+|[^\s，,由]+开关/) || ['设备'])[0] + '线路侧验电，确认三相无电']); } if (i.rule === '接地编号' && i.idx != null) items[i.idx] = Object.assign({}, items[i.idx], { text: items[i.idx].text.replace(/接地开关|接地线/, m => m + '（' + ((t.f.task || '').match(/F\d{2}/) || ['接地'])[0] + '-4）') }); if (i.rule === '标示牌' && i.text.includes('没有')) ins.push([items.length, '在开关操作把手上悬挂"禁止合闸，线路有人工作！"标示牌']); if (i.rule === '操作顺序' && i.lv === '错' && i.idx != null) { const oi = items.findIndex(x => /断开.*?(开关|断路器)/.test(x.text)); if (oi > i.idx) { const [o] = items.splice(oi, 1); items.splice(i.idx, 0, o); } } if (i.rule === '票面要素' && /监护人/.test(i.text)) t.f.guard = '韩雪'; if (i.rule === '汇报') ins.push([items.length, '检查现场安措布置完毕，向配调汇报操作完毕']); });
    ins.sort((a, b) => b[0] - a[0]).forEach(([at, text]) => items.splice(at, 0, { text, done: false, added: true })); items.forEach((x, i) => x.n = i + 1); t.items = items; return t; }
};
